var searchData=
[
  ['sauterquadorder_0',['SauterQuadOrder',['../structSauterQuadOrder.html',1,'']]],
  ['sauterquadraturerule_1',['SauterQuadratureRule',['../structSauterQuadratureRule.html',1,'']]],
  ['sauterquadraturetaskbufferforvector_2',['SauterQuadratureTaskBufferForVector',['../classCUDAWrappers_1_1SauterQuadratureTaskBufferForVector.html',1,'CUDAWrappers']]],
  ['sauterquadraturetaskringbuffer_3',['SauterQuadratureTaskRingBuffer',['../classCUDAWrappers_1_1SauterQuadratureTaskRingBuffer.html',1,'CUDAWrappers']]],
  ['sauterquadraturetaskscalardata_4',['SauterQuadratureTaskScalarData',['../classCUDAWrappers_1_1SauterQuadratureTaskScalarData.html',1,'CUDAWrappers']]],
  ['schurcomplement_5',['SchurComplement',['../classSchurComplement.html',1,'']]],
  ['sequencepartitioner_6',['SequencePartitioner',['../classSequencePartitioner.html',1,'']]],
  ['simpleboundingbox_7',['SimpleBoundingBox',['../classSimpleBoundingBox.html',1,'']]],
  ['simpleboundingbox_3c_20spacedim_2c_20double_20_3e_8',['SimpleBoundingBox&lt; spacedim, double &gt;',['../classSimpleBoundingBox.html',1,'']]],
  ['simpleboundingbox_3c_20spacedim_2c_20real_5ftype_20_3e_9',['SimpleBoundingBox&lt; spacedim, real_type &gt;',['../classSimpleBoundingBox.html',1,'']]],
  ['singlelayerkernel_10',['SingleLayerKernel',['../classPlatformShared_1_1HelmholtzAcousticKernel_1_1SingleLayerKernel.html',1,'PlatformShared::HelmholtzAcousticKernel::SingleLayerKernel&lt; spacedim, KernelNumberType &gt;'],['../classPlatformShared_1_1LaplaceKernel_1_1SingleLayerKernel.html',1,'PlatformShared::LaplaceKernel::SingleLayerKernel&lt; spacedim, KernelNumberType &gt;']]],
  ['singlelayerkernel_3c_20spacedim_2c_20devicenumbertype_3c_20kernelnumbertype_20_3e_20_3e_11',['SingleLayerKernel&lt; spacedim, DeviceNumberType&lt; KernelNumberType &gt; &gt;',['../classPlatformShared_1_1HelmholtzAcousticKernel_1_1SingleLayerKernel.html',1,'PlatformShared::HelmholtzAcousticKernel']]],
  ['singlelayerpreconditioner_12',['SingleLayerPreconditioner',['../classSingleLayerPreconditioner.html',1,'']]],
  ['solverbicgstabgeneral_13',['SolverBicgstabGeneral',['../classSolverBicgstabGeneral.html',1,'']]],
  ['solvercggeneral_14',['SolverCGGeneral',['../classSolverCGGeneral.html',1,'']]],
  ['solverdqgmres_15',['SolverDQGMRES',['../classSolverDQGMRES.html',1,'']]],
  ['subdomainhmatrixforchargeneutralityeqn_16',['SubdomainHMatrixForChargeNeutralityEqn',['../classSubdomainHMatrixForChargeNeutralityEqn.html',1,'']]],
  ['subdomainhmatrixforglobalpreconditioning_17',['SubdomainHMatrixForGlobalPreconditioning',['../classSubdomainHMatrixForGlobalPreconditioning.html',1,'']]],
  ['subdomainhmatrixfortransmissioneqn_18',['SubdomainHMatrixForTransmissionEqn',['../classSubdomainHMatrixForTransmissionEqn.html',1,'']]],
  ['subdomainsteklovpoincarehmatrix_19',['SubdomainSteklovPoincareHMatrix',['../classSubdomainSteklovPoincareHMatrix.html',1,'']]],
  ['subdomainsteklovpoincarehmatrix_3c_20spacedim_2c_20double_20_3e_20',['SubdomainSteklovPoincareHMatrix&lt; spacedim, double &gt;',['../classSubdomainSteklovPoincareHMatrix.html',1,'']]],
  ['subdomaintopology_21',['SubdomainTopology',['../classSubdomainTopology.html',1,'']]],
  ['surfacenormaldetector_22',['SurfaceNormalDetector',['../classSurfaceNormalDetector.html',1,'']]]
];
