HierBEM: include/hmatrix/aca_plus/aca_plus.hcu File Reference
aca_plus.hcu File Reference
Implement the ACA+ method proposed in Grasedyck, L. 2005. “Adaptive Recompression of \(\mathscr{H}\)-Matrices for BEM.” Computing 74 (3): 205–23.
#include <deal.II/base/logstream.h>
#include <deal.II/base/numbers.h>
#include <deal.II/base/parallel.h>
#include <deal.II/base/timer.h>
#include <deal.II/base/types.h>
#include <deal.II/fe/fe_update_flags.h>
#include <deal.II/lac/vector.h>
#include <cuda_runtime.h>
#include <tbb/tbb.h>
#include <algorithm>
#include <chrono>
#include <cmath>
#include <complex>
#include <condition_variable>
#include <cstdint>
#include <forward_list>
#include <functional>
#include <iostream>
#include <iterator>
#include <mutex>
#include <random>
#include <thread>
#include <type_traits>
#include <utility>
#include <vector>
#include "bem/bem_kernels.hcu"
#include "bem/bem_tools.h"
#include "bem/cu_bem_values.hcu"
#include "config.h"
#include "hmatrix/aca_plus/aca_config.h"
#include "hmatrix/hmatrix.h"
#include "linear_algebra/cu_table.hcu"
#include "linear_algebra/lapack_full_matrix_ext.h"
#include "linear_algebra/linalg.h"
#include "mapping/mapping_info.h"
#include "quadrature/sauter_quadrature.hcu"
#include "sequence_partition/sequence_partition.h"
#include "utilities/debug_tools.h"
#include "utilities/generic_functors.h"
#include "utilities/number_traits.h"
#include "utilities/unary_template_arg_containers.h"
Typedefs
using size_type = std::make_unsigned< types::blas_int >::type
Functions
size_type generate_random_index (const size_type a, const size_type b)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void assemble_kernel_row (Vector< RangeNumberType > &row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const types::global_dof_index row_dof_index, const std::vector< types::global_dof_index > &column_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const DoFHandler< dim, spacedim > &kx_dof_handler, const DoFHandler< dim, spacedim > &ky_dof_handler, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > &scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void assemble_kernel_row (Vector< RangeNumberType > &row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, const types::global_dof_index row_dof_index, const std::vector< types::global_dof_index > &column_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const DoFHandler< dim, spacedim > &kx_dof_handler, const DoFHandler< dim, spacedim > &ky_dof_handler, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > &scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void assemble_kernel_row (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > &task_buffer, Vector< RangeNumberType > &row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const types::global_dof_index row_dof_index, const std::vector< types::global_dof_index > &column_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void assemble_kernel_row (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > &task_buffer, Vector< RangeNumberType > &row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, const types::global_dof_index row_dof_index, const std::vector< types::global_dof_index > &column_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void assemble_kernel_column (Vector< RangeNumberType > &col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< types::global_dof_index > &row_dof_indices, const types::global_dof_index col_dof_index, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > &scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void assemble_kernel_column (Vector< RangeNumberType > &col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, const std::vector< types::global_dof_index > &row_dof_indices, const types::global_dof_index col_dof_index, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > &scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void assemble_kernel_column (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > &task_buffer, Vector< RangeNumberType > &col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< types::global_dof_index > &row_dof_indices, const types::global_dof_index col_dof_index, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void assemble_kernel_column (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > &task_buffer, Vector< RangeNumberType > &col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, const std::vector< types::global_dof_index > &row_dof_indices, const types::global_dof_index col_dof_index, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
size_type random_select_ref_row (Vector< RangeNumberType > &row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, std::forward_list< size_type > &remaining_row_indices, const size_type current_ref_row_index, const size_type pass_the_end_ref_row_index, const std::vector< types::global_dof_index > &row_dof_indices, const std::vector< types::global_dof_index > &col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > &scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
size_type random_select_ref_row (Vector< RangeNumberType > &row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, std::forward_list< size_type > &remaining_row_indices, const size_type current_ref_row_index, const size_type pass_the_end_ref_row_index, const std::vector< types::global_dof_index > &row_dof_indices, const std::vector< types::global_dof_index > &col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > &scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
size_type random_select_ref_row (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > &task_buffer, Vector< RangeNumberType > &row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, std::forward_list< size_type > &remaining_row_indices, const size_type current_ref_row_index, const size_type pass_the_end_ref_row_index, const std::vector< types::global_dof_index > &row_dof_indices, const std::vector< types::global_dof_index > &col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
size_type random_select_ref_row (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > &task_buffer, Vector< RangeNumberType > &row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, std::forward_list< size_type > &remaining_row_indices, const size_type current_ref_row_index, const size_type pass_the_end_ref_row_index, const std::vector< types::global_dof_index > &row_dof_indices, const std::vector< types::global_dof_index > &col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<typename RangeNumberType = double>
size_type random_select_ref_row (Vector< RangeNumberType > &row_vector, const LAPACKFullMatrixExt< RangeNumberType > &A, std::forward_list< size_type > &remaining_row_indices, const size_type current_ref_row_index, const size_type pass_the_end_ref_row_index)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
size_type random_select_ref_column (Vector< RangeNumberType > &col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > factor, std::forward_list< size_type > &remaining_col_indices, const size_type current_ref_col_index, const size_type pass_the_end_ref_col_index, const std::vector< types::global_dof_index > &row_dof_indices, const std::vector< types::global_dof_index > &col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > &scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
size_type random_select_ref_column (Vector< RangeNumberType > &col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, std::forward_list< size_type > &remaining_col_indices, const size_type current_ref_col_index, const size_type pass_the_end_ref_col_index, const std::vector< types::global_dof_index > &row_dof_indices, const std::vector< types::global_dof_index > &col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > &scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
size_type random_select_ref_column (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > &task_buffer, Vector< RangeNumberType > &col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > factor, std::forward_list< size_type > &remaining_col_indices, const size_type current_ref_col_index, const size_type pass_the_end_ref_col_index, const std::vector< types::global_dof_index > &row_dof_indices, const std::vector< types::global_dof_index > &col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
size_type random_select_ref_column (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > &task_buffer, Vector< RangeNumberType > &col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, std::forward_list< size_type > &remaining_col_indices, const size_type current_ref_col_index, const size_type pass_the_end_ref_col_index, const std::vector< types::global_dof_index > &row_dof_indices, const std::vector< types::global_dof_index > &col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<typename RangeNumberType = double>
size_type random_select_ref_column (Vector< RangeNumberType > &col_vector, const LAPACKFullMatrixExt< RangeNumberType > &A, std::forward_list< size_type > &remaining_col_indices, const size_type current_ref_col_index, const size_type pass_the_end_ref_col_index)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void aca_plus_parallel_sauter_quad_for_vector_entry (RkMatrix< RangeNumberType > &rkmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::array< types::global_dof_index, 2 > &row_dof_index_range, const std::array< types::global_dof_index, 2 > &col_dof_index_range, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > &scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void aca_plus_parallel_sauter_quad_for_vector_entry (RkMatrix< RangeNumberType > &rkmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, KernelNumberType > &kernel, const KernelNumberType kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, const std::array< types::global_dof_index, 2 > &row_dof_index_range, const std::array< types::global_dof_index, 2 > &col_dof_index_range, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void aca_plus_parallel_sauter_quad_for_whole_vector (RkMatrix< RangeNumberType > &rkmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::array< types::global_dof_index, 2 > &row_dof_index_range, const std::array< types::global_dof_index, 2 > &col_dof_index_range, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const BEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void aca_plus_parallel_sauter_quad_for_whole_vector (RkMatrix< RangeNumberType > &rkmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, KernelNumberType > &kernel, const KernelNumberType kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, const std::array< types::global_dof_index, 2 > &row_dof_index_range, const std::array< types::global_dof_index, 2 > &col_dof_index_range, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const BEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data)
template<typename RangeNumberType = double>
void aca_plus (RkMatrix< RangeNumberType > &rkmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const LAPACKFullMatrixExt< RangeNumberType > &A)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void fill_hmatrix_leaf_node_with_aca_plus (HMatrix< spacedim, RangeNumberType > *leaf_mat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const DoFHandler< dim, spacedim > &kx_dof_handler, const DoFHandler< dim, spacedim > &ky_dof_handler, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > &scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data, const bool enable_build_symmetric_hmat=false)
Fill a single leaf node of the \(\mathcal{H}\)-matrix using ACA+. If the matrix type is RkMatrixType, the memory for the full or rank-k matrix in the leaf node has been allocated.
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void fill_hmatrix_leaf_node_with_aca_plus (HMatrix< spacedim, RangeNumberType > *leaf_mat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const DoFHandler< dim, spacedim > &kx_dof_handler, const DoFHandler< dim, spacedim > &ky_dof_handler, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > &scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data, const bool enable_build_symmetric_hmat=false)
Fill a single leaf node of the \(\mathcal{H}\)-matrix using ACA+. If the matrix type is RkMatrixType, the memory for the full or rank-k matrix in the leaf node has been allocated.
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void fill_hmatrix_leaf_node_with_aca_plus (HMatrix< spacedim, RangeNumberType > *leaf_mat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const typename numbers::NumberTraits< RangeNumberType >::real_type mass_matrix_factor, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const DoFHandler< dim, spacedim > &kx_dof_handler, const DoFHandler< dim, spacedim > &ky_dof_handler, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, CellWiseScratchDataForMassMatrix< dim, spacedim > &mass_matrix_scratch_data, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > &scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data, const bool enable_build_symmetric_hmat=false)
Fill a single leaf node of the \(\mathcal{H}\)-matrix using ACA+.
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void fill_far_field_hmatrix_leaf_node_with_aca_plus (HMatrix< spacedim, RangeNumberType > *leaf_mat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const BEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data, const bool enable_build_symmetric_hmat=false)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void fill_far_field_hmatrix_leaf_node_with_aca_plus (HMatrix< spacedim, RangeNumberType > *leaf_mat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const BEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > &scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > &copy_data, const bool enable_build_symmetric_hmat=false)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void fill_far_field_hmatrix_leaf_node_subrange_with_aca_plus (const tbb::blocked_range< typename std::vector< HMatrix< spacedim, RangeNumberType > * >::iterator > &range, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const BEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const DoFHandler< dim, spacedim > &kx_dof_handler, const DoFHandler< dim, spacedim > &ky_dof_handler, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, const bool enable_build_symmetric_hmat=false)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void fill_far_field_hmatrix_leaf_node_subrange_with_aca_plus (const tbb::blocked_range< typename std::vector< HMatrix< spacedim, RangeNumberType > * >::iterator > &range, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const BEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > &bem_values_gpu, const DoFHandler< dim, spacedim > &kx_dof_handler, const DoFHandler< dim, spacedim > &ky_dof_handler, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, const bool enable_build_symmetric_hmat=false)
template<int spacedim, typename RangeNumberType , typename KernelNumberType >
void stabilize_near_field_hmatrices_for_hypersingular_kernel (const tbb::blocked_range< typename std::vector< HMatrix< spacedim, RangeNumberType > * >::iterator > &range, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, const bool enable_build_symmetric_hmat=true)
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void fill_hmatrix_with_aca_plus_serial (HMatrix< spacedim, RangeNumberType > &hmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, KernelNumberType > &kernel, const KernelNumberType kernel_factor, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const SauterQuadratureRule< dim > &sauter_quad_rule, const DoFHandler< dim, spacedim > &kx_dof_handler, const DoFHandler< dim, spacedim > &ky_dof_handler, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, const bool enable_build_symmetric_hmat=false)
Fill the leaf set of the \(\mathcal{H}\)-matrix using ACA+, where the hierarchical structure of the \(\mathcal{H}\)-matrix has been built with respect to a block cluster tree and the memory for the matrices in the leaf set has been allocated.
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void fill_hmatrix_with_aca_plus_serial (HMatrix< spacedim, RangeNumberType > &hmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, KernelNumberType > &kernel, const KernelNumberType kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const SauterQuadratureRule< dim > &sauter_quad_rule, const DoFHandler< dim, spacedim > &kx_dof_handler, const DoFHandler< dim, spacedim > &ky_dof_handler, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, const bool enable_build_symmetric_hmat=false)
Fill the leaf set of the \(\mathcal{H}\)-matrix using ACA+, where the hierarchical structure of the \(\mathcal{H}\)-matrix has been built with respect to a block cluster tree and the memory for the matrices in the leaf set has been allocated.
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void fill_hmatrix_with_aca_plus_serial (HMatrix< spacedim, RangeNumberType > &hmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, KernelNumberType > &kernel, const KernelNumberType kernel_factor, const typename numbers::NumberTraits< RangeNumberType >::real_type mass_matrix_factor, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const SauterQuadratureRule< dim > &sauter_quad_rule, const QGauss< dim > &mass_matrix_quadrature_formula, const DoFHandler< dim, spacedim > &kx_dof_handler, const DoFHandler< dim, spacedim > &ky_dof_handler, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, const bool enable_build_symmetric_hmat=false)
Fill the leaf set of the \(\mathcal{H}\)-matrix using ACA+, where the hierarchical structure of the \(\mathcal{H}\)-matrix has been built with respect to a block cluster tree and the memory for the matrices in the leaf set has been allocated.
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void fill_hmatrix_with_aca_plus_smp (const unsigned int thread_num, HMatrix< spacedim, RangeNumberType > &hmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const SauterQuadratureRule< dim > &sauter_quad_rule, const DoFHandler< dim, spacedim > &kx_dof_handler, const DoFHandler< dim, spacedim > &ky_dof_handler, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, const bool enable_build_symmetric_hmat=false)
Fill the leaf set of the \(\mathcal{H}\)-matrix using ACA+, where the hierarchical structure of the \(\mathcal{H}\)-matrix has been built with respect to a block cluster tree and the memory for the matrices in the leaf set has been allocated.
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void fill_hmatrix_with_aca_plus_smp (const unsigned int thread_num, HMatrix< spacedim, RangeNumberType > &hmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > &mass_vmult_weq, const KernelNumberType stabilization_factor, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const SauterQuadratureRule< dim > &sauter_quad_rule, const DoFHandler< dim, spacedim > &kx_dof_handler, const DoFHandler< dim, spacedim > &ky_dof_handler, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, const bool enable_build_symmetric_hmat=false)
Fill the leaf set of the \(\mathcal{H}\)-matrix using ACA+, where the hierarchical structure of the \(\mathcal{H}\)-matrix has been built with respect to a block cluster tree and the memory for the matrices in the leaf set has been allocated.
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector >
void fill_hmatrix_with_aca_plus_smp (const unsigned int thread_num, HMatrix< spacedim, RangeNumberType > &hmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > &aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > &kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const typename numbers::NumberTraits< RangeNumberType >::real_type mass_matrix_factor, const DoFToCellTopology< dim, spacedim > &kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > &ky_dof_to_cell_topo, const SauterQuadratureRule< dim > &sauter_quad_rule, const QGauss< dim > &mass_matrix_quadrature_formula, const DoFHandler< dim, spacedim > &kx_dof_handler, const DoFHandler< dim, spacedim > &ky_dof_handler, const std::vector< types::global_dof_index > *kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > *ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > &kx_dof_i2e_numbering, const std::vector< types::global_dof_index > &ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const std::map< types::material_id, unsigned int > &material_id_to_mapping_index, const SurfaceNormalDetector &normal_detector, const bool enable_build_symmetric_hmat=false)
Fill the leaf set of the \(\mathcal{H}\)-matrix using ACA+, where the hierarchical structure of the \(\mathcal{H}\)-matrix has been built with respect to a block cluster tree and the memory for the matrices in the leaf set has been allocated.
Variables
std::mt19937 rand_engine
Detailed Description
Implement the ACA+ method proposed in Grasedyck, L. 2005. “Adaptive Recompression of \(\mathscr{H}\)-Matrices for BEM.” Computing 74 (3): 205–23.
Date
2022-03-07
Author
Jihuan Tian
Definition in file aca_plus.hcu.
Macro Definition Documentation
HIERBEM_INCLUDE_HMATRIX_ACA_PLUS_ACA_PLUS_H_
#define HIERBEM_INCLUDE_HMATRIX_ACA_PLUS_ACA_PLUS_H_
Definition at line 21 of file aca_plus.hcu.
Typedef Documentation
size_type
using size_type = std::make_unsigned<types::blas_int>::type
The type used for matrix row and column indices.
Definition at line 90 of file aca_plus.hcu.
Function Documentation
aca_plus()
template<typename RangeNumberType = double> void aca_plus (RkMatrix< RangeNumberType > & rkmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const LAPACKFullMatrixExt< RangeNumberType > & A)
ACA+ algorithm for verification purpose. The matrix for the current block is passed in as a full matrix without kernel function evaluation.
Grasedyck, L. 2005. “Adaptive Recompression of \(\mathcal{H}\)-Matrices for BEM.” Computing 74 (3): 205–23.}
Parameters
rkmat The rank-k matrix to be constructed for the current block, the memory of which should be preallocated and the formal rank of which should be the same as the maximum iteration number in aca_config.
aca_config
A The full matrix to be approximated
Get the size of each dimension of the matrix block to be built.
Create matrix references associated with the component matrices in the rank-k matrix to be returned, which hold the row and column vectors in the selected crosses during the ACA iteration. The number of columns should be the same as the maximum iteration number in aca_config.
Generate two lists for storing remaining row indices and column indices of the matrix block.
Select the initial reference row and column vectors and return their matrix indices.
The absolute values for the reference row and column vectors.
Calculate the absolute values for the reference row and column vectors.
Note
In the following, we use static_cast to explicitly specify which version of std::abs to call.
Row and column indices for the \(k\)'th step. The corresponding row and column vectors comprise the cross.
Temporary row and column vectors for the current step \(k\).
The absolute values for the temporary row and column vectors for the current step \(k\).
Temporary row and column vectors for the previous step \(l\).
Start the ACA+ iteration from \(k=1\).
Select the row index from the maximizer of the reference column.
Select the column index from the maximizer of the reference row.
Select \(i^*\) as the current row index \(i_k\).
Extract the \(i_k\)'th row of \(A\).
Note
Here the counter \(l\) iterates over all the previous steps before \(k\). For each step, the row and column vectors comprising the cross have been stored as column vectors into v_mat and u_mat respectively. Hence, the index for extracting vectors from v_mat or u_mat should be \(l-1\).
Extract the previous cross.
Select the column index from the maximizer of the absolute values of \(\widetilde{v}_k\).
Scale the vector \(\widetilde{v}_k\).
Extract the \(j_k\)'th column from \(A\).
Extract the previous cross.
Select \(j^*\) as the current column index \(j_k\).
Extract the \(j_k\)'th column from the matrix \(A\).
Extract the previous cross.
Select the row index as the maximizer of the absolute values of \(u_k\).
Extract the \(i_k\)'th row from \(A\).
Extract the previous cross.
Scale the vector \(\widetilde{v}_k\).
Update the matrices storing row and column vectors comprising the cross.
When the index of the selected row is the same as that of the reference row, reselect a reference row.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Extract the previous cross.
Otherwise, update the values of the reference row vector.
Update the vector of absolute values for vr.
When the index of the selected column is the same as that of the reference column, reselect a reference column.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Extract the previous cross.
Otherwise, update the values of the reference column vector.
Update the vector of absolute values for uc.
Check the convergence condition.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Definition at line 5432 of file aca_plus.hcu.
References RkMatrix< Number >::get_m(), and RkMatrix< Number >::get_n().
aca_plus_parallel_sauter_quad_for_vector_entry() [1/2]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void aca_plus_parallel_sauter_quad_for_vector_entry (RkMatrix< RangeNumberType > & rkmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::array< types::global_dof_index, 2 > & row_dof_index_range, const std::array< types::global_dof_index, 2 > & col_dof_index_range, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > & scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
ACA+ algorithm
Grasedyck, L. 2005. “Adaptive Recompression of \(\mathcal{H}\)-Matrices for BEM.” Computing 74 (3): 205–23.}
Note
At present, the simple convergence condition in this paper is adopted instead of that in Bebendorf's book.
Parameters
rkmat The rank-k matrix to be constructed for the current block, the memory of which should be preallocated and the formal rank of which should be the same as the maximum iteration number in aca_config.
aca_config
kernel
factor
row_dof_indices
col_dof_indices
kx_dof_to_cell_topo
ky_dof_to_cell_topo
bem_values
kx_dof_handler
ky_dof_handler
kx_mapping
ky_mapping
scratch_data
copy_data
Adjust the maximum ACA+ iteration if is larger than the matrix dimension.
Generate lists of internal DoF indices (internal DoF numbering) from corresponding index ranges.
Create matrix references associated with the component matrices in the rank-k matrix to be returned, which hold the row and column vectors in the selected crosses during the ACA iteration. The number of columns should be the same as the effective maximum iteration number.
Generate two lists for storing remaining row indices and column indices of the matrix block.
Select the initial reference row and column vectors and return their matrix indices.
The absolute values for the reference row and column vectors.
Calculate the absolute values for the reference row and column vectors.
Note
In the following, we use static_cast to explicitly specify which version of std::abs to call.
Row and column indices for the \(k\)'th step. The corresponding row and column vectors comprise the cross.
Temporary row and column vectors for the current step \(k\).
The absolute values for the temporary row and column vectors for the current step \(k\).
Temporary row and column vectors for the previous step \(l\).
The error threshold as the stopping condition.
Start the ACA+ iteration from \(k=1\).
Select the row index from the maximizer of the reference column.
Select the column index from the maximizer of the reference row.
Select \(i^*\) as the current row index \(i_k\).
Extract the \(i_k\)'th row of \(A\).
Note
Here the counter \(l\) iterates over all the previous steps before \(k\). For each step, the row and column vectors comprising the cross have been stored as column vectors into v_mat and u_mat respectively. Hence, the index for extracting vectors from v_mat or u_mat should be \(l-1\).
Extract the previous cross.
Select the column index from the maximizer of the absolute values of \(\widetilde{v}_k\).
Scale the vector \(\widetilde{v}_k\).
Extract the \(j_k\)'th column from \(A\).
Extract the previous cross.
Select \(j^*\) as the current column index \(j_k\).
Extract the \(j_k\)'th column from the matrix \(A\).
Extract the previous cross.
Select the row index as the maximizer of the absolute values of \(u_k\).
Extract the \(i_k\)'th row from \(A\).
Extract the previous cross.
Scale the vector \(\widetilde{v}_k\).
Update the matrices storing row and column vectors comprising the cross.
Calculate the error threshold only in the first step.
When the index of the selected row is the same as that of the reference row, reselect a reference row.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Extract the previous cross.
Otherwise, update the values of the reference row vector.
Update the vector of absolute values for vr.
When the index of the selected column is the same as that of the reference column, reselect a reference column.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Extract the previous cross.
Otherwise, update the values of the reference column vector.
Update the vector of absolute values for uc.
Check the convergence condition.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Definition at line 2483 of file aca_plus.hcu.
Referenced by fill_hmatrix_leaf_node_with_aca_plus().
aca_plus_parallel_sauter_quad_for_vector_entry() [2/2]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void aca_plus_parallel_sauter_quad_for_vector_entry (RkMatrix< RangeNumberType > & rkmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, KernelNumberType > & kernel, const KernelNumberType kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, const std::array< types::global_dof_index, 2 > & row_dof_index_range, const std::array< types::global_dof_index, 2 > & col_dof_index_range, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
ACA+ algorithm
Grasedyck, L. 2005. “Adaptive Recompression of \(\mathcal{H}\)-Matrices for BEM.” Computing 74 (3): 205–23.}
Note
1. At present, the simple convergence condition in this paper is adopted instead of that in Bebendorf's book.
This version is especially for assembling the regularized hyper-singular matrix with the stabilization term.
Parameters
rkmat
aca_config
kernel
factor
mass_vmult_weq
stabilization_factor
row_dof_index_range
col_dof_index_range
kx_dof_to_cell_topo
ky_dof_to_cell_topo
bem_values
kx_dof_handler
ky_dof_handler
kx_dof_i2e_numbering
ky_dof_i2e_numbering
kx_mapping
ky_mapping
scratch_data
copy_data
Get the size of each dimension of the matrix block to be built.
Adjust the maximum ACA+ iteration if is larger than the matrix dimension.
Generate lists of internal DoF indices (internal DoF numbering) from corresponding index ranges.
Create matrix references associated with the component matrices in the rank-k matrix to be returned, which hold the row and column vectors in the selected crosses during the ACA iteration. The number of columns should be the same as the effective maximum iteration number.
Generate two lists for storing remaining row indices and column indices of the matrix block.
Select the initial reference row and column vectors and return their matrix indices.
The absolute values for the reference row and column vectors.
Calculate the absolute values for the reference row and column vectors.
Note
In the following, we use static_cast to explicitly specify which version of std::abs to call.
Row and column indices for the \(k\)'th step. The corresponding row and column vectors comprise the cross.
Temporary row and column vectors for the current step \(k\).
The absolute values for the temporary row and column vectors for the current step \(k\).
Temporary row and column vectors for the previous step \(l\).
The error threshold as the stopping condition.
Start the ACA+ iteration from \(k=1\).
Select the row index from the maximizer of the reference column.
Select the column index from the maximizer of the reference row.
Select \(i^*\) as the current row index \(i_k\).
Extract the \(i_k\)'th row of \(A\).
Note
Here the counter \(l\) iterates over all the previous steps before \(k\). For each step, the row and column vectors comprising the cross have been stored as column vectors into v_mat and u_mat respectively. Hence, the index for extracting vectors from v_mat or u_mat should be \(l-1\).
Extract the previous cross.
Select the column index from the maximizer of the absolute values of \(\widetilde{v}_k\).
Scale the vector \(\widetilde{v}_k\).
Extract the \(j_k\)'th column from \(A\).
Extract the previous cross.
Select \(j^*\) as the current column index \(j_k\).
Extract the \(j_k\)'th column from the matrix \(A\).
Extract the previous cross.
Select the row index as the maximizer of the absolute values of \(u_k\).
Extract the \(i_k\)'th row from \(A\).
Extract the previous cross.
Scale the vector \(\widetilde{v}_k\).
Update the matrices storing row and column vectors comprising the cross.
Calculate the error threshold only in the first step.
When the index of the selected row is the same as that of the reference row, reselect a reference row.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Extract the previous cross.
Otherwise, update the values of the reference row vector.
Update the vector of absolute values for vr.
When the index of the selected column is the same as that of the reference column, reselect a reference column.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Extract the previous cross.
Otherwise, update the values of the reference column vector.
Update the vector of absolute values for uc.
Check the convergence condition.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Definition at line 3191 of file aca_plus.hcu.
aca_plus_parallel_sauter_quad_for_whole_vector() [1/2]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void aca_plus_parallel_sauter_quad_for_whole_vector (RkMatrix< RangeNumberType > & rkmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::array< types::global_dof_index, 2 > & row_dof_index_range, const std::array< types::global_dof_index, 2 > & col_dof_index_range, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const BEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Parameters
row_dof_index_range Local DoF index range with internal numbering for the rows of the current matrix block.
col_dof_index_range Local DoF index range with internal numbering for the columns of the current matrix block.
Adjust the maximum ACA+ iteration if is larger than the matrix dimension.
Generate lists of local DoF indices with internal DoF numbering from corresponding index ranges.
Create matrix references associated with the component matrices in the rank-k matrix to be returned, which hold the row and column vectors in the selected crosses during the ACA iteration. The number of columns should be the same as the effective maximum iteration number.
Generate two lists for storing remaining row indices and column indices of the matrix block.
Select the initial reference row and column vectors and return their matrix indices.
The absolute values for the reference row and column vectors.
Calculate the absolute values for the reference row and column vectors.
Note
In the following, we use static_cast to explicitly specify which version of std::abs to call.
Row and column indices for the \(k\)'th step. The corresponding row and column vectors comprise the cross.
Temporary row and column vectors for the current step \(k\).
The absolute values for the temporary row and column vectors for the current step \(k\).
Temporary row and column vectors for the previous step \(l\).
The error threshold as the stopping condition.
Start the ACA+ iteration from \(k=1\).
Select the row index from the maximizer of the reference column.
Select the column index from the maximizer of the reference row.
Select \(i^*\) as the current row index \(i_k\).
Extract the \(i_k\)'th row of \(A\).
Note
Here the counter \(l\) iterates over all the previous steps before \(k\). For each step, the row and column vectors comprising the cross have been stored as column vectors into v_mat and u_mat respectively. Hence, the index for extracting vectors from v_mat or u_mat should be \(l-1\).
Extract the previous cross.
Select the column index from the maximizer of the absolute values of \(\widetilde{v}_k\).
Scale the vector \(\widetilde{v}_k\).
Extract the \(j_k\)'th column from \(A\).
Extract the previous cross.
Select \(j^*\) as the current column index \(j_k\).
Extract the \(j_k\)'th column from the matrix \(A\).
Extract the previous cross.
Select the row index as the maximizer of the absolute values of \(u_k\).
Extract the \(i_k\)'th row from \(A\).
Extract the previous cross.
Scale the vector \(\widetilde{v}_k\).
Update the matrices storing row and column vectors comprising the cross.
Calculate the error threshold only in the first step.
When the index of the selected row is the same as that of the reference row, reselect a reference row.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Extract the previous cross.
Otherwise, update the values of the reference row vector.
Update the vector of absolute values for vr.
When the index of the selected column is the same as that of the reference column, reselect a reference column.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Extract the previous cross.
Otherwise, update the values of the reference column vector.
Update the vector of absolute values for uc.
Check the convergence condition.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Definition at line 3890 of file aca_plus.hcu.
Referenced by fill_far_field_hmatrix_leaf_node_with_aca_plus().
aca_plus_parallel_sauter_quad_for_whole_vector() [2/2]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void aca_plus_parallel_sauter_quad_for_whole_vector (RkMatrix< RangeNumberType > & rkmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, KernelNumberType > & kernel, const KernelNumberType kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, const std::array< types::global_dof_index, 2 > & row_dof_index_range, const std::array< types::global_dof_index, 2 > & col_dof_index_range, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const BEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Get the size of each dimension of the matrix block to be built.
Adjust the maximum ACA+ iteration if is larger than the matrix dimension.
Generate lists of internal DoF indices (internal DoF numbering) from corresponding index ranges.
Create matrix references associated with the component matrices in the rank-k matrix to be returned, which hold the row and column vectors in the selected crosses during the ACA iteration. The number of columns should be the same as the effective maximum iteration number.
Generate two lists for storing remaining row indices and column indices of the matrix block.
Select the initial reference row and column vectors and return their matrix indices.
The absolute values for the reference row and column vectors.
Calculate the absolute values for the reference row and column vectors.
Note
In the following, we use static_cast to explicitly specify which version of std::abs to call.
Row and column indices for the \(k\)'th step. The corresponding row and column vectors comprise the cross.
Temporary row and column vectors for the current step \(k\).
The absolute values for the temporary row and column vectors for the current step \(k\).
Temporary row and column vectors for the previous step \(l\).
The error threshold as the stopping condition.
Start the ACA+ iteration from \(k=1\).
Select the row index from the maximizer of the reference column.
Select the column index from the maximizer of the reference row.
Select \(i^*\) as the current row index \(i_k\).
Extract the \(i_k\)'th row of \(A\).
Note
Here the counter \(l\) iterates over all the previous steps before \(k\). For each step, the row and column vectors comprising the cross have been stored as column vectors into v_mat and u_mat respectively. Hence, the index for extracting vectors from v_mat or u_mat should be \(l-1\).
Extract the previous cross.
Select the column index from the maximizer of the absolute values of \(\widetilde{v}_k\).
Scale the vector \(\widetilde{v}_k\).
Extract the \(j_k\)'th column from \(A\).
Extract the previous cross.
Select \(j^*\) as the current column index \(j_k\).
Extract the \(j_k\)'th column from the matrix \(A\).
Extract the previous cross.
Select the row index as the maximizer of the absolute values of \(u_k\).
Extract the \(i_k\)'th row from \(A\).
Extract the previous cross.
Scale the vector \(\widetilde{v}_k\).
Update the matrices storing row and column vectors comprising the cross.
Calculate the error threshold only in the first step.
When the index of the selected row is the same as that of the reference row, reselect a reference row.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Extract the previous cross.
Otherwise, update the values of the reference row vector.
Update the vector of absolute values for vr.
When the index of the selected column is the same as that of the reference column, reselect a reference column.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Extract the previous cross.
Otherwise, update the values of the reference column vector.
Update the vector of absolute values for uc.
Check the convergence condition.
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
If the number of ACA+ iterations is less than the allowed maximum value, the rkmat should be truncated to its actual rank.
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Apply complex conjugation to the component matrix B, when we're dealing with complex values, because the rank-k matrix should take the form \(M=AB^{\mathrm{H}}\).
Definition at line 4649 of file aca_plus.hcu.
assemble_kernel_column() [1/4]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void assemble_kernel_column (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > & task_buffer, Vector< RangeNumberType > & col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< types::global_dof_index > & row_dof_indices, const types::global_dof_index col_dof_index, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Assemble a column vector by evaluating the Galerkin-BEM double integral with respect to the kernel. This version parallelizes over each vector element.
Definition at line 765 of file aca_plus.hcu.
References PairCellWiseScratchData< dim, spacedim, KernelNumberType >::cuda_stream_handle.
assemble_kernel_column() [2/4]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void assemble_kernel_column (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > & task_buffer, Vector< RangeNumberType > & col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, const std::vector< types::global_dof_index > & row_dof_indices, const types::global_dof_index col_dof_index, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Assemble a column vector by evaluating the Galerkin-BEM double integral with respect to the kernel. This version regularizes the kernel and parallelizes over each vector element.
Definition at line 870 of file aca_plus.hcu.
References assemble_kernel_column().
assemble_kernel_column() [3/4]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void assemble_kernel_column (Vector< RangeNumberType > & col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< types::global_dof_index > & row_dof_indices, const types::global_dof_index col_dof_index, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > & scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Assemble a column vector by evaluating the Galerkin-BEM double integral with respect to the kernel.
Note
The memory for col_vector should be preallocated, since inside the function there is no reinitialization of this vector anymore.
Parameters
col_vector
kernel
factor
row_dof_indices The list of row DoF indices in the global internal DoF numbering.
col_dof_index The column DoF index in the global internal DoF numbering.
kx_dof_to_cell_topo
ky_dof_to_cell_topo
bem_values
kx_dof_handler
ky_dof_handler
kx_map_from_local_to_full_dof_indices
ky_map_from_local_to_full_dof_indices
kx_dof_i2e_numbering
ky_dof_i2e_numbering
kx_mapping
ky_mapping
scratch_data
copy_data
Iterate over each row DoF index.
Definition at line 557 of file aca_plus.hcu.
Referenced by assemble_kernel_column(), and random_select_ref_column().
assemble_kernel_column() [4/4]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void assemble_kernel_column (Vector< RangeNumberType > & col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, const std::vector< types::global_dof_index > & row_dof_indices, const types::global_dof_index col_dof_index, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > & scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Assemble a column vector by evaluating the Galerkin-BEM double integral with respect to the kernel.
Note
1. The memory for col_vector should be preallocated, since inside the function there is no reinitialization of this vector anymore.
This version is especially for assembling the regularized hyper-singular matrix with the stabilization term.
Parameters
col_vector
kernel
factor
mass_vmult_weq
row_dof_indices
col_dof_index
kx_dof_to_cell_topo
ky_dof_to_cell_topo
bem_values
kx_dof_handler
ky_dof_handler
kx_dof_i2e_numbering
ky_dof_i2e_numbering
kx_mapping
ky_mapping
scratch_data
copy_data
Iterate over each row DoF index.
Definition at line 669 of file aca_plus.hcu.
assemble_kernel_row() [1/4]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void assemble_kernel_row (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > & task_buffer, Vector< RangeNumberType > & row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, const types::global_dof_index row_dof_index, const std::vector< types::global_dof_index > & column_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Assemble a row vector by evaluating the Galerkin-BEM double integral with respect to the kernel. This version regularizes the kernel and parallelizes over each vector element.
Definition at line 450 of file aca_plus.hcu.
References assemble_kernel_row().
assemble_kernel_row() [2/4]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void assemble_kernel_row (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > & task_buffer, Vector< RangeNumberType > & row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const types::global_dof_index row_dof_index, const std::vector< types::global_dof_index > & column_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Assemble a row vector by evaluating the Galerkin-BEM double integral with respect to the kernel. This version parallelizes over each vector element.
Definition at line 341 of file aca_plus.hcu.
References PairCellWiseScratchData< dim, spacedim, KernelNumberType >::cuda_stream_handle.
assemble_kernel_row() [3/4]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void assemble_kernel_row (Vector< RangeNumberType > & row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, const types::global_dof_index row_dof_index, const std::vector< types::global_dof_index > & column_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const DoFHandler< dim, spacedim > & kx_dof_handler, const DoFHandler< dim, spacedim > & ky_dof_handler, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > & scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Assemble a row vector by evaluating the Galerkin-BEM double integral with respect to the kernel.
Note
1. The memory for row_vector should be preallocated, since inside the function there is no reinitialization of this vector anymore.
This version is especially for assembling the regularized hyper-singular matrix with the stabilization term.
Parameters
row_vector
kernel
kernel_factor
mass_vmult_weq
stabilization_factor
row_dof_index
column_dof_indices
kx_dof_to_cell_topo
ky_dof_to_cell_topo
bem_values
kx_dof_handler
ky_dof_handler
kx_dof_i2e_numbering
ky_dof_i2e_numbering
kx_mapping
ky_mapping
scratch_data
copy_data
Iterate over each column DoF index.
Definition at line 242 of file aca_plus.hcu.
assemble_kernel_row() [4/4]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void assemble_kernel_row (Vector< RangeNumberType > & row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const types::global_dof_index row_dof_index, const std::vector< types::global_dof_index > & column_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const DoFHandler< dim, spacedim > & kx_dof_handler, const DoFHandler< dim, spacedim > & ky_dof_handler, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > & scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Assemble a row vector by evaluating the Galerkin-BEM double integral with respect to the kernel.
Note
The memory for row_vector should be preallocated, since inside the function there is no reinitialization of this vector anymore.
Parameters
row_vector [out]
scratch
data
kernel
row_dof_index The current row DoF index.
column_dof_indices The list of column DoF indices.
Iterate over each column DoF index.
Definition at line 125 of file aca_plus.hcu.
Referenced by assemble_kernel_row(), and random_select_ref_row().
fill_far_field_hmatrix_leaf_node_subrange_with_aca_plus() [1/2]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void fill_far_field_hmatrix_leaf_node_subrange_with_aca_plus (const tbb::blocked_range< typename std::vector< HMatrix< spacedim, RangeNumberType > * >::iterator > & range, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const BEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const DoFHandler< dim, spacedim > & kx_dof_handler, const DoFHandler< dim, spacedim > & ky_dof_handler, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, const bool enable_build_symmetric_hmat = false)
Fill the leaf nodes in a subrange of an \(\mathcal{H}\)-matrix using ACA+.
Note
This function is to be used for TBB parallelization.
Parameters
range
aca_config
kernel
kernel_factor
kx_dof_to_cell_topo
ky_dof_to_cell_topo
bem_values
kx_dof_handler
ky_dof_handler
kx_mapping
ky_mapping
enable_build_symmetric_hmat Flag indicating whether symmetric \(\mathcal{H}\)-matrix will be built when the kernel function is symmetric.
Define PairCellWiseScratchData and PairCellWisePerTaskData which are local to the current working thread. This is mandatory because each current working thread should have its own copy of these data.
Release pair cell wise scratch and copy data.
Definition at line 7507 of file aca_plus.hcu.
References fill_far_field_hmatrix_leaf_node_with_aca_plus().
fill_far_field_hmatrix_leaf_node_subrange_with_aca_plus() [2/2]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void fill_far_field_hmatrix_leaf_node_subrange_with_aca_plus (const tbb::blocked_range< typename std::vector< HMatrix< spacedim, RangeNumberType > * >::iterator > & range, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const BEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const DoFHandler< dim, spacedim > & kx_dof_handler, const DoFHandler< dim, spacedim > & ky_dof_handler, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, const bool enable_build_symmetric_hmat = false)
Fill the leaf nodes in a subrange of an \(\mathcal{H}\)-matrix using ACA+.
Note
1. This function is to be used for TBB parallelization.
This version is especially for assembling the regularized hyper-singular matrix with the stabilization term.
Parameters
range
aca_config
kernel
kernel_factor
mass_vmult_weq
stabilization_factor
kx_dof_to_cell_topo
ky_dof_to_cell_topo
bem_values
kx_dof_handler
ky_dof_handler
kx_dof_i2e_numbering
ky_dof_i2e_numbering
kx_mapping
ky_mapping
enable_build_symmetric_hmat
Define PairCellWiseScratchData and PairCellWisePerTaskData which are local to the current working thread. This is mandatory because each current working thread should have its own copy of these data.
Release pair cell wise scratch and copy data.
Definition at line 7632 of file aca_plus.hcu.
References fill_far_field_hmatrix_leaf_node_with_aca_plus().
fill_far_field_hmatrix_leaf_node_with_aca_plus() [1/2]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void fill_far_field_hmatrix_leaf_node_with_aca_plus (HMatrix< spacedim, RangeNumberType > * leaf_mat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const BEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data, const bool enable_build_symmetric_hmat = false)
When the \(\mathcal{H}\)-matrix block type is rank-k matrix, when the top level \(\mathcal{H}\)-matrix is symmetric and the flag enable_build_symmetric_hmat is true, only those matrix blocks belong to the lower triangular part will be computed. Otherwise, the rank-k matrix block will always be computed. ACA+ will be used for building the rank-k matrix.
Build the \(\mathcal{H}\)-matrix block when it belongs to the lower triangular part using ACA+.
Do not build \(\mathcal{H}\)-matrix block belonging to the upper triangular part.
An rank-k matrix cannot belong to the diagonal part.
Definition at line 7151 of file aca_plus.hcu.
References aca_plus_parallel_sauter_quad_for_whole_vector(), FullMatrixType, HMatrix< spacedim, Number >::get_block_type(), HMatrix< spacedim, Number >::get_col_index_range(), HMatrix< spacedim, Number >::get_rkmatrix(), HMatrix< spacedim, Number >::get_row_index_range(), HMatrix< spacedim, Number >::get_type(), and RkMatrixType.
Referenced by fill_far_field_hmatrix_leaf_node_subrange_with_aca_plus().
fill_far_field_hmatrix_leaf_node_with_aca_plus() [2/2]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void fill_far_field_hmatrix_leaf_node_with_aca_plus (HMatrix< spacedim, RangeNumberType > * leaf_mat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const BEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data, const bool enable_build_symmetric_hmat = false)
When the \(\mathcal{H}\)-matrix block type is rank-k matrix, when the top level \(\mathcal{H}\)-matrix is symmetric and the flag enable_build_symmetric_hmat is true, only those matrix blocks belong to the lower triangular part will be computed. Otherwise, the rank-k matrix block will always be computed. ACA+ will be used for building the rank-k matrix.
Build the \(\mathcal{H}\)-matrix block when it belongs to the lower triangular part using ACA+.
Do not build \(\mathcal{H}\)-matrix block belonging to the upper triangular part.
An rank-k matrix cannot belong to the diagonal part.
Definition at line 7321 of file aca_plus.hcu.
References aca_plus_parallel_sauter_quad_for_whole_vector(), FullMatrixType, HMatrix< spacedim, Number >::get_block_type(), HMatrix< spacedim, Number >::get_col_index_range(), HMatrix< spacedim, Number >::get_rkmatrix(), HMatrix< spacedim, Number >::get_row_index_range(), HMatrix< spacedim, Number >::get_type(), and RkMatrixType.
fill_hmatrix_leaf_node_with_aca_plus() [1/3]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void fill_hmatrix_leaf_node_with_aca_plus (HMatrix< spacedim, RangeNumberType > * leaf_mat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const DoFHandler< dim, spacedim > & kx_dof_handler, const DoFHandler< dim, spacedim > & ky_dof_handler, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > & scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data, const bool enable_build_symmetric_hmat = false)
Fill a single leaf node of the \(\mathcal{H}\)-matrix using ACA+. If the matrix type is RkMatrixType, the memory for the full or rank-k matrix in the leaf node has been allocated.
For the near field matrix, full matrices will be built whose elements will be obtained from the evaluation of the double integral in Galerkin-BEM. For the far field admissible matrix, rank-k matrices will be built using ACA+.
Note
1. This is used as the work function for parallel \(\mathcal{H}\)-matrix construction using ACA+.
For near field matrix assembly, the producer-consumer model is not adopted. GPU parallelization with 2D thread grid is distributed over each quadrature point in the X direction and each k3 term in the Y direction.
Template Parameters
dim
spacedim
KernelFunctionType
RangeNumberType
KernelNumberType
SurfaceNormalDetector
Parameters
leaf_mat
aca_config
kernel
kernel_factor
kx_dof_to_cell_topo
ky_dof_to_cell_topo
bem_values_gpu
kx_dof_handler
ky_dof_handler
kx_map_from_local_to_full_dof_indices
ky_map_from_local_to_full_dof_indices
kx_dof_i2e_numbering
ky_dof_i2e_numbering
mappings
material_id_to_mapping_index
normal_detector
scratch_data
scratch_data_gpu
copy_data
enable_build_symmetric_hmat
When the flag enable_build_symmetric_hmat is true and the kernel function is symmetric, try to build a symmetric \(\mathcal{H}\)-matrix. Otherwise, the whole full matrix will be built.
A diagonal \(\mathcal{H}\)-matrix block as well as its associated full matrix should be symmetric.
Only evaluate the diagonal and lower triangular elements in the full matrix.
Do not build \(\mathcal{H}\)-matrix block belonging to the upper triangular part.
When the current \(\mathcal{H}\)-matrix block belongs to the lower triangular part, evaluate all of its elements as usual.
Evaluate the whole full matrix.
When the \(\mathcal{H}\)-matrix block type is rank-k matrix, when the top level \(\mathcal{H}\)-matrix is symmetric and the flag enable_build_symmetric_hmat is true, only those matrix blocks belong to the lower triangular part will be computed. Otherwise, the rank-k matrix block will always be computed. ACA+ will be used for building the rank-k matrix.
Build the \(\mathcal{H}\)-matrix block when it belongs to the lower triangular part using ACA+.
Do not build \(\mathcal{H}\)-matrix block belonging to the upper triangular part.
An rank-k matrix cannot belong to the diagonal part.
Definition at line 5981 of file aca_plus.hcu.
References aca_plus_parallel_sauter_quad_for_vector_entry(), FullMatrixType, HMatrix< spacedim, Number >::get_block_type(), HMatrix< spacedim, Number >::get_col_index_range(), HMatrix< spacedim, Number >::get_fullmatrix(), HMatrix< spacedim, Number >::get_property(), LAPACKFullMatrixExt< Number >::get_property(), HMatrix< spacedim, Number >::get_rkmatrix(), HMatrix< spacedim, Number >::get_row_index_range(), HMatrix< spacedim, Number >::get_type(), RkMatrixType, and DoFToCellTopology< dim, spacedim >::topology.
Referenced by fill_hmatrix_with_aca_plus_serial().
fill_hmatrix_leaf_node_with_aca_plus() [2/3]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void fill_hmatrix_leaf_node_with_aca_plus (HMatrix< spacedim, RangeNumberType > * leaf_mat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const DoFHandler< dim, spacedim > & kx_dof_handler, const DoFHandler< dim, spacedim > & ky_dof_handler, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > & scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data, const bool enable_build_symmetric_hmat = false)
Fill a single leaf node of the \(\mathcal{H}\)-matrix using ACA+. If the matrix type is RkMatrixType, the memory for the full or rank-k matrix in the leaf node has been allocated.
For the near field matrix, full matrices will be built whose elements will be obtained from the evaluation of the double integral in Galerkin-BEM. For the far field admissible matrix, rank-k matrices will be built using ACA+.
Note
This is used as the work function for parallel \(\mathcal{H}\)-matrix construction using ACA+.
For near field matrix assembly, the producer-consumer model is not adopted. GPU parallelization with 2D thread grid is distributed over each quadrature point in the X direction and each k3 term in the Y direction.
This version is especially for assembling the regularized hyper-singular matrix appended with the stabilization term. The stabilization term in the variational equation is
\[ \alpha\langle \gamma_0^{\rm ext}u, \omega_{\rm eq} \rangle \cdot \langle v, \omega_{\rm eq} \rangle_{\Gamma}. \]
The stabilization term in the discretized form is
\[ \alpha M [\omega_{\rm eq}] \cdot \left[ M [\omega_{\rm eq}] \right]^{\rm T} \cdot [\gamma_0^{\rm ext}u], \]
which is actually an outer-product representation. The argument mass_vmult_weq passed to this function is just the vector \(M [\omega_{\rm eq}]\).
Template Parameters
dim
spacedim
KernelFunctionType
RangeNumberType
KernelNumberType
SurfaceNormalDetector
Parameters
leaf_mat
aca_config
kernel
kernel_factor
mass_vmult_weq This is the multiplication of the mass matrix and natural density vector. When in the mixed boundary value problem, because it produces an intermediate result, the DoF indices associated with the result vector are the local DoF indices, which does not need the application of the internal-to-external map (which is caused by the renumbering due to cluster tree construction), nor the external local-to-full Dirichlet DoF index map (which is caused by selecting a subset of DoFs from the Dirichlet space.).
stabilization_factor
kx_dof_to_cell_topo
ky_dof_to_cell_topo
bem_values_gpu
kx_dof_handler
ky_dof_handler
kx_map_from_local_to_full_dof_indices
ky_map_from_local_to_full_dof_indices
kx_dof_i2e_numbering
ky_dof_i2e_numbering
mappings
material_id_to_mapping_index
normal_detector
scratch_data
scratch_data_gpu
copy_data
enable_build_symmetric_hmat
When the flag enable_build_symmetric_hmat is true and the kernel function is symmetric, try to build a symmetric \(\mathcal{H}\)-matrix. Otherwise, the whole full matrix will be built.
A diagonal \(\mathcal{H}\)-matrix block as well as its associated full matrix should be symmetric.
Only evaluate the diagonal and lower triangular elements in the full matrix.
Do not build \(\mathcal{H}\)-matrix block belonging to the upper triangular part.
When the current \(\mathcal{H}\)-matrix block belongs to the lower triangular part, evaluate all of its elements as usual.
Evaluate the whole full matrix.
When the \(\mathcal{H}\)-matrix block type is rank-k matrix, when the top level \(\mathcal{H}\)-matrix is symmetric and the flag enable_build_symmetric_hmat is true, only those matrix blocks belong to the lower triangular part will be computed. Otherwise, the rank-k matrix block will always be computed. ACA+ will be used for building the rank-k matrix.
Build the \(\mathcal{H}\)-matrix block when it belongs to the lower triangular part using ACA+.
Do not build \(\mathcal{H}\)-matrix block belonging to the upper triangular part.
An rank-k matrix cannot belong to the diagonal part.
Definition at line 6400 of file aca_plus.hcu.
References aca_plus_parallel_sauter_quad_for_vector_entry(), FullMatrixType, HMatrix< spacedim, Number >::get_block_type(), HMatrix< spacedim, Number >::get_col_index_range(), HMatrix< spacedim, Number >::get_fullmatrix(), HMatrix< spacedim, Number >::get_property(), LAPACKFullMatrixExt< Number >::get_property(), HMatrix< spacedim, Number >::get_rkmatrix(), HMatrix< spacedim, Number >::get_row_index_range(), HMatrix< spacedim, Number >::get_type(), RkMatrixType, and DoFToCellTopology< dim, spacedim >::topology.
fill_hmatrix_leaf_node_with_aca_plus() [3/3]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void fill_hmatrix_leaf_node_with_aca_plus (HMatrix< spacedim, RangeNumberType > * leaf_mat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const typename numbers::NumberTraits< RangeNumberType >::real_type mass_matrix_factor, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const DoFHandler< dim, spacedim > & kx_dof_handler, const DoFHandler< dim, spacedim > & ky_dof_handler, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, CellWiseScratchDataForMassMatrix< dim, spacedim > & mass_matrix_scratch_data, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > & scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data, const bool enable_build_symmetric_hmat = false)
Fill a single leaf node of the \(\mathcal{H}\)-matrix using ACA+.
In the mean time, the FEM mass matrix multiplied by a factor will be added to the near field matrix block.
If the matrix type is RkMatrixType, the memory for the full or rank-k matrix in the leaf node has been allocated.
For the near field matrix, full matrices will be built whose elements will be obtained from the evaluation of the double integral in Galerkin-BEM. For the far field admissible matrix, rank-k matrices will be built using ACA+.
Note
1. This is used as the work function for parallel \(\mathcal{H}\)-matrix construction using ACA+.
For near field matrix assembly, the producer-consumer model is not adopted. GPU parallelization with 2D thread grid is distributed over each quadrature point in the X direction and each k3 term in the Y direction.
Template Parameters
dim
spacedim
KernelFunctionType
RangeNumberType
KernelNumberType
SurfaceNormalDetector
Parameters
leaf_mat
aca_config
kernel
kernel_factor
mass_matrix_factor
kx_dof_to_cell_topo
ky_dof_to_cell_topo
bem_values_gpu
kx_dof_handler
ky_dof_handler
kx_map_from_local_to_full_dof_indices
ky_map_from_local_to_full_dof_indices
kx_dof_i2e_numbering
ky_dof_i2e_numbering
mappings
material_id_to_mapping_index
normal_detector
mass_matrix_scratch_data
scratch_data
scratch_data_gpu
copy_data
enable_build_symmetric_hmat
When the flag enable_build_symmetric_hmat is true and the kernel function is symmetric, try to build a symmetric \(\mathcal{H}\)-matrix. Otherwise, the whole full matrix will be built.
A diagonal \(\mathcal{H}\)-matrix block as well as its associated full matrix should be symmetric.
Only evaluate the diagonal and lower triangular elements in the full matrix.
Do not build \(\mathcal{H}\)-matrix block belonging to the upper triangular part.
When the current \(\mathcal{H}\)-matrix block belongs to the lower triangular part, evaluate all of its elements as usual.
Build the \(\mathcal{H}\)-matrix block when it belongs to the lower triangular part using ACA+.
Do not build \(\mathcal{H}\)-matrix block belonging to the upper triangular part.
An rank-k matrix cannot belong to the diagonal part.
Definition at line 6817 of file aca_plus.hcu.
References aca_plus_parallel_sauter_quad_for_vector_entry(), FullMatrixType, HMatrix< spacedim, Number >::get_block_type(), HMatrix< spacedim, Number >::get_col_index_range(), HMatrix< spacedim, Number >::get_fullmatrix(), HMatrix< spacedim, Number >::get_property(), LAPACKFullMatrixExt< Number >::get_property(), HMatrix< spacedim, Number >::get_rkmatrix(), HMatrix< spacedim, Number >::get_row_index_range(), HMatrix< spacedim, Number >::get_type(), RkMatrixType, and DoFToCellTopology< dim, spacedim >::topology.
fill_hmatrix_with_aca_plus_serial() [1/3]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void fill_hmatrix_with_aca_plus_serial (HMatrix< spacedim, RangeNumberType > & hmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, KernelNumberType > & kernel, const KernelNumberType kernel_factor, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const SauterQuadratureRule< dim > & sauter_quad_rule, const DoFHandler< dim, spacedim > & kx_dof_handler, const DoFHandler< dim, spacedim > & ky_dof_handler, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, const bool enable_build_symmetric_hmat = false)
Fill the leaf set of the \(\mathcal{H}\)-matrix using ACA+, where the hierarchical structure of the \(\mathcal{H}\)-matrix has been built with respect to a block cluster tree and the memory for the matrices in the leaf set has been allocated.
For the near field matrices in the leaf set, full matrices will be built whose elements will be obtained from the evaluation of the double integral in Galerkin-BEM. For the far field admissible matrices in the leaf set, rank-k matrices will be built using ACA+.
Note
This version processes each \(\mathcal{H}\)-matrix node in the leaf set one-by-one without partitioning the leaf set using TBB.
Template Parameters
dim
spacedim
KernelFunctionType
RangeNumberType
KernelNumberType
SurfaceNormalDetector
Parameters
hmat
aca_config
kernel
kernel_factor
kx_dof_to_cell_topo
ky_dof_to_cell_topo
sauter_quad_rule
kx_dof_handler
ky_dof_handler
kx_map_from_local_to_full_dof_indices
ky_map_from_local_to_full_dof_indices
kx_dof_i2e_numbering
ky_dof_i2e_numbering
mappings
material_id_to_mapping_index
normal_detector
enable_build_symmetric_hmat
Precalculate data tables for shape values at quadrature points.
Note
Precalculate shape function values and their gradient values at each quadrature point. N.B.
The data tables for shape function values and their gradient values should be calculated for both function space on \(K_x\) and function space on \(K_y\).
Being different from the integral in FEM, the integral in BEM handled by Sauter's quadrature rule has multiple parts of \(k_3\) (except the regular cell neighboring type), each of which should be evaluated at a different set of quadrature points in the unit cell after coordinate transformation from the parametric space. Therefore, a dimension with respect to \(k_3\) term index should be added to the data table compared to the usual FEValues and this brings about the class BEMValues.
Copy the precalculated BEM values to the GPU device.
Define PairCellWiseScratchData and PairCellWisePerTaskData which are local to the current working thread. This is mandatory because each current working thread should have its own copy of these data.
Create pair cell wise scratch data and task data on GPU device.
Release BEM values on the GPU device.
Release pair cell wise scratch and copy data on the GPU device.
Definition at line 7910 of file aca_plus.hcu.
References PairCellWiseScratchData< dim, spacedim, KernelNumberType >::cuda_stream_handle, fill_hmatrix_leaf_node_with_aca_plus(), BEMValues< dim, spacedim, RangeNumberType >::fill_shape_function_value_tables(), and HMatrix< spacedim, Number >::get_leaf_set().
fill_hmatrix_with_aca_plus_serial() [2/3]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void fill_hmatrix_with_aca_plus_serial (HMatrix< spacedim, RangeNumberType > & hmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, KernelNumberType > & kernel, const KernelNumberType kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const SauterQuadratureRule< dim > & sauter_quad_rule, const DoFHandler< dim, spacedim > & kx_dof_handler, const DoFHandler< dim, spacedim > & ky_dof_handler, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, const bool enable_build_symmetric_hmat = false)
Fill the leaf set of the \(\mathcal{H}\)-matrix using ACA+, where the hierarchical structure of the \(\mathcal{H}\)-matrix has been built with respect to a block cluster tree and the memory for the matrices in the leaf set has been allocated.
For the near field matrices in the leaf set, full matrices will be built whose elements will be obtained from the evaluation of the double integral in Galerkin-BEM. For the far field admissible matrices in the leaf set, rank-k matrices will be built using ACA+.
Note
This version processes each \(\mathcal{H}\)-matrix node in the leaf set one-by-one without partitioning the leaf set using TBB.
This version is especially for assembling the regularized hyper-singular matrix appended with the stabilization term. The stabilization term in the variational equation is
\[ \alpha\langle \gamma_0^{\rm ext}u, \omega_{\rm eq} \rangle \cdot \langle v, \omega_{\rm eq} \rangle_{\Gamma}. \]
The stabilization term in the discretized form is
\[ \alpha M [\omega_{\rm eq}] \cdot \left[ M [\omega_{\rm eq}] \right]^{\rm T} \cdot [\gamma_0^{\rm ext}u], \]
which is actually an outer-product representation. The argument mass_vmult_weq passed to this function is just the vector \(M [\omega_{\rm eq}]\).
Template Parameters
dim
spacedim
KernelFunctionType
RangeNumberType
KernelNumberType
SurfaceNormalDetector
Parameters
hmat
aca_config
kernel
kernel_factor
mass_vmult_weq
stabilization_factor
kx_dof_to_cell_topo
ky_dof_to_cell_topo
sauter_quad_rule
kx_dof_handler
ky_dof_handler
kx_map_from_local_to_full_dof_indices
ky_map_from_local_to_full_dof_indices
kx_dof_i2e_numbering
ky_dof_i2e_numbering
mappings
material_id_to_mapping_index
normal_detector
enable_build_symmetric_hmat
Precalculate data tables for shape values at quadrature points.
Note
Precalculate shape function values and their gradient values at each quadrature point. N.B.
The data tables for shape function values and their gradient values should be calculated for both function space on \(K_x\) and function space on \(K_y\).
Being different from the integral in FEM, the integral in BEM handled by Sauter's quadrature rule has multiple parts of \(k_3\) (except the regular cell neighboring type), each of which should be evaluated at a different set of quadrature points in the unit cell after coordinate transformation from the parametric space. Therefore, a dimension with respect to \(k_3\) term index should be added to the data table compared to the usual FEValues and this brings about the class BEMValues.
Copy the precalculated BEM values to the GPU device.
Define PairCellWiseScratchData and PairCellWisePerTaskData which are local to the current working thread. This is mandatory because each current working thread should have its own copy of these data.
Create pair cell wise scratch data and task data on GPU device.
Release BEM values on the GPU device.
Release pair cell wise scratch and copy data.
Definition at line 8093 of file aca_plus.hcu.
References PairCellWiseScratchData< dim, spacedim, KernelNumberType >::cuda_stream_handle, fill_hmatrix_leaf_node_with_aca_plus(), BEMValues< dim, spacedim, RangeNumberType >::fill_shape_function_value_tables(), and HMatrix< spacedim, Number >::get_leaf_set().
fill_hmatrix_with_aca_plus_serial() [3/3]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void fill_hmatrix_with_aca_plus_serial (HMatrix< spacedim, RangeNumberType > & hmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, KernelNumberType > & kernel, const KernelNumberType kernel_factor, const typename numbers::NumberTraits< RangeNumberType >::real_type mass_matrix_factor, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const SauterQuadratureRule< dim > & sauter_quad_rule, const QGauss< dim > & mass_matrix_quadrature_formula, const DoFHandler< dim, spacedim > & kx_dof_handler, const DoFHandler< dim, spacedim > & ky_dof_handler, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, const bool enable_build_symmetric_hmat = false)
Fill the leaf set of the \(\mathcal{H}\)-matrix using ACA+, where the hierarchical structure of the \(\mathcal{H}\)-matrix has been built with respect to a block cluster tree and the memory for the matrices in the leaf set has been allocated.
For the near field matrices in the leaf set, full matrices will be built whose elements will be obtained from the evaluation of the double integral in Galerkin-BEM. For the far field admissible matrices in the leaf set, rank-k matrices will be built using ACA+.
Note
1. This version processes each \(\mathcal{H}\)-matrix node in the leaf set one-by-one without partitioning the leaf set using TBB.
The mass matrix scaled with a factor is appended to the near field leaf node.
Template Parameters
dim
spacedim
KernelFunctionType
RangeNumberType
KernelNumberType
SurfaceNormalDetector
Parameters
hmat
aca_config
kernel
kernel_factor
mass_matrix_factor
kx_dof_to_cell_topo
ky_dof_to_cell_topo
sauter_quad_rule
mass_matrix_quadrature_formula
kx_dof_handler
ky_dof_handler
kx_map_from_local_to_full_dof_indices
ky_map_from_local_to_full_dof_indices
kx_dof_i2e_numbering
ky_dof_i2e_numbering
mappings
material_id_to_mapping_index
normal_detector
enable_build_symmetric_hmat
Precalculate data tables for shape values at quadrature points.
Note
Precalculate shape function values and their gradient values at each quadrature point. N.B.
The data tables for shape function values and their gradient values should be calculated for both function space on \(K_x\) and function space on \(K_y\).
Being different from the integral in FEM, the integral in BEM handled by Sauter's quadrature rule has multiple parts of \(k_3\) (except the regular cell neighboring type), each of which should be evaluated at a different set of quadrature points in the unit cell after coordinate transformation from the parametric space. Therefore, a dimension with respect to \(k_3\) term index should be added to the data table compared to the usual FEValues and this brings about the class BEMValues.
Copy the precalculated BEM values to the GPU device.
Define CellWiseScratchDataForMassMatrix which is local to current working thread.
Define PairCellWiseScratchData and PairCellWisePerTaskData which are local to the current working thread. This is mandatory because each current working thread should have its own copy of these data.
Create pair cell wise scratch data and task data on GPU device.
Release BEM values on the GPU device.
Release pair cell wise scratch and copy data.
Definition at line 8267 of file aca_plus.hcu.
References PairCellWiseScratchData< dim, spacedim, KernelNumberType >::cuda_stream_handle, fill_hmatrix_leaf_node_with_aca_plus(), BEMValues< dim, spacedim, RangeNumberType >::fill_shape_function_value_tables(), and HMatrix< spacedim, Number >::get_leaf_set().
fill_hmatrix_with_aca_plus_smp() [1/3]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void fill_hmatrix_with_aca_plus_smp (const unsigned int thread_num, HMatrix< spacedim, RangeNumberType > & hmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const SauterQuadratureRule< dim > & sauter_quad_rule, const DoFHandler< dim, spacedim > & kx_dof_handler, const DoFHandler< dim, spacedim > & ky_dof_handler, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, const bool enable_build_symmetric_hmat = false)
Fill the leaf set of the \(\mathcal{H}\)-matrix using ACA+, where the hierarchical structure of the \(\mathcal{H}\)-matrix has been built with respect to a block cluster tree and the memory for the matrices in the leaf set has been allocated.
For the near field matrices in the leaf set, full matrices will be built whose elements will be obtained from the evaluation of the double integral in Galerkin-BEM. For the far field admissible matrices in the leaf set, rank-k matrices will be built using ACA+.
Note
For the near field leaf set, GPU parallelization is realized in a producer-consumer model. GPU 1D thread grid is distributed over each Sauter quadrature task in the ring buffer.
For the far field leaf set, GPU 2D thread grid is distributed over each Sauter quadrature task in the X direction and each quadrature point in the Y direction. The quadrature tasks collected in the buffer are used to build a row or column vector.
Template Parameters
dim
spacedim
KernelFunctionType
RangeNumberType
KernelNumberType
SurfaceNormalDetector
Parameters
thread_num
hmat
aca_config
kernel
kernel_factor
kx_dof_to_cell_topo
ky_dof_to_cell_topo
sauter_quad_rule
kx_dof_handler
ky_dof_handler
kx_map_from_local_to_full_dof_indices
ky_map_from_local_to_full_dof_indices
kx_dof_i2e_numbering
ky_dof_i2e_numbering
mappings
material_id_to_mapping_index
normal_detector
enable_build_symmetric_hmat
Precalculate shape function values and their gradient values at each quadrature point.
The data tables for shape function values and their gradient values should be calculated for both function space on \(K_x\) and function space on \(K_y\).
Being different from the integral in FEM, the integral in BEM handled by Sauter's quadrature rule has multiple parts of \(k_3\) (except the regular cell neighboring type), each of which should be evaluated at a different set of quadrature points in the unit cell after coordinate transformation from the parametric space. Therefore, a dimension with respect to \(k_3\) term index should be added to the data table compared to the usual FEValues and this brings about the class BEMValues.}
Copy the precalculated BEM values to the GPU device.
Release BEM values on the GPU device.
Definition at line 8455 of file aca_plus.hcu.
References HMatrix< spacedim, Number >::compute_near_field_leaf_set_assembly_task_costs(), BEMValues< dim, spacedim, RangeNumberType >::fill_shape_function_value_tables(), and print_wall_time().
Referenced by LaplaceBEM< dim, spacedim, RangeNumberType, KernelNumberType >::Priv::compute_stabilization_terms_for_D1_hmat().
fill_hmatrix_with_aca_plus_smp() [2/3]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void fill_hmatrix_with_aca_plus_smp (const unsigned int thread_num, HMatrix< spacedim, RangeNumberType > & hmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const SauterQuadratureRule< dim > & sauter_quad_rule, const DoFHandler< dim, spacedim > & kx_dof_handler, const DoFHandler< dim, spacedim > & ky_dof_handler, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, const bool enable_build_symmetric_hmat = false)
Fill the leaf set of the \(\mathcal{H}\)-matrix using ACA+, where the hierarchical structure of the \(\mathcal{H}\)-matrix has been built with respect to a block cluster tree and the memory for the matrices in the leaf set has been allocated.
For the near field matrices in the leaf set, full matrices will be built whose elements will be obtained from the evaluation of the double integral in Galerkin-BEM. For the far field admissible matrices in the leaf set, rank-k matrices will be built using ACA+.
This version is used for assembling the regularized hyper-singular matrix with the stabilization term.
Note
For the near field leaf set, GPU parallelization is realized in a producer-consumer model. GPU 1D thread grid is distributed over each Sauter quadrature task in the ring buffer.
For the far field leaf set, GPU 2D thread grid is distributed over each Sauter quadrature task in the X direction and each quadrature point in the Y direction. The quadrature tasks collected in the buffer are used to build a row or column vector.
Template Parameters
dim
spacedim
KernelFunctionType
RangeNumberType
KernelNumberType
SurfaceNormalDetector
Parameters
thread_num
hmat
aca_config
kernel
kernel_factor
mass_vmult_weq
stabilization_factor
kx_dof_to_cell_topo
ky_dof_to_cell_topo
sauter_quad_rule
kx_dof_handler
ky_dof_handler
kx_map_from_local_to_full_dof_indices
ky_map_from_local_to_full_dof_indices
kx_dof_i2e_numbering
ky_dof_i2e_numbering
mappings
material_id_to_mapping_index
normal_detector
enable_build_symmetric_hmat
Precalculate data tables for shape values at quadrature points.
Note
Precalculate shape function values and their gradient values at each quadrature point. N.B.
The data tables for shape function values and their gradient values should be calculated for both function space on \(K_x\) and function space on \(K_y\).
Being different from the integral in FEM, the integral in BEM handled by Sauter's quadrature rule has multiple parts of \(k_3\) (except the regular cell neighboring type), each of which should be evaluated at a different set of quadrature points in the unit cell after coordinate transformation from the parametric space. Therefore, a dimension with respect to \(k_3\) term index should be added to the data table compared to the usual FEValues and this brings about the class BEMValues.
Copy the precalculated BEM values to the GPU device.
Release BEM values on the GPU device.
Definition at line 8871 of file aca_plus.hcu.
References HMatrix< spacedim, Number >::compute_near_field_leaf_set_assembly_task_costs(), BEMValues< dim, spacedim, RangeNumberType >::fill_shape_function_value_tables(), and print_wall_time().
fill_hmatrix_with_aca_plus_smp() [3/3]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > void fill_hmatrix_with_aca_plus_smp (const unsigned int thread_num, HMatrix< spacedim, RangeNumberType > & hmat, const ACAConfig< typename numbers::NumberTraits< RangeNumberType >::real_type > & aca_config, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const typename numbers::NumberTraits< RangeNumberType >::real_type mass_matrix_factor, const DoFToCellTopology< dim, spacedim > & kx_dof_to_cell_topo, const DoFToCellTopology< dim, spacedim > & ky_dof_to_cell_topo, const SauterQuadratureRule< dim > & sauter_quad_rule, const QGauss< dim > & mass_matrix_quadrature_formula, const DoFHandler< dim, spacedim > & kx_dof_handler, const DoFHandler< dim, spacedim > & ky_dof_handler, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, const bool enable_build_symmetric_hmat = false)
Fill the leaf set of the \(\mathcal{H}\)-matrix using ACA+, where the hierarchical structure of the \(\mathcal{H}\)-matrix has been built with respect to a block cluster tree and the memory for the matrices in the leaf set has been allocated.
In the mean time, the FEM mass matrix multiplied by a factor will be added to the near field matrix block.
For the near field matrices in the leaf set, full matrices will be built whose elements will be obtained from the evaluation of the double integral in Galerkin-BEM. For the far field admissible matrices in the leaf set, rank-k matrices will be built using ACA+.
Note
For the near field leaf set, GPU parallelization is realized in a producer-consumer model. GPU 1D thread grid is distributed over each Sauter quadrature task in the ring buffer.
For the far field leaf set, GPU 2D thread grid is distributed over each Sauter quadrature task in the X direction and each quadrature point in the Y direction. The quadrature tasks collected in the buffer are used to build a row or column vector.
Template Parameters
dim
spacedim
KernelFunctionType
RangeNumberType
KernelNumberType
SurfaceNormalDetector
Parameters
thread_num
hmat
aca_config
kernel
kernel_factor
mass_matrix_factor
kx_dof_to_cell_topo
ky_dof_to_cell_topo
sauter_quad_rule
mass_matrix_quadrature_formula
kx_dof_handler
ky_dof_handler
kx_map_from_local_to_full_dof_indices
ky_map_from_local_to_full_dof_indices
kx_dof_i2e_numbering
ky_dof_i2e_numbering
mappings
material_id_to_mapping_index
normal_detector
enable_build_symmetric_hmat
Precalculate data tables for shape values at quadrature points.
Note
Precalculate shape function values and their gradient values at each quadrature point. N.B.
The data tables for shape function values and their gradient values should be calculated for both function space on \(K_x\) and function space on \(K_y\).
Being different from the integral in FEM, the integral in BEM handled by Sauter's quadrature rule has multiple parts of \(k_3\) (except the regular cell neighboring type), each of which should be evaluated at a different set of quadrature points in the unit cell after coordinate transformation from the parametric space. Therefore, a dimension with respect to \(k_3\) term index should be added to the data table compared to the usual FEValues and this brings about the class BEMValues.
Copy the precalculated BEM values to the GPU device.
Release BEM values on the GPU device.
Definition at line 9318 of file aca_plus.hcu.
References HMatrix< spacedim, Number >::compute_near_field_leaf_set_assembly_task_costs(), BEMValues< dim, spacedim, RangeNumberType >::fill_shape_function_value_tables(), and print_wall_time().
generate_random_index()
size_type generate_random_index (const size_type a, const size_type b)
Generate a random non-negative integer in the specified range \([a,b]\) using the global random number engine rand_engine.
Parameters
a
b
Returns
Definition at line 43 of file aca_plus.cu.
Referenced by random_select_ref_column(), and random_select_ref_row().
random_select_ref_column() [1/5]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > size_type random_select_ref_column (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > & task_buffer, Vector< RangeNumberType > & col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > factor, std::forward_list< size_type > & remaining_col_indices, const size_type current_ref_col_index, const size_type pass_the_end_ref_col_index, const std::vector< types::global_dof_index > & row_dof_indices, const std::vector< types::global_dof_index > & col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
The array index used to access the std::forward_list remaining_col_indices.
The reference column index to be selected for the next ACA step.
The column DoF index corresponding to the selected reference column index for the next ACA step.
Get the next_ref_col_index'th column from the kernel evaluation.
When the extracted column vector is zero-valued, remove the corresponding column index from the remaining_col_indices and continue another try.
When the extracted column vector is not zero-valued, it is a valid choice. Hence, return the selected column index.
If there is only one column index left, there is no reference column can be selected. Then return the invalid reference column index.
Because the selected column for the next step is the same as the current reference column, try another valid selection.
Definition at line 2065 of file aca_plus.hcu.
References assemble_kernel_column(), erase_at(), generate_random_index(), size(), and value_at().
random_select_ref_column() [2/5]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > size_type random_select_ref_column (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > & task_buffer, Vector< RangeNumberType > & col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, std::forward_list< size_type > & remaining_col_indices, const size_type current_ref_col_index, const size_type pass_the_end_ref_col_index, const std::vector< types::global_dof_index > & row_dof_indices, const std::vector< types::global_dof_index > & col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
The array index used to access the std::forward_list remaining_col_indices.
The reference column index to be selected for the next ACA step.
The column DoF index corresponding to the selected reference column index for the next ACA step.
Get the next_ref_col_index'th column from the kernel evaluation.
When the extracted column vector is zero-valued, remove the corresponding column index from the remaining_col_indices and continue another try.
When the extracted column vector is not zero-valued, it is a valid choice. Hence, return the selected column index.
If there is only one column index left, there is no reference column can be selected. Then return the invalid reference column index.
Because the selected column for the next step is the same as the current reference column, try another valid selection.
Definition at line 2213 of file aca_plus.hcu.
References assemble_kernel_column(), erase_at(), generate_random_index(), size(), and value_at().
random_select_ref_column() [3/5]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > size_type random_select_ref_column (Vector< RangeNumberType > & col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > factor, std::forward_list< size_type > & remaining_col_indices, const size_type current_ref_col_index, const size_type pass_the_end_ref_col_index, const std::vector< types::global_dof_index > & row_dof_indices, const std::vector< types::global_dof_index > & col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > & scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Randomly select a reference column index from the remaining column indices for the next ACA step.
Note
The data type for DoF index is types::global_dof_index, while the data type for matrix row or column index is size_type, which is the unsigned version of blas::int.
Parameters
col_vector The selected reference column vector, the memory of which should be preallocated in order to reduce the number of times for memory allocation and releasing.
scratch
data
kernel
remaining_col_indices Remaining column indices to be checked and selected from, which are stored in a std::forward_list.
current_ref_col_index The current reference column index
pass_the_end_ref_col_index When this function cannot select a new reference column, return this invalid index.
row_dof_indices The list of DoF indices corresponding to the matrix rows
col_dof_indices The list of DoF indices corresponding to the matrix columns
dof_to_cell_topo DoF-to-cell topology
bem_values
kx_dof_handler
ky_dof_handler
kx_mapping
ky_mapping
Returns
The selected reference column index
The array index used to access the std::forward_list remaining_col_indices.
The reference column index to be selected for the next ACA step.
The column DoF index corresponding to the selected reference column index for the next ACA step.
Get the next_ref_col_index'th column from the kernel evaluation.
When the extracted column vector is zero-valued, remove the corresponding column index from the remaining_col_indices and continue another try.
When the extracted column vector is not zero-valued, it is a valid choice. Hence, return the selected column index.
If there is only one column index left, there is no reference column can be selected. Then return the invalid reference column index.
Because the selected column for the next step is the same as the current reference column, try another valid selection.
Definition at line 1733 of file aca_plus.hcu.
References assemble_kernel_column(), erase_at(), generate_random_index(), size(), and value_at().
random_select_ref_column() [4/5]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > size_type random_select_ref_column (Vector< RangeNumberType > & col_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, std::forward_list< size_type > & remaining_col_indices, const size_type current_ref_col_index, const size_type pass_the_end_ref_col_index, const std::vector< types::global_dof_index > & row_dof_indices, const std::vector< types::global_dof_index > & col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > & scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Randomly select a reference column index from the remaining column indices for the next ACA step.
Note
1. The data type for DoF index is types::global_dof_index, while the data type for matrix row or column index is size_type, which is the unsigned version of blas::int.
This version is especially for assembling the regularized hyper-singular matrix with the stabilization term.
Parameters
col_vector
kernel
kernel_factor
mass_vmult_weq
stabilization_factor
remaining_col_indices
current_ref_col_index
pass_the_end_ref_col_index When this function cannot select a new reference column, return this invalid index.
row_dof_indices
col_dof_indices
kx_dof_to_cell_topo
ky_dof_to_cell_topo
bem_values
kx_dof_handler
ky_dof_handler
kx_dof_i2e_numbering
ky_dof_i2e_numbering
kx_mapping
ky_mapping
scratch_data
copy_data
Returns
The array index used to access the std::forward_list remaining_col_indices.
The reference column index to be selected for the next ACA step.
The column DoF index corresponding to the selected reference column index for the next ACA step.
Get the next_ref_col_index'th column from the kernel evaluation.
When the extracted column vector is zero-valued, remove the corresponding column index from the remaining_col_indices and continue another try.
When the extracted column vector is not zero-valued, it is a valid choice. Hence, return the selected column index.
If there is only one column index left, there is no reference column can be selected. Then return the invalid reference column index.
Because the selected column for the next step is the same as the current reference column, try another valid selection.
Definition at line 1914 of file aca_plus.hcu.
References assemble_kernel_column(), erase_at(), generate_random_index(), size(), and value_at().
random_select_ref_column() [5/5]
template<typename RangeNumberType = double> size_type random_select_ref_column (Vector< RangeNumberType > & col_vector, const LAPACKFullMatrixExt< RangeNumberType > & A, std::forward_list< size_type > & remaining_col_indices, const size_type current_ref_col_index, const size_type pass_the_end_ref_col_index)
For debugging purpose: randomly select a reference column index from the remaining column indices for the next ACA step.
Parameters
col_vector The extracted column vector, the memory of which should be preallocated
A The full matrix for the current block, the rows of which are extracted
remaining_col_indices
current_ref_col_index
pass_the_end_ref_col_index When this function cannot select a new reference column, return this invalid index.
row_dof_indices
col_dof_indices
Returns
The array index used to access the std::forward_list remaining_col_indices.
The reference column index to be selected for the next ACA step.
When the extracted column vector is zero-valued, remove the corresponding column index from the remaining_col_indices and continue another try.
When the extracted column vector is not zero-valued, it is a valid choice. Hence, return the selected column index.
If there is only one column index left, there is no reference column can be selected. Then return the invalid reference column index.
Because the selected column for the next step is the same as the current reference column, try another valid selection.
Definition at line 2375 of file aca_plus.hcu.
References erase_at(), generate_random_index(), LAPACKFullMatrixExt< Number >::get_column(), size(), and value_at().
random_select_ref_row() [1/5]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > size_type random_select_ref_row (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > & task_buffer, Vector< RangeNumberType > & row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, std::forward_list< size_type > & remaining_row_indices, const size_type current_ref_row_index, const size_type pass_the_end_ref_row_index, const std::vector< types::global_dof_index > & row_dof_indices, const std::vector< types::global_dof_index > & col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
The array index used to access the std::forward_list remaining_row_indices.
The reference row index to be selected for the next ACA step.
The row DoF index corresponding to the selected reference row index for the next ACA step.
Get the next_ref_row_index'th row from the kernel evaluation.
When the extracted row vector is zero-valued, remove the corresponding row index from the remaining_row_indices and continue another try.
When the extracted row vector is not zero-valued, it is a valid choice. Hence, return the selected row index.
If there is only one row index left, there is no reference row can be selected. Then return the invalid reference row index.
Because the selected row for the next step is the same as the current reference row, try another valid selection.
Definition at line 1459 of file aca_plus.hcu.
References assemble_kernel_row(), erase_at(), generate_random_index(), size(), and value_at().
random_select_ref_row() [2/5]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > size_type random_select_ref_row (HierBEM::CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, DeviceNumberType< RangeNumberType >, DeviceNumberType< KernelNumberType > > & task_buffer, Vector< RangeNumberType > & row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, std::forward_list< size_type > & remaining_row_indices, const size_type current_ref_row_index, const size_type pass_the_end_ref_row_index, const std::vector< types::global_dof_index > & row_dof_indices, const std::vector< types::global_dof_index > & col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
The array index used to access the std::forward_list remaining_row_indices.
The reference row index to be selected for the next ACA step.
The row DoF index corresponding to the selected reference row index for the next ACA step.
Get the next_ref_row_index'th row from the kernel evaluation.
When the extracted row vector is zero-valued, remove the corresponding row index from the remaining_row_indices and continue another try.
When the extracted row vector is not zero-valued, it is a valid choice. Hence, return the selected row index.
If there is only one row index left, there is no reference row can be selected. Then return the invalid reference row index.
Because the selected row for the next step is the same as the current reference row, try another valid selection.
Definition at line 1312 of file aca_plus.hcu.
References assemble_kernel_row(), erase_at(), generate_random_index(), size(), and value_at().
random_select_ref_row() [3/5]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > size_type random_select_ref_row (Vector< RangeNumberType > & row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, std::forward_list< size_type > & remaining_row_indices, const size_type current_ref_row_index, const size_type pass_the_end_ref_row_index, const std::vector< types::global_dof_index > & row_dof_indices, const std::vector< types::global_dof_index > & col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > & scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Randomly select a reference row index from the remaining row indices for the next ACA step.
Note
1. The data type for DoF index is types::global_dof_index, while the data type for matrix row or column index is size_type, which is the unsigned version of blas::int.
This version is especially for assembling the regularized hyper-singular matrix with the stabilization term.
Parameters
row_vector
kernel
kernel_factor
mass_vmult_weq
stabilization_factor
remaining_row_indices
current_ref_row_index
pass_the_end_ref_row_index When this function cannot select a new reference row, return this invalid index.
row_dof_indices
col_dof_indices
kx_dof_to_cell_topo
ky_dof_to_cell_topo
bem_values
kx_dof_handler
ky_dof_handler
kx_dof_i2e_numbering
ky_dof_i2e_numbering
kx_mapping
ky_mapping
scratch_data
copy_data
Returns
The selected reference row index with respect to the matrix block, i.e. matrix block index.
The array index used to access the std::forward_list remaining_row_indices.
The reference row index to be selected for the next ACA step.
The row DoF index corresponding to the selected reference row index for the next ACA step.
Get the next_ref_row_index'th row from the kernel evaluation.
When the extracted row vector is zero-valued, remove the corresponding row index from the remaining_row_indices and continue another try.
When the extracted row vector is not zero-valued, it is a valid choice. Hence, return the selected row index.
If there is only one row index left, there is no reference row can be selected. Then return the invalid reference row index.
Because the selected row for the next step is the same as the current reference row, try another valid selection.
Definition at line 1162 of file aca_plus.hcu.
References assemble_kernel_row(), erase_at(), generate_random_index(), size(), and value_at().
random_select_ref_row() [4/5]
template<int dim, int spacedim, template< int, typename > typename KernelFunctionType, typename RangeNumberType , typename KernelNumberType , typename SurfaceNormalDetector > size_type random_select_ref_row (Vector< RangeNumberType > & row_vector, const KernelFunctionType< spacedim, DeviceNumberType< KernelNumberType > > & kernel, const DeviceNumberType< KernelNumberType > kernel_factor, std::forward_list< size_type > & remaining_row_indices, const size_type current_ref_row_index, const size_type pass_the_end_ref_row_index, const std::vector< types::global_dof_index > & row_dof_indices, const std::vector< types::global_dof_index > & col_dof_indices, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & kx_dof_to_cell_topo, const std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & ky_dof_to_cell_topo, const HierBEM::CUDAWrappers::CUDABEMValues< dim, spacedim, typename numbers::NumberTraits< RangeNumberType >::real_type > & bem_values_gpu, const std::vector< types::global_dof_index > * kx_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > * ky_map_from_local_to_full_dof_indices, const std::vector< types::global_dof_index > & kx_dof_i2e_numbering, const std::vector< types::global_dof_index > & ky_dof_i2e_numbering, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const std::map< types::material_id, unsigned int > & material_id_to_mapping_index, const SurfaceNormalDetector & normal_detector, PairCellWiseScratchData< dim, spacedim, KernelNumberType > & scratch_data, HierBEM::CUDAWrappers::CUDAPairCellWiseScratchData< dim, spacedim, DeviceNumberType< KernelNumberType > > & scratch_data_gpu, PairCellWisePerTaskData< dim, spacedim, KernelNumberType > & copy_data)
Randomly select a reference row index from the remaining row indices for the next ACA step.
Note
The data type for DoF index is types::global_dof_index, while the data type for matrix row or column index is size_type, which is the unsigned version of blas::int.
Parameters
row_vector The selected reference row vector, the memory of which should be preallocated in order to reduce the number of times for memory allocation and releasing.
scratch
data
kernel
remaining_row_indices Remaining row indices to be checked and selected from, which are stored in a std::forward_list.
current_ref_row_index The current reference row index
pass_the_end_ref_row_index When this function cannot select a new reference row, return this invalid index.
row_dof_indices The list of DoF indices corresponding to the matrix rows
col_dof_indices The list of DoF indices corresponding to the matrix columns
dof_to_cell_topo DoF-to-cell topology
bem_values
kx_dof_handler
ky_dof_handler
kx_mapping
ky_mapping
Returns
The selected reference row index with respect to the matrix block, i.e. matrix block index.
The array index used to access the std::forward_list remaining_row_indices.
The reference row index to be selected for the next ACA step.
The row DoF index corresponding to the selected reference row index for the next ACA step.
Get the next_ref_row_index'th row from the kernel evaluation.
When the extracted row vector is zero-valued, remove the corresponding row index from the remaining_row_indices and continue another try.
When the extracted row vector is not zero-valued, it is a valid choice. Hence, return the selected row index.
If there is only one row index left, there is no reference row can be selected. Then return the invalid reference row index.
Because the selected row for the next step is the same as the current reference row, try another valid selection.
Definition at line 981 of file aca_plus.hcu.
References assemble_kernel_row(), erase_at(), generate_random_index(), size(), and value_at().
random_select_ref_row() [5/5]
template<typename RangeNumberType = double> size_type random_select_ref_row (Vector< RangeNumberType > & row_vector, const LAPACKFullMatrixExt< RangeNumberType > & A, std::forward_list< size_type > & remaining_row_indices, const size_type current_ref_row_index, const size_type pass_the_end_ref_row_index)
For debugging purpose: randomly select a reference row index from the remaining row indices for the next ACA step.
Parameters
row_vector The extracted row vector, the memory of which should be preallocated
A The full matrix for the current block, the rows of which are extracted
remaining_row_indices
current_ref_row_index
pass_the_end_ref_row_index When this function cannot select a new reference row, return this invalid index.
row_dof_indices
col_dof_indices
Returns
The row index with respect to the matrix block, i.e. matrix block index.
The array index used to access the std::forward_list remaining_row_indices.
The reference row index to be selected for the next ACA step.
When the extracted row vector is zero-valued, remove the corresponding row index from the remaining_row_indices and continue another try.
When the extracted row vector is not zero-valued, it is a valid choice. Hence, return the selected row index.
If there is only one row index left, there is no reference row can be selected. Then return the invalid reference row index.
Because the selected row for the next step is the same as the current reference row, try another valid selection.
Definition at line 1621 of file aca_plus.hcu.
References erase_at(), generate_random_index(), LAPACKFullMatrixExt< Number >::get_row(), size(), and value_at().
stabilize_near_field_hmatrices_for_hypersingular_kernel()
template<int spacedim, typename RangeNumberType , typename KernelNumberType > void stabilize_near_field_hmatrices_for_hypersingular_kernel (const tbb::blocked_range< typename std::vector< HMatrix< spacedim, RangeNumberType > * >::iterator > & range, const std::vector< Vector< KernelNumberType > > & mass_vmult_weq, const KernelNumberType stabilization_factor, const bool enable_build_symmetric_hmat = true)
Add the stabilization matrix for the bilinear form of the hyper-singular kernel to the range of near field matrices. The stabilization matrix is \(\alpha a a^T\), where \(a = M w_{\rm eq}\) as a column vector is the multiplication of FEM mass matrix and the natural density.
Template Parameters
spacedim
RangeNumberType
Parameters
range
mass_vmult_weq
stabilization_factor
enable_build_symmetric_hmat
Definition at line 7744 of file aca_plus.hcu.
References FullMatrixType, HMatrix< spacedim, Number >::get_block_type(), HMatrix< spacedim, Number >::get_col_index_range(), HMatrix< spacedim, Number >::get_fullmatrix(), HMatrix< spacedim, Number >::get_property(), LAPACKFullMatrixExt< Number >::get_property(), HMatrix< spacedim, Number >::get_row_index_range(), and HMatrix< spacedim, Number >::get_type().
Variable Documentation
rand_engine
std::mt19937 rand_engine extern
Global declaration of the random number device and engine.
Definition at line 38 of file aca_plus.cu.