HierBEM: include/bem/bem_tools.h File Reference
bem_tools.h File Reference
Introduction of bem_tools.h.
#include <deal.II/base/derivative_form.h>
#include <deal.II/base/point.h>
#include <deal.II/base/subscriptor.h>
#include <deal.II/base/table.h>
#include <deal.II/base/table_indices.h>
#include <deal.II/base/utilities.h>
#include <deal.II/dofs/dof_accessor.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/fe/fe.h>
#include <deal.II/fe/fe_data.h>
#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/fe_tools.h>
#include <deal.II/fe/fe_values.h>
#include <deal.II/fe/mapping_q.h>
#include <deal.II/grid/tria.h>
#include <deal.II/lac/full_matrix.templates.h>
#include <assert.h>
#include <algorithm>
#include <array>
#include <cmath>
#include <map>
#include <utility>
#include <vector>
#include "config.h"
#include "linear_algebra/lapack_full_matrix_ext.h"
#include "mapping/mapping_q_ext.h"
#include "utilities/generic_functors.h"
Enumerations
enum BEMTools::CellNeighboringType {
BEMTools::SamePanel , BEMTools::CommonEdge , BEMTools::CommonVertex , BEMTools::Regular ,
BEMTools::None
}
enum BEMTools::DetectCellNeighboringTypeMethod { BEMTools::SameTriangulations , BEMTools::DifferentTriangulations }
Functions
const char * BEMTools::cell_neighboring_type_name (CellNeighboringType n)
template<typename VectorType1 , typename VectorType2 , typename IndexType >
void BEMTools::permute_vector (const VectorType1 &input_vector, const std::vector< IndexType > &permutation_indices, VectorType2 &permuted_vector)
Permute a vector by using the given permutation indices to access its elements.
template<int dim, int spacedim = dim>
std::vector< types::global_dof_index > BEMTools::get_conflict_indices (const typename DoFHandler< dim, spacedim >::active_cell_iterator &cell)
template<int dim, int spacedim = dim>
unsigned int BEMTools::get_vertex_local_index_in_cell (const Point< spacedim > &v, const typename Triangulation< dim, spacedim >::cell_iterator &cell)
template<int dim, int spacedim = dim>
unsigned int BEMTools::get_vertex_local_index_in_cell (const Point< spacedim > &v, const typename Triangulation< dim, spacedim >::cell_iterator &cell, const double threshold)
template<int dim, int spacedim = dim>
std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_cell > BEMTools::get_vertex_indices_in_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell)
template<int dim, int spacedim = dim>
void BEMTools::get_vertex_indices_in_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell, std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_cell > &cell_vertex_indices)
template<int dim, int spacedim = dim>
std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_face > BEMTools::get_vertex_indices_in_face (const typename Triangulation< dim, spacedim >::face_iterator &face)
template<int dim, int spacedim = dim>
void BEMTools::get_vertex_indices_in_face (const typename Triangulation< dim, spacedim >::face_iterator &face, std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_face > &face_vertex_indices)
template<int dim, int spacedim, typename Number = double>
Number BEMTools::cell_distance (const typename Triangulation< dim, spacedim >::cell_iterator first_cell, const typename Triangulation< dim, spacedim >::cell_iterator second_cell)
template<int dim, int spacedim, typename RangeNumberType = double>
LAPACKFullMatrixExt< RangeNumberType > BEMTools::shape_grad_matrix (const FiniteElement< dim, spacedim > &fe, const std::vector< unsigned int > &dof_permutation, const Point< dim > &p)
template<int dim, int spacedim, typename RangeNumberType = double>
void BEMTools::mappingq_shape_grad_matrix (const typename MappingQ< dim, spacedim >::InternalData &mapping_data, const unsigned int point_no, LAPACKFullMatrixExt< RangeNumberType > &grad_matrix)
template<int dim, int spacedim, typename RangeNumberType = double>
LAPACKFullMatrixExt< RangeNumberType > BEMTools::shape_grad_matrix_in_default_dof_order (const FiniteElement< dim, spacedim > &fe, const Point< dim > &p)
template<int dim, int spacedim, typename RangeNumberType = double>
LAPACKFullMatrixExt< RangeNumberType > BEMTools::shape_grad_matrix_in_lexicographic_order (const FiniteElement< dim, spacedim > &fe, const Point< dim > &p)
template<int dim, int spacedim, typename RangeNumberType = double>
Vector< RangeNumberType > BEMTools::shape_values (const FiniteElement< dim, spacedim > &fe, const std::vector< unsigned int > &dof_permutation, const Point< dim > &p)
template<int dim, int spacedim, typename RangeNumberType = double>
Vector< RangeNumberType > BEMTools::shape_values_in_default_dof_order (const FiniteElement< dim, spacedim > &fe, const Point< dim > &p)
template<int dim, int spacedim, typename RangeNumberType = double>
Vector< RangeNumberType > BEMTools::shape_values_in_lexicographic_order (const FiniteElement< dim, spacedim > &fe, const Point< dim > &p)
template<int spacedim, typename RangeNumberType = double>
LAPACKFullMatrixExt< RangeNumberType > BEMTools::collect_two_components_from_point3 (const std::vector< Point< spacedim, RangeNumberType > > &points, const unsigned int first_component, const unsigned int second_component)
template<int spacedim, typename RangeNumberType = double>
LAPACKFullMatrixExt< RangeNumberType > BEMTools::collect_two_components_from_point3 (const std::vector< Point< spacedim, RangeNumberType > > &points, const unsigned int effective_point_num, const unsigned int first_component, const unsigned int second_component)
template<int spacedim, typename RangeNumberType = double>
LAPACKFullMatrixExt< RangeNumberType > BEMTools::collect_components_from_points (const std::vector< Point< spacedim, RangeNumberType > > &points)
template<int spacedim, typename RangeNumberType = double>
LAPACKFullMatrixExt< RangeNumberType > BEMTools::collect_components_from_points (const std::vector< Point< spacedim, RangeNumberType > > &points, const unsigned int point_num)
template<int dim, int spacedim = dim>
std::vector< Point< dim > > BEMTools::get_unit_support_points_with_permutation (const FiniteElement< dim, spacedim > &fe, const std::vector< unsigned int > &dof_permutation)
template<int dim, int spacedim = dim>
void BEMTools::get_unit_support_points_with_permutation (const FiniteElement< dim, spacedim > &fe, const std::vector< unsigned int > &dof_permutation, std::vector< Point< dim > > &permuted_unit_support_points)
template<int dim, int spacedim = dim>
std::vector< Point< dim > > BEMTools::get_lexicographic_unit_support_points (const FiniteElement< dim, spacedim > &fe)
template<int dim, int spacedim = dim>
void BEMTools::get_lexicographic_unit_support_points (const FiniteElement< dim, spacedim > &fe, std::vector< Point< dim > > &lexicographic_unit_support_points)
template<int dim, int spacedim = dim>
std::vector< Point< spacedim > > BEMTools::get_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const FiniteElement< dim, spacedim > &fe, const MappingQ< dim, spacedim > &mapping, const std::vector< unsigned int > &dof_permutation)
template<int dim, int spacedim = dim>
void BEMTools::get_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const FiniteElement< dim, spacedim > &fe, const MappingQ< dim, spacedim > &mapping, const std::vector< unsigned int > &dof_permutation, std::vector< Point< spacedim > > &support_points_in_real_cell)
template<int dim, int spacedim>
std::vector< Point< spacedim > > BEMTools::get_support_points_in_default_dof_order_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const FiniteElement< dim, spacedim > &fe, const MappingQ< dim, spacedim > &mapping)
template<int dim, int spacedim>
void BEMTools::get_support_points_in_default_dof_order_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const FiniteElement< dim, spacedim > &fe, const MappingQ< dim, spacedim > &mapping, std::vector< Point< spacedim > > &support_points_in_reall_cell)
template<int dim, int spacedim>
std::vector< Point< spacedim > > BEMTools::get_lexicographic_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const FiniteElement< dim, spacedim > &fe, const MappingQ< dim, spacedim > &mapping)
template<int dim, int spacedim>
void BEMTools::get_lexicographic_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const FiniteElement< dim, spacedim > &fe, const MappingQ< dim, spacedim > &mapping, std::vector< Point< spacedim > > &support_points_in_real_cell)
template<int dim, int spacedim = dim>
unsigned int BEMTools::get_dofs_per_face_for_fe (const FiniteElement< dim, spacedim > &fe)
template<int dim, int spacedim>
std::array< Point< dim >, GeometryInfo< dim >::vertices_per_cell > BEMTools::get_vertices_from_lexicographic_unit_support_points (const FiniteElement< dim, spacedim > &fe, const bool is_counter_clockwise_ordered=false)
template<int dim, int spacedim>
void BEMTools::get_vertices_from_lexicographic_unit_support_points (const FiniteElement< dim, spacedim > &fe, std::array< Point< dim >, GeometryInfo< dim >::vertices_per_cell > &vertices, const bool is_counter_clockwise_ordered=false)
template<int dim, int spacedim>
std::array< Point< spacedim >, GeometryInfo< dim >::vertices_per_cell > BEMTools::get_vertices_from_lexicographic_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const FiniteElement< dim, spacedim > &fe, const Mapping< dim, spacedim > &mapping, const bool is_counter_clockwise_ordered=false)
template<int dim, int spacedim>
void BEMTools::get_vertices_from_lexicographic_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const FiniteElement< dim, spacedim > &fe, const Mapping< dim, spacedim > &mapping, std::array< Point< spacedim >, GeometryInfo< dim >::vertices_per_cell > &vertices_in_real_cell, const bool is_counter_clockwise_ordered=false)
template<int dim, int spacedim>
std::vector< types::global_dof_index > BEMTools::get_lexicographic_dof_indices (const typename DoFHandler< dim, spacedim >::cell_iterator &cell)
template<int dim, int spacedim>
void BEMTools::get_lexicographic_dof_indices (const typename DoFHandler< dim, spacedim >::cell_iterator &cell, std::vector< types::global_dof_index > &lexicographic_dof_indices)
template<int dim, int spacedim>
std::vector< types::global_dof_index > BEMTools::get_vertex_dof_indices_from_lexicographic_dof_indices (const typename DoFHandler< dim, spacedim >::cell_iterator &cell, const bool is_counter_clockwise_ordered=false)
template<int dim, int spacedim = dim>
void BEMTools::get_vertex_dof_indices_from_lexicographic_dof_indices (const typename DoFHandler< dim, spacedim >::cell_iterator &cell, std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > &vertex_dof_indices, const bool is_counter_clockwise_ordered=false)
template<int dim, int spacedim>
std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > BEMTools::get_vertex_dof_indices_in_cell (const typename DoFHandler< dim, spacedim >::cell_iterator &cell, const Mapping< dim, spacedim > &mapping, const double threshold=1e-12)
template<int dim, int spacedim>
void BEMTools::get_vertex_dof_indices_in_cell (const typename DoFHandler< dim, spacedim >::cell_iterator &cell, const Mapping< dim, spacedim > &mapping, std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > &cell_vertex_dof_indices, const double threshold=1e-12)
template<int dim, int spacedim>
types::global_dof_index BEMTools::get_dof_index_for_vertex_in_cell (const typename DoFHandler< dim, spacedim >::cell_iterator &cell, const Mapping< dim, spacedim > &mapping, const unsigned int local_vertex_index_in_cell, const double threshold=1e-12)
template<int dim>
CellNeighboringType BEMTools::detect_cell_neighboring_type_for_same_triangulations (const std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_cell > &first_cell_vertex_indices, const std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_cell > &second_cell_vertex_indices, std::vector< types::global_vertex_index > &common_vertex_indices)
template<int dim, int spacedim>
CellNeighboringType BEMTools::detect_cell_neighboring_type_for_same_triangulations (const typename Triangulation< dim, spacedim >::active_cell_iterator &first_cell_iter, const typename Triangulation< dim, spacedim >::active_cell_iterator &second_cell_iter, std::vector< std::pair< unsigned int, unsigned int > > &common_vertex_pair_local_indices)
template<int dim, int spacedim = dim>
CellNeighboringType BEMTools::detect_cell_neighboring_type_for_same_triangulations (const typename DoFHandler< dim, spacedim >::active_cell_iterator &first_cell_iter, const typename DoFHandler< dim, spacedim >::active_cell_iterator &second_cell_iter, const Mapping< dim, spacedim > &first_cell_mapping, const Mapping< dim, spacedim > &second_cell_mapping, std::vector< std::pair< types::global_dof_index, types::global_dof_index > > &common_vertex_pair_dof_indices, const double threshold=1e-12)
template<int dim, int spacedim>
CellNeighboringType BEMTools::detect_cell_neighboring_type_for_different_triangulations (const typename Triangulation< dim, spacedim >::active_cell_iterator &first_cell_iter, const typename Triangulation< dim, spacedim >::active_cell_iterator &second_cell_iter, const std::map< typename Triangulation< dim, spacedim >::cell_iterator, typename Triangulation< dim+1, spacedim >::face_iterator > &map_from_first_boundary_mesh_to_volume_mesh, const std::map< typename Triangulation< dim, spacedim >::cell_iterator, typename Triangulation< dim+1, spacedim >::face_iterator > &map_from_second_boundary_mesh_to_volume_mesh, std::vector< std::pair< unsigned int, unsigned int > > &common_vertex_pair_local_indices)
template<int dim, int spacedim = dim>
CellNeighboringType BEMTools::detect_cell_neighboring_type_for_different_triangulations (const typename DoFHandler< dim, spacedim >::active_cell_iterator &first_cell_iter, const typename DoFHandler< dim, spacedim >::active_cell_iterator &second_cell_iter, const Mapping< dim, spacedim > &first_cell_mapping, const Mapping< dim, spacedim > &second_cell_mapping, const std::map< typename Triangulation< dim, spacedim >::cell_iterator, typename Triangulation< dim+1, spacedim >::face_iterator > &map_from_first_boundary_mesh_to_volume_mesh, const std::map< typename Triangulation< dim, spacedim >::cell_iterator, typename Triangulation< dim+1, spacedim >::face_iterator > &map_from_second_boundary_mesh_to_volume_mesh, std::vector< std::pair< types::global_dof_index, types::global_dof_index > > &common_vertex_pair_dof_indices, const double threshold=1e-12)
template<int dim>
CellNeighboringType BEMTools::detect_cell_neighboring_type_for_same_h1_dofhandlers (const std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > &first_cell_vertex_dof_indices, const std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > &second_cell_vertex_dof_indices, std::vector< types::global_dof_index > &vertex_dof_index_intersection)
template<int dim, int spacedim = dim>
CellNeighboringType BEMTools::detect_cell_neighboring_type_for_same_dofhandlers (const typename DoFHandler< dim, spacedim >::active_cell_iterator &first_cell_iter, const typename DoFHandler< dim, spacedim >::active_cell_iterator &second_cell_iter, const Mapping< dim, spacedim > &first_cell_mapping, const Mapping< dim, spacedim > &second_cell_mapping, std::vector< std::pair< types::global_dof_index, types::global_dof_index > > &common_vertex_pair_dof_indices, const double threshold=1e-12)
template<int dim, int spacedim>
CellNeighboringType BEMTools::detect_cell_neighboring_type (const DetectCellNeighboringTypeMethod method_for_cell_neighboring_type, const typename Triangulation< dim, spacedim >::cell_iterator &first_cell_iter, const typename Triangulation< dim, spacedim >::cell_iterator &second_cell_iter, const std::map< typename Triangulation< dim, spacedim >::cell_iterator, typename Triangulation< dim+1, spacedim >::face_iterator > &map_from_first_boundary_mesh_to_volume_mesh, const std::map< typename Triangulation< dim, spacedim >::cell_iterator, typename Triangulation< dim+1, spacedim >::face_iterator > &map_from_second_boundary_mesh_to_volume_mesh, std::vector< std::pair< unsigned int, unsigned int > > &common_vertex_pair_local_indices)
template<int spacedim>
double BEMTools::surface_jacobian_det (const unsigned int k3_index, const unsigned int quad_no, const Table< 2, LAPACKFullMatrixExt< double > > &shape_grad_matrix_table, const std::vector< Point< spacedim > > &support_points_in_real_cell)
template<int spacedim, typename RangeNumberType = double>
RangeNumberType BEMTools::surface_jacobian_det_and_normal_vector (const unsigned int k3_index, const unsigned int quad_no, const Table< 3, LAPACKFullMatrixExt< RangeNumberType > > &mapping_shape_grad_matrix_table, const unsigned int mapping_index, const unsigned int mapping_n_shape_functions, const std::vector< Point< spacedim, RangeNumberType > > &support_points_in_real_cell, Tensor< 1, spacedim, RangeNumberType > &normal_vector, const bool is_normal_vector_negated=false)
template<int spacedim, typename RangeNumberType = double>
RangeNumberType BEMTools::surface_jacobian_det_and_normal_vector (const std::vector< Point< spacedim, RangeNumberType > > &mapping_support_points, const LAPACKFullMatrixExt< RangeNumberType > &mapping_shape_grad_matrix, Tensor< 1, spacedim, RangeNumberType > &normal_vector, const bool is_normal_vector_negated=false)
template<int spacedim, typename RangeNumberType = double>
LAPACKFullMatrixExt< RangeNumberType > BEMTools::surface_covariant_transformation (const unsigned int k3_index, const unsigned int quad_no, const Table< 3, LAPACKFullMatrixExt< RangeNumberType > > &mapping_shape_grad_matrix_table, const unsigned int mapping_index, const unsigned int mapping_n_shape_functions, const std::vector< Point< spacedim, RangeNumberType > > &support_points_in_real_cell)
template<int spacedim, typename RangeNumberType = double>
Point< spacedim, RangeNumberType > BEMTools::transform_quad_point_from_unit_to_permuted_real_cell (const unsigned int k3_index, const unsigned int quad_no, const Table< 4, RangeNumberType > &mapping_shape_value_table, const unsigned int mapping_index, const unsigned int mapping_n_shape_functions, const std::vector< Point< spacedim, RangeNumberType > > &mapping_support_points_in_real_cell)
template<int dim, int spacedim>
std::vector< unsigned int > BEMTools::generate_forward_dof_permutation (const FiniteElement< dim, spacedim > &fe, unsigned int starting_corner)
template<int dim, int spacedim>
void BEMTools::generate_forward_dof_permutation (const FiniteElement< dim, spacedim > &fe, unsigned int starting_corner, std::vector< unsigned int > &dof_permutation)
template<int dim, int spacedim>
std::vector< unsigned int > BEMTools::generate_forward_mapping_support_point_permutation (const MappingQExt< dim, spacedim > &mapping, unsigned int starting_corner)
template<int dim, int spacedim>
void BEMTools::generate_forward_mapping_support_point_permutation (const MappingQExt< dim, spacedim > &mapping, unsigned int starting_corner, std::vector< unsigned int > &support_point_permutation)
template<int dim, int spacedim>
std::vector< unsigned int > BEMTools::generate_backward_dof_permutation (const FiniteElement< dim, spacedim > &fe, unsigned int starting_corner)
template<int dim, int spacedim>
void BEMTools::generate_backward_dof_permutation (const FiniteElement< dim, spacedim > &fe, unsigned int starting_corner, std::vector< unsigned int > &dof_permutation)
template<int dim, int spacedim>
std::vector< unsigned int > BEMTools::generate_backward_mapping_support_point_permutation (const MappingQExt< dim, spacedim > &mapping, unsigned int starting_corner)
template<int dim, int spacedim>
void BEMTools::generate_backward_mapping_support_point_permutation (const MappingQExt< dim, spacedim > &mapping, unsigned int starting_corner, std::vector< unsigned int > &support_point_permutation)
Detailed Description
Introduction of bem_tools.h.
Date
2022-03-03
Author
Jihuan Tian
Definition in file bem_tools.h.
Enumeration Type Documentation
CellNeighboringType
enum BEMTools::CellNeighboringType
Different cell neighboring types
Enumerator
SamePanel
SamePanel.
CommonEdge
CommonEdge.
CommonVertex
CommonVertex.
Regular
Regular.
None
None.
Definition at line 65 of file bem_tools.h.
DetectCellNeighboringTypeMethod
enum BEMTools::DetectCellNeighboringTypeMethod
Different scenarios for detecting cell neighboring types
Enumerator
SameTriangulations
SameTriangulations.
DifferentTriangulations
DifferentTriangulations.
Definition at line 78 of file bem_tools.h.
Function Documentation
cell_distance()
template<int dim, int spacedim, typename Number = double> Number BEMTools::cell_distance (const typename Triangulation< dim, spacedim >::cell_iterator first_cell, const typename Triangulation< dim, spacedim >::cell_iterator second_cell)
Calculate the distance between the centers of two cells.
Parameters
first_cell
second_cell
Returns
Definition at line 335 of file bem_tools.h.
References BEMTools::cell_distance().
Referenced by BEMTools::cell_distance().
cell_neighboring_type_name()
const char * BEMTools::cell_neighboring_type_name (CellNeighboringType n) inline
Get the string representation of the cell neighboring type.
Parameters
s
Returns
Definition at line 92 of file bem_tools.h.
References BEMTools::cell_neighboring_type_name().
Referenced by CUDAWrappers::SauterQuadratureTaskRingBuffer< capacity, dim, spacedim, RangeNumberType, KernelNumberType >::add_task(), BEMTools::cell_neighboring_type_name(), and CUDAWrappers::SauterQuadratureTaskRingBuffer< capacity, dim, spacedim, RangeNumberType, KernelNumberType >::fetch_and_process_task_batch().
collect_components_from_points() [1/2]
template<int spacedim, typename RangeNumberType = double> LAPACKFullMatrixExt< RangeNumberType > BEMTools::collect_components_from_points (const std::vector< Point< spacedim, RangeNumberType > > & points)
Collect coordinate components from the list of points in \(\mathbb{R}^d\). The obtained coordinate matrix has this format:
\[ \begin{pmatrix} x_1(1) & \cdots & x_1(k) \\ \vdots & \vdots & \vdots \\ x_d(1) & \cdots & x_d(k) \end{pmatrix} \]
where \(k\) is the number of points and \(x(i)\) is the i-th point in the list.
Note
This function will be used for calculating the Jacobian matrix. Let \(DN\) be the matrix of first order derivatives of shape functions and \(P\) be the resulted coordinate matrix. Then [ J = P \cdot DN ]
Parameters
points
Returns
Definition at line 679 of file bem_tools.h.
References BEMTools::collect_components_from_points().
Referenced by BEMTools::collect_components_from_points(), and BEMTools::surface_covariant_transformation().
collect_components_from_points() [2/2]
template<int spacedim, typename RangeNumberType = double> LAPACKFullMatrixExt< RangeNumberType > BEMTools::collect_components_from_points (const std::vector< Point< spacedim, RangeNumberType > > & points, const unsigned int point_num)
This overloaded function only use the first point_num number of points.
Precondition
Postcondition
Template Parameters
spacedim
Parameters
points
point_num
Returns
Definition at line 708 of file bem_tools.h.
References BEMTools::collect_components_from_points().
collect_two_components_from_point3() [1/2]
template<int spacedim, typename RangeNumberType = double> LAPACKFullMatrixExt< RangeNumberType > BEMTools::collect_two_components_from_point3 (const std::vector< Point< spacedim, RangeNumberType > > & points, const unsigned int effective_point_num, const unsigned int first_component, const unsigned int second_component)
Collect two coordinate components from the list of points in 3D space. Only the first effective_point_num will be used.
Note
This function is useful in constructing the surface metric tensor or surface normal vector.
Parameters
points A list of points in 3D space
effective_point_num Number of points to be used.
first_component Index for the first coordinate component to be collected
second_component Index for the second coordinate component to be collected
Returns
A matrix storing the two coordinate components for all points. It has a dimension 2*points.size().
Definition at line 631 of file bem_tools.h.
References BEMTools::collect_two_components_from_point3().
collect_two_components_from_point3() [2/2]
template<int spacedim, typename RangeNumberType = double> LAPACKFullMatrixExt< RangeNumberType > BEMTools::collect_two_components_from_point3 (const std::vector< Point< spacedim, RangeNumberType > > & points, const unsigned int first_component, const unsigned int second_component)
Collect two coordinate components from the list of points in 3D space.
Note
This function is useful in constructing the surface metric tensor or surface normal vector.
Parameters
points A list of points in 3D space
first_component Index for the first coordinate component to be collected
second_component Index for the second coordinate component to be collected
Returns
A matrix storing the two coordinate components for all points. It has a dimension 2*points.size().
Definition at line 593 of file bem_tools.h.
References BEMTools::collect_two_components_from_point3().
Referenced by BEMTools::collect_two_components_from_point3(), BEMTools::surface_jacobian_det(), and BEMTools::surface_jacobian_det_and_normal_vector().
detect_cell_neighboring_type()
template<int dim, int spacedim> CellNeighboringType BEMTools::detect_cell_neighboring_type (const DetectCellNeighboringTypeMethod method_for_cell_neighboring_type, const typename Triangulation< dim, spacedim >::cell_iterator & first_cell_iter, const typename Triangulation< dim, spacedim >::cell_iterator & second_cell_iter, const std::map< typename Triangulation< dim, spacedim >::cell_iterator, typename Triangulation< dim+1, spacedim >::face_iterator > & map_from_first_boundary_mesh_to_volume_mesh, const std::map< typename Triangulation< dim, spacedim >::cell_iterator, typename Triangulation< dim+1, spacedim >::face_iterator > & map_from_second_boundary_mesh_to_volume_mesh, std::vector< std::pair< unsigned int, unsigned int > > & common_vertex_pair_local_indices)
Detect the neighboring type of two cells based on their vertex indices.
Parameters
method_for_cell_neighboring_type
first_cell_iter
second_cell_iter
map_from_first_boundary_mesh_to_volume_mesh
map_from_second_boundary_mesh_to_volume_mesh
common_vertex_pair_local_indices
Returns
Definition at line 2914 of file bem_tools.h.
References BEMTools::detect_cell_neighboring_type(), BEMTools::detect_cell_neighboring_type_for_different_triangulations(), and BEMTools::detect_cell_neighboring_type_for_same_triangulations().
Referenced by BEMTools::detect_cell_neighboring_type().
detect_cell_neighboring_type_for_different_triangulations() [1/2]
template<int dim, int spacedim = dim> CellNeighboringType BEMTools::detect_cell_neighboring_type_for_different_triangulations (const typename DoFHandler< dim, spacedim >::active_cell_iterator & first_cell_iter, const typename DoFHandler< dim, spacedim >::active_cell_iterator & second_cell_iter, const Mapping< dim, spacedim > & first_cell_mapping, const Mapping< dim, spacedim > & second_cell_mapping, const std::map< typename Triangulation< dim, spacedim >::cell_iterator, typename Triangulation< dim+1, spacedim >::face_iterator > & map_from_first_boundary_mesh_to_volume_mesh, const std::map< typename Triangulation< dim, spacedim >::cell_iterator, typename Triangulation< dim+1, spacedim >::face_iterator > & map_from_second_boundary_mesh_to_volume_mesh, std::vector< std::pair< types::global_dof_index, types::global_dof_index > > & common_vertex_pair_dof_indices, const double threshold = 1e-12)
Detect the cell neighboring type for the two cells pointed by the input cell iterators. This function handles the case when the involved two DoF handlers are different where the finite elements can be either identical or different, but the triangulations are always different.
In this case, neither vertex indices nor DoF indices for the two cells are numbered in a same index system.
These two surface triangulations are constructed respectively from a common volume mesh by specifying a set of boundary ids. Therefore, the map from surface/boundary mesh to volume mesh is needed.
The map from surface/boundary mesh to volume mesh is only for the coarse mesh, due to the behavior of GridGenerator::extract_boundary_mesh.
The template parameters dim and spacedim are for the boundary mesh. For the original volume mesh, the corresponding dimensions should be dim+1 and spacedim.
Parameters
first_cell_iter
second_cell_iter
first_cell_mapping
second_cell_mapping
map_from_first_boundary_mesh_to_volume_mesh
map_from_second_boundary_mesh_to_volume_mesh
common_vertex_pair_dof_indices A vector of pairs of global DoF indices in the corresponding DoF handlers. Each pair corresponds to a common vertex shred by the two cells, if any. The first DoF index in the pair is in the first cell with the first DoF handler, while the second DoF index in the pair is in the second cell with the second DoF handler.
threshold
Returns
Cell neighboring type
Get the iterators to the faces in the original volume triangulation.
Get the vertex indices in each face in the original volume triangulation.
Calculate the intersection of the two faces' vertex indices. This operation is meaningful because the two faces are both pulled back into the original volume triangulation.
According to deal.ii's documentation about extract_boundary_mesh,
‍The order of vertices of surface cells at the boundary and the
corresponding volume faces may not match in order to ensure that each surface cell is associated with an outward facing normal. As a consequence, if you want to match quantities on the faces of the domain cells and on the cells of the surface mesh, you may have to translate between vertex locations or quadrature points.
Hence, the local index of each common vertex in its corresponding face in the volume mesh is not the same as its local index in the cell in the surface mesh. Therefore, the correlation mapping between cell vertices in the surface mesh and those in the face in the volume mesh should be constructed by matching vertex coordinates.
Get the coordinates of the current common vertex.
Get the coordinates of the current common vertex.
Note
The point returned from the member function TriaAccessor::vertex is a reference.
Find the current common vertex in the first boundary cell by coordinate matching.
Get the DoF index associated with the common vertex in the first cell.
Handle the case when the finite element order is 0, i.e. for FE_DGQ. Set the common vertex DoF index to be the DoF in the cell's interior, even though it is not associated to the vertex.
Find the current common vertex in the second boundary cell by coordinates.
Get the DoF index associated with the common vertex in the second cell.
Handle the case when the finite element order is 0, i.e. for FE_DGQ. Set the common vertex DoF index to be the DoF in the cell's interior, even though it is not associated to the vertex.
Add the pair of DoF indices associated with the common vertex in the two boundary cells to the list.
Definition at line 2483 of file bem_tools.h.
References BEMTools::CommonEdge, BEMTools::CommonVertex, BEMTools::detect_cell_neighboring_type_for_different_triangulations(), BEMTools::get_dof_index_for_vertex_in_cell(), BEMTools::None, BEMTools::Regular, and BEMTools::SamePanel.
detect_cell_neighboring_type_for_different_triangulations() [2/2]
template<int dim, int spacedim> CellNeighboringType BEMTools::detect_cell_neighboring_type_for_different_triangulations (const typename Triangulation< dim, spacedim >::active_cell_iterator & first_cell_iter, const typename Triangulation< dim, spacedim >::active_cell_iterator & second_cell_iter, const std::map< typename Triangulation< dim, spacedim >::cell_iterator, typename Triangulation< dim+1, spacedim >::face_iterator > & map_from_first_boundary_mesh_to_volume_mesh, const std::map< typename Triangulation< dim, spacedim >::cell_iterator, typename Triangulation< dim+1, spacedim >::face_iterator > & map_from_second_boundary_mesh_to_volume_mesh, std::vector< std::pair< unsigned int, unsigned int > > & common_vertex_pair_local_indices)
Detect the cell neighboring type for two cells which belong to different surface/boundary triangulations.
These two surface triangulations are constructed respectively from a common volume mesh by specifying a set of boundary ids. Therefore, the map from surface/boundary mesh to volume mesh is needed.
The map from surface/boundary mesh to volume mesh is only for the coarse mesh, due to the behavior of GridGenerator::extract_boundary_mesh.
Parameters
first_cell_iter
second_cell_iter
map_from_first_boundary_mesh_to_volume_mesh
map_from_second_boundary_mesh_to_volume_mesh
common_vertex_pair_indices A vector of pairs of vertex local indices in the two cells in the surface mesh. Each pair corresponds to a common vertex shared by the two cells, if any. The first element in each pair is the local index of the common vertex in the first cell, and the second element is that in the second cell.
Returns
Cell neighboring type
Get the iterators to the faces in the original volume triangulation.
Get the vertex indices in each face in the original volume triangulation.
Calculate the intersection of the two faces' vertex indices. This operation is meaningful because the two faces are both pulled back into the original volume triangulation.
According to deal.ii's documentation about extract_boundary_mesh,
‍The order of vertices of surface cells at the boundary and the
corresponding volume faces may not match in order to ensure that each surface cell is associated with an outward facing normal. As a consequence, if you want to match quantities on the faces of the domain cells and on the cells of the surface mesh, you may have to translate between vertex locations or quadrature points.
Hence, the local index of each common vertex in its corresponding face in the volume mesh is not the same as its local index in the cell in the surface mesh. Therefore, the correlation mapping between cell vertices in the surface mesh and those in the face in the volume mesh should be constructed by matching vertex coordinates.
Get the coordinates of the current common vertex.
Note
The point returned from the member function TriaAccessor::vertex is a reference.
Find the current common vertex in the first cell in the surface mesh by coordinate matching.
Find the current common vertex in the second cell in the surface mesh by coordinate matching.
Definition at line 2322 of file bem_tools.h.
References BEMTools::detect_cell_neighboring_type_for_different_triangulations().
Referenced by BEMTools::detect_cell_neighboring_type(), and BEMTools::detect_cell_neighboring_type_for_different_triangulations().
detect_cell_neighboring_type_for_same_dofhandlers()
template<int dim, int spacedim = dim> CellNeighboringType BEMTools::detect_cell_neighboring_type_for_same_dofhandlers (const typename DoFHandler< dim, spacedim >::active_cell_iterator & first_cell_iter, const typename DoFHandler< dim, spacedim >::active_cell_iterator & second_cell_iter, const Mapping< dim, spacedim > & first_cell_mapping, const Mapping< dim, spacedim > & second_cell_mapping, std::vector< std::pair< types::global_dof_index, types::global_dof_index > > & common_vertex_pair_dof_indices, const double threshold = 1e-12)
Detect the cell neighboring type for the two cells pointed by the input cell iterators. This function handles the case when the involved two DoF handlers are the same, i.e. both the associated finite elements and triangulations are the same.
In this case, the vertex indices for the two cells are numbered in a same index system. Same situation holds for DoF indices for the two cells. Hence, when the finite element is H1, such as FE_Q, in each pair of the returned vector common_vertex_pair_dof_indices, the two elements are the same.
When the finite element type is H1, e.g. FE_Q, we get the common vertex DoF indices by taking the intersection of vertex indices in the two cells.
In principle, we can call the function detect_cell_neighboring_type_for_same_triangulations as what is done for the other case L2 element. However, it involves comparison of point coordinates, which is less efficient.
Parameters
first_cell_iter
second_cell_iter
first_cell_mapping
second_cell_mapping
common_vertex_pair_dof_indices A vector of pairs of DoF indices. Each pair corresponds to a common vertex and in each pair, the first DoF index is in the first cell, while the second DoF index is in the second cell.
threshold
Returns
Get the finite element, which should be the same for the two cell iterators.
Get the list of vertex DoF indices in the two cells
Fill the vector of pairs for common_vertex_dof_indices.
Definition at line 2808 of file bem_tools.h.
References BEMTools::CommonEdge, BEMTools::CommonVertex, BEMTools::detect_cell_neighboring_type_for_same_dofhandlers(), BEMTools::detect_cell_neighboring_type_for_same_triangulations(), BEMTools::get_vertex_dof_indices_in_cell(), BEMTools::None, BEMTools::Regular, and BEMTools::SamePanel.
Referenced by BEMTools::detect_cell_neighboring_type_for_same_dofhandlers().
detect_cell_neighboring_type_for_same_h1_dofhandlers()
template<int dim> CellNeighboringType BEMTools::detect_cell_neighboring_type_for_same_h1_dofhandlers (const std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > & first_cell_vertex_dof_indices, const std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > & second_cell_vertex_dof_indices, std::vector< types::global_dof_index > & vertex_dof_index_intersection)
Detect the cell neighboring type for two cells by checking the intersection of the DoF indices associated with their vertices. Because there are vertex DoFs, the finite elements contained in the DoF handlers should be H1. The intersection of the DoF indices is returned via argument by reference.
Comparison of DoF indices implies that the two cells should belong to a same DoFHandler. Otherwise, there will be two sets of DoF indices, which cannot be compared.
Note
N.B. The template argument dim of this function cannot be automatically inducted by the compiler from its input arguments, since even though the template argument GeometryInfo<dim>::vertices_per_cell of the two input arguments first_cell_vertex_dof_indices and second_cell_vertex_dof_indices contains dim, the whole GeometryInfo<dim>::vertices_per_cell will be evaluated into an integer by the compiler, so that dim will be discarded.
Parameters
first_cell_vertex_dof_indices
second_cell_vertex_dof_indices
vertex_dof_index_intersection Before calling this function, this variable should be cleared.
Returns
Cell neighboring type
Calculate the intersection of the two cells' vertex DoF indices.
Definition at line 2721 of file bem_tools.h.
References BEMTools::CommonEdge, BEMTools::CommonVertex, BEMTools::detect_cell_neighboring_type_for_same_h1_dofhandlers(), BEMTools::None, BEMTools::Regular, and BEMTools::SamePanel.
Referenced by BEMTools::detect_cell_neighboring_type_for_same_h1_dofhandlers().
detect_cell_neighboring_type_for_same_triangulations() [1/3]
template<int dim> CellNeighboringType BEMTools::detect_cell_neighboring_type_for_same_triangulations (const std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_cell > & first_cell_vertex_indices, const std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_cell > & second_cell_vertex_indices, std::vector< types::global_vertex_index > & common_vertex_indices)
Detect the cell neighboring type by checking the intersection of the given two lists of vertex indices. The intersection of the global vertex indices is returned in the argument common_vertex_indices by reference.
Comparison of vertex indices implies that the two cells should belong to a same triangulation. Otherwise, there will be two sets of vertex indices, which cannot be compared.
Note
N.B. The template argument dim of this function cannot be automatically inducted by the compiler from its input arguments, since even though the template argument GeometryInfo<dim>::vertices_per_cell of the two input arguments first_cell_vertex_indices and second_cell_vertex_indices contains dim, the whole GeometryInfo<dim>::vertices_per_cell will be evaluated into an integer by the compiler, so that dim will be discarded.
Parameters
first_cell_vertex_indices
second_cell_vertex_indices
common_vertex_indices
Returns
Calculate the intersection of the two cells' vertex indices.
Definition at line 1994 of file bem_tools.h.
References BEMTools::CommonEdge, BEMTools::CommonVertex, BEMTools::detect_cell_neighboring_type_for_same_triangulations(), BEMTools::None, BEMTools::Regular, and BEMTools::SamePanel.
Referenced by BEMTools::detect_cell_neighboring_type(), BEMTools::detect_cell_neighboring_type_for_same_dofhandlers(), and BEMTools::detect_cell_neighboring_type_for_same_triangulations().
detect_cell_neighboring_type_for_same_triangulations() [2/3]
template<int dim, int spacedim = dim> CellNeighboringType BEMTools::detect_cell_neighboring_type_for_same_triangulations (const typename DoFHandler< dim, spacedim >::active_cell_iterator & first_cell_iter, const typename DoFHandler< dim, spacedim >::active_cell_iterator & second_cell_iter, const Mapping< dim, spacedim > & first_cell_mapping, const Mapping< dim, spacedim > & second_cell_mapping, std::vector< std::pair< types::global_dof_index, types::global_dof_index > > & common_vertex_pair_dof_indices, const double threshold = 1e-12)
Detect the cell neighboring type for the two cells pointed by the input cell iterators. This function handles the case when the involved two DoF handlers are different where the finite elements are different but the triangulations are the same.
In this case, the vertex indices for the two cells are numbered in a same index system. But the DoF indices for the two cells are independently indexed.
Parameters
first_cell_iter
second_cell_iter
first_cell_mapping
second_cell_mapping
common_vertex_pair_dof_indices A vector of pairs of DoF indices. Each pair corresponds to a common vertex. In each pair, the first DoF index is in the first cell with the first DoF handler, while the second DoF index is in the second cell with the second DoF handler. @pram threshold
Returns
Cell neighboring type
Get the vertex indices in each cell.
Calculate the intersection of the two cells' vertex indices. This operation is meaningful because the triangulations for the two cells are the same.
Fill the vector of pairs for common_vertex_pair_dof_indices. For each vertex index in the intersection, find the corresponding DoF indices in the two cells respectively.
Find the current common vertex in the list of vertex indices for the first cell.
Handle the case when there is only one DoF in a cell, i.e. FE_DGQ with order 0. Set the common vertex DoF index to be the DoF in the cell's interior, even though it is not associated to the vertex.
Find the current common vertex in the list of vertex indices for the second cell.
Handle the case when the finite element order is 0, i.e. for FE_DGQ. Set the common vertex DoF index to be the DoF in the cell's interior, even though it is not associated to the vertex.
Definition at line 2145 of file bem_tools.h.
References BEMTools::CommonEdge, BEMTools::CommonVertex, BEMTools::detect_cell_neighboring_type_for_same_triangulations(), BEMTools::get_dof_index_for_vertex_in_cell(), BEMTools::None, BEMTools::Regular, and BEMTools::SamePanel.
detect_cell_neighboring_type_for_same_triangulations() [3/3]
template<int dim, int spacedim> CellNeighboringType BEMTools::detect_cell_neighboring_type_for_same_triangulations (const typename Triangulation< dim, spacedim >::active_cell_iterator & first_cell_iter, const typename Triangulation< dim, spacedim >::active_cell_iterator & second_cell_iter, std::vector< std::pair< unsigned int, unsigned int > > & common_vertex_pair_local_indices)
Detect the cell neighboring type for two cells by checking the intersection of their vertex indices. Each of the common global vertex index is duplicated and made into a pair, then pushed into the result vector.
Comparison of vertex indices implies that the two cells should belong to a same triangulation. Otherwise, there will be two sets of vertex indices, which cannot be compared.
Parameters
first_cell_iter
second_cell_iter
common_vertex_pair_indices
Returns
Definition at line 2064 of file bem_tools.h.
References BEMTools::detect_cell_neighboring_type_for_same_triangulations().
generate_backward_dof_permutation() [1/2]
template<int dim, int spacedim> std::vector< unsigned int > BEMTools::generate_backward_dof_permutation (const FiniteElement< dim, spacedim > & fe, unsigned int starting_corner)
Generate the permutation of the polynomial space inverse numbering by starting from the specified corner in the backward direction. The numbering is returned from this function via the return value.
Parameters
fe
starting_corner Index of the starting corner point. Because there are only four corners in a cell, its value belongs to \([0,1,2,3]\).
Returns
Numbering of the permuted DoFs
Definition at line 3667 of file bem_tools.h.
References BEMTools::generate_backward_dof_permutation().
Referenced by BEMTools::generate_backward_dof_permutation().
generate_backward_dof_permutation() [2/2]
template<int dim, int spacedim> void BEMTools::generate_backward_dof_permutation (const FiniteElement< dim, spacedim > & fe, unsigned int starting_corner, std::vector< unsigned int > & dof_permutation)
Generate the permutation of the polynomial space inverse numbering by starting from the specified corner in the backward direction. This overloaded version has the returned vector as its argument.
Parameters
fe
starting_corner Index of the starting corner point. Because there are only four corners in a cell, its value belongs to \([0,1,2,3]\).
Returns
dof_permutation Numbering of the permuted DoFs. Its memory should be pre-allocated.
Definition at line 3771 of file bem_tools.h.
References BEMTools::generate_backward_dof_permutation().
generate_backward_mapping_support_point_permutation() [1/2]
template<int dim, int spacedim> std::vector< unsigned int > BEMTools::generate_backward_mapping_support_point_permutation (const MappingQExt< dim, spacedim > & mapping, unsigned int starting_corner)
Definition at line 3863 of file bem_tools.h.
generate_backward_mapping_support_point_permutation() [2/2]
template<int dim, int spacedim> void BEMTools::generate_backward_mapping_support_point_permutation (const MappingQExt< dim, spacedim > & mapping, unsigned int starting_corner, std::vector< unsigned int > & support_point_permutation)
Definition at line 3955 of file bem_tools.h.
generate_forward_dof_permutation() [1/2]
template<int dim, int spacedim> std::vector< unsigned int > BEMTools::generate_forward_dof_permutation (const FiniteElement< dim, spacedim > & fe, unsigned int starting_corner)
Generate the permutation of the polynomial space inverse numbering by starting from the specified corner in the forward direction. The numbering is returned from the function as the return value.
Parameters
fe
starting_corner Index of the starting corner point. Because there are only four corners in a cell, its value belongs to \([0,1,2,3]\).
Returns
Numbering of the permuted DoFs
Definition at line 3311 of file bem_tools.h.
References BEMTools::generate_forward_dof_permutation().
Referenced by BEMTools::generate_forward_dof_permutation().
generate_forward_dof_permutation() [2/2]
template<int dim, int spacedim> void BEMTools::generate_forward_dof_permutation (const FiniteElement< dim, spacedim > & fe, unsigned int starting_corner, std::vector< unsigned int > & dof_permutation)
Generate the permutation of the polynomial space inverse numbering by starting from the specified corner in the forward direction. This overloaded version has the returned vector as its argument.
Parameters
fe
starting_corner Index of the starting corner point. Because there are only four corners in a cell, its value belongs to \([0,1,2,3]\).
dof_permutation Numbering of the permuted DoFs. Its memory should be pre-allocated.
Definition at line 3407 of file bem_tools.h.
References BEMTools::generate_forward_dof_permutation().
generate_forward_mapping_support_point_permutation() [1/2]
template<int dim, int spacedim> std::vector< unsigned int > BEMTools::generate_forward_mapping_support_point_permutation (const MappingQExt< dim, spacedim > & mapping, unsigned int starting_corner)
Definition at line 3491 of file bem_tools.h.
generate_forward_mapping_support_point_permutation() [2/2]
template<int dim, int spacedim> void BEMTools::generate_forward_mapping_support_point_permutation (const MappingQExt< dim, spacedim > & mapping, unsigned int starting_corner, std::vector< unsigned int > & support_point_permutation)
Definition at line 3574 of file bem_tools.h.
get_conflict_indices()
template<int dim, int spacedim = dim> std::vector< types::global_dof_index > BEMTools::get_conflict_indices (const typename DoFHandler< dim, spacedim >::active_cell_iterator & cell)
This function returns a list of DoF indices in the given cell iterator, which is used for checking if the two cells have interaction. This function is called by GraphColoring::make_graph_coloring.
Reference: http://localhost/dealii-9.1.1-doc/namespaceGraphColoring.html#a670720d11f544a762592112ae5213876
Parameters
cell
Returns
Definition at line 153 of file bem_tools.h.
References BEMTools::get_conflict_indices().
Referenced by BEMTools::get_conflict_indices().
get_dof_index_for_vertex_in_cell()
template<int dim, int spacedim> types::global_dof_index BEMTools::get_dof_index_for_vertex_in_cell (const typename DoFHandler< dim, spacedim >::cell_iterator & cell, const Mapping< dim, spacedim > & mapping, const unsigned int local_vertex_index_in_cell, const double threshold = 1e-12)
Get the DoF index for the specified vertex in the cell.
Note
When the finite element associated with the cell conforms with H1, this function is the same as DoFAccessor::vertex_dof_index. When the finite element conforms with L2, because there are no DoFs associated with vertices, the matching of support points and vertices should be calculated.
Parameters
cell
mapping
local_vertex_index_in_cell
threshold Threshold for point equality checking
Returns
When the finite element conforms to \(H_1\), e.g. FE_Q, the vertex DoF indices can be directly obtained by calling the member function DoFAccessor::vertex_dof_index.
Assert there is only one DoF associated with each vertex.
Handle the case when the finite element conforms to \(L_2\), e.g. FE_DGQ, where no DoFs are associated with vertices.
Assert there is no DoF associated with each vertex.
Get the list of vertex DoF indices in lexicographic order, which are directly extracted from the list of all DoF indices. N.B. The ordering of this list of vertex DoF indices may not match the ordering of the vertices in the geometry information.
Calculate the list of vertex support point coordinates in the real cell with the help of the mapping object. It will be compared with the vertex coordinates obtained from the cell geometry using the given threshold.
N.B. The ordering of this list of vertex support points corresponds with the ordering of the list of the above vertex DoF indices.
Iterate over each vertex support point and check if it matches the required vertex.
Definition at line 1876 of file bem_tools.h.
References BEMTools::get_dof_index_for_vertex_in_cell(), and BEMTools::get_vertices_from_lexicographic_support_points_in_real_cell().
Referenced by BEMTools::detect_cell_neighboring_type_for_different_triangulations(), BEMTools::detect_cell_neighboring_type_for_same_triangulations(), and BEMTools::get_dof_index_for_vertex_in_cell().
get_dofs_per_face_for_fe()
template<int dim, int spacedim = dim> unsigned int BEMTools::get_dofs_per_face_for_fe (const FiniteElement< dim, spacedim > & fe)
Definition at line 1150 of file bem_tools.h.
get_lexicographic_dof_indices() [1/2]
template<int dim, int spacedim> std::vector< types::global_dof_index > BEMTools::get_lexicographic_dof_indices (const typename DoFHandler< dim, spacedim >::cell_iterator & cell)
Get the list of DoF indices in the current cell. It is obtained via the return value.
Parameters
cell
Returns
Extract the list of DoF indices in the current cell.
Definition at line 1439 of file bem_tools.h.
References BEMTools::get_lexicographic_dof_indices(), and BEMTools::permute_vector().
Referenced by BEMTools::get_lexicographic_dof_indices(), and BEMTools::get_vertex_dof_indices_from_lexicographic_dof_indices().
get_lexicographic_dof_indices() [2/2]
template<int dim, int spacedim> void BEMTools::get_lexicographic_dof_indices (const typename DoFHandler< dim, spacedim >::cell_iterator & cell, std::vector< types::global_dof_index > & lexicographic_dof_indices)
Get the list of DoF indices in the current cell. It is obtained via argument by reference.
Parameters
cell
lexicographic_dof_indices
Extract the list of DoF indices in the current cell.
Definition at line 1475 of file bem_tools.h.
References BEMTools::get_lexicographic_dof_indices(), and BEMTools::permute_vector().
get_lexicographic_support_points_in_real_cell() [1/2]
template<int dim, int spacedim> std::vector< Point< spacedim > > BEMTools::get_lexicographic_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator & cell, const FiniteElement< dim, spacedim > & fe, const MappingQ< dim, spacedim > & mapping)
Calculate a list of support points in the real cell in the lexicographic order. The results are obtained via the return value.
Parameters
cell
fe
mapping Geometric mapping object used for transforming support points from the unit cell to the real cell.
Returns
A list of support points in the real cell in the lexicographic order.
Note
N.B. Each support point in the real cell has the space dimension spacedim, while each support point in the unit cell has the manifold dimension dim.
Definition at line 1089 of file bem_tools.h.
References BEMTools::get_lexicographic_support_points_in_real_cell(), and BEMTools::get_support_points_in_real_cell().
Referenced by BEMTools::get_lexicographic_support_points_in_real_cell().
get_lexicographic_support_points_in_real_cell() [2/2]
template<int dim, int spacedim> void BEMTools::get_lexicographic_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator & cell, const FiniteElement< dim, spacedim > & fe, const MappingQ< dim, spacedim > & mapping, std::vector< Point< spacedim > > & support_points_in_real_cell)
Calculate a list of support points in the real cell in the lexicographic order. The results are obtained via argument by reference.
Parameters
cell
fe
mapping
support_points_in_real_cell Returned list of support points in the lexicographic order in the real cell, the memory of which should be preallocated.
Definition at line 1125 of file bem_tools.h.
References BEMTools::get_lexicographic_support_points_in_real_cell(), and BEMTools::get_support_points_in_real_cell().
get_lexicographic_unit_support_points() [1/2]
template<int dim, int spacedim = dim> std::vector< Point< dim > > BEMTools::get_lexicographic_unit_support_points (const FiniteElement< dim, spacedim > & fe)
Get the list of unit support points in the lexicographic order in the finite element. The results are obtained via the return value.
Parameters
fe
Returns
Definition at line 820 of file bem_tools.h.
References BEMTools::get_lexicographic_unit_support_points(), and BEMTools::get_unit_support_points_with_permutation().
Referenced by BEMTools::get_lexicographic_unit_support_points(), and BEMTools::get_vertices_from_lexicographic_unit_support_points().
get_lexicographic_unit_support_points() [2/2]
template<int dim, int spacedim = dim> void BEMTools::get_lexicographic_unit_support_points (const FiniteElement< dim, spacedim > & fe, std::vector< Point< dim > > & lexicographic_unit_support_points)
Get the list of unit support points in the lexicographic order in the finite element. The results are obtained via argument by reference.
Parameters
fe
lexicographic_unit_support_points Returned list of unit support points in the lexicographic order, the memory of which should be preallocated.
Definition at line 852 of file bem_tools.h.
References BEMTools::get_lexicographic_unit_support_points(), and BEMTools::get_unit_support_points_with_permutation().
get_support_points_in_default_dof_order_in_real_cell() [1/2]
template<int dim, int spacedim> std::vector< Point< spacedim > > BEMTools::get_support_points_in_default_dof_order_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator & cell, const FiniteElement< dim, spacedim > & fe, const MappingQ< dim, spacedim > & mapping)
Calculate a list of support points in the real cell in the default DoF order.
Parameters
cell
fe
mapping Geometric mapping object used for transforming support points from the unit cell to the real cell.
Returns
A list of support points in the real cell in the default DoF order.
Note
N.B. Each support point in the real cell has the space dimension spacedim, while each support point in the unit cell has the manifold dimension dim.
Definition at line 995 of file bem_tools.h.
References BEMTools::get_support_points_in_default_dof_order_in_real_cell().
Referenced by BEMTools::get_support_points_in_default_dof_order_in_real_cell().
get_support_points_in_default_dof_order_in_real_cell() [2/2]
template<int dim, int spacedim> void BEMTools::get_support_points_in_default_dof_order_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator & cell, const FiniteElement< dim, spacedim > & fe, const MappingQ< dim, spacedim > & mapping, std::vector< Point< spacedim > > & support_points_in_reall_cell)
Calculate a list of support points in the real cell in the default DoF order.
Parameters
cell
fe
mapping Geometric mapping object used for transforming support points from the unit cell to the real cell.
support_points_in_real_cell A list of support points in the real cell in the hierarchic order, the memory of which should be preallocated.
Note
N.B. Each support point in the real cell has the space dimension spacedim, while each support point in the unit cell has the manifold dimension dim.
Definition at line 1041 of file bem_tools.h.
References BEMTools::get_support_points_in_default_dof_order_in_real_cell().
get_support_points_in_real_cell() [1/2]
template<int dim, int spacedim = dim> std::vector< Point< spacedim > > BEMTools::get_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator & cell, const FiniteElement< dim, spacedim > & fe, const MappingQ< dim, spacedim > & mapping, const std::vector< unsigned int > & dof_permutation)
Calculate a list of support points in the real cell in the order specified by dof_permutation. The results are returned via the return value.
Parameters
cell
fe
mapping Geometric mapping object used for transforming support points from the unit cell to the real cell.
dof_permutation The numbering for accessing the support points in the specified order.
Returns
A list of support points in the real cell.
Note
N.B. Each support point in the real cell has the space dimension spacedim, while each support point in the unit cell has the manifold dimension dim.
Get the list of support points in the unit cell in the default DoF ordering.
Transform the support points from unit cell to real cell via the mapping object. The support points in the original default DoF ordering are permuted according to dof_permutation.
Definition at line 894 of file bem_tools.h.
References BEMTools::get_support_points_in_real_cell().
Referenced by BEMTools::get_lexicographic_support_points_in_real_cell(), and BEMTools::get_support_points_in_real_cell().
get_support_points_in_real_cell() [2/2]
template<int dim, int spacedim = dim> void BEMTools::get_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator & cell, const FiniteElement< dim, spacedim > & fe, const MappingQ< dim, spacedim > & mapping, const std::vector< unsigned int > & dof_permutation, std::vector< Point< spacedim > > & support_points_in_real_cell)
Calculate a list of support points in the real cell in the order specified by dof_permutation. The results are returned via argument by reference.
Parameters
cell
fe
mapping
dof_permutation
support_points_in_real_cell
Get the list of support points in the unit cell in the default DoF ordering.
Transform the support points from unit cell to real cell via the mapping object. The support points in the original default DoF ordering are permuted according to dof_permutation.
Definition at line 943 of file bem_tools.h.
References BEMTools::get_support_points_in_real_cell().
get_unit_support_points_with_permutation() [1/2]
template<int dim, int spacedim = dim> std::vector< Point< dim > > BEMTools::get_unit_support_points_with_permutation (const FiniteElement< dim, spacedim > & fe, const std::vector< unsigned int > & dof_permutation)
Get the list of unit support points in the finite element, which is ordered according to the specified permutation. The results are obtained via the return value.
Parameters
fe
dof_permutation
Returns
Get the list of support points in the unit cell in the default DoF ordering.
Definition at line 739 of file bem_tools.h.
References BEMTools::get_unit_support_points_with_permutation().
Referenced by BEMTools::get_lexicographic_unit_support_points(), and BEMTools::get_unit_support_points_with_permutation().
get_unit_support_points_with_permutation() [2/2]
template<int dim, int spacedim = dim> void BEMTools::get_unit_support_points_with_permutation (const FiniteElement< dim, spacedim > & fe, const std::vector< unsigned int > & dof_permutation, std::vector< Point< dim > > & permuted_unit_support_points)
Get the list of unit support points in the finite element, which is ordered according to the specified permutation. The results are obtained as argument by reference.
Parameters
fe
dof_permutation
permuted_unit_support_points Returned list of permuted unit support points, the memory of which should be preallocated.
Get the list of support points in the unit cell in the default DoF ordering.
Definition at line 782 of file bem_tools.h.
References BEMTools::get_unit_support_points_with_permutation().
get_vertex_dof_indices_from_lexicographic_dof_indices() [1/2]
template<int dim, int spacedim> std::vector< types::global_dof_index > BEMTools::get_vertex_dof_indices_from_lexicographic_dof_indices (const typename DoFHandler< dim, spacedim >::cell_iterator & cell, const bool is_counter_clockwise_ordered = false)
Get a list of vertex DoF indices, which are directly extracted from the list of DoF indices in the lexicographic order. The result is obtained in the return value.
Parameters
cell
is_counter_clockwise_ordered
Returns
Get the list of DoF indices in the lexicographic order.
Definition at line 1511 of file bem_tools.h.
References BEMTools::get_lexicographic_dof_indices(), and BEMTools::get_vertex_dof_indices_from_lexicographic_dof_indices().
Referenced by BEMTools::get_vertex_dof_indices_from_lexicographic_dof_indices(), and BEMTools::get_vertex_dof_indices_in_cell().
get_vertex_dof_indices_from_lexicographic_dof_indices() [2/2]
template<int dim, int spacedim = dim> void BEMTools::get_vertex_dof_indices_from_lexicographic_dof_indices (const typename DoFHandler< dim, spacedim >::cell_iterator & cell, std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > & vertex_dof_indices, const bool is_counter_clockwise_ordered = false)
Get a list of vertex DoF indices, which are directly extracted from the list of DoF indices in the lexicographic order. The result is obtained via argument by reference.
Parameters
cell
vertex_dof_indices
is_counter_clockwise_ordered
Get the list of DoF indices in the lexicographic order.
Definition at line 1586 of file bem_tools.h.
References BEMTools::get_vertex_dof_indices_from_lexicographic_dof_indices().
get_vertex_dof_indices_in_cell() [1/2]
template<int dim, int spacedim> std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > BEMTools::get_vertex_dof_indices_in_cell (const typename DoFHandler< dim, spacedim >::cell_iterator & cell, const Mapping< dim, spacedim > & mapping, const double threshold = 1e-12)
Return a list of global DoF indices, which are located at the list of vertices in the cell respectively. The result is obtained via the return value.
Parameters
cell
mapping
threshold
Returns
When the finite element conforms to \(H_1\), e.g. FE_Q, the vertex DoF indices can be directly obtained by calling the member function DoFAccessor::vertex_dof_index.
Assert there is only one DoF associated with each vertex.
Handle the case when the finite element conforms to \(L_2\), e.g. FE_DGQ, where there are no DoFs associated with vertices.
Assert there is no DoF associated with each vertex.
Get the list of vertex DoF indices which are directly extracted from the list of all DoF indices. N.B. The ordering of this list of vertex DoF indices may not match the ordering of the vertices in the geometry information.
Calculate the list of vertex support point coordinates in the real cell with the help of the mapping object. It will be compared with the vertex coordinates obtained from the cell geometry.
N.B. The ordering of this list of vertex support points corresponds with the ordering of the list of the above vertex DoF indices.
Iterate over each vertex support point and check that to which vertex in the cell it is equal.
Definition at line 1660 of file bem_tools.h.
References BEMTools::get_vertex_dof_indices_in_cell(), and BEMTools::get_vertices_from_lexicographic_support_points_in_real_cell().
Referenced by BEMTools::detect_cell_neighboring_type_for_same_dofhandlers(), and BEMTools::get_vertex_dof_indices_in_cell().
get_vertex_dof_indices_in_cell() [2/2]
template<int dim, int spacedim> void BEMTools::get_vertex_dof_indices_in_cell (const typename DoFHandler< dim, spacedim >::cell_iterator & cell, const Mapping< dim, spacedim > & mapping, std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > & cell_vertex_dof_indices, const double threshold = 1e-12)
Return a list of global DoF indices, which are located at the list of vertices in the cell respectively. The result is obtained via argument by reference.
Parameters
cell
mapping
threshold
cell_vertex_dof_indices
When the finite element conforms to \(H_1\), e.g. FE_Q, the vertex DoF indices can be directly obtained by calling the member function DoFAccessor::vertex_dof_index.
Assert there is only one DoF associated with each vertex.
Handle the case when the finite element conforms to \(L_2\), e.g. FE_DGQ, where there are no DoFs associated with vertices.
Assert there is no DoF associated with each vertex.
Get the list of vertex DoF indices which are directly extracted from the list of all DoF indices. N.B. The ordering of this list of vertex DoF indices may not match the ordering of the vertices in the geometry information.
Calculate the list of vertex support point coordinates in the real cell with the help of the mapping object. It will be compared with the vertex coordinates obtained from the cell geometry.
N.B. The ordering of this list of vertex support points corresponds with the ordering of the list of the above vertex DoF indices.
Iterate over each vertex support point and check that to which vertex in the cell it is equal.
Definition at line 1767 of file bem_tools.h.
References BEMTools::get_vertex_dof_indices_from_lexicographic_dof_indices(), BEMTools::get_vertex_dof_indices_in_cell(), and BEMTools::get_vertices_from_lexicographic_support_points_in_real_cell().
get_vertex_indices_in_cell() [1/2]
template<int dim, int spacedim = dim> std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_cell > BEMTools::get_vertex_indices_in_cell (const typename Triangulation< dim, spacedim >::cell_iterator & cell)
Return a list of global vertex indices for all the vertices in the given cell pointed by the cell iterator obtained from a triangulation. The result is obtained via the return value.
Parameters
cell
Returns
Definition at line 238 of file bem_tools.h.
References BEMTools::get_vertex_indices_in_cell().
Referenced by BEMTools::get_vertex_indices_in_cell().
get_vertex_indices_in_cell() [2/2]
template<int dim, int spacedim = dim> void BEMTools::get_vertex_indices_in_cell (const typename Triangulation< dim, spacedim >::cell_iterator & cell, std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_cell > & cell_vertex_indices)
Return a list of global vertex indices for all the vertices in the given cell pointed by the cell iterator obtained from a triangulation. The result is obtained via argument by reference.
Parameters
cell
cell_vertex_indices
Definition at line 263 of file bem_tools.h.
References BEMTools::get_vertex_indices_in_cell().
get_vertex_indices_in_face() [1/2]
template<int dim, int spacedim = dim> std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_face > BEMTools::get_vertex_indices_in_face (const typename Triangulation< dim, spacedim >::face_iterator & face)
Return a list of global vertex indices for all the vertices in the given face pointed by the face iterator obtained from a triangulation. The result is obtained via the return value.
Note
The dimension of the face is dim-1.
Parameters
face
Returns
Definition at line 287 of file bem_tools.h.
References BEMTools::get_vertex_indices_in_face().
Referenced by BEMTools::get_vertex_indices_in_face().
get_vertex_indices_in_face() [2/2]
template<int dim, int spacedim = dim> void BEMTools::get_vertex_indices_in_face (const typename Triangulation< dim, spacedim >::face_iterator & face, std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_face > & face_vertex_indices)
Return a list of global vertex indices for all the vertices in the given face pointed by the face iterator obtained from a triangulation. The result is obtained via argument by reference.
Note
The dimension of the face is dim-1.
Parameters
face
face_vertex_indices
Definition at line 314 of file bem_tools.h.
References BEMTools::get_vertex_indices_in_face().
get_vertex_local_index_in_cell() [1/2]
template<int dim, int spacedim = dim> unsigned int BEMTools::get_vertex_local_index_in_cell (const Point< spacedim > & v, const typename Triangulation< dim, spacedim >::cell_iterator & cell)
Get the local index of the given vertex in the list of vertices of the cell by raw comparison of vertex coordinates.
Note
The template parameter dim cannot be deduced from the arguments.
Parameters
v
cell
Returns
Definition at line 178 of file bem_tools.h.
References BEMTools::get_vertex_local_index_in_cell(), and is_equal().
Referenced by BEMTools::get_vertex_local_index_in_cell().
get_vertex_local_index_in_cell() [2/2]
template<int dim, int spacedim = dim> unsigned int BEMTools::get_vertex_local_index_in_cell (const Point< spacedim > & v, const typename Triangulation< dim, spacedim >::cell_iterator & cell, const double threshold)
Get the local index of the given vertex in the list of vertices of the cell by numerical comparison of vertex coordinates.
Note
The template parameter dim cannot be deduced from the arguments.
Parameters
v
cell
Returns
Definition at line 210 of file bem_tools.h.
References BEMTools::get_vertex_local_index_in_cell(), and is_equal().
get_vertices_from_lexicographic_support_points_in_real_cell() [1/2]
template<int dim, int spacedim> std::array< Point< spacedim >, GeometryInfo< dim >::vertices_per_cell > BEMTools::get_vertices_from_lexicographic_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator & cell, const FiniteElement< dim, spacedim > & fe, const Mapping< dim, spacedim > & mapping, const bool is_counter_clockwise_ordered = false)
Get the list of vertex coordinates from a list of support points in the real cell in the lexicographic order. The results are obtained via the return value.
If is_counter_clockwise_ordered is true when dim==2, the last two vertices will be swapped.
Parameters
cell
fe
mapping
is_counter_clockwise_ordered
Returns
Extract the list of support points at vertices in the unit cell.
Map the support points from the unit cell to the real cell.
Definition at line 1349 of file bem_tools.h.
References BEMTools::get_vertices_from_lexicographic_support_points_in_real_cell(), and BEMTools::get_vertices_from_lexicographic_unit_support_points().
Referenced by BEMTools::get_dof_index_for_vertex_in_cell(), BEMTools::get_vertex_dof_indices_in_cell(), and BEMTools::get_vertices_from_lexicographic_support_points_in_real_cell().
get_vertices_from_lexicographic_support_points_in_real_cell() [2/2]
template<int dim, int spacedim> void BEMTools::get_vertices_from_lexicographic_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator & cell, const FiniteElement< dim, spacedim > & fe, const Mapping< dim, spacedim > & mapping, std::array< Point< spacedim >, GeometryInfo< dim >::vertices_per_cell > & vertices_in_real_cell, const bool is_counter_clockwise_ordered = false)
Get the list of vertex coordinates from a list of support points in the real cell in the lexicographic order. The results are obtained via argument by reference.
If is_counter_clockwise_ordered is true when dim==2, the last two vertices will be swapped.
Parameters
cell
fe
mapping
vertices_in_real_cell
is_counter_clockwise_ordered
Extract the list of support points at vertices in the unit cell.
Map the support points from the unit cell to the real cell.
Definition at line 1398 of file bem_tools.h.
References BEMTools::get_vertices_from_lexicographic_support_points_in_real_cell(), and BEMTools::get_vertices_from_lexicographic_unit_support_points().
get_vertices_from_lexicographic_unit_support_points() [1/2]
template<int dim, int spacedim> std::array< Point< dim >, GeometryInfo< dim >::vertices_per_cell > BEMTools::get_vertices_from_lexicographic_unit_support_points (const FiniteElement< dim, spacedim > & fe, const bool is_counter_clockwise_ordered = false)
Get the list of vertex coordinates from a list of unit support points in the lexicographic order. The results are obtained via the return value.
If is_counter_clockwise_ordered is true when dim==2, the last two vertices will be swapped.
Parameters
fe
Returns
Get the list of unit support points in the lexicographic order.
Swap the last two vertices so that all the vertices are ordered counter clockwise.
Definition at line 1206 of file bem_tools.h.
References BEMTools::get_lexicographic_unit_support_points(), and BEMTools::get_vertices_from_lexicographic_unit_support_points().
Referenced by BEMTools::get_vertices_from_lexicographic_support_points_in_real_cell(), and BEMTools::get_vertices_from_lexicographic_unit_support_points().
get_vertices_from_lexicographic_unit_support_points() [2/2]
template<int dim, int spacedim> void BEMTools::get_vertices_from_lexicographic_unit_support_points (const FiniteElement< dim, spacedim > & fe, std::array< Point< dim >, GeometryInfo< dim >::vertices_per_cell > & vertices, const bool is_counter_clockwise_ordered = false)
Get the list of vertex coordinates from a list of unit support points in the lexicographic order. The results are obtained via argument by reference.
If is_counter_clockwise_ordered is true when dim==2, the last two vertices will be swapped.
Parameters
fe
vertices
is_counter_clockwise_ordered
Get the list of unit support points in the lexicographic order.
Definition at line 1280 of file bem_tools.h.
References BEMTools::get_lexicographic_unit_support_points(), and BEMTools::get_vertices_from_lexicographic_unit_support_points().
mappingq_shape_grad_matrix()
template<int dim, int spacedim, typename RangeNumberType = double> void BEMTools::mappingq_shape_grad_matrix (const typename MappingQ< dim, spacedim >::InternalData & mapping_data, const unsigned int point_no, LAPACKFullMatrixExt< RangeNumberType > & grad_matrix)
Collect the gradient of MappingQ shape functions into a matrix.
The shape functions and their derivatives of the mapping object have been evaluated at a list of points in the unit cell, therefore we need to specify at which point we will collect the data.
Parameters
mapping_data The InternalData within MappingQ .
quad_no The index of the point in the unit cell
Definition at line 400 of file bem_tools.h.
References BEMTools::mappingq_shape_grad_matrix().
Referenced by BEMTools::mappingq_shape_grad_matrix().
permute_vector()
template<typename VectorType1 , typename VectorType2 , typename IndexType > void BEMTools::permute_vector (const VectorType1 & input_vector, const std::vector< IndexType > & permutation_indices, VectorType2 & permuted_vector)
Permute a vector by using the given permutation indices to access its elements.
Template Parameters
VectorType1
VectorType2
IndexType
Parameters
input_vector
permutation_indices
permuted_vector Result vector, whose memory should be allocated before calling this function. Its size should be >= the size of the input vector.
Definition at line 125 of file bem_tools.h.
References BEMTools::permute_vector().
Referenced by BEMTools::get_lexicographic_dof_indices(), and BEMTools::permute_vector().
shape_grad_matrix()
template<int dim, int spacedim, typename RangeNumberType = double> LAPACKFullMatrixExt< RangeNumberType > BEMTools::shape_grad_matrix (const FiniteElement< dim, spacedim > & fe, const std::vector< unsigned int > & dof_permutation, const Point< dim > & p)
Calculates the matrix which stores shape function gradient values with respect to area coordinates. Each row of the matrix is the gradient of one of the shape functions. The order of the matrix rows corresponding to the shape function gradients is determined by the given numbering dof_permuation.
Note
The support points, shape functions and DoFs in the finite element are enumerated in the hierarchic order for the continuous element FE_Q, while the discontinuous element FE_DGQ adopts the lexicographic order.
Parameters
fe
dof_permutation The numbering for accessing the shape functions in the specified order.
p The area coordinates at which the shape function's gradient is to be evaluated.
Returns
The matrix storing the gradient of each shape function. Its dimension is dofs_per_cell*dim.
Definition at line 365 of file bem_tools.h.
References BEMTools::shape_grad_matrix().
Referenced by BEMTools::shape_grad_matrix(), and BEMTools::shape_grad_matrix_in_default_dof_order().
shape_grad_matrix_in_default_dof_order()
template<int dim, int spacedim, typename RangeNumberType = double> LAPACKFullMatrixExt< RangeNumberType > BEMTools::shape_grad_matrix_in_default_dof_order (const FiniteElement< dim, spacedim > & fe, const Point< dim > & p)
Calculate the matrix which stores shape function gradient values with respect to area coordinates. Each row of the matrix is the gradient of one of the shape functions. The matrix rows corresponding to the shape function gradients are arranged in the default DoF order.
Note
The support points, shape functions and DoFs in the finite element are enumerated in the hierarchic order for the continuous element FE_Q, while the discontinuous element FE_DGQ adopts the lexicographic order.
Parameters
fe
p The area coordinates at which the shape function's gradient is to be evaluated.
Returns
The matrix storing the gradient of each shape function. Its dimension is dofs_per_cell*dim.
Definition at line 441 of file bem_tools.h.
References BEMTools::shape_grad_matrix(), and BEMTools::shape_grad_matrix_in_default_dof_order().
Referenced by BEMTools::shape_grad_matrix_in_default_dof_order().
shape_grad_matrix_in_lexicographic_order()
template<int dim, int spacedim, typename RangeNumberType = double> LAPACKFullMatrixExt< RangeNumberType > BEMTools::shape_grad_matrix_in_lexicographic_order (const FiniteElement< dim, spacedim > & fe, const Point< dim > & p)
Calculate the matrix which stores shape function gradient values with respect to area coordinates. Each row of the matrix is the gradient of one of the shape functions. The matrix rows corresponding to the shape function gradients are arranged in the lexicographic order.
Note
The support points, shape functions and DoFs in the finite element are enumerated in the hierarchic order for the continuous element FE_Q, while the discontinuous element FE_DGQ adopts the lexicographic order.
Parameters
fe
p The area coordinates at which the shape function's gradient is to be evaluated.
Returns
The matrix storing the gradient of each shape function. Its dimension is dofs_per_cell*dim .
Definition at line 480 of file bem_tools.h.
References BEMTools::shape_grad_matrix_in_lexicographic_order().
Referenced by BEMValues< dim, spacedim, RangeNumberType >::shape_function_values_regular(), and BEMTools::shape_grad_matrix_in_lexicographic_order().
shape_values()
template<int dim, int spacedim, typename RangeNumberType = double> Vector< RangeNumberType > BEMTools::shape_values (const FiniteElement< dim, spacedim > & fe, const std::vector< unsigned int > & dof_permutation, const Point< dim > & p)
Evaluate a list of shape functions at the specified area coordinates. The shape functions are arranged in the order specified by dof_permutation.
Parameters
fe
dof_permutation The numbering for accessing the shape functions in the specified order.
p The area coordinates at which the shape functions are to be evaluated.
Returns
A list of shape function values.
Definition at line 505 of file bem_tools.h.
References BEMTools::shape_values().
Referenced by BEMTools::shape_values().
shape_values_in_default_dof_order()
template<int dim, int spacedim, typename RangeNumberType = double> Vector< RangeNumberType > BEMTools::shape_values_in_default_dof_order (const FiniteElement< dim, spacedim > & fe, const Point< dim > & p)
Evaluate a list of shape functions at the specified area coordinates in the default DoF order.
Note
The support points, shape functions and DoFs in the finite element are enumerated in the hierarchic order for the continuous element FE_Q, while the discontinuous element FE_DGQ adopts the lexicographic order.
Parameters
fe
p The area coordinates at which the shape functions are to be evaluated.
Returns
A list of shape function values.
Definition at line 535 of file bem_tools.h.
References BEMTools::shape_values_in_default_dof_order().
Referenced by BEMTools::shape_values_in_default_dof_order().
shape_values_in_lexicographic_order()
template<int dim, int spacedim, typename RangeNumberType = double> Vector< RangeNumberType > BEMTools::shape_values_in_lexicographic_order (const FiniteElement< dim, spacedim > & fe, const Point< dim > & p)
Evaluate a list of shape functions at the specified area coordinates in the lexicographic order.
Note
The support points, shape functions and DoFs in the finite element are enumerated in the hierarchic order for the continuous element FE_Q, while the discontinuous element FE_DGQ adopts the lexicographic order.
Parameters
fe
p The area coordinates at which the shape functions are to be evaluated.
Returns
A list of shape function values.
Definition at line 564 of file bem_tools.h.
References BEMTools::shape_values_in_lexicographic_order().
Referenced by BEMTools::shape_values_in_lexicographic_order().
surface_covariant_transformation()
template<int spacedim, typename RangeNumberType = double> LAPACKFullMatrixExt< RangeNumberType > BEMTools::surface_covariant_transformation (const unsigned int k3_index, const unsigned int quad_no, const Table< 3, LAPACKFullMatrixExt< RangeNumberType > > & mapping_shape_grad_matrix_table, const unsigned int mapping_index, const unsigned int mapping_n_shape_functions, const std::vector< Point< spacedim, RangeNumberType > > & support_points_in_real_cell)
Calculate the covariant transformation matrix for mapping the gradient in local coordinate chart to global coordinates.
The formula for calculating the covariant transformation matrix:
\[ J G^{-1} = J (J^T J)^{-1}. \]
N.B. \(J\) is the Jacobian matrix in \(\mathbb{R}^{{\rm spacedim}\times{\rm dim}}\). Therefore, the covariant transformation matrix has the same sizes as \(J\).
Parameters
k3_index
quad_no
mapping_shape_grad_matrix_table
mapping_index
mapping_n_shape_functions
support_points_in_real_cell
Returns
Extract the shape function's gradient matrix under the specified \(k_3\) index and quadrature point, which will then be used for calculating the Jacobian matrix.
Metric tensor
Inverse of the metric tensor
\(G=J^T J\)
Definition at line 3195 of file bem_tools.h.
References BEMTools::collect_components_from_points(), LAPACKFullMatrixExt< Number >::invert(), LAPACKFullMatrixExt< Number >::mmult(), BEMTools::surface_covariant_transformation(), and LAPACKFullMatrixExt< Number >::Tmmult().
Referenced by BEMTools::surface_covariant_transformation().
surface_jacobian_det()
template<int spacedim> double BEMTools::surface_jacobian_det (const unsigned int k3_index, const unsigned int quad_no, const Table< 2, LAPACKFullMatrixExt< double > > & shape_grad_matrix_table, const std::vector< Point< spacedim > > & support_points_in_real_cell)
Calculate the surface Jacobian determinant at the quadrature point specified by its index.
Parameters
k3_index \(k_3\) term index
quad_no Quadrature point index
shape_grad_matrix_table The data table storing the gradient values of the shape functions. Refer to BEMValues::kx_shape_grad_matrix_table_for_same_panel.
support_points_in_real_cell A list of support points in the real cell in the lexicographic order.
Returns
Surface Jacobian determinant or surface metric tensor
Extract the shape function's gradient matrix under the specified \(k_3\) index and quadrature point.
Definition at line 2984 of file bem_tools.h.
References BEMTools::collect_two_components_from_point3(), LAPACKFullMatrixExt< Number >::determinant2x2(), LAPACKFullMatrixExt< Number >::mmult(), and BEMTools::surface_jacobian_det().
Referenced by BEMTools::surface_jacobian_det(), and BEMTools::surface_jacobian_det_and_normal_vector().
surface_jacobian_det_and_normal_vector() [1/2]
template<int spacedim, typename RangeNumberType = double> RangeNumberType BEMTools::surface_jacobian_det_and_normal_vector (const std::vector< Point< spacedim, RangeNumberType > > & mapping_support_points, const LAPACKFullMatrixExt< RangeNumberType > & mapping_shape_grad_matrix, Tensor< 1, spacedim, RangeNumberType > & normal_vector, const bool is_normal_vector_negated = false)
Compute the Jacobian determinant and normal vector at a given point in the unit cell.
The point in the unit cell is not explicitly given, but the mapping shape function's gradient matrix provided has been evaluated at this point.
This loop transform the vector \([J_{01}, J_{12}, J_{20}]/\abs{J}\) to \([J_{12}, J_{20}, J_{01}]/\abs{J}\), which is the normal vector.
Definition at line 3121 of file bem_tools.h.
References BEMTools::collect_two_components_from_point3(), LAPACKFullMatrixExt< Number >::determinant2x2(), LAPACKFullMatrixExt< Number >::mmult(), BEMTools::surface_jacobian_det(), and BEMTools::surface_jacobian_det_and_normal_vector().
surface_jacobian_det_and_normal_vector() [2/2]
template<int spacedim, typename RangeNumberType = double> RangeNumberType BEMTools::surface_jacobian_det_and_normal_vector (const unsigned int k3_index, const unsigned int quad_no, const Table< 3, LAPACKFullMatrixExt< RangeNumberType > > & mapping_shape_grad_matrix_table, const unsigned int mapping_index, const unsigned int mapping_n_shape_functions, const std::vector< Point< spacedim, RangeNumberType > > & support_points_in_real_cell, Tensor< 1, spacedim, RangeNumberType > & normal_vector, const bool is_normal_vector_negated = false)
Calculate the surface Jacobian determinant and the normal vector at the quadrature point specified by its index.
Note
N.B. The reversed lexicographic order appears for \(K_y\) when the cell neighboring type is common edge. Then the calculated normal vector \(n_y\) has the opposite direction of the real one, which should be negated in the subsequent calculation.
Parameters
k3_index \(k_3\) term index
quad_no Quadrature point index
mapping_shape_grad_matrix_table The data table storing the gradient values of the shape functions. Refer to BEMValues::kx_shape_grad_matrix_table_for_same_panel.
mapping_index Index to the mapping object for the current cell.
support_points_in_real_cell A list of support points in the real cell in the lexicographic order.
normal_vector
is_normal_vector_negated Whether the direction of the computed normal vector should be negated.
Returns
Surface Jacobian determinant or surface metric tensor
Extract the shape function's gradient matrix under the specified mapping index, \(k_3\) index and quadrature point index. The first dimension of the gradient matrix is the shape function index and the second dimension is coordinate component index in the unit cell.
This loop transform the vector \([J_{01}, J_{12}, J_{20}]/\abs{J}\) to \([J_{12}, J_{20}, J_{01}]/\abs{J}\), which is the normal vector.
Definition at line 3043 of file bem_tools.h.
References BEMTools::collect_two_components_from_point3(), LAPACKFullMatrixExt< Number >::determinant2x2(), LAPACKFullMatrixExt< Number >::mmult(), BEMTools::surface_jacobian_det(), and BEMTools::surface_jacobian_det_and_normal_vector().
Referenced by BEMTools::surface_jacobian_det_and_normal_vector().
transform_quad_point_from_unit_to_permuted_real_cell()
template<int spacedim, typename RangeNumberType = double> Point< spacedim, RangeNumberType > BEMTools::transform_quad_point_from_unit_to_permuted_real_cell (const unsigned int k3_index, const unsigned int quad_no, const Table< 4, RangeNumberType > & mapping_shape_value_table, const unsigned int mapping_index, const unsigned int mapping_n_shape_functions, const std::vector< Point< spacedim, RangeNumberType > > & mapping_support_points_in_real_cell)
Coordinate transformation of the specified quadrature point in the unit cell to the real cell based on a list of support points in the real cell. This version runs on the host.
Parameters
k3_index
quad_no Quadrature point index
mapping_shape_value_table Data table for the mapping shape function values. Refer to BEMValues::kx_shape_value_table_for_same_panel.
mapping_support_points_in_real_cell A list of support points in the real cell in the lexicographic order.
Returns
Point coordinates in the real cell, which has the spatial dimension spacedim.
Linear combination of support point coordinates and evaluation of mapping shape functions at the specified area coordinates.
Definition at line 3264 of file bem_tools.h.
References BEMTools::transform_quad_point_from_unit_to_permuted_real_cell().
Referenced by BEMTools::transform_quad_point_from_unit_to_permuted_real_cell().