HierBEM: include/linear_algebra/blas_helpers.h File Reference
blas_helpers.h File Reference
Linear algebra
Helper functions for calling BLAS functions.
#include <deal.II/base/aligned_vector.h>
#include <deal.II/base/numbers.h>
#include <deal.II/base/types.h>
#include <deal.II/base/vectorization.h>
#include <deal.II/lac/lapack_support.h>
#include <deal.II/lac/vector_operations_internal.h>
#include <type_traits>
#include "blas_templates.h"
#include "config.h"
Typedefs
using BLASHelpers::size_type = dealii::types::blas_int
Functions
template<typename VectorType >
VectorType::value_type BLASHelpers::inner_product_helper (const size_type n, const VectorType &x, const VectorType &y, const size_type incx=1, const size_type incy=1)
Compute the inner product of x and y. When in the complex valued case, complex conjugation is applied to y.
template<typename VectorType >
VectorType::value_type BLASHelpers::linear_combination_helper (const size_type n, const VectorType &x, const VectorType &y, const size_type incx=1, const size_type incy=1)
Compute the linear combination of x and y. When in the complex valued case, there is no complex conjugation applied to y.
template<typename Number , template< typename > typename VectorType>
void BLASHelpers::scal_helper (const size_type n, const Number alpha, VectorType< Number > &array, const size_type incx=1)
Scale a vector.
Detailed Description
Helper functions for calling BLAS functions.
Date
2025-03-28
Author
Jihuan Tian
Definition in file blas_helpers.h.
Typedef Documentation
size_type
using BLASHelpers::size_type = typedef dealii::types::blas_int
Definition at line 40 of file blas_helpers.h.
Function Documentation
inner_product_helper()
template<typename VectorType > VectorType::value_type BLASHelpers::inner_product_helper (const size_type n, const VectorType & x, const VectorType & y, const size_type incx = 1, const size_type incy = 1)
Compute the inner product of x and y. When in the complex valued case, complex conjugation is applied to y.
Template Parameters
VectorType
Parameters
n
x
y
incx
incy
Returns
Definition at line 56 of file blas_helpers.h.
References BLASHelpers::inner_product_helper().
Referenced by BLASHelpers::inner_product_helper().
linear_combination_helper()
template<typename VectorType > VectorType::value_type BLASHelpers::linear_combination_helper (const size_type n, const VectorType & x, const VectorType & y, const size_type incx = 1, const size_type incy = 1)
Compute the linear combination of x and y. When in the complex valued case, there is no complex conjugation applied to y.
Template Parameters
VectorType
Parameters
n
x
y
incx
incy
Returns
Definition at line 91 of file blas_helpers.h.
References BLASHelpers::linear_combination_helper().
Referenced by BLASHelpers::linear_combination_helper().
scal_helper()
template<typename Number , template< typename > typename VectorType> void BLASHelpers::scal_helper (const size_type n, const Number alpha, VectorType< Number > & array, const size_type incx = 1)
Scale a vector.
Template Parameters
Number
Parameters
n
alpha
array
incx
Definition at line 121 of file blas_helpers.h.
References BLASHelpers::scal_helper().
Referenced by BLASHelpers::scal_helper().