HierBEM: include/cluster_tree/block_cluster_tree.h File Reference
block_cluster_tree.h File Reference
Hierarchical matrices
Implementation of the class BlockClusterTree.
#include <deal.II/base/memory_consumption.h>
#include "block_cluster.h"
#include "cluster_tree.h"
#include "config.h"
#include "linear_algebra/lapack_full_matrix_ext.h"
#include "tree.h"
#include "utilities/debug_tools.h"
Classes
class BlockClusterTree< spacedim, Number >
Class for block cluster tree.
Functions
template<int spacedim, typename Number >
std::ostream & operator<< (std::ostream &out, const BlockClusterTree< spacedim, Number > &block_cluster_tree)
template<int spacedim, typename Number >
void split_block_cluster_node (TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > *bc_node, BlockClusterTree< spacedim, Number > &bc_tree, const TreeNodeSplitMode split_mode, const bool if_add_child_nodes_to_leaf_set=true)
template<int spacedim, typename Number = double>
bool prune_to_partition_recursion (BlockClusterTree< spacedim, Number > &bct, const std::vector< TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * > &partition, TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > *bc_node)
template<int spacedim, typename Number >
TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * find_bc_node_in_partition_intersect_current_bc_node (TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > *current_bc_node, const std::vector< TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * > &partition)
template<int spacedim, typename Number >
TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * find_bc_node_in_partition_proper_subset_of_current_bc_node (TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > *current_bc_node, const std::vector< TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * > &partition)
template<int spacedim, typename Number >
void print_block_cluster_node_info_as_dot_node (std::ostream &out, const TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > *current_bc_node)
Detailed Description
Implementation of the class BlockClusterTree.
Date
2021-04-20
Author
Jihuan Tian
Definition in file block_cluster_tree.h.
Function Documentation
find_bc_node_in_partition_intersect_current_bc_node()
template<int spacedim, typename Number > TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * find_bc_node_in_partition_intersect_current_bc_node (TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * current_bc_node, const std::vector< TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * > & partition)
Find a block cluster node in the given partition which has nonempty intersection with the current block cluster node.
Parameters
current_bc_node
partition
Returns
Definition at line 3575 of file block_cluster_tree.h.
Referenced by BlockClusterTree< spacedim, Number >::extend_finer_than_partition().
find_bc_node_in_partition_proper_subset_of_current_bc_node()
template<int spacedim, typename Number > TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * find_bc_node_in_partition_proper_subset_of_current_bc_node (TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * current_bc_node, const std::vector< TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * > & partition)
Definition at line 3606 of file block_cluster_tree.h.
operator<<()
template<int spacedim, typename Number > std::ostream & operator<< (std::ostream & out, const BlockClusterTree< spacedim, Number > & block_cluster_tree)
Definition at line 913 of file block_cluster_tree.h.
print_block_cluster_node_info_as_dot_node()
template<int spacedim, typename Number > void print_block_cluster_node_info_as_dot_node (std::ostream & out, const TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * current_bc_node)
Create the graph node for the current block cluster node. When the current block cluster node belongs to the near field, use red background. When it belongs to the far field, use green background. Otherwise, use white background.
Construct the relationship between the current node and its children.
Print each child block cluster node.
Definition at line 3636 of file block_cluster_tree.h.
Referenced by BlockClusterTree< spacedim, Number >::print_bct_info_as_dot().
prune_to_partition_recursion()
template<int spacedim, typename Number = double> bool prune_to_partition_recursion (BlockClusterTree< spacedim, Number > & bct, const std::vector< TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * > & partition, TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * bc_node)
Prune all those block cluster nodes which are descendants of the block cluster nodes specified in the given partition.
Note
Because the block cluster nodes in the given partition are not contained in the block cluster tree, it is necessary to traverse the whole block cluster tree by recursion, during which each block cluster node is checked whether it belongs to the partition so that its descendants should be pruned.
Parameters
bct The block cluster tree to be pruned.
partition The given partition whose descendants will be pruned from the original block cluster tree.
bc_node The current block cluster node to be checked and determined whether it belongs to the partition so that its descendants should be pruned.
Definition at line 1263 of file block_cluster_tree.h.
References find_pointer_data(), BlockClusterTree< spacedim, Number >::prune_descendants_from_node(), and prune_to_partition_recursion().
Referenced by BlockClusterTree< spacedim, Number >::prune_to_partition(), and prune_to_partition_recursion().
split_block_cluster_node()
template<int spacedim, typename Number > void split_block_cluster_node (TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * bc_node, BlockClusterTree< spacedim, Number > & bc_tree, const TreeNodeSplitMode split_mode, const bool if_add_child_nodes_to_leaf_set = true)
Split a block cluster node in a block cluster tree according to the given split mode.
After the splitting, the total number of block cluster nodes in the block cluster tree will be updated. Whether the leaf set will be added with the newly created block cluster nodes is controlled by the flag if_add_child_nodes_to_leaf_set.
Note
If the newly created block cluster nodes are to be added to the leaf set, their parent block cluster node should firstly be erased from the leaf set. This operation is not included in this function and should be performed beforehand.
Parameters
bc_node Pointer to the block cluster node
bc_tree Reference to the block cluster tree
split_mode
if_add_child_nodes_to_leaf_set If the newly created block cluster nodes will be appended to the leaf set of the block cluster tree.
Work flow
Horizontal split mode
Set the split mode of the current block cluster node.
Create a new block cluster node by constructing its index set or index range as \(\tau^* \times \sigma\) with \(\tau^* \in S(\tau)\). Its parent node is set to the current block cluster node.
Check if the block cluster node is small.
Append this new node as a child of the current block cluster node.
Add this new node to the leaf set if necessary.
Increase the total number of nodes in the block cluster tree.
Vertical split mode
Set the split mode of the current block cluster node.
Create a new block cluster node by constructing its index set as \(\tau \times \sigma^*\) with \(\sigma^* \in S(\sigma)\). Its parent node is set to the current block cluster node.
Check if the block cluster node is small.
Append this new node as a child of the current block cluster node.
Add this new node to the leaf set if necessary.
Increase the total number of nodes in the block cluster tree.
Cross split mode
Set the split mode of the current block cluster node.
Create a new block cluster node by constructing its index set as \(\tau^* \times \sigma^*\) with \(\tau^* \in S(\tau)\) and \(\sigma^* \in S(\sigma)\). Its parent node is set to the current block cluster node.
Check if the block cluster node is small.
Append this new node as one of the children of the current block cluster node.
Add this new node to the leaf set if necessary.
Increase the total number of nodes in the block cluster tree.
Definition at line 972 of file block_cluster_tree.h.
Referenced by BlockClusterTree< spacedim, Number >::extend_finer_than_partition(), HMatrix< spacedim, Number >::h_h_mmult_cross_split(), HMatrix< spacedim, Number >::h_h_mmult_horizontal_split(), and HMatrix< spacedim, Number >::h_h_mmult_vertical_split().