HierBEM: LAPACKFullMatrixExt< Number > Class Template Reference
LAPACKFullMatrixExt< Number > Class Template Reference
#include <lapack_full_matrix_ext.h>
Public Types
using size_type = std::make_unsigned< types::blas_int >::type
using value_type = Number
using real_type = typename numbers::NumberTraits< Number >::real_type
Public Member Functions
LAPACKFullMatrixExt (const size_type size=0)
LAPACKFullMatrixExt (const size_type rows, const size_type cols)
LAPACKFullMatrixExt (const LAPACKFullMatrixExt &mat)
LAPACKFullMatrixExt (const LAPACKFullMatrix< Number > &mat)
LAPACKFullMatrixExt (const std::array< types::global_dof_index, 2 > &row_index_range, const std::array< types::global_dof_index, 2 > &column_index_range, const LAPACKFullMatrixExt< Number > &M)
LAPACKFullMatrixExt (const std::array< types::global_dof_index, 2 > &row_index_range, const std::array< types::global_dof_index, 2 > &column_index_range, const LAPACKFullMatrixExt< Number > &M, const std::array< types::global_dof_index, 2 > &M_row_index_range, const std::array< types::global_dof_index, 2 > &M_column_index_range)
LAPACKFullMatrixExt (const LAPACKFullMatrixExt &M1, const LAPACKFullMatrixExt &M2, bool is_horizontal_split)
LAPACKFullMatrixExt (const LAPACKFullMatrixExt &M11, const LAPACKFullMatrixExt &M12, const LAPACKFullMatrixExt &M21, const LAPACKFullMatrixExt &M22)
LAPACKFullMatrixExt< Number > & operator= (const LAPACKFullMatrixExt< Number > &matrix)
LAPACKFullMatrixExt< Number > & operator= (const LAPACKFullMatrix< Number > &matrix)
LAPACKFullMatrixExt< Number > & operator= (const Number d)
template<typename Number2 >
LAPACKFullMatrixExt< Number > & operator*= (const Number2 factor)
template<typename Number2 >
LAPACKFullMatrixExt< Number > & operator/= (const Number2 factor)
void lower_triangular (LAPACKFullMatrixExt< Number > &tril)
void upper_triangular (LAPACKFullMatrixExt< Number > &triu)
void set_column_zeros (const size_type col_index)
void set_row_zeros (const size_type row_index)
void get_row (const size_type row_index, Vector< Number > &row_values) const
void get_column (const size_type col_index, Vector< Number > &col_values) const
void remove_row (const size_type row_index)
void remove_rows (const std::vector< size_type > &row_indices)
void keep_first_n_rows (const size_type n, bool other_rows_removed=true)
void remove_column (const size_type column_index)
void remove_columns (const std::vector< size_type > &column_indices)
void keep_first_n_columns (const size_type n, bool other_columns_removed=true)
void svd (LAPACKFullMatrixExt< Number > &U, std::vector< real_type > &Sigma_r, LAPACKFullMatrixExt< Number > &VT)
void svd (LAPACKFullMatrixExt< Number > &U, std::vector< real_type > &Sigma_r, LAPACKFullMatrixExt< Number > &VT, const size_type truncation_rank)
size_type reduced_svd (LAPACKFullMatrixExt< Number > &U, std::vector< real_type > &Sigma_r, LAPACKFullMatrixExt< Number > &VT, size_type truncation_rank, real_type singular_value_threshold=0.)
size_type reduced_svd (LAPACKFullMatrixExt< Number > &U, std::vector< real_type > &Sigma_r, LAPACKFullMatrixExt< Number > &VT, LAPACKFullMatrixExt< Number > &C, LAPACKFullMatrixExt< Number > &D, size_type truncation_rank, real_type singular_value_threshold=0.)
void compute_lu_factorization ()
void compute_cholesky_factorization ()
std::vector< types::blas_int > & get_lu_permutation ()
const std::vector< types::blas_int > & get_lu_permutation () const
size_type rank (real_type threshold=0.) const
void qr (LAPACKFullMatrixExt< Number > &Q, LAPACKFullMatrixExt< Number > &R)
void reduced_qr (LAPACKFullMatrixExt< Number > &Q, LAPACKFullMatrixExt< Number > &R)
template<typename Number2 >
void scale_rows (const std::vector< Number2 > &V)
template<typename Number2 >
void scale_rows (LAPACKFullMatrixExt< Number > &A, const std::vector< Number2 > &V) const
template<typename Number2 >
void scale_rows (const Vector< Number2 > &V)
template<typename Number2 >
void scale_columns (const std::vector< Number2 > &V)
template<typename Number2 >
void scale_columns (LAPACKFullMatrixExt< Number > &A, const std::vector< Number2 > &V) const
template<typename Number2 >
void scale_columns (const Vector< Number2 > &V)
void conjugate ()
Apply complex conjugation to the current matrix.
void conjugate (LAPACKFullMatrixExt< Number > &mat) const
void transpose ()
void transpose (LAPACKFullMatrixExt< Number > &AT) const
real_type norm (const char type) const
real_type l1_norm () const
real_type linfty_norm () const
real_type frobenius_norm () const
template<typename MatrixType , typename Number2 = double>
void fill (const MatrixType &src, const size_type dst_offset_i=0, const size_type dst_offset_j=0, const size_type src_offset_i=0, const size_type src_offset_j=0, const Number2 factor=Number2(1.), const bool transpose=false, const bool is_adding=false)
void fill_row (const size_type row_index, const Vector< Number > &values, const bool is_adding=false)
void fill_row (const size_type dst_row_index, const size_type src_row_index, const LAPACKFullMatrixExt< Number > &M, const Number factor=1., const bool is_adding=false)
void fill_rows (const std::array< types::global_dof_index, 2 > &row_index_range, const LAPACKFullMatrixExt< Number > &M, const std::array< types::global_dof_index, 2 > &M_row_index_range, const Number factor=1., const bool is_adding=false)
void fill_col (const size_type col_index, const Vector< Number > &values, const bool is_adding=false)
void hstack (LAPACKFullMatrixExt< Number > &C, const LAPACKFullMatrixExt< Number > &B) const
void vstack (LAPACKFullMatrixExt< Number > &C, const LAPACKFullMatrixExt< Number > &B) const
size_type rank_k_decompose (const unsigned int k, LAPACKFullMatrixExt< Number > &A, LAPACKFullMatrixExt< Number > &B)
size_type rank_k_decompose (const unsigned int k, LAPACKFullMatrixExt< Number > &A, LAPACKFullMatrixExt< Number > &B, LAPACKFullMatrixExt< Number > &C, LAPACKFullMatrixExt< Number > &D)
size_type rank_k_decompose (LAPACKFullMatrixExt< Number > &A, LAPACKFullMatrixExt< Number > &B)
size_type rank_k_decompose (const unsigned int k, LAPACKFullMatrixExt< Number > &A, LAPACKFullMatrixExt< Number > &B, bool is_left_associative)
size_type rank_k_decompose (const unsigned int k, LAPACKFullMatrixExt< Number > &A, LAPACKFullMatrixExt< Number > &B, LAPACKFullMatrixExt< Number > &C, LAPACKFullMatrixExt< Number > &D, bool is_left_associative)
template<typename Number2 , typename Number3 >
void add (LAPACKFullMatrixExt< Number3 > &C, const LAPACKFullMatrixExt< Number2 > &B, const bool is_result_matrix_symm_apriori=false) const
template<typename Number2 , typename Number3 , typename Number4 >
void add (LAPACKFullMatrixExt< Number4 > &C, const Number2 b, const LAPACKFullMatrixExt< Number3 > &B, const bool is_result_matrix_symm_apriori=false) const
template<typename Number2 >
void add (const LAPACKFullMatrixExt< Number2 > &B, const bool is_result_matrix_store_tril_only=false)
template<typename Number2 , typename Number3 >
void add (const Number2 b, const LAPACKFullMatrixExt< Number3 > &B, const bool is_result_matrix_store_tril_only=false)
template<typename Number2 >
void add (const size_type i, const size_type j, const Number2 value)
Add a single value to the specified matrix element.
void outer_product_formal (const Vector< Number > &v, const Vector< Number > &w)
Compute the formal outer product of the two vectors and store the results into the current matrix.
void outer_product (const Vector< Number > &v, const Vector< Number > &w)
Compute the outer product of the two vectors and store the results into the current matrix.
template<typename Number2 >
void vmult (Vector< Number > &w, const Number2 alpha, const Vector< Number > &v, const bool adding=false) const
void vmult (Vector< Number > &w, const Vector< Number > &v, const bool adding=false) const
template<typename Number2 >
void vmult_add (Vector< Number > &w, const Number2 alpha, const Vector< Number > &v) const
void vmult_add (Vector< Number > &w, const Vector< Number > &v) const
void Cvmult (Vector< Number > &w, const Vector< Number > &v, const bool adding=false) const
void Tvmult (Vector< Number > &w, const Vector< Number > &v, const bool adding=false) const
void Hvmult (Vector< Number > &w, const Vector< Number > &v, const bool adding=false) const
void mmult (LAPACKFullMatrixExt< Number > &C, const LAPACKFullMatrixExt< Number > &B, const bool adding=false) const
template<typename Number2 >
void mmult (LAPACKFullMatrixExt< Number > &C, const Number2 alpha, const LAPACKFullMatrixExt< Number > &B, const bool adding=false) const
void mTmult (LAPACKFullMatrixExt< Number > &C, const LAPACKFullMatrixExt< Number > &B, bool adding=false) const
template<typename Number2 >
void mTmult (LAPACKFullMatrixExt< Number > &C, const Number2 alpha, const LAPACKFullMatrixExt< Number > &B, bool adding=false) const
void Tmmult (LAPACKFullMatrixExt< Number > &C, const LAPACKFullMatrixExt< Number > &B, bool adding=false) const
template<typename Number2 >
void Tmmult (LAPACKFullMatrixExt< Number > &C, const Number2 alpha, const LAPACKFullMatrixExt< Number > &B, bool adding=false) const
void mHmult (LAPACKFullMatrixExt< Number > &C, const LAPACKFullMatrixExt< Number > &B, bool adding=false) const
template<typename Number2 >
void mHmult (LAPACKFullMatrixExt< Number > &C, const Number2 alpha, const LAPACKFullMatrixExt< Number > &B, bool adding=false) const
void Hmmult (LAPACKFullMatrixExt< Number > &C, const LAPACKFullMatrixExt< Number > &B, bool adding=false) const
template<typename Number2 >
void Hmmult (LAPACKFullMatrixExt< Number > &C, const Number2 alpha, const LAPACKFullMatrixExt< Number > &B, bool adding=false) const
template<typename Number2 >
void precondition_Jacobi (Vector< Number2 > &dst, const Vector< Number2 > &src, const real_type omega=1.) const
Number determinant2x2 () const
Number determinant3x3 () const
void invert (const LAPACKFullMatrixExt< Number > &M)
void invert_by_gauss_elim (LAPACKFullMatrixExt< Number > &M_inv)
void set_property (const LAPACKSupport::Property property)
void set_state (const LAPACKSupport::State state)
LAPACKSupport::Property get_property () const
LAPACKSupport::State get_state () const
void solve (Vector< Number > &v, const bool transposed=false) const
void solve_by_forward_substitution (Vector< Number > &b, const bool transposed=false, const bool is_unit_diagonal=true, const bool permute_rhs_vector=false) const
void solve_by_forward_substitution (Vector< Number > &x, const Vector< Number > &b, const bool transposed=false, const bool is_unit_diagonal=true) const
void solve_by_backward_substitution (Vector< Number > &b, const bool transposed=false, const bool is_unit_diagonal=false) const
void solve_by_backward_substitution (Vector< Number > &x, const Vector< Number > &b, const bool transposed=false, const bool is_unit_diagonal=false) const
void print_formatted_to_mat (std::ostream &out, const std::string &name, const unsigned int precision=8, const bool scientific=true, const unsigned int width=0, const char *zero_string="0", const double denominator=1., const double threshold=0.) const
void read_from_mat (std::ifstream &in, const std::string &name)
std::size_t memory_consumption () const
Static Public Member Functions
static void ZeroMatrix (const size_type rows, const size_type cols, LAPACKFullMatrixExt< Number > &matrix)
static void ConstantMatrix (const size_type rows, const size_type cols, Number value, LAPACKFullMatrixExt< Number > &matrix)
static void DiagMatrix (const size_type dim, Number value, LAPACKFullMatrixExt &matrix)
static void IdentityMatrix (const size_type dim, LAPACKFullMatrixExt &matrix)
static void Reshape (const size_type rows, const size_type cols, const std::vector< Number > &values, LAPACKFullMatrixExt< Number > &matrix)
static void Reshape (const size_type rows, const size_type cols, const Number *values, LAPACKFullMatrixExt< Number > &matrix)
static size_type reduced_svd_on_AxBH (LAPACKFullMatrixExt< Number > &A, LAPACKFullMatrixExt< Number > &B, LAPACKFullMatrixExt< Number > &U, std::vector< typename numbers::NumberTraits< Number >::real_type > &Sigma_r, LAPACKFullMatrixExt< Number > &VT, typename numbers::NumberTraits< Number >::real_type singular_value_threshold=0.)
static size_type reduced_svd_on_AxBH (LAPACKFullMatrixExt< Number > &A, LAPACKFullMatrixExt< Number > &B, LAPACKFullMatrixExt< Number > &U, std::vector< typename numbers::NumberTraits< Number >::real_type > &Sigma_r, LAPACKFullMatrixExt< Number > &VT, size_type truncation_rank, typename numbers::NumberTraits< Number >::real_type singular_value_threshold=0.)
static size_type reduced_svd_on_AxBH (LAPACKFullMatrixExt< Number > &A, LAPACKFullMatrixExt< Number > &B, LAPACKFullMatrixExt< Number > &U, std::vector< typename numbers::NumberTraits< Number >::real_type > &Sigma_r, LAPACKFullMatrixExt< Number > &VT, LAPACKFullMatrixExt< Number > &C, LAPACKFullMatrixExt< Number > &D, size_type truncation_rank, typename numbers::NumberTraits< Number >::real_type singular_value_threshold=0.)
Private Attributes
LAPACKSupport::State state
LAPACKSupport::Property property
std::vector< Number > tau
std::vector< Number > work
std::vector< types::blas_int > iwork
std::vector< types::blas_int > ipiv
std::mutex mutex
Friends
template<typename Number1 >
void balance_frobenius_norm (LAPACKFullMatrixExt< Number1 > &A, LAPACKFullMatrixExt< Number1 > &B)
Detailed Description
template<typename Number>
class LAPACKFullMatrixExt< Number >
Extend and expose more of the the functionality of LAPACKFullMatrix.
Definition at line 89 of file lapack_full_matrix_ext.h.
Member Typedef Documentation
real_type
template<typename Number > using LAPACKFullMatrixExt< Number >::real_type = typename numbers::NumberTraits<Number>::real_type
Definition at line 98 of file lapack_full_matrix_ext.h.
size_type
template<typename Number > using LAPACKFullMatrixExt< Number >::size_type = std::make_unsigned<types::blas_int>::type
Declare the type for container size.
Definition at line 95 of file lapack_full_matrix_ext.h.
value_type
template<typename Number > using LAPACKFullMatrixExt< Number >::value_type = Number
Definition at line 97 of file lapack_full_matrix_ext.h.
Constructor & Destructor Documentation
LAPACKFullMatrixExt() [1/8]
template<typename Number > LAPACKFullMatrixExt< Number >::LAPACKFullMatrixExt (const size_type size = 0)
Construct a square matrix by specifying the dimension.
Set the property of the parent class as well.
Definition at line 2462 of file lapack_full_matrix_ext.h.
LAPACKFullMatrixExt() [2/8]
template<typename Number > LAPACKFullMatrixExt< Number >::LAPACKFullMatrixExt (const size_type rows, const size_type cols)
Construct a matrix by specifying the number of rows and columns.
Parameters
rows
cols
Set the property of the parent class as well.
Definition at line 2479 of file lapack_full_matrix_ext.h.
LAPACKFullMatrixExt() [3/8]
template<typename Number > LAPACKFullMatrixExt< Number >::LAPACKFullMatrixExt (const LAPACKFullMatrixExt< Number > & mat)
Copy constructor from an LAPACKFullMatrixExt object.
Parameters
mat
Set the property of the parent class as well.
Definition at line 2497 of file lapack_full_matrix_ext.h.
LAPACKFullMatrixExt() [4/8]
template<typename Number > LAPACKFullMatrixExt< Number >::LAPACKFullMatrixExt (const LAPACKFullMatrix< Number > & mat)
Copy constructor from an LAPACKFullMatrix object.
Note
N.B. The state and property fields of mat is not accessible, because they are private members in the class LAPACKFullMatrix<Number>. Hence the state of the current matrix is set to the default matrix and its property is set to the default general.
Parameters
mat
Set the property of the parent class as well.
Definition at line 2514 of file lapack_full_matrix_ext.h.
LAPACKFullMatrixExt() [5/8]
template<typename Number > LAPACKFullMatrixExt< Number >::LAPACKFullMatrixExt (const std::array< types::global_dof_index, 2 > & row_index_range, const std::array< types::global_dof_index, 2 > & column_index_range, const LAPACKFullMatrixExt< Number > & M)
Construct a full matrix by restriction to the block cluster \(\tau \times \sigma\) defined by their index ranges from the global full matrix M.
Parameters
row_index_range
column_index_range
M
Set the property of the parent class as well.
Extract the data for the submatrix defined on the block cluster \(\tau \times \sigma\) from the full global matrix M.
Because M is global, the indices in \(\tau\) and \(\sigma\) can be directly used for accessing the elements of M.
Definition at line 2532 of file lapack_full_matrix_ext.h.
LAPACKFullMatrixExt() [6/8]
template<typename Number > LAPACKFullMatrixExt< Number >::LAPACKFullMatrixExt (const std::array< types::global_dof_index, 2 > & row_index_range, const std::array< types::global_dof_index, 2 > & column_index_range, const LAPACKFullMatrixExt< Number > & M, const std::array< types::global_dof_index, 2 > & M_row_index_range, const std::array< types::global_dof_index, 2 > & M_column_index_range)
Construct a full matrix by restriction to the block cluster \(\tau \times \sigma\) defined by their index ranges from the local full matrix M.
Parameters
row_index_range
column_index_range
M The larger full matrix to be restricted.
M_row_index_range
M_column_index_range
Make an assertion that the index ranges for the matrix to be built should be subsets of the index ranges for the local matrix M.
Set the property of the parent class as well.
Extract the data for the submatrix block \(b = \tau \times \sigma\) from the original matrix M.
Definition at line 2569 of file lapack_full_matrix_ext.h.
References is_subset().
LAPACKFullMatrixExt() [7/8]
template<typename Number > LAPACKFullMatrixExt< Number >::LAPACKFullMatrixExt (const LAPACKFullMatrixExt< Number > & M1, const LAPACKFullMatrixExt< Number > & M2, bool is_horizontal_split)
Construct a full matrix \(M\) from an agglomeration of two full submatrices \(M_1\) and \(M_2\), which have been obtained from either horizontal splitting or vertical splitting.
When the two submatrices have been obtained from horizontal splitting, vstack will be used for the agglomeration. When the two submatrices have been obtained from vertical splitting, hstack will be used for the agglomeration.
Parameters
M1
M2
is_horizontal_split
Set the property of the parent class as well.
Definition at line 2615 of file lapack_full_matrix_ext.h.
References LAPACKFullMatrixExt< Number >::hstack(), and LAPACKFullMatrixExt< Number >::vstack().
LAPACKFullMatrixExt() [8/8]
template<typename Number > LAPACKFullMatrixExt< Number >::LAPACKFullMatrixExt (const LAPACKFullMatrixExt< Number > & M11, const LAPACKFullMatrixExt< Number > & M12, const LAPACKFullMatrixExt< Number > & M21, const LAPACKFullMatrixExt< Number > & M22)
Construct a full matrix \(M\) from an agglomeration of four full submatrices, \(M_{11}, M_{12}, M_{21}, M_{22}\).
\[ M = \begin{pmatrix} M_{11} & M_{12} \\ M_{21} & M_{22} \end{pmatrix} \]
Note
This method implements (7.7) for full matrices in Hackbusch's \(\mathcal{H}\)-matrix book.
This method is only applicable in the case when the cardinality based cluster tree partition is used.
Set the property of the parent class as well.
Definition at line 2643 of file lapack_full_matrix_ext.h.
Member Function Documentation
add() [1/5]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::add (const LAPACKFullMatrixExt< Number2 > & B, const bool is_result_matrix_store_tril_only = false)
Add the matrix B into the current matrix.
Parameters
B
Perform addition for matrix elements in the diagonal part and in the lower triangular part only.
Definition at line 4947 of file lapack_full_matrix_ext.h.
add() [2/5]
template<typename Number > template<typename Number2 , typename Number3 > void LAPACKFullMatrixExt< Number >::add (const Number2 b, const LAPACKFullMatrixExt< Number3 > & B, const bool is_result_matrix_store_tril_only = false)
Add the matrix B into the current matrix with a factor \(b\) multiplied with \(B\).
Parameters
B
Perform addition for matrix elements in the diagonal part and in the lower triangular part only.
Definition at line 4992 of file lapack_full_matrix_ext.h.
add() [3/5]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::add (const size_type i, const size_type j, const Number2 value)
Add a single value to the specified matrix element.
Parameters
i
j
value
Definition at line 5039 of file lapack_full_matrix_ext.h.
add() [4/5]
template<typename Number > template<typename Number2 , typename Number3 > void LAPACKFullMatrixExt< Number >::add (LAPACKFullMatrixExt< Number3 > & C, const LAPACKFullMatrixExt< Number2 > & B, const bool is_result_matrix_symm_apriori = false) const
Add two matrix into a new matrix \(C = A + B\), where \(A\) is the current matrix.
Perform addition for matrix elements in the diagonal part and in the lower triangular part only.
Definition at line 4846 of file lapack_full_matrix_ext.h.
add() [5/5]
template<typename Number > template<typename Number2 , typename Number3 , typename Number4 > void LAPACKFullMatrixExt< Number >::add (LAPACKFullMatrixExt< Number4 > & C, const Number2 b, const LAPACKFullMatrixExt< Number3 > & B, const bool is_result_matrix_symm_apriori = false) const
Add two matrix into a new matrix \(C = A + b*B\) with a factor \(b\) multiplied with \(B\), where \(A\) is the current matrix.
Perform addition for matrix elements in the diagonal part and in the lower triangular part only.
Definition at line 4896 of file lapack_full_matrix_ext.h.
compute_cholesky_factorization()
template<typename Number > void LAPACKFullMatrixExt< Number >::compute_cholesky_factorization
Compute the Cholesky factorization of the full matrix.
Note
This is a wrapper of the same function in LAPACKFullMatrix<Number> in order that the state of the current LAPACKFullMatrixExt<Number> object can be updated. Before the factorization, the full matrix has matrix state and symmetric property. After the factorization, it has cholesky state and lower_triangular property.
Call the member function in the parent class so that the matrix property in the parent class can be property set.
Definition at line 3861 of file lapack_full_matrix_ext.h.
compute_lu_factorization()
template<typename Number > void LAPACKFullMatrixExt< Number >::compute_lu_factorization
Compute the LU factorization of the full matrix.
Note
This is a copy of the same function in LAPACKFullMatrix<Number> in order that the permutation vector ipiv can be accessed, since ipiv is private in LAPACKFullMatrix<Number>.
Definition at line 3838 of file lapack_full_matrix_ext.h.
conjugate() [1/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::conjugate
Apply complex conjugation to the current matrix.
Definition at line 4313 of file lapack_full_matrix_ext.h.
Referenced by LAPACKFullMatrixExt< Number >::conjugate().
conjugate() [2/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::conjugate (LAPACKFullMatrixExt< Number > & mat) const
Generate a matrix which is the complex conjugate of the current matrix.
Definition at line 4365 of file lapack_full_matrix_ext.h.
References LAPACKFullMatrixExt< Number >::conjugate().
ConstantMatrix()
template<typename Number > void LAPACKFullMatrixExt< Number >::ConstantMatrix (const size_type rows, const size_type cols, Number value, LAPACKFullMatrixExt< Number > & matrix) static
Create constant valued matrix.
Parameters
rows
cols
value
matrix
Definition at line 1576 of file lapack_full_matrix_ext.h.
Cvmult()
template<typename Number > void LAPACKFullMatrixExt< Number >::Cvmult (Vector< Number > & w, const Vector< Number > & v, const bool adding = false) const
Matrix-vector multiplication with the matrix applied complex conjugation.
Definition at line 5245 of file lapack_full_matrix_ext.h.
References LAPACKFullMatrixExt< Number >::vmult().
determinant2x2()
template<typename Number > Number LAPACKFullMatrixExt< Number >::determinant2x2
Calculate the determinant of a \(2\times 2\) matrix.
Returns
Definition at line 6514 of file lapack_full_matrix_ext.h.
Referenced by BEMTools::surface_jacobian_det(), and BEMTools::surface_jacobian_det_and_normal_vector().
determinant3x3()
template<typename Number > Number LAPACKFullMatrixExt< Number >::determinant3x3
Calculate the determinant of a \(3\times 3\) matrix.
Returns
Definition at line 6525 of file lapack_full_matrix_ext.h.
DiagMatrix()
template<typename Number > void LAPACKFullMatrixExt< Number >::DiagMatrix (const size_type dim, Number value, LAPACKFullMatrixExt< Number > & matrix) static
Create a constant valued diagonal matrix.
Parameters
dim
value
matrix
Definition at line 1595 of file lapack_full_matrix_ext.h.
fill()
template<typename Number > template<typename MatrixType , typename Number2 > void LAPACKFullMatrixExt< Number >::fill (const MatrixType & src, const size_type dst_offset_i = 0, const size_type dst_offset_j = 0, const size_type src_offset_i = 0, const size_type src_offset_j = 0, const Number2 factor = Number2(1.), const bool transpose = false, const bool is_adding = false)
Fill a rectangular block into the current matrix. This function has the similar behavior as FullMatrix::fill.
Parameters
src
dst_offset_i
dst_offset_j
src_offset_i
src_offset_j
factor
transpose When this flag is true, the block in the source matrix will be transposed.
Determine the number of rows and columns to be copied.
Definition at line 4485 of file lapack_full_matrix_ext.h.
fill_col()
template<typename Number > void LAPACKFullMatrixExt< Number >::fill_col (const size_type col_index, const Vector< Number > & values, const bool is_adding = false)
Fill the values to the col_index'th column of the current matrix.
Parameters
col_index
values
Definition at line 4636 of file lapack_full_matrix_ext.h.
Referenced by h_f_mmult(), h_f_mTmult(), and h_f_Tmmult().
fill_row() [1/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::fill_row (const size_type dst_row_index, const size_type src_row_index, const LAPACKFullMatrixExt< Number > & M, const Number factor = 1., const bool is_adding = false)
Fill a specified row in the destination matrix with a row extracted from the source matrix.
Parameters
dst_row_index
src_row_index
M
factor
is_adding
Definition at line 4588 of file lapack_full_matrix_ext.h.
fill_row() [2/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::fill_row (const size_type row_index, const Vector< Number > & values, const bool is_adding = false)
Fill the values to the row_index'th row of the current matrix.
Parameters
row_index
values
Definition at line 4563 of file lapack_full_matrix_ext.h.
Referenced by HMatrix< spacedim, Number >::addsym_diag(), f_h_mmult(), f_h_mTmult(), and f_h_Tmmult().
fill_rows()
template<typename Number > void LAPACKFullMatrixExt< Number >::fill_rows (const std::array< types::global_dof_index, 2 > & row_index_range, const LAPACKFullMatrixExt< Number > & M, const std::array< types::global_dof_index, 2 > & M_row_index_range, const Number factor = 1., const bool is_adding = false)
Fill the data in M by rows into the current matrix based on the their index ranges.
Definition at line 4616 of file lapack_full_matrix_ext.h.
References is_subset().
frobenius_norm()
template<typename Number > numbers::NumberTraits< Number >::real_type LAPACKFullMatrixExt< Number >::frobenius_norm (void) const
Definition at line 4475 of file lapack_full_matrix_ext.h.
get_column()
template<typename Number > void LAPACKFullMatrixExt< Number >::get_column (const size_type col_index, Vector< Number > & col_values) const
Get the values of the column col_index into a Vector.
Parameters
col_index
col_values
Definition at line 2958 of file lapack_full_matrix_ext.h.
Referenced by f_h_Tmmult(), h_f_mmult(), h_f_Tmmult(), and random_select_ref_column().
get_lu_permutation() [1/2]
template<typename Number > std::vector< types::blas_int > & LAPACKFullMatrixExt< Number >::get_lu_permutation
Get the reference to the vector which stores the row permutation relation obtained from an LU factorization.
Returns
The vector storing the row permutation relation. Its i'th element stores the row index of the matrix to which the i'th row migrates.
Definition at line 3880 of file lapack_full_matrix_ext.h.
get_lu_permutation() [2/2]
template<typename Number > const std::vector< types::blas_int > & LAPACKFullMatrixExt< Number >::get_lu_permutation
Get the const reference to the vector which stores the row permutation relation obtained from an LU factorization.
Returns
The vector storing the row permutation relation. Its i'th element stores the row index of the matrix to which the i'th row migrates.
Definition at line 3888 of file lapack_full_matrix_ext.h.
get_property()
template<typename Number > LAPACKSupport::Property LAPACKFullMatrixExt< Number >::get_property
Get the matrix property.
Returns
Definition at line 6702 of file lapack_full_matrix_ext.h.
Referenced by fill_hmatrix_leaf_node_with_aca_plus(), HMatrixSymmPreconditioner< spacedim, Number >::HMatrixSymmPreconditioner(), HMatrix< spacedim, Number >::set_current_matrix_property(), and stabilize_near_field_hmatrices_for_hypersingular_kernel().
get_row()
template<typename Number > void LAPACKFullMatrixExt< Number >::get_row (const size_type row_index, Vector< Number > & row_values) const
Get the values of the row row_index into a Vector.
Parameters
row_index
row_values
Definition at line 2940 of file lapack_full_matrix_ext.h.
Referenced by f_h_mmult(), f_h_mTmult(), h_f_mTmult(), and random_select_ref_row().
get_state()
template<typename Number > LAPACKSupport::State LAPACKFullMatrixExt< Number >::get_state
Get the matrix state.
Returns
Definition at line 6709 of file lapack_full_matrix_ext.h.
Hmmult() [1/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::Hmmult (LAPACKFullMatrixExt< Number > & C, const LAPACKFullMatrixExt< Number > & B, bool adding = false) const
Multiply two matrices with the first operand Hermite transposed, i.e. \(C = A^H B\) or \(C = C + A^H B\).
Parameters
C
B
adding
Definition at line 6232 of file lapack_full_matrix_ext.h.
Hmmult() [2/2]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::Hmmult (LAPACKFullMatrixExt< Number > & C, const Number2 alpha, const LAPACKFullMatrixExt< Number > & B, bool adding = false) const
Multiply two matrices with the first operand Hermite transposed and with the product scaled by a factor, i.e. \(C = \alpha \cdot A^H B\) or \(C = C + \alpha \cdot A^H B\).
Parameters
C
alpha
B
adding
Definition at line 6362 of file lapack_full_matrix_ext.h.
hstack()
template<typename Number > void LAPACKFullMatrixExt< Number >::hstack (LAPACKFullMatrixExt< Number > & C, const LAPACKFullMatrixExt< Number > & B) const
Horizontally stack two matrices, \(C = [A, B]\).
Parameters
C
B
Definition at line 4660 of file lapack_full_matrix_ext.h.
Referenced by RkMatrix< Number >::add(), and LAPACKFullMatrixExt< Number >::LAPACKFullMatrixExt().
Hvmult()
template<typename Number > void LAPACKFullMatrixExt< Number >::Hvmult (Vector< Number > & w, const Vector< Number > & v, const bool adding = false) const
Hermite transposed matrix-vector multiplication.
Parameters
w
v
adding
Definition at line 5376 of file lapack_full_matrix_ext.h.
IdentityMatrix()
template<typename Number > void LAPACKFullMatrixExt< Number >::IdentityMatrix (const size_type dim, LAPACKFullMatrixExt< Number > & matrix) static
Create an identity matrix of dimension dim.
Parameters
dim
matrix
Definition at line 1610 of file lapack_full_matrix_ext.h.
invert()
template<typename Number > void LAPACKFullMatrixExt< Number >::invert (const LAPACKFullMatrixExt< Number > & M)
Assign the inverse of the given matrix to *this.
Parameters
M
Definition at line 6541 of file lapack_full_matrix_ext.h.
Referenced by BEMTools::surface_covariant_transformation().
invert_by_gauss_elim()
template<typename Number > void LAPACKFullMatrixExt< Number >::invert_by_gauss_elim (LAPACKFullMatrixExt< Number > & M_inv)
Calculate the inverse of the matrix using Gauss elimination.
Parameters
M_inv
Eliminate the lower triangular part of the matrix.
Scale the current row by the factor \(\frac{1}{a_{ll}}\) and this value is directly filled into the result matrix.
For the matrix \(M\), after this scaling, the element \(M_{ll}\) will become 1, there is no need to compute the scaling of this element. Meanwhile, the elements \(M_{l1}, \cdots, M_{l,l-1}\) are already zeros after previous eliminations, neither need we compute the scaling of these elements. Therefore, the actual computation to be performed is for columns \(j = l + 1, \cdots, n\).
For the matrix \(M^{-1}\), after this scaling, the element at \((l, l)\) will be \(\frac{1}{M_{ll}}\), so there is no need to compute this scaling. Meanwhile, only those elements \(M^{-1}_{l,1}, \cdots, M^{-1}_{l-1}\) may be non-zeros, we only loop over \(j = 1, \cdots, l - 1\).
Then we eliminate the elements \(M_{l+1,l}, \cdots, M_{n,l}\) by iterating over the rows \(l + 1, \cdots, n\).
This transformation will only influence the columns \(1, \cdots, l\) in \(M^{-1}\).
This transformation will only influence the columns \(l+1, \cdots, n\) in \(M\).
Eliminate the upper triangular part. Now the row transformation is only related to the result matrix \(M^{-1}\).
Eliminate the elements \(M_{l-1,l}, \cdots, M_{1,l}\).
N.B. When the loop counter i of unsigned type decreased to be zero, further decrement will not produce a value smaller than zero but a very large integer. Hence, we do not use a typical for loop here as below.
for (size_type i = l - 1; i >= 0; i–) { ... }
Instead, we use a while loop with the true condition. Inside this loop, when we detect the counter is zero after loop execution, we jump out the loop.
Because the elements in the current l'th row of \(M^{-1}\) are generally non-zeros, the computation involves columns \(1, \cdots, n\).
Definition at line 6553 of file lapack_full_matrix_ext.h.
keep_first_n_columns()
template<typename Number > void LAPACKFullMatrixExt< Number >::keep_first_n_columns (const size_type n, bool other_columns_removed = true)
Keep only the first n columns of the matrix.
When other_columns_removed is true, the other columns are deleted from the matrix, otherwise they are set to zero.
Parameters
n
other_rows_removed
Definition at line 3209 of file lapack_full_matrix_ext.h.
keep_first_n_rows()
template<typename Number > void LAPACKFullMatrixExt< Number >::keep_first_n_rows (const size_type n, bool other_rows_removed = true)
Keep only the first n rows of the matrix.
When other_rows_removed is true, the other rows are deleted from the matrix, otherwise they are set to zero.
Parameters
n
other_rows_removed
Definition at line 3061 of file lapack_full_matrix_ext.h.
l1_norm()
template<typename Number > numbers::NumberTraits< Number >::real_type LAPACKFullMatrixExt< Number >::l1_norm
Definition at line 4457 of file lapack_full_matrix_ext.h.
linfty_norm()
template<typename Number > numbers::NumberTraits< Number >::real_type LAPACKFullMatrixExt< Number >::linfty_norm
Definition at line 4466 of file lapack_full_matrix_ext.h.
lower_triangular()
template<typename Number > void LAPACKFullMatrixExt< Number >::lower_triangular (LAPACKFullMatrixExt< Number > & tril)
Get the lower triangular part of the matrix, including the diagonal.
Definition at line 2880 of file lapack_full_matrix_ext.h.
memory_consumption()
template<typename Number > std::size_t LAPACKFullMatrixExt< Number >::memory_consumption
Determine an estimate for the memory consumption (in bytes) of this object.
Returns
Definition at line 6998 of file lapack_full_matrix_ext.h.
mHmult() [1/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::mHmult (LAPACKFullMatrixExt< Number > & C, const LAPACKFullMatrixExt< Number > & B, bool adding = false) const
Multiply two matrices with the second operand Hermite transposed, i.e. \(C = AB^H\) or \(C = C + AB^H\).
Parameters
C
B
adding
Definition at line 5971 of file lapack_full_matrix_ext.h.
mHmult() [2/2]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::mHmult (LAPACKFullMatrixExt< Number > & C, const Number2 alpha, const LAPACKFullMatrixExt< Number > & B, bool adding = false) const
Multiply two matrices with the second operand Hermite transposed and with the product scaled by a factor, i.e. \(C = \alpha \cdot AB^H\) or \(C = C + \alpha \cdot AB^H\).
Parameters
C
alpha
B
adding
Definition at line 6100 of file lapack_full_matrix_ext.h.
mmult() [1/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::mmult (LAPACKFullMatrixExt< Number > & C, const LAPACKFullMatrixExt< Number > & B, const bool adding = false) const
Multiply two matrices, i.e. \(C = AB\) or \(C = C + AB\).
Parameters
C
B
adding
Definition at line 5490 of file lapack_full_matrix_ext.h.
Referenced by BEMTools::surface_covariant_transformation(), BEMTools::surface_jacobian_det(), and BEMTools::surface_jacobian_det_and_normal_vector().
mmult() [2/2]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::mmult (LAPACKFullMatrixExt< Number > & C, const Number2 alpha, const LAPACKFullMatrixExt< Number > & B, const bool adding = false) const
Multiply two matrices with the product scaled by a factor, i.e. \(C = \alpha \cdot AB\) or \(C = C + \alpha \cdot AB\).
Parameters
C
alpha
B
adding
Make a local copy of the matrix B and scale it.
Definition at line 5513 of file lapack_full_matrix_ext.h.
mTmult() [1/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::mTmult (LAPACKFullMatrixExt< Number > & C, const LAPACKFullMatrixExt< Number > & B, bool adding = false) const
Multiply two matrices with the second operand transposed, i.e. \(C = AB^T\) or \(C = C + AB^T\).
Parameters
C
B
adding
Definition at line 5545 of file lapack_full_matrix_ext.h.
Referenced by HMatrix< spacedim, Number >::addsym_diag().
mTmult() [2/2]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::mTmult (LAPACKFullMatrixExt< Number > & C, const Number2 alpha, const LAPACKFullMatrixExt< Number > & B, bool adding = false) const
Multiply two matrices with the second operand transposed and with the product scaled by a factor, i.e. \(C = \alpha \cdot AB^T\) or \(C = C + \alpha \cdot AB^T\).
Parameters
C
alpha
B
adding
Definition at line 5651 of file lapack_full_matrix_ext.h.
norm()
template<typename Number > numbers::NumberTraits< Number >::real_type LAPACKFullMatrixExt< Number >::norm (const char type) const
Definition at line 4423 of file lapack_full_matrix_ext.h.
operator*=()
template<typename Number > template<typename Number2 > LAPACKFullMatrixExt< Number > & LAPACKFullMatrixExt< Number >::operator*= (const Number2 factor)
Definition at line 2724 of file lapack_full_matrix_ext.h.
operator/=()
template<typename Number > template<typename Number2 > LAPACKFullMatrixExt< Number > & LAPACKFullMatrixExt< Number >::operator/= (const Number2 factor)
Definition at line 2801 of file lapack_full_matrix_ext.h.
operator=() [1/3]
template<typename Number > LAPACKFullMatrixExt< Number > & LAPACKFullMatrixExt< Number >::operator= (const LAPACKFullMatrix< Number > & matrix)
Overloaded assignment operator.
Parameters
matrix
Returns
Because state and property are private members of LAPACKFullMatrix<Number>, they cannot be copied from the given matrix. Hence, they are assigned with the default values LAPACKSupport::matrix and LAPACKSupport::general.
Definition at line 2692 of file lapack_full_matrix_ext.h.
operator=() [2/3]
template<typename Number > LAPACKFullMatrixExt< Number > & LAPACKFullMatrixExt< Number >::operator= (const LAPACKFullMatrixExt< Number > & matrix)
Overloaded assignment operator.
Parameters
matrix
Returns
Since ipiv contains the crucial permutation data if the matrix has been factorized by LU, it needs to be copied.
Definition at line 2674 of file lapack_full_matrix_ext.h.
operator=() [3/3]
template<typename Number > LAPACKFullMatrixExt< Number > & LAPACKFullMatrixExt< Number >::operator= (const Number d)
Assign a scalar value to all elements of the matrix.
Parameters
a
Returns
Definition at line 2711 of file lapack_full_matrix_ext.h.
outer_product()
template<typename Number > void LAPACKFullMatrixExt< Number >::outer_product (const Vector< Number > & v, const Vector< Number > & w)
Compute the outer product of the two vectors and store the results into the current matrix.
In the complex valued case, complex conjugation is applied to w.
Parameters
v
w
Definition at line 5069 of file lapack_full_matrix_ext.h.
outer_product_formal()
template<typename Number > void LAPACKFullMatrixExt< Number >::outer_product_formal (const Vector< Number > & v, const Vector< Number > & w)
Compute the formal outer product of the two vectors and store the results into the current matrix.
In the complex valued case, this outer product is formal and there is no complex conjugation applied to w.
Parameters
v
w
Definition at line 5050 of file lapack_full_matrix_ext.h.
precondition_Jacobi()
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::precondition_Jacobi (Vector< Number2 > & dst, const Vector< Number2 > & src, const real_type omega = 1.) const
This function is required by the class PreconditionJacobi<LAPACKFullMatrix<Number>> when the matrix is solved with a Jacobi preconditioner.
Because the matrix is full and will not be solved in an actual case, this is only for verification purpose.
Definition at line 6495 of file lapack_full_matrix_ext.h.
print_formatted_to_mat()
template<typename Number > void LAPACKFullMatrixExt< Number >::print_formatted_to_mat (std::ostream & out, const std::string & name, const unsigned int precision = 8, const bool scientific = true, const unsigned int width = 0, const char * zero_string = "0", const double denominator = 1., const double threshold = 0.) const
Print a LAPACKFullMatrixExt to Octave mat format.
Parameters
out
name
precision
scientific
width
zero_string
denominator
threshold
Definition at line 6887 of file lapack_full_matrix_ext.h.
Referenced by HMatrix< spacedim, Number >::print_as_formatted_full_matrix().
qr()
template<typename Number > void LAPACKFullMatrixExt< Number >::qr (LAPACKFullMatrixExt< Number > & Q, LAPACKFullMatrixExt< Number > & R)
Perform QR decomposition of the matrix. The current matrix belongs to \(\mathbb{K}^{m\times n}\)
Parameters
Q It belongs to \(\mathbb{K}^{m\times m}\).
R It belongs to \(\mathbb{K}^{m\times n}\).
Set work space size as 1 and lwork as -1 for the determination of optimal work space size.
Make sure that the first entry in the work space is clear, in case the routine does not completely overwrite the memory:
Resize the work space and add one to the size computed by LAPACK to be on the safe side.
Perform the actual QR decomposition.
Collect results for the upper triangular matrix R.
Collect results for the orthogonal matrix Q with a dimension \(m \times m\). It is represented as a product of elementary reflectors (Householder transformation) as
\[ Q = H_1 H_2 \cdots H_k, \]
where \(k = \min\{m, n\}\).
Construct the vector v. Values in v before the i'th component are all zeros. The i'th component is 1. Values after the i'th component are stored in the current matrix A(i+1:m,i).
Construct the Householder matrix.
Release the work space used.
Definition at line 3938 of file lapack_full_matrix_ext.h.
rank()
template<typename Number > LAPACKFullMatrixExt< Number >::size_type LAPACKFullMatrixExt< Number >::rank (real_type threshold = 0.) const
Get the rank of the matrix using SVD.
A copy will be made at first for SVD to operate on.
Parameters
threshold threshold for singular values. The number of singular values larger than this threshold is the matrix rank.
Returns
If the singular value threshold is perfect zero, calculate a threshold value instead.
Definition at line 3896 of file lapack_full_matrix_ext.h.
rank_k_decompose() [1/5]
template<typename Number > LAPACKFullMatrixExt< Number >::size_type LAPACKFullMatrixExt< Number >::rank_k_decompose (const unsigned int k, LAPACKFullMatrixExt< Number > & A, LAPACKFullMatrixExt< Number > & B)
Decompose the full matrix into the two components of its rank-k representation, the associativity of triple-matrix multiplication is automatically detected.
Note
This method will be used for converting a full matrix to a rank-k matrix, which underlies the operator \(\mathcal{T}_{r}^{\mathcal{R} \leftarrow \mathcal{F}}\) in (7.2) in Hackbusch's \(\mathcal{H}\)-matrix book.
Parameters
k
A
B
Returns
When the matrix is long, apply right associativity.
When the matrix is wide, apply left associativity.
Definition at line 4694 of file lapack_full_matrix_ext.h.
rank_k_decompose() [2/5]
template<typename Number > LAPACKFullMatrixExt< Number >::size_type LAPACKFullMatrixExt< Number >::rank_k_decompose (const unsigned int k, LAPACKFullMatrixExt< Number > & A, LAPACKFullMatrixExt< Number > & B, bool is_left_associative)
Decompose the full matrix into the two components of its rank-k representation.
Note
Because the reduced_svd member function is called by rank_k_decompose, the effective rank of the matrix will be returned, which can be smaller than the specified fixed rank k.
Parameters
k User specified truncation rank.
is_left_associative
A
B
Returns
Effective rank.
Perform RSVD for the matrix and return U and V^H into A and B respectively. N.B. After running this function, B actually holds the transpose or Hermite transpose of itself at the moment.
Let A = A*Sigma_r and B = B^H.
Let A = A and B = (Sigma_r * B)^H.
Definition at line 4763 of file lapack_full_matrix_ext.h.
rank_k_decompose() [3/5]
template<typename Number > LAPACKFullMatrixExt< Number >::size_type LAPACKFullMatrixExt< Number >::rank_k_decompose (const unsigned int k, LAPACKFullMatrixExt< Number > & A, LAPACKFullMatrixExt< Number > & B, LAPACKFullMatrixExt< Number > & C, LAPACKFullMatrixExt< Number > & D)
Decompose the full matrix into the two components of its rank-k representation, the associativity of triple-matrix multiplication is automatically detected. The error matrices are returned.
Note
This method will be used for converting a full matrix to a rank-k matrix, which underlies the operator \(\mathcal{T}_{r}^{\mathcal{R} \leftarrow \mathcal{F}}\) in (7.2) in Hackbusch's \(\mathcal{H}\)-matrix book.
Parameters
k
A
B
C
D
Returns
When the matrix is long, apply right associativity.
When the matrix is wide, apply left associativity.
Definition at line 4717 of file lapack_full_matrix_ext.h.
rank_k_decompose() [4/5]
template<typename Number > LAPACKFullMatrixExt< Number >::size_type LAPACKFullMatrixExt< Number >::rank_k_decompose (const unsigned int k, LAPACKFullMatrixExt< Number > & A, LAPACKFullMatrixExt< Number > & B, LAPACKFullMatrixExt< Number > & C, LAPACKFullMatrixExt< Number > & D, bool is_left_associative)
Decompose the full matrix into the two components of its rank-k representation, while the error matrices are returned.
Note
Because the reduced_svd member function is called by rank_k_decompose, the effective rank of the matrix will be returned, which can be smaller than the specified fixed rank k.
Parameters
k User specified truncation rank.
is_left_associative
A
B
C
D
Returns
Effective rank.
Perform RSVD for the matrix and return U and V^H into A and B respectively. N.B. After running this function, B actually holds the transpose or Hermite transpose of itself at the moment.
Let A = A*Sigma_r and B = B^H.
Let A = A and B = (Sigma_r * B)^H.
Definition at line 4803 of file lapack_full_matrix_ext.h.
rank_k_decompose() [5/5]
template<typename Number > LAPACKFullMatrixExt< Number >::size_type LAPACKFullMatrixExt< Number >::rank_k_decompose (LAPACKFullMatrixExt< Number > & A, LAPACKFullMatrixExt< Number > & B)
Decompose the full matrix into the two components of its rank-k representation, the associativity of triple-matrix multiplication is automatically detected. This version does not have an actual rank truncation but sets the truncation rank to be the minimum matrix dimension \(\min\{m, n\}\).
Note
This method will be used for converting a full matrix to a rank-k matrix, which implements the operator \(\mathcal{T}_{r}^{\mathcal{R} \leftarrow \mathcal{F}}\) in (7.2) in Hackbusch's \(\mathcal{H}\)-matrix book.
Parameters
A
B
Returns
Effective rank of the matrix.
Use the minimum matrix dimension as the default truncation rank.
Definition at line 4742 of file lapack_full_matrix_ext.h.
read_from_mat()
template<typename Number > void LAPACKFullMatrixExt< Number >::read_from_mat (std::ifstream & in, const std::string & name)
Read the data of a full matrix with the specified variable name from a file saved by Octave using the option -text.
Parameters
in Input file stream
name Variable name
Iterate over each line of the file to search the desired variable.
When the desired variable is found, read the next line to check the data type is matrix.
Read a new line to extract the number of rows.
Read a new line to extract the number of columns.
Get each row of the matrix.
Get each matrix element in a row.
After reading all matrix data, exit from the loop.
Definition at line 6914 of file lapack_full_matrix_ext.h.
reduced_qr()
template<typename Number > void LAPACKFullMatrixExt< Number >::reduced_qr (LAPACKFullMatrixExt< Number > & Q, LAPACKFullMatrixExt< Number > & R)
Perform reduced QR decomposition of the matrix. The number of rows m of the current matrix should be larger than the number of columns n.
Parameters
Q It belongs to \(\mathbb{K}^{m\times n}\).
R It belongs to \(\mathbb{K}^{n\times n}\).
Set work space size as 1 and lwork as -1 for the determination of optimal work space size.
Make sure that the first entry in the work space is clear, in case the routine does not completely overwrite the memory:
Resize the work space and add one to the size computed by LAPACK to be on the safe side.
Perform the actual QR decomposition.
Collect results for the square upper triangular matrix R'.
Collect results for the orthogonal matrix Q with a dimension \(m \times m\). It is represented as a product of elementary reflectors (Householder transformation) as
\[ Q = H_1 H_2 \cdots H_k, \]
where \(k = \min\{m, n\}\).
Construct the vector v. Values in v before the i'th component are all zeros. The i'th component is 1. Values after the i'th component are stored in the current matrix A(i+1:m,i).
Construct the Householder matrix.
Release the work space used.
Keep the first nn columns of Q.
Definition at line 4050 of file lapack_full_matrix_ext.h.
reduced_svd() [1/2]
template<typename Number > LAPACKFullMatrixExt< Number >::size_type LAPACKFullMatrixExt< Number >::reduced_svd (LAPACKFullMatrixExt< Number > & U, std::vector< real_type > & Sigma_r, LAPACKFullMatrixExt< Number > & VT, LAPACKFullMatrixExt< Number > & C, LAPACKFullMatrixExt< Number > & D, size_type truncation_rank, real_type singular_value_threshold = 0.)
Perform the reduced singular value decomposition (SVD) with rank truncation. In addition, the components \(C\) and \(D\) of the error matrix due to rank truncation are returned. The error matrix \(E = CD^T\).
References
Bebendorf, Mario. 2008. Hierarchical Matrices: A Means to Efficiently Solve Elliptic Boundary Value Problems. Lecture Notes in Computational Science and Engineering 63. Berlin, Heidelberg: Springer, Section 2.5.1, p66-69.
Note
Even though an explicit truncation rank is specified, inside this function, after SVD, the effective rank of the matrix is obtained. Because any given truncation rank value larger than the effective matrix rank is meaningless, it will be limited to be the effective rank.
Parameters
U
Sigma_r
VT
C
D
truncation_rank Truncation rank specified by the user.
singular_value_threshold
Returns
Effective rank.
Work flow
Perform the full SVD.
If the singular value threshold is perfect zero, calculate a threshold value instead.
Get the actual rank of the matrix by counting the total number of singular values which are larger than the given threshold singular_value_threshold. The actual rank should always be less than or equal to min_dim.
Limit the value of truncation_rank not larger than the actual rank just obtained by counting effective singular values.
Perform singular value truncation when the given truncation_rank (after value limiting wrt. the actual rank) is less than the minimum matrix dimension. The procedures are as below.
Keep the first truncation_rank singular values, while discarding the others.
Copy the remaining singular values for constructing the error matrices.
Allocate memory for the error matrices. At the moment, \(D\) stores the transpose (real valued case) or Hermite transpose (complex valued case) version for itself.
When the original full matrix \(AB^T\) is a long matrix, so is the error matrix. Then we perform the right association, i.e. \(C(\Sigma_{r,\epsilon}D^{\mathrm{T}})\) or \(C(\Sigma_{r,\epsilon}D^{\mathrm{H}})\).
When the original full matrix \(AB^T\) is a wide matrix, so is the error matrix. Then we perform the left association, i.e. \((C\Sigma_{r,\epsilon})D^{\mathrm{T}}\) or \((C\Sigma_{r,\epsilon})D^{\mathrm{H}}\)
Balance the Frobenius norm of C and D.
Keep the first truncation_rank columns of U, while discarding the others.
Keep the first truncation_rank rows of VT, while discarding the others.
When the truncation rank is zero, the error matrices should be directly obtained from the SVD results.
When the original full matrix \(AB^T\) is a long matrix, perform right association.
When the original full matrix \(AB^T\) is a wide matrix, perform left association.
Balance the Frobenius norm of C and D.
Then, clear the SVD result matrix and singular value vector.
When truncation_rank (after value limiting wrt. the actual rank) is equal to the minimum matrix dimension, we only need to adjust the columns of \(U\) or the rows of \(V^T\) depending on the shape of the matrix \(M\).
There is no effective rank truncation and thus no accuracy loss. Therefore, the error matrix components \(C\) and \(D\) are set to zero dimension.
For details, if \(M\) has a dimension \(m \times n\), the dimensions of all matrices obtained from SVD are:
\(U \in \mathbb{R}^{m \times m}\)
\(\Sigma_r \in \mathbb{R}^{m \times n}\)
\(V \in \mathbb{R}^{n \times n}\)
When \(M\) is long, \(\Sigma_r = \begin{pmatrix}\Sigma_r' \\ 0 \end{pmatrix}\). Therefore, we keep the first min_dim columns of \(U\), while deleting others. \(V^T\) is kept intact.
When \(M\) is wide, \(\Sigma_r = \begin{pmatrix} \Sigma_r' & 0 \end{pmatrix}\). Therefore, we keep the first min_dim rows of \(V^T\), while deleting others. \(U\) is kept intact.
When \(M\) is square, do nothing.
Return the value of truncation_rank. Instead of its original specified value, it now contains the actual rank of the matrix after truncation.
Definition at line 3574 of file lapack_full_matrix_ext.h.
reduced_svd() [2/2]
template<typename Number > LAPACKFullMatrixExt< Number >::size_type LAPACKFullMatrixExt< Number >::reduced_svd (LAPACKFullMatrixExt< Number > & U, std::vector< real_type > & Sigma_r, LAPACKFullMatrixExt< Number > & VT, size_type truncation_rank, real_type singular_value_threshold = 0.)
Perform the reduced singular value decomposition (SVD) with rank truncation.
Note
Even though an explicit truncation rank is specified, inside this function, after SVD, the effective rank of the matrix is obtained. Because any given truncation rank value larger than the effective matrix rank is meaningless, it will be limited to be the effective rank.
Parameters
U
Sigma_r
VT
truncation_rank Truncation rank specified by the user.
singular_value_threshold
Returns
Effective rank.
Work flow
Perform the full SVD.
If the singular value threshold is perfectly zero, calculate a threshold value instead.
Get the actual rank of the matrix by counting the total number of singular values which are larger than the given threshold singular_value_threshold. The actual rank should always be less than or equal to min_dim.
Limit the value of truncation_rank not larger than the actual rank just obtained by counting effective singular values.
Perform singular value truncation when the given truncation_rank (after value limiting wrt. the actual rank) is less than the minimum matrix dimension. The procedures are as below.
Keep the first truncation_rank singular values, while discarding the others.
Keep the first truncation_rank columns of U, while discarding the others.
Keep the first truncation_rank rows of VT, while discarding the others.
Clear the SVD result matrix and singular value vector.
When truncation_rank (after value limiting wrt. the actual rank) is equal to the minimum matrix dimension, we only need to adjust the columns of \(U\) or the rows of \(V^T\) depending on the shape of the matrix \(M\).
For details, if \(M\) has a dimension \(m \times n\), the dimensions of all matrices obtained from SVD are:
\(U \in \mathbb{R}^{m \times m}\)
\(\Sigma_r \in \mathbb{R}^{m \times n}\)
\(V \in \mathbb{R}^{n \times n}\)
When \(M\) is long, \(\Sigma_r = \begin{pmatrix}\Sigma_r' \\ 0 \end{pmatrix}\). Therefore, we keep the first min_dim columns of \(U\), while deleting others. \(V^T\) is kept intact.
When \(M\) is wide, \(\Sigma_r = \begin{pmatrix} \Sigma_r' & 0 \end{pmatrix}\). Therefore, we keep the first min_dim rows of \(V^T\), while deleting others. \(U\) is kept intact.
When \(M\) is square, do nothing.
Return the value of truncation_rank. Instead of its original specified value, it now contains the actual rank of the matrix after truncation.
Definition at line 3415 of file lapack_full_matrix_ext.h.
reduced_svd_on_AxBH() [1/3]
template<typename Number > static size_type LAPACKFullMatrixExt< Number >::reduced_svd_on_AxBH (LAPACKFullMatrixExt< Number > & A, LAPACKFullMatrixExt< Number > & B, LAPACKFullMatrixExt< Number > & U, std::vector< typename numbers::NumberTraits< Number >::real_type > & Sigma_r, LAPACKFullMatrixExt< Number > & VT, LAPACKFullMatrixExt< Number > & C, LAPACKFullMatrixExt< Number > & D, size_type truncation_rank, typename numbers::NumberTraits< Number >::real_type singular_value_threshold = 0.) static
Perform SVD on the product of two component matrices \(A\) and \(B^T\) with truncation by a specified rank. In addition, the components \(C\) and \(D\) of the error matrix due to rank truncation are returned. The error matrix \(E = CD^T\).
The operation of this function may have accuracy loss when the specified rank is less than the actual rank of the matrix.
N.B. If the actual rank of the matrix is less than the specified truncation_rank, i.e. rank deficient, the matrix will be truncated to its actual rank. Then, this function has no accuracy loss.
Parameters
A
B
U
Sigma_r
VT
C
D
truncation_rank
reduced_svd_on_AxBH() [2/3]
template<typename Number > static size_type LAPACKFullMatrixExt< Number >::reduced_svd_on_AxBH (LAPACKFullMatrixExt< Number > & A, LAPACKFullMatrixExt< Number > & B, LAPACKFullMatrixExt< Number > & U, std::vector< typename numbers::NumberTraits< Number >::real_type > & Sigma_r, LAPACKFullMatrixExt< Number > & VT, size_type truncation_rank, typename numbers::NumberTraits< Number >::real_type singular_value_threshold = 0.) static
Perform SVD on the product of two component matrices \(A\) and \(B^T\) with truncation by a specified rank.
The operation of this function may have accuracy loss when the specified rank is less than the actual rank of the matrix.
N.B. If the actual rank of the matrix is less than the specified truncation_rank, i.e. rank deficient, the matrix will be truncated to its actual rank. Then, this function has no accuracy loss.
Parameters
A
B
U
Sigma_r
VT
truncation_rank
reduced_svd_on_AxBH() [3/3]
template<typename Number > static size_type LAPACKFullMatrixExt< Number >::reduced_svd_on_AxBH (LAPACKFullMatrixExt< Number > & A, LAPACKFullMatrixExt< Number > & B, LAPACKFullMatrixExt< Number > & U, std::vector< typename numbers::NumberTraits< Number >::real_type > & Sigma_r, LAPACKFullMatrixExt< Number > & VT, typename numbers::NumberTraits< Number >::real_type singular_value_threshold = 0.) static
Perform SVD on the product of two component matrices \(A\) and \(B^T\) (or \(B^H\) in the complex valued case) without rank truncation. If the matrix is not of full rank, truncate it to the effective rank. It returns the effective rank.
The operation of this function has no accuracy loss.
Parameters
A
B
U
Sigma_r
VT
Referenced by RkMatrix< Number >::truncate_to_rank().
remove_column()
template<typename Number > void LAPACKFullMatrixExt< Number >::remove_column (const size_type column_index)
Remove column column_index from the matrix.
Parameters
column_index
Definition at line 3122 of file lapack_full_matrix_ext.h.
remove_columns()
template<typename Number > void LAPACKFullMatrixExt< Number >::remove_columns (const std::vector< size_type > & column_indices)
Remove columns column_indices from the matrix.
Parameters
column_indices
Definition at line 3154 of file lapack_full_matrix_ext.h.
remove_row()
template<typename Number > void LAPACKFullMatrixExt< Number >::remove_row (const size_type row_index)
Remove row row_index from the matrix.
Parameters
row_index
Definition at line 2975 of file lapack_full_matrix_ext.h.
remove_rows()
template<typename Number > void LAPACKFullMatrixExt< Number >::remove_rows (const std::vector< size_type > & row_indices)
Remove rows row_indices from the matrix.
Parameters
row_indices
Definition at line 3006 of file lapack_full_matrix_ext.h.
Reshape() [1/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::Reshape (const size_type rows, const size_type cols, const Number * values, LAPACKFullMatrixExt< Number > & matrix) static
Reshape an array of values into a LAPACKFullMatrixExt in column major.
Definition at line 1645 of file lapack_full_matrix_ext.h.
Reshape() [2/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::Reshape (const size_type rows, const size_type cols, const std::vector< Number > & values, LAPACKFullMatrixExt< Number > & matrix) static
Reshape a vector of values into a LAPACKFullMatrixExt in column major.
Definition at line 1624 of file lapack_full_matrix_ext.h.
scale_columns() [1/3]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::scale_columns (const std::vector< Number2 > & V)
Right multiply the current matrix with a diagonal matrix V, which is equivalent to scale the columns of the current matrix with the corresponding scalar elements in V. The scaling factors are stored in a std::vector .
Parameters
V
Definition at line 4242 of file lapack_full_matrix_ext.h.
scale_columns() [2/3]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::scale_columns (const Vector< Number2 > & V)
Right multiply the current matrix with a diagonal matrix V, which is equivalent to scale the columns of the current matrix with the corresponding scalar elements in V. The scaling factors are stored in a dealii::Vector .
Parameters
V
Definition at line 4290 of file lapack_full_matrix_ext.h.
scale_columns() [3/3]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::scale_columns (LAPACKFullMatrixExt< Number > & A, const std::vector< Number2 > & V) const
Right multiply the current matrix with a diagonal matrix V, which is equivalent to scale the columns of the current matrix with the corresponding scalar elements in V. The scaling factors are stored in a std::vector . The result is stored in a new matrix A.
Parameters
A
V
Definition at line 4266 of file lapack_full_matrix_ext.h.
scale_rows() [1/3]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::scale_rows (const std::vector< Number2 > & V)
Left multiply the current matrix with a diagonal matrix V, which is equivalent to scale the rows of the current matrix with the corresponding scalar elements in V. The scaling factors are stored in a std::vector .
Parameters
V
Definition at line 4170 of file lapack_full_matrix_ext.h.
scale_rows() [2/3]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::scale_rows (const Vector< Number2 > & V)
Left multiply the current matrix with a diagonal matrix V, which is equivalent to scale the rows of the current matrix with the corresponding scalar elements in V. The scaling factors are stored in a dealii::Vector .
Parameters
V
Definition at line 4218 of file lapack_full_matrix_ext.h.
scale_rows() [3/3]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::scale_rows (LAPACKFullMatrixExt< Number > & A, const std::vector< Number2 > & V) const
Left multiply the current matrix with a diagonal matrix V, which is equivalent to scale the rows of the current matrix with the corresponding scalar elements in V. The scaling factors are stored in a std::vector . The result is stored in a new matrix A.
Parameters
A
V
Definition at line 4194 of file lapack_full_matrix_ext.h.
set_column_zeros()
template<typename Number > void LAPACKFullMatrixExt< Number >::set_column_zeros (const size_type col_index)
Set a matrix column as zeros.
Definition at line 2908 of file lapack_full_matrix_ext.h.
set_property()
template<typename Number > void LAPACKFullMatrixExt< Number >::set_property (const LAPACKSupport::Property property)
Set the matrix property of type LAPACKSupport::Property for the matrix.
Comment
The property should be explicitly set by the caller and the algorithm will not check its validity, since in most cases, this is difficult or expensive to achieve.
Parameters
property
Definition at line 6679 of file lapack_full_matrix_ext.h.
Referenced by HMatrix< spacedim, Number >::set_property_for_converted_fullmatrix().
set_row_zeros()
template<typename Number > void LAPACKFullMatrixExt< Number >::set_row_zeros (const size_type row_index)
Set a matrix row as zeros.
Definition at line 2924 of file lapack_full_matrix_ext.h.
set_state()
template<typename Number > void LAPACKFullMatrixExt< Number >::set_state (const LAPACKSupport::State state)
Set the matrix state.
Parameters
state
N.B. There is no public or protected member function provided by LAPACKFullMatrix for setting its matrix state. Hence, unlike in the member function set_property, we do nothing here to the parent class.
Definition at line 6689 of file lapack_full_matrix_ext.h.
solve()
template<typename Number > void LAPACKFullMatrixExt< Number >::solve (Vector< Number > & v, const bool transposed = false) const
Solve the linear system with right hand side v and put the solution back to v. The matrix should be either triangular or LU/Cholesky factorization should be previously computed.
The flag transposed indicates whether the solution of the transposed system is to be performed.
Note
This function is copied from lapack_full_matrix.cc, so that the matrix state held by LAPACKFullMatrixExt can be accessed.
Parameters
v
transposed
Definition at line 6717 of file lapack_full_matrix_ext.h.
solve_by_backward_substitution() [1/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::solve_by_backward_substitution (Vector< Number > & b, const bool transposed = false, const bool is_unit_diagonal = false) const
Solve the upper triangular matrix \(Ux=b\) by backward substitution.
The right hand side vector \(b\) will be overwritten by the solution vector \(x\).
Parameters
b Right hand side vector and after execution, it stores the result vector.
transposed
The member variable values of b is private, which cannot be directly accessed. Therefore, the function trsv_helper is designed to accept the data pointer of b, which can be obtained via b.data().
Also note when in the complex valued case, if the transposed matrix is to be solved, we only allow transpose not Hermite transpose at the moment.
Definition at line 6835 of file lapack_full_matrix_ext.h.
solve_by_backward_substitution() [2/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::solve_by_backward_substitution (Vector< Number > & x, const Vector< Number > & b, const bool transposed = false, const bool is_unit_diagonal = false) const
Solve the upper triangular matrix \(Ux=b\) by backward substitution.
Parameters
x Result vector.
b Right hand side vector.
transposed
Definition at line 6874 of file lapack_full_matrix_ext.h.
solve_by_forward_substitution() [1/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::solve_by_forward_substitution (Vector< Number > & b, const bool transposed = false, const bool is_unit_diagonal = true, const bool permute_rhs_vector = false) const
Solve the unit lower triangular matrix \(Lx=b\) by forward substitution.
The right hand side vector \(b\) will be overwritten by the solution vector \(x\).
Comment
When the forward substitution procedure is applied to the matrix factorized by LU, the right hand side vector b should be permuted according to the ipiv vector, which is obtained from the LAPACK LU factorization with row pivoting. Remember that we have this relation \(PA=LU\).
However, when the lower triangular matrix to be solved is the transpose of an upper triangular matrix, there is no need to permute the right hand side vector b anymore, because permutation has been or will be performed during the solution of matrix blocks related to the lower triangulation matrix. For short, the permutation of the right hand side vector should only be performed once.
By the way, no permutation is needed when calling backward substitution or solving Cholesky related matrices.
Parameters
b Right hand side vector and after execution, it stores the result vector.
transposed
permute_rhs_vector
Permute RHS vector if the current matrix is obtained from LU factorization.
The member variable values of b is private, which cannot be directly accessed. Therefore, the function trsv_helper is designed to accept the data pointer of b, which can be obtained via b.data().
Also note when in the complex valued case, if the transposed matrix is to be solved, we only allow transpose not Hermite transpose at the moment.
Definition at line 6768 of file lapack_full_matrix_ext.h.
solve_by_forward_substitution() [2/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::solve_by_forward_substitution (Vector< Number > & x, const Vector< Number > & b, const bool transposed = false, const bool is_unit_diagonal = true) const
Solve the unit lower triangular matrix \(Lx=b\) by forward substitution.
Parameters
x Result vector.
b Right hand side vector.
transposed
Definition at line 6822 of file lapack_full_matrix_ext.h.
svd() [1/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::svd (LAPACKFullMatrixExt< Number > & U, std::vector< real_type > & Sigma_r, LAPACKFullMatrixExt< Number > & VT)
Perform the standard singular value decomposition (SVD).
Parameters
U with a dimension \(m \times m\).
Sigma_r the list of singular values, with a dimension \(\min(m,n)\).
VT with a dimension \(n \times n\)
svd() [2/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::svd (LAPACKFullMatrixExt< Number > & U, std::vector< real_type > & Sigma_r, LAPACKFullMatrixExt< Number > & VT, const size_type truncation_rank)
Perform the standard singular value decomposition (SVD) with rank truncation.
When the given truncation_rank is less than the minimum dimension \(\min{m, n}\), U's (truncation_rank+1)'th to m'th columns are set to zeros; VT's (truncation_rank+1)'th to n'th rows are set to zeros; Sigma_r's (truncation_rank+1)'th to n'th values are set to zeros.
Parameters
U with a dimension \(m \times m\).
Sigma_r the list of singular values, which has a dimension \(\min(m,n)\).
VT with a dimension \(n \times n\).
Tmmult() [1/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::Tmmult (LAPACKFullMatrixExt< Number > & C, const LAPACKFullMatrixExt< Number > & B, bool adding = false) const
Multiply two matrices with the first operand transposed, i.e. \(C = A^T B\) or \(C = C + A^T B\).
Parameters
C
B
adding
Definition at line 5758 of file lapack_full_matrix_ext.h.
Referenced by BEMTools::surface_covariant_transformation().
Tmmult() [2/2]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::Tmmult (LAPACKFullMatrixExt< Number > & C, const Number2 alpha, const LAPACKFullMatrixExt< Number > & B, bool adding = false) const
Multiply two matrices with the first operand transposed and with the product scaled by a factor, i.e. \(C = \alpha \cdot A^T B\) or \(C = C + \alpha \cdot A^T B\).
Parameters
C
alpha
B
adding
Definition at line 5864 of file lapack_full_matrix_ext.h.
transpose() [1/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::transpose
Perform in-place transpose of the matrix. When in the complex valued case, we perform Hermite transpose, which is consistent with deal.ii LAPACKFullMatrix::transpose .
Definition at line 4376 of file lapack_full_matrix_ext.h.
transpose() [2/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::transpose (LAPACKFullMatrixExt< Number > & AT) const
Get the transpose of the current matrix into a new matrix AT. When in the complex valued case, we perform Hermite transpose, which is consistent with deal.ii LAPACKFullMatrix::transpose .
Parameters
AT
Definition at line 4404 of file lapack_full_matrix_ext.h.
Tvmult()
template<typename Number > void LAPACKFullMatrixExt< Number >::Tvmult (Vector< Number > & w, const Vector< Number > & v, const bool adding = false) const
Transposed matrix-vector multiplication.
Parameters
w
v
adding
Definition at line 5264 of file lapack_full_matrix_ext.h.
upper_triangular()
template<typename Number > void LAPACKFullMatrixExt< Number >::upper_triangular (LAPACKFullMatrixExt< Number > & triu)
Get the upper triangular part of the matrix, including the diagonal.
Definition at line 2894 of file lapack_full_matrix_ext.h.
vmult() [1/2]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::vmult (Vector< Number > & w, const Number2 alpha, const Vector< Number > & v, const bool adding = false) const
Matrix-vector multiplication which also handles the case when the matrix is symmetric and lower triangular.
When adding is true, this function computes w = w + alpha*A*v. Otherwise, it computes w = alpha*A*v.
Note
When the matrix is symmetric, the LAPACK function symv is adopted. In my implementation, only those lower triangular entries in a symmetric full matrix are used by symv.
At the moment, there is no counterpart Tvmult implemented which handles the case of symmetric matrix, because there is no difference between \(Av\) and \(A^T v\).
Parameters
w
v
adding
Definition at line 5089 of file lapack_full_matrix_ext.h.
Referenced by LAPACKFullMatrixExt< Number >::Cvmult().
vmult() [2/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::vmult (Vector< Number > & w, const Vector< Number > & v, const bool adding = false) const
Matrix-vector multiplication. When adding is true, this function computes w = w + A*v. Otherwise, it computes w = A*v.
Definition at line 5215 of file lapack_full_matrix_ext.h.
vmult_add() [1/2]
template<typename Number > template<typename Number2 > void LAPACKFullMatrixExt< Number >::vmult_add (Vector< Number > & w, const Number2 alpha, const Vector< Number > & v) const
Matrix-vector multiplication with adding and scaling, i.e. w = w + alpha*A*v.
Definition at line 5226 of file lapack_full_matrix_ext.h.
vmult_add() [2/2]
template<typename Number > void LAPACKFullMatrixExt< Number >::vmult_add (Vector< Number > & w, const Vector< Number > & v) const
Matrix-vector multiplication with adding and without scaling, i.e. w = w + A*v.
Definition at line 5236 of file lapack_full_matrix_ext.h.
vstack()
template<typename Number > void LAPACKFullMatrixExt< Number >::vstack (LAPACKFullMatrixExt< Number > & C, const LAPACKFullMatrixExt< Number > & B) const
Vertically stack two matrices, \(C = [A; B]\).
Parameters
C
B
Definition at line 4677 of file lapack_full_matrix_ext.h.
Referenced by LAPACKFullMatrixExt< Number >::LAPACKFullMatrixExt().
ZeroMatrix()
template<typename Number > void LAPACKFullMatrixExt< Number >::ZeroMatrix (const size_type rows, const size_type cols, LAPACKFullMatrixExt< Number > & matrix) static
Create a zero valued matrix.
Parameters
rows
cols
matrix
Definition at line 1566 of file lapack_full_matrix_ext.h.
Friends And Related Function Documentation
balance_frobenius_norm
template<typename Number > template<typename Number1 > void balance_frobenius_norm (LAPACKFullMatrixExt< Number1 > & A, LAPACKFullMatrixExt< Number1 > & B) friend
Balance the Frobenius norm of the two matrices.
Parameters
A
B
Member Data Documentation
ipiv
template<typename Number > std::vector<types::blas_int> LAPACKFullMatrixExt< Number >::ipiv private
The vector storing the permutations applied for pivoting in the LU-factorization.
Definition at line 1538 of file lapack_full_matrix_ext.h.
iwork
template<typename Number > std::vector<types::blas_int> LAPACKFullMatrixExt< Number >::iwork private
Integer work array used by LAPACK routines.
Definition at line 1532 of file lapack_full_matrix_ext.h.
mutex
template<typename Number > std::mutex LAPACKFullMatrixExt< Number >::mutex mutable private
Definition at line 1540 of file lapack_full_matrix_ext.h.
property
template<typename Number > LAPACKSupport::Property LAPACKFullMatrixExt< Number >::property private
Definition at line 1516 of file lapack_full_matrix_ext.h.
state
template<typename Number > LAPACKSupport::State LAPACKFullMatrixExt< Number >::state private
Definition at line 1515 of file lapack_full_matrix_ext.h.
tau
template<typename Number > std::vector<Number> LAPACKFullMatrixExt< Number >::tau private
The scalar factors of the elementary reflectors, which are used in QR decomposition.
Definition at line 1522 of file lapack_full_matrix_ext.h.
work
template<typename Number > std::vector<Number> LAPACKFullMatrixExt< Number >::work private
Work space used by LAPACK routines.
Definition at line 1527 of file lapack_full_matrix_ext.h.
The documentation for this class was generated from the following file:
include/linear_algebra/lapack_full_matrix_ext.h