HierBEM: BlockClusterTree< spacedim, Number > Class Template Reference
BlockClusterTree< spacedim, Number > Class Template Reference
Hierarchical matrices
Class for block cluster tree.
#include <block_cluster_tree.h>
Public Types
typedef TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > node_value_type
typedef TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * node_pointer_type
typedef const TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > * node_const_pointer_type
typedef TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > & node_reference_type
typedef const TreeNode< BlockCluster< spacedim, Number >, BlockClusterTree< spacedim, Number >::child_num > & node_const_reference_type
typedef BlockCluster< spacedim, Number > data_value_type
typedef BlockCluster< spacedim, Number > * data_pointer_type
typedef const BlockCluster< spacedim, Number > * data_const_pointer_type
typedef BlockCluster< spacedim, Number > & data_reference_type
typedef const BlockCluster< spacedim, Number > & data_const_reference_type
Public Member Functions
DeclException2 (ExcClusterLevelMismatch, unsigned int, unsigned int,<< "The level of cluster tau "<< arg1<< " is different from that of cluster sigma"<< arg2<< " which is not allowed in a level preserving construction of a block cluster tree.")
Static Public Attributes
static const unsigned int child_num = 4
Private Attributes
node_pointer_type root_node
std::vector< node_pointer_type > leaf_set
std::vector< node_pointer_type > near_field_set
std::vector< node_pointer_type > far_field_set
unsigned int n_min
Number eta
unsigned int depth
int max_level
unsigned int node_num
bool is_subtree
Friends
template<int spacedim1, typename Number1 >
std::ostream & operator<< (std::ostream &out, const BlockClusterTree< spacedim1, Number1 > &block_cluster_tree)
template<int spacedim1, typename Number1 >
void split_block_cluster_node (TreeNode< BlockCluster< spacedim1, Number1 >, BlockClusterTree< spacedim1, Number1 >::child_num > *bc_node, BlockClusterTree< spacedim1, Number1 > &bc_tree, const TreeNodeSplitMode split_mode, const bool if_add_child_nodes_to_leaf_set)
template<int spacedim1, typename Number1 >
bool prune_to_partition_recursion (BlockClusterTree< spacedim1, Number1 > &bct, const std::vector< TreeNode< BlockCluster< spacedim1, Number1 >, BlockClusterTree< spacedim1, Number1 >::child_num > * > &partition, TreeNode< BlockCluster< spacedim1, Number1 >, BlockClusterTree< spacedim1, Number1 >::child_num > *bc_node)
template<int spacedim1, typename Number1 >
TreeNode< BlockCluster< spacedim1, Number1 >, BlockClusterTree< spacedim1, Number1 >::child_num > * find_bc_node_in_partition_intersect_current_bc_node (TreeNode< BlockCluster< spacedim1, Number1 >, BlockClusterTree< spacedim1, Number1 >::child_num > *current_bc_node, const std::vector< TreeNode< BlockCluster< spacedim1, Number1 >, BlockClusterTree< spacedim1, Number1 >::child_num > * > &partition)
template<int spacedim1, typename Number1 >
TreeNode< BlockCluster< spacedim1, Number1 >, BlockClusterTree< spacedim1, Number1 >::child_num > * find_bc_node_in_partition_proper_subset_of_current_bc_node (TreeNode< BlockCluster< spacedim1, Number1 >, BlockClusterTree< spacedim1, Number1 >::child_num > *current_bc_node, const std::vector< TreeNode< BlockCluster< spacedim1, Number1 >, BlockClusterTree< spacedim1, Number1 >::child_num > * > &partition)
template<int spacedim1, typename Number1 >
void print_block_cluster_node_info_as_dot_node (std::ostream &out, const TreeNode< BlockCluster< spacedim1, Number1 >, BlockClusterTree< spacedim1, Number1 >::child_num > &tree_node)
BlockClusterTree ()
BlockClusterTree (const ClusterTree< spacedim, Number > &TI, const ClusterTree< spacedim, Number > &TJ, const unsigned int n_min=0)
BlockClusterTree (typename ClusterTree< spacedim, Number >::node_pointer_type tau_root_node, typename ClusterTree< spacedim, Number >::node_pointer_type sigma_root_node, const unsigned int n_min=1)
BlockClusterTree (node_pointer_type bc_node, const unsigned int n_min)
BlockClusterTree (node_pointer_type bc_node, const Number eta, const unsigned int n_min)
BlockClusterTree (const ClusterTree< spacedim, Number > &TI, const ClusterTree< spacedim, Number > &TJ, const Number eta, const unsigned int n_min)
BlockClusterTree (const BlockClusterTree< spacedim, Number > &bct)
BlockClusterTree (BlockClusterTree< spacedim, Number > &&bct)
BlockClusterTree< spacedim, Number > & operator= (const BlockClusterTree< spacedim, Number > &bct)
BlockClusterTree< spacedim, Number > & operator= (BlockClusterTree< spacedim, Number > &&bct)
~BlockClusterTree ()
void release ()
void clear ()
void partition_tensor_product ()
void partition_coarse_non_tensor_product ()
void partition_fine_non_tensor_product ()
void partition (const std::vector< types::global_dof_index > &internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > &all_support_points)
void partition (const std::vector< types::global_dof_index > &internal_to_external_dof_numbering_I, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering_J, const std::vector< Point< spacedim, Number > > &all_support_points_in_I, const std::vector< Point< spacedim, Number > > &all_support_points_in_J)
void partition (const std::vector< types::global_dof_index > &internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > &all_support_points, const std::vector< Number > &cell_size_at_dofs)
void partition (const std::vector< types::global_dof_index > &internal_to_external_dof_numbering_I, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering_J, const std::vector< Point< spacedim, Number > > &all_support_points_in_I, const std::vector< Point< spacedim, Number > > &all_support_points_in_J, const std::vector< Number > &cell_size_at_dofs_in_I, const std::vector< Number > &cell_size_at_dofs_in_J)
bool extend_finer_than_partition (const std::vector< node_pointer_type > &partition)
bool extend_to_finer_partition (const std::vector< node_pointer_type > &partition)
bool prune_descendants_from_node (node_pointer_type bc_node)
bool prune_to_partition (const std::vector< node_pointer_type > &partition, const bool is_partition_in_bct)
node_pointer_type get_root () const
std::vector< node_pointer_type > & get_leaf_set ()
const std::vector< node_pointer_type > & get_leaf_set () const
void build_leaf_set ()
void write_leaf_set (std::ostream &out) const
template<typename Number1 = double>
void write_leaf_set (std::ostream &out, const LAPACKFullMatrixExt< Number1 > &matrix, const Number1 singular_value_threshold=0.) const
void print_bct_info_as_dot (std::ostream &out) const
std::vector< node_pointer_type > & get_near_field_set ()
const std::vector< node_pointer_type > & get_near_field_set () const
std::vector< node_pointer_type > & get_far_field_set ()
const std::vector< node_pointer_type > & get_far_field_set () const
unsigned int get_n_min () const
Number get_eta () const
unsigned int get_depth () const
void calc_depth_and_max_level ()
int get_max_level () const
unsigned int get_node_num () const
void set_node_num (unsigned int node_num)
unsigned int increase_node_num (unsigned int increased_node_num=1)
unsigned int decrease_node_num (unsigned int decreased_node_num=1)
void categorize_near_and_far_field_sets ()
std::size_t memory_consumption () const
std::size_t memory_consumption_of_all_block_clusters () const
void partition_tensor_product_from_block_cluster_node (node_pointer_type current_block_cluster_node, std::vector< node_pointer_type > &leaf_set_wrt_current_node)
void partition_coarse_non_tensor_product_from_block_cluster_node (node_pointer_type current_block_cluster_node, std::vector< node_pointer_type > &leaf_set_wrt_current_node)
void partition_fine_non_tensor_product_from_block_cluster_node (node_pointer_type current_block_cluster_node, std::vector< node_pointer_type > &leaf_set_wrt_current_node)
void partition_fine_non_tensor_product_from_block_cluster_node_N (node_pointer_type current_block_cluster_node, std::vector< node_pointer_type > &leaf_set_wrt_current_node)
void partition_fine_non_tensor_product_from_block_cluster_node_Nstar (node_pointer_type current_block_cluster_node, std::vector< node_pointer_type > &leaf_set_wrt_current_node)
void partition_from_block_cluster_node (node_pointer_type current_block_cluster_node, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > &all_support_points, std::vector< node_pointer_type > &leaf_set_wrt_current_node)
void partition_from_block_cluster_node (node_pointer_type current_block_cluster_node, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering_I, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering_J, const std::vector< Point< spacedim, Number > > &all_support_points_in_I, const std::vector< Point< spacedim, Number > > &all_support_points_in_J, std::vector< node_pointer_type > &leaf_set_wrt_current_node)
void partition_from_block_cluster_node (node_pointer_type current_block_cluster_node, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > &all_support_points, const std::vector< Number > &cell_size_at_dofs, std::vector< node_pointer_type > &leaf_set_wrt_current_node)
void partition_from_block_cluster_node (node_pointer_type current_block_cluster_node, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering_I, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering_J, const std::vector< Point< spacedim, Number > > &all_support_points_in_I, const std::vector< Point< spacedim, Number > > &all_support_points_in_J, const std::vector< Number > &cell_size_at_dofs_in_I, const std::vector< Number > &cell_size_at_dofs_in_J, std::vector< node_pointer_type > &leaf_set_wrt_current_node)
node_pointer_type find_leaf_bc_node_not_subset_of_bc_nodes_in_partition (const std::vector< node_pointer_type > &partition, typename std::vector< node_pointer_type >::const_iterator &it_for_desired_bc_node) const
node_pointer_type find_leaf_bc_node_not_in_partition (const std::vector< node_pointer_type > &partition, typename std::vector< node_pointer_type >::const_iterator &it_for_desired_bc_node) const
Detailed Description
template<int spacedim, typename Number = double>
class BlockClusterTree< spacedim, Number >
Class for block cluster tree.
A block cluster tree is a quad-tree which holds a hierarchy of doubly linked nodes with the type TreeNode. Because a node in the block cluster tree has four children, the template argument T required by TreeNode should be 4.
Definition at line 48 of file block_cluster_tree.h.
Member Typedef Documentation
data_const_pointer_type
template<int spacedim, typename Number = double> typedef const BlockCluster<spacedim, Number>* BlockClusterTree< spacedim, Number >::data_const_pointer_type
Definition at line 112 of file block_cluster_tree.h.
data_const_reference_type
template<int spacedim, typename Number = double> typedef const BlockCluster<spacedim, Number>& BlockClusterTree< spacedim, Number >::data_const_reference_type
Definition at line 114 of file block_cluster_tree.h.
data_pointer_type
template<int spacedim, typename Number = double> typedef BlockCluster<spacedim, Number>* BlockClusterTree< spacedim, Number >::data_pointer_type
Definition at line 111 of file block_cluster_tree.h.
data_reference_type
template<int spacedim, typename Number = double> typedef BlockCluster<spacedim, Number>& BlockClusterTree< spacedim, Number >::data_reference_type
Definition at line 113 of file block_cluster_tree.h.
data_value_type
template<int spacedim, typename Number = double> typedef BlockCluster<spacedim, Number> BlockClusterTree< spacedim, Number >::data_value_type
Data type of the data held by a tree node.
Definition at line 110 of file block_cluster_tree.h.
node_const_pointer_type
template<int spacedim, typename Number = double> typedef const TreeNode<BlockCluster<spacedim, Number>, BlockClusterTree<spacedim, Number>::child_num>* BlockClusterTree< spacedim, Number >::node_const_pointer_type
Definition at line 99 of file block_cluster_tree.h.
node_const_reference_type
template<int spacedim, typename Number = double> typedef const TreeNode<BlockCluster<spacedim, Number>, BlockClusterTree<spacedim, Number>::child_num>& BlockClusterTree< spacedim, Number >::node_const_reference_type
Definition at line 105 of file block_cluster_tree.h.
node_pointer_type
template<int spacedim, typename Number = double> typedef TreeNode<BlockCluster<spacedim, Number>, BlockClusterTree<spacedim, Number>::child_num>* BlockClusterTree< spacedim, Number >::node_pointer_type
Definition at line 96 of file block_cluster_tree.h.
node_reference_type
template<int spacedim, typename Number = double> typedef TreeNode<BlockCluster<spacedim, Number>, BlockClusterTree<spacedim, Number>::child_num>& BlockClusterTree< spacedim, Number >::node_reference_type
Definition at line 102 of file block_cluster_tree.h.
node_value_type
template<int spacedim, typename Number = double> typedef TreeNode<BlockCluster<spacedim, Number>, BlockClusterTree<spacedim, Number>::child_num> BlockClusterTree< spacedim, Number >::node_value_type
Data type of the tree node.
Definition at line 93 of file block_cluster_tree.h.
Constructor & Destructor Documentation
BlockClusterTree() [1/8]
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number >::BlockClusterTree
Default constructor, which initializes an empty quad-tree.
Definition at line 1294 of file block_cluster_tree.h.
BlockClusterTree() [2/8]
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number >::BlockClusterTree (const ClusterTree< spacedim, Number > & TI, const ClusterTree< spacedim, Number > & TJ, const unsigned int n_min = 0)
Construct from two cluster trees built from pure cardinality based partition, which has no admissibility condition.
After construction, there is only one node in the block cluster tree, i.e. tree hierarchy is not built.
Parameters
TI
TJ
n_min
Definition at line 1309 of file block_cluster_tree.h.
References CreateTreeNode(), ClusterTree< spacedim, Number >::get_n_min(), and ClusterTree< spacedim, Number >::get_root().
BlockClusterTree() [3/8]
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number >::BlockClusterTree (typename ClusterTree< spacedim, Number >::node_pointer_type tau_root_node, typename ClusterTree< spacedim, Number >::node_pointer_type sigma_root_node, const unsigned int n_min = 1)
Construct from two cluster nodes, whose Cartesian product is the root node of the block cluster tree.
After construction, there is only one node in the block cluster tree, i.e. tree hierarchy is not built.
Parameters
tau_root_node
sigma_root_node
Definition at line 1351 of file block_cluster_tree.h.
References CreateTreeNode().
BlockClusterTree() [4/8]
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number >::BlockClusterTree (node_pointer_type bc_node, const unsigned int n_min)
Construct a block cluster subtree by initializing from a block cluster node.
The constructed block cluster subtree simply takes over an existing block cluster node in a block cluster tree which has been built before.
Parameters
bc_node
n_min
Definition at line 1385 of file block_cluster_tree.h.
References BlockClusterTree< spacedim, Number >::build_leaf_set(), BlockClusterTree< spacedim, Number >::calc_depth_and_max_level(), BlockClusterTree< spacedim, Number >::categorize_near_and_far_field_sets(), CountTreeNodes(), and BlockClusterTree< spacedim, Number >::node_num.
BlockClusterTree() [5/8]
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number >::BlockClusterTree (node_pointer_type bc_node, const Number eta, const unsigned int n_min)
Construct a block cluster subtree by initializing from a block cluster node. This version has the admissibility condition.
The constructed block cluster subtree simply takes over an existing block cluster node in a block cluster tree which has been built before.
Parameters
bc_node
Definition at line 1406 of file block_cluster_tree.h.
References BlockClusterTree< spacedim, Number >::build_leaf_set(), BlockClusterTree< spacedim, Number >::calc_depth_and_max_level(), BlockClusterTree< spacedim, Number >::categorize_near_and_far_field_sets(), CountTreeNodes(), and BlockClusterTree< spacedim, Number >::node_num.
BlockClusterTree() [6/8]
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number >::BlockClusterTree (const ClusterTree< spacedim, Number > & TI, const ClusterTree< spacedim, Number > & TJ, const Number eta, const unsigned int n_min)
Construct from two cluster trees and admissibility condition.
The Cartesian product of the two clusters in the root nodes of \(T(I)\) and \(T(J)\) becomes the data in the root node of the block cluster tree.
After construction, there is only one node in the block cluster tree, i.e. tree hierarchy is not built.
Definition at line 1428 of file block_cluster_tree.h.
References CreateTreeNode(), ClusterTree< spacedim, Number >::get_n_min(), and ClusterTree< spacedim, Number >::get_root().
BlockClusterTree() [7/8]
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number >::BlockClusterTree (const BlockClusterTree< spacedim, Number > & bct)
Copy constructor for BlockClusterTree, which realizes deep copy internally.
Note
Because this is deep copy, the constructed block cluster tree is a new tree but never a subtree of an existing block cluster tree. Hence, the data field is_subtree is set to false.
Parameters
bct
Definition at line 1471 of file block_cluster_tree.h.
References BlockClusterTree< spacedim, Number >::build_leaf_set(), BlockClusterTree< spacedim, Number >::categorize_near_and_far_field_sets(), CopyTree(), and BlockClusterTree< spacedim, Number >::get_root().
BlockClusterTree() [8/8]
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number >::BlockClusterTree (BlockClusterTree< spacedim, Number > && bct)
Copy constructor via shallow copy.
Note
The data members of the input bct must be cleared before exiting this constructor. Otherwise, when bct is out of its range, the data associated with the current block cluster tree will also be destroyed, which is undesired.
Parameters
bct
Returns
Definition at line 1492 of file block_cluster_tree.h.
~BlockClusterTree()
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number >::~BlockClusterTree
Destructor which recursively destroys every node in the block cluster tree.
Definition at line 1574 of file block_cluster_tree.h.
Member Function Documentation
build_leaf_set()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::build_leaf_set
Build the leaf set by tree recursion.
Definition at line 3786 of file block_cluster_tree.h.
References GetTreeLeaves().
Referenced by BlockClusterTree< spacedim, Number >::BlockClusterTree(), and HMatrix< spacedim, Number >::mmult().
calc_depth_and_max_level()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::calc_depth_and_max_level
Calculate the depth.
Definition at line 3981 of file block_cluster_tree.h.
References calc_depth().
Referenced by BlockClusterTree< spacedim, Number >::BlockClusterTree(), and HMatrix< spacedim, Number >::mmult().
categorize_near_and_far_field_sets()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::categorize_near_and_far_field_sets
Categorize the leaf set into near field set and far field set.
Definition at line 3719 of file block_cluster_tree.h.
Referenced by BlockClusterTree< spacedim, Number >::BlockClusterTree(), and HMatrix< spacedim, Number >::mmult().
clear()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::clear
Clear the data field of the block cluster tree because its memory has been migrated to another object via shallow copy.
Definition at line 1598 of file block_cluster_tree.h.
decrease_node_num()
template<int spacedim, typename Number > unsigned int BlockClusterTree< spacedim, Number >::decrease_node_num (unsigned int decreased_node_num = 1) inline
Decrease the total number of nodes in the tree.
Definition at line 4025 of file block_cluster_tree.h.
extend_finer_than_partition()
template<int spacedim, typename Number > bool BlockClusterTree< spacedim, Number >::extend_finer_than_partition (const std::vector< node_pointer_type > & partition)
Extend the current block cluster tree to be finer than the given partition.
This member functions implements (7.10a) in Hackbusch's \(\mathcal{H}\)-matrix book.
Note
This algorithm iterates over each element in the leaf set of the block cluster tree to be extended. During the iteration, because leaf nodes may be further split into smaller ones, the leaf set is not a constant. Hence, the leaf set should be updated immediately whenever a block cluster node is split. This behavior is different from other functions such as HMatrix<spacedim, Number>::refine_to_supertree, the leaf set of of which will be built after the whole tree hierarchy has been constructed.
Parameters
P
Returns
Whether the block cluster tree has really been extended.
Iterate over the leaf set of the current block cluster tree and look for a block cluster which is not contained by any block cluster in the given partition.
Flag variable indicating whether the current block cluster tree has actually been extended. If true, the leaf set of the current block cluster tree has been modified during the extension, which needs a further re-categorization into the near field set and the far field set.
Enter the loop by selecting a block cluster node from the leaf set which is not contained in any block cluster nodes in the given partition.
Because the selected block cluster node in the leaf set is about to be split, we delete the current block cluster node from the leaf set here and add its children to the leaf set later on during calling split_block_cluster_node.
Select a block cluster node in the given partition, whose index set has a nonempty intersection with the index set of the current block cluster node.
Because the given partition is a covering of the complete block cluster index set \(I \times J\), such block cluster node must exist. Hence we make an assertion here.
Extend the current block cluster node by splitting its \(\tau\) node, which is horizontal split, then make Cartesian product with its \(\sigma\) node. The newly created block cluster nodes are appended to the leaf set.
Extend the current block cluster node by splitting its \(\sigma\) node, which is vertical split, then make Cartesian product with its \(\tau\) node. The newly created block cluster nodes are appended to the leaf set.
Extend the current block cluster node by splitting its \(\tau\) node, which is horizontal split, then make Cartesian product with its \(\sigma\) node. The newly created block cluster nodes are appended to the leaf set.
Extend the current block cluster node by splitting its \(\sigma\) node, which is vertical split, then make Cartesian product with its \(\tau\) node. The newly created block cluster nodes are appended to the leaf set.
Update the maximum level and depth of the current tree if necessary.
After block cluster tree extension, re-categorize the near field set and far field set based on the new leaf set. N.B. The value of n_min and eta does not change. Meanwhile, depth and max_level have been updated during previous procedures.
Definition at line 1739 of file block_cluster_tree.h.
References find_bc_node_in_partition_intersect_current_bc_node(), TreeNode< T, N >::get_data_reference(), and split_block_cluster_node().
Referenced by HMatrix< spacedim, Number >::convert_between_different_block_cluster_trees().
extend_to_finer_partition()
template<int spacedim, typename Number > bool BlockClusterTree< spacedim, Number >::extend_to_finer_partition (const std::vector< node_pointer_type > & partition)
Extend the current block cluster tree to the given finer partition.
This member functions implements (7.10b) in Hackbusch's \(\mathcal{H}\)-matrix book.
Note
This algorithm iterates over each element in the leaf set of the block cluster tree to be extended. During the iteration, because leaf nodes may be further split into smaller ones, the leaf set is not a constant. Hence, the leaf set should be updated immediately whenever a block cluster node is split. This behavior is different from other functions such as HMatrix<spacedim, Number>::refine_to_supertree, the leaf set of of which will be built after the whole tree hierarchy has been constructed.
Iterate over the leaf set of the current block cluster tree and look for a block cluster which does not belong to the partition.
Enter the loop by selecting a block cluster node from the leaf set, which does not belong to the given partition.
Because the selected block cluster node in the leaf set is about to be split, we delete the current block cluster node from the leaf set here and add its children to the leaf set later on during calling split_block_cluster_node.
Select a block cluster node in the given partition, whose index set is a proper subset of the index set of the current block cluster node.
Because the partition is a covering of the complete block cluster index set \(I \times J\) and it is finer than the leaf set of the current block cluster tree, such block cluster node must exist. Hence we make an assertion here.
Here we ensure that the level difference between \(\tau\) and \(\sigma\) clusters is at most 1.
Extend the current block cluster node by splitting its \(\tau\) node, which is horizontal split, then make Cartesian product with its \(\sigma\) node. The newly created block cluster nodes are appended to the leaf set.
Extend the current block cluster node by splitting its \(\sigma\) node, which is vertical split, then make Cartesian product with its \(\tau\) node. The newly created block cluster nodes are appended to the leaf set.
Extend the current block cluster node by splitting its \(\tau\) node, which is horizontal split, then make Cartesian product with its \(\sigma\) node. The newly created block cluster nodes are appended to the leaf set.
Extend the current block cluster node by splitting its \(\sigma\) node, which is vertical split, then make Cartesian product with its \(\tau\) node. The newly created block cluster nodes are appended to the leaf set.
Update the maximum level and depth of the current tree if necessary.
After block cluster tree extension, re-categorize the near field set and far field set based on the new leaf set. N.B. The value of n_min and eta does not change. Meanwhile, depth and max_level have been updated during previous procedures.
Definition at line 1896 of file block_cluster_tree.h.
Referenced by HMatrix< spacedim, Number >::convert_between_different_block_cluster_trees().
find_leaf_bc_node_not_in_partition()
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number >::node_pointer_type BlockClusterTree< spacedim, Number >::find_leaf_bc_node_not_in_partition (const std::vector< node_pointer_type > & partition, typename std::vector< node_pointer_type >::const_iterator & it_for_desired_bc_node) const private
Find a block cluster node in the leaf set of the current block cluster tree, which does not belong to the partition.
Parameters
partition the given partition.
it_for_desired_bc_node the returned iterator which points to the selected block cluster node in the leaf set of the current block cluster tree. N.B. Only when the returned pointer is not nullptr, this iterator is meaningful.
Returns
pointer to the selected block cluster node.
Work flow
Iterate over each block cluster node in the leaf set of the current block cluster tree.
Iterate over each block cluster node in the given partition.
When the index set of the current block cluster node is equal to the index set of some block cluster node in the given partition, terminate the inner loop and jump to the next leaf node for checking.
Here the desired block cluster node in the leaf set is found. Then exist the outer loop and the iterator it_for_desired_bc_node now pointing to this node will also be returned.
Definition at line 3498 of file block_cluster_tree.h.
References TreeNode< T, N >::get_data_reference(), and is_equal().
find_leaf_bc_node_not_subset_of_bc_nodes_in_partition()
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number >::node_pointer_type BlockClusterTree< spacedim, Number >::find_leaf_bc_node_not_subset_of_bc_nodes_in_partition (const std::vector< node_pointer_type > & partition, typename std::vector< node_pointer_type >::const_iterator & it_for_desired_bc_node) const private
Find a block cluster node in the leaf set of the current block cluster tree, which is not a subset of any block cluster in the given partition.
Parameters
partition the given partition.
it_for_desired_bc_node the returned iterator which points to the selected block cluster node in the leaf set of the current block cluster tree. N.B. Only when the returned pointer is not nullptr, this iterator is meaningful.
Returns
pointer to the selected block cluster node.
Work flow
Iterate over each block cluster node in the leaf set of the current block cluster tree.
Iterate over each block cluster node in the given partition.
When the index set of the current block cluster node in the leaf set is a subset of the index set of some block cluster node in the given partition, terminate the inner loop and jump to the next leaf node for checking.
Here the desired block cluster node in the leaf set is found. Then exist the outer loop and the iterator it_for_desired_bc_node now pointing to this node will also be returned.
Definition at line 3429 of file block_cluster_tree.h.
References TreeNode< T, N >::get_data_reference().
get_depth()
template<int spacedim, typename Number > unsigned int BlockClusterTree< spacedim, Number >::get_depth inline
Get the tree depth.
Definition at line 3973 of file block_cluster_tree.h.
get_eta()
template<int spacedim, typename Number > Number BlockClusterTree< spacedim, Number >::get_eta inline
Get the admissibility parameter.
Returns
Definition at line 4046 of file block_cluster_tree.h.
get_far_field_set() [1/2]
template<int spacedim, typename Number > std::vector< typename BlockClusterTree< spacedim, Number >::node_pointer_type > & BlockClusterTree< spacedim, Number >::get_far_field_set inline
Get the reference to the block cluster list which belongs to the far field.
Definition at line 3956 of file block_cluster_tree.h.
get_far_field_set() [2/2]
template<int spacedim, typename Number > const std::vector< typename BlockClusterTree< spacedim, Number >::node_pointer_type > & BlockClusterTree< spacedim, Number >::get_far_field_set inline
Get the reference to the block cluster list which belongs to the far field (const version).
Definition at line 3965 of file block_cluster_tree.h.
get_leaf_set() [1/2]
template<int spacedim, typename Number > std::vector< typename BlockClusterTree< spacedim, Number >::node_pointer_type > & BlockClusterTree< spacedim, Number >::get_leaf_set inline
Get the reference to the block cluster list.
Definition at line 3769 of file block_cluster_tree.h.
Referenced by HMatrix< spacedim, Number >::coarsen_to_subtree(), and HMatrix< spacedim, Number >::convert_between_different_block_cluster_trees().
get_leaf_set() [2/2]
template<int spacedim, typename Number > const std::vector< typename BlockClusterTree< spacedim, Number >::node_pointer_type > & BlockClusterTree< spacedim, Number >::get_leaf_set inline
Get the reference to the block cluster list (const version).
Definition at line 3778 of file block_cluster_tree.h.
get_max_level()
template<int spacedim, typename Number > int BlockClusterTree< spacedim, Number >::get_max_level inline
Get the maximum level of the tree.
Definition at line 3990 of file block_cluster_tree.h.
get_n_min()
template<int spacedim, typename Number > unsigned int BlockClusterTree< spacedim, Number >::get_n_min inline
Get the minimum cluster size.
Definition at line 4038 of file block_cluster_tree.h.
Referenced by HMatrix< spacedim, Number >::mmult().
get_near_field_set() [1/2]
template<int spacedim, typename Number > std::vector< typename BlockClusterTree< spacedim, Number >::node_pointer_type > & BlockClusterTree< spacedim, Number >::get_near_field_set inline
Get the reference to the block cluster list which belongs to the near field.
Definition at line 3938 of file block_cluster_tree.h.
get_near_field_set() [2/2]
template<int spacedim, typename Number > const std::vector< typename BlockClusterTree< spacedim, Number >::node_pointer_type > & BlockClusterTree< spacedim, Number >::get_near_field_set inline
Get the reference to the block cluster list which belongs to the near field (const version).
Definition at line 3947 of file block_cluster_tree.h.
get_node_num()
template<int spacedim, typename Number > unsigned int BlockClusterTree< spacedim, Number >::get_node_num inline
Get the total number of clusters in the tree.
Definition at line 3998 of file block_cluster_tree.h.
get_root()
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number >::node_pointer_type BlockClusterTree< spacedim, Number >::get_root inline
Get the pointer to the root node of the block cluster tree.
Returns
Definition at line 2127 of file block_cluster_tree.h.
Referenced by BlockClusterTree< spacedim, Number >::BlockClusterTree(), HMatrix< spacedim, Number >::mmult(), and BlockClusterTree< spacedim, Number >::operator=().
increase_node_num()
template<int spacedim, typename Number > unsigned int BlockClusterTree< spacedim, Number >::increase_node_num (unsigned int increased_node_num = 1) inline
Increase the total number of nodes in the tree.
Definition at line 4014 of file block_cluster_tree.h.
memory_consumption()
template<int spacedim, typename Number > std::size_t BlockClusterTree< spacedim, Number >::memory_consumption
Estimate the memory consumption of the block cluster tree with all nodes and contained data.
Definition at line 3740 of file block_cluster_tree.h.
memory_consumption_of_all_block_clusters()
template<int spacedim, typename Number > std::size_t BlockClusterTree< spacedim, Number >::memory_consumption_of_all_block_clusters
Estimate the memory consumption of all nodes in the cluster tree and their contained data.
Definition at line 3755 of file block_cluster_tree.h.
References Preorder_for_memory_consumption().
operator=() [1/2]
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number > & BlockClusterTree< spacedim, Number >::operator= (BlockClusterTree< spacedim, Number > && bct)
Overloaded assignment operator with shallow copy.
Parameters
bct
Returns
Definition at line 1544 of file block_cluster_tree.h.
operator=() [2/2]
template<int spacedim, typename Number > BlockClusterTree< spacedim, Number > & BlockClusterTree< spacedim, Number >::operator= (const BlockClusterTree< spacedim, Number > & bct)
Overloaded assignment operator with deep copy.
Parameters
bct
Returns
If the current block cluster tree is a subtree of an existing block cluster tree, clear its data members instead of releasing their memory.
Definition at line 1511 of file block_cluster_tree.h.
References CopyTree(), BlockClusterTree< spacedim, Number >::depth, BlockClusterTree< spacedim, Number >::get_root(), BlockClusterTree< spacedim, Number >::max_level, and BlockClusterTree< spacedim, Number >::node_num.
partition() [1/4]
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition (const std::vector< types::global_dof_index > & internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > & all_support_points)
Perform a recursive partition by starting from the root node. The evaluation of the admissibility condition has no mesh cell size correction.
Note
The index sets held by the two clusters share a same external DoF numbering.
Parameters
all_support_points All the support points.
Definition at line 1651 of file block_cluster_tree.h.
Referenced by DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::initialize_subdomain_hmatrices().
partition() [2/4]
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition (const std::vector< types::global_dof_index > & internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > & all_support_points, const std::vector< Number > & cell_size_at_dofs)
Perform a recursive partition by starting from the root node. The evaluation of the admissibility condition has mesh cell size correction.
Note
The index sets held by the two clusters share a same external DoF numbering.
Parameters
all_support_points All the support points.
Definition at line 1692 of file block_cluster_tree.h.
partition() [3/4]
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition (const std::vector< types::global_dof_index > & internal_to_external_dof_numbering_I, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering_J, const std::vector< Point< spacedim, Number > > & all_support_points_in_I, const std::vector< Point< spacedim, Number > > & all_support_points_in_J)
Perform a recursive partition by starting from the root node. The evaluation of the admissibility condition has no mesh cell size correction.
Note
The index sets inferred from the index ranges held by the two clusters share a same internal DoF numbering, which need to be mapped to the external numbering for accessing the list of support point coordinates.
Parameters
internal_to_external_dof_numbering_I
internal_to_external_dof_numbering_J
all_support_points_in_I
all_support_points_in_J
Definition at line 1669 of file block_cluster_tree.h.
partition() [4/4]
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition (const std::vector< types::global_dof_index > & internal_to_external_dof_numbering_I, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering_J, const std::vector< Point< spacedim, Number > > & all_support_points_in_I, const std::vector< Point< spacedim, Number > > & all_support_points_in_J, const std::vector< Number > & cell_size_at_dofs_in_I, const std::vector< Number > & cell_size_at_dofs_in_J)
Perform a recursive partition by starting from the root node. The evaluation of the admissibility condition has mesh cell size correction.
Note
The index sets inferred from the index ranges held by the two clusters share a same internal DoF numbering, which need to be mapped to the external numbering for accessing the list of support point coordinates.
Parameters
internal_to_external_dof_numbering_I
internal_to_external_dof_numbering_J
all_support_points_in_I
all_support_points_in_J
cell_size_at_dofs_in_I
cell_size_at_dofs_in_J
Definition at line 1712 of file block_cluster_tree.h.
partition_coarse_non_tensor_product()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition_coarse_non_tensor_product
Perform a recursive partition in coarse non-tensor product form without the admissibility condition because the two comprising cluster trees are built from pure cardinality based partition.
Definition at line 1625 of file block_cluster_tree.h.
partition_coarse_non_tensor_product_from_block_cluster_node()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition_coarse_non_tensor_product_from_block_cluster_node (node_pointer_type current_block_cluster_node, std::vector< node_pointer_type > & leaf_set_wrt_current_node) private
Perform a recursive non-tensor product type coarse partition by starting from a block cluster node in the tree.
No admissibility condition is enabled in this situation, because the two comprising cluster trees are built from pure cardinality based partition.
Reference: Section 2.2.2 in Hackbusch, W. 1999. A Sparse Matrix Arithmetic Based on H-Matrices. Part I: Introduction to H-Matrices. Computing 62 (2): 89108.
Parameters
current_block_cluster_node
leaf_set_wrt_current_node
Push back the current cluster node, which is small, to the leaf set and set its split mode as UnsplitMode.
Make sure that the two clusters \(\tau\) and \(\sigma\) have the same level in their respective cluster trees, i.e. level preserving property should be satisfied.
Create a new block cluster node as child. Then append this new node as one of the children of the current block cluster node. Finally, recursively partition from this node if the two component clusters have the same indices, i.e. \(I_1 \times I_1\) and \(I_2 \times I_2\); otherwise, for \(I_1 \times I_2\) and \(I_2 \times I_1\), stop the recursion and directly add them to the leaf set.
Append this new node as one of the children of the current block cluster node.
Handle the case for \(I_1 \times I_1\) and \(I_2 \times I_2\).
Merge the leaf set wrt. the child block cluster node into the leaf set of the current block cluster node.
Handle the case for \(I_1 \times I_2\) and \(I_2 \times I_1\). Because the recursion stops here, we need to check and update its near field property.
Make sure the current block cluster have four children, which is ensured by the non-tensor product construction.
Note
The second argument BlockClusterTree<spacedim, Number>::child_num should be wrapped between the brackets, otherwise, the program cannot be compiled.
Set the split mode of the current block cluster node as cross.
Definition at line 2256 of file block_cluster_tree.h.
References TreeNode< T, N >::get_data_pointer(), and TreeNode< T, N >::set_split_mode().
partition_fine_non_tensor_product()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition_fine_non_tensor_product
Perform a recursive partition in fine non-tensor product form without the admissibility condition because the two comprising cluster trees are built from pure cardinality based partition.
Definition at line 1638 of file block_cluster_tree.h.
partition_fine_non_tensor_product_from_block_cluster_node()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition_fine_non_tensor_product_from_block_cluster_node (node_pointer_type current_block_cluster_node, std::vector< node_pointer_type > & leaf_set_wrt_current_node) private
Perform a recursive non-tensor product type fine partition of \(\mathcal{M}_{\mathcal{H},k}\) type by starting from a block cluster node in the tree.
No admissibility condition is enabled in this situation, because the two comprising cluster trees are built from pure cardinality based partition.
Reference: Section 5 in Hackbusch, W. 1999. A Sparse Matrix Arithmetic Based on H-Matrices. Part I: Introduction to H-Matrices. Computing 62 (2): 89108.
Parameters
current_block_cluster_node
leaf_set_wrt_current_node
Push back the current cluster node, which is small, to the leaf set and set its split mode as UnsplitMode.
Set the split mode of the current block cluster node as cross.
Make sure that the two clusters \(\tau\) and \(\sigma\) have the same level in their respective cluster trees, i.e. level preserving property should be satisfied.
Create a new block cluster node as child. Then append this new node as one of the children of the current block cluster node. Finally, recursively partition from this node using the fine non-tensor product method if the two component clusters have the same indices, i.e. \(I_1 \times I_1\) and \(I_2 \times I_2\); for \(I_1 \times I_2\), recursively partition from it using the \(\mathcal{N}\)-type partition method; for \(I_2 \times I_1\), recursively partition from it using the \(\mathcal{N}^*\)-type partition method.
Append this new node as one of the children of the current block cluster node.
Handle the case for \(I_1 \times I_1\) and \(I_2 \times I_2\) by recursively applying the fine non-tensor product partition method itself.
Merge the leaf set wrt. the child block cluster node into the leaf set of the current block cluster node.
Handle the case for \(I_1 \times I_2\) and perform the \(\mathcal{N}\)-type recursive partition.
Merge the leaf set wrt. the child block cluster node into the leaf set of the current block cluster node.
Handle the case for \(I_2 \times I_1\) and perform the \(\mathcal{N}^*\)-type recursive partition.
Merge the leaf set wrt. the child block cluster node into the leaf set of the current block cluster node.
This case can never happen.
Make sure the current block cluster have four children, which is ensured by the fine non-tensor product construction.
Note
The second argument BlockClusterTree<spacedim, Number>::child_num should be wrapped between the brackets, otherwise, the program cannot be compiled.
Definition at line 2399 of file block_cluster_tree.h.
References TreeNode< T, N >::get_data_pointer(), and TreeNode< T, N >::set_split_mode().
partition_fine_non_tensor_product_from_block_cluster_node_N()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition_fine_non_tensor_product_from_block_cluster_node_N (node_pointer_type current_block_cluster_node, std::vector< node_pointer_type > & leaf_set_wrt_current_node) private
Perform a recursive non-tensor product type fine partition of \(\mathcal{M}_{\mathcal{N},k}\) type by starting from a block cluster node in the tree.
No admissibility condition is enabled in this situation, because the two comprising cluster trees are built from pure cardinality based partition.
Reference: Section 5 in Hackbusch, W. 1999. A Sparse Matrix Arithmetic Based on H-Matrices. Part I: Introduction to H-Matrices. Computing 62 (2): 89108.
Parameters
current_block_cluster_node
leaf_set_wrt_current_node
Push back the current cluster node, which is small, to the leaf set and set its split mode as UnsplitMode.
Make sure that the two clusters \(\tau\) and \(\sigma\) have the same level in their respective cluster trees, i.e. level preserving property should be satisfied.
Create a new block cluster node as child. Then append this new node as one of the children of the current block cluster node. Finally, recursively partition from this node if it is on the bottom left corner, i.e. it is the \(I_2 \times I_1\) block cluster; otherwise, for \(I_1 \times I_1\), \(I_1 \times I_2\) and \(I_2 \times I_2\), stop the recursion and directly add them to the leaf set.
Append this new node as one of the children of the current block cluster node.
Handle the case for \(I_2 \times I_1\) and perform the \(\mathcal{N}\)-type recursive partition.
Merge the leaf set wrt. the child block cluster node into the leaf set of the current block cluster node.
Handle the case for \(I_1 \times I_1\), \(I_1 \times I_2\) and \(I_2 \times I_2\). Because the recursion stops here, we need to check and update its near field property.
Make sure the current block cluster have four children, which is ensured by the fine non-tensor product \(\mathcal{N}\)-type construction.
Note
The second argument BlockClusterTree<spacedim, Number>::child_num should be wrapped between the brackets, otherwise, the program cannot be compiled.
Set the split mode of the current block cluster node as cross.
Definition at line 2587 of file block_cluster_tree.h.
References TreeNode< T, N >::get_data_pointer(), and TreeNode< T, N >::set_split_mode().
partition_fine_non_tensor_product_from_block_cluster_node_Nstar()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition_fine_non_tensor_product_from_block_cluster_node_Nstar (node_pointer_type current_block_cluster_node, std::vector< node_pointer_type > & leaf_set_wrt_current_node) private
Perform a recursive non-tensor product type fine partition of \(\mathcal{M}_{\mathcal{N}^*,k}\) type by starting from a block cluster node in the tree.
No admissibility condition is enabled in this situation, because the two comprising cluster trees are built from pure cardinality based partition.
Reference: Section 5 in Hackbusch, W. 1999. A Sparse Matrix Arithmetic Based on H-Matrices. Part I: Introduction to H-Matrices. Computing 62 (2): 89108.
Parameters
current_block_cluster_node
leaf_set_wrt_current_node
Push back the current cluster node, which is small, to the leaf set and set its split mode as UnsplitMode.
Make sure that the two clusters \(\tau\) and \(\sigma\) have the same level in their respective cluster trees, i.e. level preserving property should be satisfied.
Create a new block cluster node as child. Then append this new node as one of the children of the current block cluster node. Finally, recursively partition from this node if it is on the top right corner, i.e. it is the \(I_1 \times I_2\) block cluster; otherwise, for \(I_1 \times I_1\), \(I_2 \times I_1\) and \(I_2 \times I_2\), stop the recursion and directly add them to the leaf set.
Append this new node as one of the children of the current block cluster node.
Handle the case for \(I_1 \times I_2\) and perform the \(\mathcal{N}^*\)-type recursive partition.
Merge the leaf set wrt. the child block cluster node into the leaf set of the current block cluster node.
Handle the case for \(I_1 \times I_1\), \(I_2 \times I_1\) and \(I_2 \times I_2\). Because the recursion stops here, we need to check and update its near field property.
Make sure the current block cluster have four children, which is ensured by the fine non-tensor product \(\mathcal{N}^*\)-type construction.
Note
The second argument BlockClusterTree<spacedim, Number>::child_num should be wrapped between the brackets, otherwise, the program cannot be compiled.
Set the split mode of the current block cluster node as cross.
Definition at line 2732 of file block_cluster_tree.h.
References TreeNode< T, N >::get_data_pointer(), and TreeNode< T, N >::set_split_mode().
partition_from_block_cluster_node() [1/4]
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition_from_block_cluster_node (node_pointer_type current_block_cluster_node, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > & all_support_points, const std::vector< Number > & cell_size_at_dofs, std::vector< node_pointer_type > & leaf_set_wrt_current_node) private
Perform a recursive partition by starting from a block cluster node in the tree.
N.B. The evaluation of the admissibility condition has the mesh cell size correction.
Note
The index sets held by the two clusters share a same external DoF numbering.
Parameters
current_block_cluster_node
internal_to_external_dof_numbering
all_support_points
cell_size_at_dofs
leaf_set_wrt_current_node
Push back the current cluster node, which is small, to the leaf set and set its split mode as UnsplitMode.
Make sure that the two clusters \(\tau\) and \(\sigma\) have the same level in their respective cluster trees, i.e. level preserving property should be satisfied.
Create a new block cluster node as child and recursively partition from it.
Append this new node as one of the children of the current block cluster node.
Merge the leaf set wrt. the child block cluster node into the leaf set of the current block cluster node.
Make sure the current block cluster have four children, which is ensured by the tensor product construction.
Note
The second argument BlockClusterTree<spacedim, Number>::child_num should be wrapped between the brackets, otherwise, the program cannot be compiled.
Set the split mode of the current block cluster node as cross.
Definition at line 3147 of file block_cluster_tree.h.
References TreeNode< T, N >::get_data_pointer(), and TreeNode< T, N >::set_split_mode().
partition_from_block_cluster_node() [2/4]
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition_from_block_cluster_node (node_pointer_type current_block_cluster_node, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > & all_support_points, std::vector< node_pointer_type > & leaf_set_wrt_current_node) private
Perform a recursive partition by starting from a block cluster node in the tree.
N.B. The evaluation of the admissibility condition has no mesh cell size correction.
Note
The index sets held by the two clusters share a same external DoF numbering.
The algorithm performs an iteration over all the children of the current block cluster \(b = \tau \times \sigma\). Because the map \(S\) for generating the children of \(b\) is realized from a tensor product of the children of \(\tau\) and \(\sigma\), the algorithm contains nested double loops.
Parameters
current_block_cluster_node The pointer to the block cluster node in the tree, from which the admissible partition will be performed.
internal_to_external_dof_numbering
all_support_points Spatial coordinates for all the support points.
leaf_set A list of block cluster node pointers which comprise the leaf set with respect to current_block_cluster_node.
Push back the current cluster node, which is small, to the leaf set and set its split mode as UnsplitMode.
Make sure that the two clusters \(\tau\) and \(\sigma\) have the same level in their respective cluster trees, i.e. level preserving property should be satisfied.
Create a new block cluster node as child and recursively partition from it.
Append this new node as one of the children of the current block cluster node.
Update the total number of nodes in the tree.
Merge the leaf set wrt. the child block cluster node into the leaf set of the current block cluster node.
Make sure the current block cluster have four children, which is ensured by the tensor product construction.
Note
The second argument BlockClusterTree<spacedim, Number>::child_num should be wrapped between the brackets, otherwise, the program cannot be compiled.
Set the split mode of the current block cluster node as cross.
Definition at line 2877 of file block_cluster_tree.h.
References TreeNode< T, N >::get_data_pointer(), and TreeNode< T, N >::set_split_mode().
partition_from_block_cluster_node() [3/4]
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition_from_block_cluster_node (node_pointer_type current_block_cluster_node, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering_I, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering_J, const std::vector< Point< spacedim, Number > > & all_support_points_in_I, const std::vector< Point< spacedim, Number > > & all_support_points_in_J, const std::vector< Number > & cell_size_at_dofs_in_I, const std::vector< Number > & cell_size_at_dofs_in_J, std::vector< node_pointer_type > & leaf_set_wrt_current_node) private
Perform a recursive partition by starting from a block cluster node in the tree.
N.B. The evaluation of the admissibility condition has the mesh cell size correction.
Note
The index sets inferred from the index ranges held by the two clusters share a same internal DoF numbering, which need to be mapped to the external numbering for accessing the list of support point coordinates.
Parameters
current_block_cluster_node
internal_to_external_dof_numbering_I
internal_to_external_dof_numbering_J
all_support_points_in_I
all_support_points_in_J
cell_size_at_dofs_in_I
cell_size_at_dofs_in_J
leaf_set_wrt_current_node
Push back the current cluster node, which is small, to the leaf set and set its split mode as UnsplitMode.
Make sure that the two clusters \(\tau\) and \(\sigma\) have the same level in their respective cluster trees, i.e. level preserving property should be satisfied.
Create a new block cluster node as child and recursively partition from it.
Append this new node as one of the children of the current block cluster node.
Merge the leaf set wrt. the child block cluster node into the leaf set of the current block cluster node.
Make sure the current block cluster have four children, which is ensured by the tensor product construction.
Note
The second argument BlockClusterTree<spacedim, Number>::child_num should be wrapped between the brackets, otherwise, the program cannot be compiled.
Set the split mode of the current block cluster node as cross.
Definition at line 3283 of file block_cluster_tree.h.
References TreeNode< T, N >::get_data_pointer(), and TreeNode< T, N >::set_split_mode().
partition_from_block_cluster_node() [4/4]
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition_from_block_cluster_node (node_pointer_type current_block_cluster_node, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering_I, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering_J, const std::vector< Point< spacedim, Number > > & all_support_points_in_I, const std::vector< Point< spacedim, Number > > & all_support_points_in_J, std::vector< node_pointer_type > & leaf_set_wrt_current_node) private
Perform a recursive partition by starting from a block cluster node in the tree.
N.B. The evaluation of the admissibility condition has no mesh cell size correction.
Note
The index sets inferred from the index ranges held by the two clusters share a same internal DoF numbering, which need to be mapped to the external numbering for accessing the list of support point coordinates.
Parameters
current_block_cluster_node
internal_to_external_dof_numbering_I
internal_to_external_dof_numbering_J
all_support_points_in_I
all_support_points_in_J
leaf_set_wrt_current_node
Push back the current cluster node, which is small, to the leaf set and set its split mode as UnsplitMode.
Make sure that the two clusters \(\tau\) and \(\sigma\) have the same level in their respective cluster trees, i.e. level preserving property should be satisfied.
Create a new block cluster node as child and recursively partition from it.
Append this new node as one of the children of the current block cluster node.
Update the total number of nodes in the tree.
Merge the leaf set wrt. the child block cluster node into the leaf set of the current block cluster node.
Make sure the current block cluster have four children, which is ensured by the tensor product construction.
Note
The second argument BlockClusterTree<spacedim, Number>::child_num should be wrapped between the brackets, otherwise, the program cannot be compiled.
Set the split mode of the current block cluster node as cross.
Definition at line 3007 of file block_cluster_tree.h.
References TreeNode< T, N >::get_data_pointer(), and TreeNode< T, N >::set_split_mode().
partition_tensor_product()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition_tensor_product
Perform a recursive partition in tensor product form without the admissibility condition because the two comprising cluster trees are built from pure cardinality based partition.
Definition at line 1613 of file block_cluster_tree.h.
partition_tensor_product_from_block_cluster_node()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::partition_tensor_product_from_block_cluster_node (node_pointer_type current_block_cluster_node, std::vector< node_pointer_type > & leaf_set_wrt_current_node) private
Perform a recursive tensor product type partition by starting from a block cluster node in the tree.
No admissibility condition is enabled in this situation, because the two comprising cluster trees are built from pure cardinality based partition.
Parameters
current_block_cluster_node
leaf_set_wrt_current_node
Push back the current cluster node, which is small, to the leaf set and set its split mode as UnsplitMode.
Make sure that the two clusters \(\tau\) and \(\sigma\) have the same level in their respective cluster trees, i.e. level preserving property should be satisfied.
Create a new block cluster node as child and recursively partition from it.
Append this new node as one of the children of the current block cluster node.
Merge the leaf set wrt. the child block cluster node into the leaf set of the current block cluster node.
Make sure the current block cluster have four children, which is ensured by the tensor product construction.
Note
The second argument BlockClusterTree<spacedim, Number>::child_num should be wrapped between the brackets, otherwise, the program cannot be compiled.
Set the split mode of the current block cluster node as cross.
Definition at line 2135 of file block_cluster_tree.h.
References TreeNode< T, N >::get_data_pointer(), and TreeNode< T, N >::set_split_mode().
print_bct_info_as_dot()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::print_bct_info_as_dot (std::ostream & out) const
Print the block cluster tree hierarchy information as directional graph in Graphviz dot format.
Parameters
out
Write the header of the Graphviz dot file.
Define the node style.
Add comment nodes.
Finalize the Graphviz dot file.
Definition at line 3904 of file block_cluster_tree.h.
References print_block_cluster_node_info_as_dot_node().
prune_descendants_from_node()
template<int spacedim, typename Number > bool BlockClusterTree< spacedim, Number >::prune_descendants_from_node (node_pointer_type bc_node)
Prune the descendants of the given block cluster node.
Parameters
bc_node
Returns
Whether the block cluster tree is really pruned.
Delete the subtree emanating from each child node of the current block cluster node in the partition.
Update the block cluster node status including number of children and split mode.
Definition at line 2055 of file block_cluster_tree.h.
References CountTreeNodes(), DeleteTree(), TreeNode< T, N >::get_child_num(), TreeNode< T, N >::get_child_pointer(), TreeNode< T, N >::set_child_num(), TreeNode< T, N >::set_child_pointer(), and TreeNode< T, N >::set_split_mode().
Referenced by prune_to_partition_recursion().
prune_to_partition()
template<int spacedim, typename Number > bool BlockClusterTree< spacedim, Number >::prune_to_partition (const std::vector< node_pointer_type > & partition, const bool is_partition_in_bct)
Prune all those block cluster nodes which are descendants of the block cluster nodes in the given partition.
Parameters
partition
is_partition_in_bct Whether the block cluster nodes in the given partition are contained in this block cluster tree.
If the block cluster nodes in the given partition are contained in this block cluster tree, we directly prune their descendants.
Definition at line 2092 of file block_cluster_tree.h.
References prune_to_partition_recursion().
Referenced by HMatrix< spacedim, Number >::convert_between_different_block_cluster_trees().
release()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::release
Release the memory of the block cluster tree.
Definition at line 1589 of file block_cluster_tree.h.
References DeleteTree().
set_node_num()
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::set_node_num (unsigned int node_num) inline
Set the total number of nodes in the tree.
Definition at line 4006 of file block_cluster_tree.h.
write_leaf_set() [1/2]
template<int spacedim, typename Number > void BlockClusterTree< spacedim, Number >::write_leaf_set (std::ostream & out) const
Write formatted leaf set to the output stream.
Each leaf node is written in the following format:
‍
[index-range-in-cluster-tau],[index-range-in-cluster-sigma],is_near_field
For example,
‍[0 15),[15 20),1
Parameters
out
Print index range of cluster \(\tau\).
Print index range of cluster \(\sigma\).
Print the is_near_field flag.
Definition at line 3796 of file block_cluster_tree.h.
write_leaf_set() [2/2]
template<int spacedim, typename Number > template<typename Number1 > void BlockClusterTree< spacedim, Number >::write_leaf_set (std::ostream & out, const LAPACKFullMatrixExt< Number1 > & matrix, const Number1 singular_value_threshold = 0.) const
Write formatted leaf set to the output stream as well as the rank of each matrix block.
Each leaf node is written in the following format:
‍
[index-range-in-cluster-tau],[index-range-in-cluster-sigma],is_near_field,rank
For example,
‍[0 15),[15 20),1,1
Parameters
out
Print index range of cluster \(\tau\).
Print index range of cluster \(\sigma\).
Print the is_near_field flag.
Make a local copy of the matrix block and calculate its rank using SVD.
Print the rank flag.
Definition at line 3838 of file block_cluster_tree.h.
Friends And Related Function Documentation
operator<<
template<int spacedim, typename Number = double> template<int spacedim1, typename Number1 > std::ostream & operator<< (std::ostream & out, const BlockClusterTree< spacedim1, Number1 > & block_cluster_tree) friend
Print a whole block cluster tree using recursion.
Parameters
out
block_cluster_tree
Returns
Member Data Documentation
child_num
template<int spacedim, typename Number = double> const unsigned int BlockClusterTree< spacedim, Number >::child_num = 4 inline static
Number of children in a block cluster tree.
At present, only quad-tree is allowed.
Definition at line 56 of file block_cluster_tree.h.
depth
template<int spacedim, typename Number = double> unsigned int BlockClusterTree< spacedim, Number >::depth private
Depth of the tree, which is the maximum level plus one.
Note
The level number starts from 0, which is assigned to the root node. This definition of the block cluster tree depth is one more than the definition in
Definition at line 893 of file block_cluster_tree.h.
Referenced by BlockClusterTree< spacedim, Number >::operator=().
eta
template<int spacedim, typename Number = double> Number BlockClusterTree< spacedim, Number >::eta private
Definition at line 884 of file block_cluster_tree.h.
far_field_set
template<int spacedim, typename Number = double> std::vector<node_pointer_type> BlockClusterTree< spacedim, Number >::far_field_set private
Definition at line 882 of file block_cluster_tree.h.
is_subtree
template<int spacedim, typename Number = double> bool BlockClusterTree< spacedim, Number >::is_subtree private
Whether the current block cluster tree is a subtree of an existing tree.
Definition at line 908 of file block_cluster_tree.h.
leaf_set
template<int spacedim, typename Number = double> std::vector<node_pointer_type> BlockClusterTree< spacedim, Number >::leaf_set private
Definition at line 880 of file block_cluster_tree.h.
max_level
template<int spacedim, typename Number = double> int BlockClusterTree< spacedim, Number >::max_level private
Maximum node level in the tree, which is depth - 1.
Definition at line 898 of file block_cluster_tree.h.
Referenced by BlockClusterTree< spacedim, Number >::operator=().
n_min
template<int spacedim, typename Number = double> unsigned int BlockClusterTree< spacedim, Number >::n_min private
Definition at line 883 of file block_cluster_tree.h.
near_field_set
template<int spacedim, typename Number = double> std::vector<node_pointer_type> BlockClusterTree< spacedim, Number >::near_field_set private
Definition at line 881 of file block_cluster_tree.h.
node_num
template<int spacedim, typename Number = double> unsigned int BlockClusterTree< spacedim, Number >::node_num private
Total number of block clusters in the tree.
Definition at line 903 of file block_cluster_tree.h.
Referenced by BlockClusterTree< spacedim, Number >::BlockClusterTree(), and BlockClusterTree< spacedim, Number >::operator=().
root_node
template<int spacedim, typename Number = double> node_pointer_type BlockClusterTree< spacedim, Number >::root_node private
Definition at line 879 of file block_cluster_tree.h.
The documentation for this class was generated from the following file:
include/cluster_tree/block_cluster_tree.h