HierBEM: BEMValues< dim, spacedim, RangeNumberType > Class Template Reference
BEMValues< dim, spacedim, RangeNumberType > Class Template Reference
Public Types
using FE_Poly_short = FE_Poly< dim, spacedim >
Public Member Functions
BEMValues (const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe, const std::vector< MappingInfo< dim, spacedim > * > &mappings, const QGauss< dim *2 > &quad_rule_for_same_panel, const QGauss< dim *2 > &quad_rule_for_common_edge, const QGauss< dim *2 > &quad_rule_for_common_vertex, const QGauss< dim *2 > &quad_rule_for_regular)
BEMValues (const BEMValues< dim, spacedim, RangeNumberType > &bem_values)=delete
void shape_function_values_same_panel ()
void shape_function_values_common_edge ()
void shape_function_values_common_vertex ()
void shape_function_values_regular ()
void fill_shape_function_value_tables ()
Public Attributes
const FiniteElement< dim, spacedim > & kx_fe
const FiniteElement< dim, spacedim > & ky_fe
const std::vector< MappingInfo< dim, spacedim > * > & mappings
const QGauss< 4 > & quad_rule_for_same_panel
const QGauss< 4 > & quad_rule_for_common_edge
const QGauss< 4 > & quad_rule_for_common_vertex
const QGauss< 4 > & quad_rule_for_regular
Table< 3, RangeNumberType > kx_shape_value_table_for_same_panel
Table< 3, RangeNumberType > ky_shape_value_table_for_same_panel
Table< 3, RangeNumberType > kx_shape_value_table_for_common_edge
Table< 3, RangeNumberType > ky_shape_value_table_for_common_edge
Table< 3, RangeNumberType > kx_shape_value_table_for_common_vertex
Table< 3, RangeNumberType > ky_shape_value_table_for_common_vertex
Table< 3, RangeNumberType > kx_shape_value_table_for_regular
Table< 3, RangeNumberType > ky_shape_value_table_for_regular
Table< 4, RangeNumberType > kx_mapping_shape_value_table_for_same_panel
Table< 4, RangeNumberType > ky_mapping_shape_value_table_for_same_panel
Table< 4, RangeNumberType > kx_mapping_shape_value_table_for_common_edge
Table< 4, RangeNumberType > ky_mapping_shape_value_table_for_common_edge
Table< 4, RangeNumberType > kx_mapping_shape_value_table_for_common_vertex
Table< 4, RangeNumberType > ky_mapping_shape_value_table_for_common_vertex
Table< 4, RangeNumberType > kx_mapping_shape_value_table_for_regular
Table< 4, RangeNumberType > ky_mapping_shape_value_table_for_regular
Table< 2, LAPACKFullMatrixExt< RangeNumberType > > kx_shape_grad_matrix_table_for_same_panel
Table< 2, LAPACKFullMatrixExt< RangeNumberType > > ky_shape_grad_matrix_table_for_same_panel
Table< 2, LAPACKFullMatrixExt< RangeNumberType > > kx_shape_grad_matrix_table_for_common_edge
Table< 2, LAPACKFullMatrixExt< RangeNumberType > > ky_shape_grad_matrix_table_for_common_edge
Table< 2, LAPACKFullMatrixExt< RangeNumberType > > kx_shape_grad_matrix_table_for_common_vertex
Table< 2, LAPACKFullMatrixExt< RangeNumberType > > ky_shape_grad_matrix_table_for_common_vertex
Table< 2, LAPACKFullMatrixExt< RangeNumberType > > kx_shape_grad_matrix_table_for_regular
Table< 2, LAPACKFullMatrixExt< RangeNumberType > > ky_shape_grad_matrix_table_for_regular
Table< 3, LAPACKFullMatrixExt< RangeNumberType > > kx_mapping_shape_grad_matrix_table_for_same_panel
Table< 3, LAPACKFullMatrixExt< RangeNumberType > > ky_mapping_shape_grad_matrix_table_for_same_panel
Table< 3, LAPACKFullMatrixExt< RangeNumberType > > kx_mapping_shape_grad_matrix_table_for_common_edge
Table< 3, LAPACKFullMatrixExt< RangeNumberType > > ky_mapping_shape_grad_matrix_table_for_common_edge
Table< 3, LAPACKFullMatrixExt< RangeNumberType > > kx_mapping_shape_grad_matrix_table_for_common_vertex
Table< 3, LAPACKFullMatrixExt< RangeNumberType > > ky_mapping_shape_grad_matrix_table_for_common_vertex
Table< 3, LAPACKFullMatrixExt< RangeNumberType > > kx_mapping_shape_grad_matrix_table_for_regular
Table< 3, LAPACKFullMatrixExt< RangeNumberType > > ky_mapping_shape_grad_matrix_table_for_regular
Protected Member Functions
void init_shape_value_tables ()
void init_mapping_shape_value_tables ()
void init_shape_grad_matrix_tables ()
void init_mapping_shape_grad_matrix_tables ()
void init_internal_matrix_in_mapping_shape_grad_matrix_table (Table< 3, LAPACKFullMatrixExt< RangeNumberType > > &table)
void resize_internal_data_in_mappings (const unsigned int n_q_points) const
Detailed Description
template<int dim, int spacedim, typename RangeNumberType = double>
class BEMValues< dim, spacedim, RangeNumberType >
Values related to a pair of cells (panels) used in Galerkin BEM, which can be considered as a counterpart of the FEValues for FEM in deal.ii.
Note
The values encapsulated in BEMValues are shape functions value and their gradient values at each quadrature point, as well as Sauter quadrature rules for different cell neighboring types. These values will be precalculated for improving the performance.
Definition at line 61 of file bem_values.hcu.
Member Typedef Documentation
FE_Poly_short
template<int dim, int spacedim, typename RangeNumberType = double> using BEMValues< dim, spacedim, RangeNumberType >::FE_Poly_short = FE_Poly<dim, spacedim>
Definition at line 64 of file bem_values.hcu.
Constructor & Destructor Documentation
BEMValues() [1/2]
template<int dim, int spacedim, typename RangeNumberType > BEMValues< dim, spacedim, RangeNumberType >::BEMValues (const FiniteElement< dim, spacedim > & kx_fe, const FiniteElement< dim, spacedim > & ky_fe, const std::vector< MappingInfo< dim, spacedim > * > & mappings, const QGauss< dim *2 > & quad_rule_for_same_panel, const QGauss< dim *2 > & quad_rule_for_common_edge, const QGauss< dim *2 > & quad_rule_for_common_vertex, const QGauss< dim *2 > & quad_rule_for_regular)
Constructor
Note
N.B. There is no default constructor for the class BEMValues, because all the internal references to finite element objects and quadrature objects should be initialized once the BEMValues object is declared.
Parameters
kx_fe
ky_fe
quad_rule_for_same_panel
quad_rule_for_common_edge
quad_rule_for_common_vertex
quad_rule_for_regular
Definition at line 583 of file bem_values.hcu.
References BEMValues< dim, spacedim, RangeNumberType >::init_mapping_shape_grad_matrix_tables(), BEMValues< dim, spacedim, RangeNumberType >::init_mapping_shape_value_tables(), BEMValues< dim, spacedim, RangeNumberType >::init_shape_grad_matrix_tables(), and BEMValues< dim, spacedim, RangeNumberType >::init_shape_value_tables().
BEMValues() [2/2]
template<int dim, int spacedim, typename RangeNumberType = double> BEMValues< dim, spacedim, RangeNumberType >::BEMValues (const BEMValues< dim, spacedim, RangeNumberType > & bem_values) delete
Copy constructor is deleted, since some members in this class, such as finite elements, quadratures, mappings are references to external objects.
Member Function Documentation
fill_shape_function_value_tables()
template<int dim, int spacedim, typename RangeNumberType > void BEMValues< dim, spacedim, RangeNumberType >::fill_shape_function_value_tables
Fill the data tables for the values and derivatives of finite element shape functions and mapping object shape functions.
Definition at line 794 of file bem_values.hcu.
Referenced by fill_hmatrix_with_aca_plus_serial(), and fill_hmatrix_with_aca_plus_smp().
init_internal_matrix_in_mapping_shape_grad_matrix_table()
template<int dim, int spacedim, typename RangeNumberType > void BEMValues< dim, spacedim, RangeNumberType >::init_internal_matrix_in_mapping_shape_grad_matrix_table (Table< 3, LAPACKFullMatrixExt< RangeNumberType > > & table) protected
Initialize matrices storing the gradient values of shape functions in the mapping object.
Parameters
table
Definition at line 764 of file bem_values.hcu.
init_mapping_shape_grad_matrix_tables()
template<int dim, int spacedim, typename RangeNumberType > void BEMValues< dim, spacedim, RangeNumberType >::init_mapping_shape_grad_matrix_tables protected
Initialize the data tables for the gradient values of shape functions in the mapping object.
Definition at line 717 of file bem_values.hcu.
Referenced by BEMValues< dim, spacedim, RangeNumberType >::BEMValues().
init_mapping_shape_value_tables()
template<int dim, int spacedim, typename RangeNumberType > void BEMValues< dim, spacedim, RangeNumberType >::init_mapping_shape_value_tables protected
Initialize the data tables for the mapping shape function values.
Note
The number of mapping shape function in the highest order mapping object is used to initialize the second dimension of each data table.
Definition at line 634 of file bem_values.hcu.
Referenced by BEMValues< dim, spacedim, RangeNumberType >::BEMValues().
init_shape_grad_matrix_tables()
template<int dim, int spacedim, typename RangeNumberType > void BEMValues< dim, spacedim, RangeNumberType >::init_shape_grad_matrix_tables protected
Initialize the data tables for the gradient values of finite element shape functions.
Definition at line 691 of file bem_values.hcu.
Referenced by BEMValues< dim, spacedim, RangeNumberType >::BEMValues().
init_shape_value_tables()
template<int dim, int spacedim, typename RangeNumberType > void BEMValues< dim, spacedim, RangeNumberType >::init_shape_value_tables protected
Initialize the data tables for the finite element shape function values.
Definition at line 608 of file bem_values.hcu.
Referenced by BEMValues< dim, spacedim, RangeNumberType >::BEMValues().
resize_internal_data_in_mappings()
template<int dim, int spacedim, typename RangeNumberType > void BEMValues< dim, spacedim, RangeNumberType >::resize_internal_data_in_mappings (const unsigned int n_q_points) const protected
Resize the internal data in all orders of mappings.
Note
The InternalData within a MappingQ object is a temporary place holding the shape function values and their derivatives. Because deal.ii is an FEM library, which does not handle different \(k_3\) terms and cell neighboring types as in the Sauter quadrature used in BEM, whenever we come to a kind of cell neighboring type which has its associated quadrature object, we need to reinitialize the InternalData objects in all possible orders of mappings and then compute shape function values and their derivatives. After the computation, the values within InternalData will be copied into related data tables in BEMValues.
Precondition
Postcondition
Parameters
n_q_points
Definition at line 782 of file bem_values.hcu.
shape_function_values_common_edge()
template<int dim, int spacedim, typename RangeNumberType > void BEMValues< dim, spacedim, RangeNumberType >::shape_function_values_common_edge
Calculate the table storing shape function values and derivatives for both finite element and mapping objects at Sauter quadrature points for the common edge case.
Initialize the internal data in the mapping objects.
Quadrature points in the Sauter's parametric space.
Get the polynomial space inverse numbering for accessing the shape functions in the lexicographic order.
Here I have adopted an assumption that the finite elements are based on tensor product polynomials.
Quadrature points in the unit cells of \(K_x\) and \(K_y\) respectively.
Iterate over each finite element shape function in the lexicographic order on the unit cell of \(K_x\) and evaluate it at the current quadrature point kx_unit_quad_points[q].
Iterate over each finite element shape function in the lexicographic order on the unit cell of \(K_y\) and evaluate it at the current quadrature point ky_unit_quad_points[q].
Compute mapping shape function values and their derivatives in batch.
Even though the internally generated polynomials in the mapping object are in the tensor product order, the shape function values and derivatives are still in the hierarchic order. This can be verified by checking the source code of MappingQ<dim, spacedim>::InternalData::compute_shape_function_values. (see http://localhost/dealii-9.4.1-doc/mapping__q_8cc_source.html#l00271)
However, this behavior is different from the documentation for the function MappingQ< dim, spacedim >::InternalData::shape().
Definition at line 1020 of file bem_values.hcu.
shape_function_values_common_vertex()
template<int dim, int spacedim, typename RangeNumberType > void BEMValues< dim, spacedim, RangeNumberType >::shape_function_values_common_vertex
Calculate the table storing shape function values and derivatives for both finite element and mapping objects at Sauter quadrature points for the common vertex case.
Initialize the internal data in the mapping objects.
Quadrature points in the Sauter's parametric space.
Get the polynomial space inverse numbering for accessing the shape functions in the lexicographic order.
Here I have adopted an assumption that the finite elements are based on tensor product polynomials.
Quadrature points in the unit cells of \(K_x\) and \(K_y\) respectively.
Iterate over each finite element shape function in the lexicographic order on the unit cell of \(K_x\) and evaluate it at the current quadrature point kx_unit_quad_points[q].
Iterate over each finite element shape function in the lexicographic order on the unit cell of \(K_y\) and evaluate it at the current quadrature point ky_unit_quad_points[q].
Compute mapping shape function values and their derivatives in batch.
Even though the internally generated polynomials in the mapping object are in the tensor product order, the shape function values and derivatives are still in the hierarchic order. This can be verified by checking the source code of MappingQ<dim, spacedim>::InternalData::compute_shape_function_values. (see http://localhost/dealii-9.4.1-doc/mapping__q_8cc_source.html#l00271)
However, this behavior is different from the documentation for the function MappingQ< dim, spacedim >::InternalData::shape().
Definition at line 1237 of file bem_values.hcu.
shape_function_values_regular()
template<int dim, int spacedim, typename RangeNumberType > void BEMValues< dim, spacedim, RangeNumberType >::shape_function_values_regular
Calculate the table storing shape function values and derivatives for both finite element and mapping objects at Sauter quadrature points for the regular case.
Initialize the internal data in the mapping objects.
Quadrature points in the Sauter's parametric space.
Get the polynomial space inverse numbering for accessing the shape functions in the lexicographic order.
Here I have adopted an assumption that the finite elements are based on tensor product polynomials.
Quadrature points in the unit cells of \(K_x\) and \(K_y\) respectively.
Iterate over each finite element shape function in the lexicographic order on the unit cell of \(K_x\) and evaluate it at the current quadrature point kx_unit_quad_points[q].
Iterate over each finite element shape function in the lexicographic order on the unit cell of \(K_y\) and evaluate it at the current quadrature point ky_unit_quad_points[q].
Compute mapping shape function values and their derivatives in batch.
Even though the internally generated polynomials in the mapping object are in the tensor product order, the shape function values and derivatives are still in the hierarchic order. This can be verified by checking the source code of MappingQ<dim, spacedim>::InternalData::compute_shape_function_values. (see http://localhost/dealii-9.4.1-doc/mapping__q_8cc_source.html#l00271)
However, this behavior is different from the documentation for the function MappingQ< dim, spacedim >::InternalData::shape().
Definition at line 1454 of file bem_values.hcu.
References sauter_regular_parametric_coords_to_unit_cells(), and BEMTools::shape_grad_matrix_in_lexicographic_order().
shape_function_values_same_panel()
template<int dim, int spacedim, typename RangeNumberType > void BEMValues< dim, spacedim, RangeNumberType >::shape_function_values_same_panel
Calculate the table storing shape function values and derivatives for both finite element and mapping objects at Sauter quadrature points for the same panel case.
Initialize the internal data in the mapping objects.
Quadrature points in the Sauter's parametric space.
Get the polynomial space inverse numbering for accessing the shape functions in the lexicographic order.
Here I have adopted an assumption that the finite elements are based on tensor product polynomials.
Quadrature points in the unit cells of \(K_x\) and \(K_y\) respectively.
Iterate over each finite element shape function in the lexicographic order on the unit cell of \(K_x\) and evaluate it at the current quadrature point kx_unit_quad_points[q].
Iterate over each finite element shape function in the lexicographic order on the unit cell of \(K_y\) and evaluate it at the current quadrature point ky_unit_quad_points[q].
Compute mapping shape function values and their derivatives in batch.
Even though the internally generated polynomials in the mapping object are in the tensor product order, the shape function values and derivatives within InternalData are still stored in the hierarchic order. This can be verified by checking the source code of MappingQ<dim, spacedim>::InternalData::compute_shape_function_values. (see http://localhost/dealii-9.4.1-doc/mapping__q_8cc_source.html#l00271)
However, this behavior is different from the documentation for the function MappingQ< dim, spacedim >::InternalData::shape().
Definition at line 805 of file bem_values.hcu.
Member Data Documentation
kx_fe
template<int dim, int spacedim, typename RangeNumberType = double> const FiniteElement<dim, spacedim>& BEMValues< dim, spacedim, RangeNumberType >::kx_fe
Reference to finite element on the field cell \(K_x\).
Definition at line 137 of file bem_values.hcu.
kx_mapping_shape_grad_matrix_table_for_common_edge
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::kx_mapping_shape_grad_matrix_table_for_common_edge
Data table of mapping shape function's gradient values for \(K_x\) in the common edge case. It has 3 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
\(k_3\) term index: size=6
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(MappingQ::InternalData.n_shape_functions*dim\).
Definition at line 446 of file bem_values.hcu.
kx_mapping_shape_grad_matrix_table_for_common_vertex
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::kx_mapping_shape_grad_matrix_table_for_common_vertex
Data table of mapping shape function's gradient values for \(K_x\) in the common vertex case. It has 3 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
\(k_3\) term index: size=4
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(MappingQ::InternalData.n_shape_functions*dim\).
Definition at line 472 of file bem_values.hcu.
kx_mapping_shape_grad_matrix_table_for_regular
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::kx_mapping_shape_grad_matrix_table_for_regular
Data table of mapping shape function's gradient values for \(K_x\) in the regular case. It has 3 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
\(k_3\) term index: size=1
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(MappingQ::InternalData.n_shape_functions*dim\).
Definition at line 498 of file bem_values.hcu.
kx_mapping_shape_grad_matrix_table_for_same_panel
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::kx_mapping_shape_grad_matrix_table_for_same_panel
Data table of mapping shape function's gradient values for \(K_x\) in the same panel case. It has 3 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
\(k_3\) term index: size=8
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(MappingQ::InternalData.n_shape_functions*dim\).
Definition at line 420 of file bem_values.hcu.
kx_mapping_shape_value_table_for_common_edge
template<int dim, int spacedim, typename RangeNumberType = double> Table<4, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::kx_mapping_shape_value_table_for_common_edge
Data table of mapping shape function values for \(K_x\) in the common edge case. It has 4 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
Shape function index: size=number of shape functions in the highest order mapping object
\(k_3\) term index: size=6
Quadrature point index: size=number of quadrature points
Definition at line 266 of file bem_values.hcu.
kx_mapping_shape_value_table_for_common_vertex
template<int dim, int spacedim, typename RangeNumberType = double> Table<4, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::kx_mapping_shape_value_table_for_common_vertex
Data table of mapping shape function values for \(K_x\) in the common vertex case. It has 4 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
Shape function index: size=number of shape functions in the highest order mapping object
\(k_3\) term index: size=4
Quadrature point index: size=number of quadrature points
Definition at line 290 of file bem_values.hcu.
kx_mapping_shape_value_table_for_regular
template<int dim, int spacedim, typename RangeNumberType = double> Table<4, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::kx_mapping_shape_value_table_for_regular
Data table of mapping shape function values for \(K_x\) in the regular case. It has 4 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
Shape function index: size=number of shape functions in the highest order mapping object
\(k_3\) term index: size=1
Quadrature point index: size=number of quadrature points
Definition at line 314 of file bem_values.hcu.
kx_mapping_shape_value_table_for_same_panel
template<int dim, int spacedim, typename RangeNumberType = double> Table<4, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::kx_mapping_shape_value_table_for_same_panel
Data table of mapping shape function values for \(K_x\) in the same panel case. It has 4 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
Shape function index: size=number of shape functions in the highest order mapping object
\(k_3\) term index: size=8
Quadrature point index: size=number of quadrature points
Definition at line 242 of file bem_values.hcu.
kx_shape_grad_matrix_table_for_common_edge
template<int dim, int spacedim, typename RangeNumberType = double> Table<2, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::kx_shape_grad_matrix_table_for_common_edge
Data table of finite element shape function's gradient values for \(K_x\) in the common edge case. It has two dimensions:
\(k_3\) term index: size=6
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(dofs_per_cell*dim\).
Definition at line 357 of file bem_values.hcu.
kx_shape_grad_matrix_table_for_common_vertex
template<int dim, int spacedim, typename RangeNumberType = double> Table<2, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::kx_shape_grad_matrix_table_for_common_vertex
Data table of finite element shape function's gradient values for \(K_x\) in the common vertex case. It has two dimensions:
\(k_3\) term index: size=4
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(dofs_per_cell*dim\).
Definition at line 377 of file bem_values.hcu.
kx_shape_grad_matrix_table_for_regular
template<int dim, int spacedim, typename RangeNumberType = double> Table<2, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::kx_shape_grad_matrix_table_for_regular
Data table of finite element shape function's gradient values for \(K_x\) in the regular case. It has two dimensions:
\(k_3\) term index: size=1
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(dofs_per_cell*dim\).
Definition at line 397 of file bem_values.hcu.
kx_shape_grad_matrix_table_for_same_panel
template<int dim, int spacedim, typename RangeNumberType = double> Table<2, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::kx_shape_grad_matrix_table_for_same_panel
Data table of finite element shape function's gradient values for \(K_x\) in the same panel case. It has two dimensions:
\(k_3\) term index: size=8
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(dofs_per_cell*dim\).
Definition at line 337 of file bem_values.hcu.
kx_shape_value_table_for_common_edge
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::kx_shape_value_table_for_common_edge
Data table of finite element shape function values for \(K_x\) in the common edge case. It has three dimensions:
shape function index: size=dofs_per_cell
\(k_3\) term index: size=6
Quadrature point index: size=number of quadrature points
Definition at line 190 of file bem_values.hcu.
kx_shape_value_table_for_common_vertex
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::kx_shape_value_table_for_common_vertex
Data table of finite element shape function values for \(K_x\) in the common vertex case. It has three dimensions:
shape function index: size=dofs_per_cell
\(k_3\) term index: size=4
Quadrature point index: size=number of quadrature points
Definition at line 206 of file bem_values.hcu.
kx_shape_value_table_for_regular
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::kx_shape_value_table_for_regular
Data table of finite element shape function values for \(K_x\) in the regular case. It has three dimensions:
shape function index: size=dofs_per_cell
\(k_3\) term index: size=1
Quadrature point index: size=number of quadrature points
Definition at line 222 of file bem_values.hcu.
kx_shape_value_table_for_same_panel
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::kx_shape_value_table_for_same_panel
Data table of finite element shape function values for \(K_x\) in the same panel case. It has three dimensions:
shape function index: size=dofs_per_cell
\(k_3\) term index: size=8
Quadrature point index: size=number of quadrature points
Definition at line 174 of file bem_values.hcu.
ky_fe
template<int dim, int spacedim, typename RangeNumberType = double> const FiniteElement<dim, spacedim>& BEMValues< dim, spacedim, RangeNumberType >::ky_fe
Reference to finite element on the field cell \(K_y\).
Definition at line 141 of file bem_values.hcu.
ky_mapping_shape_grad_matrix_table_for_common_edge
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::ky_mapping_shape_grad_matrix_table_for_common_edge
Data table of mapping shape function's gradient values for \(K_y\) in the common edge case. It has 3 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
\(k_3\) term index: size=6
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(MappingQ::InternalData.n_shape_functions*dim\).
Definition at line 459 of file bem_values.hcu.
ky_mapping_shape_grad_matrix_table_for_common_vertex
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::ky_mapping_shape_grad_matrix_table_for_common_vertex
Data table of mapping shape function's gradient values for \(K_y\) in the common vertex case. It has 3 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
\(k_3\) term index: size=4
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(MappingQ::InternalData.n_shape_functions*dim\).
Definition at line 485 of file bem_values.hcu.
ky_mapping_shape_grad_matrix_table_for_regular
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::ky_mapping_shape_grad_matrix_table_for_regular
Data table of mapping shape function's gradient values for \(K_y\) in the regular case. It has 3 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
\(k_3\) term index: size=1
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(MappingQ::InternalData.n_shape_functions*dim\).
Definition at line 511 of file bem_values.hcu.
ky_mapping_shape_grad_matrix_table_for_same_panel
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::ky_mapping_shape_grad_matrix_table_for_same_panel
Data table of mapping shape function's gradient values for \(K_y\) in the same panel case. It has 3 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
\(k_3\) term index: size=8
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(MappingQ::InternalData.n_shape_functions*dim\).
Definition at line 433 of file bem_values.hcu.
ky_mapping_shape_value_table_for_common_edge
template<int dim, int spacedim, typename RangeNumberType = double> Table<4, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::ky_mapping_shape_value_table_for_common_edge
Data table of mapping shape function values for \(K_y\) in the common edge case. It has 4 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
Shape function index: size=number of shape functions in the highest order mapping object
\(k_3\) term index: size=6
Quadrature point index: size=number of quadrature points
Definition at line 278 of file bem_values.hcu.
ky_mapping_shape_value_table_for_common_vertex
template<int dim, int spacedim, typename RangeNumberType = double> Table<4, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::ky_mapping_shape_value_table_for_common_vertex
Data table of mapping shape function values for \(K_y\) in the common vertex case. It has 4 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
Shape function index: size=number of shape functions in the highest order mapping object
\(k_3\) term index: size=4
Quadrature point index: size=number of quadrature points
Definition at line 302 of file bem_values.hcu.
ky_mapping_shape_value_table_for_regular
template<int dim, int spacedim, typename RangeNumberType = double> Table<4, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::ky_mapping_shape_value_table_for_regular
Data table of mapping shape function values for \(K_y\) in the regular case. It has 4 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
Shape function index: size=number of shape functions in the highest order mapping object
\(k_3\) term index: size=1
Quadrature point index: size=number of quadrature points
Definition at line 326 of file bem_values.hcu.
ky_mapping_shape_value_table_for_same_panel
template<int dim, int spacedim, typename RangeNumberType = double> Table<4, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::ky_mapping_shape_value_table_for_same_panel
Data table of mapping shape function values for \(K_y\) in the same panel case. It has 4 dimensions:
Mapping index, which is mapping order minus 1. It is used to get the corresponding pointer to the MappingInfo object in BEMValues::mappings.
Shape function index: size=number of shape functions in the highest order mapping object
\(k_3\) term index: size=8
Quadrature point index: size=number of quadrature points
Definition at line 254 of file bem_values.hcu.
ky_shape_grad_matrix_table_for_common_edge
template<int dim, int spacedim, typename RangeNumberType = double> Table<2, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::ky_shape_grad_matrix_table_for_common_edge
Data table of finite element shape function's gradient values for \(K_y\) in the common edge case. It has two dimensions:
\(k_3\) term index: size=6
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(dofs_per_cell*dim\).
Definition at line 367 of file bem_values.hcu.
ky_shape_grad_matrix_table_for_common_vertex
template<int dim, int spacedim, typename RangeNumberType = double> Table<2, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::ky_shape_grad_matrix_table_for_common_vertex
Data table of finite element shape function's gradient values for \(K_y\) in the common vertex case. It has two dimensions:
\(k_3\) term index: size=4
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(dofs_per_cell*dim\).
Definition at line 387 of file bem_values.hcu.
ky_shape_grad_matrix_table_for_regular
template<int dim, int spacedim, typename RangeNumberType = double> Table<2, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::ky_shape_grad_matrix_table_for_regular
Data table of finite element shape function's gradient values for \(K_y\) in the regular case. It has two dimensions:
\(k_3\) term index: size=1
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(dofs_per_cell*dim\).
Definition at line 407 of file bem_values.hcu.
ky_shape_grad_matrix_table_for_same_panel
template<int dim, int spacedim, typename RangeNumberType = double> Table<2, LAPACKFullMatrixExt<RangeNumberType> > BEMValues< dim, spacedim, RangeNumberType >::ky_shape_grad_matrix_table_for_same_panel
Data table of finite element shape function's gradient values for \(K_y\) in the same panel case. It has two dimensions:
\(k_3\) term index: size=8
Quadrature point index: size=number of quadrature points N.B. Each data item in the table is itself a matrix with the dimension \(dofs_per_cell*dim\).
Definition at line 347 of file bem_values.hcu.
ky_shape_value_table_for_common_edge
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::ky_shape_value_table_for_common_edge
Data table of finite element shape function values for \(K_y\) in the common edge case. It has three dimensions:
shape function index: size=dofs_per_cell
\(k_3\) term index: size=6
Quadrature point index: size=number of quadrature points
Definition at line 198 of file bem_values.hcu.
ky_shape_value_table_for_common_vertex
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::ky_shape_value_table_for_common_vertex
Data table of finite element shape function values for \(K_y\) in the common vertex case. It has three dimensions:
shape function index: size=dofs_per_cell
\(k_3\) term index: size=4
Quadrature point index: size=number of quadrature points
Definition at line 214 of file bem_values.hcu.
ky_shape_value_table_for_regular
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::ky_shape_value_table_for_regular
Data table of finite element shape function values for \(K_y\) in the regular case. It has three dimensions:
shape function index: size=dofs_per_cell
\(k_3\) term index: size=1
Quadrature point index: size=number of quadrature points
Definition at line 230 of file bem_values.hcu.
ky_shape_value_table_for_same_panel
template<int dim, int spacedim, typename RangeNumberType = double> Table<3, RangeNumberType> BEMValues< dim, spacedim, RangeNumberType >::ky_shape_value_table_for_same_panel
Data table of finite element shape function values for \(K_y\) in the same panel case. It has three dimensions:
shape function index: size=dofs_per_cell
\(k_3\) term index: size=8
Quadrature point index: size=number of quadrature points
Definition at line 182 of file bem_values.hcu.
mappings
template<int dim, int spacedim, typename RangeNumberType = double> const std::vector<MappingInfo<dim, spacedim> *>& BEMValues< dim, spacedim, RangeNumberType >::mappings
Mappings of from smallest to maximum order.
Definition at line 145 of file bem_values.hcu.
Referenced by CUDAWrappers::SauterQuadratureTaskRingBuffer< capacity, dim, spacedim, RangeNumberType, KernelNumberType >::allocate(), and CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, CUDARangeNumberType, CUDAKernelNumberType >::SauterQuadratureTaskBufferForVector().
quad_rule_for_common_edge
template<int dim, int spacedim, typename RangeNumberType = double> const QGauss<4>& BEMValues< dim, spacedim, RangeNumberType >::quad_rule_for_common_edge
Reference to 4D Sauter quadrature rule for the case that \(K_x\) and \(K_y\) share a common edge.
Definition at line 155 of file bem_values.hcu.
Referenced by CUDAWrappers::KernelPulledbackToSauterSpace< dim, spacedim, KernelFunctionType, KernelNumberType >::value().
quad_rule_for_common_vertex
template<int dim, int spacedim, typename RangeNumberType = double> const QGauss<4>& BEMValues< dim, spacedim, RangeNumberType >::quad_rule_for_common_vertex
Reference to 4D Sauter quadrature rule for the case that \(K_x\) and \(K_y\) share a common vertex.
Definition at line 160 of file bem_values.hcu.
Referenced by CUDAWrappers::KernelPulledbackToSauterSpace< dim, spacedim, KernelFunctionType, KernelNumberType >::value().
quad_rule_for_regular
template<int dim, int spacedim, typename RangeNumberType = double> const QGauss<4>& BEMValues< dim, spacedim, RangeNumberType >::quad_rule_for_regular
Reference to 4D Sauter quadrature rule for the case that \(K_x\) and \(K_y\) are separated.
Definition at line 165 of file bem_values.hcu.
quad_rule_for_same_panel
template<int dim, int spacedim, typename RangeNumberType = double> const QGauss<4>& BEMValues< dim, spacedim, RangeNumberType >::quad_rule_for_same_panel
Reference to 4D Sauter quadrature rule for the case that \(K_x \equiv K_y\).
Definition at line 150 of file bem_values.hcu.
Referenced by CUDAWrappers::KernelPulledbackToSauterSpace< dim, spacedim, KernelFunctionType, KernelNumberType >::value().
The documentation for this class was generated from the following file:
include/bem/bem_values.hcu