HierBEM: HMatrixSymmPreconditioner< spacedim, Number > Class Template Reference
HMatrixSymmPreconditioner< spacedim, Number > Class Template Reference
Public Types
using real_type = typename numbers::NumberTraits< Number >::real_type
Public Types inherited from HMatrix< spacedim, double >
enum SpaceFillingCurveType
enum HilbertBlockType
using size_type = std::make_unsigned< types::blas_int >::type
using value_type = double
using real_type = typename numbers::NumberTraits< double >::real_type
using TaskNode = tbb::flow::continue_node< tbb::flow::continue_msg >
using TaskNodePtr = std::shared_ptr< TaskNode >
Public Member Functions
HMatrixSymmPreconditioner ()
HMatrixSymmPreconditioner (const BlockClusterTree< spacedim, real_type > &bct, const unsigned int fixed_rank_k=1)
HMatrixSymmPreconditioner (typename BlockClusterTree< spacedim, real_type >::node_const_pointer_type bc_node, const unsigned int fixed_rank_k=1)
HMatrixSymmPreconditioner (const BlockClusterTree< spacedim, real_type > &bct, const LAPACKFullMatrixExt< Number > &M, const unsigned int fixed_rank_k)
HMatrixSymmPreconditioner (const BlockClusterTree< spacedim, real_type > &bct, const LAPACKFullMatrixExt< Number > &M)
HMatrixSymmPreconditioner (typename BlockClusterTree< spacedim, real_type >::node_const_pointer_type bc_node, const LAPACKFullMatrixExt< Number > &M, const unsigned int fixed_rank_k)
HMatrixSymmPreconditioner (typename BlockClusterTree< spacedim, real_type >::node_const_pointer_type bc_node, const LAPACKFullMatrixExt< Number > &M)
HMatrixSymmPreconditioner (const HMatrixSymmPreconditioner< spacedim, Number > &H)
HMatrixSymmPreconditioner (HMatrixSymmPreconditioner< spacedim, Number > &&H) noexcept
HMatrixSymmPreconditioner< spacedim, Number > & operator= (const HMatrixSymmPreconditioner< spacedim, Number > &H)
HMatrixSymmPreconditioner< spacedim, Number > & operator= (HMatrixSymmPreconditioner< spacedim, Number > &&H) noexcept
HMatrixSymmPreconditioner (const HMatrix< spacedim, Number > &H)
HMatrixSymmPreconditioner (HMatrix< spacedim, Number > &&H) noexcept
HMatrixSymmPreconditioner< spacedim, Number > & operator= (const HMatrix< spacedim, Number > &H)
HMatrixSymmPreconditioner< spacedim, Number > & operator= (HMatrix< spacedim, Number > &&H) noexcept
virtual void vmult (Vector< Number > &y, const Vector< Number > &x) const
Public Member Functions inherited from HMatrix< spacedim, double >
HMatrix ()
HMatrix (const BlockClusterTree< spacedim, real_type > &bct, const unsigned int fixed_rank_k=1, const HMatrixSupport::Property property=HMatrixSupport::Property::general, const HMatrixSupport::BlockType block_type=HMatrixSupport::BlockType::undefined_block)
HMatrix (typename BlockClusterTree< spacedim, real_type >::node_const_pointer_type bc_node, const unsigned int fixed_rank_k=1, const HMatrixSupport::Property property=HMatrixSupport::Property::general, const HMatrixSupport::BlockType block_type=HMatrixSupport::BlockType::undefined_block)
HMatrix (const BlockClusterTree< spacedim, real_type > &bct, const LAPACKFullMatrixExt< double > &M, const unsigned int fixed_rank_k, const HMatrixSupport::BlockType block_type=HMatrixSupport::BlockType::diagonal_block)
HMatrix (const BlockClusterTree< spacedim, real_type > &bct, const LAPACKFullMatrixExt< double > &M, const HMatrixSupport::BlockType block_type=HMatrixSupport::BlockType::diagonal_block)
HMatrix (typename BlockClusterTree< spacedim, real_type >::node_const_pointer_type bc_node, const LAPACKFullMatrixExt< double > &M, const unsigned int fixed_rank_k, const HMatrixSupport::Property property=HMatrixSupport::Property::general, const HMatrixSupport::BlockType block_type=HMatrixSupport::BlockType::undefined_block)
HMatrix (typename BlockClusterTree< spacedim, real_type >::node_const_pointer_type bc_node, const LAPACKFullMatrixExt< double > &M, const HMatrixSupport::Property property=HMatrixSupport::Property::general, const HMatrixSupport::BlockType block_type=HMatrixSupport::BlockType::undefined_block)
HMatrix (typename BlockClusterTree< spacedim, real_type >::node_const_pointer_type bc_node, HMatrix< spacedim, double > &&H, const HMatrixSupport::Property property=HMatrixSupport::Property::general, const HMatrixSupport::BlockType block_type=HMatrixSupport::BlockType::undefined_block)
HMatrix (const BlockClusterTree< spacedim, real_type > &bct, HMatrix< spacedim, double > &&H, const HMatrixSupport::Property property=HMatrixSupport::Property::general, const HMatrixSupport::BlockType block_type=HMatrixSupport::BlockType::diagonal_block)
HMatrix (const HMatrix< spacedim, double > &H)
HMatrix (HMatrix< spacedim, double > &&H) noexcept
void reinit (const BlockClusterTree< spacedim, real_type > &bct, const unsigned int fixed_rank_k=1, const HMatrixSupport::Property property=HMatrixSupport::Property::general, const HMatrixSupport::BlockType block_type=HMatrixSupport::BlockType::diagonal_block)
void reinit (typename BlockClusterTree< spacedim, real_type >::node_const_pointer_type bc_node, const unsigned int fixed_rank_k=1, const HMatrixSupport::Property property=HMatrixSupport::Property::general, const HMatrixSupport::BlockType block_type=HMatrixSupport::BlockType::undefined_block)
HMatrix< spacedim, double > & operator= (HMatrix< spacedim, double > &&H) noexcept
HMatrix< spacedim, double > & operator= (const HMatrix< spacedim, double > &H)
void convertToFullMatrix (MatrixType &M) const
void release ()
void clear ()
void clear_hmat_node ()
void clear_lu_or_cholesky_task_nodes ()
void clear_lu_or_cholesky_task_nodes_in_hmat ()
~HMatrix ()
HMatrixType get_type () const
bool is_root () const
bool is_near_field () const
bool is_far_field () const
bool is_leaf () const
size_type get_m () const
unsigned int get_n_row_blocks () const
unsigned int get_n_col_blocks () const
HMatrixSupport::Property get_property () const
void set_current_matrix_property (const HMatrixSupport::Property property)
void set_current_matrix_property (const LAPACKFullMatrixExt< double > &M)
void set_property (const HMatrixSupport::Property property)
void set_property (const LAPACKFullMatrixExt< double > &M)
void set_current_matrix_state (const HMatrixSupport::State state)
HMatrixSupport::State get_state () const
void set_state (const HMatrixSupport::State state)
HMatrixSupport::BlockType get_block_type () const
void set_current_matrix_block_type (const HMatrixSupport::BlockType block_type)
void set_block_type (const HMatrixSupport::BlockType block_type)
size_type get_n () const
RkMatrix< double > * get_rkmatrix ()
const RkMatrix< double > * get_rkmatrix () const
void calc_rank_upper_bound_for_rkmatrices () const
LAPACKFullMatrixExt< double > * get_fullmatrix ()
const LAPACKFullMatrixExt< double > * get_fullmatrix () const
std::vector< HMatrix< spacedim, double > * > & get_submatrices ()
const std::vector< HMatrix< spacedim, double > * > & get_submatrices () const
void print_formatted (std::ostream &out, const unsigned int precision=3, const bool scientific=true, const unsigned int width=0, const char *zero_string=" ", const double denominator=1., const double threshold=0.) const
void print_matrix_info (std::ostream &out) const
void print_current_matrix_info (std::ostream &out) const
void print_matrix_info_as_dot (std::ostream &out)
void print_as_formatted_full_matrix (std::ostream &out, const std::string &name, const unsigned int precision=8, const bool scientific=true, const unsigned int width=0, const char *zero_string="0", const double denominator=1., const double threshold=0.) const
void print_leaf_set_info (std::ostream &out) const
void write_fullmatrix_leaf_node (std::ostream &out, const real_type singular_value_threshold=0.) const
void write_rkmatrix_leaf_node (std::ostream &out) const
void write_leaf_set (std::ostream &out, const real_type singular_value_threshold=0.) const
void write_leaf_set_by_iteration (std::ostream &out, const real_type singular_value_threshold=0.) const
HMatrix * find_row_diag_block_for_offdiag_block ()
HMatrix * find_col_diag_block_for_offdiag_block ()
void truncate_to_rank (size_type new_rank)
void truncate_to_rank_preserve_positive_definite (size_type new_rank, const bool is_only_handle_tril=true)
void truncate_to_rank_diag_preserve_positive_definite (size_type new_rank, const bool is_only_handle_tril=true)
void truncate_to_rank_off_diag_preserve_positive_definite (size_type new_rank, const bool is_compensate_diag_blocks=true)
void set_default_vmult_strategy ()
void set_vmult_strategy (std::unique_ptr< HMatrixVmultStrategy< spacedim, double > > strategy)
void vmult (Vector< double > &y, const Vector< double > &x, const HMatrixSupport::Property top_hmat_property) const
void vmult (Vector< double > &y, const Number2 alpha, const Vector< double > &x, const HMatrixSupport::Property top_hmat_property) const
void vmult (Vector< double > &y, const Vector< double > &x, const HMatrix< spacedim, double > &starting_hmat, const HMatrixSupport::Property top_hmat_property) const
void vmult (Vector< double > &y, const Number2 alpha, const Vector< double > &x, const HMatrix< spacedim, double > &starting_hmat, const HMatrixSupport::Property top_hmat_property) const
void vmult (Vector< double > &y, const Vector< double > &x) const
void vmult (Vector< double > &y, const Number2 alpha, const Vector< double > &x) const
void vmult_serial_iterative (const Number2 beta, Vector< double > &y, const Number3 alpha, const Vector< double > &x) const
void vmult_task_parallel (const Number2 beta, Vector< double > &y, const Number3 alpha, const Vector< double > &x) const
void vmult_add (Vector< double > &y, const Vector< double > &x) const
void vmult_add (Vector< double > &y, const Number2 alpha, const Vector< double > &x) const
void Tvmult (Vector< double > &y, const Vector< double > &x, const HMatrixSupport::Property top_hmat_property) const
void Tvmult (Vector< double > &y, const Number2 alpha, const Vector< double > &x, const HMatrixSupport::Property top_hmat_property) const
void Tvmult (Vector< double > &y, const Vector< double > &x, const HMatrix< spacedim, double > &starting_hmat, const HMatrixSupport::Property top_hmat_property) const
void Tvmult (Vector< double > &y, const Number2 alpha, const Vector< double > &x, const HMatrix< spacedim, double > &starting_hmat, const HMatrixSupport::Property top_hmat_property) const
void Tvmult (Vector< double > &y, const Vector< double > &x) const
void Tvmult (Vector< double > &y, const Number2 alpha, const Vector< double > &x) const
void Tvmult_serial_iterative (const Number2 beta, Vector< double > &y, const Number3 alpha, const Vector< double > &x) const
void Tvmult_task_parallel (const Number2 beta, Vector< double > &y, const Number3 alpha, const Vector< double > &x) const
void Tvmult_add (Vector< double > &y, const Vector< double > &x) const
void Tvmult_add (Vector< double > &y, const Number2 alpha, const Vector< double > &x) const
void Hvmult (Vector< double > &y, const Vector< double > &x, const HMatrixSupport::Property top_hmat_property) const
void Hvmult (Vector< double > &y, const Number2 alpha, const Vector< double > &x, const HMatrixSupport::Property top_hmat_property) const
void Hvmult (Vector< double > &y, const Vector< double > &x, const HMatrix< spacedim, double > &starting_hmat, const HMatrixSupport::Property top_hmat_property) const
void Hvmult (Vector< double > &y, const Number2 alpha, const Vector< double > &x, const HMatrix< spacedim, double > &starting_hmat, const HMatrixSupport::Property top_hmat_property) const
void Hvmult (Vector< double > &y, const Vector< double > &x) const
void Hvmult (Vector< double > &y, const Number2 alpha, const Vector< double > &x) const
void Hvmult_task_parallel (const Number2 beta, Vector< double > &y, const Number3 alpha, const Vector< double > &x) const
void Hvmult_serial_iterative (const Number2 beta, Vector< double > &y, const Number3 alpha, const Vector< double > &x) const
Calculate the top level \(\mathcal{H}\)-matrix/vector multiplication as \(y = \beta y + \alpha \cdot M^H \cdot x\) by iterating over the leaf set.
void Hvmult_add (Vector< double > &y, const Vector< double > &x) const
void Hvmult_add (Vector< double > &y, const Number2 alpha, const Vector< double > &x) const
void h_h_mmult_reduction ()
void h_h_mmult_horizontal_split (BlockClusterTree< spacedim, real_type > &bc_tree)
void h_h_mmult_vertical_split (BlockClusterTree< spacedim, real_type > &bc_tree)
void h_h_mmult_cross_split (BlockClusterTree< spacedim, real_type > &bc_tree)
void mmult (HMatrix< spacedim, double > &C, HMatrix< spacedim, double > &B, const BlockClusterTree< spacedim, real_type > &bct_a, const BlockClusterTree< spacedim, real_type > &bct_b, BlockClusterTree< spacedim, real_type > &bct_c, const unsigned int fixed_rank=1)
void mmult (HMatrix< spacedim, double > &C, HMatrix< spacedim, double > &B, const BlockClusterTree< spacedim, real_type > &bct_a, const BlockClusterTree< spacedim, real_type > &bct_b, BlockClusterTree< spacedim, real_type > &bct_c, const unsigned int fixed_rank, const bool adding)
void mmult_level_conserving (HMatrix< spacedim, double > &C, HMatrix< spacedim, double > &B, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
void mmult_level_conserving (HMatrix< spacedim, double > &C, const double alpha, HMatrix< spacedim, double > &B, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
void mmult_level_conserving_for_parallel_lu (HMatrix< spacedim, double > &C, const double alpha, HMatrix< spacedim, double > &B, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
void mTmult_level_conserving (HMatrix< spacedim, double > &C, HMatrix< spacedim, double > &B, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
void mTmult_level_conserving (HMatrix< spacedim, double > &C, const double alpha, HMatrix< spacedim, double > &B, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
void mTmult_level_conserving_for_parallel_cholesky (HMatrix< spacedim, double > &C, const double alpha, HMatrix< spacedim, double > &B, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
void Tmmult_level_conserving (HMatrix< spacedim, double > &C, HMatrix< spacedim, double > &B, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
void Tmmult_level_conserving (HMatrix< spacedim, double > &C, const double alpha, HMatrix< spacedim, double > &B, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
void add (HMatrix< spacedim, double > &C, const HMatrix< spacedim, double > &B, const size_type fixed_rank_k) const
void add (HMatrix< spacedim, double > &C, const double b, const HMatrix< spacedim, double > &B, const size_type fixed_rank_k) const
void add (const HMatrix< spacedim, double > &B, const size_type fixed_rank_k) const
void add (const double b, const HMatrix< spacedim, double > &B, const size_type fixed_rank_k) const
void add (const RkMatrix< double > &B, const std::array< types::global_dof_index, 2 > &B_row_index_range, const std::array< types::global_dof_index, 2 > &B_col_index_range, const size_type fixed_rank_k, const bool is_result_matrix_store_tril_only=false) const
void add (const double b, const RkMatrix< double > &B, const std::array< types::global_dof_index, 2 > &B_row_index_range, const std::array< types::global_dof_index, 2 > &B_col_index_range, const size_type fixed_rank_k, const bool is_result_matrix_store_tril_only=false) const
void add (const RkMatrix< double > &B, const size_type fixed_rank_k, const bool is_result_matrix_store_tril_only=false)
void add (const double b, const RkMatrix< double > &B, const size_type fixed_rank_k, const bool is_result_matrix_store_tril_only=false)
void add (HMatrix< spacedim, double > &C, const RkMatrix< double > &B, const size_type fixed_rank_k)
void add (HMatrix< spacedim, double > &C, const double b, const RkMatrix< double > &B, const size_type fixed_rank_k)
void add_for_parallel_lu_or_cholesky (const RkMatrix< double > &B, const std::array< types::global_dof_index, 2 > &B_row_index_range, const std::array< types::global_dof_index, 2 > &B_col_index_range, const size_type fixed_rank_k, const bool is_result_matrix_store_tril_only=false)
void add_for_parallel_lu_or_cholesky (const RkMatrix< double > &B, const size_type fixed_rank_k, const bool is_result_matrix_store_tril_only=false)
void addsym_diag (const LAPACKFullMatrixExt< double > &E)
void invert_by_gauss_elim (HMatrix< spacedim, double > &M_inv, const size_type fixed_rank_k)
void solve_by_forward_substitution (Vector< double > &b, const bool is_unit_diagonal=true) const
void solve_by_forward_substitution (Vector< double > &x, const Vector< double > &b, const bool is_unit_diagonal=true) const
void solve_by_forward_substitution (Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat, const bool is_unit_diagonal=true) const
void solve_by_forward_substitution (Vector< double > &x, const Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat, const bool is_unit_diagonal=true) const
void solve_by_forward_substitution_matrix_valued (HMatrix< spacedim, double > &X, HMatrix< spacedim, double > &Z, const unsigned int fixed_rank, const bool is_unit_diagonal=true) const
void solve_by_forward_substitution_matrix_valued (HMatrix< spacedim, double > &Z, const unsigned int fixed_rank, const bool is_unit_diagonal=true) const
void solve_cholesky_by_forward_substitution_matrix_valued (HMatrix< spacedim, double > &X, HMatrix< spacedim, double > &Z, const unsigned int fixed_rank) const
void solve_cholesky_by_forward_substitution_matrix_valued (HMatrix< spacedim, double > &Z, const unsigned int fixed_rank) const
void solve_transpose_by_forward_substitution (Vector< double > &b) const
void solve_transpose_by_forward_substitution (Vector< double > &x, const Vector< double > &b) const
void solve_transpose_by_forward_substitution (Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat) const
void solve_transpose_by_forward_substitution (Vector< double > &x, const Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat) const
void solve_transpose_by_forward_substitution_matrix_valued (HMatrix< spacedim, double > &X, HMatrix< spacedim, double > &Z, const unsigned int fixed_rank) const
void solve_transpose_by_forward_substitution_matrix_valued (HMatrix< spacedim, double > &Z, const unsigned int fixed_rank) const
void solve_cholesky_transpose_by_forward_substitution_matrix_valued (HMatrix< spacedim, double > &X, HMatrix< spacedim, double > &Z, const unsigned int fixed_rank) const
void solve_cholesky_transpose_by_forward_substitution_matrix_valued (HMatrix< spacedim, double > &Z, const unsigned int fixed_rank) const
void solve_block_triangular_by_forward_substitution (Vector< double > &b, const bool is_unit_block_diagonal=true) const
void solve_block_triangular_by_forward_substitution (Vector< double > &x, const Vector< double > &b, const bool is_unit_block_diagonal=true) const
void solve_block_triangular_by_forward_substitution (Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat, const bool is_unit_block_diagonal=true) const
void solve_block_triangular_by_forward_substitution (Vector< double > &x, const Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat, const bool is_unit_block_diagonal=true) const
void solve_cholesky_by_forward_substitution (Vector< double > &b) const
void solve_cholesky_by_forward_substitution (Vector< double > &x, const Vector< double > &b) const
void solve_cholesky_by_forward_substitution (Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat) const
void solve_cholesky_by_forward_substitution (Vector< double > &x, const Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat) const
void solve_by_backward_substitution (Vector< double > &b, const bool is_unit_diagonal=false) const
void solve_by_backward_substitution (Vector< double > &x, const Vector< double > &b, const bool is_unit_diagonal=false) const
void solve_by_backward_substitution (Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat, const bool is_unit_diagonal=false) const
void solve_by_backward_substitution (Vector< double > &x, const Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat, const bool is_unit_diagonal=false) const
void solve_block_triangular_by_backward_substitution (Vector< double > &b, const bool is_unit_block_diagonal=false) const
void solve_block_triangular_by_backward_substitution (Vector< double > &x, const Vector< double > &b, const bool is_unit_block_diagonal=false) const
void solve_block_triangular_by_backward_substitution (Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat, const bool is_unit_block_diagonal=false) const
void solve_block_triangular_by_backward_substitution (Vector< double > &x, const Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat, const bool is_unit_block_diagonal=false) const
void solve_cholesky_by_backward_substitution (Vector< double > &b) const
void solve_cholesky_by_backward_substitution (Vector< double > &x, const Vector< double > &b) const
void solve_cholesky_by_backward_substitution (Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat) const
void solve_cholesky_by_backward_substitution (Vector< double > &x, const Vector< double > &b, const HMatrix< spacedim, double > &starting_hmat) const
void compute_lu_factorization (HMatrix< spacedim, double > &LU, const unsigned int fixed_rank)
void compute_lu_factorization (const unsigned int fixed_rank)
void compute_lu_factorization_task_parallel (const unsigned int fixed_rank)
void compute_cholesky_factorization (HMatrix< spacedim, double > &L, const unsigned int fixed_rank)
void compute_cholesky_factorization (const unsigned int fixed_rank)
void compute_cholesky_factorization_task_parallel (const unsigned int fixed_rank)
void solve_lu (Vector< double > &x, const Vector< double > &b) const
void solve_cholesky (Vector< double > &x, const Vector< double > &b) const
void coarsen_to_subtree (const BlockClusterTree< spacedim, real_type > &subtree, const unsigned int fixed_rank_k)
void coarsen_to_partition (const std::vector< typename BlockClusterTree< spacedim, real_type >::node_pointer_type > &partition, const unsigned int fixed_rank_k)
void link_hmat_nodes_on_same_levels ()
void link_hmat_nodes_on_cross_from_diagonal_blocks (const HMatrixSupport::Property top_hmat_property)
HMatrix< spacedim, double > * get_top_left_leaf_node ()
Get the pointer to the top left leaf node in the \(\mathcal{H}\)-matrix.
const HMatrix< spacedim, double > * get_top_left_leaf_node () const
Get the pointer to the top left leaf node in the \(\mathcal{H}\)-matrix.
void build_leaf_set ()
std::vector< HMatrix< spacedim, double > * > & get_leaf_set ()
const std::vector< HMatrix< spacedim, double > * > & get_leaf_set () const
std::vector< HMatrix< spacedim, double > * > & get_near_field_leaf_set ()
const std::vector< HMatrix< spacedim, double > * > & get_near_field_leaf_set () const
std::vector< HMatrix< spacedim, double > * > & get_far_field_leaf_set ()
const std::vector< HMatrix< spacedim, double > * > & get_far_field_leaf_set () const
std::array< types::global_dof_index, 2 > * get_row_index_range ()
const std::array< types::global_dof_index, 2 > * get_row_index_range () const
std::array< types::global_dof_index, 2 > * get_col_index_range ()
const std::array< types::global_dof_index, 2 > * get_col_index_range () const
std::vector< HMatrix< spacedim, double > * >::iterator find_block_cluster_in_leaf_set (const BlockCluster< spacedim, real_type > &block_cluster)
std::vector< HMatrix< spacedim, double > * >::const_iterator find_block_cluster_in_leaf_set (const BlockCluster< spacedim, real_type > &block_cluster) const
void refine_to_supertree ()
void convert_between_different_block_cluster_trees (BlockClusterTree< spacedim, real_type > &bct1, BlockClusterTree< spacedim, real_type > &bct2, const unsigned int fixed_rank_k2=1)
void remove_hmat_pair_from_mm_product_list (const HMatrix< spacedim, double > *M1, const HMatrix< spacedim, double > *M2)
void remove_hmat_pair_from_mm_product_list (const std::pair< const HMatrix< spacedim, double > *, const HMatrix< spacedim, double > * > &hmat_pair)
TreeNodeSplitMode determine_mm_split_mode_from_Sigma_P ()
std::size_t memory_consumption_of_current_hmat_node () const
std::size_t memory_consumption () const
std::size_t memory_consumption_of_leaf_set () const
std::size_t memory_consumption_of_near_field_leaf_set () const
std::size_t memory_consumption_of_far_field_leaf_set () const
void compute_leaf_set_vmult_or_Tvmult_task_costs (std::vector< double > &task_costs) const
void compute_near_field_leaf_set_assembly_task_costs (std::vector< double > &task_costs) const
void compute_far_field_leaf_set_assembly_task_costs (std::vector< double > &task_costs) const
unsigned int compute_vmult_or_tvmult_thread_num (const bool is_vmult, const bool is_tvmult) const
void prepare_for_vmult_or_tvmult (const bool is_vmult, const bool is_tvmult)
Additional Inherited Members
Static Public Member Functions inherited from HMatrix< spacedim, double >
static void set_leaf_set_traversal_method (const SpaceFillingCurveType type)
Static Public Attributes inherited from HMatrix< spacedim, double >
static const unsigned int submatrix_index_invalid
Detailed Description
template<int spacedim, typename Number = double>
class HMatrixSymmPreconditioner< spacedim, Number >
Definition at line 33 of file hmatrix_symm_preconditioner.h.
Member Typedef Documentation
real_type
template<int spacedim, typename Number = double> using HMatrixSymmPreconditioner< spacedim, Number >::real_type = typename numbers::NumberTraits<Number>::real_type
Definition at line 36 of file hmatrix_symm_preconditioner.h.
Constructor & Destructor Documentation
HMatrixSymmPreconditioner() [1/11]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number >::HMatrixSymmPreconditioner
Default constructor
Definition at line 201 of file hmatrix_symm_preconditioner.h.
HMatrixSymmPreconditioner() [2/11]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number >::HMatrixSymmPreconditioner (const BlockClusterTree< spacedim, real_type > & bct, const unsigned int fixed_rank_k = 1)
Construct the hierarchical structure without data from the root node of a BlockClusterTree.
Definition at line 207 of file hmatrix_symm_preconditioner.h.
HMatrixSymmPreconditioner() [3/11]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number >::HMatrixSymmPreconditioner (typename BlockClusterTree< spacedim, real_type >::node_const_pointer_type bc_node, const unsigned int fixed_rank_k = 1)
Construct the hierarchical structure without data from a TreeNode in a BlockClusterTree.
Definition at line 218 of file hmatrix_symm_preconditioner.h.
HMatrixSymmPreconditioner() [4/11]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number >::HMatrixSymmPreconditioner (const BlockClusterTree< spacedim, real_type > & bct, const LAPACKFullMatrixExt< Number > & M, const unsigned int fixed_rank_k)
Construct from the root node of a BlockClusterTree while copying the data of a global full matrix, which is created on the complete block cluster \(I \times J\).
Note
Since this \(\mathcal{H}\)-matrix is the global matrix, i.e. on the same level as the global full matrix M in the \(\mathcal{H}\)-matrix hierarchy, its block type is set to HMatrixSupport::diagonal_block by default.
Definition at line 230 of file hmatrix_symm_preconditioner.h.
References LAPACKFullMatrixExt< Number >::get_property().
HMatrixSymmPreconditioner() [5/11]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number >::HMatrixSymmPreconditioner (const BlockClusterTree< spacedim, real_type > & bct, const LAPACKFullMatrixExt< Number > & M)
Construct from the root node of a BlockClusterTree while copying the data of a global full matrix, which is created on the complete block cluster \(I \times J\).
This version has no rank truncation.
Note
Since this \(\mathcal{H}\)-matrix is the global matrix, i.e. on the same level as the global full matrix M in the \(\mathcal{H}\)-matrix hierarchy, its block type is set to HMatrixSupport::diagonal_block by default.
Definition at line 245 of file hmatrix_symm_preconditioner.h.
References LAPACKFullMatrixExt< Number >::get_property().
HMatrixSymmPreconditioner() [6/11]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number >::HMatrixSymmPreconditioner (typename BlockClusterTree< spacedim, real_type >::node_const_pointer_type bc_node, const LAPACKFullMatrixExt< Number > & M, const unsigned int fixed_rank_k)
Construct from a TreeNode in a BlockClusterTree while copying the data of a global full matrix, which is created on the complete block cluster \(I \times J\).
Note
The current \(\mathcal{H}\)-matrix to be built may only be a matrix block in the global matrix, while the full matrix M is global, i.e., the \(\mathcal{H}\)-matrix and the full matrix M are not on a same level in the \(\mathcal{H}\)-matrix hierarchy. But because the current \(\mathcal{H}\)-matrix is symmetric, its block type is still diagonal and its property should be symmetric.
Definition at line 256 of file hmatrix_symm_preconditioner.h.
References LAPACKFullMatrixExt< Number >::get_property().
HMatrixSymmPreconditioner() [7/11]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number >::HMatrixSymmPreconditioner (typename BlockClusterTree< spacedim, real_type >::node_const_pointer_type bc_node, const LAPACKFullMatrixExt< Number > & M)
Construct from a TreeNode in a BlockClusterTree while copying the data of a global full matrix, which is created on the complete block cluster \(I \times J\).
This version has no rank truncation.
Note
The current \(\mathcal{H}\)-matrix to be built may only be a matrix block in the global matrix, while the full matrix M is global, i.e., the \(\mathcal{H}\)-matrix and the full matrix M are not on a same level in the \(\mathcal{H}\)-matrix hierarchy. But because the current \(\mathcal{H}\)-matrix is symmetric, its block type is still diagonal and its property should be symmetric.
Definition at line 273 of file hmatrix_symm_preconditioner.h.
References LAPACKFullMatrixExt< Number >::get_property().
HMatrixSymmPreconditioner() [8/11]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number >::HMatrixSymmPreconditioner (const HMatrixSymmPreconditioner< spacedim, Number > & H)
Deep copy constructor
Parameters
H
Definition at line 288 of file hmatrix_symm_preconditioner.h.
HMatrixSymmPreconditioner() [9/11]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number >::HMatrixSymmPreconditioner (HMatrixSymmPreconditioner< spacedim, Number > && H) noexcept
Shallow copy constructor
Parameters
H
Definition at line 295 of file hmatrix_symm_preconditioner.h.
HMatrixSymmPreconditioner() [10/11]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number >::HMatrixSymmPreconditioner (const HMatrix< spacedim, Number > & H)
Deep copy constructor, copy from a HMatrix.
Parameters
H
Definition at line 324 of file hmatrix_symm_preconditioner.h.
HMatrixSymmPreconditioner() [11/11]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number >::HMatrixSymmPreconditioner (HMatrix< spacedim, Number > && H) noexcept
Shallow copy constructor, copy from a HMatrix.
Parameters
H
Definition at line 331 of file hmatrix_symm_preconditioner.h.
Member Function Documentation
operator=() [1/4]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number > & HMatrixSymmPreconditioner< spacedim, Number >::operator= (const HMatrix< spacedim, Number > & H)
Deep assignment operator, assign from a HMatrix.
Parameters
H
Returns
Definition at line 339 of file hmatrix_symm_preconditioner.h.
References HMatrix< spacedim, Number >::operator=().
operator=() [2/4]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number > & HMatrixSymmPreconditioner< spacedim, Number >::operator= (const HMatrixSymmPreconditioner< spacedim, Number > & H)
Deep assignment operator
Parameters
return
Definition at line 303 of file hmatrix_symm_preconditioner.h.
References HMatrix< spacedim, Number >::operator=().
operator=() [3/4]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number > & HMatrixSymmPreconditioner< spacedim, Number >::operator= (HMatrix< spacedim, Number > && H) noexcept
Shallow assignment operator, assign from a HMatrix.
Parameters
H
Returns
Definition at line 350 of file hmatrix_symm_preconditioner.h.
References HMatrix< spacedim, Number >::operator=().
operator=() [4/4]
template<int spacedim, typename Number > HMatrixSymmPreconditioner< spacedim, Number > & HMatrixSymmPreconditioner< spacedim, Number >::operator= (HMatrixSymmPreconditioner< spacedim, Number > && H) noexcept
Shallow assignment operator
Parameters
return
Definition at line 314 of file hmatrix_symm_preconditioner.h.
References HMatrix< spacedim, Number >::operator=().
vmult()
template<int spacedim, typename Number > void HMatrixSymmPreconditioner< spacedim, Number >::vmult (Vector< Number > & y, const Vector< Number > & x) const virtual
Calculate matrix-vector multiplication as \(y = M^{-1} \cdot x\), which is actually applying the preconditioner to the input vector.
Parameters
y
x
Definition at line 361 of file hmatrix_symm_preconditioner.h.
The documentation for this class was generated from the following file:
include/hmatrix/preconditioner/hmatrix_symm_preconditioner.h