HierBEM: BinaryTreeNode< T > Class Template Reference
BinaryTreeNode< T > Class Template Reference
Hierarchical matrices
Class for binary tree node.
#include <tree.h>
Public Member Functions
BinaryTreeNode ()
BinaryTreeNode (const BinaryTreeNode &node)
BinaryTreeNode (const T &data, unsigned int level, BinaryTreeNode *left=nullptr, BinaryTreeNode *right=nullptr, BinaryTreeNode *parent=nullptr)
BinaryTreeNode * Left (void) const
BinaryTreeNode * Right (void) const
BinaryTreeNode * get_child_pointer (std::size_t index) const
unsigned int get_child_num () const
void set_child_num (const unsigned int child_num)
void increase_child_num (const unsigned int incr_num=1)
void decrease_child_num (const unsigned int decr_num=1)
BinaryTreeNode * Parent (void) const
void Left (const BinaryTreeNode *node_pointer)
void Right (const BinaryTreeNode *node_pointer)
void set_child_pointer (std::size_t index, const BinaryTreeNode *node_pointer)
void Parent (const BinaryTreeNode *node_pointer)
T * get_data_pointer ()
const T * get_data_pointer () const
T & get_data_reference ()
const T & get_data_reference () const
unsigned int get_level () const
void set_level (const unsigned int level)
bool is_leaf () const
bool is_root () const
bool operator== (const BinaryTreeNode< T > &node) const
std::size_t memory_consumption () const
Private Attributes
T data
unsigned int level
BinaryTreeNode * left
BinaryTreeNode * right
BinaryTreeNode * parent
unsigned int child_num
Detailed Description
template<typename T>
class BinaryTreeNode< T >
Class for binary tree node.
In the implementation of hierarchical matrices, a binary tree node is designed to hold a cluster (Cluster) in a cluster tree (ClusterTree) along with two pointers left and right pointing to the two children belong to the node itself. The template argument T should be assigned the type of the cluster.
Definition at line 53 of file tree.h.
Constructor & Destructor Documentation
BinaryTreeNode() [1/3]
template<typename T > BinaryTreeNode< T >::BinaryTreeNode
Default constructor.
Definition at line 246 of file tree.h.
BinaryTreeNode() [2/3]
template<typename T > BinaryTreeNode< T >::BinaryTreeNode (const BinaryTreeNode< T > & node)
Copy constructor.
Definition at line 257 of file tree.h.
BinaryTreeNode() [3/3]
template<typename T > BinaryTreeNode< T >::BinaryTreeNode (const T & data, unsigned int level, BinaryTreeNode< T > * left = nullptr, BinaryTreeNode< T > * right = nullptr, BinaryTreeNode< T > * parent = nullptr)
Constructor from the given data.
N.B. The data of type T will be copied into the created node.
Increment the child_num of the parent node.
Definition at line 268 of file tree.h.
References BinaryTreeNode< T >::child_num.
Member Function Documentation
decrease_child_num()
template<typename T > void BinaryTreeNode< T >::decrease_child_num (const unsigned int decr_num = 1)
Decrease the total number of children.
Returns
Definition at line 363 of file tree.h.
get_child_num()
template<typename T > unsigned int BinaryTreeNode< T >::get_child_num inline
Get the total number of nonempty children.
Definition at line 339 of file tree.h.
Referenced by GetTreeLeaves(), PrintTreeNode(), and ClusterTree< spacedim, Number >::set_index_ranges_and_clear_index_sets_from_cluster_node().
get_child_pointer()
template<typename T > BinaryTreeNode< T > * BinaryTreeNode< T >::get_child_pointer (std::size_t index) const
Get the pointer to the index'th child.
Parameters
index Index of the child
Returns
Definition at line 317 of file tree.h.
Referenced by ClusterTree< spacedim, Number >::set_index_ranges_and_clear_index_sets_from_cluster_node().
get_data_pointer() [1/2]
template<typename T > T * BinaryTreeNode< T >::get_data_pointer inline
Get the pointer to the node data.
Definition at line 429 of file tree.h.
Referenced by ClusterTree< spacedim, Number >::partition_from_cluster_node().
get_data_pointer() [2/2]
template<typename T > const T * BinaryTreeNode< T >::get_data_pointer inline
Get the pointer to the node data (const version).
Definition at line 453 of file tree.h.
get_data_reference() [1/2]
template<typename T > T & BinaryTreeNode< T >::get_data_reference inline
Get the reference to the node data.
Definition at line 437 of file tree.h.
Referenced by CopyTree(), PrintTreeNode(), and ClusterTree< spacedim, Number >::set_index_ranges_and_clear_index_sets_from_cluster_node().
get_data_reference() [2/2]
template<typename T > const T & BinaryTreeNode< T >::get_data_reference inline
Get the reference to the node data (const version).
Definition at line 445 of file tree.h.
get_level()
template<typename T > unsigned int BinaryTreeNode< T >::get_level inline
Get the level of the node in the tree.
Definition at line 460 of file tree.h.
Referenced by ClusterTree< spacedim, Number >::_print_tree_info_as_dot_node(), CopyTree(), GetTreeNodesAtLevel(), ClusterTree< spacedim, Number >::partition_from_cluster_node(), and PrintTreeNode().
increase_child_num()
template<typename T > void BinaryTreeNode< T >::increase_child_num (const unsigned int incr_num = 1) inline
Increase the total number of children.
Definition at line 355 of file tree.h.
Referenced by CopyTree().
is_leaf()
template<typename T > bool BinaryTreeNode< T >::is_leaf inline
Return whether the current binary tree node is a leaf.
Returns
Definition at line 476 of file tree.h.
is_root()
template<typename T > bool BinaryTreeNode< T >::is_root inline
Return whether the current binary tree node is the root.
Returns
Definition at line 484 of file tree.h.
Left() [1/2]
template<typename T > void BinaryTreeNode< T >::Left (const BinaryTreeNode< T > * node_pointer) inline
Set the left child node pointer.
N.B. The const pointer type in the argument will be converted to non-const pointer type. In this way, even a const node can be added to the tree.
Definition at line 415 of file tree.h.
Left() [2/2]
template<typename T > BinaryTreeNode< T > * BinaryTreeNode< T >::Left (void) const inline
Get the pointer to the left child node.
Definition at line 302 of file tree.h.
Referenced by calc_depth(), CopyTree(), CountTreeNodes(), GetTreeLeaves(), GetTreeNodesAtLevel(), Inorder(), ClusterTree< spacedim, Number >::partition_from_cluster_node(), Postorder(), Preorder(), and Preorder_for_memory_consumption().
memory_consumption()
template<typename T > std::size_t BinaryTreeNode< T >::memory_consumption
Estimate the memory consumption of the node itself and its contained data.
Definition at line 500 of file tree.h.
Referenced by Preorder_for_memory_consumption().
operator==()
template<typename T > bool BinaryTreeNode< T >::operator== (const BinaryTreeNode< T > & node) const inline
Check the equality of two binary tree nodes by comparing the contained data.
Parameters
node
Returns
Definition at line 492 of file tree.h.
Parent() [1/2]
template<typename T > void BinaryTreeNode< T >::Parent (const BinaryTreeNode< T > * node_pointer) inline
Set the pointer to the parent.
Parameters
node_pointer
Definition at line 407 of file tree.h.
Parent() [2/2]
template<typename T > BinaryTreeNode< T > * BinaryTreeNode< T >::Parent (void) const inline
Get the pointer to the parent node.
Definition at line 399 of file tree.h.
Referenced by CopyTree(), and PrintTreeNode().
Right() [1/2]
template<typename T > void BinaryTreeNode< T >::Right (const BinaryTreeNode< T > * node_pointer) inline
Set the right child node pointer.
N.B. The const pointer type in the argument will be converted to non-const pointer type. In this way, even a const node can be added to the tree.
Definition at line 422 of file tree.h.
Right() [2/2]
template<typename T > BinaryTreeNode< T > * BinaryTreeNode< T >::Right (void) const inline
Get the pointer to the right child node.
Definition at line 309 of file tree.h.
Referenced by calc_depth(), CopyTree(), CountTreeNodes(), GetTreeLeaves(), GetTreeNodesAtLevel(), Inorder(), ClusterTree< spacedim, Number >::partition_from_cluster_node(), Postorder(), Preorder(), and Preorder_for_memory_consumption().
set_child_num()
template<typename T > void BinaryTreeNode< T >::set_child_num (const unsigned int child_num) inline
Set the total number of nonempty children.
Parameters
child_num
Definition at line 347 of file tree.h.
set_child_pointer()
template<typename T > void BinaryTreeNode< T >::set_child_pointer (std::size_t index, const BinaryTreeNode< T > * node_pointer)
Set the pointer to the index'th child.
Parameters
index Index of the child
node_pointer Pointer value to be assigned to the specified child.
Definition at line 378 of file tree.h.
set_level()
template<typename T > void BinaryTreeNode< T >::set_level (const unsigned int level) inline
Set the level of the node.
Parameters
level
Definition at line 468 of file tree.h.
Member Data Documentation
child_num
template<typename T > unsigned int BinaryTreeNode< T >::child_num private
Total number of nonempty children.
Definition at line 242 of file tree.h.
Referenced by BinaryTreeNode< T >::BinaryTreeNode().
data
template<typename T > T BinaryTreeNode< T >::data private
Definition at line 232 of file tree.h.
left
template<typename T > BinaryTreeNode* BinaryTreeNode< T >::left private
Definition at line 235 of file tree.h.
level
template<typename T > unsigned int BinaryTreeNode< T >::level private
Definition at line 233 of file tree.h.
parent
template<typename T > BinaryTreeNode* BinaryTreeNode< T >::parent private
Definition at line 237 of file tree.h.
right
template<typename T > BinaryTreeNode* BinaryTreeNode< T >::right private
Definition at line 236 of file tree.h.
The documentation for this class was generated from the following file:
include/cluster_tree/tree.h