HierBEM: CUDAWrappers::CUDATable< N, T > Class Template Reference
CUDAWrappers::CUDATable< N, T > Class Template Reference
Public Types
using value_type = T
using size_type = std::size_t
using pointer = T *
using const_pointer = const T *
Public Member Functions
HBEM_ATTR_HOST void allocate (const TableIndices< N > &table_size_arg)
HBEM_ATTR_HOST void allocate (const TableIndices< N > &table_size_arg, const cudaStream_t stream)
HBEM_ATTR_HOST void allocate (const CUDATableIndices< N > &table_size_arg)
HBEM_ATTR_HOST void allocate (const CUDATableIndices< N > &table_size_arg, const cudaStream_t stream)
HBEM_ATTR_HOST void assign_from_host (const Table< N, T > &table_cpu)
HBEM_ATTR_HOST void assign_from_host (const Table< N, T > &table_cpu, const cudaStream_t stream)
HBEM_ATTR_HOST void assign_from_host (const std::vector< T > &data)
HBEM_ATTR_HOST void assign_from_host (const std::vector< T > &data, const cudaStream_t stream)
HBEM_ATTR_HOST void assign_from_host (const T *data, const size_type size)
HBEM_ATTR_HOST void assign_from_host (const T *data, const size_type size, const cudaStream_t stream)
HBEM_ATTR_HOST void assign_from_host (const T *data, const size_type offset_in_device_table, const size_type size)
HBEM_ATTR_HOST void assign_from_host (const T *data, const size_type offset_in_device_table, const size_type size, const cudaStream_t stream)
HBEM_ATTR_HOST void copy_to_host (Table< N, T > &table_cpu) const
HBEM_ATTR_HOST void copy_to_host (Table< N, T > &table_cpu, const cudaStream_t stream) const
HBEM_ATTR_HOST void release ()
HBEM_ATTR_HOST void release (const cudaStream_t stream)
HBEM_ATTR_HOST HBEM_ATTR_DEV size_type n_elements () const
HBEM_ATTR_HOST CUDATable (const CUDATable< N, T > &)=default
HBEM_ATTR_HOST CUDATable< N, T > & operator= (const CUDATable< N, T > &src)
HBEM_ATTR_HOST void assign (const CUDATable< N, T > &src, const cudaStream_t stream)
HBEM_ATTR_DEV const T & operator[] (const size_type i) const
HBEM_ATTR_DEV T & operator[] (const size_type i)
HBEM_ATTR_DEV const T & operator() (const CUDATableIndices< N > &indices) const
HBEM_ATTR_DEV T & operator() (const CUDATableIndices< N > &indices)
HBEM_ATTR_DEV const T & operator() (const size_type i) const
HBEM_ATTR_DEV T & operator() (const size_type i)
HBEM_ATTR_DEV const T & operator() (const size_type i, const size_type j) const
HBEM_ATTR_DEV T & operator() (const size_type i, const size_type j)
HBEM_ATTR_DEV const T & operator() (const size_type i, const size_type j, const size_type k) const
HBEM_ATTR_DEV T & operator() (const size_type i, const size_type j, const size_type k)
HBEM_ATTR_DEV const T & operator() (const size_type i, const size_type j, const size_type k, const size_type l) const
HBEM_ATTR_DEV T & operator() (const size_type i, const size_type j, const size_type k, const size_type l)
HBEM_ATTR_DEV const T & operator() (const size_type i, const size_type j, const size_type k, const size_type l, const size_type m) const
HBEM_ATTR_DEV T & operator() (const size_type i, const size_type j, const size_type k, const size_type l, const size_type m)
HBEM_ATTR_HOST HBEM_ATTR_DEV size_type offset (const CUDATableIndices< N > &indices) const
HBEM_ATTR_HOST HBEM_ATTR_DEV size_type offset (const size_type i, const size_type j) const
HBEM_ATTR_HOST HBEM_ATTR_DEV size_type offset (const size_type i, const size_type j, const size_type k) const
HBEM_ATTR_HOST HBEM_ATTR_DEV size_type offset (const size_type i, const size_type j, const size_type k, const size_type l) const
HBEM_ATTR_HOST HBEM_ATTR_DEV size_type offset (const size_type i, const size_type j, const size_type k, const size_type l, const size_type m) const
HBEM_ATTR_HOST HBEM_ATTR_DEV const CUDATableIndices< N > & size () const
HBEM_ATTR_HOST HBEM_ATTR_DEV size_type size (const size_type i) const
HBEM_ATTR_HOST HBEM_ATTR_DEV pointer data ()
HBEM_ATTR_HOST HBEM_ATTR_DEV const_pointer data () const
Private Attributes
T * values = nullptr
size_type element_num = 0
CUDATableIndices< N > table_size {}
Detailed Description
template<int N, typename T = double>
class CUDAWrappers::CUDATable< N, T >
Table class with the memory for its internal data allocated on the GPU device.
Template Parameters
N Table dimension
T Value type
Definition at line 48 of file cu_table.hcu.
Member Typedef Documentation
const_pointer
template<int N, typename T = double> using CUDAWrappers::CUDATable< N, T >::const_pointer = const T *
Definition at line 55 of file cu_table.hcu.
pointer
template<int N, typename T = double> using CUDAWrappers::CUDATable< N, T >::pointer = T *
Definition at line 54 of file cu_table.hcu.
size_type
template<int N, typename T = double> using CUDAWrappers::CUDATable< N, T >::size_type = std::size_t
Definition at line 53 of file cu_table.hcu.
value_type
template<int N, typename T = double> using CUDAWrappers::CUDATable< N, T >::value_type = T
Definition at line 52 of file cu_table.hcu.
Member Function Documentation
allocate() [1/4]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::allocate (const CUDATableIndices< N > & table_size_arg)
Allocate global memory on the device according to the specified table sizes in CUDATableIndices.
Parameters
table_size_arg
Definition at line 639 of file cu_table.hcu.
allocate() [2/4]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::allocate (const CUDATableIndices< N > & table_size_arg, const cudaStream_t stream)
Allocate global memory on the device according to the specified table sizes in CUDATableIndices (asynchronous allocation).
Parameters
table_size_arg
stream
Definition at line 661 of file cu_table.hcu.
allocate() [3/4]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::allocate (const TableIndices< N > & table_size_arg)
Allocate global memory on the device according to the specified table sizes in TableIndices.
Parameters
table_size_arg
Definition at line 593 of file cu_table.hcu.
Referenced by CUDAWrappers::SauterQuadratureTaskBufferForVector< dim, spacedim, CUDARangeNumberType, CUDAKernelNumberType >::SauterQuadratureTaskBufferForVector().
allocate() [4/4]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::allocate (const TableIndices< N > & table_size_arg, const cudaStream_t stream)
Allocate global memory on the device according to the specified table sizes in TableIndices (asynchronous allocation).
Parameters
table_size_arg
stream
Definition at line 615 of file cu_table.hcu.
assign()
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::assign (const CUDATable< N, T > & src, const cudaStream_t stream)
Assignment operator: copy the values from another CUDATable object (asynchronous).
This function can only run on the host, since objects of this class are actually managed from the host and inside this function, the function cudaMemcpyAsync is called, which can only run on the host.
Parameters
src
stream
Returns
Definition at line 931 of file cu_table.hcu.
References CUDAWrappers::CUDATable< N, T >::element_num, CUDAWrappers::CUDATable< N, T >::table_size, and CUDAWrappers::CUDATable< N, T >::values.
assign_from_host() [1/8]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::assign_from_host (const std::vector< T > & data)
Assign values held within a vector on the host to the device.
Parameters
data
Definition at line 721 of file cu_table.hcu.
assign_from_host() [2/8]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::assign_from_host (const std::vector< T > & data, const cudaStream_t stream)
Assign values held within a vector on the host to the device (asynchronous copy).
Parameters
data
stream
Definition at line 736 of file cu_table.hcu.
assign_from_host() [3/8]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::assign_from_host (const T * data, const size_type offset_in_device_table, const size_type size)
Assign values held within an array on the host to the device with an offset in the 1D memory on the device.
Parameters
data
size
Definition at line 786 of file cu_table.hcu.
References size().
assign_from_host() [4/8]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::assign_from_host (const T * data, const size_type offset_in_device_table, const size_type size, const cudaStream_t stream)
Assign values held within an array on the host to the device with an offset in the 1D memory on the device (asynchronous copy).
Parameters
data
offset_in_device_table
size
stream
Definition at line 804 of file cu_table.hcu.
References size().
assign_from_host() [5/8]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::assign_from_host (const T * data, const size_type size)
Assign values held within an array on the host to the device.
Parameters
data
size
Definition at line 753 of file cu_table.hcu.
References size().
assign_from_host() [6/8]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::assign_from_host (const T * data, const size_type size, const cudaStream_t stream)
Assign values held within an array on the host to the device (asynchronous copy).
Parameters
data
size
stream
Definition at line 767 of file cu_table.hcu.
References size().
assign_from_host() [7/8]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::assign_from_host (const Table< N, T > & table_cpu)
Assign values held within a deal.ii Table on the host to the device.
The memory of the CUDATable should preallocated to the same table size before calling this function. The data are directly copied from table_cpu to the current object and there is no size checking.
Parameters
table_cpu
Definition at line 685 of file cu_table.hcu.
assign_from_host() [8/8]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::assign_from_host (const Table< N, T > & table_cpu, const cudaStream_t stream)
Assign values held within a deal.ii Table on the host to the device (asynchronous copy).
The memory of the CUDATable should preallocated to the same table size before calling this function. The data are directly copied from table_cpu to the current object and there is no size checking.
Parameters
table_cpu
stream
Definition at line 702 of file cu_table.hcu.
copy_to_host() [1/2]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::copy_to_host (Table< N, T > & table_cpu) const
Copy the table data on the device to the table on the host.
Parameters
table_cpu
Definition at line 824 of file cu_table.hcu.
copy_to_host() [2/2]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::copy_to_host (Table< N, T > & table_cpu, const cudaStream_t stream) const
Copy the table data on the device to the table on the host (asynchronous copy).
Parameters
table_cpu
stream
Definition at line 838 of file cu_table.hcu.
data() [1/2]
template<int N, typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDATable< N, T >::pointer CUDAWrappers::CUDATable< N, T >::data inline
Get the pointer to the internal data.
Returns
Definition at line 1191 of file cu_table.hcu.
data() [2/2]
template<int N, typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDATable< N, T >::const_pointer CUDAWrappers::CUDATable< N, T >::data inline
Get the const pointer to the internal data.
Returns
Definition at line 1199 of file cu_table.hcu.
n_elements()
template<int N, typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDATable< N, T >::size_type CUDAWrappers::CUDATable< N, T >::n_elements inline
Get the total number of elements in the table.
Returns
Definition at line 898 of file cu_table.hcu.
offset() [1/5]
template<int N, typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDATable< N, T >::size_type CUDAWrappers::CUDATable< N, T >::offset (const CUDATableIndices< N > & indices) const inline
Compute the offset in the linear memory of the table entry, which is specified by its table indices.
Note
The table entries are accessed using the C style.
Parameters
indices
Returns
Definition at line 1116 of file cu_table.hcu.
offset() [2/5]
template<int N, typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDATable< N, T >::size_type CUDAWrappers::CUDATable< N, T >::offset (const size_type i, const size_type j) const inline
Compute the offset in the linear memory of the table entry, which is specified by its table indices.
Note
The table entries are accessed using the C style. This version is used for table dimension 2.
Parameters
i
j
Returns
Definition at line 1124 of file cu_table.hcu.
offset() [3/5]
template<int N, typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDATable< N, T >::size_type CUDAWrappers::CUDATable< N, T >::offset (const size_type i, const size_type j, const size_type k) const inline
Compute the offset in the linear memory of the table entry, which is specified by its table indices.
Note
The table entries are accessed using the C style. This version is used for table dimension 3.
Parameters
i
j
k
Returns
Definition at line 1134 of file cu_table.hcu.
offset() [4/5]
template<int N, typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDATable< N, T >::size_type CUDAWrappers::CUDATable< N, T >::offset (const size_type i, const size_type j, const size_type k, const size_type l) const inline
Compute the offset in the linear memory of the table entry, which is specified by its table indices.
Note
The table entries are accessed using the C style. This version is used for table dimension 4.
Parameters
i
j
k
l
Returns
Definition at line 1146 of file cu_table.hcu.
offset() [5/5]
template<int N, typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDATable< N, T >::size_type CUDAWrappers::CUDATable< N, T >::offset (const size_type i, const size_type j, const size_type k, const size_type l, const size_type m) const inline
Compute the offset in the linear memory of the table entry, which is specified by its table indices.
Note
The table entries are accessed using the C style. This version is used for table dimension 5.
Parameters
i
j
k
l
m
Returns
Definition at line 1159 of file cu_table.hcu.
operator()() [1/12]
template<int N, typename T > HBEM_ATTR_DEV T & CUDAWrappers::CUDATable< N, T >::operator() (const CUDATableIndices< N > & indices)
Get the reference to the element specified by the table indices. C style indexing is adopted.
This function can only be called on the device, since the table data are stored on the device and accessing only one element at a time is inefficient.
Parameters
indices
Returns
Definition at line 980 of file cu_table.hcu.
operator()() [2/12]
template<int N, typename T > HBEM_ATTR_DEV const T & CUDAWrappers::CUDATable< N, T >::operator() (const CUDATableIndices< N > & indices) const inline
Get the const reference to the element specified by the table indices. C style indexing is adopted.
This function can only be called on the device, since the table data are stored on the device and accessing only one element at a time is inefficient.
Parameters
indices
Returns
Definition at line 972 of file cu_table.hcu.
operator()() [3/12]
template<int N, typename T > HBEM_ATTR_DEV T & CUDAWrappers::CUDATable< N, T >::operator() (const size_type i) inline
Get the reference to the i'th element in the table.
Note
The table should have only one dimension.
Parameters
i
Returns
Definition at line 998 of file cu_table.hcu.
operator()() [4/12]
template<int N, typename T > HBEM_ATTR_DEV const T & CUDAWrappers::CUDATable< N, T >::operator() (const size_type i) const inline
Get the const reference to the i'th element in the table.
Note
The table should have only one dimension.
Parameters
i
Returns
Definition at line 988 of file cu_table.hcu.
operator()() [5/12]
template<int N, typename T > HBEM_ATTR_DEV T & CUDAWrappers::CUDATable< N, T >::operator() (const size_type i, const size_type j) inline
Get the reference to the element (i,j) in the table.
Note
The table should have two dimensions.
Parameters
i
j
Returns
Definition at line 1018 of file cu_table.hcu.
operator()() [6/12]
template<int N, typename T > HBEM_ATTR_DEV const T & CUDAWrappers::CUDATable< N, T >::operator() (const size_type i, const size_type j) const inline
Get the const reference to the element (i,j) in the table.
Note
The table should have two dimensions.
Parameters
i
j
Returns
Definition at line 1008 of file cu_table.hcu.
operator()() [7/12]
template<int N, typename T > HBEM_ATTR_DEV T & CUDAWrappers::CUDATable< N, T >::operator() (const size_type i, const size_type j, const size_type k) inline
Get the reference to the element (i,j,k) in the table.
Note
The table should have three dimensions.
Parameters
i
j
k
Returns
Definition at line 1040 of file cu_table.hcu.
operator()() [8/12]
template<int N, typename T > HBEM_ATTR_DEV const T & CUDAWrappers::CUDATable< N, T >::operator() (const size_type i, const size_type j, const size_type k) const inline
Get the const reference to the element (i,j,k) in the table.
Note
The table should have three dimensions.
Parameters
i
j
k
Returns
Definition at line 1028 of file cu_table.hcu.
operator()() [9/12]
template<int N, typename T > HBEM_ATTR_DEV T & CUDAWrappers::CUDATable< N, T >::operator() (const size_type i, const size_type j, const size_type k, const size_type l) inline
Get the reference to the element (i,j,k,l) in the table.
Note
The table should have four dimensions.
Parameters
i
j
k
l
Returns
Definition at line 1067 of file cu_table.hcu.
operator()() [10/12]
template<int N, typename T > HBEM_ATTR_DEV const T & CUDAWrappers::CUDATable< N, T >::operator() (const size_type i, const size_type j, const size_type k, const size_type l) const inline
Get the const reference to the element (i,j,k,l) in the table.
Note
The table should have four dimensions.
Parameters
i
j
k
l
Returns
Definition at line 1052 of file cu_table.hcu.
operator()() [11/12]
template<int N, typename T > HBEM_ATTR_DEV T & CUDAWrappers::CUDATable< N, T >::operator() (const size_type i, const size_type j, const size_type k, const size_type l, const size_type m) inline
Get the reference to the element (i,j,k,l,m) in the table.
Note
The table should have five dimensions.
Parameters
i
j
k
l
m
Returns
Definition at line 1099 of file cu_table.hcu.
operator()() [12/12]
template<int N, typename T > HBEM_ATTR_DEV const T & CUDAWrappers::CUDATable< N, T >::operator() (const size_type i, const size_type j, const size_type k, const size_type l, const size_type m) const inline
Get the const reference to the element (i,j,k,l,m) in the table.
Note
The table should have five dimensions.
Parameters
i
j
k
l
m
Returns
Definition at line 1082 of file cu_table.hcu.
operator=()
template<int N, typename T > HBEM_ATTR_HOST CUDATable< N, T > & CUDAWrappers::CUDATable< N, T >::operator= (const CUDATable< N, T > & src)
Assignment operator: copy the values from another CUDATable object.
This function can only run on the host, since objects of this class are actually managed from the host and inside this function, the function cudaMemcpy is called, which can only run on the host.
Parameters
src
Returns
Definition at line 906 of file cu_table.hcu.
References CUDAWrappers::CUDATable< N, T >::element_num, CUDAWrappers::CUDATable< N, T >::table_size, and CUDAWrappers::CUDATable< N, T >::values.
operator[]() [1/2]
template<int N, typename T > HBEM_ATTR_DEV T & CUDAWrappers::CUDATable< N, T >::operator[] (const size_type i) inline
Get the reference to the i'th element in the table using linear index.
This function can only be called on the device, since the table data are stored on the device and accessing only one element at a time is inefficient.
Parameters
i
Returns
Definition at line 964 of file cu_table.hcu.
operator[]() [2/2]
template<int N, typename T > HBEM_ATTR_DEV const T & CUDAWrappers::CUDATable< N, T >::operator[] (const size_type i) const inline
Get the const reference to the i'th element in the table using linear index.
This function can only be called on the device, since the table data are stored on the device and accessing only one element at a time is inefficient.
Parameters
i
Returns
Definition at line 956 of file cu_table.hcu.
release() [1/2]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::release
Release the allocated global memory on the device.
Definition at line 854 of file cu_table.hcu.
release() [2/2]
template<int N, typename T > HBEM_ATTR_HOST void CUDAWrappers::CUDATable< N, T >::release (const cudaStream_t stream)
Release the allocated global memory on the device (asynchronous release).
Parameters
stream
Definition at line 876 of file cu_table.hcu.
size() [1/2]
template<int N, typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV const CUDATableIndices< N > & CUDAWrappers::CUDATable< N, T >::size inline
Get table sizes.
Returns
Definition at line 1175 of file cu_table.hcu.
size() [2/2]
template<int N, typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDATable< N, T >::size_type CUDAWrappers::CUDATable< N, T >::size (const size_type i) const inline
Get the table size in the i'th dimension.
Parameters
i
Returns
Definition at line 1183 of file cu_table.hcu.
Member Data Documentation
element_num
template<int N, typename T = double> size_type CUDAWrappers::CUDATable< N, T >::element_num = 0 private
Total number of entries in the table.
Definition at line 583 of file cu_table.hcu.
Referenced by CUDAWrappers::CUDATable< N, T >::assign(), and CUDAWrappers::CUDATable< N, T >::operator=().
table_size
template<int N, typename T = double> CUDATableIndices<N> CUDAWrappers::CUDATable< N, T >::table_size {} private
Table size in each dimension.
Definition at line 587 of file cu_table.hcu.
Referenced by CUDAWrappers::CUDATable< N, T >::assign(), and CUDAWrappers::CUDATable< N, T >::operator=().
values
template<int N, typename T = double> T* CUDAWrappers::CUDATable< N, T >::values = nullptr private
Pointer to the table of values.
Definition at line 579 of file cu_table.hcu.
Referenced by CUDAWrappers::CUDATable< N, T >::assign(), and CUDAWrappers::CUDATable< N, T >::operator=().
The documentation for this class was generated from the following file:
include/linear_algebra/cu_table.hcu