HierBEM: Cluster< spacedim, Number > Class Template Reference
Cluster< spacedim, Number > Class Template Reference
Hierarchical matrices
Class for an index cluster.
#include <cluster.h>
Public Member Functions
Cluster ()
Cluster (const std::vector< types::global_dof_index > &index_set)
Cluster (const std::vector< types::global_dof_index > &index_set, const std::vector< Point< spacedim, Number > > &all_support_points)
Cluster (const std::vector< types::global_dof_index > &index_set, const std::vector< Point< spacedim, Number > > &all_support_points, const std::vector< Number > &cell_size_at_dofs)
Cluster (const std::vector< types::global_dof_index > &index_set, const SimpleBoundingBox< spacedim, Number > &bbox, const std::vector< Point< spacedim, Number > > &all_support_points)
Cluster (const std::vector< types::global_dof_index > &index_set, const SimpleBoundingBox< spacedim, Number > &bbox, const std::vector< Point< spacedim, Number > > &all_support_points, const std::vector< Number > &cell_size_at_dofs)
Cluster (const Cluster< spacedim, Number > &cluster)
std::vector< types::global_dof_index > & get_index_set ()
const std::vector< types::global_dof_index > & get_index_set () const
std::array< types::global_dof_index, 2 > & get_index_range ()
const std::array< types::global_dof_index, 2 > & get_index_range () const
void set_index_range (const types::global_dof_index lower_bound, const types::global_dof_index pass_upper_bound)
SimpleBoundingBox< spacedim, Number > & get_bounding_box ()
const SimpleBoundingBox< spacedim, Number > & get_bounding_box () const
Number get_diameter () const
Number calc_diameter (const std::vector< Point< spacedim, Number > > &all_support_points) const
Number calc_diameter (const std::vector< types::global_dof_index > &internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > &all_support_points) const
Number calc_diameter (const std::vector< Point< spacedim, Number > > &all_support_points, const std::vector< Number > &cell_size_at_dofs) const
Number calc_diameter (const std::vector< types::global_dof_index > &internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > &all_support_points, const std::vector< Number > &cell_size_at_dofs) const
Number distance_to_cluster (const Cluster &cluster, const std::vector< Point< spacedim, Number > > &all_support_points) const
Number distance_to_cluster (const Cluster &cluster, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > &all_support_points) const
Number distance_to_cluster (const Cluster &cluster, const std::vector< Point< spacedim, Number > > &all_support_points1, const std::vector< Point< spacedim, Number > > &all_support_points2) const
Number distance_to_cluster (const Cluster &cluster, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering1, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering2, const std::vector< Point< spacedim, Number > > &all_support_points1, const std::vector< Point< spacedim, Number > > &all_support_points2) const
Number distance_to_cluster (const Cluster &cluster, const std::vector< Point< spacedim, Number > > &all_support_points, const std::vector< Number > &cell_size_at_dofs) const
Number distance_to_cluster (const Cluster &cluster, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > &all_support_points, const std::vector< Number > &cell_size_at_dofs) const
Number distance_to_cluster (const Cluster &cluster, const std::vector< Point< spacedim, Number > > &all_support_points1, const std::vector< Point< spacedim, Number > > &all_support_points2, const std::vector< Number > &cell_size_at_dofs1, const std::vector< Number > &cell_size_at_dofs2) const
Number distance_to_cluster (const Cluster &cluster, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering1, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering2, const std::vector< Point< spacedim, Number > > &all_support_points1, const std::vector< Point< spacedim, Number > > &all_support_points2, const std::vector< Number > &cell_size_at_dofs1, const std::vector< Number > &cell_size_at_dofs2) const
bool is_subset (const Cluster &cluster) const
bool is_proper_subset (const Cluster &cluster) const
bool is_superset (const Cluster &cluster) const
bool is_proper_superset (const Cluster &cluster) const
void intersect (const Cluster &cluster, std::vector< types::global_dof_index > &index_set_intersection) const
void intersect (const Cluster &cluster, std::array< types::global_dof_index, 2 > &index_range_intersection) const
bool has_intersection (const Cluster &cluster) const
std::size_t get_cardinality () const
bool is_large (unsigned int n_min) const
std::size_t memory_consumption () const
Private Attributes
std::vector< types::global_dof_index > index_set
std::array< types::global_dof_index, 2 > index_range
SimpleBoundingBox< spacedim, Number > bbox
Number diameter
Friends
template<int spacedim1, typename Number1 >
std::ostream & operator<< (std::ostream &out, const Cluster< spacedim1, Number1 > &cluster)
template<int spacedim1, typename Number1 >
Number1 calc_cluster_distance (const Cluster< spacedim1, Number1 > &cluster1, const Cluster< spacedim1, Number1 > &cluster2, const std::vector< Point< spacedim1, Number1 > > &all_support_points)
template<int spacedim1, typename Number1 >
Number1 calc_cluster_distance (const Cluster< spacedim1, Number1 > &cluster1, const Cluster< spacedim1, Number1 > &cluster2, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering, const std::vector< Point< spacedim1, Number1 > > &all_support_points)
template<int spacedim1, typename Number1 >
Number1 calc_cluster_distance (const Cluster< spacedim1, Number1 > &cluster1, const Cluster< spacedim1, Number1 > &cluster2, const std::vector< Point< spacedim1, Number1 > > &all_support_points1, const std::vector< Point< spacedim1, Number1 > > &all_support_points2)
template<int spacedim1, typename Number1 >
Number1 calc_cluster_distance (const Cluster< spacedim1, Number1 > &cluster1, const Cluster< spacedim1, Number1 > &cluster2, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering1, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering2, const std::vector< Point< spacedim1, Number1 > > &all_support_points1, const std::vector< Point< spacedim1, Number1 > > &all_support_points2)
template<int spacedim1, typename Number1 >
Number1 calc_cluster_distance (const Cluster< spacedim1, Number1 > &cluster1, const Cluster< spacedim1, Number1 > &cluster2, const std::vector< Point< spacedim1, Number1 > > &all_support_points, const std::vector< Number1 > &cell_size_at_dofs)
template<int spacedim1, typename Number1 >
Number1 calc_cluster_distance (const Cluster< spacedim1, Number1 > &cluster1, const Cluster< spacedim1, Number1 > &cluster2, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering, const std::vector< Point< spacedim1, Number1 > > &all_support_points, const std::vector< Number1 > &cell_size_at_dofs)
template<int spacedim1, typename Number1 >
Number1 calc_cluster_distance (const Cluster< spacedim1, Number1 > &cluster1, const Cluster< spacedim1, Number1 > &cluster2, const std::vector< Point< spacedim1, Number1 > > &all_support_points1, const std::vector< Point< spacedim1, Number1 > > &all_support_points2, const std::vector< Number1 > &cell_size_at_dofs1, const std::vector< Number1 > &cell_size_at_dofs2)
template<int spacedim1, typename Number1 >
Number1 calc_cluster_distance (const Cluster< spacedim1, Number1 > &cluster1, const Cluster< spacedim1, Number1 > &cluster2, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering1, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering2, const std::vector< Point< spacedim1, Number1 > > &all_support_points1, const std::vector< Point< spacedim1, Number1 > > &all_support_points2, const std::vector< Number1 > &cell_size_at_dofs1, const std::vector< Number1 > &cell_size_at_dofs2)
template<int spacedim1, typename Number1 >
bool operator== (const Cluster< spacedim1, Number1 > &cluster1, const Cluster< spacedim1, Number1 > &cluster2)
Detailed Description
template<int spacedim, typename Number = double>
class Cluster< spacedim, Number >
Class for an index cluster.
The Cluster class contains both the DoF index set index_set and the corresponding bounding box bbox.
Definition at line 48 of file cluster.h.
Constructor & Destructor Documentation
Cluster() [1/7]
template<int spacedim, typename Number > Cluster< spacedim, Number >::Cluster
Default constructor.
Definition at line 1230 of file cluster.h.
Cluster() [2/7]
template<int spacedim, typename Number > Cluster< spacedim, Number >::Cluster (const std::vector< types::global_dof_index > & index_set)
Constructor from an index set only without support points and associated bounding box.
Parameters
index_set
Definition at line 1239 of file cluster.h.
Cluster() [3/7]
template<int spacedim, typename Number > Cluster< spacedim, Number >::Cluster (const std::vector< types::global_dof_index > & index_set, const std::vector< Point< spacedim, Number > > & all_support_points)
Constructor from an index set without cluster diameter correction.
The bounding box will be recalculated.
Parameters
index_set
all_support_points
Definition at line 1249 of file cluster.h.
Cluster() [4/7]
template<int spacedim, typename Number > Cluster< spacedim, Number >::Cluster (const std::vector< types::global_dof_index > & index_set, const std::vector< Point< spacedim, Number > > & all_support_points, const std::vector< Number > & cell_size_at_dofs)
Constructor from an index set with cluster diameter correction.
The bounding box will be recalculated.
Parameters
index_set
all_support_points
Definition at line 1259 of file cluster.h.
Cluster() [5/7]
template<int spacedim, typename Number > Cluster< spacedim, Number >::Cluster (const std::vector< types::global_dof_index > & index_set, const SimpleBoundingBox< spacedim, Number > & bbox, const std::vector< Point< spacedim, Number > > & all_support_points)
Constructor from an index set and a bounding box without cluster diameter correction.
The input bounding box will be copied into the cluster without recalculation. However, the diameter of the cluster is recalculated.
Parameters
index_set
bbox
Definition at line 1270 of file cluster.h.
Cluster() [6/7]
template<int spacedim, typename Number > Cluster< spacedim, Number >::Cluster (const std::vector< types::global_dof_index > & index_set, const SimpleBoundingBox< spacedim, Number > & bbox, const std::vector< Point< spacedim, Number > > & all_support_points, const std::vector< Number > & cell_size_at_dofs)
Constructor from an index set and a bounding box with cluster diameter correction.
The input bounding box will be copied into the cluster without recalculation. However, the diameter of the cluster is recalculated.
Parameters
index_set
bbox
Definition at line 1281 of file cluster.h.
Cluster() [7/7]
template<int spacedim, typename Number > Cluster< spacedim, Number >::Cluster (const Cluster< spacedim, Number > & cluster)
Copy constructor.
Definition at line 1293 of file cluster.h.
Member Function Documentation
calc_diameter() [1/4]
template<int spacedim, typename Number > Number Cluster< spacedim, Number >::calc_diameter (const std::vector< Point< spacedim, Number > > & all_support_points) const
Calculate the diameter of the cluster. There is no cell size correction.
Calculate the number of point pairs in the cluster. Let \([0, 1, 2, 3, 4, 5]\) be the indices of support points in the cluster, whose pairwise inter-distance will be calculated. The calculation is only needed for the marked pairs of points as shown below.
  0 1 2 3 4 5
0   - - - - -
1     - - - -
2       - - -
3         - -
4           -
5
Definition at line 1367 of file cluster.h.
calc_diameter() [2/4]
template<int spacedim, typename Number > Number Cluster< spacedim, Number >::calc_diameter (const std::vector< Point< spacedim, Number > > & all_support_points, const std::vector< Number > & cell_size_at_dofs) const
Calculate the diameter of the cluster. Cell size correction is applied.
N.B. Doubled estimated cell size is adopted as an approximation of the support set diameter \({\rm diam}(Q_j)\). The correction is calculated according to the following formula.
\[ \widetilde{\rm diam}(\tau) := {\rm diam}(\hat{Q}_{\tau}) + \max_{j \in \tau} {\rm diam}(Q_j) \]
Parameters
all_support_points
cell_size_at_dofs
Returns
Definition at line 1483 of file cluster.h.
calc_diameter() [3/4]
template<int spacedim, typename Number > Number Cluster< spacedim, Number >::calc_diameter (const std::vector< types::global_dof_index > & internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > & all_support_points) const
Calculate the diameter of the cluster. There is no cell size correction.
Note
In this version, the index set held by the cluster is empty and the index range takes effect.
Parameters
internal_to_external_dof_numbering
all_support_points
Returns
Calculate the number of point pairs in the cluster. Let \([0, 1, 2, 3, 4, 5]\) be the indices of support points in the cluster, whose pairwise inter-distance will be calculated. The calculation is only needed for the marked pairs of points as shown below.
  0 1 2 3 4 5
0   - - - - -
1     - - - -
2       - - -
3         - -
4           -
5
Definition at line 1423 of file cluster.h.
calc_diameter() [4/4]
template<int spacedim, typename Number > Number Cluster< spacedim, Number >::calc_diameter (const std::vector< types::global_dof_index > & internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > & all_support_points, const std::vector< Number > & cell_size_at_dofs) const
Calculate the diameter of the cluster. Cell size correction is applied.
N.B. Doubled estimated cell size is adopted as an approximation of the support set diameter \({\rm diam}(Q_j)\). The correction is calculated according to the following formula.
\[ \widetilde{\rm diam}(\tau) := {\rm diam}(\hat{Q}_{\tau}) + \max_{j \in \tau} {\rm diam}(Q_j) \]
Note
In this version, the index set held by the cluster is empty and the index range takes effect.
Parameters
internal_to_external_dof_numbering
all_support_points
cell_size_at_dofs
Returns
Definition at line 1505 of file cluster.h.
distance_to_cluster() [1/8]
template<int spacedim, typename Number > Number Cluster< spacedim, Number >::distance_to_cluster (const Cluster< spacedim, Number > & cluster, const std::vector< Point< spacedim, Number > > & all_support_points) const
Calculate the minimum distance of the current cluster to the given cluster. There is no cell size correction.
Note
The index sets held by the two clusters share a same external DoF numbering.
Definition at line 1533 of file cluster.h.
References calc_cluster_distance().
distance_to_cluster() [2/8]
template<int spacedim, typename Number > Number Cluster< spacedim, Number >::distance_to_cluster (const Cluster< spacedim, Number > & cluster, const std::vector< Point< spacedim, Number > > & all_support_points, const std::vector< Number > & cell_size_at_dofs) const
Calculate the minimum distance of the current cluster to the given cluster. Cell size correction is applied.
Note
The index sets held by the two clusters share a same external DoF numbering.
Definition at line 1592 of file cluster.h.
References calc_cluster_distance().
distance_to_cluster() [3/8]
template<int spacedim, typename Number > Number Cluster< spacedim, Number >::distance_to_cluster (const Cluster< spacedim, Number > & cluster, const std::vector< Point< spacedim, Number > > & all_support_points1, const std::vector< Point< spacedim, Number > > & all_support_points2) const
Calculate the minimum distance of the current cluster to the given cluster. There is no cell size correction.
Note
The index sets held by the two clusters refer to two different external DoF numberings.
Parameters
cluster
all_support_points1
all_support_points2
Returns
Definition at line 1558 of file cluster.h.
References calc_cluster_distance().
distance_to_cluster() [4/8]
template<int spacedim, typename Number > Number Cluster< spacedim, Number >::distance_to_cluster (const Cluster< spacedim, Number > & cluster, const std::vector< Point< spacedim, Number > > & all_support_points1, const std::vector< Point< spacedim, Number > > & all_support_points2, const std::vector< Number > & cell_size_at_dofs1, const std::vector< Number > & cell_size_at_dofs2) const
Calculate the minimum distance of the current cluster to the given cluster. Cell size correction is applied.
Note
The index sets held by the two clusters refer to two different external DoF numberings.
Parameters
cluster
all_support_points1
all_support_points2
cell_size_at_dofs1
cell_size_at_dofs2
Returns
Definition at line 1623 of file cluster.h.
References calc_cluster_distance().
distance_to_cluster() [5/8]
template<int spacedim, typename Number > Number Cluster< spacedim, Number >::distance_to_cluster (const Cluster< spacedim, Number > & cluster, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > & all_support_points) const
Calculate the minimum distance of the current cluster to the given cluster. There is no cell size correction.
Note
The index sets inferred from the index ranges held by the two clusters share a same internal DoF numbering, which need to be mapped to the external numbering for accessing the list of support point coordinates.
Parameters
cluster
internal_to_external_dof_numbering
all_support_points
Returns
Definition at line 1543 of file cluster.h.
References calc_cluster_distance().
distance_to_cluster() [6/8]
template<int spacedim, typename Number > Number Cluster< spacedim, Number >::distance_to_cluster (const Cluster< spacedim, Number > & cluster, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > & all_support_points, const std::vector< Number > & cell_size_at_dofs) const
Calculate the minimum distance of the current cluster to the given cluster. Cell size correction is applied.
Note
The index sets inferred from the index ranges held by the two clusters share a same internal DoF numbering, which need to be mapped to the external numbering for accessing the list of support point coordinates.
Parameters
cluster
internal_to_external_dof_numbering
all_support_points
cell_size_at_dofs
Returns
Definition at line 1606 of file cluster.h.
References calc_cluster_distance().
distance_to_cluster() [7/8]
template<int spacedim, typename Number > Number Cluster< spacedim, Number >::distance_to_cluster (const Cluster< spacedim, Number > & cluster, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering1, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering2, const std::vector< Point< spacedim, Number > > & all_support_points1, const std::vector< Point< spacedim, Number > > & all_support_points2) const
Calculate the minimum distance of the current cluster to the given cluster. There is no cell size correction.
Note
The index sets inferred from the index ranges held by the two clusters refer to two different internal DoF numberings, which need to be mapped to their corresponding external numberings for accessing the list of support point coordinates.
Parameters
cluster
internal_to_external_dof_numbering1
internal_to_external_dof_numbering2
all_support_points1
all_support_points2
Returns
Definition at line 1572 of file cluster.h.
References calc_cluster_distance().
distance_to_cluster() [8/8]
template<int spacedim, typename Number > Number Cluster< spacedim, Number >::distance_to_cluster (const Cluster< spacedim, Number > & cluster, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering1, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering2, const std::vector< Point< spacedim, Number > > & all_support_points1, const std::vector< Point< spacedim, Number > > & all_support_points2, const std::vector< Number > & cell_size_at_dofs1, const std::vector< Number > & cell_size_at_dofs2) const
Calculate the minimum distance of the current cluster to the given cluster. Cell size correction is applied.
Note
The index sets inferred from the index ranges held by the two clusters refer to two different internal DoF numberings, which need to be mapped to their corresponding external numberings for accessing the list of support point coordinates.
Parameters
cluster
internal_to_external_dof_numbering1
internal_to_external_dof_numbering2
all_support_points1
all_support_points2
cell_size_at_dofs1
cell_size_at_dofs2
Returns
Definition at line 1641 of file cluster.h.
References calc_cluster_distance().
get_bounding_box() [1/2]
template<int spacedim, typename Number > SimpleBoundingBox< spacedim, Number > & Cluster< spacedim, Number >::get_bounding_box
Get the reference to the bounding box.
Definition at line 1346 of file cluster.h.
get_bounding_box() [2/2]
template<int spacedim, typename Number > const SimpleBoundingBox< spacedim, Number > & Cluster< spacedim, Number >::get_bounding_box
Get the reference to the bounding box (const version).
Definition at line 1353 of file cluster.h.
get_cardinality()
template<int spacedim, typename Number > std::size_t Cluster< spacedim, Number >::get_cardinality
Get the cardinality of the index set.
Returns
Definition at line 1833 of file cluster.h.
Referenced by operator<<().
get_diameter()
template<int spacedim, typename Number > Number Cluster< spacedim, Number >::get_diameter
Get the diameter of the cluster.
Definition at line 1360 of file cluster.h.
get_index_range() [1/2]
template<int spacedim, typename Number > std::array< types::global_dof_index, 2 > & Cluster< spacedim, Number >::get_index_range
Get the reference to the index range, which is in the internal numbering.
Returns
Definition at line 1317 of file cluster.h.
Referenced by calc_cluster_distance().
get_index_range() [2/2]
template<int spacedim, typename Number > const std::array< types::global_dof_index, 2 > & Cluster< spacedim, Number >::get_index_range
Get the reference to the index range, which is in the internal numbering (const version).
Returns
Definition at line 1325 of file cluster.h.
get_index_set() [1/2]
template<int spacedim, typename Number > std::vector< types::global_dof_index > & Cluster< spacedim, Number >::get_index_set
Get the reference to the index set.
Definition at line 1302 of file cluster.h.
Referenced by calc_cluster_distance().
get_index_set() [2/2]
template<int spacedim, typename Number > const std::vector< types::global_dof_index > & Cluster< spacedim, Number >::get_index_set
Get the reference to the index set (const version).
Definition at line 1309 of file cluster.h.
has_intersection()
template<int spacedim, typename Number > bool Cluster< spacedim, Number >::has_intersection (const Cluster< spacedim, Number > & cluster) const
Determine if the index set of the current cluster has a nonempty intersection with the index set of the given cluster.
Note
The index sets associated with clusters should be sorted before calling this function. In the current implementation of cluster tree construction, all the index sets have already been sorted.
Parameters
cluster
Returns
Definition at line 1798 of file cluster.h.
References Cluster< spacedim, Number >::index_set.
intersect() [1/2]
template<int spacedim, typename Number > void Cluster< spacedim, Number >::intersect (const Cluster< spacedim, Number > & cluster, std::array< types::global_dof_index, 2 > & index_range_intersection) const
Calculate the intersection of the index ranges of the current and the given clusters.
Parameters
cluster
index_range_intersection
Definition at line 1786 of file cluster.h.
intersect() [2/2]
template<int spacedim, typename Number > void Cluster< spacedim, Number >::intersect (const Cluster< spacedim, Number > & cluster, std::vector< types::global_dof_index > & index_set_intersection) const
Calculate the intersection of the index sets of the current and the given clusters.
Note
The index sets associated with clusters should be sorted before calling this function. In the current implementation of cluster tree construction, all the index sets have already been sorted.
Parameters
cluster
index_set_intersection
Definition at line 1766 of file cluster.h.
References Cluster< spacedim, Number >::index_set.
is_large()
template<int spacedim, typename Number > bool Cluster< spacedim, Number >::is_large (unsigned int n_min) const
Determine if the cluster is large enough.
Parameters
n_min The size threshold value for determining if a cluster is large.
Returns
Definition at line 1847 of file cluster.h.
is_proper_subset()
template<int spacedim, typename Number > bool Cluster< spacedim, Number >::is_proper_subset (const Cluster< spacedim, Number > & cluster) const
Check if the index set of the current cluster is a proper subset of that of the given cluster.
Note
The index sets associated with clusters should be sorted before calling this function. In the current implementation of cluster tree construction, all the index sets have already been sorted.
Parameters
cluster
Returns
Definition at line 1683 of file cluster.h.
References Cluster< spacedim, Number >::index_range, Cluster< spacedim, Number >::index_set, and is_proper_subset().
is_proper_superset()
template<int spacedim, typename Number > bool Cluster< spacedim, Number >::is_proper_superset (const Cluster< spacedim, Number > & cluster) const
Check if the index set of the current cluster is a proper superset of that of the given cluster.
Note
The index sets associated with clusters should be sorted before calling this function. In the current implementation of cluster tree construction, all the index sets have already been sorted.
Parameters
cluster
Returns
Definition at line 1733 of file cluster.h.
References Cluster< spacedim, Number >::index_range, Cluster< spacedim, Number >::index_set, and is_proper_superset().
is_subset()
template<int spacedim, typename Number > bool Cluster< spacedim, Number >::is_subset (const Cluster< spacedim, Number > & cluster) const
Check if the index set of the current cluster is a subset of that of the given cluster.
Note
The index sets associated with clusters should be sorted before calling this function. In the current implementation of cluster tree construction, all the index sets have already been sorted.
Parameters
cluster
Returns
Definition at line 1665 of file cluster.h.
References Cluster< spacedim, Number >::index_range, Cluster< spacedim, Number >::index_set, and is_subset().
is_superset()
template<int spacedim, typename Number > bool Cluster< spacedim, Number >::is_superset (const Cluster< spacedim, Number > & cluster) const
Check if the index set of the current cluster is a superset of that of the given cluster.
Note
The index sets associated with clusters should be sorted before calling this function. In the current implementation of cluster tree construction, all the index sets have already been sorted.
Parameters
cluster
Returns
Definition at line 1715 of file cluster.h.
References Cluster< spacedim, Number >::index_range, Cluster< spacedim, Number >::index_set, and is_superset().
memory_consumption()
template<int spacedim, typename Number > std::size_t Cluster< spacedim, Number >::memory_consumption
Estimate the memory consumption of the cluster.
Definition at line 1862 of file cluster.h.
set_index_range()
template<int spacedim, typename Number > void Cluster< spacedim, Number >::set_index_range (const types::global_dof_index lower_bound, const types::global_dof_index pass_upper_bound)
Set the index range, which is in the internal numbering. After the index range is set, the original index set will be immediately cleared for saving memory.
Parameters
lower_bound
upper_bound
Definition at line 1333 of file cluster.h.
Friends And Related Function Documentation
operator==
template<int spacedim, typename Number = double> template<int spacedim1, typename Number1 > bool operator== (const Cluster< spacedim1, Number1 > & cluster1, const Cluster< spacedim1, Number1 > & cluster2) friend
Check the equality of two clusters by comparing their index sets.
This function firstly check the equality of the sizes/cardinalities of the index sets in the two clusters. If their sizes are equal, then
if the size is larger than 0, which means the index set is not empty and the index range is still not generated, then compare the contents in the index set.
if the size is 0, which means the index set has been cleared and the index range has been generated, then compare the contents in the index range.
Parameters
cluster1
cluster2
Returns
Member Data Documentation
bbox
template<int spacedim, typename Number = double> SimpleBoundingBox<spacedim, Number> Cluster< spacedim, Number >::bbox private
Definition at line 645 of file cluster.h.
diameter
template<int spacedim, typename Number = double> Number Cluster< spacedim, Number >::diameter private
Definition at line 646 of file cluster.h.
index_range
template<int spacedim, typename Number = double> std::array<types::global_dof_index, 2> Cluster< spacedim, Number >::index_range private
The DoF index range in the internal numbering.
Definition at line 644 of file cluster.h.
Referenced by Cluster< spacedim, Number >::is_proper_subset(), Cluster< spacedim, Number >::is_proper_superset(), Cluster< spacedim, Number >::is_subset(), Cluster< spacedim, Number >::is_superset(), and operator<<().
index_set
template<int spacedim, typename Number = double> std::vector<types::global_dof_index> Cluster< spacedim, Number >::index_set private
The list of DoF indices.
Definition at line 640 of file cluster.h.
Referenced by Cluster< spacedim, Number >::has_intersection(), Cluster< spacedim, Number >::intersect(), Cluster< spacedim, Number >::is_proper_subset(), Cluster< spacedim, Number >::is_proper_superset(), Cluster< spacedim, Number >::is_subset(), Cluster< spacedim, Number >::is_superset(), and operator<<().
The documentation for this class was generated from the following file:
include/cluster_tree/cluster.h