HierBEM: parse_result Class Reference
parse_result Class Reference
The result of a parsing operation.
#include <parse_result.hpp>
Classes
struct storage_t
Public Member Functions
TOML_NODISCARD_CTOR parse_result () noexcept
Default constructs an 'error' result.
TOML_NODISCARD_CTOR parse_result (toml::table &&tbl) noexcept
TOML_NODISCARD_CTOR parse_result (parse_error &&err) noexcept
TOML_NODISCARD_CTOR parse_result (parse_result &&res) noexcept
Move constructor.
parse_result & operator= (parse_result &&rhs) noexcept
Move-assignment operator.
~parse_result () noexcept
Destructor.
Result state
TOML_NODISCARD bool succeeded () const noexcept
Returns true if parsing succeeeded.
TOML_NODISCARD bool failed () const noexcept
Returns true if parsing failed.
TOML_NODISCARD operator bool () const noexcept
Returns true if parsing succeeded.
Successful parses
Warning
It is undefined behaviour to call these functions when the result respresents a failed parse. Check failed(), succeeded or operator bool() to determine the result's state.
TOML_NODISCARD toml::table & table () &noexcept
Returns the internal toml::table.
TOML_NODISCARD toml::table && table () &&noexcept
Returns the internal toml::table (rvalue overload).
TOML_NODISCARD const toml::table & table () const &noexcept
Returns the internal toml::table (const lvalue overload).
TOML_NODISCARD operator toml::table & () noexcept
Returns the internal toml::table.
TOML_NODISCARD operator toml::table && () noexcept
Returns the internal toml::table (rvalue overload).
TOML_NODISCARD operator const toml::table & () const noexcept
Returns the internal toml::table (const lvalue overload).
Failed parses
Warning
It is undefined behaviour to call these functions when the result respresents a successful parse. Check failed(), succeeded or operator bool() to determine the result's state.
TOML_NODISCARD parse_error & error () &noexcept
Returns the internal toml::parse_error.
TOML_NODISCARD parse_error && error () &&noexcept
Returns the internal toml::parse_error (rvalue overload).
TOML_NODISCARD const parse_error & error () const &noexcept
Returns the internal toml::parse_error (const lvalue overload).
TOML_NODISCARD operator parse_error & () noexcept
Returns the internal toml::parse_error.
TOML_NODISCARD operator parse_error && () noexcept
Returns the internal toml::parse_error (rvalue overload).
TOML_NODISCARD operator const parse_error & () const noexcept
Returns the internal toml::parse_error (const lvalue overload).
Node views
TOML_NODISCARD node_view< node > at_path (std::string_view path) noexcept
Returns a view of the subnode matching a fully-qualified "TOML path".
TOML_NODISCARD node_view< const node > at_path (std::string_view path) const noexcept
Returns a const view of the subnode matching a fully-qualified "TOML path".
TOML_NODISCARD node_view< node > at_path (const toml::path &path) noexcept
Returns a view of the subnode matching a fully-qualified "TOML path".
TOML_NODISCARD node_view< const node > at_path (const toml::path &path) const noexcept
Returns a const view of the subnode matching a fully-qualified "TOML path".
TOML_NODISCARD node_view< node > at_path (std::wstring_view path)
Returns a view of the subnode matching a fully-qualified "TOML path".
TOML_NODISCARD node_view< const node > at_path (std::wstring_view path) const
Returns a const view of the subnode matching a fully-qualified "TOML path".
TOML_NODISCARD node_view< node > operator[] (const toml::path &path) noexcept
Returns a view of the subnode matching a fully-qualified "TOML path".
TOML_NODISCARD node_view< const node > operator[] (const toml::path &path) const noexcept
Returns a const view of the subnode matching a fully-qualified "TOML path".
TOML_NODISCARD node_view< node > operator[] (std::string_view key) noexcept
Gets a node_view for the selected key-value pair in the wrapped table.
TOML_NODISCARD node_view< const node > operator[] (std::string_view key) const noexcept
Gets a node_view for the selected key-value pair in the wrapped table (const overload).
TOML_NODISCARD node_view< node > operator[] (std::wstring_view key)
Gets a node_view for the selected key-value pair in the wrapped table.
TOML_NODISCARD node_view< const node > operator[] (std::wstring_view key) const
Gets a node_view for the selected key-value pair in the wrapped table (const overload).
Private Member Functions
void destroy () noexcept
Static Private Member Functions
template<typename Type >
TOML_NODISCARD static TOML_ALWAYS_INLINE Type * get_as (storage_t &s) noexcept
Private Attributes
storage_t storage_
bool err_
Friends
std::ostream & operator<< (std::ostream &os, const parse_result &result)
Prints the held error or table object out to a text stream.
Iteration
using iterator = table_iterator
A BidirectionalIterator for iterating over key-value pairs in a wrapped toml::table.
using const_iterator = const_table_iterator
A BidirectionalIterator for iterating over const key-value pairs in a wrapped toml::table.
TOML_NODISCARD table_iterator begin () noexcept
Returns an iterator to the first key-value pair in the wrapped table.
TOML_NODISCARD const_table_iterator begin () const noexcept
Returns an iterator to the first key-value pair in the wrapped table.
TOML_NODISCARD const_table_iterator cbegin () const noexcept
Returns an iterator to the first key-value pair in the wrapped table.
TOML_NODISCARD table_iterator end () noexcept
Returns an iterator to one-past-the-last key-value pair in the wrapped table.
TOML_NODISCARD const_table_iterator end () const noexcept
Returns an iterator to one-past-the-last key-value pair in the wrapped table.
TOML_NODISCARD const_table_iterator cend () const noexcept
Returns an iterator to one-past-the-last key-value pair in the wrapped table.
Detailed Description
The result of a parsing operation.
\availability This type only exists when exceptions are disabled. Otherwise parse_result is just an alias for toml::table: \cpp #if TOML_EXCEPTIONS using parse_result = table; #else class parse_result { // ... #endif \ecpp
\detail A parse_result is effectively a discriminated union containing either a toml::table or a toml::parse_error. Most member functions assume a particular one of these two states, and calling them when in the wrong state will cause errors (e.g. attempting to access the error object when parsing was successful). \cpp toml::parse_result result = toml::parse_file("config.toml"); if (result) do_stuff_with_a_table(result); //implicitly converts to table& else std::cerr << "Parse failed:\n"sv << result.error() << "\n"; \ecpp
\out example output:
Parse failed: Encountered unexpected character while parsing boolean; expected 'true', saw 'trU' (error occurred at line 1, column 13 of 'config.toml') \eout
Getting node_views (operator[], at_path()) and using the iterator accessor functions (begin(), end() etc.) are unconditionally safe; when parsing fails these just return 'empty' values. A ranged-for loop on a failed parse_result is also safe since begin() and end() return the same iterator and will not lead to any dereferences and iterations.
Definition at line 52 of file parse_result.hpp.
Member Typedef Documentation
const_iterator
using parse_result::const_iterator = const_table_iterator
A BidirectionalIterator for iterating over const key-value pairs in a wrapped toml::table.
Definition at line 283 of file parse_result.hpp.
iterator
using parse_result::iterator = table_iterator
A BidirectionalIterator for iterating over key-value pairs in a wrapped toml::table.
Definition at line 280 of file parse_result.hpp.
Constructor & Destructor Documentation
parse_result() [1/4]
TOML_NODISCARD_CTOR parse_result::parse_result () inline noexcept
Default constructs an 'error' result.
Definition at line 87 of file parse_result.hpp.
parse_result() [2/4]
TOML_NODISCARD_CTOR parse_result::parse_result (toml::table && tbl) inline explicit noexcept
Definition at line 94 of file parse_result.hpp.
parse_result() [3/4]
TOML_NODISCARD_CTOR parse_result::parse_result (parse_error && err) inline explicit noexcept
Definition at line 101 of file parse_result.hpp.
parse_result() [4/4]
TOML_NODISCARD_CTOR parse_result::parse_result (parse_result && res) inline noexcept
Move constructor.
Definition at line 109 of file parse_result.hpp.
~parse_result()
parse_result::~parse_result () inline noexcept
Destructor.
Definition at line 141 of file parse_result.hpp.
Member Function Documentation
at_path() [1/6]
TOML_NODISCARD node_view< const node > parse_result::at_path (const toml::path & path) const inline noexcept
Returns a const view of the subnode matching a fully-qualified "TOML path".
See also
#toml::node::at_path(const toml::path&)
Definition at line 366 of file parse_result.hpp.
References table().
at_path() [2/6]
TOML_NODISCARD node_view< node > parse_result::at_path (const toml::path & path) inline noexcept
Returns a view of the subnode matching a fully-qualified "TOML path".
See also
#toml::node::at_path(const toml::path&)
Definition at line 357 of file parse_result.hpp.
References table().
at_path() [3/6]
TOML_NODISCARD node_view< const node > parse_result::at_path (std::string_view path) const inline noexcept
Returns a const view of the subnode matching a fully-qualified "TOML path".
See also
#toml::node::at_path(std::string_view)
Definition at line 348 of file parse_result.hpp.
References table().
at_path() [4/6]
TOML_NODISCARD node_view< node > parse_result::at_path (std::string_view path) inline noexcept
Returns a view of the subnode matching a fully-qualified "TOML path".
See also
#toml::node::at_path(std::string_view)
Definition at line 339 of file parse_result.hpp.
References table().
at_path() [5/6]
TOML_NODISCARD node_view< node > parse_result::at_path (std::wstring_view path) inline
Returns a view of the subnode matching a fully-qualified "TOML path".
\availability This overload is only available when TOML_ENABLE_WINDOWS_COMPAT is enabled.
See also
#toml::node::at_path(std::string_view)
Definition at line 379 of file parse_result.hpp.
References table().
at_path() [6/6]
TOML_NODISCARD node_view< const node > parse_result::at_path (std::wstring_view path) const inline
Returns a const view of the subnode matching a fully-qualified "TOML path".
\availability This overload is only available when TOML_ENABLE_WINDOWS_COMPAT is enabled.
See also
#toml::node::at_path(std::string_view)
Definition at line 390 of file parse_result.hpp.
References table().
begin() [1/2]
TOML_NODISCARD const_table_iterator parse_result::begin () const inline noexcept
Returns an iterator to the first key-value pair in the wrapped table.
Remarks
Always returns the same value as end() if parsing failed.
Definition at line 296 of file parse_result.hpp.
References table().
begin() [2/2]
TOML_NODISCARD table_iterator parse_result::begin () inline noexcept
Returns an iterator to the first key-value pair in the wrapped table.
Remarks
Always returns the same value as end() if parsing failed.
Definition at line 288 of file parse_result.hpp.
References table().
cbegin()
TOML_NODISCARD const_table_iterator parse_result::cbegin () const inline noexcept
Returns an iterator to the first key-value pair in the wrapped table.
Remarks
Always returns the same value as cend() if parsing failed.
Definition at line 304 of file parse_result.hpp.
References table().
cend()
TOML_NODISCARD const_table_iterator parse_result::cend () const inline noexcept
Returns an iterator to one-past-the-last key-value pair in the wrapped table.
Definition at line 325 of file parse_result.hpp.
References table().
destroy()
void parse_result::destroy () inline private noexcept
Definition at line 76 of file parse_result.hpp.
end() [1/2]
TOML_NODISCARD const_table_iterator parse_result::end () const inline noexcept
Returns an iterator to one-past-the-last key-value pair in the wrapped table.
Definition at line 318 of file parse_result.hpp.
References table().
end() [2/2]
TOML_NODISCARD table_iterator parse_result::end () inline noexcept
Returns an iterator to one-past-the-last key-value pair in the wrapped table.
Definition at line 311 of file parse_result.hpp.
References table().
error() [1/3]
TOML_NODISCARD parse_error && parse_result::error () && inline noexcept
Returns the internal toml::parse_error (rvalue overload).
Definition at line 239 of file parse_result.hpp.
error() [2/3]
TOML_NODISCARD parse_error & parse_result::error () & inline noexcept
Returns the internal toml::parse_error.
Definition at line 231 of file parse_result.hpp.
Referenced by operator const parse_error &(), operator parse_error &(), operator parse_error &&(), and operator=().
error() [3/3]
TOML_NODISCARD const parse_error & parse_result::error () const & inline noexcept
Returns the internal toml::parse_error (const lvalue overload).
Definition at line 247 of file parse_result.hpp.
failed()
TOML_NODISCARD bool parse_result::failed () const inline noexcept
Returns true if parsing failed.
Definition at line 158 of file parse_result.hpp.
get_as()
template<typename Type > TOML_NODISCARD static TOML_ALWAYS_INLINE Type * parse_result::get_as (storage_t & s) inline static private noexcept
Definition at line 71 of file parse_result.hpp.
operator bool()
TOML_NODISCARD parse_result::operator bool () const inline explicit noexcept
Returns true if parsing succeeded.
Definition at line 165 of file parse_result.hpp.
operator const parse_error &()
TOML_NODISCARD parse_result::operator const parse_error & () const inline explicit noexcept
Returns the internal toml::parse_error (const lvalue overload).
Definition at line 269 of file parse_result.hpp.
References error().
operator const toml::table &()
TOML_NODISCARD parse_result::operator const toml::table & () const inline noexcept
Returns the internal toml::table (const lvalue overload).
Definition at line 217 of file parse_result.hpp.
References table().
operator parse_error &()
TOML_NODISCARD parse_result::operator parse_error & () inline explicit noexcept
Returns the internal toml::parse_error.
Definition at line 255 of file parse_result.hpp.
References error().
operator parse_error &&()
TOML_NODISCARD parse_result::operator parse_error && () inline explicit noexcept
Returns the internal toml::parse_error (rvalue overload).
Definition at line 262 of file parse_result.hpp.
References error().
operator toml::table &()
TOML_NODISCARD parse_result::operator toml::table & () inline noexcept
Returns the internal toml::table.
Definition at line 203 of file parse_result.hpp.
References table().
operator toml::table &&()
TOML_NODISCARD parse_result::operator toml::table && () inline noexcept
Returns the internal toml::table (rvalue overload).
Definition at line 210 of file parse_result.hpp.
References table().
operator=()
parse_result & parse_result::operator= (parse_result && rhs) inline noexcept
Move-assignment operator.
Definition at line 119 of file parse_result.hpp.
References error(), and table().
operator[]() [1/6]
TOML_NODISCARD node_view< const node > parse_result::operator[] (const toml::path & path) const inline noexcept
Returns a const view of the subnode matching a fully-qualified "TOML path".
See also
#toml::node::operator[](const toml::path&)
Definition at line 410 of file parse_result.hpp.
References table().
operator[]() [2/6]
TOML_NODISCARD node_view< node > parse_result::operator[] (const toml::path & path) inline noexcept
Returns a view of the subnode matching a fully-qualified "TOML path".
See also
#toml::node::operator[](const toml::path&)
Definition at line 401 of file parse_result.hpp.
References table().
operator[]() [3/6]
TOML_NODISCARD node_view< const node > parse_result::operator[] (std::string_view key) const inline noexcept
Gets a node_view for the selected key-value pair in the wrapped table (const overload).
Parameters
key The key used for the lookup.
Returns
A view of the value at the given key if parsing was successful and a matching key existed, or an empty node view.
See also
toml::node_view
Definition at line 438 of file parse_result.hpp.
References table().
operator[]() [4/6]
TOML_NODISCARD node_view< node > parse_result::operator[] (std::string_view key) inline noexcept
Gets a node_view for the selected key-value pair in the wrapped table.
Parameters
key The key used for the lookup.
Returns
A view of the value at the given key if parsing was successful and a matching key existed, or an empty node view.
See also
toml::node_view
Definition at line 424 of file parse_result.hpp.
References table().
operator[]() [5/6]
TOML_NODISCARD node_view< node > parse_result::operator[] (std::wstring_view key) inline
Gets a node_view for the selected key-value pair in the wrapped table.
\availability This overload is only available when TOML_ENABLE_WINDOWS_COMPAT is enabled.
Parameters
key The key used for the lookup.
Returns
A view of the value at the given key if parsing was successful and a matching key existed, or an empty node view.
See also
toml::node_view
Definition at line 456 of file parse_result.hpp.
References table().
operator[]() [6/6]
TOML_NODISCARD node_view< const node > parse_result::operator[] (std::wstring_view key) const inline
Gets a node_view for the selected key-value pair in the wrapped table (const overload).
\availability This overload is only available when TOML_ENABLE_WINDOWS_COMPAT is enabled.
Parameters
key The key used for the lookup.
Returns
A view of the value at the given key if parsing was successful and a matching key existed, or an empty node view.
See also
toml::node_view
Definition at line 472 of file parse_result.hpp.
References table().
succeeded()
TOML_NODISCARD bool parse_result::succeeded () const inline noexcept
Returns true if parsing succeeeded.
Definition at line 151 of file parse_result.hpp.
table() [1/3]
TOML_NODISCARD toml::table && parse_result::table () && inline noexcept
Returns the internal toml::table (rvalue overload).
Definition at line 187 of file parse_result.hpp.
table() [2/3]
TOML_NODISCARD toml::table & parse_result::table () & inline noexcept
Returns the internal toml::table.
Definition at line 179 of file parse_result.hpp.
Referenced by at_path(), begin(), cbegin(), cend(), end(), operator const toml::table &(), operator toml::table &(), operator toml::table &&(), operator=(), and operator[]().
table() [3/3]
TOML_NODISCARD const toml::table & parse_result::table () const & inline noexcept
Returns the internal toml::table (const lvalue overload).
Definition at line 195 of file parse_result.hpp.
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const parse_result & result) friend
Prints the held error or table object out to a text stream.
\availability This operator is only available when TOML_ENABLE_FORMATTERS is enabled.
Definition at line 486 of file parse_result.hpp.
Member Data Documentation
err_
bool parse_result::err_ private
Definition at line 66 of file parse_result.hpp.
storage_
storage_t parse_result::storage_ mutable private
Definition at line 65 of file parse_result.hpp.
The documentation for this class was generated from the following file:
/home/jihuan/Projects/hierbem/vcpkg_installed/x64-linux/include/toml++/impl/parse_result.hpp