HierBEM: CUDAWrappers::CUDAFullMatrix< T > Class Template Reference
CUDAWrappers::CUDAFullMatrix< T > Class Template Reference
Public Types
using pointer = T *
using const_pointer = const T *
using reference = T &
using const_reference = const T &
using size_type = std::size_t
Public Member Functions
HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix ()
HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix (pointer p, const size_type _rows, const size_type _cols)
HBEM_ATTR_HOST HBEM_ATTR_DEV void reinit (pointer p, const size_type _rows, const size_type _cols)
HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix (const CUDAFullMatrix< T > &)=delete
HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix (CUDAFullMatrix< T > &&mat)
HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T > & operator= (const CUDAFullMatrix< T > &mat)
HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T > & operator= (CUDAFullMatrix< T > &&mat)
HBEM_ATTR_HOST HBEM_ATTR_DEV void fill (const_pointer data)
HBEM_ATTR_HOST HBEM_ATTR_DEV size_type m () const
HBEM_ATTR_HOST HBEM_ATTR_DEV size_type n () const
HBEM_ATTR_HOST HBEM_ATTR_DEV size_type n_elements () const
HBEM_ATTR_HOST HBEM_ATTR_DEV size_type size (const size_type i) const
HBEM_ATTR_HOST HBEM_ATTR_DEV pointer data ()
HBEM_ATTR_HOST HBEM_ATTR_DEV const_pointer data () const
HBEM_ATTR_HOST HBEM_ATTR_DEV reference operator() (const size_type i, const size_type j, const bool is_column_major=true)
HBEM_ATTR_HOST HBEM_ATTR_DEV const_reference operator() (const size_type i, const size_type j, const bool is_column_major=true) const
HBEM_ATTR_HOST HBEM_ATTR_DEV void vmult (CUDAVector< T > &w, const CUDAVector< T > &v, const bool adding=false) const
HBEM_ATTR_HOST HBEM_ATTR_DEV void Tvmult (CUDAVector< T > &w, const CUDAVector< T > &v, const bool adding=false) const
HBEM_ATTR_HOST HBEM_ATTR_DEV void mmult (CUDAFullMatrix< T > &C, const CUDAFullMatrix< T > &B, const bool adding=false) const
HBEM_ATTR_HOST HBEM_ATTR_DEV void Tmmult (CUDAFullMatrix< T > &C, const CUDAFullMatrix< T > &B, const bool adding=false) const
HBEM_ATTR_HOST HBEM_ATTR_DEV void mTmult (CUDAFullMatrix< T > &C, const CUDAFullMatrix< T > &B, const bool adding=false) const
HBEM_ATTR_HOST HBEM_ATTR_DEV void invert_by_gauss_elim (CUDAFullMatrix< T > &M_inv)
HBEM_ATTR_HOST HBEM_ATTR_DEV void invert2x2 (const CUDAFullMatrix< T > &M)
HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T > & operator*= (const T factor)
HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T > & operator/= (const T factor)
HBEM_ATTR_HOST HBEM_ATTR_DEV T determinant2x2 () const
HBEM_ATTR_HOST HBEM_ATTR_DEV T determinant3x3 () const
HBEM_ATTR_HOST HBEM_ATTR_DEV void print (const bool C_index_style=false, const bool scientific=true) const
HBEM_ATTR_HOST HBEM_ATTR_DEV void reinit ()
Private Attributes
pointer values
size_type rows
size_type cols
Detailed Description
template<typename T = double>
class CUDAWrappers::CUDAFullMatrix< T >
Definition at line 33 of file cu_fullmatrix.hcu.
Member Typedef Documentation
const_pointer
template<typename T = double> using CUDAWrappers::CUDAFullMatrix< T >::const_pointer = const T *
Definition at line 37 of file cu_fullmatrix.hcu.
const_reference
template<typename T = double> using CUDAWrappers::CUDAFullMatrix< T >::const_reference = const T &
Definition at line 39 of file cu_fullmatrix.hcu.
pointer
template<typename T = double> using CUDAWrappers::CUDAFullMatrix< T >::pointer = T *
Definition at line 36 of file cu_fullmatrix.hcu.
reference
template<typename T = double> using CUDAWrappers::CUDAFullMatrix< T >::reference = T &
Definition at line 38 of file cu_fullmatrix.hcu.
size_type
template<typename T = double> using CUDAWrappers::CUDAFullMatrix< T >::size_type = std::size_t
Definition at line 40 of file cu_fullmatrix.hcu.
Constructor & Destructor Documentation
CUDAFullMatrix() [1/4]
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAWrappers::CUDAFullMatrix< T >::CUDAFullMatrix
Default constructor.
Definition at line 336 of file cu_fullmatrix.hcu.
CUDAFullMatrix() [2/4]
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAWrappers::CUDAFullMatrix< T >::CUDAFullMatrix (pointer p, const size_type _rows, const size_type _cols)
Constructor
Parameters
p
_rows
_cols
Definition at line 345 of file cu_fullmatrix.hcu.
CUDAFullMatrix() [3/4]
template<typename T = double> HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAWrappers::CUDAFullMatrix< T >::CUDAFullMatrix (const CUDAFullMatrix< T > &) delete
Deep copy constructor is disabled. Since this class has no memory allocation, which is merely a wrapper, and because all memory allocation on GPU has been performed in the host code by calling cudaMalloc, the copy constructor is disabled.
Parameters
CUDAFullMatrix() [4/4]
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAWrappers::CUDAFullMatrix< T >::CUDAFullMatrix (CUDAFullMatrix< T > && mat)
Shallow copy constructor is still available.
Parameters
mat
Definition at line 368 of file cu_fullmatrix.hcu.
Member Function Documentation
data() [1/2]
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T >::pointer CUDAWrappers::CUDAFullMatrix< T >::data inline
Get the internal data pointer.
Returns
Definition at line 460 of file cu_fullmatrix.hcu.
data() [2/2]
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T >::const_pointer CUDAWrappers::CUDAFullMatrix< T >::data inline
Get the internal data pointer (const version).
Returns
Definition at line 468 of file cu_fullmatrix.hcu.
determinant2x2()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV T CUDAWrappers::CUDAFullMatrix< T >::determinant2x2
Calculate the determinant of a \(2\times 2\) matrix.
Returns
Definition at line 798 of file cu_fullmatrix.hcu.
Referenced by CUDAWrappers::CUDAFullMatrix< T >::invert2x2().
determinant3x3()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV T CUDAWrappers::CUDAFullMatrix< T >::determinant3x3
Calculate the determinant of a \(3\times 3\) matrix.
Returns
Definition at line 806 of file cu_fullmatrix.hcu.
fill()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV void CUDAWrappers::CUDAFullMatrix< T >::fill (const_pointer data)
Fill the matrix from a pointer to the source data.
Definition at line 405 of file cu_fullmatrix.hcu.
invert2x2()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV void CUDAWrappers::CUDAFullMatrix< T >::invert2x2 (const CUDAFullMatrix< T > & M)
Assign the inverse of the given 2x2 matrix to *this.
Let
\[ M = \begin{pmatrix} a & b \\ c & d \end{pmatrix} \]
\[ M^{-1} = \frac{1}{\abs{M}} \begin{pmatrix} d & -b \\ -c & a \end{pmatrix} \]
Parameters
inv
Definition at line 755 of file cu_fullmatrix.hcu.
References CUDAWrappers::CUDAFullMatrix< T >::determinant2x2(), CUDAWrappers::CUDAFullMatrix< T >::m(), and CUDAWrappers::CUDAFullMatrix< T >::n().
invert_by_gauss_elim()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV void CUDAWrappers::CUDAFullMatrix< T >::invert_by_gauss_elim (CUDAFullMatrix< T > & M_inv)
Compute the inverse of the matrix using Gauss elimination.
Before calling this function, the output matrix M_inv should be reinitialized to zero.
Parameters
M_inv
Eliminate the lower triangular part of the matrix.
Scale the current row by the factor \(\frac{1}{a_{ll}}\) and this value is directly filled into the result matrix.
For the matrix \(M\), after this scaling, the element \(M_{ll}\) will become 1, there is no need to compute the scaling of this element. Meanwhile, the elements \(M_{l1}, \cdots, M_{l,l-1}\) are already zeros after previous eliminations, neither need we compute the scaling of these elements. Therefore, the actual computation to be performed is for columns \(j = l + 1, \cdots, n\).
For the matrix \(M^{-1}\), after this scaling, the element at \((l, l)\) will be \(\frac{1}{M_{ll}}\), so there is no need to compute this scaling. Meanwhile, only those elements \(M^{-1}_{l,1}, \cdots, M^{-1}_{l-1}\) may be non-zeros, we only loop over \(j = 1, \cdots, l - 1\).
Then we eliminate the elements \(M_{l+1,l}, \cdots, M_{n,l}\) by iterating over the rows \(l + 1, \cdots, n\).
This transformation will only influence the columns \(1, \cdots, l\) in \(M^{-1}\).
This transformation will only influence the columns \(l+1, \cdots, n\) in \(M\).
Eliminate the upper triangular part. Now the row transformation is only related to the result matrix \(M^{-1}\).
Eliminate the elements \(M_{l-1,l}, \cdots, M_{1,l}\).
N.B. When the loop counter i of unsigned type decreased to be zero, further decrement will not produce a value smaller than zero but a very large integer. Hence, we do not use a typical for loop here as below.
for (size_type i = l - 1; i >= 0; i–) { ... }
Instead, we use a while loop with the true condition. Inside this loop, when we detect the counter is zero after loop execution, we jump out the loop.
Because the elements in the current l'th row of \(M^{-1}\) are generally non-zeros, the computation involves columns \(1, \cdots, n\).
Definition at line 629 of file cu_fullmatrix.hcu.
References CUDAWrappers::CUDAFullMatrix< T >::m(), CUDAWrappers::CUDAFullMatrix< T >::n(), and CUDAWrappers::CUDAFullMatrix< T >::reinit().
m()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T >::size_type CUDAWrappers::CUDAFullMatrix< T >::m inline
Get the number of rows.
Returns
Definition at line 416 of file cu_fullmatrix.hcu.
Referenced by CUDAWrappers::CUDAFullMatrix< T >::invert2x2(), CUDAWrappers::CUDAFullMatrix< T >::invert_by_gauss_elim(), CUDAWrappers::CUDAFullMatrix< T >::mmult(), CUDAWrappers::CUDAFullMatrix< T >::mTmult(), and CUDAWrappers::CUDAFullMatrix< T >::Tmmult().
mmult()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV void CUDAWrappers::CUDAFullMatrix< T >::mmult (CUDAFullMatrix< T > & C, const CUDAFullMatrix< T > & B, const bool adding = false) const
Perform matrix-matrix multiplication \(C = A B\). When adding is true, compute \(C = C + A B\).
Parameters
C
B
adding
Definition at line 545 of file cu_fullmatrix.hcu.
References CUDAWrappers::CUDAFullMatrix< T >::m(), and CUDAWrappers::CUDAFullMatrix< T >::n().
mTmult()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV void CUDAWrappers::CUDAFullMatrix< T >::mTmult (CUDAFullMatrix< T > & C, const CUDAFullMatrix< T > & B, const bool adding = false) const
Perform matrix-matrix multiplication \(C = A B^T\). When adding is true, compute \(C = C + A B^T\).
Parameters
C
B
adding
Definition at line 601 of file cu_fullmatrix.hcu.
References CUDAWrappers::CUDAFullMatrix< T >::m(), and CUDAWrappers::CUDAFullMatrix< T >::n().
n()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T >::size_type CUDAWrappers::CUDAFullMatrix< T >::n inline
Get the number of columns.
Returns
Definition at line 424 of file cu_fullmatrix.hcu.
Referenced by CUDAWrappers::CUDAFullMatrix< T >::invert2x2(), CUDAWrappers::CUDAFullMatrix< T >::invert_by_gauss_elim(), CUDAWrappers::CUDAFullMatrix< T >::mmult(), CUDAWrappers::CUDAFullMatrix< T >::mTmult(), and CUDAWrappers::CUDAFullMatrix< T >::Tmmult().
n_elements()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T >::size_type CUDAWrappers::CUDAFullMatrix< T >::n_elements inline
Get the total number of matrix entries.
Returns
Definition at line 432 of file cu_fullmatrix.hcu.
operator()() [1/2]
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T >::reference CUDAWrappers::CUDAFullMatrix< T >::operator() (const size_type i, const size_type j, const bool is_column_major = true) inline
Get the reference to the matrix entry \((i,j)\).
Parameters
i
j
Returns
Definition at line 476 of file cu_fullmatrix.hcu.
operator()() [2/2]
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T >::const_reference CUDAWrappers::CUDAFullMatrix< T >::operator() (const size_type i, const size_type j, const bool is_column_major = true) const inline
Get the const reference to the matrix entry \((i,j)\).
Parameters
i
j
Returns
Definition at line 487 of file cu_fullmatrix.hcu.
operator*=()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T > & CUDAWrappers::CUDAFullMatrix< T >::operator*= (const T factor)
Scale all matrix entries by the factor.
Parameters
factor
Returns
Definition at line 772 of file cu_fullmatrix.hcu.
operator/=()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T > & CUDAWrappers::CUDAFullMatrix< T >::operator/= (const T factor)
Divide all matrix entires by the factor.
Parameters
factor
Returns
Definition at line 785 of file cu_fullmatrix.hcu.
operator=() [1/2]
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T > & CUDAWrappers::CUDAFullMatrix< T >::operator= (const CUDAFullMatrix< T > & mat)
Deep assignment. N.B. The target matrix must have the same sizes as the source matrix.
Parameters
mat
Returns
Definition at line 377 of file cu_fullmatrix.hcu.
operator=() [2/2]
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T > & CUDAWrappers::CUDAFullMatrix< T >::operator= (CUDAFullMatrix< T > && mat)
Shallow assignment.
Parameters
mat
Returns
Definition at line 393 of file cu_fullmatrix.hcu.
print()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV void CUDAWrappers::CUDAFullMatrix< T >::print (const bool C_index_style = false, const bool scientific = true) const
Print all the values in the matrix using the specified C or Fortran index style.
Definition at line 819 of file cu_fullmatrix.hcu.
reinit() [1/2]
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV void CUDAWrappers::CUDAFullMatrix< T >::reinit
Set all matrix entries to zero.
Definition at line 845 of file cu_fullmatrix.hcu.
reinit() [2/2]
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV void CUDAWrappers::CUDAFullMatrix< T >::reinit (pointer p, const size_type _rows, const size_type _cols)
Reinitialize the current matrix wrapper with new pointer and dimension.
Definition at line 356 of file cu_fullmatrix.hcu.
Referenced by CUDAWrappers::CUDAFullMatrix< T >::invert_by_gauss_elim().
size()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV CUDAFullMatrix< T >::size_type CUDAWrappers::CUDAFullMatrix< T >::size (const size_type i) const
Get the size in the specified dimension.
Parameters
i
Returns
Definition at line 440 of file cu_fullmatrix.hcu.
Tmmult()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV void CUDAWrappers::CUDAFullMatrix< T >::Tmmult (CUDAFullMatrix< T > & C, const CUDAFullMatrix< T > & B, const bool adding = false) const
Perform matrix-matrix multiplication \(C = A^T B\). When adding is true, compute \(C = C + A^T B\).
Parameters
C
B
adding
Definition at line 573 of file cu_fullmatrix.hcu.
References CUDAWrappers::CUDAFullMatrix< T >::m(), and CUDAWrappers::CUDAFullMatrix< T >::n().
Tvmult()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV void CUDAWrappers::CUDAFullMatrix< T >::Tvmult (CUDAVector< T > & w, const CUDAVector< T > & v, const bool adding = false) const
Perform matrix-vector multiplication \(w = A^Tv\). When adding is true, compute \(w = A^Tv + w\).
Parameters
w
v
adding
Definition at line 521 of file cu_fullmatrix.hcu.
References CUDAWrappers::CUDAVector< T >::size().
vmult()
template<typename T > HBEM_ATTR_HOST HBEM_ATTR_DEV void CUDAWrappers::CUDAFullMatrix< T >::vmult (CUDAVector< T > & w, const CUDAVector< T > & v, const bool adding = false) const
Perform matrix-vector multiplication \(w = Av\). When adding is true, compute \(w = Av + w\).
Parameters
w
v
adding
Definition at line 497 of file cu_fullmatrix.hcu.
References CUDAWrappers::CUDAVector< T >::size().
Member Data Documentation
cols
template<typename T = double> size_type CUDAWrappers::CUDAFullMatrix< T >::cols private
Definition at line 330 of file cu_fullmatrix.hcu.
rows
template<typename T = double> size_type CUDAWrappers::CUDAFullMatrix< T >::rows private
Definition at line 329 of file cu_fullmatrix.hcu.
values
template<typename T = double> pointer CUDAWrappers::CUDAFullMatrix< T >::values private
Definition at line 328 of file cu_fullmatrix.hcu.
The documentation for this class was generated from the following file:
include/linear_algebra/cu_fullmatrix.hcu