HierBEM: DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType > Class Template Reference
DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType > Class Template Reference
Public Types
using real_type = typename numbers::NumberTraits< RangeNumberType >::real_type
Public Member Functions
DDMEfield (const unsigned int fe_order_for_dirichlet_space, const unsigned int fe_order_for_neumann_space, const unsigned int n_min_for_ct, const unsigned int n_min_for_bct, const real_type eta, const unsigned int max_hmat_rank, const real_type aca_relative_error, const real_type eta_for_preconditioner, const unsigned int max_hmat_rank_for_preconditioner, const real_type aca_relative_error_for_preconditioner, const unsigned int thread_num)
void read_subdomain_topology (const std::string &cad_file, const std::string &mesh_file)
void initialize_parameters ()
void initialize_manifolds_and_mappings ()
void interpolate_surface_dirichlet_bc ()
void create_efield_subdomains_and_surfaces ()
void initialize_subdomain_hmatrices ()
void collect_cell_iterators ()
void setup_system ()
void assemble_system ()
void assemble_preconditioner ()
void solve ()
void output_results ()
const SubdomainTopology< dim, spacedim > & get_subdomain_topology () const
SubdomainTopology< dim, spacedim > & get_subdomain_topology ()
const Triangulation< dim, spacedim > & get_triangulation () const
Triangulation< dim, spacedim > & get_triangulation ()
Static Public Attributes
static const unsigned int max_mapping_order = 3
Private Attributes
SubdomainTopology< dim, spacedim > subdomain_topology
EfieldSubdomainDescription< spacedim, RangeNumberType > domain
Triangulation< dim, spacedim > tria
std::vector< MappingInfo< dim, spacedim > * > mappings
HierBEM::PlatformShared::LaplaceKernel::SingleLayerKernel< 3, KernelNumberType > single_layer_kernel
HierBEM::PlatformShared::LaplaceKernel::DoubleLayerKernel< 3, KernelNumberType > double_layer_kernel
HierBEM::PlatformShared::LaplaceKernel::HyperSingularKernelRegular< 3, KernelNumberType > hyper_singular_kernel
DoFHandler< dim, spacedim > dof_handler_for_dirichlet_space
DoFHandler< dim, spacedim > dof_handler_for_neumann_space
std::string project_name
unsigned int fe_order_for_dirichlet_space
unsigned int fe_order_for_neumann_space
FE_Q< dim, spacedim > fe_for_dirichlet_space
FE_DGQ< dim, spacedim > fe_for_neumann_space
std::vector< typename DoFHandler< dim, spacedim >::cell_iterator > cell_iterators_for_dirichlet_space
std::vector< typename DoFHandler< dim, spacedim >::cell_iterator > cell_iterators_for_neumann_space
DoFToCellTopology< dim, spacedim > dof_to_cell_topo_for_dirichlet_space
DoFToCellTopology< dim, spacedim > dof_to_cell_topo_for_neumann_space
unsigned int n_min_for_ct
unsigned int n_min_for_bct
real_type eta
unsigned int max_hmat_rank
real_type aca_relative_error
real_type eta_for_preconditioner
unsigned int max_hmat_rank_for_preconditioner
real_type aca_relative_error_for_preconditioner
unsigned int thread_num
DDMEfieldMatrix< spacedim, RangeNumberType > system_matrix
DDMEfieldGlobalPreconditioner< spacedim, RangeNumberType > system_preconditioner
Vector< RangeNumberType > rhs_for_transmission_eqn
Vector< RangeNumberType > rhs_for_charge_neutrality_eqn
Vector< RangeNumberType > dirichlet_bc
std::map< EntityTag, SubdomainType > subdomain_types
std::map< EntityTag, RangeNumberType > permittivities
std::map< EntityTag, RangeNumberType > conductor_voltages
std::map< EntityTag, Function< spacedim, RangeNumberType > * > dirichlet_boundary_conditions
std::map< EntityTag, types::manifold_id > manifold_description
std::map< types::manifold_id, Manifold< dim, spacedim > * > manifolds
std::map< types::manifold_id, unsigned int > manifold_id_to_mapping_order
Detailed Description
template<int dim, int spacedim, typename RangeNumberType, typename KernelNumberType>
class DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >
Definition at line 380 of file ddm_efield.h.
Member Typedef Documentation
real_type
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > using DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::real_type = typename numbers::NumberTraits<RangeNumberType>::real_type
Definition at line 383 of file ddm_efield.h.
Constructor & Destructor Documentation
DDMEfield() [1/2]
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::DDMEfield
Definition at line 652 of file ddm_efield.h.
DDMEfield() [2/2]
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::DDMEfield (const unsigned int fe_order_for_dirichlet_space, const unsigned int fe_order_for_neumann_space, const unsigned int n_min_for_ct, const unsigned int n_min_for_bct, const real_type eta, const unsigned int max_hmat_rank, const real_type aca_relative_error, const real_type eta_for_preconditioner, const unsigned int max_hmat_rank_for_preconditioner, const real_type aca_relative_error_for_preconditioner, const unsigned int thread_num)
Definition at line 674 of file ddm_efield.h.
~DDMEfield()
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::~DDMEfield
Definition at line 707 of file ddm_efield.h.
Member Function Documentation
assemble_system()
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > void DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::assemble_system
Define the ACAConfig object.
Definition at line 1500 of file ddm_efield.h.
collect_cell_iterators()
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > void DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::collect_cell_iterators
Definition at line 1440 of file ddm_efield.h.
create_efield_subdomains_and_surfaces()
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > void DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::create_efield_subdomains_and_surfaces
Definition at line 877 of file ddm_efield.h.
get_subdomain_topology() [1/2]
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > SubdomainTopology< dim, spacedim > & DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::get_subdomain_topology () inline
Definition at line 476 of file ddm_efield.h.
get_subdomain_topology() [2/2]
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > const SubdomainTopology< dim, spacedim > & DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::get_subdomain_topology () const inline
Definition at line 470 of file ddm_efield.h.
get_triangulation() [1/2]
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > Triangulation< dim, spacedim > & DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::get_triangulation () inline
Definition at line 488 of file ddm_efield.h.
get_triangulation() [2/2]
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > const Triangulation< dim, spacedim > & DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::get_triangulation () const inline
Definition at line 482 of file ddm_efield.h.
initialize_manifolds_and_mappings()
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > void DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::initialize_manifolds_and_mappings
Definition at line 800 of file ddm_efield.h.
initialize_parameters()
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > void DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::initialize_parameters
Manually initialize problem parameters for testing purpose.
Precondition
Postcondition
Definition at line 748 of file ddm_efield.h.
initialize_subdomain_hmatrices()
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > void DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::initialize_subdomain_hmatrices
Initialize \(\mathcal{H}\)-matrices for each dielectric subdomain.
Precondition
Postcondition
Build the DoF-to-cell topology.
Note
Access of this topology for the Dirichlet space requires the map from local to full DoF indices.
Definition at line 1092 of file ddm_efield.h.
References ClusterTree< spacedim, Number >::get_external_to_internal_dof_numbering(), ClusterTree< spacedim, Number >::get_internal_to_external_dof_numbering(), ClusterTree< spacedim, Number >::partition(), and BlockClusterTree< spacedim, Number >::partition().
interpolate_surface_dirichlet_bc()
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > void DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::interpolate_surface_dirichlet_bc
Interpolate Dirichlet boundary conditions on dielectric surfaces or interfaces.
Precondition
Postcondition
Definition at line 848 of file ddm_efield.h.
output_results()
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > void DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::output_results
Definition at line 1521 of file ddm_efield.h.
read_subdomain_topology()
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > void DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::read_subdomain_topology (const std::string & cad_file, const std::string & mesh_file)
Read the CAD file and build the association relationship between volumes and surfaces.
Precondition
Postcondition
Parameters
cad_file
Definition at line 735 of file ddm_efield.h.
setup_system()
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > void DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::setup_system
Definition at line 1465 of file ddm_efield.h.
Member Data Documentation
aca_relative_error
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > real_type DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::aca_relative_error private
Relative approximation error used in ACA+. At present, assume all \(\mathcal{H}\)-matrices share this same parameter.
Definition at line 587 of file ddm_efield.h.
aca_relative_error_for_preconditioner
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > real_type DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::aca_relative_error_for_preconditioner private
Relative approximation error used in ACA+ for the preconditioner.
Definition at line 599 of file ddm_efield.h.
cell_iterators_for_dirichlet_space
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > std::vector<typename DoFHandler<dim, spacedim>::cell_iterator> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::cell_iterators_for_dirichlet_space private
Definition at line 552 of file ddm_efield.h.
cell_iterators_for_neumann_space
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > std::vector<typename DoFHandler<dim, spacedim>::cell_iterator> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::cell_iterators_for_neumann_space private
Definition at line 554 of file ddm_efield.h.
conductor_voltages
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > std::map<EntityTag, RangeNumberType> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::conductor_voltages private
Map volume entity tag to voltages of conductors.
Definition at line 626 of file ddm_efield.h.
dirichlet_bc
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > Vector<RangeNumberType> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::dirichlet_bc private
Dirichlet boundary condition data on all DoFs in the associated DoF handler.
Definition at line 613 of file ddm_efield.h.
dirichlet_boundary_conditions
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > std::map<EntityTag, Function<spacedim, RangeNumberType> *> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::dirichlet_boundary_conditions private
Map surface entity tag to Dirichlet boundary condition.
Definition at line 631 of file ddm_efield.h.
dof_handler_for_dirichlet_space
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > DoFHandler<dim, spacedim> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::dof_handler_for_dirichlet_space private
Dirichlet space on the whole skeleton.
Definition at line 522 of file ddm_efield.h.
dof_handler_for_neumann_space
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > DoFHandler<dim, spacedim> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::dof_handler_for_neumann_space private
Neumann space on the whole skeleton.
Definition at line 526 of file ddm_efield.h.
dof_to_cell_topo_for_dirichlet_space
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > DoFToCellTopology<dim, spacedim> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::dof_to_cell_topo_for_dirichlet_space private
DoF-to-cell topologies for various DoF handlers, which are used for matrix assembly on a pair of DoFs.
Definition at line 560 of file ddm_efield.h.
dof_to_cell_topo_for_neumann_space
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > DoFToCellTopology<dim, spacedim> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::dof_to_cell_topo_for_neumann_space private
Definition at line 561 of file ddm_efield.h.
domain
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > EfieldSubdomainDescription<spacedim, RangeNumberType> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::domain private
Definition at line 495 of file ddm_efield.h.
double_layer_kernel
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > HierBEM::PlatformShared::LaplaceKernel::DoubleLayerKernel<3, KernelNumberType> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::double_layer_kernel private
Kernel function for the double layer potential.
Definition at line 511 of file ddm_efield.h.
eta
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > real_type DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::eta private
Admissibility constant. At present, assume all block cluster trees share this same parameter.
Definition at line 577 of file ddm_efield.h.
eta_for_preconditioner
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > real_type DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::eta_for_preconditioner private
Admissibility constant for the preconditioner.
Definition at line 591 of file ddm_efield.h.
fe_for_dirichlet_space
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > FE_Q<dim, spacedim> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::fe_for_dirichlet_space private
Finite element \(H^{\frac{1}{2}+s}\) for the Dirichlet space. At present, it is implemented as a continuous Lagrange space.
Definition at line 544 of file ddm_efield.h.
fe_for_neumann_space
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > FE_DGQ<dim, spacedim> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::fe_for_neumann_space private
Finite element \(H^{-\frac{1}{2}+s}\) for the Neumann space. At present, it is implemented as a discontinuous Lagrange space.
Definition at line 549 of file ddm_efield.h.
fe_order_for_dirichlet_space
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > unsigned int DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::fe_order_for_dirichlet_space private
Finite element order for the Dirichlet space.
Definition at line 533 of file ddm_efield.h.
fe_order_for_neumann_space
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > unsigned int DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::fe_order_for_neumann_space private
Finite element order for the Neumann space.
Definition at line 538 of file ddm_efield.h.
hyper_singular_kernel
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > HierBEM::PlatformShared::LaplaceKernel:: HyperSingularKernelRegular<3, KernelNumberType> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::hyper_singular_kernel private
Kernel function for the hyper-singular potential.
Definition at line 517 of file ddm_efield.h.
manifold_description
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > std::map<EntityTag, types::manifold_id> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::manifold_description private
Map surface entity tag to manifold id. At the moment, the material for each surface is the same as the entity tag in Gmsh.
Definition at line 636 of file ddm_efield.h.
manifold_id_to_mapping_order
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > std::map<types::manifold_id, unsigned int> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::manifold_id_to_mapping_order private
Map manifold_id to mapping order.
Definition at line 644 of file ddm_efield.h.
manifolds
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > std::map<types::manifold_id, Manifold<dim, spacedim> *> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::manifolds private
Map manifold_id to the pointer of a Manifold object.
Definition at line 640 of file ddm_efield.h.
mappings
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > std::vector<MappingInfo<dim, spacedim> *> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::mappings private
A list of mapping objects from 1st to 3rd order.
Definition at line 500 of file ddm_efield.h.
max_hmat_rank
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > unsigned int DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::max_hmat_rank private
Maximum rank of the \(\mathcal{H}\)-matrices to be built. At present, assume all \(\mathcal{H}\)-matrices share this same parameter.
Definition at line 582 of file ddm_efield.h.
max_hmat_rank_for_preconditioner
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > unsigned int DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::max_hmat_rank_for_preconditioner private
Maximum rank of the \(\mathcal{H}\)-matrices to be built for the preconditioner.
Definition at line 595 of file ddm_efield.h.
max_mapping_order
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > const unsigned int DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::max_mapping_order = 3 inline static
Maximum mapping order.
Definition at line 388 of file ddm_efield.h.
n_min_for_bct
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > unsigned int DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::n_min_for_bct private
Minimum block cluster size. At present, assume all block cluster trees share this same parameter.
Definition at line 572 of file ddm_efield.h.
n_min_for_ct
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > unsigned int DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::n_min_for_ct private
Minimum cluster size. At present, assume all block cluster trees share this same parameter.
Definition at line 567 of file ddm_efield.h.
permittivities
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > std::map<EntityTag, RangeNumberType> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::permittivities private
Map volume entity tag to permittivity.
Definition at line 622 of file ddm_efield.h.
project_name
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > std::string DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::project_name private
Definition at line 528 of file ddm_efield.h.
rhs_for_charge_neutrality_eqn
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > Vector<RangeNumberType> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::rhs_for_charge_neutrality_eqn private
Definition at line 607 of file ddm_efield.h.
rhs_for_transmission_eqn
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > Vector<RangeNumberType> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::rhs_for_transmission_eqn private
Definition at line 606 of file ddm_efield.h.
single_layer_kernel
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > HierBEM::PlatformShared::LaplaceKernel::SingleLayerKernel<3, KernelNumberType> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::single_layer_kernel private
Kernel function for the single layer potential.
Definition at line 506 of file ddm_efield.h.
subdomain_topology
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > SubdomainTopology<dim, spacedim> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::subdomain_topology private
Definition at line 494 of file ddm_efield.h.
subdomain_types
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > std::map<EntityTag, SubdomainType> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::subdomain_types private
Map volume entity tag to subdomain type.
Definition at line 618 of file ddm_efield.h.
system_matrix
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > DDMEfieldMatrix<spacedim, RangeNumberType> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::system_matrix private
Definition at line 603 of file ddm_efield.h.
system_preconditioner
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > DDMEfieldGlobalPreconditioner<spacedim, RangeNumberType> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::system_preconditioner private
Definition at line 605 of file ddm_efield.h.
thread_num
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > unsigned int DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::thread_num private
Definition at line 601 of file ddm_efield.h.
tria
template<int dim, int spacedim, typename RangeNumberType , typename KernelNumberType > Triangulation<dim, spacedim> DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::tria private
Definition at line 496 of file ddm_efield.h.
The documentation for this class was generated from the following file:
include/electric_field/ddm_efield.h