HierBEM: ClusterTree< spacedim, Number > Class Template Reference
ClusterTree< spacedim, Number > Class Template Reference
Class for cluster tree.
#include <cluster_tree.h>
Public Types
typedef BinaryTreeNode< Cluster< spacedim, Number > > node_value_type
typedef BinaryTreeNode< Cluster< spacedim, Number > > * node_pointer_type
typedef const BinaryTreeNode< Cluster< spacedim, Number > > * node_const_pointer_type
typedef BinaryTreeNode< Cluster< spacedim, Number > > & node_reference_type
typedef const BinaryTreeNode< Cluster< spacedim, Number > > & node_const_reference_type
typedef Cluster< spacedim, Number > data_value_type
typedef Cluster< spacedim, Number > * data_pointer_type
typedef const Cluster< spacedim, Number > * data_const_pointer_type
typedef Cluster< spacedim, Number > & data_reference_type
typedef const Cluster< spacedim, Number > & data_const_reference_type
Public Member Functions
ClusterTree ()
ClusterTree (const std::vector< types::global_dof_index > &index_set, const unsigned int n_min)
ClusterTree (const std::vector< types::global_dof_index > &index_set, const std::vector< Point< spacedim, Number > > &all_support_points, const unsigned int n_min)
ClusterTree (const std::vector< types::global_dof_index > &index_set, const std::vector< Point< spacedim, Number > > &all_support_points, const std::vector< Number > &cell_size_at_dofs, const unsigned int n_min)
ClusterTree (const ClusterTree< spacedim, Number > &cluster_tree)
~ClusterTree ()
void release ()
ClusterTree< spacedim, Number > & operator= (const ClusterTree< spacedim, Number > &cluster_tree)
ClusterTree< spacedim, Number > & operator= (ClusterTree< spacedim, Number > &&cluster_tree)
void partition ()
void partition (const std::vector< Point< spacedim, Number > > &all_support_points)
void partition (const std::vector< Point< spacedim, Number > > &all_support_points, const std::vector< Number > &cell_size_at_dofs)
node_pointer_type get_root () const
std::vector< node_pointer_type > & get_leaf_set ()
const std::vector< node_pointer_type > & get_leaf_set () const
void build_leaf_set ()
void build_cluster_set_at_level (const unsigned int level, std::vector< node_pointer_type > &cluster_set)
std::vector< types::global_dof_index > & get_internal_to_external_dof_numbering ()
const std::vector< types::global_dof_index > & get_internal_to_external_dof_numbering () const
std::vector< types::global_dof_index > & get_external_to_internal_dof_numbering ()
const std::vector< types::global_dof_index > & get_external_to_internal_dof_numbering () const
unsigned int get_n_min () const
unsigned int get_depth () const
unsigned int get_max_level () const
unsigned int get_node_num () const
void print_tree_info_as_dot (std::ostream &out) const
bool is_index_sets_cleared () const
std::size_t memory_consumption () const
std::size_t memory_consumption_of_all_clusters () const
Static Public Attributes
static const unsigned int child_num = 2
Private Member Functions
void _print_tree_info_as_dot_node (std::ostream &out, node_const_pointer_type cluster_node) const
void partition_from_cluster_node (node_pointer_type current_cluster_node, std::vector< node_pointer_type > &leaf_set_wrt_current_node)
void partition_from_cluster_node (node_pointer_type current_cluster_node, const std::vector< Point< spacedim, Number > > &all_support_points, std::vector< node_pointer_type > &leaf_set_wrt_current_node)
void partition_from_cluster_node (node_pointer_type current_cluster_node, const std::vector< Point< spacedim, Number > > &all_support_points, const std::vector< Number > &cell_size_at_dofs, std::vector< node_pointer_type > &leaf_set_wrt_current_node)
void build_internal_and_external_dof_numbering_mappings ()
void set_index_ranges_and_clear_index_sets ()
void set_index_ranges_and_clear_index_sets_from_cluster_node (node_pointer_type current_cluster_node)
Private Attributes
node_pointer_type root_node
std::vector< node_pointer_type > leaf_set
std::vector< types::global_dof_index > internal_to_external_dof_numbering
std::vector< types::global_dof_index > external_to_internal_dof_numbering
unsigned int depth
int max_level
unsigned int n_min
unsigned int node_num
bool index_sets_cleared
Friends
template<int spacedim1, typename Number1 >
std::ostream & operator<< (std::ostream &out, const ClusterTree< spacedim1, Number1 > &cluster_tree)
Detailed Description
template<int spacedim, typename Number = double>
class ClusterTree< spacedim, Number >
Class for cluster tree.
A cluster tree is a binary tree which holds a hierarchy of linked nodes with the type BinaryTreeNode.
Definition at line 30 of file cluster_tree.h.
Member Typedef Documentation
data_const_pointer_type
template<int spacedim, typename Number = double> typedef const Cluster<spacedim, Number>* ClusterTree< spacedim, Number >::data_const_pointer_type
Const pointer type for the content held by a node in the ClusterTree.
Definition at line 78 of file cluster_tree.h.
data_const_reference_type
template<int spacedim, typename Number = double> typedef const Cluster<spacedim, Number>& ClusterTree< spacedim, Number >::data_const_reference_type
Const reference type for the content held by a node in the ClusterTree.
Definition at line 86 of file cluster_tree.h.
data_pointer_type
template<int spacedim, typename Number = double> typedef Cluster<spacedim, Number>* ClusterTree< spacedim, Number >::data_pointer_type
Pointer type for the content held by a node in the ClusterTree.
Definition at line 74 of file cluster_tree.h.
data_reference_type
template<int spacedim, typename Number = double> typedef Cluster<spacedim, Number>& ClusterTree< spacedim, Number >::data_reference_type
Reference type for the content held by a node in the ClusterTree.
Definition at line 82 of file cluster_tree.h.
data_value_type
template<int spacedim, typename Number = double> typedef Cluster<spacedim, Number> ClusterTree< spacedim, Number >::data_value_type
Data type for the content held by a node in the ClusterTree.
Definition at line 70 of file cluster_tree.h.
node_const_pointer_type
template<int spacedim, typename Number = double> typedef const BinaryTreeNode<Cluster<spacedim, Number> >* ClusterTree< spacedim, Number >::node_const_pointer_type
Const pointer type for a node in the ClusterTree.
Definition at line 56 of file cluster_tree.h.
node_const_reference_type
template<int spacedim, typename Number = double> typedef const BinaryTreeNode<Cluster<spacedim, Number> >& ClusterTree< spacedim, Number >::node_const_reference_type
Const reference type for a node in the ClusterTree.
Definition at line 65 of file cluster_tree.h.
node_pointer_type
template<int spacedim, typename Number = double> typedef BinaryTreeNode<Cluster<spacedim, Number> >* ClusterTree< spacedim, Number >::node_pointer_type
Pointer type for a node in the ClusterTree.
Definition at line 51 of file cluster_tree.h.
node_reference_type
template<int spacedim, typename Number = double> typedef BinaryTreeNode<Cluster<spacedim, Number> >& ClusterTree< spacedim, Number >::node_reference_type
Reference type for a node in the ClusterTree.
Definition at line 60 of file cluster_tree.h.
node_value_type
template<int spacedim, typename Number = double> typedef BinaryTreeNode<Cluster<spacedim, Number> > ClusterTree< spacedim, Number >::node_value_type
Data type for a node in the ClusterTree.
Definition at line 47 of file cluster_tree.h.
Constructor & Destructor Documentation
ClusterTree() [1/5]
template<int spacedim, typename Number > ClusterTree< spacedim, Number >::ClusterTree
Default constructor, which initializes an empty binary tree.
Definition at line 582 of file cluster_tree.h.
ClusterTree() [2/5]
template<int spacedim, typename Number > ClusterTree< spacedim, Number >::ClusterTree (const std::vector< types::global_dof_index > & index_set, const unsigned int n_min)
Construct from only an index set without support point and the partition will be only based on the cardinality of the index set.
Parameters
index_set
n_min
Definition at line 596 of file cluster_tree.h.
References ClusterTree< spacedim, Number >::depth, ClusterTree< spacedim, Number >::external_to_internal_dof_numbering, ClusterTree< spacedim, Number >::internal_to_external_dof_numbering, ClusterTree< spacedim, Number >::max_level, and ClusterTree< spacedim, Number >::node_num.
ClusterTree() [3/5]
template<int spacedim, typename Number > ClusterTree< spacedim, Number >::ClusterTree (const std::vector< types::global_dof_index > & index_set, const std::vector< Point< spacedim, Number > > & all_support_points, const unsigned int n_min)
Constructor from a full index set and associated support point coordinates.
This constructor will create the root node of the cluster tree based on the given data. There is no mesh cell size correction for the cluster diameter.
Parameters
index_set The full DoF index set, which will be assigned to the root node.
all_support_points All the support points.
n_min
Definition at line 625 of file cluster_tree.h.
References ClusterTree< spacedim, Number >::depth, ClusterTree< spacedim, Number >::external_to_internal_dof_numbering, ClusterTree< spacedim, Number >::internal_to_external_dof_numbering, ClusterTree< spacedim, Number >::max_level, and ClusterTree< spacedim, Number >::node_num.
ClusterTree() [4/5]
template<int spacedim, typename Number > ClusterTree< spacedim, Number >::ClusterTree (const std::vector< types::global_dof_index > & index_set, const std::vector< Point< spacedim, Number > > & all_support_points, const std::vector< Number > & cell_size_at_dofs, const unsigned int n_min)
Constructor from a full index set and associated support point coordinates.
This constructor will create the root node of the cluster tree based on the given data. There is mesh cell size correction for the cluster diameter.
Parameters
index_set The full DoF index set, which will be assigned to the root node.
all_support_points All the support points.
cell_size_at_dofs
n_min
Definition at line 658 of file cluster_tree.h.
References ClusterTree< spacedim, Number >::depth, ClusterTree< spacedim, Number >::external_to_internal_dof_numbering, ClusterTree< spacedim, Number >::internal_to_external_dof_numbering, ClusterTree< spacedim, Number >::max_level, and ClusterTree< spacedim, Number >::node_num.
ClusterTree() [5/5]
template<int spacedim, typename Number > ClusterTree< spacedim, Number >::ClusterTree (const ClusterTree< spacedim, Number > & cluster_tree)
Copy constructor.
Parameters
cluster_tree
Definition at line 693 of file cluster_tree.h.
References ClusterTree< spacedim, Number >::build_leaf_set(), CopyTree(), and ClusterTree< spacedim, Number >::get_root().
~ClusterTree()
template<int spacedim, typename Number > ClusterTree< spacedim, Number >::~ClusterTree
Destructor which recursively destroys every node in the cluster tree.
Definition at line 713 of file cluster_tree.h.
Member Function Documentation
_print_tree_info_as_dot_node()
template<int spacedim, typename Number > void ClusterTree< spacedim, Number >::_print_tree_info_as_dot_node (std::ostream & out, node_const_pointer_type cluster_node) const private
Print the block cluster tree hierarchy information recursively as a node in the directional graph in GraphViz dot format.
Parameters
out
Create the graph node for the current cluster node.
Construct the relationship between the current node and its children.
Print each child node.
Definition at line 1622 of file cluster_tree.h.
References BinaryTreeNode< T >::get_level().
build_cluster_set_at_level()
template<int spacedim, typename Number = double> void ClusterTree< spacedim, Number >::build_cluster_set_at_level (const unsigned int level, std::vector< node_pointer_type > & cluster_set)
Build the set of clusters at the specified tree level.
Parameters
level
cluster_set
Definition at line 1487 of file cluster_tree.h.
References GetTreeNodesAtLevel().
build_internal_and_external_dof_numbering_mappings()
template<int spacedim, typename Number > void ClusterTree< spacedim, Number >::build_internal_and_external_dof_numbering_mappings private
Build the internal-to-external and external-to-internal DoF numberings by iterating over the leaf set.
Note
Since the leaf set has been constructed using recursion and whenever we come to a cluster node, its left child node is processed before the right child node, the cluster nodes in the leaf set are naturally ordered.
Definition at line 1338 of file cluster_tree.h.
build_leaf_set()
template<int spacedim, typename Number > void ClusterTree< spacedim, Number >::build_leaf_set
Build the leaf set by tree recursion.
Definition at line 1477 of file cluster_tree.h.
References GetTreeLeaves().
Referenced by ClusterTree< spacedim, Number >::ClusterTree().
get_depth()
template<int spacedim, typename Number > unsigned int ClusterTree< spacedim, Number >::get_depth
Get the tree depth.
Definition at line 1539 of file cluster_tree.h.
get_external_to_internal_dof_numbering() [1/2]
template<int spacedim, typename Number > std::vector< types::global_dof_index > & ClusterTree< spacedim, Number >::get_external_to_internal_dof_numbering
Get the reference to the external-to-internal DoF numbering.
Returns
Definition at line 1516 of file cluster_tree.h.
Referenced by DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::initialize_subdomain_hmatrices().
get_external_to_internal_dof_numbering() [2/2]
template<int spacedim, typename Number > const std::vector< types::global_dof_index > & ClusterTree< spacedim, Number >::get_external_to_internal_dof_numbering
Get the reference to the external-to-internal DoF numbering (const version).
Returns
Definition at line 1524 of file cluster_tree.h.
get_internal_to_external_dof_numbering() [1/2]
template<int spacedim, typename Number > std::vector< types::global_dof_index > & ClusterTree< spacedim, Number >::get_internal_to_external_dof_numbering
Get the reference to the internal-to-external DoF numbering.
Returns
Definition at line 1500 of file cluster_tree.h.
Referenced by DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::initialize_subdomain_hmatrices().
get_internal_to_external_dof_numbering() [2/2]
template<int spacedim, typename Number > const std::vector< types::global_dof_index > & ClusterTree< spacedim, Number >::get_internal_to_external_dof_numbering
Get the reference to the internal-to-external DoF numbering (const version).
Returns
Definition at line 1508 of file cluster_tree.h.
get_leaf_set() [1/2]
template<int spacedim, typename Number > std::vector< typename ClusterTree< spacedim, Number >::node_pointer_type > & ClusterTree< spacedim, Number >::get_leaf_set
Get the reference to the block cluster list.
Definition at line 1461 of file cluster_tree.h.
get_leaf_set() [2/2]
template<int spacedim, typename Number > const std::vector< typename ClusterTree< spacedim, Number >::node_pointer_type > & ClusterTree< spacedim, Number >::get_leaf_set
Get the reference to the block cluster list (const version).
Definition at line 1469 of file cluster_tree.h.
get_max_level()
template<int spacedim, typename Number > unsigned int ClusterTree< spacedim, Number >::get_max_level
Get the maximum tree level.
Definition at line 1546 of file cluster_tree.h.
get_n_min()
template<int spacedim, typename Number > unsigned int ClusterTree< spacedim, Number >::get_n_min
Get the minimum cluster size.
Definition at line 1532 of file cluster_tree.h.
Referenced by BlockClusterTree< spacedim, Number >::BlockClusterTree().
get_node_num()
template<int spacedim, typename Number > unsigned int ClusterTree< spacedim, Number >::get_node_num
Get the total number of clusters in the tree.
Definition at line 1554 of file cluster_tree.h.
get_root()
template<int spacedim, typename Number > ClusterTree< spacedim, Number >::node_pointer_type ClusterTree< spacedim, Number >::get_root
Get the pointer to the root node of the cluster tree.
Definition at line 1453 of file cluster_tree.h.
Referenced by BlockClusterTree< spacedim, Number >::BlockClusterTree(), ClusterTree< spacedim, Number >::ClusterTree(), and ClusterTree< spacedim, Number >::operator=().
is_index_sets_cleared()
template<int spacedim, typename Number = double> bool ClusterTree< spacedim, Number >::is_index_sets_cleared () const inline
Return the flag indicating whether the index sets have been cleared.
Returns
Definition at line 356 of file cluster_tree.h.
References ClusterTree< spacedim, Number >::index_sets_cleared.
memory_consumption()
template<int spacedim, typename Number > std::size_t ClusterTree< spacedim, Number >::memory_consumption
Estimate the memory consumption of the cluster tree, including all its nodes and contained data.
Definition at line 1593 of file cluster_tree.h.
memory_consumption_of_all_clusters()
template<int spacedim, typename Number > std::size_t ClusterTree< spacedim, Number >::memory_consumption_of_all_clusters
Estimate the memory consumption of all clusters in the tree.
Definition at line 1610 of file cluster_tree.h.
References Preorder_for_memory_consumption().
operator=() [1/2]
template<int spacedim, typename Number > ClusterTree< spacedim, Number > & ClusterTree< spacedim, Number >::operator= (ClusterTree< spacedim, Number > && cluster_tree)
Shallow assignment operator.
Parameters
cluster_tree
Returns
Definition at line 764 of file cluster_tree.h.
operator=() [2/2]
template<int spacedim, typename Number > ClusterTree< spacedim, Number > & ClusterTree< spacedim, Number >::operator= (const ClusterTree< spacedim, Number > & cluster_tree)
Deep assignment operator.
Parameters
cluster_tree
Returns
Definition at line 740 of file cluster_tree.h.
References CopyTree(), ClusterTree< spacedim, Number >::depth, ClusterTree< spacedim, Number >::external_to_internal_dof_numbering, ClusterTree< spacedim, Number >::get_root(), ClusterTree< spacedim, Number >::index_sets_cleared, ClusterTree< spacedim, Number >::internal_to_external_dof_numbering, ClusterTree< spacedim, Number >::max_level, ClusterTree< spacedim, Number >::n_min, and ClusterTree< spacedim, Number >::node_num.
partition() [1/3]
template<int spacedim, typename Number > void ClusterTree< spacedim, Number >::partition
Perform a pure cardinality based recursive partition, which will ultimately be used in constructing an \(\mathcal{H}^p\) matrix for example.
Note
If the initial complete cluster index set \(I\) is sorted, which is usually \([0, 1, \cdots, N]\), the cardinality based cluster partition produces cluster index sets following the same order, i.e. the cardinality based partition is order preserving.
If the initial complete cluster index set \(I\) is also continuous, i.e. it is a continuous integer array, the cardinality based cluster partition also produces continuous cluster index sets. Hence, the cardinality based partition is continuity preserving.
Definition at line 1410 of file cluster_tree.h.
References calc_depth().
Referenced by DDMEfield< dim, spacedim, RangeNumberType, KernelNumberType >::initialize_subdomain_hmatrices().
partition() [2/3]
template<int spacedim, typename Number > void ClusterTree< spacedim, Number >::partition (const std::vector< Point< spacedim, Number > > & all_support_points)
Perform a recursive partition dependent on the coordinates of DoF support points by starting from the root node.
In this version, there is no mesh cell size correction to the cluster diameter and cluster pair distance.
Note
If the initial complete cluster index set \(I\) is sorted, which is usually \([0, 1, \cdots, N]\), the support point coordinates based partition is also order preserving. This is because the two child clusters of the current cluster are built by scanning the index set of the current cluster from beginning to end.
The support point coordinates based partition is not continuity preserving.
Definition at line 1423 of file cluster_tree.h.
References calc_depth().
partition() [3/3]
template<int spacedim, typename Number > void ClusterTree< spacedim, Number >::partition (const std::vector< Point< spacedim, Number > > & all_support_points, const std::vector< Number > & cell_size_at_dofs)
Perform a recursive partition dependent on the coordinates of DoF support points by starting from the root node.
In this version, there is mesh cell size correction to the cluster diameter and cluster pair distance.
Note
If the initial complete cluster index set \(I\) is sorted, which is usually \([0, 1, \cdots, N]\), the support point coordinates based partition is also order preserving. This is because the two child clusters of the current cluster are built by scanning the index set of the current cluster from beginning to end.
The support point coordinates based partition is not continuity preserving.
Definition at line 1436 of file cluster_tree.h.
References calc_depth().
partition_from_cluster_node() [1/3]
template<int spacedim, typename Number > void ClusterTree< spacedim, Number >::partition_from_cluster_node (node_pointer_type current_cluster_node, const std::vector< Point< spacedim, Number > > & all_support_points, const std::vector< Number > & cell_size_at_dofs, std::vector< node_pointer_type > & leaf_set_wrt_current_node) private
Perform a recursive partition dependent on the coordinates of DoF support points by starting from a cluster node.
In this version, there is mesh cell size correction to the cluster diameter and cluster pair distance.
Note
If the initial complete cluster index set \(I\) is sorted, which is usually \([0, 1, \cdots, N]\), the support point coordinates based partition is also order preserving. This is because the two child clusters of the current cluster are built by scanning the index set of the current cluster from beginning to end.
The support point coordinates based partition is not continuity preserving.
Parameters
all_support_points All the support points.
When the size/cardinality of the current cluster is large enough, continue the partition.
If the bounding box of the current cluster has zero volume, we use the cardinality based partition instead. The reason why such case appears is because when the finite element is of a discontinuous type, such as that used for the Neumann space, there will be multiple support points having the same coordinates, for example, all the support points associated with a common vertex which is shared by several cells. The number of such support points may be larger than \(n_{\min}\).
Declare the two child index sets.
Split the index set of the current node into halves.
Calculate the splitting index in the middle of the index set, which is to be used for constructing half-closed and half-open subintervals.
Construct the left child index set.
Construct the right child index set.
Divide the bounding box of the current cluster into halves.
Determine to which child index set each support point in the original bounding box belongs to.
If the support point associated with the current DoF index belongs to the left child box, add this DoF index to the left child index set.
Otherwise, add this DoF index to the right child index set.
N.B. During the creation of the new child cluster, its bounding box will be recalculated, which may be smaller than the child bounding box obtained from the previous bounding box geometric bisection.
Append this new node as the left child of the current cluster node.
Continue the recursive partition by starting from this child node.
Merge the leaf set wrt. the child cluster node into the leaf set of the current cluster node.
N.B. During the creation of the new child cluster, its bounding box will be recalculated, which may be smaller than the child bounding box obtained from the previous bounding box geometric bisection.
Append this new node as the right child of the current cluster node.
Continue the recursive partition by starting from this child node.
Merge the leaf set wrt. the child cluster node into the leaf set of the current cluster node.
Definition at line 1129 of file cluster_tree.h.
References BinaryTreeNode< T >::get_data_pointer(), BinaryTreeNode< T >::get_level(), BinaryTreeNode< T >::Left(), and BinaryTreeNode< T >::Right().
partition_from_cluster_node() [2/3]
template<int spacedim, typename Number > void ClusterTree< spacedim, Number >::partition_from_cluster_node (node_pointer_type current_cluster_node, const std::vector< Point< spacedim, Number > > & all_support_points, std::vector< node_pointer_type > & leaf_set_wrt_current_node) private
Perform a recursive partition dependent on the coordinates of DoF support points by starting from a cluster node.
In this version, there is no mesh cell size correction to the cluster diameter and cluster pair distance.
Note
If the initial complete cluster index set \(I\) is sorted, which is usually \([0, 1, \cdots, N]\), the support point coordinates based partition is also order preserving. This is because the two child clusters of the current cluster are built by scanning the index set of the current cluster from beginning to end.
The support point coordinates based partition is not continuity preserving.
Parameters
all_support_points All the support points.
When the size/cardinality of the current cluster is large enough, continue the partition.
If the bounding box of the current cluster has zero volume, we use the cardinality based partition instead. The reason why such case appears is because when the finite element is of a discontinuous type, such as that used for the Neumann space, there will be multiple support points having the same coordinates, for example, all the support points associated with a common vertex which is shared by several cells. The number of such support points may be larger than \(n_{\min}\).
Declare the two child index sets.
Split the index set of the current node into halves.
Calculate the splitting index in the middle of the index set, which is to be used for constructing half-closed and half-open subintervals.
Construct the left child index set.
Construct the right child index set.
Divide the bounding box of the current cluster into halves.
Determine to which child index set each support point in the original bounding box belongs to.
If the support point associated with the current DoF index belongs to the left child box, add this DoF index to the left child index set.
Otherwise, add this DoF index to the right child index set.
N.B. During the creation of the new child cluster, its bounding box will be recalculated, which may be smaller than the child bounding box obtained from the previous bounding box geometric bisection.
Append this new node as the left child of the current cluster node.
Continue the recursive partition by starting from this child node.
Merge the leaf set wrt. the child cluster node into the leaf set of the current cluster node.
N.B. During the creation of the new child cluster, its bounding box will be recalculated, which may be smaller than the child bounding box obtained from the previous bounding box geometric bisection.
Append this new node as the right child of the current cluster node.
Continue the recursive partition by starting from this child node.
Merge the leaf set wrt. the child cluster node into the leaf set of the current cluster node.
Definition at line 927 of file cluster_tree.h.
References BinaryTreeNode< T >::get_data_pointer(), BinaryTreeNode< T >::get_level(), BinaryTreeNode< T >::Left(), and BinaryTreeNode< T >::Right().
partition_from_cluster_node() [3/3]
template<int spacedim, typename Number > void ClusterTree< spacedim, Number >::partition_from_cluster_node (node_pointer_type current_cluster_node, std::vector< node_pointer_type > & leaf_set_wrt_current_node) private
Perform a pure cardinality based recursive partition by starting from a cluster node.
Note
If the initial complete cluster index set \(I\) is sorted, which is usually \([0, 1, \cdots, N]\), the cardinality based cluster partition produces cluster index sets following the same order, i.e. the cardinality based partition is order preserving.
If the initial complete cluster index set \(I\) is also continuous, i.e. it is a continuous integer array, the cardinality based cluster partition also produces continuous cluster index sets. Hence, the cardinality based partition is continuity preserving.
Parameters
current_cluster_node
leaf_set_wrt_current_node
When the size/cardinality of the current cluster is large enough, continue the partition.
Declare the two child index sets.
Split the index set of the current node into halves.
Calculate the splitting index in the middle of the index set, which is to be used for constructing half-closed and half-open subintervals.
Construct the left child index set.
Construct the right child index set.
Append this new node as the left child of the current cluster node.
Continue the recursive partition by starting from this child node.
Merge the leaf set wrt. the child cluster node into the leaf set of the current cluster node.
Append this new node as the right child of the current cluster node.
Continue the recursive partition by starting from this child node.
Merge the leaf set wrt. the child cluster node into the leaf set of the current cluster node.
Definition at line 799 of file cluster_tree.h.
References BinaryTreeNode< T >::get_data_pointer(), BinaryTreeNode< T >::get_level(), BinaryTreeNode< T >::Left(), and BinaryTreeNode< T >::Right().
print_tree_info_as_dot()
template<int spacedim, typename Number > void ClusterTree< spacedim, Number >::print_tree_info_as_dot (std::ostream & out) const
Print the block cluster tree hierarchy information in the directional graph in GraphViz dot format.
Parameters
out
Write the header of the Graphviz dot file.
Define the node style.
Add comment nodes.
Finalize the Graphviz dot file.
Definition at line 1562 of file cluster_tree.h.
release()
template<int spacedim, typename Number > void ClusterTree< spacedim, Number >::release
Release the memory and status of the cluster tree hierarchy.
Definition at line 721 of file cluster_tree.h.
References DeleteTree().
set_index_ranges_and_clear_index_sets()
template<int spacedim, typename Number > void ClusterTree< spacedim, Number >::set_index_ranges_and_clear_index_sets private
Set the index range (in internal DoF numbering) of each cluster node in the cluster tree from its associated index set based on the mapping from the external numbering to internal numbering. Then, clear the index set (in external DoF numbering) for saving memory.
Definition at line 1357 of file cluster_tree.h.
set_index_ranges_and_clear_index_sets_from_cluster_node()
template<int spacedim, typename Number > void ClusterTree< spacedim, Number >::set_index_ranges_and_clear_index_sets_from_cluster_node (node_pointer_type current_cluster_node) private
Set index ranges and clear index sets recursively by starting from a cluster node in the cluster tree.
Parameters
current_cluster_node
Definition at line 1369 of file cluster_tree.h.
References BinaryTreeNode< T >::get_child_num(), BinaryTreeNode< T >::get_child_pointer(), and BinaryTreeNode< T >::get_data_reference().
Friends And Related Function Documentation
operator<<
template<int spacedim, typename Number = double> template<int spacedim1, typename Number1 > std::ostream & operator<< (std::ostream & out, const ClusterTree< spacedim1, Number1 > & cluster_tree) friend
Print a whole cluster tree using recursion.
Parameters
out
cluster_tree
Returns
Member Data Documentation
child_num
template<int spacedim, typename Number = double> const unsigned int ClusterTree< spacedim, Number >::child_num = 2 inline static
Number of children in a cluster tree.
At present, only binary tree is allowed.
Definition at line 93 of file cluster_tree.h.
depth
template<int spacedim, typename Number = double> unsigned int ClusterTree< spacedim, Number >::depth private
Depth of the tree, which is the maximum level plus one.
Note
The level number starts from 0, which is assigned to the root node. This definition of the cluster tree depth is one more than the definition in
Definition at line 518 of file cluster_tree.h.
Referenced by ClusterTree< spacedim, Number >::ClusterTree(), and ClusterTree< spacedim, Number >::operator=().
external_to_internal_dof_numbering
template<int spacedim, typename Number = double> std::vector<types::global_dof_index> ClusterTree< spacedim, Number >::external_to_internal_dof_numbering private
The numbering mapping from external DoF indices to internal DoF indices.
Definition at line 509 of file cluster_tree.h.
Referenced by ClusterTree< spacedim, Number >::ClusterTree(), and ClusterTree< spacedim, Number >::operator=().
index_sets_cleared
template<int spacedim, typename Number = double> bool ClusterTree< spacedim, Number >::index_sets_cleared private
Whether the index sets for all cluster nodes are cleared.
Definition at line 542 of file cluster_tree.h.
Referenced by ClusterTree< spacedim, Number >::is_index_sets_cleared(), and ClusterTree< spacedim, Number >::operator=().
internal_to_external_dof_numbering
template<int spacedim, typename Number = double> std::vector<types::global_dof_index> ClusterTree< spacedim, Number >::internal_to_external_dof_numbering private
The numbering mapping from internal DoF indices to external DoF indices.
Definition at line 505 of file cluster_tree.h.
Referenced by ClusterTree< spacedim, Number >::ClusterTree(), and ClusterTree< spacedim, Number >::operator=().
leaf_set
template<int spacedim, typename Number = double> std::vector<node_pointer_type> ClusterTree< spacedim, Number >::leaf_set private
Definition at line 500 of file cluster_tree.h.
max_level
template<int spacedim, typename Number = double> int ClusterTree< spacedim, Number >::max_level private
Maximum level of the cluster tree, which is depth - 1.
Note
The level number starts from 0, which is assigned to the root node.
Definition at line 526 of file cluster_tree.h.
Referenced by ClusterTree< spacedim, Number >::ClusterTree(), and ClusterTree< spacedim, Number >::operator=().
n_min
template<int spacedim, typename Number = double> unsigned int ClusterTree< spacedim, Number >::n_min private
Minimum cluster size, which is used as the condition for stopping box division.
Definition at line 532 of file cluster_tree.h.
Referenced by ClusterTree< spacedim, Number >::operator=().
node_num
template<int spacedim, typename Number = double> unsigned int ClusterTree< spacedim, Number >::node_num private
Total number of clusters in the tree.
Definition at line 537 of file cluster_tree.h.
Referenced by ClusterTree< spacedim, Number >::ClusterTree(), and ClusterTree< spacedim, Number >::operator=().
root_node
template<int spacedim, typename Number = double> node_pointer_type ClusterTree< spacedim, Number >::root_node private
Definition at line 499 of file cluster_tree.h.
The documentation for this class was generated from the following file:
include/cluster_tree/cluster_tree.h