HierBEM: TreeNode< T, N > Class Template Reference
TreeNode< T, N > Class Template Reference
Class for general tree node.
#include <tree.h>
Public Member Functions
TreeNode ()
TreeNode (const T &data)
TreeNode (const T &data, unsigned int level, const std::array< TreeNode *, N > &children, TreeNode *parent=nullptr, TreeNodeSplitMode split_mode=UnsplitMode)
TreeNode (const TreeNode &node)
TreeNode * get_child_pointer (std::size_t index) const
void set_child_pointer (std::size_t index, const TreeNode *pointer)
unsigned int get_child_num () const
void set_child_num (const unsigned int child_num)
void increase_child_num (const unsigned int incr_num=1)
void decrease_child_num (const unsigned int decr_num=1)
TreeNode * Parent (void) const
void Parent (const TreeNode *node_pointer)
T * get_data_pointer ()
const T * get_data_pointer () const
T & get_data_reference ()
const T & get_data_reference () const
unsigned int get_level () const
void set_level (const unsigned int level)
bool is_leaf () const
bool is_root () const
TreeNodeSplitMode get_split_mode () const
void set_split_mode (TreeNodeSplitMode split_mode)
bool operator== (const TreeNode< T, N > &node) const
std::size_t memory_consumption () const
Private Attributes
T data
unsigned int level
std::array< TreeNode *, N > children
TreeNode * parent
unsigned int child_num
TreeNodeSplitMode split_mode
Detailed Description
template<typename T, std::size_t N>
class TreeNode< T, N >
Class for general tree node.
This general tree node can contains any but fixed number of children. T is the type of the data held by the node. N is the number of children belong to the node.
Definition at line 548 of file tree.h.
Constructor & Destructor Documentation
TreeNode() [1/4]
template<typename T , std::size_t N> TreeNode< T, N >::TreeNode
Default constructor
Definition at line 735 of file tree.h.
TreeNode() [2/4]
template<typename T , std::size_t N> TreeNode< T, N >::TreeNode (const T & data)
Constructor from the given data without children.
Definition at line 746 of file tree.h.
TreeNode() [3/4]
template<typename T , std::size_t N> TreeNode< T, N >::TreeNode (const T & data, unsigned int level, const std::array< TreeNode< T, N > *, N > & children, TreeNode< T, N > * parent = nullptr, TreeNodeSplitMode split_mode = UnsplitMode)
Constructor from the given data.
N.B. The number of children of the parent node will automatically be incremented, because the current node is associated with this parent.
Count the total number of nonempty children.
When the tree node is split into four children, this is a cross splitting mode. Otherwise, split_mode is temporarily kept at UnsplitMode, which will further be set from outside.
Increment the child_num of the parent node.
Definition at line 757 of file tree.h.
References TreeNode< T, N >::child_num.
TreeNode() [4/4]
template<typename T , std::size_t N> TreeNode< T, N >::TreeNode (const TreeNode< T, N > & node)
Copy constructor.
Definition at line 800 of file tree.h.
Member Function Documentation
decrease_child_num()
template<typename T , std::size_t N> void TreeNode< T, N >::decrease_child_num (const unsigned int decr_num = 1) inline
Decrease the total number of children.
Returns
Definition at line 855 of file tree.h.
get_child_num()
template<typename T , std::size_t N> unsigned int TreeNode< T, N >::get_child_num inline
Get the total number of nonempty children.
Definition at line 831 of file tree.h.
Referenced by CopyTree(), GetTreeLeaves(), PrintTreeNode(), and BlockClusterTree< spacedim, Number >::prune_descendants_from_node().
get_child_pointer()
template<typename T , std::size_t N> TreeNode< T, N > * TreeNode< T, N >::get_child_pointer (std::size_t index) const
Get the pointer to the index'th child.
Parameters
index Index of the child
Returns
Definition at line 811 of file tree.h.
Referenced by calc_depth(), CopyTree(), CountTreeNodes(), GetTreeLeaves(), GetTreeNodesAtLevel(), Postorder(), Preorder(), Preorder_for_memory_consumption(), and BlockClusterTree< spacedim, Number >::prune_descendants_from_node().
get_data_pointer() [1/2]
template<typename T , std::size_t N> T * TreeNode< T, N >::get_data_pointer inline
Get the pointer to the node data.
Definition at line 884 of file tree.h.
Referenced by BlockClusterTree< spacedim, Number >::partition_coarse_non_tensor_product_from_block_cluster_node(), BlockClusterTree< spacedim, Number >::partition_fine_non_tensor_product_from_block_cluster_node(), BlockClusterTree< spacedim, Number >::partition_fine_non_tensor_product_from_block_cluster_node_N(), BlockClusterTree< spacedim, Number >::partition_fine_non_tensor_product_from_block_cluster_node_Nstar(), BlockClusterTree< spacedim, Number >::partition_from_block_cluster_node(), and BlockClusterTree< spacedim, Number >::partition_tensor_product_from_block_cluster_node().
get_data_pointer() [2/2]
template<typename T , std::size_t N> const T * TreeNode< T, N >::get_data_pointer inline
Get the pointer to the node data (const version).
Definition at line 891 of file tree.h.
get_data_reference() [1/2]
template<typename T , std::size_t N> T & TreeNode< T, N >::get_data_reference inline
Get the reference to the node data.
Definition at line 899 of file tree.h.
Referenced by CopyTree(), BlockClusterTree< spacedim, Number >::extend_finer_than_partition(), BlockClusterTree< spacedim, Number >::find_leaf_bc_node_not_in_partition(), BlockClusterTree< spacedim, Number >::find_leaf_bc_node_not_subset_of_bc_nodes_in_partition(), HMatrix< spacedim, Number >::mmult(), and PrintTreeNode().
get_data_reference() [2/2]
template<typename T , std::size_t N> const T & TreeNode< T, N >::get_data_reference inline
Get the reference to the node data (const version).
Definition at line 907 of file tree.h.
get_level()
template<typename T , std::size_t N> unsigned int TreeNode< T, N >::get_level inline
Get the level of the node in the tree.
Definition at line 915 of file tree.h.
Referenced by CopyTree(), GetTreeNodesAtLevel(), and PrintTreeNode().
get_split_mode()
template<typename T , std::size_t N> TreeNodeSplitMode TreeNode< T, N >::get_split_mode inline
Return the split mode of the tree node.
Returns
Definition at line 947 of file tree.h.
Referenced by CopyTree(), and PrintTreeNode().
increase_child_num()
template<typename T , std::size_t N> void TreeNode< T, N >::increase_child_num (const unsigned int incr_num = 1) inline
Increase the total number of children.
Definition at line 847 of file tree.h.
Referenced by CopyTree().
is_leaf()
template<typename T , std::size_t N> bool TreeNode< T, N >::is_leaf inline
Return whether the current tree node is a leaf.
Returns
Definition at line 931 of file tree.h.
is_root()
template<typename T , std::size_t N> bool TreeNode< T, N >::is_root inline
Return whether the current tree node is the root.
Returns
Definition at line 939 of file tree.h.
memory_consumption()
template<typename T , std::size_t N> std::size_t TreeNode< T, N >::memory_consumption
Estimate the memory consumption of the node itself and its contained data.
Definition at line 971 of file tree.h.
Referenced by Preorder_for_memory_consumption().
operator==()
template<typename T , std::size_t N> bool TreeNode< T, N >::operator== (const TreeNode< T, N > & node) const inline
Check the equality of two tree nodes by comparing the contained data.
Parameters
node
Returns
Definition at line 963 of file tree.h.
Parent() [1/2]
template<typename T , std::size_t N> void TreeNode< T, N >::Parent (const TreeNode< T, N > * node_pointer) inline
Set the pointer to the parent tree node.
Parameters
node_pointer
Definition at line 877 of file tree.h.
Parent() [2/2]
template<typename T , std::size_t N> TreeNode< T, N > * TreeNode< T, N >::Parent (void) const inline
Get the pointer to the parent tree node.
Returns
Definition at line 870 of file tree.h.
Referenced by CopyTree(), and PrintTreeNode().
set_child_num()
template<typename T , std::size_t N> void TreeNode< T, N >::set_child_num (const unsigned int child_num) inline
Set the total number of nonempty children.
Parameters
child_num
Definition at line 839 of file tree.h.
Referenced by BlockClusterTree< spacedim, Number >::prune_descendants_from_node().
set_child_pointer()
template<typename T , std::size_t N> void TreeNode< T, N >::set_child_pointer (std::size_t index, const TreeNode< T, N > * pointer)
Set the pointer to the index'th child.
N.B. The const pointer type in the argument will be converted to non-const pointer type. In this way, even a const node can be added to the tree.
Parameters
index Index of the child
pointer New pointer value
Definition at line 820 of file tree.h.
Referenced by CopyTree(), and BlockClusterTree< spacedim, Number >::prune_descendants_from_node().
set_level()
template<typename T , std::size_t N> void TreeNode< T, N >::set_level (const unsigned int level) inline
Set the level of the node.
Parameters
level
Definition at line 923 of file tree.h.
set_split_mode()
template<typename T , std::size_t N> void TreeNode< T, N >::set_split_mode (TreeNodeSplitMode split_mode) inline
Set the split mode of the tree node.
Parameters
split_mode
Definition at line 955 of file tree.h.
Referenced by BlockClusterTree< spacedim, Number >::partition_coarse_non_tensor_product_from_block_cluster_node(), BlockClusterTree< spacedim, Number >::partition_fine_non_tensor_product_from_block_cluster_node(), BlockClusterTree< spacedim, Number >::partition_fine_non_tensor_product_from_block_cluster_node_N(), BlockClusterTree< spacedim, Number >::partition_fine_non_tensor_product_from_block_cluster_node_Nstar(), BlockClusterTree< spacedim, Number >::partition_from_block_cluster_node(), BlockClusterTree< spacedim, Number >::partition_tensor_product_from_block_cluster_node(), and BlockClusterTree< spacedim, Number >::prune_descendants_from_node().
Member Data Documentation
child_num
template<typename T , std::size_t N> unsigned int TreeNode< T, N >::child_num private
Total number of nonempty children.
Definition at line 729 of file tree.h.
Referenced by TreeNode< T, N >::TreeNode().
children
template<typename T , std::size_t N> std::array<TreeNode *, N> TreeNode< T, N >::children private
Definition at line 723 of file tree.h.
data
template<typename T , std::size_t N> T TreeNode< T, N >::data private
Definition at line 720 of file tree.h.
level
template<typename T , std::size_t N> unsigned int TreeNode< T, N >::level private
Definition at line 721 of file tree.h.
parent
template<typename T , std::size_t N> TreeNode* TreeNode< T, N >::parent private
Definition at line 724 of file tree.h.
split_mode
template<typename T , std::size_t N> TreeNodeSplitMode TreeNode< T, N >::split_mode private
Definition at line 731 of file tree.h.
The documentation for this class was generated from the following file:
include/cluster_tree/tree.h