HierBEM: MappingInfo< dim, spacedim > Class Template Reference
MappingInfo< dim, spacedim > Class Template Reference
#include <mapping_info.h>
Public Member Functions
MappingInfo ()
MappingInfo (const unsigned int order)
MappingInfo (const MappingInfo< dim, spacedim > &)=delete
MappingInfo< dim, spacedim > & operator= (const MappingInfo< dim, spacedim > &)=delete
void resize_internal_data (const unsigned int n_points_in_unit_cell) const
std::unique_ptr< typename MappingQ< dim, spacedim >::InternalData > & get_data ()
MappingQExt< dim, spacedim > & get_mapping ()
const std::unique_ptr< typename MappingQ< dim, spacedim >::InternalData > & get_data () const
const MappingQExt< dim, spacedim > & get_mapping () const
const std::array< std::vector< unsigned int >, GeometryInfo< dim >::vertices_per_cell > & get_lexicographic_numberings () const
const std::array< std::vector< unsigned int >, GeometryInfo< dim >::vertices_per_cell > & get_reversed_lexicographic_numberings () const
Private Member Functions
void init_mapping_data ()
void init_lexicographic_numberings_and_reverse ()
Private Attributes
MappingQExt< dim, spacedim > mapping
std::unique_ptr< typename MappingQ< dim, spacedim >::InternalData > data
std::array< std::vector< unsigned int >, GeometryInfo< dim >::vertices_per_cell > lexicographic_numberings
std::array< std::vector< unsigned int >, GeometryInfo< dim >::vertices_per_cell > reversed_lexicographic_numberings
Detailed Description
template<int dim, int spacedim>
class MappingInfo< dim, spacedim >
Class holding both the mapping object and its internal data.
Template Parameters
dim
spacedim
Definition at line 42 of file mapping_info.h.
Constructor & Destructor Documentation
MappingInfo() [1/3]
template<int dim, int spacedim> MappingInfo< dim, spacedim >::MappingInfo
Default constructor.
Precondition
Postcondition
Definition at line 199 of file mapping_info.h.
MappingInfo() [2/3]
template<int dim, int spacedim> MappingInfo< dim, spacedim >::MappingInfo (const unsigned int order)
Constructor.
Precondition
Postcondition
Parameters
order
Definition at line 206 of file mapping_info.h.
References MappingInfo< dim, spacedim >::init_lexicographic_numberings_and_reverse(), and MappingInfo< dim, spacedim >::init_mapping_data().
MappingInfo() [3/3]
template<int dim, int spacedim> MappingInfo< dim, spacedim >::MappingInfo (const MappingInfo< dim, spacedim > &) delete
Disable the copy constructor, because this class contains a unique_ptr member.
Precondition
Postcondition
Parameters
Member Function Documentation
get_data() [1/2]
template<int dim, int spacedim> std::unique_ptr< typename MappingQ< dim, spacedim >::InternalData > & MappingInfo< dim, spacedim >::get_data () inline
Definition at line 104 of file mapping_info.h.
get_data() [2/2]
template<int dim, int spacedim> const std::unique_ptr< typename MappingQ< dim, spacedim >::InternalData > & MappingInfo< dim, spacedim >::get_data () const inline
Definition at line 116 of file mapping_info.h.
get_lexicographic_numberings()
template<int dim, int spacedim> const std::array< std::vector< unsigned int >, GeometryInfo< dim >::vertices_per_cell > & MappingInfo< dim, spacedim >::get_lexicographic_numberings () const inline
Definition at line 129 of file mapping_info.h.
get_mapping() [1/2]
template<int dim, int spacedim> MappingQExt< dim, spacedim > & MappingInfo< dim, spacedim >::get_mapping () inline
Definition at line 110 of file mapping_info.h.
get_mapping() [2/2]
template<int dim, int spacedim> const MappingQExt< dim, spacedim > & MappingInfo< dim, spacedim >::get_mapping () const inline
Definition at line 122 of file mapping_info.h.
get_reversed_lexicographic_numberings()
template<int dim, int spacedim> const std::array< std::vector< unsigned int >, GeometryInfo< dim >::vertices_per_cell > & MappingInfo< dim, spacedim >::get_reversed_lexicographic_numberings () const inline
Definition at line 136 of file mapping_info.h.
init_lexicographic_numberings_and_reverse()
template<int dim, int spacedim> void MappingInfo< dim, spacedim >::init_lexicographic_numberings_and_reverse private
Initialize the lexicographic numberings and their reversed numberings for accessing mapping support points.
Precondition
Postcondition
Definition at line 247 of file mapping_info.h.
Referenced by MappingInfo< dim, spacedim >::MappingInfo().
init_mapping_data()
template<int dim, int spacedim> void MappingInfo< dim, spacedim >::init_mapping_data private
Create the internal data object in the parent Mapping object.
Precondition
Postcondition
Downcast the smart pointer of Mapping<dim, spacedim>::InternalDataBase to MappingQ<dim,spacedim>::InternalData by first unwrapping the original smart pointer via static_cast then wrapping it again.
Definition at line 230 of file mapping_info.h.
Referenced by MappingInfo< dim, spacedim >::MappingInfo().
operator=()
template<int dim, int spacedim> MappingInfo< dim, spacedim > & MappingInfo< dim, spacedim >::operator= (const MappingInfo< dim, spacedim > &) delete
Disable the copy assignment operator, because this class contains a unique_ptr member.
Precondition
Postcondition
Parameters
return
resize_internal_data()
template<int dim, int spacedim> void MappingInfo< dim, spacedim >::resize_internal_data (const unsigned int n_points_in_unit_cell) const
Resize the data tables in the internal data.
This function should be called when the number of points in the unit cell for evaluation are settled or have changed. These points can be quadrature points or support points of a finite element, etc.
The data tables depend on the number of mapping shape functions and the number of quadrature points. After resizing and computing shape function values including their derivatives, the values in the data tables will be copied into BEMValues. Then the internal data can be resized to be used for other cases.
Precondition
Postcondition
Parameters
n_points_in_unit_cell
Definition at line 217 of file mapping_info.h.
Referenced by DoFToolsExt::map_dofs_to_support_points_and_normal_vectors().
Member Data Documentation
data
template<int dim, int spacedim> std::unique_ptr<typename MappingQ<dim, spacedim>::InternalData> MappingInfo< dim, spacedim >::data private
Pointer to the InternalData in the mapping.
Definition at line 169 of file mapping_info.h.
lexicographic_numberings
template<int dim, int spacedim> std::array<std::vector<unsigned int>, GeometryInfo<dim>::vertices_per_cell> MappingInfo< dim, spacedim >::lexicographic_numberings private
The numbering used for accessing the list of support points in the mapping object in the lexicographic order by starting from a specific cell vertex, where the list of support points are stored in the hierarchic order.
The array index is the vertex index.
Definition at line 180 of file mapping_info.h.
mapping
template<int dim, int spacedim> MappingQExt<dim, spacedim> MappingInfo< dim, spacedim >::mapping private
Mapping object.
Definition at line 164 of file mapping_info.h.
reversed_lexicographic_numberings
template<int dim, int spacedim> std::array<std::vector<unsigned int>, GeometryInfo<dim>::vertices_per_cell> MappingInfo< dim, spacedim >::reversed_lexicographic_numberings private
The numbering used for accessing the list of support points in the mapping object in the reversed lexicographic order by starting from a specific cell vertex, where the list of support points are stored in the hierarchical order.
The array index is the vertex index.
Note
This numbering occurs only when \(K_x\) and \(K_y\) share a common edge and it is applied to the mapping for \(K_y\).
Definition at line 194 of file mapping_info.h.
The documentation for this class was generated from the following file:
include/mapping/mapping_info.h