HierBEM: include/cluster_tree/cluster.h File Reference
cluster.h File Reference
Hierarchical matrices
Implementation of the class Cluster.
#include <deal.II/base/memory_consumption.h>
#include <deal.II/base/types.h>
#include <algorithm>
#include <array>
#include <iterator>
#include <vector>
#include "config.h"
#include "simple_bounding_box.h"
#include "utilities/generic_functors.h"
Classes
class Cluster< spacedim, Number >
Class for an index cluster.
Functions
template<int spacedim, typename Number >
std::ostream & operator<< (std::ostream &out, const Cluster< spacedim, Number > &cluster)
template<int spacedim, typename Number = double>
Number calc_cluster_distance (const Cluster< spacedim, Number > &cluster1, const Cluster< spacedim, Number > &cluster2, const std::vector< Point< spacedim, Number > > &all_support_points)
template<int spacedim, typename Number = double>
Number calc_cluster_distance (const Cluster< spacedim, Number > &cluster1, const Cluster< spacedim, Number > &cluster2, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > &all_support_points)
template<int spacedim, typename Number = double>
Number calc_cluster_distance (const Cluster< spacedim, Number > &cluster1, const Cluster< spacedim, Number > &cluster2, const std::vector< Point< spacedim, Number > > &all_support_points1, const std::vector< Point< spacedim, Number > > &all_support_points2)
template<int spacedim, typename Number = double>
Number calc_cluster_distance (const Cluster< spacedim, Number > &cluster1, const Cluster< spacedim, Number > &cluster2, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering1, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering2, const std::vector< Point< spacedim, Number > > &all_support_points1, const std::vector< Point< spacedim, Number > > &all_support_points2)
template<int spacedim, typename Number = double>
Number calc_cluster_distance (const Cluster< spacedim, Number > &cluster1, const Cluster< spacedim, Number > &cluster2, const std::vector< Point< spacedim, Number > > &all_support_points, const std::vector< Number > &cell_size_at_dofs)
template<int spacedim, typename Number = double>
Number calc_cluster_distance (const Cluster< spacedim, Number > &cluster1, const Cluster< spacedim, Number > &cluster2, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > &all_support_points, const std::vector< Number > &cell_size_at_dofs)
template<int spacedim, typename Number = double>
Number calc_cluster_distance (const Cluster< spacedim, Number > &cluster1, const Cluster< spacedim, Number > &cluster2, const std::vector< Point< spacedim, Number > > &all_support_points1, const std::vector< Point< spacedim, Number > > &all_support_points2, const std::vector< Number > &cell_size_at_dofs1, const std::vector< Number > &cell_size_at_dofs2)
template<int spacedim, typename Number = double>
Number calc_cluster_distance (const Cluster< spacedim, Number > &cluster1, const Cluster< spacedim, Number > &cluster2, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering1, const std::vector< types::global_dof_index > &internal_to_external_dof_numbering2, const std::vector< Point< spacedim, Number > > &all_support_points1, const std::vector< Point< spacedim, Number > > &all_support_points2, const std::vector< Number > &cell_size_at_dofs1, const std::vector< Number > &cell_size_at_dofs2)
template<int spacedim, typename Number >
bool operator== (const Cluster< spacedim, Number > &cluster1, const Cluster< spacedim, Number > &cluster2)
Detailed Description
Implementation of the class Cluster.
Date
2021-04-18
Author
Jihuan Tian
Definition in file cluster.h.
Function Documentation
calc_cluster_distance() [1/8]
template<int spacedim, typename Number = double> Number calc_cluster_distance (const Cluster< spacedim, Number > & cluster1, const Cluster< spacedim, Number > & cluster2, const std::vector< Point< spacedim, Number > > & all_support_points)
Calculate the minimum distance between two clusters. This calculation has no mesh size correction.
The calculation is based on measuring the distance between each pair of support points contained in the clusters, which prevents the distance calculation between two support sets.
Note
The index sets held by the two clusters share a same external DoF numbering.
Parameters
cluster1
cluster2
all_support_points A list of support point coordinates which are ordered by external DoF indices.
Returns
Definition at line 695 of file cluster.h.
References Cluster< spacedim, Number >::get_index_set().
Referenced by calc_cluster_distance(), and Cluster< spacedim, Number >::distance_to_cluster().
calc_cluster_distance() [2/8]
template<int spacedim, typename Number = double> Number calc_cluster_distance (const Cluster< spacedim, Number > & cluster1, const Cluster< spacedim, Number > & cluster2, const std::vector< Point< spacedim, Number > > & all_support_points, const std::vector< Number > & cell_size_at_dofs)
Calculate the minimum distance between two clusters. This calculation has the mesh size correction.
The calculation is based on measuring the distance between each pair of support points contained in the clusters, which prevents the distance calculation between two support sets.
Parameters
cluster1
cluster2
all_support_points A list of support point coordinates which are ordered by DoF indices.
cell_size_at_dofs The list of estimated cell size values at DoF support points.
Returns
Calculate the uncorrected cluster distance.
Get the maximum diameter of the support sets for different DoFs, which is 2 times of the cell size associated with the corresponding DoF.
Ensure the positivity of the returned cluster distance.
Definition at line 922 of file cluster.h.
References calc_cluster_distance(), and Cluster< spacedim, Number >::get_index_set().
calc_cluster_distance() [3/8]
template<int spacedim, typename Number = double> Number calc_cluster_distance (const Cluster< spacedim, Number > & cluster1, const Cluster< spacedim, Number > & cluster2, const std::vector< Point< spacedim, Number > > & all_support_points1, const std::vector< Point< spacedim, Number > > & all_support_points2)
Calculate the minimum distance between two clusters. This calculation has no mesh size correction.
The calculation is based on measuring the distance between each pair of support points contained in the clusters, which prevents the distance calculation between two support sets.
Note
The index sets held by the two clusters refer to two different external DoF numberings.
Parameters
cluster1
cluster2
all_support_points1
all_support_points2
Returns
Definition at line 806 of file cluster.h.
References Cluster< spacedim, Number >::get_index_set().
calc_cluster_distance() [4/8]
template<int spacedim, typename Number = double> Number calc_cluster_distance (const Cluster< spacedim, Number > & cluster1, const Cluster< spacedim, Number > & cluster2, const std::vector< Point< spacedim, Number > > & all_support_points1, const std::vector< Point< spacedim, Number > > & all_support_points2, const std::vector< Number > & cell_size_at_dofs1, const std::vector< Number > & cell_size_at_dofs2)
Calculate the minimum distance between two clusters. This calculation has the mesh size correction.
The calculation is based on measuring the distance between each pair of support points contained in the clusters, which prevents the distance calculation between two support sets.
Note
The index sets held by the two clusters refer to two different external DoF numberings.
Parameters
cluster1
cluster2
all_support_points1
all_support_points2
cell_size_at_dofs1
cell_size_at_dofs2
Returns
Calculate the uncorrected cluster distance.
Get the maximum diameter of the support sets for different DoFs, which is 2 times of the cell size associated with the corresponding DoF.
Ensure the positivity of the returned cluster distance.
Definition at line 1079 of file cluster.h.
References calc_cluster_distance(), and Cluster< spacedim, Number >::get_index_set().
calc_cluster_distance() [5/8]
template<int spacedim, typename Number = double> Number calc_cluster_distance (const Cluster< spacedim, Number > & cluster1, const Cluster< spacedim, Number > & cluster2, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > & all_support_points)
Calculate the minimum distance between two clusters. This calculation has no mesh size correction.
The calculation is based on measuring the distance between each pair of support points contained in the clusters, which prevents the distance calculation between two support sets.
Note
The index sets inferred from the index ranges held by the two clusters share a same internal DoF numbering, which need to be mapped to the external numbering for accessing the list of support point coordinates.
Parameters
cluster1
cluster2
internal_to_external_dof_numbering
all_support_points
Returns
Definition at line 744 of file cluster.h.
References Cluster< spacedim, Number >::get_index_range().
calc_cluster_distance() [6/8]
template<int spacedim, typename Number = double> Number calc_cluster_distance (const Cluster< spacedim, Number > & cluster1, const Cluster< spacedim, Number > & cluster2, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering, const std::vector< Point< spacedim, Number > > & all_support_points, const std::vector< Number > & cell_size_at_dofs)
Calculate the minimum distance between two clusters. This calculation has the mesh size correction.
The calculation is based on measuring the distance between each pair of support points contained in the clusters, which prevents the distance calculation between two support sets.
Note
The index sets inferred from the index ranges held by the two clusters share a same internal DoF numbering, which need to be mapped to the external numbering for accessing the list of support point coordinates as well as estimated cell sizes.
Parameters
cluster1
cluster2
internal_to_external_dof_numbering
all_support_points
cell_size_at_dofs
Returns
Calculate the uncorrected cluster distance.
Get the maximum diameter of the support sets for different DoFs, which is 2 times of the cell size associated with the corresponding DoF.
Ensure the positivity of the returned cluster distance.
Definition at line 994 of file cluster.h.
References calc_cluster_distance(), and Cluster< spacedim, Number >::get_index_range().
calc_cluster_distance() [7/8]
template<int spacedim, typename Number = double> Number calc_cluster_distance (const Cluster< spacedim, Number > & cluster1, const Cluster< spacedim, Number > & cluster2, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering1, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering2, const std::vector< Point< spacedim, Number > > & all_support_points1, const std::vector< Point< spacedim, Number > > & all_support_points2)
Calculate the minimum distance between two clusters. This calculation has no mesh size correction.
The calculation is based on measuring the distance between each pair of support points contained in the clusters, which prevents the distance calculation between two support sets.
Note
The index sets inferred from the index ranges held by the two clusters refer to two different internal DoF numberings, which need to be mapped to their corresponding external numberings for accessing the list of support point coordinates.
Parameters
cluster1
cluster2
internal_to_external_dof_numbering1
internal_to_external_dof_numbering2
all_support_points1
all_support_points2
Returns
Definition at line 858 of file cluster.h.
References Cluster< spacedim, Number >::get_index_range().
calc_cluster_distance() [8/8]
template<int spacedim, typename Number = double> Number calc_cluster_distance (const Cluster< spacedim, Number > & cluster1, const Cluster< spacedim, Number > & cluster2, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering1, const std::vector< types::global_dof_index > & internal_to_external_dof_numbering2, const std::vector< Point< spacedim, Number > > & all_support_points1, const std::vector< Point< spacedim, Number > > & all_support_points2, const std::vector< Number > & cell_size_at_dofs1, const std::vector< Number > & cell_size_at_dofs2)
Calculate the minimum distance between two clusters. This calculation has the mesh size correction.
The calculation is based on measuring the distance between each pair of support points contained in the clusters, which prevents the distance calculation between two support sets.
Note
The index sets inferred from the index ranges held by the two clusters refer to two different internal DoF numberings, which need to be mapped to their corresponding external numberings for accessing the list of support point coordinates as well as estimated cell sizes.
Parameters
cluster1
cluster2
internal_to_external_dof_numbering1
internal_to_external_dof_numbering2
all_support_points1
all_support_points2
cell_size_at_dofs1
cell_size_at_dofs2
Returns
Calculate the uncorrected cluster distance.
Get the maximum diameter of the support sets for different DoFs, which is 2 times of the cell size associated with the corresponding DoF.
Ensure the positivity of the returned cluster distance.
Definition at line 1156 of file cluster.h.
References calc_cluster_distance(), and Cluster< spacedim, Number >::get_index_range().
operator<<()
template<int spacedim, typename Number > std::ostream & operator<< (std::ostream & out, const Cluster< spacedim, Number > & cluster)
Print out the cluster data.
Parameters
out
cluster
Returns
Definition at line 657 of file cluster.h.
References Cluster< spacedim, Number >::get_cardinality(), Cluster< spacedim, Number >::index_range, and Cluster< spacedim, Number >::index_set.
operator==()
template<int spacedim, typename Number > bool operator== (const Cluster< spacedim, Number > & cluster1, const Cluster< spacedim, Number > & cluster2)
Definition at line 1875 of file cluster.h.