HierBEM: include/utilities/debug_tools.h File Reference
debug_tools.h File Reference
This file includes a bunch of helper functions for printing out and visualizing information about grid, DoFs, map, etc.
#include <deal.II/base/logstream.h>
#include <deal.II/base/table.h>
#include <deal.II/base/timer.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_tools.h>
#include <deal.II/fe/fe.h>
#include <deal.II/fe/fe_system.h>
#include <deal.II/fe/fe_tools.h>
#include <deal.II/fe/mapping.h>
#include <deal.II/fe/mapping_q.h>
#include <deal.II/grid/tria.h>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <string>
#include <utility>
#include "config.h"
#include "linear_algebra/lapack_full_matrix_ext.h"
#include "quadrature/quadrature.templates.h"
Functions
void print_wall_time (LogStream &log, const Timer &timer, const std::string &activity_name)
void print_wall_time (std::ostream &out, const Timer &timer, const std::string &activity_name)
void print_cpu_time (LogStream &log, const Timer &timer, const std::string &activity_name)
void print_cpu_time (std::ostream &out, const Timer &timer, const std::string &activity_name)
template<int dim, int spacedim>
void print_mesh_info (std::ostream &out, const Triangulation< dim, spacedim > &triangulation)
template<typename VectorType >
void print_vector_values (std::ostream &out, const VectorType &values, const std::string &sep=std::string(","), bool has_newline=true)
template<typename VectorType >
void print_vector_indices (std::ostream &out, const VectorType &values, const std::string &sep, bool index_starting_from_zero, bool has_newline=true)
template<typename Number >
void print_scalar_to_mat (std::ostream &out, const std::string &name, const Number value)
template<typename VectorType >
void print_vector_to_mat (std::ostream &out, const std::string &name, const VectorType &values, bool is_row_vector=false, const unsigned int precision=15, const unsigned int width=25)
template<typename MatrixType >
void print_matrix_to_mat (std::ostream &out, const std::string &name, const MatrixType &values, const unsigned int precision=8, const bool scientific=true, const unsigned int width=0, const char *zero_string="0", const double denominator=1., const double threshold=0.)
template<typename MatrixType >
void print_sparse_matrix_to_mat (std::ostream &out, const std::string &name, const MatrixType &values, const unsigned int precision=8, const bool scientific=true, const unsigned int width=0, const char *zero_string="0", const double denominator=1.)
template<typename T >
void print_2d_table_to_mat (std::ostream &out, const std::string &name, const Table< 2, T > &values, const unsigned int precision=8, const bool scientific=true, const unsigned int width=0)
template<typename node_pointer_type >
void print_vector_of_tree_node_pointer_values (std::ostream &out, const std::vector< node_pointer_type > &tree_node_pointers, const std::string &sep=std::string(","))
template<int dim, int spacedim>
void print_support_point_info (const FiniteElement< dim, spacedim > &fe, const Mapping< dim, spacedim > &mapping, const DoFHandler< dim, spacedim > &dof_handler, const std::string &base_name)
Generate a table of DoF indices associated with each support point.
template<int spacedim>
void print_support_point_info (const std::vector< Point< spacedim > > &support_points, const std::string &base_name)
template<int dim, int spacedim>
void print_support_point_info (const FESystem< dim, spacedim > &fe_system, const Mapping< dim, spacedim > &mapping, const DoFHandler< dim, spacedim > &dof_handler, const std::string &base_name)
Generate a table of DoF indices associated with each support point.
template<int dim, int spacedim>
void print_support_point_info (const MappingQ< dim, spacedim > &mapping, const DoFHandler< dim, spacedim > &dof_handler, const std::string &fe_name)
template<typename FiniteElementType >
void print_polynomial_space_numbering (std::ostream &out, const FiniteElementType &fe, const std::string &fe_name)
template<int dim, int spacedim = dim>
void print_mapping_between_lexicographic_and_hierarchic_numberings (std::ostream &out, const FiniteElement< dim, spacedim > &fe, const std::string &fe_name)
template<int dim, int spacedim = dim>
void print_triangulation_info (std::ostream &out, const Triangulation< dim, spacedim > &triangulation)
template<int dim, int spacedim = dim>
void print_fe_info (std::ostream &out, const FiniteElement< dim, spacedim > &fe)
template<int dim>
void print_qgauss (std::ostream &out, const QGauss< dim > &quad_cpu, const std::string &separator=std::string(","))
template<typename RangeNumberType = double>
void print_qgauss (std::ostream &out, const Table< 2, RangeNumberType > &points, const RangeNumberType *const weights)
template<int dim, typename Number = double>
void print_point_vector_to_mat (std::ostream &out, const std::string &name, const std::vector< Point< dim, Number > > &values, const unsigned int precision=6, const unsigned int width=10)
void read_file_lines (const std::string &file_name, std::vector< std::string > &lines)
Detailed Description
This file includes a bunch of helper functions for printing out and visualizing information about grid, DoFs, map, etc.
Date
2021-04-25
Author
Jihuan Tian
Definition in file debug_tools.h.
Function Documentation
print_2d_table_to_mat()
template<typename T > void print_2d_table_to_mat (std::ostream & out, const std::string & name, const Table< 2, T > & values, const unsigned int precision = 8, const bool scientific = true, const unsigned int width = 0)
Definition at line 356 of file debug_tools.h.
print_cpu_time() [1/2]
void print_cpu_time (LogStream & log, const Timer & timer, const std::string & activity_name)
Print the elapsed CPU time and the total CPU time to log stream.
Parameters
log
timer
activity_name
print_cpu_time() [2/2]
void print_cpu_time (std::ostream & out, const Timer & timer, const std::string & activity_name)
Print the elapsed CPU time and the total CPU time to output stream.
Parameters
out
timer
activity_name
print_fe_info()
template<int dim, int spacedim = dim> void print_fe_info (std::ostream & out, const FiniteElement< dim, spacedim > & fe)
Definition at line 628 of file debug_tools.h.
print_mapping_between_lexicographic_and_hierarchic_numberings()
template<int dim, int spacedim = dim> void print_mapping_between_lexicographic_and_hierarchic_numberings (std::ostream & out, const FiniteElement< dim, spacedim > & fe, const std::string & fe_name)
Print out the mapping between lexicographic numbering and hierarchic numbering of a finite element in Octave format.
Parameters
out
fe
fe_name
Definition at line 596 of file debug_tools.h.
print_matrix_to_mat()
template<typename MatrixType > void print_matrix_to_mat (std::ostream & out, const std::string & name, const MatrixType & values, const unsigned int precision = 8, const bool scientific = true, const unsigned int width = 0, const char * zero_string = "0", const double denominator = 1., const double threshold = 0.)
Print a FullMatrix or a LAPACKFullMatrix into an Octave matrix.
Parameters
out
name
values
precision
scientific
width
zero_string
denominator
threshold
Definition at line 299 of file debug_tools.h.
print_mesh_info()
template<int dim, int spacedim> void print_mesh_info (std::ostream & out, const Triangulation< dim, spacedim > & triangulation)
Print mesh information.
Template Parameters
dim
spacedim
Parameters
triangulation
{ std::map<types::boundary_id, unsigned int> boundary_count;
// Loop over each cell using TriaAccessor. for (auto &cell : triangulation.active_cell_iterators()) { for (unsigned int face = 0; face < GeometryInfo<dim>::faces_per_cell; ++face) { if (cell->face(face)->at_boundary()) boundary_count[cell->face(face)->boundary_id()]++; } }
out << "Boundary indicators: "; for (const std::pair<const types::boundary_id, unsigned int> &pair : boundary_count) { out << pair.first << "(" << pair.second << " cells) "; } out << std::endl; }
Definition at line 113 of file debug_tools.h.
print_point_vector_to_mat()
template<int dim, typename Number = double> void print_point_vector_to_mat (std::ostream & out, const std::string & name, const std::vector< Point< dim, Number > > & values, const unsigned int precision = 6, const unsigned int width = 10)
Print the vector of Point objects as a n*dim matrix in Octave format.
Template Parameters
dim
RangeNumberType
Parameters
out
name
values
precision
width
Definition at line 730 of file debug_tools.h.
print_polynomial_space_numbering()
template<typename FiniteElementType > void print_polynomial_space_numbering (std::ostream & out, const FiniteElementType & fe, const std::string & fe_name)
Print out the polynomial space numbering and inverse numbering of a finite element in Octave format.
Parameters
out
fe
fe_name
Definition at line 571 of file debug_tools.h.
print_qgauss() [1/2]
template<int dim> void print_qgauss (std::ostream & out, const QGauss< dim > & quad_cpu, const std::string & separator = std::string(","))
Print out a QGauss object.
Template Parameters
dim
Parameters
out
quad_cpu
Definition at line 653 of file debug_tools.h.
print_qgauss() [2/2]
template<typename RangeNumberType = double> void print_qgauss (std::ostream & out, const Table< 2, RangeNumberType > & points, const RangeNumberType *const weights)
N.B. The points stored in the table adopt the C style indexing.
Parameters
out
points The first dimension is the quadrature point number. The second dimension is the coordinate component. The index for the second dimension runs faster.
weights
Definition at line 689 of file debug_tools.h.
print_scalar_to_mat()
template<typename Number > void print_scalar_to_mat (std::ostream & out, const std::string & name, const Number value)
Definition at line 234 of file debug_tools.h.
print_sparse_matrix_to_mat()
template<typename MatrixType > void print_sparse_matrix_to_mat (std::ostream & out, const std::string & name, const MatrixType & values, const unsigned int precision = 8, const bool scientific = true, const unsigned int width = 0, const char * zero_string = "0", const double denominator = 1.)
Definition at line 328 of file debug_tools.h.
print_support_point_info() [1/4]
template<int dim, int spacedim> void print_support_point_info (const FESystem< dim, spacedim > & fe_system, const Mapping< dim, spacedim > & mapping, const DoFHandler< dim, spacedim > & dof_handler, const std::string & base_name)
Generate a table of DoF indices associated with each support point.
The information in the table is defined in the given Mapping and DoFHandler objects, which can be then visualized in Gnuplot by executing the following command.
For spacedim=2:
plot "./data_file.gpl" using 1:2:3 with labels offset 1,1 point pt 1 lc rgb
\ "red" notitle
For spacedim=3:
splot "./data_file.gpl" using 1:2:3:4 with labels offset 1,1 point pt 1 lc
\ rgb "red"
Parameters
fe_system The given FESystem object will be checked if it has support points.
mapping
dof_handler
base_name
Allocate memory for the vector storing support points.
Get the list of support point coordinates for all DoFs. The DoFs are in the default numbering starting from 0.
Write the table of DoF indices for each support point into file.
Definition at line 512 of file debug_tools.h.
print_support_point_info() [2/4]
template<int dim, int spacedim> void print_support_point_info (const FiniteElement< dim, spacedim > & fe, const Mapping< dim, spacedim > & mapping, const DoFHandler< dim, spacedim > & dof_handler, const std::string & base_name)
Generate a table of DoF indices associated with each support point.
The information in the table is defined in the given Mapping and DoFHandler objects, which can be then visualized in Gnuplot by executing the following command.
For spacedim=2:
plot "./data_file.gpl" using 1:2:3 with labels offset 1,1 point pt 1 lc rgb
\ "red" notitle
For spacedim=3:
splot "./data_file.gpl" using 1:2:3:4 with labels offset 1,1 point pt 1 lc
\ rgb "red"
Parameters
fe_system The given FiniteElement object will be checked if it has support points.
mapping
dof_handler
base_name
Allocate memory for the vector storing support points.
Get the list of support point coordinates for all DoFs. The DoFs are in the default numbering starting from 0.
Write the table of DoF indices for each support point into file.
Definition at line 430 of file debug_tools.h.
print_support_point_info() [3/4]
template<int dim, int spacedim> void print_support_point_info (const MappingQ< dim, spacedim > & mapping, const DoFHandler< dim, spacedim > & dof_handler, const std::string & fe_name)
Definition at line 543 of file debug_tools.h.
print_support_point_info() [4/4]
template<int spacedim> void print_support_point_info (const std::vector< Point< spacedim > > & support_points, const std::string & base_name)
Generate a table of DoF indices associated with each support point. The DoF indices are automatically assigned by starting from zero.
Parameters
support_points
base_name
Allocate memory for the vector storing support points. The DoF numbering will automatically be given by starting from zero.
Write the table of DoF indices for each support point into file.
Definition at line 468 of file debug_tools.h.
print_triangulation_info()
template<int dim, int spacedim = dim> void print_triangulation_info (std::ostream & out, const Triangulation< dim, spacedim > & triangulation)
Definition at line 616 of file debug_tools.h.
print_vector_indices()
template<typename VectorType > void print_vector_indices (std::ostream & out, const VectorType & values, const std::string & sep, bool index_starting_from_zero, bool has_newline = true)
Definition at line 180 of file debug_tools.h.
print_vector_of_tree_node_pointer_values()
template<typename node_pointer_type > void print_vector_of_tree_node_pointer_values (std::ostream & out, const std::vector< node_pointer_type > & tree_node_pointers, const std::string & sep = std::string(","))
Definition at line 392 of file debug_tools.h.
print_vector_to_mat()
template<typename VectorType > void print_vector_to_mat (std::ostream & out, const std::string & name, const VectorType & values, bool is_row_vector = false, const unsigned int precision = 15, const unsigned int width = 25)
Definition at line 248 of file debug_tools.h.
print_vector_values()
template<typename VectorType > void print_vector_values (std::ostream & out, const VectorType & values, const std::string & sep = std::string(","), bool has_newline = true)
Definition at line 151 of file debug_tools.h.
print_wall_time() [1/2]
void print_wall_time (LogStream & log, const Timer & timer, const std::string & activity_name)
Print the elapsed wall time and the total wall time to log stream.
Parameters
log
timer
activity_name
Referenced by HMatrix< spacedim, Number >::compute_cholesky_factorization_task_parallel(), HMatrix< spacedim, Number >::compute_lu_factorization_task_parallel(), fill_hmatrix_with_aca_plus_smp(), and LaplaceBEM< dim, spacedim, RangeNumberType, KernelNumberType >::Priv::setup_system().
print_wall_time() [2/2]
void print_wall_time (std::ostream & out, const Timer & timer, const std::string & activity_name)
Print the elapsed wall time and the total wall time to output stream.
Parameters
out
timer
activity_name