HierBEM: include/dofs/dof_tools_ext.h File Reference
dof_tools_ext.h File Reference
Introduction of dof_tools_ext.h.
#include <deal.II/base/exceptions.h>
#include <deal.II/base/function.h>
#include <deal.II/base/geometry_info.h>
#include <deal.II/base/point.h>
#include <deal.II/base/tensor.h>
#include <deal.II/base/types.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_tools.h>
#include <deal.II/fe/mapping_q.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/lac/sparsity_pattern.h>
#include <algorithm>
#include <map>
#include <memory>
#include <set>
#include <vector>
#include "bem/bem_tools.h"
#include "cad_mesh/gmsh_manipulation.h"
#include "config.h"
#include "dof_to_cell_topology.h"
#include "linear_algebra/lapack_full_matrix_ext.h"
#include "mapping/mapping_info.h"
Functions
template<int dim, int spacedim>
void DoFToolsExt::extract_subdomain_dofs (const DoFHandler< dim, spacedim > &dof_handler, const std::set< types::subdomain_id > &subdomain_ids, std::vector< bool > &selected_dofs)
template<int dim, int spacedim>
types::global_dof_index DoFToolsExt::extract_material_domain_dofs (const DoFHandler< dim, spacedim > &dof_handler, const std::set< types::material_id > &material_ids, std::vector< bool > &selected_dofs, const bool reset_selectors_to_false=true)
template<int dim, int spacedim>
types::global_dof_index DoFToolsExt::extract_material_domain_dofs_by_excluding_complement_subdomain (const DoFHandler< dim, spacedim > &dof_handler, const std::set< types::material_id > &complement_subdomain_material_ids, std::vector< bool > &selected_dofs, const bool reset_selectors_to_true=true)
template<int dim, int spacedim>
types::global_dof_index DoFToolsExt::extract_material_domain_mg_dofs (const DoFHandler< dim, spacedim > &dof_handler, const unsigned int level, const std::set< types::material_id > &material_ids, std::vector< bool > &selected_dofs, const bool reset_selectors_to_false=true)
template<int dim, int spacedim>
types::global_dof_index DoFToolsExt::extract_material_domain_mg_dofs_by_excluding_complement_subdomain (const DoFHandler< dim, spacedim > &dof_handler, const unsigned int level, const std::set< types::material_id > &complement_subdomain_material_ids, std::vector< bool > &selected_dofs, const bool reset_selectors_to_true=true)
void DoFToolsExt::generate_full_to_local_dof_id_map (const std::vector< bool > &dof_selectors, std::vector< types::global_dof_index > &full_to_local_map)
void DoFToolsExt::generate_local_to_full_dof_id_map (const std::vector< bool > &dof_selectors, std::vector< types::global_dof_index > &local_to_full_map)
void DoFToolsExt::generate_maps_between_full_and_local_dof_ids (const std::vector< bool > &dof_selectors, std::vector< types::global_dof_index > &full_to_local_map, std::vector< types::global_dof_index > &local_to_full_map)
template<int dim, int spacedim, typename RangeNumberType >
void DoFToolsExt::extract_boundary_condition_dofs (const DoFHandler< dim, spacedim > &dof_handler, std::map< EntityTag, Function< spacedim, RangeNumberType > * > &boundary_bc_definition, std::vector< bool > &selected_dofs, const bool reset_selectors_to_false=true)
Generate DoF selectors for those on the boundary condition.
template<int dim, int spacedim>
types::global_dof_index DoFToolsExt::extract_material_domain_dofs_excluding_boundary_dofs (const DoFHandler< dim, spacedim > &dof_handler, const std::set< types::material_id > &boundary_cell_material_ids, std::vector< bool > &selected_dofs)
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_dofs_to_support_points (const Mapping< dim, spacedim > &mapping, const DoFHandler< dim, spacedim > &dof_handler, std::vector< Point< spacedim, Number > > &support_points)
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_dofs_to_support_points (const Mapping< dim, spacedim > &mapping, const DoFHandler< dim, spacedim > &dof_handler, const std::vector< types::global_dof_index > &map_from_local_to_full_dof_indices, std::vector< Point< spacedim, Number > > &support_points)
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_dofs_to_support_points_and_normal_vectors (MappingInfo< dim, spacedim > &mapping_info, const DoFHandler< dim, spacedim > &dof_handler, std::vector< Point< spacedim, Number > > &support_points, std::vector< Tensor< 1, spacedim, Number > > &normal_vectors, const bool is_normal_vector_negated=false)
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_mg_dofs_to_support_points (const Mapping< dim, spacedim > &mapping, const DoFHandler< dim, spacedim > &dof_handler, const unsigned int level, std::map< types::global_dof_index, Point< spacedim, Number > > &support_points)
Return a list of support points for DoFs on the specified level in the DoF handler.
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_mg_dofs_to_support_points (const Mapping< dim, spacedim > &mapping, const DoFHandler< dim, spacedim > &dof_handler, const unsigned int level, std::vector< Point< spacedim, Number > > &support_points)
Return a list of support points for DoFs on the specified level in the DoF handler.
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_mg_dofs_to_support_points (const Mapping< dim, spacedim > &mapping, const DoFHandler< dim, spacedim > &dof_handler, const unsigned int level, const std::set< types::material_id > &subdomain_material_ids, const std::vector< bool > &dof_selectors, const std::vector< types::global_dof_index > &full_to_local_dof_id_map, std::map< types::global_dof_index, Point< spacedim, Number > > &support_points)
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_mg_dofs_to_support_points (const Mapping< dim, spacedim > &mapping, const DoFHandler< dim, spacedim > &dof_handler, const unsigned int level, const std::set< types::material_id > &subdomain_material_ids, const std::vector< bool > &dof_selectors, const std::vector< types::global_dof_index > &full_to_local_dof_id_map, std::vector< Point< spacedim, Number > > &support_points)
Return a list of support points for DoFs in a subdomain on the specified level in the DoF handler.
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_dofs_to_average_cell_size (const DoFHandler< dim, spacedim > &dof_handler, std::vector< Number > &dof_average_cell_size)
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_mg_dofs_to_average_cell_size (const DoFHandler< dim, spacedim > &dof_handler, const unsigned int level, std::vector< Number > &dof_average_cell_size)
Calculate the average cell sizes associated with those DoFs on a specific level in the given DoF handler object.
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_dofs_to_average_cell_size (const DoFHandler< dim, spacedim > &dof_handler, const std::vector< types::global_dof_index > &map_from_local_to_full_dof_indices, std::vector< Number > &dof_average_cell_size)
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_mg_dofs_to_average_cell_size (const DoFHandler< dim, spacedim > &dof_handler, const unsigned int level, const std::vector< types::global_dof_index > &map_from_local_to_full_dof_indices, std::vector< Number > &dof_average_cell_size)
Calculate the average cell sizes associated with a subset of DoFs selected from all those DoFs on a specific level in the DoF handler.
template<typename DoFHandlerType , typename Number = double>
void DoFToolsExt::map_dofs_to_max_cell_size (const DoFHandlerType &dof_handler, std::vector< Number > &dof_max_cell_size)
template<typename DoFHandlerType , typename Number = double>
void DoFToolsExt::map_mg_dofs_to_max_cell_size (const DoFHandlerType &dof_handler, const unsigned int level, std::vector< Number > &dof_max_cell_size)
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_dofs_to_max_cell_size (const DoFHandler< dim, spacedim > &dof_handler, const std::vector< types::global_dof_index > &map_from_local_to_full_dof_indices, std::vector< Number > &dof_max_cell_size)
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_mg_dofs_to_max_cell_size (const DoFHandler< dim, spacedim > &dof_handler, const unsigned int level, const std::vector< types::global_dof_index > &map_from_local_to_full_dof_indices, std::vector< Number > &dof_max_cell_size)
Calculate the maximum cell sizes associated with a subset of DoFs selected from all those DoFs on a specific level in the DoF handler.
template<typename DoFHandlerType , typename Number = double>
void DoFToolsExt::map_dofs_to_min_cell_size (const DoFHandlerType &dof_handler, std::vector< Number > &dof_min_cell_size)
template<typename DoFHandlerType , typename Number = double>
void DoFToolsExt::map_mg_dofs_to_min_cell_size (const DoFHandlerType &dof_handler, const unsigned int level, std::vector< Number > &dof_min_cell_size)
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_dofs_to_min_cell_size (const DoFHandler< dim, spacedim > &dof_handler, const std::vector< types::global_dof_index > &map_from_local_to_full_dof_indices, std::vector< Number > &dof_min_cell_size)
Calculate the minimum cell sizes associated with a subset of DoFs selected from all those DoFs in the DoF handler.
template<int dim, int spacedim, typename Number = double>
void DoFToolsExt::map_mg_dofs_to_min_cell_size (const DoFHandler< dim, spacedim > &dof_handler, const unsigned int level, const std::vector< types::global_dof_index > &map_from_local_to_full_dof_indices, std::vector< Number > &dof_min_cell_size)
Calculate the minimum cell sizes associated with a subset of DoFs selected from all those DoFs on a specific level in the DoF handler.
template<int spacedim, typename Number = double>
void DoFToolsExt::write_gnuplot_dof_support_point_info (std::ostream &out, const std::map< types::global_dof_index, Point< spacedim, Number > > &support_points, const std::vector< bool > &selected_dofs, const bool has_label=true)
Print out support points for the list of selected DoFs, which are used for visualization in Gnuplot.
template<typename Number >
void DoFToolsExt::extend_selected_dof_values_to_full_dofs (Vector< Number > &all_dof_values, const Vector< Number > &selected_dof_values, const std::vector< types::global_dof_index > &map_from_local_to_full_dof_indices)
Copy the list of selected DoF values into the complete DoF value list.
template<int dim, int spacedim>
void DoFToolsExt::build_dof_to_cell_topology (std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &dof_to_cell_topo, const std::vector< typename DoFHandler< dim, spacedim >::cell_iterator > &cell_iterators_in_dof_handler, const DoFHandler< dim, spacedim > &dof_handler, const unsigned int fe_index=0)
template<int dim, int spacedim>
void DoFToolsExt::build_dof_to_cell_topology (DoFToCellTopology< dim, spacedim > &dof_to_cell_topo, const std::vector< typename DoFHandler< dim, spacedim >::cell_iterator > &cell_iterators_in_dof_handler, const DoFHandler< dim, spacedim > &dof_handler, const unsigned int fe_index=0)
Build the topology for "DoF support point-to-cell" relation.
template<int dim, int spacedim>
void DoFToolsExt::build_mg_dof_to_cell_topology (std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > &dof_to_cell_topo, const std::vector< typename DoFHandler< dim, spacedim >::cell_iterator > &mg_cell_iterators_in_dof_handler, const DoFHandler< dim, spacedim > &dof_handler, const unsigned int level=0, const unsigned int fe_index=0)
Build the topology for "DoF support point-to-cell" relation. The DoFs are on a specific level in the multigrid.
template<int dim, int spacedim>
void DoFToolsExt::build_mg_dof_to_cell_topology (DoFToCellTopology< dim, spacedim > &dof_to_cell_topo, const std::vector< typename DoFHandler< dim, spacedim >::cell_iterator > &mg_cell_iterators_in_dof_handler, const DoFHandler< dim, spacedim > &dof_handler, const unsigned int level=0, const unsigned int fe_index=0)
Build the topology for "DoF support point-to-cell" relation. The DoFs are on a specific level in the multigrid.
template<int dim, int spacedim>
void DoFToolsExt::build_mg_dof_to_cell_topology (DoFToCellTopology< dim, spacedim > &dof_to_cell_topo, const std::vector< typename DoFHandler< dim, spacedim >::cell_iterator > &mg_cell_iterators_in_dof_handler, const DoFHandler< dim, spacedim > &dof_handler, const std::vector< bool > &dof_selectors, const unsigned int level=0, const unsigned int fe_index=0)
Build the topology for "DoF support point-to-cell" relation. Only selected DoFs on a specific level in the multigrid are considered.
template<int dim, int spacedim, typename SparsityPatternType >
void DoFToolsExt::make_sparsity_pattern (const DoFHandler< dim, spacedim > &dof_handler_test_space, const DoFHandler< dim, spacedim > &dof_handler_trial_space, const std::vector< bool > &dof_selectors_test_space, const std::vector< types::global_dof_index > &full_to_local_dof_id_map_test_space, const std::vector< bool > &dof_selectors_trial_space, const std::vector< types::global_dof_index > &full_to_local_dof_id_map_trial_space, SparsityPatternType &sparsity)
template<int dim, int spacedim, typename SparsityPatternType >
void DoFToolsExt::make_sparsity_pattern (const DoFHandler< dim, spacedim > &dof_handler_test_space, const DoFHandler< dim, spacedim > &dof_handler_trial_space, const std::set< types::material_id > &subdomain_material_ids, const std::vector< bool > &dof_selectors_test_space, const std::vector< types::global_dof_index > &full_to_local_dof_id_map_test_space, const std::vector< bool > &dof_selectors_trial_space, const std::vector< types::global_dof_index > &full_to_local_dof_id_map_trial_space, SparsityPatternType &sparsity)
Detailed Description
Introduction of dof_tools_ext.h.
Date
2022-11-16
Author
Jihuan Tian
Definition in file dof_tools_ext.h.
Function Documentation
build_dof_to_cell_topology() [1/2]
template<int dim, int spacedim> void DoFToolsExt::build_dof_to_cell_topology (DoFToCellTopology< dim, spacedim > & dof_to_cell_topo, const std::vector< typename DoFHandler< dim, spacedim >::cell_iterator > & cell_iterators_in_dof_handler, const DoFHandler< dim, spacedim > & dof_handler, const unsigned int fe_index = 0)
Build the topology for "DoF support point-to-cell" relation.
Template Parameters
dim
spacedim
Parameters
dof_to_cell_topo The result is returned in this object of type DoFToCellTopology, which also stores the maximum number of cells associated with a DoF.
cell_iterators_in_dof_handler
dof_handler
fe_index
Definition at line 1521 of file dof_tools_ext.h.
References DoFToolsExt::build_dof_to_cell_topology(), DoFToCellTopology< dim, spacedim >::max_cells_per_dof, and DoFToCellTopology< dim, spacedim >::topology.
build_dof_to_cell_topology() [2/2]
template<int dim, int spacedim> void DoFToolsExt::build_dof_to_cell_topology (std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & dof_to_cell_topo, const std::vector< typename DoFHandler< dim, spacedim >::cell_iterator > & cell_iterators_in_dof_handler, const DoFHandler< dim, spacedim > & dof_handler, const unsigned int fe_index = 0)
Build the topology for "DoF support point-to-cell" relation.
Note
2022-06-06 This topology is needed when the continuous finite element such as FE_Q is adopted. For the discontinuous finite element such as FE_DGQ, the DoFs in a cell are separated from those in other cells. Hence, such point-to-cell topology is not necessary.
Parameters
dof_to_cell_topo
dof_handler
fe_index
Definition at line 1480 of file dof_tools_ext.h.
References DoFToolsExt::build_dof_to_cell_topology().
Referenced by DoFToolsExt::build_dof_to_cell_topology().
build_mg_dof_to_cell_topology() [1/3]
template<int dim, int spacedim> void DoFToolsExt::build_mg_dof_to_cell_topology (DoFToCellTopology< dim, spacedim > & dof_to_cell_topo, const std::vector< typename DoFHandler< dim, spacedim >::cell_iterator > & mg_cell_iterators_in_dof_handler, const DoFHandler< dim, spacedim > & dof_handler, const std::vector< bool > & dof_selectors, const unsigned int level = 0, const unsigned int fe_index = 0)
Build the topology for "DoF support point-to-cell" relation. Only selected DoFs on a specific level in the multigrid are considered.
Template Parameters
dim
spacedim
Parameters
dof_to_cell_topo The result is returned in this object of type DoFToCellTopology, which also stores the maximum number of cells associated with a DoF.
mg_cell_iterators_in_dof_handler
dof_handler
level
fe_index
Definition at line 1664 of file dof_tools_ext.h.
References DoFToolsExt::build_mg_dof_to_cell_topology(), DoFToCellTopology< dim, spacedim >::max_cells_per_dof, and DoFToCellTopology< dim, spacedim >::topology.
build_mg_dof_to_cell_topology() [2/3]
template<int dim, int spacedim> void DoFToolsExt::build_mg_dof_to_cell_topology (DoFToCellTopology< dim, spacedim > & dof_to_cell_topo, const std::vector< typename DoFHandler< dim, spacedim >::cell_iterator > & mg_cell_iterators_in_dof_handler, const DoFHandler< dim, spacedim > & dof_handler, const unsigned int level = 0, const unsigned int fe_index = 0)
Build the topology for "DoF support point-to-cell" relation. The DoFs are on a specific level in the multigrid.
Template Parameters
dim
spacedim
Parameters
dof_to_cell_topo The result is returned in this object of type DoFToCellTopology, which also stores the maximum number of cells associated with a DoF.
mg_cell_iterators_in_dof_handler
dof_handler
level
fe_index
Definition at line 1613 of file dof_tools_ext.h.
References DoFToolsExt::build_mg_dof_to_cell_topology(), DoFToCellTopology< dim, spacedim >::max_cells_per_dof, and DoFToCellTopology< dim, spacedim >::topology.
build_mg_dof_to_cell_topology() [3/3]
template<int dim, int spacedim> void DoFToolsExt::build_mg_dof_to_cell_topology (std::vector< std::vector< const typename DoFHandler< dim, spacedim >::cell_iterator * > > & dof_to_cell_topo, const std::vector< typename DoFHandler< dim, spacedim >::cell_iterator > & mg_cell_iterators_in_dof_handler, const DoFHandler< dim, spacedim > & dof_handler, const unsigned int level = 0, const unsigned int fe_index = 0)
Build the topology for "DoF support point-to-cell" relation. The DoFs are on a specific level in the multigrid.
Template Parameters
dim
spacedim
Parameters
dof_to_cell_topo
mg_cell_iterators_in_dof_handler
dof_handler
level
fe_index
Definition at line 1569 of file dof_tools_ext.h.
References DoFToolsExt::build_mg_dof_to_cell_topology().
Referenced by DoFToolsExt::build_mg_dof_to_cell_topology().
extend_selected_dof_values_to_full_dofs()
template<typename Number > void DoFToolsExt::extend_selected_dof_values_to_full_dofs (Vector< Number > & all_dof_values, const Vector< Number > & selected_dof_values, const std::vector< types::global_dof_index > & map_from_local_to_full_dof_indices)
Copy the list of selected DoF values into the complete DoF value list.
Template Parameters
Number
Parameters
all_dof_values
selected_dof_values
map_from_local_to_full_dof_indices
Definition at line 1449 of file dof_tools_ext.h.
References DoFToolsExt::extend_selected_dof_values_to_full_dofs().
Referenced by DoFToolsExt::extend_selected_dof_values_to_full_dofs().
extract_boundary_condition_dofs()
template<int dim, int spacedim, typename RangeNumberType > void DoFToolsExt::extract_boundary_condition_dofs (const DoFHandler< dim, spacedim > & dof_handler, std::map< EntityTag, Function< spacedim, RangeNumberType > * > & boundary_bc_definition, std::vector< bool > & selected_dofs, const bool reset_selectors_to_false = true)
Generate DoF selectors for those on the boundary condition.
Template Parameters
dim
spacedim
Parameters
dof_handler
boundary_bc_definition
selected_dofs
reset_selectors_to_false
Definition at line 388 of file dof_tools_ext.h.
References DoFToolsExt::extract_boundary_condition_dofs().
Referenced by DoFToolsExt::extract_boundary_condition_dofs().
extract_material_domain_dofs()
template<int dim, int spacedim> types::global_dof_index DoFToolsExt::extract_material_domain_dofs (const DoFHandler< dim, spacedim > & dof_handler, const std::set< types::material_id > & material_ids, std::vector< bool > & selected_dofs, const bool reset_selectors_to_false = true)
Mark the DoFs in cells which have a material id belonging to the given collection.
Parameters
dof_handler
material_ids
selected_dofs
reset_selectors_to_false If preset all selectors to false at the beginning of this function.
Returns
Effective number of DoFs.
Definition at line 118 of file dof_tools_ext.h.
References DoFToolsExt::extract_material_domain_dofs().
Referenced by DoFToolsExt::extract_material_domain_dofs().
extract_material_domain_dofs_by_excluding_complement_subdomain()
template<int dim, int spacedim> types::global_dof_index DoFToolsExt::extract_material_domain_dofs_by_excluding_complement_subdomain (const DoFHandler< dim, spacedim > & dof_handler, const std::set< types::material_id > & complement_subdomain_material_ids, std::vector< bool > & selected_dofs, const bool reset_selectors_to_true = true)
Mark the DoFs in cells by excluding those DoFs in cells in the complement subdomain. The complement subdomain is specified by a set of material ids.
Returns
Effective number of DoFs.
Definition at line 175 of file dof_tools_ext.h.
References DoFToolsExt::extract_material_domain_dofs_by_excluding_complement_subdomain().
Referenced by DoFToolsExt::extract_material_domain_dofs_by_excluding_complement_subdomain().
extract_material_domain_dofs_excluding_boundary_dofs()
template<int dim, int spacedim> types::global_dof_index DoFToolsExt::extract_material_domain_dofs_excluding_boundary_dofs (const DoFHandler< dim, spacedim > & dof_handler, const std::set< types::material_id > & boundary_cell_material_ids, std::vector< bool > & selected_dofs)
Definition at line 435 of file dof_tools_ext.h.
extract_material_domain_mg_dofs()
template<int dim, int spacedim> types::global_dof_index DoFToolsExt::extract_material_domain_mg_dofs (const DoFHandler< dim, spacedim > & dof_handler, const unsigned int level, const std::set< types::material_id > & material_ids, std::vector< bool > & selected_dofs, const bool reset_selectors_to_false = true)
Mark the DoFs in cells on the specified level which have a material id belonging to the given collection.
Returns
Effective number of DoFs.
Definition at line 229 of file dof_tools_ext.h.
References DoFToolsExt::extract_material_domain_mg_dofs().
Referenced by DoFToolsExt::extract_material_domain_mg_dofs().
extract_material_domain_mg_dofs_by_excluding_complement_subdomain()
template<int dim, int spacedim> types::global_dof_index DoFToolsExt::extract_material_domain_mg_dofs_by_excluding_complement_subdomain (const DoFHandler< dim, spacedim > & dof_handler, const unsigned int level, const std::set< types::material_id > & complement_subdomain_material_ids, std::vector< bool > & selected_dofs, const bool reset_selectors_to_true = true)
Mark the DoFs in cells on the specified level by excluding those DoFs in cells in the complement subdomain. The complement subdomain is specified by a set of material ids.
Returns
Effective number of DoFs.
Definition at line 284 of file dof_tools_ext.h.
References DoFToolsExt::extract_material_domain_mg_dofs_by_excluding_complement_subdomain().
Referenced by DoFToolsExt::extract_material_domain_mg_dofs_by_excluding_complement_subdomain().
extract_subdomain_dofs()
template<int dim, int spacedim> void DoFToolsExt::extract_subdomain_dofs (const DoFHandler< dim, spacedim > & dof_handler, const std::set< types::subdomain_id > & subdomain_ids, std::vector< bool > & selected_dofs)
N.B. This function appears here because the already instantiated deal.ii versions only assume dim==spacedim. Meanwhile, the general template version only appears in dof_tool.cc, which is not accessible to the outside.
Parameters
dof_handler
subdomain_id
selected_dofs
Definition at line 68 of file dof_tools_ext.h.
References DoFToolsExt::extract_subdomain_dofs().
Referenced by DoFToolsExt::extract_subdomain_dofs().
generate_full_to_local_dof_id_map()
void DoFToolsExt::generate_full_to_local_dof_id_map (const std::vector< bool > & dof_selectors, std::vector< types::global_dof_index > & full_to_local_map)
Generate the full-to-local DoF index map based on the DoF selectors.
Parameters
dof_selectors
full_to_local_map The memory for this vector should be preallocated. The number of elements is the total number of DoFs in the DoF handler.
Definition at line 25 of file dof_tools_ext.cc.
References DoFToolsExt::generate_full_to_local_dof_id_map().
Referenced by DoFToolsExt::generate_full_to_local_dof_id_map().
generate_local_to_full_dof_id_map()
void DoFToolsExt::generate_local_to_full_dof_id_map (const std::vector< bool > & dof_selectors, std::vector< types::global_dof_index > & local_to_full_map)
Generate the local-to-full DoF index map based on the DoF selectors.
Parameters
dof_selectors
local_to_full_map The memory for this vector should be reserved. The maximum possible number of elements is the total number of DoFs in the DoF handler.
Definition at line 43 of file dof_tools_ext.cc.
References DoFToolsExt::generate_local_to_full_dof_id_map().
Referenced by DoFToolsExt::generate_local_to_full_dof_id_map().
generate_maps_between_full_and_local_dof_ids()
void DoFToolsExt::generate_maps_between_full_and_local_dof_ids (const std::vector< bool > & dof_selectors, std::vector< types::global_dof_index > & full_to_local_map, std::vector< types::global_dof_index > & local_to_full_map)
Generate the full-to-local and local-to-full DoF index maps based on the DoF selectors.
Parameters
dof_selectors
full_to_local_map The memory for this vector should be preallocated. The number of elements is the total number of DoFs in the DoF handler.
local_to_full_map The memory for this vector should be reserved. The maximum possible number of elements is the total number of DoFs in the DoF handler.
Definition at line 57 of file dof_tools_ext.cc.
References DoFToolsExt::generate_maps_between_full_and_local_dof_ids().
Referenced by DoFToolsExt::generate_maps_between_full_and_local_dof_ids().
make_sparsity_pattern() [1/2]
template<int dim, int spacedim, typename SparsityPatternType > void DoFToolsExt::make_sparsity_pattern (const DoFHandler< dim, spacedim > & dof_handler_test_space, const DoFHandler< dim, spacedim > & dof_handler_trial_space, const std::set< types::material_id > & subdomain_material_ids, const std::vector< bool > & dof_selectors_test_space, const std::vector< types::global_dof_index > & full_to_local_dof_id_map_test_space, const std::vector< bool > & dof_selectors_trial_space, const std::vector< types::global_dof_index > & full_to_local_dof_id_map_trial_space, SparsityPatternType & sparsity)
Make sparsity pattern on subdomain for active cells.
The shape functions are assumed to be truncated within the subdomain, so we iterate over each cell in the subdomain.
Definition at line 1762 of file dof_tools_ext.h.
References DoFToolsExt::make_sparsity_pattern().
make_sparsity_pattern() [2/2]
template<int dim, int spacedim, typename SparsityPatternType > void DoFToolsExt::make_sparsity_pattern (const DoFHandler< dim, spacedim > & dof_handler_test_space, const DoFHandler< dim, spacedim > & dof_handler_trial_space, const std::vector< bool > & dof_selectors_test_space, const std::vector< types::global_dof_index > & full_to_local_dof_id_map_test_space, const std::vector< bool > & dof_selectors_trial_space, const std::vector< types::global_dof_index > & full_to_local_dof_id_map_trial_space, SparsityPatternType & sparsity)
Make sparsity pattern on subdomain for active cells.
The shape functions may extend over the boundary of the subdomain, so that we iterate over each cell in the triangulation, without checking if the cell is within the subdomain.
Definition at line 1713 of file dof_tools_ext.h.
References DoFToolsExt::make_sparsity_pattern().
Referenced by DoFToolsExt::make_sparsity_pattern().
map_dofs_to_average_cell_size() [1/2]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_dofs_to_average_cell_size (const DoFHandler< dim, spacedim > & dof_handler, const std::vector< types::global_dof_index > & map_from_local_to_full_dof_indices, std::vector< Number > & dof_average_cell_size)
Calculate the average cell sizes associated with a subset of DoFs selected from all those DoFs in the DoF handler.
Note
The doubled cell size will be used as an estimate for the diameter of the support set of each DoF.
Precondition
Postcondition
Template Parameters
dim
spacedim
Number
Parameters
dof_handler DoF handler object.
map_from_local_to_full_dof_indices This is a vector which stores a list of global DoF indices corresponding to the DoFs held in the dof_handler, while the element indices of this vector play the role of local DoF indices corresponding to the selected DoFs. Therefore, this vector is used as a map from local to global DoF indices.
dof_average_cell_size The returned list of average cell sizes which corresponds to the selected DoFs. The memory for this vector should be preallocated and initialized to zero before calling this function.
Definition at line 1014 of file dof_tools_ext.h.
References DoFToolsExt::map_dofs_to_average_cell_size().
map_dofs_to_average_cell_size() [2/2]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_dofs_to_average_cell_size (const DoFHandler< dim, spacedim > & dof_handler, std::vector< Number > & dof_average_cell_size)
Calculate the average cell sizes associated with those DoFs in the given DoF handler object.
Note
The doubled cell size will be used as an estimate for the diameter of the support set of each DoF.
Parameters
dof_handler DoF handler object.
dof_average_cell_size The returned list of average cell sizes which corresponds to the DoFs held within the DoF handler object. The memory for this vector should be preallocated and initialized to zero before calling this function.
Create the vector which stores the number of cells that share a common DoF for each DoF.
Get the diameter of the current cell.
Get DoF indices local to this cell.
Definition at line 894 of file dof_tools_ext.h.
References DoFToolsExt::map_dofs_to_average_cell_size().
Referenced by DoFToolsExt::map_dofs_to_average_cell_size().
map_dofs_to_max_cell_size() [1/2]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_dofs_to_max_cell_size (const DoFHandler< dim, spacedim > & dof_handler, const std::vector< types::global_dof_index > & map_from_local_to_full_dof_indices, std::vector< Number > & dof_max_cell_size)
Calculate the maximum cell sizes associated with a subset of DoFs selected from all those DoFs in the DoF handler.
Parameters
dof_handler
map_from_local_to_full_dof_indices
dof_max_cell_size The returned list of maximum cell sizes. The memory for this vector should be preallocated and initialized to zero before calling this function.
Definition at line 1174 of file dof_tools_ext.h.
References DoFToolsExt::map_dofs_to_max_cell_size().
map_dofs_to_max_cell_size() [2/2]
template<typename DoFHandlerType , typename Number = double> void DoFToolsExt::map_dofs_to_max_cell_size (const DoFHandlerType & dof_handler, std::vector< Number > & dof_max_cell_size)
Calculate the maximum cell sizes associated with those DoFs in the given DoF handler object.
The value doubled is used as an estimate for the diameter of the support set of each DoF.
Parameters
dof_handler
dof_max_cell_size The returned list of maximum cell sizes. The memory for this vector should be preallocated and initialized to zero before calling this function.
Get the diameter of the current cell.
Get DoF indices local to this cell.
Definition at line 1087 of file dof_tools_ext.h.
References DoFToolsExt::map_dofs_to_max_cell_size().
Referenced by DoFToolsExt::map_dofs_to_max_cell_size().
map_dofs_to_min_cell_size() [1/2]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_dofs_to_min_cell_size (const DoFHandler< dim, spacedim > & dof_handler, const std::vector< types::global_dof_index > & map_from_local_to_full_dof_indices, std::vector< Number > & dof_min_cell_size)
Calculate the minimum cell sizes associated with a subset of DoFs selected from all those DoFs in the DoF handler.
Template Parameters
Number
dim
spacedim
Parameters
dof_handler
map_from_local_to_full_dof_indices
dof_min_cell_size The returned list of minimum cell sizes. The memory for this vector should be preallocated and initialized to zero before calling this function.
Definition at line 1334 of file dof_tools_ext.h.
References DoFToolsExt::map_dofs_to_min_cell_size().
map_dofs_to_min_cell_size() [2/2]
template<typename DoFHandlerType , typename Number = double> void DoFToolsExt::map_dofs_to_min_cell_size (const DoFHandlerType & dof_handler, std::vector< Number > & dof_min_cell_size)
Calculate the minimum cell sizes associated with those DoFs in the given DoF handler object.
The value doubled is used as an estimate for the diameter of the support set of each DoF.
Parameters
dof_min_cell_size The returned list of minimum cell sizes. The memory for this vector should be preallocated and initialized to zero before calling this function.
Get the diameter of the current cell.
Get DoF indices local to this cell.
Definition at line 1244 of file dof_tools_ext.h.
References DoFToolsExt::map_dofs_to_min_cell_size().
Referenced by DoFToolsExt::map_dofs_to_min_cell_size().
map_dofs_to_support_points() [1/2]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_dofs_to_support_points (const Mapping< dim, spacedim > & mapping, const DoFHandler< dim, spacedim > & dof_handler, const std::vector< types::global_dof_index > & map_from_local_to_full_dof_indices, std::vector< Point< spacedim, Number > > & support_points)
Return a list of support points for the local DoFs selected from the full list of DoFs handled by the DoF handler.
The result is a vector of support points.
Precondition
Postcondition
Template Parameters
dim
spacedim
Parameters
mapping The mapping from the reference cell to the real cell on which DoFs are defined.
dof_handler The DoF handler object, in which the finite element object should provide support points.
map_from_local_to_full_dof_indices This is a vector which stores a list of global DoF indices corresponding to the DoFs held in the dof_handler, while the element indices of this vector play the role of local DoF indices corresponding to the selected DoFs. Therefore, this vector is used as a map from local to global DoF indices.
support_points A vector that stores the corresponding location of the DoFs in real space coordinates. Before calling this function, this vector should has the same size as the number of selected local DoFs, which is also equal to the size of map_from_local_to_full_dof_indices. Previous content of this object is deleted in this function.
Definition at line 546 of file dof_tools_ext.h.
References DoFToolsExt::map_dofs_to_support_points().
map_dofs_to_support_points() [2/2]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_dofs_to_support_points (const Mapping< dim, spacedim > & mapping, const DoFHandler< dim, spacedim > & dof_handler, std::vector< Point< spacedim, Number > > & support_points)
Get the coordinates for all support points in the DoF handler.
This function returns the coordinates of the given template type, while deal.ii's implementation only returns the double type.
Definition at line 499 of file dof_tools_ext.h.
References DoFToolsExt::map_dofs_to_support_points().
Referenced by DoFToolsExt::map_dofs_to_support_points().
map_dofs_to_support_points_and_normal_vectors()
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_dofs_to_support_points_and_normal_vectors (MappingInfo< dim, spacedim > & mapping_info, const DoFHandler< dim, spacedim > & dof_handler, std::vector< Point< spacedim, Number > > & support_points, std::vector< Tensor< 1, spacedim, Number > > & normal_vectors, const bool is_normal_vector_negated = false)
Compute point coordinates and normal vectors at the support points of the finite element in the DoF handler.
Parameters
mapping_order Polynomial order of the Lagrange shape functions used for the mapping.
dof_handler DoF handler for the target triangulation on which the support points and normal vectors will be computed.
support_points
normal_vectors
is_normal_vector_negated Whether the computed normal vectors should be negated in case the original norma directions are not what we desire.
Definition at line 585 of file dof_tools_ext.h.
References MappingQExt< dim, spacedim >::get_support_points(), DoFToolsExt::map_dofs_to_support_points_and_normal_vectors(), and MappingInfo< dim, spacedim >::resize_internal_data().
Referenced by DoFToolsExt::map_dofs_to_support_points_and_normal_vectors().
map_mg_dofs_to_average_cell_size() [1/2]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_mg_dofs_to_average_cell_size (const DoFHandler< dim, spacedim > & dof_handler, const unsigned int level, const std::vector< types::global_dof_index > & map_from_local_to_full_dof_indices, std::vector< Number > & dof_average_cell_size)
Calculate the average cell sizes associated with a subset of DoFs selected from all those DoFs on a specific level in the DoF handler.
Template Parameters
Number
dim
spacedim
Parameters
dof_handler
map_from_local_to_full_dof_indices
level
dof_average_cell_size The returned list of average cell sizes. The memory for this vector should be preallocated and initialized to zero before calling this function.
Definition at line 1050 of file dof_tools_ext.h.
References DoFToolsExt::map_mg_dofs_to_average_cell_size().
map_mg_dofs_to_average_cell_size() [2/2]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_mg_dofs_to_average_cell_size (const DoFHandler< dim, spacedim > & dof_handler, const unsigned int level, std::vector< Number > & dof_average_cell_size)
Calculate the average cell sizes associated with those DoFs on a specific level in the given DoF handler object.
Template Parameters
Number
dim
spacedim
Parameters
dof_handler
level
dof_average_cell_size The returned list of average cell sizes. The memory for this vector should be preallocated and initialized to zero before calling this function.
Create the vector which stores the number of cells that share a common DoF for each DoF.
Get the diameter of the current cell.
Get DoF indices local to this cell.
Definition at line 949 of file dof_tools_ext.h.
References DoFToolsExt::map_mg_dofs_to_average_cell_size().
Referenced by DoFToolsExt::map_mg_dofs_to_average_cell_size().
map_mg_dofs_to_max_cell_size() [1/2]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_mg_dofs_to_max_cell_size (const DoFHandler< dim, spacedim > & dof_handler, const unsigned int level, const std::vector< types::global_dof_index > & map_from_local_to_full_dof_indices, std::vector< Number > & dof_max_cell_size)
Calculate the maximum cell sizes associated with a subset of DoFs selected from all those DoFs on a specific level in the DoF handler.
Template Parameters
Number
dim
spacedim
Parameters
dof_handler
map_from_local_to_full_dof_indices
level
dof_max_cell_size The returned list of maximum cell sizes. The memory for this vector should be preallocated and initialized to zero before calling this function.
Definition at line 1210 of file dof_tools_ext.h.
References DoFToolsExt::map_mg_dofs_to_max_cell_size().
map_mg_dofs_to_max_cell_size() [2/2]
template<typename DoFHandlerType , typename Number = double> void DoFToolsExt::map_mg_dofs_to_max_cell_size (const DoFHandlerType & dof_handler, const unsigned int level, std::vector< Number > & dof_max_cell_size)
Calculate the maximum cell sizes associated with those DoFs on a specific level in the given DoF handler object.
Parameters
dof_handler
level
dof_max_cell_size The returned list of maximum cell sizes. The memory for this vector should be preallocated and initialized to zero before calling this function.
Get the diameter of the current cell.
Get DoF indices local to this cell.
Definition at line 1130 of file dof_tools_ext.h.
References DoFToolsExt::map_mg_dofs_to_max_cell_size().
Referenced by DoFToolsExt::map_mg_dofs_to_max_cell_size().
map_mg_dofs_to_min_cell_size() [1/2]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_mg_dofs_to_min_cell_size (const DoFHandler< dim, spacedim > & dof_handler, const unsigned int level, const std::vector< types::global_dof_index > & map_from_local_to_full_dof_indices, std::vector< Number > & dof_min_cell_size)
Calculate the minimum cell sizes associated with a subset of DoFs selected from all those DoFs on a specific level in the DoF handler.
Template Parameters
Number
dim
spacedim
Parameters
dof_handler
map_from_local_to_full_dof_indices
level
dof_min_cell_size The returned list of minimum cell sizes. The memory for this vector should be preallocated and initialized to zero before calling this function.
Definition at line 1370 of file dof_tools_ext.h.
References DoFToolsExt::map_mg_dofs_to_min_cell_size().
map_mg_dofs_to_min_cell_size() [2/2]
template<typename DoFHandlerType , typename Number = double> void DoFToolsExt::map_mg_dofs_to_min_cell_size (const DoFHandlerType & dof_handler, const unsigned int level, std::vector< Number > & dof_min_cell_size)
Calculate the minimum cell sizes associated with those DoFs on a specific level in the given DoF handler object.
Parameters
dof_min_cell_size The returned list of minimum cell sizes. The memory for this vector should be preallocated and initialized to zero before calling this function.
Get the diameter of the current cell.
Get DoF indices local to this cell.
Definition at line 1286 of file dof_tools_ext.h.
References DoFToolsExt::map_mg_dofs_to_min_cell_size().
Referenced by DoFToolsExt::map_mg_dofs_to_min_cell_size().
map_mg_dofs_to_support_points() [1/4]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_mg_dofs_to_support_points (const Mapping< dim, spacedim > & mapping, const DoFHandler< dim, spacedim > & dof_handler, const unsigned int level, const std::set< types::material_id > & subdomain_material_ids, const std::vector< bool > & dof_selectors, const std::vector< types::global_dof_index > & full_to_local_dof_id_map, std::map< types::global_dof_index, Point< spacedim, Number > > & support_points)
Return a list of support points for DoFs in a subdomain on the specified level in the DoF handler.
The result is a map from local DoF indices to support points, which can be passed to DoFTools::write_gnuplot_dof_support_point_info for visualizing the distribution of support points.
Definition at line 775 of file dof_tools_ext.h.
References DoFToolsExt::map_mg_dofs_to_support_points().
map_mg_dofs_to_support_points() [2/4]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_mg_dofs_to_support_points (const Mapping< dim, spacedim > & mapping, const DoFHandler< dim, spacedim > & dof_handler, const unsigned int level, const std::set< types::material_id > & subdomain_material_ids, const std::vector< bool > & dof_selectors, const std::vector< types::global_dof_index > & full_to_local_dof_id_map, std::vector< Point< spacedim, Number > > & support_points)
Return a list of support points for DoFs in a subdomain on the specified level in the DoF handler.
The result is a vector of support points and its memory should be preallocated.
Template Parameters
dim
spacedim
Parameters
mapping
dof_handler
level
support_points The memory of the list of support points should be preallocated.
Definition at line 837 of file dof_tools_ext.h.
References DoFToolsExt::map_mg_dofs_to_support_points().
map_mg_dofs_to_support_points() [3/4]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_mg_dofs_to_support_points (const Mapping< dim, spacedim > & mapping, const DoFHandler< dim, spacedim > & dof_handler, const unsigned int level, std::map< types::global_dof_index, Point< spacedim, Number > > & support_points)
Return a list of support points for DoFs on the specified level in the DoF handler.
The result is a map from DoF indices to support points, which can be passed to DoFTools::write_gnuplot_dof_support_point_info for visualizing the distribution of support points.
Template Parameters
dim
spacedim
Parameters
mapping
dof_handler
level
support_points
Definition at line 682 of file dof_tools_ext.h.
References DoFToolsExt::map_mg_dofs_to_support_points().
Referenced by DoFToolsExt::map_mg_dofs_to_support_points().
map_mg_dofs_to_support_points() [4/4]
template<int dim, int spacedim, typename Number = double> void DoFToolsExt::map_mg_dofs_to_support_points (const Mapping< dim, spacedim > & mapping, const DoFHandler< dim, spacedim > & dof_handler, const unsigned int level, std::vector< Point< spacedim, Number > > & support_points)
Return a list of support points for DoFs on the specified level in the DoF handler.
The results is a vector of support points and its memory should be preallocated.
Template Parameters
dim
spacedim
Parameters
mapping
dof_handler
level
support_points
Definition at line 732 of file dof_tools_ext.h.
References DoFToolsExt::map_mg_dofs_to_support_points().
write_gnuplot_dof_support_point_info()
template<int spacedim, typename Number = double> void DoFToolsExt::write_gnuplot_dof_support_point_info (std::ostream & out, const std::map< types::global_dof_index, Point< spacedim, Number > > & support_points, const std::vector< bool > & selected_dofs, const bool has_label = true)
Print out support points for the list of selected DoFs, which are used for visualization in Gnuplot.
Template Parameters
spacedim
Parameters
out
support_points
selected_dofs
has_label
Definition at line 1403 of file dof_tools_ext.h.
References DoFToolsExt::write_gnuplot_dof_support_point_info().
Referenced by DoFToolsExt::write_gnuplot_dof_support_point_info().