HierBEM: include/utilities/generic_functors.h File Reference
generic_functors.h File Reference
This header file contains a set of self-defined generic functors.
#include <deal.II/base/exceptions.h>
#include <deal.II/base/point.h>
#include <deal.II/base/tensor.h>
#include <deal.II/base/types.h>
#include <deal.II/lac/lapack_support.h>
#include <deal.II/lac/vector.h>
#include <array>
#include <cmath>
#include <cstring>
#include <forward_list>
#include <iterator>
#include <map>
#include <type_traits>
#include <vector>
#include "config.h"
Typedefs
using size_type = std::make_unsigned< types::blas_int >::type
Functions
template<typename InputIterator , typename T >
InputIterator find_pointer_data (InputIterator first, InputIterator last, const T *value_pointer)
template<typename VectorType >
void permute_vector_by_ipiv (VectorType &v, const std::vector< dealii::types::blas_int > &ipiv)
template<typename number >
void copy_vector (Vector< number > &dst_vec, const typename Vector< number >::size_type dst_start_index, const Vector< number > &src_vec, const typename Vector< number >::size_type src_start_index, const typename Vector< number >::size_type number_of_data)
template<typename T >
size_type size (const std::forward_list< T > &fl)
template<typename T >
T & value_at (std::forward_list< T > &fl, const size_type i)
template<typename T >
const T & value_at (const std::forward_list< T > &fl, const size_type i)
template<typename T >
void erase_at (std::forward_list< T > &fl, const size_type i)
template<template< typename > typename Container, typename number >
void gen_linear_indices (Container< number > &a, number starting_value=0, number step=1)
template<typename KeyType , typename ValueType >
std::size_t memory_consumption_of_map (const std::map< KeyType, ValueType > &m)
template<int spacedim, typename Number = double>
bool is_equal (const Point< spacedim, Number > &p1, const Point< spacedim, Number > &p2)
template<int spacedim, typename Number = double>
bool is_equal (const Point< spacedim, Number > &p1, const Point< spacedim, Number > &p2, const Number threshold)
template<int dim, typename Number , typename VectorType >
void VectorToTensor (const VectorType &v, Tensor< 1, dim, Number > &t)
template<int dim, typename Number , typename VectorType >
Tensor< 1, dim, Number > VectorToTensor (const VectorType &v)
template<typename Value >
bool is_subset (const std::array< Value, 2 > &range1, const std::array< Value, 2 > &range2)
template<typename Value >
bool is_proper_subset (const std::array< Value, 2 > &range1, const std::array< Value, 2 > &range2)
template<typename Value >
bool is_superset (const std::array< Value, 2 > &range1, const std::array< Value, 2 > &range2)
template<typename Value >
bool is_proper_superset (const std::array< Value, 2 > &range1, const std::array< Value, 2 > &range2)
template<typename Value >
void intersect (const std::array< Value, 2 > &range1, const std::array< Value, 2 > &range2, std::array< Value, 2 > &range_intersection)
Detailed Description
This header file contains a set of self-defined generic functors.
Date
2021-07-20
Author
Jihuan Tian
Definition in file generic_functors.h.
Typedef Documentation
size_type
using size_type = std::make_unsigned<types::blas_int>::type
Definition at line 43 of file generic_functors.h.
Function Documentation
copy_vector()
template<typename number > void copy_vector (Vector< number > & dst_vec, const typename Vector< number >::size_type dst_start_index, const Vector< number > & src_vec, const typename Vector< number >::size_type src_start_index, const typename Vector< number >::size_type number_of_data)
Copy a number of data from source vector to target vector.
Parameters
dst_vec
dst_start_index
src_vec
src_start_index
number_of_data
Definition at line 113 of file generic_functors.h.
erase_at()
template<typename T > void erase_at (std::forward_list< T > & fl, const size_type i)
Erase the i'th element of the std::forward_list.
Parameters
fl
i
Definition at line 192 of file generic_functors.h.
Referenced by random_select_ref_column(), and random_select_ref_row().
find_pointer_data()
template<typename InputIterator , typename T > InputIterator find_pointer_data (InputIterator first, InputIterator last, const T * value_pointer)
Find the pointer in a list of pointers of the same type. The comparison is based on the data being pointed instead of the pointer addresses.
Parameters
first
last
value_pointer
Returns
N.B. Here we use (*first) to get the pointer stored in the container. Then use (*(*first)) to get the data associated with this pointer.
Definition at line 55 of file generic_functors.h.
Referenced by HMatrix< spacedim, Number >::coarsen_to_partition(), and prune_to_partition_recursion().
gen_linear_indices()
template<template< typename > typename Container, typename number > void gen_linear_indices (Container< number > & a, number starting_value = 0, number step = 1)
Generate a list of linearized indices into a container by starting from the given value with the specified increment step.
Note
The definition of this function adopts the template template and alias template techniques.
Parameters
a The container holding the list of linearized indices
starting_value The starting value to be placed into the first element of the list
step The step value
Definition at line 214 of file generic_functors.h.
intersect()
template<typename Value > void intersect (const std::array< Value, 2 > & range1, const std::array< Value, 2 > & range2, std::array< Value, 2 > & range_intersection)
Definition at line 408 of file generic_functors.h.
is_equal() [1/2]
template<int spacedim, typename Number = double> bool is_equal (const Point< spacedim, Number > & p1, const Point< spacedim, Number > & p2)
Check the equality of the two points using raw comparison instead of numerical comparison.
Note
Here the raw comparison means each component in the dim coordinates of p1 is directly compared with that of p2, which is not checking if the absolute value of their difference is less than a threshold. The latter is a common technique in numerical computation.
Parameters
p1
p2
Returns
Definition at line 255 of file generic_functors.h.
is_equal() [2/2]
template<int spacedim, typename Number = double> bool is_equal (const Point< spacedim, Number > & p1, const Point< spacedim, Number > & p2, const Number threshold)
Check the equality of the two points using numerical comparison instead of raw comparison.
Parameters
p1
p2
threshold
Returns
Definition at line 283 of file generic_functors.h.
is_proper_subset()
template<typename Value > bool is_proper_subset (const std::array< Value, 2 > & range1, const std::array< Value, 2 > & range2)
Check if range1 is a proper subset of range2.
Parameters
range1
range2
Returns
Definition at line 365 of file generic_functors.h.
Referenced by Cluster< spacedim, Number >::is_proper_subset().
is_proper_superset()
template<typename Value > bool is_proper_superset (const std::array< Value, 2 > & range1, const std::array< Value, 2 > & range2)
Check if range1 is a proper super set of range2.
Parameters
range1
range2
Returns
Definition at line 398 of file generic_functors.h.
Referenced by Cluster< spacedim, Number >::is_proper_superset().
is_subset()
template<typename Value > bool is_subset (const std::array< Value, 2 > & range1, const std::array< Value, 2 > & range2)
Check if range1 is a subset of range2.
Parameters
range1
range2
Returns
Definition at line 349 of file generic_functors.h.
Referenced by LAPACKFullMatrixExt< Number >::fill_rows(), Cluster< spacedim, Number >::is_subset(), LAPACKFullMatrixExt< Number >::LAPACKFullMatrixExt(), and RkMatrix< Number >::restrictToFullMatrix().
is_superset()
template<typename Value > bool is_superset (const std::array< Value, 2 > & range1, const std::array< Value, 2 > & range2)
Check if range1 is a super set of range2.
Parameters
range1
range2
Returns
Definition at line 382 of file generic_functors.h.
Referenced by Cluster< spacedim, Number >::is_superset().
memory_consumption_of_map()
template<typename KeyType , typename ValueType > std::size_t memory_consumption_of_map (const std::map< KeyType, ValueType > & m)
Compute the memory consumption for a std::map.
Parameters
m
Returns
Definition at line 234 of file generic_functors.h.
permute_vector_by_ipiv()
template<typename VectorType > void permute_vector_by_ipiv (VectorType & v, const std::vector< dealii::types::blas_int > & ipiv)
Permute a vector according to the permutation vector ipiv obtained from an LU factorization.
Parameters
v
ipiv The vector storing the row permutation obtained from an LU factorization. The row indices stored in ipiv starts from 1 instead of 0.
Definition at line 87 of file generic_functors.h.
size()
template<typename T > size_type size (const std::forward_list< T > & fl)
Get the size of a std::forward_list.
Parameters
fl
Returns
Definition at line 142 of file generic_functors.h.
Referenced by CUDAWrappers::CUDATable< N, T >::assign_from_host(), random_select_ref_column(), and random_select_ref_row().
value_at() [1/2]
template<typename T > const T & value_at (const std::forward_list< T > & fl, const size_type i)
Get the const reference to the i'th element of the std::forward_list.
Parameters
fl
index
Returns
Definition at line 175 of file generic_functors.h.
value_at() [2/2]
template<typename T > T & value_at (std::forward_list< T > & fl, const size_type i)
Get the reference to the i'th element of the std::forward_list.
Parameters
fl
index
Returns
Definition at line 157 of file generic_functors.h.
Referenced by random_select_ref_column(), and random_select_ref_row().
VectorToTensor() [1/2]
template<int dim, typename Number , typename VectorType > Tensor< 1, dim, Number > VectorToTensor (const VectorType & v)
Definition at line 325 of file generic_functors.h.
VectorToTensor() [2/2]
template<int dim, typename Number , typename VectorType > void VectorToTensor (const VectorType & v, Tensor< 1, dim, Number > & t)
Convert a vector to a rank-1 tensor.
Parameters
v
t
Definition at line 312 of file generic_functors.h.