HierBEM: include/hmatrix/hmatrix_support.h File Reference
hmatrix_support.h File Reference
Hierarchical matrices
Adapted from deal.ii/lac/lapack_support.h and define some features for an \(\mathcal{H}\)-matrix.
#include <deal.II/base/exceptions.h>
#include <array>
#include <string>
#include "config.h"
Enumerations
enum HMatrixSupport::State {
HMatrixSupport::matrix , HMatrixSupport::inverse_matrix , HMatrixSupport::lu , HMatrixSupport::cholesky ,
HMatrixSupport::eigenvalues , HMatrixSupport::svd , HMatrixSupport::inverse_svd , HMatrixSupport::unusable = 0x8000
}
enum HMatrixSupport::Property {
HMatrixSupport::general = 0 , HMatrixSupport::symmetric = 1 , HMatrixSupport::upper_triangular = 2 , HMatrixSupport::lower_triangular = 4 ,
HMatrixSupport::hermite_symmetric = 6
}
enum HMatrixSupport::BlockType { HMatrixSupport::undefined_block = 0 , HMatrixSupport::diagonal_block = 1 , HMatrixSupport::upper_triangular_block = 2 , HMatrixSupport::lower_triangular_block = 4 }
Functions
const char * HMatrixSupport::state_name (State s)
const char * HMatrixSupport::property_name (const Property s)
const char * HMatrixSupport::block_type_name (const BlockType b)
void HMatrixSupport::infer_submatrix_block_types_from_parent_hmat (const BlockType parent_hmat_block_type, std::array< HMatrixSupport::BlockType, 4 > &submatrix_block_types)
Detailed Description
Adapted from deal.ii/lac/lapack_support.h and define some features for an \(\mathcal{H}\)-matrix.
Date
2021-10-20
Author
Jihuan Tian
Definition in file hmatrix_support.h.
Enumeration Type Documentation
BlockType
enum HMatrixSupport::BlockType
Type of the matrix block, which can be diagonal block, upper triangular block or lower triangular block.
Note
N.B. Here the diagonal/upper-triangular/lower-triangular block does not mean the matrix block itself is a diagonal/upper-triangular/lower-triangular matrix, but means that the matrix block belongs to the diagonal/upper-triangular/lower-triangular part of the original matrix.
For an \(\mathcal{H}\)-matrix built with respect to a quad-block cluster tree,
the top level \(\mathcal{H}\)-matrix node is a diagonal block;
if the current \(\mathcal{H}\)-matrix node is a diagonal block and has submatrices, the first and last submatrices are still diagonal blocks, while the second submatrix is an upper triangular block and the third submatrix is a lower triangular block;
if the current \(\mathcal{H}\)-matrix node is an upper (lower) triangular block and has submatrices, all of them are upper (lower) triangular blocks.
Enumerator
undefined_block
Undefined block type.
diagonal_block
Diagonal block.
upper_triangular_block
Upper triangular block.
lower_triangular_block
Lower triangular block.
Definition at line 184 of file hmatrix_support.h.
Property
enum HMatrixSupport::Property
A matrix can have certain features allowing for optimization, but hard to test. These are listed here.
general: the \(\mathcal{H}\)-matrix is general and all the \(\mathcal{H}\)-matrix nodes in the \(\mathcal{H}\)-matrix hierarchy are created and allocated with memory.
symmetric: the \(\mathcal{H}\)-matrix is symmetric and only the diagonal blocks in the near field and matrix blocks in the lower triangular part are created and allocated with memory. For the matrix blocks in the upper triangular part, basic matrix information, such as dimension, is still maintained but the memory for data is not allocated. The matrix blocks in the upper triangular part is assumed to be symmetric to those related blocks in the lower triangular part.
upper_triangular: only the matrix blocks in the upper triangular part and the diagonal blocks in the near field are created and allocated with memory.The matrix blocks in the lower triangular part are zero valued. Their basic matrix information, such as dimension, is still maintained but the memory for the data is not allocated.
lower_triangular: only the matrix blocks in the lower triangular part and the diagonal blocks in the near field are created and allocated with memory.The matrix blocks in the upper triangular part are zero valued. Their basic matrix information, such as dimension, is still stored but the memory for the data is not allocated.
hermite_symmetric
Enumerator
general
No special properties.
symmetric
Matrix is symmetric.
upper_triangular
Matrix is upper triangular.
lower_triangular
Matrix is lower triangular.
hermite_symmetric
Matrix is Hermite symmetric.
Definition at line 125 of file hmatrix_support.h.
State
enum HMatrixSupport::State
Most functions that one can apply to an \(\mathcal{H}\)-matrix (e.g., by calling the member functions of this class) change the content of the \(\mathcal{H}\)-matrix in some ways. For example, they may invert the matrix, or may replace it by a matrix whose columns represent the eigenvectors of the original content of the matrix. The elements of this enumeration are therefore used to track what is currently being stored by this object.
Comment
The above documentation is extracted from deal.ii.
Enumerator
matrix
Contents is actually a matrix.
inverse_matrix
Contents is the inverse of a matrix.
lu
Contents is an LU decomposition.
cholesky
Contents is a Cholesky decomposition.
eigenvalues
Eigenvalue vector is filled.
svd
Matrix contains singular value decomposition,.
inverse_svd
Matrix is the inverse of a singular value decomposition.
unusable
Contents is something useless.
Definition at line 47 of file hmatrix_support.h.
Function Documentation
block_type_name()
const char * HMatrixSupport::block_type_name (const BlockType b) inline
Function printing the name of the block type.
Definition at line 201 of file hmatrix_support.h.
References HMatrixSupport::block_type_name().
Referenced by HMatrixSupport::block_type_name().
infer_submatrix_block_types_from_parent_hmat()
void HMatrixSupport::infer_submatrix_block_types_from_parent_hmat (const BlockType parent_hmat_block_type, std::array< HMatrixSupport::BlockType, 4 > & submatrix_block_types)
Determine the block types of the four submatrices from the given block type of their parent \(\mathcal{H}\)-matrix.
References HMatrixSupport::infer_submatrix_block_types_from_parent_hmat().
Referenced by HMatrixSupport::infer_submatrix_block_types_from_parent_hmat().
property_name()
const char * HMatrixSupport::property_name (const Property s) inline
Function printing the name of a Property.
Definition at line 144 of file hmatrix_support.h.
References HMatrixSupport::property_name().
Referenced by HMatrixSupport::property_name().
state_name()
const char * HMatrixSupport::state_name (State s) inline
Function printing the name of a State.
Definition at line 72 of file hmatrix_support.h.
References HMatrixSupport::state_name().
Referenced by HMatrixSupport::state_name().