HierBEM: include/hmatrix/hmatrix.h File Reference
hmatrix.h File Reference
Hierarchical matrices
Definition of hierarchical matrix.
#include <deal.II/base/logstream.h>
#include <deal.II/base/numbers.h>
#include <deal.II/base/thread_management.h>
#include <deal.II/base/types.h>
#include <deal.II/lac/full_matrix.h>
#include <deal.II/lac/vector.h>
#include <openblas-pthread/cblas.h>
#include <tbb/tbb.h>
#include <algorithm>
#include <fstream>
#include <iostream>
#include <memory>
#include <mutex>
#include <queue>
#include <sstream>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
#include "cluster_tree/block_cluster.h"
#include "cluster_tree/block_cluster_tree.h"
#include "config.h"
#include "hmatrix/hmatrix_support.h"
#include "hmatrix/hmatrix_vmult_strategy.h"
#include "linear_algebra/lapack_full_matrix_ext.h"
#include "rkmatrix.h"
#include "sequence_partition/sequence_partition.h"
#include "utilities/generic_functors.h"
#include "utilities/number_traits.h"
Classes
class HMatrix< spacedim, Number >
struct HMatrix< spacedim, Number >::VmultOrTvmultThreadData
class HMatrix< spacedim, Number >::UpdateTaskNodeForLUOrCholesky
Enumerations
enum HMatrixType { FullMatrixType , RkMatrixType , HierarchicalMatrixType , UndefinedMatrixType }
Functions
DeclException1 (ExcInvalidHMatrixType, HMatrixType,<< "Invalid H-matrix node type: "<< arg1)
DeclException1 (ExcInvalidHMatrixState, HMatrixSupport::State,<< "Invalid H-matrix node state: "<< arg1)
DeclException1 (ExcInvalidHMatrixProperty, HMatrixSupport::Property,<< "Invalid H-matrix node property: "<< arg1)
DeclException1 (ExcInvalidHMatrixBlockType, HMatrixSupport::BlockType,<< "Invalid H-matrix node block type: "<< arg1)
template<int spacedim, typename Number = double>
void InitHMatrixWrtBlockClusterNode (HMatrix< spacedim, Number > &hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node)
template<int spacedim, typename Number = double>
void InitHMatrixWrtBlockClusterNode (HMatrix< spacedim, Number > &hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const std::vector< std::pair< HMatrix< spacedim, Number > *, HMatrix< spacedim, Number > * > > &Sigma_P)
template<int spacedim, typename Number = double>
void InitHMatrixWrtBlockClusterNode (HMatrix< spacedim, Number > &hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const std::pair< HMatrix< spacedim, Number > *, HMatrix< spacedim, Number > * > &hmat_pair)
template<int spacedim, typename Number = double>
void InitAndCreateHMatrixChildrenWithoutAlloc (HMatrix< spacedim, Number > *hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node)
template<int spacedim, typename Number = double>
void InitAndCreateHMatrixChildren (HMatrix< spacedim, Number > *hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const unsigned int fixed_rank_k, const HMatrixSupport::Property top_hmat_node_property=HMatrixSupport::Property::general)
template<int spacedim, typename Number = double>
void InitAndCreateHMatrixChildren (HMatrix< spacedim, Number > *hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const unsigned int fixed_rank_k, const LAPACKFullMatrixExt< Number > &M, const HMatrixSupport::Property top_hmat_node_property=HMatrixSupport::Property::general)
template<int spacedim, typename Number = double>
void InitAndCreateHMatrixChildren (HMatrix< spacedim, Number > *hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const LAPACKFullMatrixExt< Number > &M, const HMatrixSupport::Property top_hmat_node_property=HMatrixSupport::Property::general)
template<int spacedim, typename Number = double>
void InitAndCreateHMatrixChildren (HMatrix< spacedim, Number > *hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const unsigned int fixed_rank_k, const LAPACKFullMatrixExt< Number > &M, const std::array< types::global_dof_index, 2 > &M_row_index_range, const std::array< types::global_dof_index, 2 > &M_col_index_range, const HMatrixSupport::Property top_hmat_node_property=HMatrixSupport::Property::general)
template<int spacedim, typename Number = double>
void InitAndCreateHMatrixChildren (HMatrix< spacedim, Number > *hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const LAPACKFullMatrixExt< Number > &M, const std::array< types::global_dof_index, 2 > &M_row_index_range, const std::array< types::global_dof_index, 2 > &M_col_index_range, const HMatrixSupport::Property top_hmat_node_property=HMatrixSupport::Property::general)
template<int spacedim, typename Number = double>
void InitAndCreateHMatrixChildren (HMatrix< spacedim, Number > *hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, HMatrix< spacedim, Number > &&H)
template<int spacedim, typename Number >
void RefineHMatrixWrtExtendedBlockClusterTree (HMatrix< spacedim, Number > *starting_hmat, HMatrix< spacedim, Number > *current_hmat)
template<int spacedim, typename Number = double>
void convertHMatBlockToRkMatrix (HMatrix< spacedim, Number > *hmat_block, const unsigned int fixed_rank_k, const HMatrix< spacedim, Number > *hmat_root_block=nullptr, size_t *calling_counter=nullptr, const std::string &output_file_base_name=std::string("hmat-bct"))
template<int spacedim, typename Number = double>
void h_rk_mmult (HMatrix< spacedim, Number > &M1, const RkMatrix< Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void h_rk_mmult (const Number alpha, HMatrix< spacedim, Number > &M1, const RkMatrix< Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void h_rk_mTmult (HMatrix< spacedim, Number > &M1, const RkMatrix< Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void h_rk_mTmult (const Number alpha, HMatrix< spacedim, Number > &M1, const RkMatrix< Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void h_rk_Tmmult (HMatrix< spacedim, Number > &M1, const RkMatrix< Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void h_rk_Tmmult (const Number alpha, HMatrix< spacedim, Number > &M1, const RkMatrix< Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void h_rk_mmult_for_h_h_mmult (HMatrix< spacedim, Number > *M1, const HMatrix< spacedim, Number > *M2, HMatrix< spacedim, Number > *M, bool is_M1M2_last_in_M_Sigma_P=true)
template<int spacedim, typename Number = double>
void rk_h_mmult (const RkMatrix< Number > &M1, HMatrix< spacedim, Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void rk_h_mmult (const Number alpha, const RkMatrix< Number > &M1, HMatrix< spacedim, Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void rk_h_mTmult (const RkMatrix< Number > &M1, HMatrix< spacedim, Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void rk_h_mTmult (const Number alpha, const RkMatrix< Number > &M1, HMatrix< spacedim, Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void rk_h_Tmmult (const RkMatrix< Number > &M1, HMatrix< spacedim, Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void rk_h_Tmmult (const Number alpha, const RkMatrix< Number > &M1, HMatrix< spacedim, Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void rk_h_mmult_for_h_h_mmult (const HMatrix< spacedim, Number > *M1, HMatrix< spacedim, Number > *M2, HMatrix< spacedim, Number > *M, bool is_M1M2_last_in_M_Sigma_P=true)
template<int spacedim, typename Number = double>
void h_f_mmult (HMatrix< spacedim, Number > &M1, const LAPACKFullMatrixExt< Number > &M2, LAPACKFullMatrixExt< Number > &M)
template<int spacedim, typename Number = double>
void h_f_mmult (const Number alpha, HMatrix< spacedim, Number > &M1, const LAPACKFullMatrixExt< Number > &M2, LAPACKFullMatrixExt< Number > &M)
template<int spacedim, typename Number = double>
void h_f_mTmult (HMatrix< spacedim, Number > &M1, const LAPACKFullMatrixExt< Number > &M2, LAPACKFullMatrixExt< Number > &M)
template<int spacedim, typename Number = double>
void h_f_mTmult (const Number alpha, HMatrix< spacedim, Number > &M1, const LAPACKFullMatrixExt< Number > &M2, LAPACKFullMatrixExt< Number > &M)
template<int spacedim, typename Number = double>
void h_f_Tmmult (HMatrix< spacedim, Number > &M1, const LAPACKFullMatrixExt< Number > &M2, LAPACKFullMatrixExt< Number > &M)
template<int spacedim, typename Number = double>
void h_f_Tmmult (const Number alpha, HMatrix< spacedim, Number > &M1, const LAPACKFullMatrixExt< Number > &M2, LAPACKFullMatrixExt< Number > &M)
template<int spacedim, typename Number = double>
void h_f_mmult (HMatrix< spacedim, Number > &M1, const LAPACKFullMatrixExt< Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void h_f_mmult (const Number alpha, HMatrix< spacedim, Number > &M1, const LAPACKFullMatrixExt< Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void h_f_mTmult (HMatrix< spacedim, Number > &M1, const LAPACKFullMatrixExt< Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void h_f_mTmult (const Number alpha, HMatrix< spacedim, Number > &M1, const LAPACKFullMatrixExt< Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void h_f_Tmmult (HMatrix< spacedim, Number > &M1, const LAPACKFullMatrixExt< Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void h_f_Tmmult (const Number alpha, HMatrix< spacedim, Number > &M1, const LAPACKFullMatrixExt< Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void h_f_mmult_for_h_h_mmult (HMatrix< spacedim, Number > *M1, const HMatrix< spacedim, Number > *M2, HMatrix< spacedim, Number > *M, bool is_M1M2_last_in_M_Sigma_P=true)
template<int spacedim, typename Number = double>
void f_h_mmult (const LAPACKFullMatrixExt< Number > &M1, HMatrix< spacedim, Number > &M2, LAPACKFullMatrixExt< Number > &M)
template<int spacedim, typename Number = double>
void f_h_mmult (const Number alpha, const LAPACKFullMatrixExt< Number > &M1, HMatrix< spacedim, Number > &M2, LAPACKFullMatrixExt< Number > &M)
template<int spacedim, typename Number = double>
void f_h_mTmult (const LAPACKFullMatrixExt< Number > &M1, HMatrix< spacedim, Number > &M2, LAPACKFullMatrixExt< Number > &M)
template<int spacedim, typename Number = double>
void f_h_mTmult (const Number alpha, const LAPACKFullMatrixExt< Number > &M1, HMatrix< spacedim, Number > &M2, LAPACKFullMatrixExt< Number > &M)
template<int spacedim, typename Number = double>
void f_h_Tmmult (const LAPACKFullMatrixExt< Number > &M1, HMatrix< spacedim, Number > &M2, LAPACKFullMatrixExt< Number > &M)
template<int spacedim, typename Number = double>
void f_h_Tmmult (const Number alpha, const LAPACKFullMatrixExt< Number > &M1, HMatrix< spacedim, Number > &M2, LAPACKFullMatrixExt< Number > &M)
template<int spacedim, typename Number = double>
void f_h_mmult (const LAPACKFullMatrixExt< Number > &M1, HMatrix< spacedim, Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void f_h_mmult (const Number alpha, const LAPACKFullMatrixExt< Number > &M1, HMatrix< spacedim, Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void f_h_mTmult (const LAPACKFullMatrixExt< Number > &M1, HMatrix< spacedim, Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void f_h_mTmult (const Number alpha, const LAPACKFullMatrixExt< Number > &M1, HMatrix< spacedim, Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void f_h_Tmmult (const LAPACKFullMatrixExt< Number > &M1, HMatrix< spacedim, Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void f_h_Tmmult (const Number alpha, const LAPACKFullMatrixExt< Number > &M1, HMatrix< spacedim, Number > &M2, RkMatrix< Number > &M)
template<int spacedim, typename Number = double>
void f_h_mmult_for_h_h_mmult (const HMatrix< spacedim, Number > *M1, HMatrix< spacedim, Number > *M2, HMatrix< spacedim, Number > *M, bool is_M1M2_last_in_M_Sigma_P=true)
template<int spacedim, typename Number = double>
void h_h_mmult_phase1_recursion (HMatrix< spacedim, Number > *M, BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type > &Tind)
template<int spacedim, typename Number = double>
void h_h_mmult_phase2 (HMatrix< spacedim, Number > &M, BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type > &target_bc_tree, const unsigned int fixed_rank)
template<int spacedim, typename Number >
void h_h_mmult_from_leaf_node (HMatrix< spacedim, Number > &M0, HMatrix< spacedim, Number > &M, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_mmult_from_leaf_node (HMatrix< spacedim, Number > &M0, HMatrix< spacedim, Number > &M, const Number alpha, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_mmult_from_leaf_node_for_parallel_lu (HMatrix< spacedim, Number > &M0, HMatrix< spacedim, Number > &M, const Number alpha, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_mTmult_from_leaf_node (HMatrix< spacedim, Number > &M0, HMatrix< spacedim, Number > &M, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_mTmult_from_leaf_node (HMatrix< spacedim, Number > &M0, HMatrix< spacedim, Number > &M, const Number alpha, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_mTmult_from_leaf_node_for_parallel_cholesky (HMatrix< spacedim, Number > &M0, HMatrix< spacedim, Number > &M, const Number alpha, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_Tmmult_from_leaf_node (HMatrix< spacedim, Number > &M0, HMatrix< spacedim, Number > &M, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_Tmmult_from_leaf_node (HMatrix< spacedim, Number > &M0, HMatrix< spacedim, Number > &M, const Number alpha, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_mmult_level_conserving (HMatrix< spacedim, Number > &M, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_mmult_level_conserving (HMatrix< spacedim, Number > &M, const Number alpha, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_mmult_level_conserving_for_parallel_lu (HMatrix< spacedim, Number > &M, const Number alpha, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_mTmult_level_conserving (HMatrix< spacedim, Number > &M, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_mTmult_level_conserving (HMatrix< spacedim, Number > &M, const Number alpha, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_mTmult_level_conserving_for_parallel_cholesky (HMatrix< spacedim, Number > &M, const Number alpha, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_Tmmult_level_conserving (HMatrix< spacedim, Number > &M, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number >
void h_h_Tmmult_level_conserving (HMatrix< spacedim, Number > &M, const Number alpha, HMatrix< spacedim, Number > &M1, HMatrix< spacedim, Number > &M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only=false)
template<int spacedim, typename Number = double>
void copy_hmatrix_node (HMatrix< spacedim, Number > &hmat_dst, const HMatrix< spacedim, Number > &hmat_src)
template<int spacedim, typename Number = double>
void copy_hmatrix_node (HMatrix< spacedim, Number > &hmat_dst, HMatrix< spacedim, Number > &&hmat_src)
template<int spacedim, typename Number = double>
void copy_hmatrix (HMatrix< spacedim, Number > &hmat_dst, const HMatrix< spacedim, Number > &hmat_src)
template<int spacedim, typename Number = double>
void print_h_submatrix_accessor (std::ostream &out, const std::string &name, const HMatrix< spacedim, Number > &M)
template<int spacedim, typename Number = double>
void print_h_h_submatrix_mmult_accessor (std::ostream &out, const std::string &name1, const HMatrix< spacedim, Number > &M1, const std::string &name2, const HMatrix< spacedim, Number > &M2)
template<int spacedim, typename Number >
void hmatrix_solve_lu (const HMatrix< spacedim, Number > &L, const HMatrix< spacedim, Number > &U, Vector< Number > &x, const Vector< Number > &b)
template<int spacedim, typename Number >
void hmatrix_solve_cholesky (const HMatrix< spacedim, Number > &L, Vector< Number > &x, const Vector< Number > &b)
Detailed Description
Definition of hierarchical matrix.
Date
2021-06-06
Author
Jihuan Tian
Definition in file hmatrix.h.
Enumeration Type Documentation
HMatrixType
enum HMatrixType
Matrix type of an HMaxtrix, which can be full matrix in the near field, rank-k matrix in the far field and hierarchical matrix which does not belong to the leaf set of a block cluster tree.
Enumerator
FullMatrixType
FullMatrixType.
RkMatrixType
RkMatrixType.
HierarchicalMatrixType
HierarchicalType.
UndefinedMatrixType
UndefinedMatrixType.
Definition at line 65 of file hmatrix.h.
Function Documentation
convertHMatBlockToRkMatrix()
template<int spacedim, typename Number = double> void convertHMatBlockToRkMatrix (HMatrix< spacedim, Number > * hmat_block, const unsigned int fixed_rank_k, const HMatrix< spacedim, Number > * hmat_root_block = nullptr, size_t * calling_counter = nullptr, const std::string & output_file_base_name = std::string("hmat-bct"))
Convert an \(\mathcal{H}\)-matrix block hmat_block recursively into a rank-k matrix or a full matrix, which depends on whether the block cluster associated with hmat_block is large or not.
Generally speaking, this method can be considered as the agglomeration of all descendants of hmat_block.
Note
This method implements the operator \(\mathcal{T}_r^{\mathcal{R} \leftarrow \mathcal{H}}\), i.e. the algorithm \(Convert\_H\) in (7.8) in Hackbusch's \(\mathcal{H}\)-matrix book.
This \(\mathcal{H}\)-matrix block is implemented as a node in a whole \(\mathcal{H}\)-matrix hierarchy. This conversion algorithm will recursively descend in the hierarchical matrices for processing:
when the current matrix block belongs to the near field set \(P^-\), it is represented as a full matrix and no operations will be applied to it;
when it belongs to the far field set \(P^+\), it is already a rank-k matrix, which will then be truncated to the given fixed_rank_k;
when it is not a leaf, i.e. it is a hierarchical matrix, this function will be called recursively for each of its children. After that,
a. if the block cluster related to the current matrix is large, pairwise agglomeration for rank-k matrices will be performed and a rank-k matrix will be obtained with the given rank fixed_rank_k;
b. if the block cluster related to the current matrix is small, agglomeration of full matrices will be performed and a full matrix will be obtained.
Parameters
hmat_block the pointer to the current matrix block from which the recursion will start.
fixed_rank_k the fixed rank to which the rank-k matrices in the far field set will be truncated.
hmat_root_block the pointer to the root \(\mathcal{H}\)-matrix block, which is only used for exporting matrix partition structure for further visualization.
calling_counter the pointer to the counter which records the current total number of calling times of this function. Its value will be used to construct the name of the output file, which stores the matrix partition structure.
output_file_base_name the based name of the output file which stores the matrix partition structure.
Work flow
When the current \(\mathcal{H}\)-matrix block belongs to the leaf set.
When the current \(\mathcal{H}\)-matrix belongs to the near field set, it should be of a full matrix type. Therefore, we make an assertion here. After that we do nothing, since a near field node should always be represented as a full matrix, thus the rank truncation should not be applied.
When the current \(\mathcal{H}\)-matrix belongs to the far field set, it should be of a rank-k matrix type. Therefore, we make an assertion here. After that the rank-k matrix block is truncated to the specified rank.
When the current \(\mathcal{H}\)-matrix block does not belong to the leaf set, recursively convert each child of it to rank-k matrix if possible.
When the current \(\mathcal{H}\)-matrix block belongs to the near field set, we perform the operation of full matrix agglomeration.
Note
Normally, this case cannot happen because when an \(\mathcal{H}\)-matrix block belongs to the near field, it is represented as a full matrix and belongs to the leaf set. However, this contradicts the precondition that the current \(\mathcal{H}\)-matrix block does not belong to the leaf set.
But still this situation may happen during the conversion of an \(\mathcal{H}\)-matrix to a different block cluster tree.
The general work flow for the agglomeration of a set of full matrix blocks is as below.
Create a large full matrix on the heap and assemble all submatrices into it which depends on the split mode of the block cluster.
a. When it is CrossSplitMode, apply agglomeration of four full submatrices.
b. When the split mode is HorizontalSplitMode, apply agglomeration of two full submatrices via vertical stacking.
c. When the split mode is VerticalSplitMode, apply agglomeration of two full submatrices via horizontal stacking.
Delete all submatrices associated with the current \(\mathcal{H}\)-matrix and clear the std::vector storing submatrix pointers.
Associate the new large full matrix with the current \(\mathcal{H}\)-matrix.
Update the \(\mathcal{H}\)-matrix type as FullMatrix.
About matrix assembly for CrossSplitMode
Let the block cluster associated with the current \(\mathcal{H}\)-matrix is \(\tau \times \sigma\). Assume the clusters are partitioned as \(\tau = [\tau_1, \tau_2]\) and \(\sigma = [\sigma_1, \sigma_2]\). Then the ordering of the child block clusters are \(\tau_1 \times \sigma_1, \tau_1 \times \sigma_2, \tau_2 \times \sigma_1, \tau_2 \times \sigma_2\).
When the current \(\mathcal{H}\)-matrix block belongs to the far field set, perform the pairwise matrix agglomeration of rank-k submatrices or full submatrices, which has been implemented into the constructor of RkMatrix.
If the children of the current \(\mathcal{H}\)-matrix block are rank-k matrices, perform the pairwise rank-k matrix agglomeration directly.
If the children of the current \(\mathcal{H}\)-matrix block are full matrices, firstly convert all of them into rank-k matrices, then perform the pairwise rank-k matrix agglomeration.
Other cases are invalid.
If the children of the current \(\mathcal{H}\)-matrix block are rank-k matrices, perform the pairwise rank-k matrix agglomeration directly.
If the children of the current \(\mathcal{H}\)-matrix block are full matrices, firstly convert all of them into rank-k matrices, then perform the pairwise rank-k matrix agglomeration.
Other cases are invalid.
If the children of the current \(\mathcal{H}\)-matrix block are rank-k matrices, perform the pairwise rank-k matrix agglomeration directly.
If the children of the current \(\mathcal{H}\)-matrix block are full matrices, firstly convert all of them into rank-k matrices, then perform the pairwise rank-k matrix agglomeration.
Other cases are invalid.
Visualize the partition structure if a not-null pointer to the root \(\mathcal{H}\)-matrix node and a a not-null pointer to a calling_counter are provided.
Definition at line 10017 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, convertHMatBlockToRkMatrix(), FullMatrixType, HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::submatrices, HMatrix< spacedim, Number >::type, and UndefinedMatrixType.
Referenced by HMatrix< spacedim, Number >::coarsen_to_partition(), and convertHMatBlockToRkMatrix().
copy_hmatrix()
template<int spacedim, typename Number = double> void copy_hmatrix (HMatrix< spacedim, Number > & hmat_dst, const HMatrix< spacedim, Number > & hmat_src)
Recursively copy an \(\mathcal{H}\)-matrix into the target matrix.
Parameters
M_dst
M_src
Copy the current \(\mathcal{H}\)-matrix node.
Recursively copy child \(\mathcal{H}\)-matrix nodes.
Create a corresponding child \(\mathcal{H}\)-matrix node on the heap and push it back into the submatrices list of the current \(\mathcal{H}\)-matrix node.
Definition at line 17518 of file hmatrix.h.
References copy_hmatrix(), copy_hmatrix_node(), HMatrix< spacedim, Number >::parent, and HMatrix< spacedim, Number >::submatrices.
Referenced by copy_hmatrix(), and HMatrix< spacedim, Number >::operator=().
copy_hmatrix_node() [1/2]
template<int spacedim, typename Number = double> void copy_hmatrix_node (HMatrix< spacedim, Number > & hmat_dst, const HMatrix< spacedim, Number > & hmat_src)
Deep copy an \(\mathcal{H}\)-matrix node into the target node, i.e. the copy is limited within the current node without recursion into its descendants. This function will be called by copy_hmatrix.
Note
1. Do not copy the list submatrices from the source submatrix, because newly created child matrices will be pushed back into this list.
Do not copy the list leaf_set. After the whole \(\mathcal{H}\)-matrix hierarchy has been constructed, the leaf set will be built in the constructor.
Do not copy the working data: Sigma_P, Sigma_F, Sigma_R and Tind.
Do not copy parent and it will be set during the recursive deep copy of the \(\mathcal{H}\)-matrix.
Parameters
hmat_dst
hmat_src
Copy the rank-k matrix in the source submatrix if it is not NULL.
Copy the full matrix in the source submatrix if it is not NULL.
Definition at line 17421 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::block_type, HMatrix< spacedim, Number >::col_index_range, HMatrix< spacedim, Number >::fullmatrix, HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::property, HMatrix< spacedim, Number >::rkmatrix, HMatrix< spacedim, Number >::row_index_range, HMatrix< spacedim, Number >::state, HMatrix< spacedim, Number >::submatrix_index, and HMatrix< spacedim, Number >::type.
Referenced by copy_hmatrix(), and HMatrix< spacedim, Number >::operator=().
copy_hmatrix_node() [2/2]
template<int spacedim, typename Number = double> void copy_hmatrix_node (HMatrix< spacedim, Number > & hmat_dst, HMatrix< spacedim, Number > && hmat_src)
Shallow copy an \(\mathcal{H}\)-matrix node into the target node, i.e. the copy is limited within the current node without recursion into its descendants. Or rather, we can say the destination \(\mathcal{H}\)-matrix takes over the data from the source \(\mathcal{H}\)-matrix.
Parameters
hmat_dst
hmat_src
Definition at line 17474 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::block_type, HMatrix< spacedim, Number >::col_index_range, HMatrix< spacedim, Number >::dot_node_id, HMatrix< spacedim, Number >::far_field_leaf_set, HMatrix< spacedim, Number >::fullmatrix, HMatrix< spacedim, Number >::leaf_set, HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::near_field_leaf_set, HMatrix< spacedim, Number >::next_same_level_hmat_node, HMatrix< spacedim, Number >::next_same_level_same_column_hmat_node, HMatrix< spacedim, Number >::next_same_level_same_row_hmat_node, HMatrix< spacedim, Number >::parent, HMatrix< spacedim, Number >::previous_same_level_same_column_hmat_node, HMatrix< spacedim, Number >::previous_same_level_same_row_hmat_node, HMatrix< spacedim, Number >::property, HMatrix< spacedim, Number >::rkmatrix, HMatrix< spacedim, Number >::row_index_range, HMatrix< spacedim, Number >::Sigma_F, HMatrix< spacedim, Number >::Sigma_P, HMatrix< spacedim, Number >::Sigma_R, HMatrix< spacedim, Number >::state, HMatrix< spacedim, Number >::submatrices, HMatrix< spacedim, Number >::submatrix_index, HMatrix< spacedim, Number >::Tind, and HMatrix< spacedim, Number >::type.
DeclException1() [1/4]
DeclException1 (ExcInvalidHMatrixBlockType , HMatrixSupport::BlockType , << "Invalid H-matrix node block type: "<< arg1)
Exception for invalid \(\mathcal{H}\)-matrix node block type (HMatrixSupport::BlockType).
DeclException1() [2/4]
DeclException1 (ExcInvalidHMatrixProperty , HMatrixSupport::Property , << "Invalid H-matrix node property: "<< arg1)
Exception for invalid \(\mathcal{H}\)-matrix node property (HMatrixSupport::Property).
DeclException1() [3/4]
DeclException1 (ExcInvalidHMatrixState , HMatrixSupport::State , << "Invalid H-matrix node state: "<< arg1)
Exception for invalid \(\mathcal{H}\)-matrix node state (HMatrixSupport:State).
DeclException1() [4/4]
DeclException1 (ExcInvalidHMatrixType , HMatrixType , << "Invalid H-matrix node type: "<< arg1)
Exception for invalid \(\mathcal{H}\)-matrix node type (HMatrixType).
f_h_mmult() [1/4]
template<int spacedim, typename Number = double> void f_h_mmult (const LAPACKFullMatrixExt< Number > & M1, HMatrix< spacedim, Number > & M2, LAPACKFullMatrixExt< Number > & M)
Multiplication of a full matrix and a \(\mathcal{H}\)-matrix. A full matrix is returned in M.
Parameters
M1
M2
M
Definition at line 11964 of file hmatrix.h.
References LAPACKFullMatrixExt< Number >::fill_row(), HMatrix< spacedim, Number >::get_property(), LAPACKFullMatrixExt< Number >::get_row(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, and HMatrix< spacedim, Number >::Tvmult().
Referenced by f_h_mmult_for_h_h_mmult(), and h_h_mmult_level_conserving().
f_h_mmult() [2/4]
template<int spacedim, typename Number = double> void f_h_mmult (const LAPACKFullMatrixExt< Number > & M1, HMatrix< spacedim, Number > & M2, RkMatrix< Number > & M)
Multiplication of a full matrix and a \(\mathcal{H}\)-matrix. A rank-k matrix is returned in M.
Parameters
M1
M2
M
The creation of the rank-k matrix M1_rk from M1 will modify M1 internally. Hence, we make a copy of M1 here.
Definition at line 12175 of file hmatrix.h.
References HMatrix< spacedim, Number >::m, and rk_h_mmult().
f_h_mmult() [3/4]
template<int spacedim, typename Number = double> void f_h_mmult (const Number alpha, const LAPACKFullMatrixExt< Number > & M1, HMatrix< spacedim, Number > & M2, LAPACKFullMatrixExt< Number > & M)
Multiplication of a full matrix and a \(\mathcal{H}\)-matrix and the result is scaled by a factor. A full matrix is returned in M.
Parameters
alpha
M1
M2
M
Since the following Tvmult will compute \(y = y + M^T x\), result_vect should be reset to zero beforehand.
Definition at line 11999 of file hmatrix.h.
f_h_mmult() [4/4]
template<int spacedim, typename Number = double> void f_h_mmult (const Number alpha, const LAPACKFullMatrixExt< Number > & M1, HMatrix< spacedim, Number > & M2, RkMatrix< Number > & M)
Multiplication of a full matrix and a \(\mathcal{H}\)-matrix and the result is scaled by a factor. A rank-k matrix is returned in M.
Parameters
alpha
M1
M2
M
The creation of the rank-k matrix M1_rk from M1 will modify M1 internally. Hence, we make a copy of M1 here.
Definition at line 12203 of file hmatrix.h.
f_h_mmult_for_h_h_mmult()
template<int spacedim, typename Number = double> void f_h_mmult_for_h_h_mmult (const HMatrix< spacedim, Number > * M1, HMatrix< spacedim, Number > * M2, HMatrix< spacedim, Number > * M, bool is_M1M2_last_in_M_Sigma_P = true)
Multiplication of two \(\mathcal{H}\)-matrices, where the first one is of FullMatrixType. An \(\mathcal{H}\)-matrix is returned in M, which is either of FullMatrixType or RkMatrixType.
Parameters
M1
M2
M
is_M1M2_last_in_M_Sigma_P
Full matrix is returned.
Rank-k matrix is returned.
Definition at line 12342 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, f_h_mmult(), HMatrix< spacedim, Number >::fullmatrix, FullMatrixType, HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::remove_hmat_pair_from_mm_product_list(), RkMatrixType, HMatrix< spacedim, Number >::Sigma_F, HMatrix< spacedim, Number >::Sigma_P, HMatrix< spacedim, Number >::Sigma_R, and HMatrix< spacedim, Number >::type.
Referenced by HMatrix< spacedim, Number >::h_h_mmult_reduction().
f_h_mTmult() [1/4]
template<int spacedim, typename Number = double> void f_h_mTmult (const LAPACKFullMatrixExt< Number > & M1, HMatrix< spacedim, Number > & M2, LAPACKFullMatrixExt< Number > & M)
Multiplication of a full matrix and a \(\mathcal{H}\)-matrix with the second operand being transposed. A full matrix is returned in M.
Parameters
M1
M2
M
Definition at line 12038 of file hmatrix.h.
References LAPACKFullMatrixExt< Number >::fill_row(), HMatrix< spacedim, Number >::get_property(), LAPACKFullMatrixExt< Number >::get_row(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, and HMatrix< spacedim, Number >::vmult().
Referenced by h_h_mTmult_level_conserving().
f_h_mTmult() [2/4]
template<int spacedim, typename Number = double> void f_h_mTmult (const LAPACKFullMatrixExt< Number > & M1, HMatrix< spacedim, Number > & M2, RkMatrix< Number > & M)
Multiplication of a full matrix and a \(\mathcal{H}\)-matrix with the second operand being transposed. A rank-k matrix is returned in M.
Parameters
M1
M2
M
The creation of the rank-k matrix M1_rk from M1 will modify M1 internally. Hence, we make a copy of M1 here.
Definition at line 12231 of file hmatrix.h.
References HMatrix< spacedim, Number >::n, and rk_h_mTmult().
f_h_mTmult() [3/4]
template<int spacedim, typename Number = double> void f_h_mTmult (const Number alpha, const LAPACKFullMatrixExt< Number > & M1, HMatrix< spacedim, Number > & M2, LAPACKFullMatrixExt< Number > & M)
Multiplication of a full matrix and a \(\mathcal{H}\)-matrix with the second operand being transposed, the result of which will be scaled by a factor. A full matrix is returned in M.
Parameters
alpha
M1
M2
M
Definition at line 12073 of file hmatrix.h.
f_h_mTmult() [4/4]
template<int spacedim, typename Number = double> void f_h_mTmult (const Number alpha, const LAPACKFullMatrixExt< Number > & M1, HMatrix< spacedim, Number > & M2, RkMatrix< Number > & M)
Multiplication of a full matrix and a \(\mathcal{H}\)-matrix with the second operand being transposed. The result will be scaled by a factor. A rank-k matrix is returned in M.
Parameters
alpha
M1
M2
M
The creation of the rank-k matrix M1_rk from M1 will modify M1 internally. Hence, we make a copy of M1 here.
Definition at line 12259 of file hmatrix.h.
f_h_Tmmult() [1/4]
template<int spacedim, typename Number = double> void f_h_Tmmult (const LAPACKFullMatrixExt< Number > & M1, HMatrix< spacedim, Number > & M2, LAPACKFullMatrixExt< Number > & M)
Multiplication of a transposed full matrix and a \(\mathcal{H}\)-matrix. A full matrix is returned in M.
Parameters
M1
M2
M
Definition at line 12107 of file hmatrix.h.
References LAPACKFullMatrixExt< Number >::fill_row(), LAPACKFullMatrixExt< Number >::get_column(), HMatrix< spacedim, Number >::get_property(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, and HMatrix< spacedim, Number >::Tvmult().
Referenced by h_h_Tmmult_level_conserving().
f_h_Tmmult() [2/4]
template<int spacedim, typename Number = double> void f_h_Tmmult (const LAPACKFullMatrixExt< Number > & M1, HMatrix< spacedim, Number > & M2, RkMatrix< Number > & M)
Multiplication of a transposed full matrix and a \(\mathcal{H}\)-matrix. A rank-k matrix is returned in M.
Parameters
M1
M2
M
The creation of the rank-k matrix M1_rk from M1 will modify M1 internally. Hence, we make a copy of M1 here.
Definition at line 12287 of file hmatrix.h.
References HMatrix< spacedim, Number >::m, and rk_h_Tmmult().
f_h_Tmmult() [3/4]
template<int spacedim, typename Number = double> void f_h_Tmmult (const Number alpha, const LAPACKFullMatrixExt< Number > & M1, HMatrix< spacedim, Number > & M2, LAPACKFullMatrixExt< Number > & M)
Scaled multiplication of a transposed full matrix and a \(\mathcal{H}\)-matrix. A full matrix is returned in M.
Parameters
alpha
M1
M2
M
Definition at line 12141 of file hmatrix.h.
f_h_Tmmult() [4/4]
template<int spacedim, typename Number = double> void f_h_Tmmult (const Number alpha, const LAPACKFullMatrixExt< Number > & M1, HMatrix< spacedim, Number > & M2, RkMatrix< Number > & M)
Scaled multiplication of a transposed full matrix and a \(\mathcal{H}\)-matrix. A rank-k matrix is returned in M.
Parameters
alpha
M1
M2
M
The creation of the rank-k matrix M1_rk from M1 will modify M1 internally. Hence, we make a copy of M1 here.
Definition at line 12314 of file hmatrix.h.
h_f_mmult() [1/4]
template<int spacedim, typename Number = double> void h_f_mmult (const Number alpha, HMatrix< spacedim, Number > & M1, const LAPACKFullMatrixExt< Number > & M2, LAPACKFullMatrixExt< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the result scaled by a factor. The second operand is a full matrix and the result is also represented as a full matrix because the associated block cluster node \(\tau\times\rho\) is small.
Parameters
alpha
M1
M2
M
Definition at line 11496 of file hmatrix.h.
h_f_mmult() [2/4]
template<int spacedim, typename Number = double> void h_f_mmult (const Number alpha, HMatrix< spacedim, Number > & M1, const LAPACKFullMatrixExt< Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the result scaled by a factor. The second operand is a full matrix and the result is represented as a rank-k matrix because the associated block cluster is large.
The second matrix M2 will be firstly converted to a rank-k matrix. Then its multiplication with M1 will be carried by calling h_rk_mmult. Since the conversion from a full matrix to a rank-k matrix will modify the original data, a copy of M2 will be created.
Parameters
alpha
M1
M2
M
Create a local copy of the full matrix M2.
Convert the full matrix M2 to a rank-k matrix.
Definition at line 11707 of file hmatrix.h.
h_f_mmult() [3/4]
template<int spacedim, typename Number = double> void h_f_mmult (HMatrix< spacedim, Number > & M1, const LAPACKFullMatrixExt< Number > & M2, LAPACKFullMatrixExt< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes, where the second one is a full matrix and the result is also represented as a full matrix because the associated block cluster node \(\tau\times\rho\) is small.
Parameters
M1
M2
M
Definition at line 11460 of file hmatrix.h.
References LAPACKFullMatrixExt< Number >::fill_col(), LAPACKFullMatrixExt< Number >::get_column(), HMatrix< spacedim, Number >::get_property(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, and HMatrix< spacedim, Number >::vmult().
Referenced by h_f_mmult_for_h_h_mmult(), and h_h_mmult_level_conserving().
h_f_mmult() [4/4]
template<int spacedim, typename Number = double> void h_f_mmult (HMatrix< spacedim, Number > & M1, const LAPACKFullMatrixExt< Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes, where the second one is a full matrix and the result is represented as a rank-k matrix because the associated block cluster is large.
The second matrix M2 will be firstly converted to a rank-k matrix. Then its multiplication with M1 will be carried by calling h_rk_mmult. Since the conversion from a full matrix to a rank-k matrix will modify the original data, a copy of M2 will be created.
Parameters
M1
M2
M
Create a local copy of the full matrix M2.
Convert the full matrix M2 to a rank-k matrix.
Definition at line 11669 of file hmatrix.h.
References h_rk_mmult(), and HMatrix< spacedim, Number >::n.
h_f_mmult_for_h_h_mmult()
template<int spacedim, typename Number = double> void h_f_mmult_for_h_h_mmult (HMatrix< spacedim, Number > * M1, const HMatrix< spacedim, Number > * M2, HMatrix< spacedim, Number > * M, bool is_M1M2_last_in_M_Sigma_P = true)
Multiplication of two \(\mathcal{H}\)-matrices, where the second one is of FullMatrixType. An \(\mathcal{H}\)-matrix is returned in M, which is either of FullMatrixType or RkMatrixType.
Parameters
M1
M2
M
is_M1M2_last_in_M_Sigma_P
Full matrix is returned.
Rank-k matrix is returned.
Definition at line 11894 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::fullmatrix, FullMatrixType, h_f_mmult(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::remove_hmat_pair_from_mm_product_list(), RkMatrixType, HMatrix< spacedim, Number >::Sigma_F, HMatrix< spacedim, Number >::Sigma_P, HMatrix< spacedim, Number >::Sigma_R, and HMatrix< spacedim, Number >::type.
Referenced by HMatrix< spacedim, Number >::h_h_mmult_reduction().
h_f_mTmult() [1/4]
template<int spacedim, typename Number = double> void h_f_mTmult (const Number alpha, HMatrix< spacedim, Number > & M1, const LAPACKFullMatrixExt< Number > & M2, LAPACKFullMatrixExt< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the second operand being transposed, where the second one is a full matrix and the result is also represented as a full matrix because the associated block cluster node \(\tau\times\rho\) is small. The result will be scaled by a factor.
Parameters
M1
M2
M
Definition at line 11567 of file hmatrix.h.
h_f_mTmult() [2/4]
template<int spacedim, typename Number = double> void h_f_mTmult (const Number alpha, HMatrix< spacedim, Number > & M1, const LAPACKFullMatrixExt< Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the second operand being transposed, where the second one is a full matrix and the result is represented as a rank-k matrix because the associated block cluster is large. The result will be scaled by a factor.
The second matrix M2 will be firstly converted to a rank-k matrix. Then its multiplication with M1 will be carried by calling h_rk_mTmult. Since the conversion from a full matrix to a rank-k matrix will modify the original data, a copy of M2 will be created.
Parameters
M1
M2
M
Create a local copy of the full matrix M2.
Convert the full matrix M2 to a rank-k matrix.
Definition at line 11784 of file hmatrix.h.
h_f_mTmult() [3/4]
template<int spacedim, typename Number = double> void h_f_mTmult (HMatrix< spacedim, Number > & M1, const LAPACKFullMatrixExt< Number > & M2, LAPACKFullMatrixExt< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the second operand being transposed, where the second one is a full matrix and the result is also represented as a full matrix because the associated block cluster node \(\tau\times\rho\) is small.
Parameters
M1
M2
M
Definition at line 11532 of file hmatrix.h.
References LAPACKFullMatrixExt< Number >::fill_col(), HMatrix< spacedim, Number >::get_property(), LAPACKFullMatrixExt< Number >::get_row(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, and HMatrix< spacedim, Number >::vmult().
Referenced by h_h_mTmult_level_conserving().
h_f_mTmult() [4/4]
template<int spacedim, typename Number = double> void h_f_mTmult (HMatrix< spacedim, Number > & M1, const LAPACKFullMatrixExt< Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the second operand being transposed, where the second one is a full matrix and the result is represented as a rank-k matrix because the associated block cluster is large.
The second matrix M2 will be firstly converted to a rank-k matrix. Then its multiplication with M1 will be carried by calling h_rk_mTmult. Since the conversion from a full matrix to a rank-k matrix will modify the original data, a copy of M2 will be created.
Parameters
M1
M2
M
Create a local copy of the full matrix M2.
Convert the full matrix M2 to a rank-k matrix.
Definition at line 11746 of file hmatrix.h.
References h_rk_mTmult(), and HMatrix< spacedim, Number >::n.
h_f_Tmmult() [1/4]
template<int spacedim, typename Number = double> void h_f_Tmmult (const Number alpha, HMatrix< spacedim, Number > & M1, const LAPACKFullMatrixExt< Number > & M2, LAPACKFullMatrixExt< Number > & M)
Definition at line 11628 of file hmatrix.h.
h_f_Tmmult() [2/4]
template<int spacedim, typename Number = double> void h_f_Tmmult (const Number alpha, HMatrix< spacedim, Number > & M1, const LAPACKFullMatrixExt< Number > & M2, RkMatrix< Number > & M)
Calculate the scaled product of two \(\mathcal{H}\)-matrix nodes with the first operand being transposed, where the second one is a full matrix and the result is represented as a rank-k matrix because the associated block cluster is large.
The second matrix M2 will be firstly converted to a rank-k matrix. Then its multiplication with M1^T will be carried by calling h_rk_Tmmult. Since the conversion from a full matrix to a rank-k matrix will modify the original data, a copy of M2 will be created.
Parameters
alpha
M1
M2
M
Create a local copy of the full matrix M2.
Convert the full matrix M2 to a rank-k matrix.
Definition at line 11862 of file hmatrix.h.
h_f_Tmmult() [3/4]
template<int spacedim, typename Number = double> void h_f_Tmmult (HMatrix< spacedim, Number > & M1, const LAPACKFullMatrixExt< Number > & M2, LAPACKFullMatrixExt< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the first operand being transposed, where the second one is a full matrix and the result is also represented as a full matrix because the associated block cluster node \(\tau\times\rho\) is small.
Parameters
M1
M2
M
Definition at line 11603 of file hmatrix.h.
References LAPACKFullMatrixExt< Number >::fill_col(), LAPACKFullMatrixExt< Number >::get_column(), HMatrix< spacedim, Number >::get_property(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, and HMatrix< spacedim, Number >::Tvmult().
Referenced by h_h_Tmmult_level_conserving().
h_f_Tmmult() [4/4]
template<int spacedim, typename Number = double> void h_f_Tmmult (HMatrix< spacedim, Number > & M1, const LAPACKFullMatrixExt< Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the first operand being transposed, where the second one is a full matrix and the result is represented as a rank-k matrix because the associated block cluster is large.
The second matrix M2 will be firstly converted to a rank-k matrix. Then its multiplication with M1^T will be carried by calling h_rk_Tmmult. Since the conversion from a full matrix to a rank-k matrix will modify the original data, a copy of M2 will be created.
Parameters
M1
M2
M
Create a local copy of the full matrix M2.
Convert the full matrix M2 to a rank-k matrix.
Definition at line 11823 of file hmatrix.h.
References h_rk_Tmmult(), and HMatrix< spacedim, Number >::m.
h_h_mmult_from_leaf_node() [1/2]
template<int spacedim, typename Number > void h_h_mmult_from_leaf_node (HMatrix< spacedim, Number > & M0, HMatrix< spacedim, Number > & M, const Number alpha, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
\(\mathcal{H}\)-matrix- \(\mathcal{H}\)-matrix multiplication with the result scaled by a factor, when the product matrix belongs to the leaf set of the target block cluster tree.
This function implements the recursive MMR algorithm in (7.26) in Hackbusch's \(\mathcal{H}\)-matrix book.
Parameters
M0 The initial product matrix on the block cluster node \(\tau_0\times\rho_0\).
M The current product matrix \(M\) on the block cluster node \(\tau\times\rho\), which will assembles the contribution from \(M_1 \cdot M_2\) (N.B. This description is only valid for the first call of this function. During recursive calls of this function, M may not be on a same level as the product of M1 and M2, when both M1 and M2 have substructures and the multiplication needs to collect results from the multiplications of submatrices). For the first call of this function, M is the same as M0.
M1 The first operand of the multiplication, which is built upon the block cluster node \(\tau\times\sigma\).
M2 The second operand of the multiplication, which is built upon the block cluster node \(\sigma\times\rho\).
block_type_for_local_Z Block type for the local \(\mathcal{H}\)-matrix Z, which is the product of M1 and M2.
fixed_rank
is_result_matrix_store_tril_only Flag indicating whether only the lower triangular part and the diagonal part of the \(\mathcal{H}\)-matrix M are stored. The naming of this variable follows the convention adopted by GNU Octave, where a lower triangular matrix has nonzero entries only on the main diagonal and below. See tril and istril function in GNU Octave.
Here we make an assertion that the top level result \(\mathcal{H}\)-matrix M0 should be a leaf node.
Create a block cluster node \(\tau\times\rho\) for the current local product matrix Z. Since this block cluster node will not be connected with other block cluster nodes in a block cluster tree, it has neither parent nor children and its level is set to zero.
Set the is_near_field flag of the block cluster node for the current local product matrix Z according to the matrix type of the initial leaf node \(\mathcal{H}\)-matrix M0, i.e. it inherits the is_near_field flag of the block cluster node for M0.
When the flag is_result_matrix_store_tril_only is true, determine if the \(\mathcal{H}\)-matrix property of the local product \(\mathcal{H}\)-matrix Z should be the same as that of M by checking if the index ranges of its \(\tau\) node and \(\sigma\) are the same, since only when they are the same, Z or M's property can be symmetric, Hermite symmetric or lower triangular.
The local product \(\mathcal{H}\)-matrix Z inherits the property of M, which can be either symmetric, Hermite symmetric or lower triangular.
If the local \(\mathcal{H}\)-matrix Z is symmetric, Hermite symmetric or lower triangular, its block type should be diagonal_block and an assertion is made about this fact.
Create the local product \(\mathcal{H}\)-matrix Z associated with the current block cluster node. During its initialization, memory will be allocated depending on its \(\mathcal{H}\)-matrix property and block type.
When either operand M1 or M2 is a leaf node, directly evaluation of their multiplication can be performed.
If the local product \(\mathcal{H}\)-matrix Z is expected to be symmetric, Hermite symmetric or lower triangular, also set the property of the associated full matrix correspondingly. This operation is mandatory because the property of the local full matrix ZF is general, which has overwritten the property of Z.
In this case, both M1 and M2 have child submatrices.
When we perform submatrix multiplication, we use a higher specified rank, since the results will be assembled into the larger matrix Z via pairwise formatted addition, during which the actual matrix rank may increase.
The virtual submatrix block Z.submatrices[1], which is obtained from the cross type multiplication of M1 and M2, will be evaluated in two scenarios:
when the result matrix is not expected to be symmetric, Hermite symmetric or lower triangular;
when the result matrix is required to be symmetric, Hermite symmetric or lower triangular a priori, then if the product matrix Z is not symmetric, Hermite symmetric or lower triangular.
Here the "virtual" above means even though Z is actually not further divided and have no submatrices, the cross type multiplication will generate submatrix blocks virtually.
Assemble the local matrix Z to the product matrix M.
When the original matrix M0 belongs to the near field, assemble the full matrix stored in Z directly into M.
When the original matrix M0 does not belong to the near field, assemble the rank-k matrix stored in Z into M by first embedding then formatted addition, which has been implemented in the member function assemble_from_rkmatrix.
Definition at line 13010 of file hmatrix.h.
h_h_mmult_from_leaf_node() [2/2]
template<int spacedim, typename Number > void h_h_mmult_from_leaf_node (HMatrix< spacedim, Number > & M0, HMatrix< spacedim, Number > & M, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
\(\mathcal{H}\)-matrix- \(\mathcal{H}\)-matrix multiplication when the product matrix belongs to the leaf set of the target block cluster tree.
This function implements the recursive MMR algorithm in (7.26) in Hackbusch's \(\mathcal{H}\)-matrix book.
Parameters
M0 The initial product matrix on the block cluster node \(\tau_0\times\rho_0\), which is a leaf node in the product block cluster tree.
M The current product matrix \(M\) on the block cluster node \(\tau\times\rho\), which will assembles the contribution from \(M_1 \cdot M_2\) (N.B. This description is only valid for the first call of this function. During recursive calls of this function, M may not be on a same level as the product of M1 and M2, when both M1 and M2 have substructures and the multiplication needs to collect results from the multiplications of submatrices). For the first call of this function, M is the same as M0.
M1 The first operand of the multiplication, which is built upon the block cluster node \(\tau\times\sigma\).
M2 The second operand of the multiplication, which is built upon the block cluster node \(\sigma\times\rho\).
fixed_rank
Here we make an assertion that the top level result \(\mathcal{H}\)-matrix M0 should be a leaf node.
Create a block cluster node \(\tau\times\rho\) for the current local product matrix Z. Since this block cluster node will not be connected with other block cluster nodes in a block cluster tree, it has neither parent nor children and its level is set to zero.
Set the is_near_field flag of the block cluster node for the current local product matrix Z according to the matrix type of the initial leaf node \(\mathcal{H}\)-matrix M0, i.e. it inherits the is_near_field flag of the block cluster node for M0.
When the flag is_result_matrix_store_tril_only is true, determine if the \(\mathcal{H}\)-matrix property of the local product \(\mathcal{H}\)-matrix Z should be the same as that of M by checking if the index ranges of its \(\tau\) node and \(\sigma\) are the same, since only when they are the same, Z or M's property can be symmetric, Hermite symmetric or lower triangular.
The local product \(\mathcal{H}\)-matrix Z inherits the property of M, which can be either symmetric, Hermite symmetric or lower triangular.
If the local \(\mathcal{H}\)-matrix Z is symmetric, Hermite symmetric or lower triangular, its block type should be diagonal_block and an assertion is made about this fact.
Create the local product \(\mathcal{H}\)-matrix Z associated with the current block cluster node. During its initialization, memory will be allocated depending on its \(\mathcal{H}\)-matrix property and block type.
When either operand M1 or M2 is a leaf node, directly evaluation of their multiplication can be performed.
If the local product \(\mathcal{H}\)-matrix Z is expected to be symmetric, Hermite symmetric or lower triangular, also set the property of the associated full matrix correspondingly. This operation is mandatory because the property of the local full matrix ZF is general , which has overwritten the property of Z.
In this case, both M1 and M2 have child submatrices.
When we perform submatrix multiplication, we use a higher specified rank, since the results will be assembled into the larger matrix Z via pairwise formatted addition, during which the actual matrix rank may increase.
The submatrix block Z.submatrices[1], which is obtained from the cross type multiplication of M1 and M2, will be evaluated in two scenarios:
when the \(\mathcal{H}\)-matrix M is not expected to be symmetric, Hermite symmetric or lower triangular;
when the \(\mathcal{H}\)-matrix M is required to be symmetric, Hermite symmetric or lower triangular a priori, and the product matrix Z should not be symmetric, Hermite symmetric or lower triangular.
Assemble the local matrix Z to the product matrix M.
When the original matrix M0 belongs to the near field, assemble the full matrix stored in Z directly into M.
When the original matrix M0 does not belong to the near field, assemble the rank-k matrix stored in Z into M by first embedding then formatted addition, which has been implemented in the member function assemble_from_rkmatrix.
Definition at line 12592 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::get_block_type(), and HMatrix< spacedim, Number >::get_property().
Referenced by h_h_mmult_level_conserving().
h_h_mmult_from_leaf_node_for_parallel_lu()
template<int spacedim, typename Number > void h_h_mmult_from_leaf_node_for_parallel_lu (HMatrix< spacedim, Number > & M0, HMatrix< spacedim, Number > & M, const Number alpha, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
Here we make an assertion that the top level result \(\mathcal{H}\)-matrix M0 should be a leaf node.
Create a block cluster node \(\tau\times\rho\) for the current local product matrix Z. Since this block cluster node will not be connected with other block cluster nodes in a block cluster tree, it has neither parent nor children and its level is set to zero.
Set the is_near_field flag of the block cluster node for the current local product matrix Z according to the matrix type of the initial leaf node \(\mathcal{H}\)-matrix M0, i.e. it inherits the is_near_field flag of the block cluster node for M0.
When the flag is_result_matrix_store_tril_only is true, determine if the \(\mathcal{H}\)-matrix property of the local product \(\mathcal{H}\)-matrix Z should be the same as that of M by checking if the index ranges of its \(\tau\) node and \(\sigma\) are the same, since only when they are the same, Z or M's property can be symmetric or lower triangular.
The local product \(\mathcal{H}\)-matrix Z inherits the property of M, which can be either symmetric or lower triangular.
If the local \(\mathcal{H}\)-matrix Z is symmetric or lower triangular, its block type should be diagonal_block and an assertion is made about this fact.
Create the local product \(\mathcal{H}\)-matrix Z associated with the current block cluster node. During its initialization, memory will be allocated depending on its \(\mathcal{H}\)-matrix property and block type.
When either operand M1 or M2 is a leaf node, directly evaluation of their multiplication can be performed.
If the local product \(\mathcal{H}\)-matrix Z is expected to be symmetric or lower triangular, also set the property of the associated full matrix correspondingly. This operation is mandatory because the property of the local full matrix ZF is general, which has overwritten the property of Z.
In this case, both M1 and M2 have child submatrices.
When we perform submatrix multiplication, we use a higher specified rank, since the results will be assembled into the larger matrix Z via pairwise formatted addition, during which the actual matrix rank may increase.
The virtual submatrix block Z.submatrices[1], which is obtained from the cross type multiplication of M1 and M2, will be evaluated in two scenarios:
when the result matrix is not expected to be symmetric, Hermite symmetric or lower triangular;
when the result matrix is required to be symmetric, Hermite symmetric or lower triangular a priori, then if the product matrix Z is not symmetric, Hermite symmetric or lower triangular.
Here the "virtual" above means even though Z is actually not further divided and have no submatrices, the cross type multiplication will generate submatrix blocks virtually.
Assemble the local matrix Z to the product matrix M.
When the original matrix M0 belongs to the near field, assemble the full matrix stored in Z directly into M.
Only when the result matrix M is the top level result matrix M0, the mutex will be locked. Otherwise, the result matrix M is only a temporary object, which needs not be locked.
When the original matrix M0 does not belong to the near field, assemble the rank-k matrix stored in Z into M by first embedding then formatted addition, which has been implemented in the member function assemble_from_rkmatrix.
Only when the result matrix M is the top level result matrix M0, the mutex will be locked. Otherwise, the result matrix M is only a temporary object, which needs not be locked.
Definition at line 13410 of file hmatrix.h.
h_h_mmult_level_conserving() [1/2]
template<int spacedim, typename Number > void h_h_mmult_level_conserving (HMatrix< spacedim, Number > & M, const Number alpha, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
Multiplication of two level-conserving \(\mathcal{H}\)-matrices with a factor multiplied to the matrix product and the result will be added to the target matrix M, i.e. \(M = M + \alpha \cdot M_1 M_2\).
Note
It is required that an empty result matrix M should be created first with respect to a block cluster tree.
Parameters
M0
M
alpha
M1
M2
fixed_rank
All matrices (including the two operands and the product result) have substructure. Hence the \(\mathcal{H}\)-matrix multiplication type is cross.
N.B. When the \(\mathcal{H}\)-matrix is symmetric or lower triangular, it stores the lower triangular data only (including diagonal elements).
The submatrix block M.submatrices[1] will be evaluated in two scenarios:
when the result matrix is not expected to be symmetric, Hermite symmetric or lower triangular;
when the result matrix is required to be symmetric, Hermite symmetric or lower triangular a priori, then if the product matrix M is not symmetric, Hermite symmetric or lower triangular.
This is the case when the product matrix M is further divided, while at least one of the two operands is a leaf. Hence the multiplication on this level can be directly evaluated.
When one of the operand matrix is a rank-k matrix, the product result is also a rank-k matrix.
When one of the operand matrix is a full matrix, the immediate product result is for sure a full matrix. However, because the block cluster associated with M is not a leaf, M should be represented as a rank-k matrix, which is converted from the full matrix. In the current implementation, this conversion has no accuracy loss.
Add the result matrix Z into M and note that Z and M are associated with a same block cluster.
This addition is implemented by restricting Z to each leaf node of M first, then the addition operation will be performed on each leaf node respectively.
The matrix Z should only be added into M but not simply overwrite M. This is because the result matrix M on the block cluster \(\tau\times\rho\) may be contributed from several multiplications with respect to a collection of \({\sigma_i}\), which forms a partition of the index set \(J\).
This is the first time of calling h_h_mmult_from_leaf_node, where the second argument M is the product of M1 and M2. If there are further recursive calls of this function, the second argument will be one level higher than the product of M1 and M2.
Definition at line 16210 of file hmatrix.h.
h_h_mmult_level_conserving() [2/2]
template<int spacedim, typename Number > void h_h_mmult_level_conserving (HMatrix< spacedim, Number > & M, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
Multiplication of two level-conserving \(\mathcal{H}\)-matrices and the result will be added to the target matrix M, i.e. \(M = M + M_1 M_2\).
Note
It is required that an empty result matrix M should be created first with respect to a block cluster tree.
Parameters
M
M1
M2
fixed_rank
is_result_matrix_store_tril_only
All matrices (including the two operands and the product result) have substructure. Hence the \(\mathcal{H}\)-matrix multiplication type is cross.
N.B. When the \(\mathcal{H}\)-matrix is symmetric, Hermite symmetric or lower triangular, it stores the lower triangular data only (including diagonal elements).
The submatrix block M.submatrices[1] will be evaluated in two scenarios:
when the result matrix is not expected to be symmetric, Hermite symmetric or lower triangular;
when the result matrix is required to be symmetric, Hermite symmetric or lower triangular a priori, then if the product matrix M is not symmetric, Hermite symmetric or lower triangular.
This is the case when the product matrix M is further divided, while at least one of the two operands is a leaf. Hence the multiplication on this level can be directly evaluated.
When one of the operand matrix is a rank-k matrix, the product result is also a rank-k matrix.
When one of the operand matrix is a full matrix, the immediate product result is for sure a full matrix. However, because the block cluster associated with M is not a leaf, M should be represented as a rank-k matrix, which is converted from the full matrix. In the current implementation, this conversion has no accuracy loss.
Add the result matrix Z into M and note that Z and M are associated with a same block cluster.
This addition is implemented by restricting Z to each leaf node of M first, then the addition operation will be performed on each leaf node respectively.
The matrix Z should only be added into M but not simply overwrite M. This is because the result matrix M on the block cluster \(\tau\times\rho\) may be contributed from several multiplications with respect to a collection of \({\sigma_i}\), which forms a partition of the index set \(J\).
This is the first time of calling h_h_mmult_from_leaf_node, where the second argument M is the product of M1 and M2. If there are further recursive calls of this function, the second argument will be one level higher than the product of M1 and M2.
Definition at line 16039 of file hmatrix.h.
References HMatrix< spacedim, Number >::add(), HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::block_type, f_h_mmult(), HMatrix< spacedim, Number >::fullmatrix, FullMatrixType, h_f_mmult(), h_h_mmult_from_leaf_node(), h_h_mmult_level_conserving(), h_rk_mmult(), HMatrix< spacedim, Number >::property, rk_h_mmult(), HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::submatrices, and HMatrix< spacedim, Number >::type.
Referenced by h_h_mmult_level_conserving(), and HMatrix< spacedim, Number >::mmult_level_conserving().
h_h_mmult_level_conserving_for_parallel_lu()
template<int spacedim, typename Number > void h_h_mmult_level_conserving_for_parallel_lu (HMatrix< spacedim, Number > & M, const Number alpha, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
All matrices (including the two operands and the product result) have substructure. Hence the \(\mathcal{H}\)-matrix multiplication type is cross.
N.B. When the \(\mathcal{H}\)-matrix is symmetric or lower triangular, it stores the lower triangular data only (including diagonal elements).
The submatrix block M.submatrices[1] will be evaluated in two scenarios:
when the result matrix is not expected to be symmetric, Hermite symmetric or lower triangular;
when the result matrix is required to be symmetric, Hermite symmetric or lower triangular a priori, then if the product matrix M is not symmetric, Hermite symmetric or lower triangular.
This is the case when the product matrix M is further divided, while at least one of the two operands is a leaf. Hence the multiplication on this level can be directly evaluated.
When one of the operand matrix is a rank-k matrix, the product result is also a rank-k matrix.
When one of the operand matrix is a full matrix, the immediate product result is for sure a full matrix. However, because the block cluster associated with M is not a leaf, M should be represented as a rank-k matrix, which is converted from the full matrix. In the current implementation, this conversion has no accuracy loss.
Add the result matrix Z into M and note that Z and M are associated with a same block cluster.
This addition is implemented by restricting Z to each leaf node of M first, then the addition operation will be performed on each leaf node respectively.
The matrix Z should only be added into M but not simply overwrite M. This is because the result matrix M on the block cluster \(\tau\times\rho\) may be contributed from several multiplications with respect to a collection of \({\sigma_i}\), which forms a partition of the index set \(J\).
This is the first time of calling h_h_mmult_from_leaf_node, where the second argument M is the product of M1 and M2. If there are further recursive calls of this function, the second argument will be one level higher than the product of M1 and M2.
Definition at line 16373 of file hmatrix.h.
h_h_mmult_phase1_recursion()
template<int spacedim, typename Number = double> void h_h_mmult_phase1_recursion (HMatrix< spacedim, Number > * M, BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type > & Tind)
There are still multiplication subtasks stored in Sigma_P to be handled recursively.
After previous reduction and splitting, the matrix multiplication for the current \(\mathcal{H}\)-matrix node should be replaced by the multiplication subtasks for submatrices. These subtasks are recorded as \(\mathcal{H}\)-matrix node pairs which are stored in \(\Sigma_b^P\) of the submatrices.
Definition at line 12403 of file hmatrix.h.
References HMatrix< spacedim, Number >::determine_mm_split_mode_from_Sigma_P(), HMatrix< spacedim, Number >::h_h_mmult_reduction(), and HMatrix< spacedim, Number >::Sigma_P.
Referenced by HMatrix< spacedim, Number >::mmult().
h_h_mmult_phase2()
template<int spacedim, typename Number = double> void h_h_mmult_phase2 (HMatrix< spacedim, Number > & M, BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type > & target_bc_tree, const unsigned int fixed_rank)
Collect terms in Sigma_R and Sigma_F for the leaf nodes.
Here we make sure that \(\mathcal{H}\)-matrix pairs in the list \(\Sigma_b^P\) have all been processed and erased, hence the list should be empty.
Perform pairwise formatted addition for the list of rank-k matrices stored in the list \(\Sigma_b^R\), the result of which will be assigned to the rkmatrix field of the current \(\mathcal{H}\)-matrix leaf node.
Clear the list \(\Sigma_b^R\) after adding all of its rank-k matrices.
Clear the list \(\Sigma_b^F\) after adding all of its full matrices.
Important: Distribute matrices stored in \(\Sigma_b^R\) and \(\Sigma_b^F\) of each non-leaf node to the leaf nodes which are its descendants.
Convert the calculated product matrix to the specified matrix structure.
Definition at line 12474 of file hmatrix.h.
References HMatrix< spacedim, Number >::convert_between_different_block_cluster_trees(), HMatrix< spacedim, Number >::distribute_all_non_leaf_nodes_sigma_r_and_f_to_leaves(), HMatrix< spacedim, Number >::fullmatrix, FullMatrixType, HMatrix< spacedim, Number >::leaf_set, HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::Sigma_F, HMatrix< spacedim, Number >::Sigma_P, HMatrix< spacedim, Number >::Sigma_R, HMatrix< spacedim, Number >::Tind, and HMatrix< spacedim, Number >::type.
Referenced by HMatrix< spacedim, Number >::mmult().
h_h_mTmult_from_leaf_node() [1/2]
template<int spacedim, typename Number > void h_h_mTmult_from_leaf_node (HMatrix< spacedim, Number > & M0, HMatrix< spacedim, Number > & M, const Number alpha, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
\(\mathcal{H}\)-matrix- \(\mathcal{H}\)-matrix multiplication with the second operand transposed, when the product matrix belongs to the leaf set of the target block cluster tree.
This function implements the recursive MMR algorithm in (7.26) in Hackbusch's \(\mathcal{H}\)-matrix book.
Parameters
M0 The initial product matrix on the block cluster node \(\tau_0\times\rho_0\).
M The current product matrix \(M\) on the block cluster node \(\tau\times\rho\), which will assembles the contribution from \(M_1 \cdot M_2^T\) (N.B. This description is only valid for the first call of this function. During recursive calls of this function, M may not be on a same level as the product of M1 and M2, when both M1 and M2 have substructures and the multiplication needs to collect results from the multiplications of submatrices). For the first call of this function, M is the same as M0.
alpha
M1 The first operand of the multiplication, which is built upon the block cluster node \(\tau\times\sigma\).
M2 The second operand of the multiplication, which is built upon the block cluster node \(\rho\times\sigma\).
block_type_for_local_Z Block type for the local \(\mathcal{H}\)-matrix Z, which is the product of M1 and M2.
fixed_rank
is_result_matrix_store_tril_only Flag indicating whether only the lower triangular part and the diagonal part of the \(\mathcal{H}\)-matrix M are stored. The naming of this variable follows the convention adopted by GNU Octave, where a lower triangular matrix has nonzero entries only on the main diagonal and below. See tril and istril function in GNU Octave.
Here we make an assertion that the top level result \(\mathcal{H}\)-matrix M0 should be a leaf node.
Create a block cluster node \(\tau\times\rho\) for the current local product matrix Z. Since this block cluster node will not be connected with other block cluster nodes in a block cluster tree, it has neither parent nor children and its level is set to zero.
Because the current multiplication is \(M_1\cdot M_2^T\), the product \bctnode is built from \(\tau\) of \(M_1\) and \(\tau\) of \(M_2\).
Set the is_near_field flag of the block cluster node for the current local product matrix Z according to the matrix type of the initial leaf node \(\mathcal{H}\)-matrix M0, i.e. it inherits the is_near_field flag of the block cluster node for M0.
When the flag is_result_matrix_store_tril_only is true, determine if the \(\mathcal{H}\)-matrix property of the local product \(\mathcal{H}\)-matrix Z should be the same as that of M by checking if the index ranges of its \(\tau\) node and \(\sigma\) are the same, since only when they are the same, Z or M's property can be symmetric or lower triangular.
The local product \(\mathcal{H}\)-matrix Z inherits the property of M, which can be either symmetric or lower triangular.
If the local \(\mathcal{H}\)-matrix Z is symmetric or lower triangular, its block type should be diagonal_block and an assertion is made about this fact.
Create the local product \(\mathcal{H}\)-matrix Z associated with the current block cluster node. During its initialization, memory will be allocated depending on its \(\mathcal{H}\)-matrix property and block type.
When either operand M1 or M2 is a leaf node, directly evaluation of their multiplication can be performed.
If the local product \(\mathcal{H}\)-matrix Z is expected to be symmetric or lower triangular, also set the property of the associated full matrix correspondingly. This operation is mandatory because the property of the local full matrix ZF is general, which has overwritten the property of Z.
In this case, both M1 and M2 have child submatrices.
When we perform submatrix multiplication, we use a higher specified rank, since the results will be assembled into the larger matrix Z via pairwise formatted addition, during which the actual matrix rank may increase.
The submatrix block Z.submatrices[1], which is obtained from the cross type multiplication of M1 and M2, will be evaluated in two scenarios:
when the \(\mathcal{H}\)-matrix M is not expected to be symmetric, Hermite symmetric or lower triangular;
when the \(\mathcal{H}\)-matrix M is required to be symmetric, Hermite symmetric or lower triangular a priori, and the product matrix Z should not be symmetric, Hermite symmetric or lower triangular.
Assemble the product \(\mathcal{H}\)-matrix Z to the \(\mathcal{H}\)-matrix M.
When the original matrix M0 belongs to the near field, assemble the full matrix stored in Z directly into M.
When the original matrix M0 does not belong to the near field, assemble the rank-k matrix stored in Z into M by first embedding then formatted addition, which has been implemented in the member function assemble_from_rkmatrix.
Definition at line 14334 of file hmatrix.h.
h_h_mTmult_from_leaf_node() [2/2]
template<int spacedim, typename Number > void h_h_mTmult_from_leaf_node (HMatrix< spacedim, Number > & M0, HMatrix< spacedim, Number > & M, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
\(\mathcal{H}\)-matrix- \(\mathcal{H}\)-matrix multiplication with the second operand transposed, when the product matrix belongs to the leaf set of the target block cluster tree.
This function implements the recursive MMR algorithm in (7.26) in Hackbusch's \(\mathcal{H}\)-matrix book.
Parameters
M0 The initial product matrix on the block cluster node \(\tau_0\times\rho_0\).
M The current product matrix \(M\) on the block cluster node \(\tau\times\rho\), which will assembles the contribution from \(M_1 \cdot M_2^T\) (N.B. This description is only valid for the first call of this function. During recursive calls of this function, M may not be on a same level as the product of M1 and M2, when both M1 and M2 have substructures and the multiplication needs to collect results from the multiplications of submatrices). For the first call of this function, M is the same as M0.
M1 The first operand of the multiplication, which is built upon the block cluster node \(\tau\times\sigma\).
M2 The second operand of the multiplication, which is built upon the block cluster node \(\rho\times\sigma\).
block_type_for_local_Z Block type for the local \(\mathcal{H}\)-matrix Z, which is the product of M1 and M2.
fixed_rank
is_result_matrix_store_tril_only Flag indicating whether only the lower triangular part and the diagonal part of the \(\mathcal{H}\)-matrix M are stored. The naming of this variable follows the convention adopted by GNU Octave, where a lower triangular matrix has nonzero entries only on the main diagonal and below. See tril and istril function in GNU Octave.
Here we make an assertion that the top level result \(\mathcal{H}\)-matrix M0 should be a leaf node.
Create a block cluster node \(\tau\times\rho\) for the current local product matrix Z. Since this block cluster node will not be connected with other block cluster nodes in a block cluster tree, it has neither parent nor children and its level is set to zero.
Because the current multiplication is \(M_1\cdot M_2^T\), the product \bctnode is built from \(\tau\) of \(M_1\) and \(\tau\) of \(M_2\).
Set the is_near_field flag of the block cluster node for the current local product matrix Z according to the matrix type of the initial leaf node \(\mathcal{H}\)-matrix M0, i.e. it inherits the is_near_field flag of the block cluster node for M0.
When the flag is_result_matrix_store_tril_only is true, determine if the \(\mathcal{H}\)-matrix property of the local product \(\mathcal{H}\)-matrix Z should be the same as that of M by checking if the index ranges of its \(\tau\) node and \(\sigma\) are the same, since only when they are the same, Z or M's property can be symmetric, Hermite symmetric or lower triangular.
The local product \(\mathcal{H}\)-matrix Z inherits the property of M, which can be either symmetric or lower triangular.
If the local \(\mathcal{H}\)-matrix Z is symmetric or lower triangular, its block type should be diagonal_block and an assertion is made about this fact.
Create the local product \(\mathcal{H}\)-matrix Z associated with the current block cluster node. During its initialization, memory will be allocated depending on its \(\mathcal{H}\)-matrix property and block type.
When either operand M1 or M2 is a leaf node, directly evaluation of their multiplication can be performed.
If the local product \(\mathcal{H}\)-matrix Z is expected to be symmetric or lower triangular, also set the property of the associated full matrix correspondingly. This operation is mandatory because the property of the local full matrix ZF is general, which has overwritten the property of Z.
In this case, both M1 and M2 have child submatrices.
When we perform submatrix multiplication, we use a higher specified rank, since the results will be assembled into the larger matrix Z via pairwise formatted addition, during which the actual matrix rank may increase.
The submatrix block Z.submatrices[1], which is obtained from the cross type multiplication of M1 and M2, will be evaluated in two scenarios:
when the \(\mathcal{H}\)-matrix M is not expected to be symmetric, Hermite symmetric or lower triangular;
when the \(\mathcal{H}\)-matrix M is required to be symmetric, Hermite symmetric or lower triangular a priori, and the product matrix Z should not be symmetric, Hermite symmetric or lower triangular.
Assemble the local matrix Z to the product matrix M.
When the original matrix M0 belongs to the near field, assemble the full matrix stored in Z directly into M.
When the original matrix M0 does not belong to the near field, assemble the rank-k matrix stored in Z into M by first embedding then formatted addition, which has been implemented in the member function assemble_from_rkmatrix.
Definition at line 13910 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::get_block_type(), and HMatrix< spacedim, Number >::get_property().
Referenced by h_h_mTmult_level_conserving().
h_h_mTmult_from_leaf_node_for_parallel_cholesky()
template<int spacedim, typename Number > void h_h_mTmult_from_leaf_node_for_parallel_cholesky (HMatrix< spacedim, Number > & M0, HMatrix< spacedim, Number > & M, const Number alpha, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
Here we make an assertion that the top level result \(\mathcal{H}\)-matrix M0 should be a leaf node.
Create a block cluster node \(\tau\times\rho\) for the current local product matrix Z. Since this block cluster node will not be connected with other block cluster nodes in a block cluster tree, it has neither parent nor children and its level is set to zero.
Because the current multiplication is \(M_1\cdot M_2^T\), the product \bctnode is built from \(\tau\) of \(M_1\) and \(\tau\) of \(M_2\).
Set the is_near_field flag of the block cluster node for the current local product matrix Z according to the matrix type of the initial leaf node \(\mathcal{H}\)-matrix M0, i.e. it inherits the is_near_field flag of the block cluster node for M0.
When the flag is_result_matrix_store_tril_only is true, determine if the \(\mathcal{H}\)-matrix property of the local product \(\mathcal{H}\)-matrix Z should be the same as that of M by checking if the index ranges of its \(\tau\) node and \(\sigma\) are the same, since only when they are the same, Z or M's property can be symmetric or lower triangular.
The local product \(\mathcal{H}\)-matrix Z inherits the property of M, which can be either symmetric or lower triangular.
If the local \(\mathcal{H}\)-matrix Z is symmetric or lower triangular, its block type should be diagonal_block and an assertion is made about this fact.
Create the local product \(\mathcal{H}\)-matrix Z associated with the current block cluster node. During its initialization, memory will be allocated depending on its \(\mathcal{H}\)-matrix property and block type.
When either operand M1 or M2 is a leaf node, directly evaluation of their multiplication can be performed.
If the local product \(\mathcal{H}\)-matrix Z is expected to be symmetric or lower triangular, also set the property of the associated full matrix correspondingly. This operation is mandatory because the property of the local full matrix ZF is general, which has overwritten the property of Z.
In this case, both M1 and M2 have child submatrices.
When we perform submatrix multiplication, we use a higher specified rank, since the results will be assembled into the larger matrix Z via pairwise formatted addition, during which the actual matrix rank may increase.
The submatrix block Z.submatrices[1], which is obtained from the cross type multiplication of M1 and M2, will be evaluated in two scenarios:
when the \(\mathcal{H}\)-matrix M is not expected to be symmetric, Hermite symmetric, or lower triangular;
when the \(\mathcal{H}\)-matrix M is required to be symmetric, Hermite symmetric or lower triangular a priori, and the product matrix Z should not be symmetric, Hermite symmetric or lower triangular.
Assemble the product \(\mathcal{H}\)-matrix Z to the \(\mathcal{H}\)-matrix M.
When the original matrix M0 belongs to the near field, assemble the full matrix stored in Z directly into M.
Only when the result matrix M is the top level result matrix M0, the mutex will be locked. Otherwise, the result matrix M is only a temporary object, which needs not be locked.
When the original matrix M0 does not belong to the near field, assemble the rank-k matrix stored in Z into M by first embedding then formatted addition, which has been implemented in the member function assemble_from_rkmatrix.
Only when the result matrix M is the top level result matrix M0, the mutex will be locked. Otherwise, the result matrix M is only a temporary object, which needs not be locked.
Definition at line 14735 of file hmatrix.h.
h_h_mTmult_level_conserving() [1/2]
template<int spacedim, typename Number > void h_h_mTmult_level_conserving (HMatrix< spacedim, Number > & M, const Number alpha, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
Multiplication of two level-conserving \(\mathcal{H}\)-matrices with the second operand transposed. The result will multiplied by a factor and then added to the target matrix M, i.e. \(M = M + \alpha \cdot M_1 M_2^T\).
Note
It is required that an empty result matrix M should be created first with respect to a block cluster tree.
Parameters
M
alpha
M1
M2
fixed_rank
is_result_matrix_store_tril_only
All matrices (including the two operands and the product result) have substructure. Hence the \(\mathcal{H}\)-matrix multiplication type is cross.
N.B. When the \(\mathcal{H}\)-matrix is symmetric or lower triangular, it stores the lower triangular data only (including diagonal elements).
The submatrix block M.submatrices[1] will be evaluated in two scenarios:
when the result matrix is not expected to be symmetric, Hermite symmetric or lower triangular;
when the result matrix is required to be symmetric, Hermite symmetric or lower triangular a priori, then if the product matrix M is not symmetric, Hermite symmetric or lower triangular.
This is the case when the product matrix M is further divided, while some of the two operands is a leaf. Hence the multiplication on this level can be directly evaluated.
When one of the operand matrix is a rank-k matrix, the product result is also a rank-k matrix.
When one of the operand matrix is a full matrix, the immediate product result is for sure a full matrix. However, because the block cluster associated with M is not a leaf, M should be represented as a rank-k matrix, which is converted from the full matrix. In the current implementation, this conversion has no accuracy loss.
Add the result matrix Z into M and note that Z and M are associated with a same block cluster.
This addition is implemented by restricting Z to each leaf node of M first, then the addition operation will be performed on each leaf node respectively.
The matrix Z should only be added into M but not simply overwrite M. This is because the result matrix M on the block cluster \(\tau\times\rho\) may be contributed from several multiplications with respect to a collection of \({\sigma_i}\), which forms a partition of the index set \(J\).
This is the first time of calling h_h_mTmult_from_leaf_node, where the second argument M is the product of M1 and M2. If there are further recursive calls of this function, the second argument will be one level higher than the product of M1 and M2.
Definition at line 16725 of file hmatrix.h.
h_h_mTmult_level_conserving() [2/2]
template<int spacedim, typename Number > void h_h_mTmult_level_conserving (HMatrix< spacedim, Number > & M, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
Multiplication of two level-conserving \(\mathcal{H}\)-matrices with the second operand transposed. The result will be added to the target matrix M, i.e. \(M = M + M_1 M_2^T\).
Note
It is required that an empty result matrix M should be created first with respect to a block cluster tree.
Parameters
M
M1
M2
fixed_rank
is_result_matrix_store_tril_only
All matrices (including the two operands and the product result) have substructure. Hence the \(\mathcal{H}\)-matrix multiplication type is cross.
N.B. When the \(\mathcal{H}\)-matrix is symmetric or lower triangular, it stores the lower triangular data only (including diagonal elements).
The submatrix block M.submatrices[1] will be evaluated in two scenarios:
when the result matrix is not expected to be symmetric, Hermite symmetric or lower triangular;
when the result matrix is required to be symmetric, Hermite symmetric or lower triangular a priori, then if the product matrix M is not symmetric, Hermite symmetric or lower triangular.
This is the case when the product matrix M is further divided, while some of the two operands is a leaf. Hence the multiplication on this level can be directly evaluated.
When one of the operand matrix is a rank-k matrix, the product result is also a rank-k matrix.
When one of the operand matrix is a full matrix, the immediate product result is for sure a full matrix. However, because the block cluster associated with M is not a leaf, M should be represented as a rank-k matrix, which is converted from the full matrix. In the current implementation, this conversion has no accuracy loss.
Add the result matrix Z into M and note that Z and M are associated with a same block cluster.
This addition is implemented by restricting Z to each leaf node of M first, then the addition operation will be performed on each leaf node respectively.
The matrix Z should only be added into M but not simply overwrite M. This is because the result matrix M on the block cluster \(\tau\times\rho\) may be contributed from several multiplications with respect to a collection of \({\sigma_i}\), which forms a partition of the index set \(J\).
This is the first time of calling h_h_mTmult_from_leaf_node, where the second argument M is the product of M1 and M2. If there are further recursive calls of this function, the second argument will be one level higher than the product of M1 and M2.
Definition at line 16558 of file hmatrix.h.
References HMatrix< spacedim, Number >::add(), HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::block_type, f_h_mTmult(), HMatrix< spacedim, Number >::fullmatrix, FullMatrixType, h_f_mTmult(), h_h_mTmult_from_leaf_node(), h_h_mTmult_level_conserving(), h_rk_mTmult(), HMatrix< spacedim, Number >::property, rk_h_mTmult(), HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::submatrices, and HMatrix< spacedim, Number >::type.
Referenced by h_h_mTmult_level_conserving(), and HMatrix< spacedim, Number >::mTmult_level_conserving().
h_h_mTmult_level_conserving_for_parallel_cholesky()
template<int spacedim, typename Number > void h_h_mTmult_level_conserving_for_parallel_cholesky (HMatrix< spacedim, Number > & M, const Number alpha, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
All matrices (including the two operands and the product result) have substructure. Hence the \(\mathcal{H}\)-matrix multiplication type is cross.
N.B. When the \(\mathcal{H}\)-matrix is symmetric or lower triangular, it stores the lower triangular data only (including diagonal elements).
The submatrix block M.submatrices[1] will be evaluated in two scenarios:
when the result matrix is not expected to be symmetric, Hermite symmetric or lower triangular;
when the result matrix is required to be symmetric, Hermite symmetric or lower triangular a priori, then if the product matrix M is not symmetric, Hermite symmetric or lower triangular.
This is the case when the product matrix M is further divided, while some of the two operands is a leaf. Hence the multiplication on this level can be directly evaluated.
When one of the operand matrix is a rank-k matrix, the product result is also a rank-k matrix.
When one of the operand matrix is a full matrix, the immediate product result is for sure a full matrix. However, because the block cluster associated with M is not a leaf, M should be represented as a rank-k matrix, which is converted from the full matrix. In the current implementation, this conversion has no accuracy loss.
Add the result matrix Z into M and note that Z and M are associated with a same block cluster.
This addition is implemented by restricting Z to each leaf node of M first, then the addition operation will be performed on each leaf node respectively.
The matrix Z should only be added into M but not simply overwrite M. This is because the result matrix M on the block cluster \(\tau\times\rho\) may be contributed from several multiplications with respect to a collection of \({\sigma_i}\), which forms a partition of the index set \(J\).
This is the first time of calling h_h_mTmult_from_leaf_node, where the second argument M is the product of M1 and M2. If there are further recursive calls of this function, the second argument will be one level higher than the product of M1 and M2.
Definition at line 16887 of file hmatrix.h.
h_h_Tmmult_from_leaf_node() [1/2]
template<int spacedim, typename Number > void h_h_Tmmult_from_leaf_node (HMatrix< spacedim, Number > & M0, HMatrix< spacedim, Number > & M, const Number alpha, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
Scaled \(\mathcal{H}\)-matrix- \(\mathcal{H}\)-matrix multiplication with the first operand transposed, when the product matrix belongs to the leaf set of the target block cluster tree.
This function implements the recursive MMR algorithm in (7.26) in Hackbusch's \(\mathcal{H}\)-matrix book.
Parameters
M0
M
alpha
M1
M2
block_type_for_local_Z
fixed_rank
is_result_matrix_store_tril_only
Here we make an assertion that the top level result \(\mathcal{H}\)-matrix M0 should be a leaf node.
Create a block cluster node \(\tau\times\rho\) for the current local product matrix Z. Since this block cluster node will not be connected with other block cluster nodes in a block cluster tree, it has neither parent nor children and its level is set to zero.
Because the current multiplication is \(M_1^T\cdot M_2\), the product \bctnode is built from \(\sigma\) of \(M_1\) and \(\sigma\) of \(M_2\).
Set the is_near_field flag of the block cluster node for the current local product matrix Z according to the matrix type of the initial leaf node \(\mathcal{H}\)-matrix M0, i.e. it inherits the is_near_field flag of the block cluster node for M0.
When the flag is_result_matrix_store_tril_only is true, determine if the \(\mathcal{H}\)-matrix property of the local product \(\mathcal{H}\)-matrix Z should be the same as that of M by checking if the index ranges of its \(\tau\) node and \(\sigma\) are the same, since only when they are the same, Z or M's property can be symmetric or lower triangular.
The local product \(\mathcal{H}\)-matrix Z inherits the property of M, which can be either symmetric or lower triangular.
If the local \(\mathcal{H}\)-matrix Z is symmetric or lower triangular, its block type should be diagonal_block and an assertion is made about this fact.
Create the local product \(\mathcal{H}\)-matrix Z associated with the current block cluster node. During its initialization, memory will be allocated depending on its \(\mathcal{H}\)-matrix property and block type.
When either operand M1 or M2 is a leaf node, directly evaluation of their multiplication can be performed.
If the local product \(\mathcal{H}\)-matrix Z is expected to be symmetric or lower triangular, also set the property of the associated full matrix correspondingly. This operation is mandatory because the property of the local full matrix ZF is general, which has overwritten the property of Z.
In this case, both M1 and M2 have child submatrices.
When we perform submatrix multiplication, we use a higher specified rank, since the results will be assembled into the larger matrix Z via pairwise formatted addition, during which the actual matrix rank may increase.
The submatrix block Z.submatrices[1], which is obtained from the cross type multiplication of M1 and M2, will be evaluated in two scenarios:
when the \(\mathcal{H}\)-matrix M is not expected to be symmetric, Hermite symmetric or lower triangular;
when the \(\mathcal{H}\)-matrix M is required to be symmetric, Hermite symmetric or lower triangular a priori, and the product matrix Z should not be symmetric, Hermite symmetric or lower triangular.
Assemble the local matrix Z to the product matrix M.
When the original matrix M0 belongs to the near field, assemble the full matrix stored in Z directly into M.
When the original matrix M0 does not belong to the near field, assemble the rank-k matrix stored in Z into M by first embedding then formatted addition, which has been implemented in the member function assemble_from_rkmatrix.
Definition at line 15626 of file hmatrix.h.
h_h_Tmmult_from_leaf_node() [2/2]
template<int spacedim, typename Number > void h_h_Tmmult_from_leaf_node (HMatrix< spacedim, Number > & M0, HMatrix< spacedim, Number > & M, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const HMatrixSupport::BlockType block_type_for_local_Z, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
\(\mathcal{H}\)-matrix- \(\mathcal{H}\)-matrix multiplication with the first operand transposed, when the product matrix belongs to the leaf set of the target block cluster tree.
This function implements the recursive MMR algorithm in (7.26) in Hackbusch's \(\mathcal{H}\)-matrix book.
Parameters
M0
M
M1
M2
block_type_for_local_Z
fixed_rank
is_result_matrix_store_tril_only
Here we make an assertion that the top level result \(\mathcal{H}\)-matrix M0 should be a leaf node.
Create a block cluster node \(\tau\times\rho\) for the current local product matrix Z. Since this block cluster node will not be connected with other block cluster nodes in a block cluster tree, it has neither parent nor children and its level is set to zero.
Because the current multiplication is \(M_1^T\cdot M_2\), the product \bctnode is built from \(\sigma\) of \(M_1\) and \(\sigma\) of \(M_2\).
Set the is_near_field flag of the block cluster node for the current local product matrix Z according to the matrix type of the initial leaf node \(\mathcal{H}\)-matrix M0, i.e. it inherits the is_near_field flag of the block cluster node for M0.
When the flag is_result_matrix_store_tril_only is true, determine if the \(\mathcal{H}\)-matrix property of the local product \(\mathcal{H}\)-matrix Z should be the same as that of M by checking if the index ranges of its \(\tau\) node and \(\sigma\) are the same, since only when they are the same, Z or M's property can be symmetric or lower triangular.
The local product \(\mathcal{H}\)-matrix Z inherits the property of M, which can be either symmetric or lower triangular.
If the local \(\mathcal{H}\)-matrix Z is symmetric or lower triangular, its block type should be diagonal_block and an assertion is made about this fact.
Create the local product \(\mathcal{H}\)-matrix Z associated with the current block cluster node. During its initialization, memory will be allocated depending on its \(\mathcal{H}\)-matrix property and block type.
When either operand M1 or M2 is a leaf node, directly evaluation of their multiplication can be performed.
If the local product \(\mathcal{H}\)-matrix Z is expected to be symmetric or lower triangular, also set the property of the associated full matrix correspondingly. This operation is mandatory because the property of the local full matrix ZF is general, which has overwritten the property of Z.
In this case, both M1 and M2 have child submatrices.
When we perform submatrix multiplication, we use a higher specified rank, since the results will be assembled into the larger matrix Z via pairwise formatted addition, during which the actual matrix rank may increase.
The submatrix block Z.submatrices[1], which is obtained from the cross type multiplication of M1 and M2, will be evaluated in two scenarios:
when the \(\mathcal{H}\)-matrix M is not expected to be symmetric, Hermite symmetric or lower triangular;
when the \(\mathcal{H}\)-matrix M is required to be symmetric, Hermite symmetric or lower triangular a priori, and the product matrix Z should not be symmetric, Hermite symmetric or lower triangular.
Assemble the local matrix Z to the product matrix M.
When the original matrix M0 belongs to the near field, assemble the full matrix stored in Z directly into M.
When the original matrix M0 does not belong to the near field, assemble the rank-k matrix stored in Z into M by first embedding then formatted addition, which has been implemented in the member function assemble_from_rkmatrix.
Definition at line 15219 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::get_block_type(), and HMatrix< spacedim, Number >::get_property().
Referenced by h_h_Tmmult_level_conserving().
h_h_Tmmult_level_conserving() [1/2]
template<int spacedim, typename Number > void h_h_Tmmult_level_conserving (HMatrix< spacedim, Number > & M, const Number alpha, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
Scaled multiplication of two level-conserving \(\mathcal{H}\)-matrices with the first operand transposed. The result will be added to the target matrix M, i.e. \(M = M + \alpha M_1^T M_2\).
Note
It is required that an empty result matrix M should be created first with respect to a block cluster tree.
Parameters
M
alpha
M1
M2
fixed_rank
is_result_matrix_store_tril_only
All matrices (including the two operands and the product result) have substructure. Hence the \(\mathcal{H}\)-matrix multiplication type is cross.
N.B. When the \(\mathcal{H}\)-matrix is symmetric or lower triangular, it stores the lower triangular data only (including diagonal elements).
The submatrix block M.submatrices[1] will be evaluated in two scenarios:
when the result matrix is not expected to be symmetric, Hermite symmetric or lower triangular;
when the result matrix is required to be symmetric, Hermite symmetric or lower triangular a priori, then if the product matrix M is not symmetric, Hermite symmetric or lower triangular.
This is the case when the product matrix M is further divided, while at least one of the two operands is a leaf. Hence the multiplication on this level can be directly evaluated.
When one of the operand matrix is a rank-k matrix, the product result is also a rank-k matrix.
When one of the operand matrix is a full matrix, the immediate product result is for sure a full matrix. However, because the block cluster associated with M is not a leaf, M should be represented as a rank-k matrix, which is converted from the full matrix. In the current implementation, this conversion has no accuracy loss.
Add the result matrix Z into M and note that Z and M are associated with a same block cluster.
This addition is implemented by restricting Z to each leaf node of M first, then the addition operation will be performed on each leaf node respectively.
The matrix Z should only be added into M but not simply overwrite M. This is because the result matrix M on the block cluster \(\tau\times\rho\) may be contributed from several multiplications with respect to a collection of \({\sigma_i}\), which forms a partition of the index set \(J\).
This is the first time of calling h_h_mmult_from_leaf_node, where the second argument M is the product of M1 and M2. If there are further recursive calls of this function, the second argument will be one level higher than the product of M1 and M2.
Definition at line 17241 of file hmatrix.h.
h_h_Tmmult_level_conserving() [2/2]
template<int spacedim, typename Number > void h_h_Tmmult_level_conserving (HMatrix< spacedim, Number > & M, HMatrix< spacedim, Number > & M1, HMatrix< spacedim, Number > & M2, const unsigned int fixed_rank, const bool is_result_matrix_store_tril_only = false)
Multiplication of two level-conserving \(\mathcal{H}\)-matrices with the first operand transposed. The result will be added to the target matrix M, i.e. \(M = M + M_1^T M_2\).
Note
It is required that an empty result matrix M should be created first with respect to a block cluster tree.
Parameters
M
M1
M2
fixed_rank
is_result_matrix_store_tril_only
All matrices (including the two operands and the product result) have substructure. Hence the \(\mathcal{H}\)-matrix multiplication type is cross.
N.B. When the \(\mathcal{H}\)-matrix is symmetric or lower triangular, it stores the lower triangular data only (including diagonal elements).
The submatrix block M.submatrices[1] will be evaluated in two scenarios:
when the result matrix is not expected to be symmetric, Hermite symmetric or lower triangular;
when the result matrix is required to be symmetric, Hermite symmetric or lower triangular a priori, then if the product matrix M is not symmetric, Hermite symmetric or lower triangular.
This is the case when the product matrix M is further divided, while at least one of the two operands is a leaf. Hence the multiplication on this level can be directly evaluated.
When one of the operand matrix is a rank-k matrix, the product result is also a rank-k matrix.
When one of the operand matrix is a full matrix, the immediate product result is for sure a full matrix. However, because the block cluster associated with M is not a leaf, M should be represented as a rank-k matrix, which is converted from the full matrix. In the current implementation, this conversion has no accuracy loss.
Add the result matrix Z into M and note that Z and M are associated with a same block cluster.
This addition is implemented by restricting Z to each leaf node of M first, then the addition operation will be performed on each leaf node respectively.
The matrix Z should only be added into M but not simply overwrite M. This is because the result matrix M on the block cluster \(\tau\times\rho\) may be contributed from several multiplications with respect to a collection of \({\sigma_i}\), which forms a partition of the index set \(J\).
This is the first time of calling h_h_mmult_from_leaf_node, where the second argument M is the product of M1 and M2. If there are further recursive calls of this function, the second argument will be one level higher than the product of M1 and M2.
Definition at line 17073 of file hmatrix.h.
References HMatrix< spacedim, Number >::add(), HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::block_type, f_h_Tmmult(), HMatrix< spacedim, Number >::fullmatrix, FullMatrixType, h_f_Tmmult(), h_h_Tmmult_from_leaf_node(), h_h_Tmmult_level_conserving(), h_rk_Tmmult(), HMatrix< spacedim, Number >::property, rk_h_Tmmult(), HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::submatrices, and HMatrix< spacedim, Number >::type.
Referenced by h_h_Tmmult_level_conserving(), and HMatrix< spacedim, Number >::Tmmult_level_conserving().
h_rk_mmult() [1/2]
template<int spacedim, typename Number = double> void h_rk_mmult (const Number alpha, HMatrix< spacedim, Number > & M1, const RkMatrix< Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes and the result is scaled by a factor, where the second one M2 has RkMatrixType and the result will also be a rank-k matrix.
The arithmetic operation to be performed is
\[ M = \alpha \cdot M_1 \cdot M_2 = \alpha \cdot M_1 (A B^T) = \alpha \cdot (M_1 A) B^T = \alpha \cdot A' B^T, \]
where \(A' = M_1 A\) is calculated as a series of \(\mathcal{H}\)-matrix/vector multiplications. For details,
\[ M_1 A = M_1 \begin{bmatrix} a_{\sigma,1} & \cdots & a_{\sigma,r} \end{bmatrix} = \begin{bmatrix} M_1 a_{\sigma,1} & \cdots & M_1 a_{\sigma,r} \end{bmatrix} = \begin{bmatrix} a'_{\tau,1} & \cdots & a'_{\tau,r} \end{bmatrix}. \]
It can be seen that the formal rank \(r\) of the result matrix M is the same as that of M2.
Parameters
alpha
M1
M2
M
Create a temporary Vector storing a column \(a_{\sigma,j}\) in the A component of M2 and another Vector \(a'_{\tau,j}\) storing the \(\mathcal{H}\)-matrix/vector product \(M_1 \cdot a_{\sigma,j}\).
Initialize the result rank-k matrix M with the formal rank of M2. Its B component matrix is the same as that of M2.
Then we calculate the A component matrix of M, which is M1*M2.A.
Since the following vmult will compute \(y = y + M x\), result_vect should be reset to zero beforehand.
Fill the result vector into the A component matrix of M.
Definition at line 10518 of file hmatrix.h.
h_rk_mmult() [2/2]
template<int spacedim, typename Number = double> void h_rk_mmult (HMatrix< spacedim, Number > & M1, const RkMatrix< Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes, where the second one M2 has RkMatrixType and the result will also be a rank-k matrix.
The arithmetic operation to be performed is
\[ M = M_1 \cdot M_2 = M_1 (A B^T) = (M_1 A) B^T = A' B^T, \]
where \(A' = M_1 A\) is calculated as a series of \(\mathcal{H}\)-matrix/vector multiplications. For details,
\[ M_1 A = M_1 \begin{bmatrix} a_{\sigma,1} & \cdots & a_{\sigma,r} \end{bmatrix} = \begin{bmatrix} M_1 a_{\sigma,1} & \cdots & M_1 a_{\sigma,r} \end{bmatrix} = \begin{bmatrix} a'_{\tau,1} & \cdots & a'_{\tau,r} \end{bmatrix}. \]
It can be seen that the formal rank \(r\) of the result matrix M is the same as that of M2.
Parameters
M1
M2
M
Create a temporary Vector storing a column \(a_{\sigma,j}\) in the A component of M2 and another Vector \(a'_{\tau,j}\) storing the \(\mathcal{H}\)-matrix/vector product \(M_1 \cdot a_{\sigma,j}\).
Initialize the result rank-k matrix M with the formal rank of M2. Its B component matrix is the same as that of M2.
Then we calculate the A component matrix of M, which is M1*M2.A.
Fill the result vector into the A component matrix of M.
Definition at line 10444 of file hmatrix.h.
References RkMatrix< Number >::formal_rank, HMatrix< spacedim, Number >::get_property(), HMatrix< spacedim, Number >::m, RkMatrix< Number >::m, HMatrix< spacedim, Number >::n, RkMatrix< Number >::n, RkMatrix< Number >::rank, RkMatrix< Number >::reinit(), and HMatrix< spacedim, Number >::vmult().
Referenced by h_f_mmult(), h_h_mmult_level_conserving(), and h_rk_mmult_for_h_h_mmult().
h_rk_mmult_for_h_h_mmult()
template<int spacedim, typename Number = double> void h_rk_mmult_for_h_h_mmult (HMatrix< spacedim, Number > * M1, const HMatrix< spacedim, Number > * M2, HMatrix< spacedim, Number > * M, bool is_M1M2_last_in_M_Sigma_P = true)
Calculate the product of two \(\mathcal{H}\)-matrix nodes, where the second one M2 has RkMatrixType and the result will also be a rank-k matrix. This function is to be called by the matrix-matrix multiplication function.
Parameters
M1
M2
M
Definition at line 10890 of file hmatrix.h.
References h_rk_mmult(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::remove_hmat_pair_from_mm_product_list(), HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::Sigma_F, HMatrix< spacedim, Number >::Sigma_P, HMatrix< spacedim, Number >::Sigma_R, and HMatrix< spacedim, Number >::type.
Referenced by HMatrix< spacedim, Number >::h_h_mmult_reduction().
h_rk_mTmult() [1/2]
template<int spacedim, typename Number = double> void h_rk_mTmult (const Number alpha, HMatrix< spacedim, Number > & M1, const RkMatrix< Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the second operand being transposed, where the second operand M2 has RkMatrixType and the result will also be a rank-k matrix. The result will be scaled by a factor.
The arithmetic operation to be performed is
\[ M = \alpha \cdot M_1 \cdot M_2^T = \alpha \cdot M_1 (A B^T)^T = \alpha \cdot (M_1 B) A^T = \alpha \cdot A' B'^T, \]
where \(A' = M_1 B\) is calculated as a series of \(\mathcal{H}\)-matrix/vector multiplications, and \(B' = A\). For details,
\[ M_1 B = M_1 \begin{bmatrix} b_{\sigma,1} & \cdots & b_{\sigma,r} \end{bmatrix} = \begin{bmatrix} M_1 b_{\sigma,1} & \cdots & M_1 b_{\sigma,r} \end{bmatrix} = \begin{bmatrix} b'_{\tau,1} & \cdots & b'_{\tau,r} \end{bmatrix}. \]
It can be seen that the formal rank \(r\) of the result matrix M is the same as that of M2.
Parameters
alpha
M1
M2
M
Create a temporary Vector storing a column \(b_{\sigma,j}\) in the B component of M2 and another Vector \(b'_{\tau,j}\) storing the \(\mathcal{H}\)-matrix/vector product \(M_1 \cdot b_{\sigma,j}\).
Initialize the result rank-k matrix M with the formal rank of M2. Its B component matrix is the same as that of M2.
Then we calculate the A component matrix of M, which is M1*M2.B.
Fill the result vector into the A component matrix of M.
Definition at line 10672 of file hmatrix.h.
h_rk_mTmult() [2/2]
template<int spacedim, typename Number = double> void h_rk_mTmult (HMatrix< spacedim, Number > & M1, const RkMatrix< Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the second operand being transposed, where the second operand M2 has RkMatrixType and the result will also be a rank-k matrix.
The arithmetic operation to be performed is
\[ M = M_1 \cdot M_2^T = M_1 (A B^T)^T = (M_1 B) A^T = A' B'^T, \]
where \(A' = M_1 B\) is calculated as a series of \(\mathcal{H}\)-matrix/vector multiplications, and \(B' = A\). For details,
\[ M_1 B = M_1 \begin{bmatrix} b_{\sigma,1} & \cdots & b_{\sigma,r} \end{bmatrix} = \begin{bmatrix} M_1 b_{\sigma,1} & \cdots & M_1 b_{\sigma,r} \end{bmatrix} = \begin{bmatrix} b'_{\tau,1} & \cdots & b'_{\tau,r} \end{bmatrix}. \]
It can be seen that the formal rank \(r\) of the result matrix M is the same as that of M2.
Parameters
M1
M2
M
Create a temporary Vector storing a column \(b_{\sigma,j}\) in the B component of M2 and another Vector \(b'_{\tau,j}\) storing the \(\mathcal{H}\)-matrix/vector product \(M_1 \cdot b_{\sigma,j}\).
Initialize the result rank-k matrix M with the formal rank of M2. Its B component matrix is the same as that of M2.
Then we calculate the A component matrix of M, which is M1*M2.B.
Fill the result vector into the A component matrix of M.
Definition at line 10601 of file hmatrix.h.
References RkMatrix< Number >::formal_rank, HMatrix< spacedim, Number >::get_property(), HMatrix< spacedim, Number >::m, RkMatrix< Number >::m, HMatrix< spacedim, Number >::n, RkMatrix< Number >::n, RkMatrix< Number >::rank, RkMatrix< Number >::reinit(), and HMatrix< spacedim, Number >::vmult().
Referenced by h_f_mTmult(), and h_h_mTmult_level_conserving().
h_rk_Tmmult() [1/2]
template<int spacedim, typename Number = double> void h_rk_Tmmult (const Number alpha, HMatrix< spacedim, Number > & M1, const RkMatrix< Number > & M2, RkMatrix< Number > & M)
Calculate the scaled product of two \(\mathcal{H}\)-matrix nodes with the first operand being transposed, where the second one M2 has RkMatrixType and the result will also be a rank-k matrix.
The arithmetic operation to be performed is
\[ M = \alpha M_1^T \cdot M_2 = \alpha M_1^T (A B^T) = \alpha (M_1^T A) B^T = \alpha A' B^T, \]
where \(A' = M_1^T A\) is calculated as a series of transposed- \(\mathcal{H}\)-matrix/vector multiplications. For details,
\[ M_1^T A = M_1^T \begin{bmatrix} a_{\sigma,1} & \cdots & a_{\sigma,r} \end{bmatrix} = \begin{bmatrix} M_1^T a_{\sigma,1} & \cdots & M_1^T a_{\sigma,r} \end{bmatrix} = \begin{bmatrix} a'_{\tau,1} & \cdots & a'_{\tau,r} \end{bmatrix}. \]
It can be seen that the formal rank \(r\) of the result matrix M is the same as that of M2.
Parameters
alpha
M1
M2
M
Create a temporary Vector storing a column \(a_{\sigma,j}\) in the A component of M2 and another Vector \(a'_{\tau,j}\) storing the transposed- \(\mathcal{H}\)-matrix/vector product \(M_1^T \cdot a_{\sigma,j}\).
Initialize the result rank-k matrix M with the formal rank of M2. Its B component matrix is the same as that of M2.
Then we calculate the A component matrix of M, which is M1^T*M2.A.
Fill the result vector into the A component matrix of M.
Definition at line 10832 of file hmatrix.h.
h_rk_Tmmult() [2/2]
template<int spacedim, typename Number = double> void h_rk_Tmmult (HMatrix< spacedim, Number > & M1, const RkMatrix< Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the first operand being transposed, where the second one M2 has RkMatrixType and the result will also be a rank-k matrix.
The arithmetic operation to be performed is
\[ M = M_1^T \cdot M_2 = M_1^T (A B^T) = (M_1^T A) B^T = A' B^T, \]
where \(A' = M_1^T A\) is calculated as a series of transposed- \(\mathcal{H}\)-matrix/vector multiplications. For details,
\[ M_1^T A = M_1^T \begin{bmatrix} a_{\sigma,1} & \cdots & a_{\sigma,r} \end{bmatrix} = \begin{bmatrix} M_1^T a_{\sigma,1} & \cdots & M_1^T a_{\sigma,r} \end{bmatrix} = \begin{bmatrix} a'_{\tau,1} & \cdots & a'_{\tau,r} \end{bmatrix}. \]
It can be seen that the formal rank \(r\) of the result matrix M is the same as that of M2.
Parameters
M1
M2
M
Create a temporary Vector storing a column \(a_{\sigma,j}\) in the A component of M2 and another Vector \(a'_{\tau,j}\) storing the transposed- \(\mathcal{H}\)-matrix/vector product \(M_1^T \cdot a_{\sigma,j}\).
Initialize the result rank-k matrix M with the formal rank of M2. Its B component matrix is the same as that of M2.
Then we calculate the A component matrix of M, which is M1^T*M2.A.
Fill the result vector into the A component matrix of M.
Definition at line 10751 of file hmatrix.h.
References RkMatrix< Number >::formal_rank, HMatrix< spacedim, Number >::get_property(), HMatrix< spacedim, Number >::m, RkMatrix< Number >::m, HMatrix< spacedim, Number >::n, RkMatrix< Number >::n, RkMatrix< Number >::rank, RkMatrix< Number >::reinit(), and HMatrix< spacedim, Number >::Tvmult().
Referenced by h_f_Tmmult(), and h_h_Tmmult_level_conserving().
hmatrix_solve_cholesky()
template<int spacedim, typename Number > void hmatrix_solve_cholesky (const HMatrix< spacedim, Number > & L, Vector< Number > & x, const Vector< Number > & b)
Definition at line 17589 of file hmatrix.h.
hmatrix_solve_lu()
template<int spacedim, typename Number > void hmatrix_solve_lu (const HMatrix< spacedim, Number > & L, const HMatrix< spacedim, Number > & U, Vector< Number > & x, const Vector< Number > & b)
Definition at line 17576 of file hmatrix.h.
InitAndCreateHMatrixChildren() [1/6]
template<int spacedim, typename Number = double> void InitAndCreateHMatrixChildren (HMatrix< spacedim, Number > * hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const LAPACKFullMatrixExt< Number > & M, const HMatrixSupport::Property top_hmat_node_property = HMatrixSupport::Property::general)
Recursively construct the children of an \(\mathcal{H}\)-matrix with respect to a block cluster tree by starting from a tree node which is associated with the current \(\mathcal{H}\)-matrix. There is no rank truncation to the rank-k matrices.
The matrices in the leaf set are initialized with the data in the given global full matrix M, which is created on the complete block cluster index set \(I \times J\) and whose elements should be accessed via indices stored in the block cluster.
During the recursive calling of this function, the source data matrix M is kept intact, which will not be restricted to small matrix blocks.
Note
The full matrix M is global, while hmat may not be global, but only a block in the global matrix, and bc_node in this case is not the root node of the block cluster tree.
Parameters
hmat Pointer to the current \(\mathcal{H}\)-matrix node, which has already been created on the heap but with its internal data left empty.
bc_node Pointer to a TreeNode in a BlockClusterTree, which is to be associated with hmat. It is not necessarily the root node.
M The global full matrix containing all the data required to initialize the \(\mathcal{H}\)-matrix.
Link hmat with bc_node.
Link row and column indices.
Update the matrix dimension of hmat.
When the block cluster node bc_node has children, set the current hmat type as HierarchicalMatrixType. Then we will continue constructing hierarchical submatrices.
Create an empty HMatrix on the heap.
Set the state of the child \(\mathcal{H}\)-matrix, which is the same as its parent.
Set the block type of the child \(\mathcal{H}\)-matrix, which depends on the block type of its parent.
When the current \(\mathcal{H}\)-matrix block is undefined_block, all child \(\mathcal{H}\)-matrices are undefined_block.
When the current \(\mathcal{H}\)-matrix is diagonal_block, the first and fourth child \(\mathcal{H}\)-matrices are diagonal_block, while the second child \(\mathcal{H}\)-matrix is upper_triangular_block and the third child \(\mathcal{H}\)-matrix is lower_triangular_block.
When the current \(\mathcal{H}\)-matrix is upper_triangular_block, all child \(\mathcal{H}\)-matrices are upper_triangular_block.
When the current \(\mathcal{H}\)-matrix is lower_triangular_block, all child \(\mathcal{H}\)-matrices are lower_triangular_block.
Set the property of the child \(\mathcal{H}\)-matrix, which depends on the property of its parent.
When the property of the current \(\mathcal{H}\)-matrix is general, all of its children have the same property general.
When the property of the current \(\mathcal{H}\)-matrix is symmetric, only those diagonal submatrices are symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is hermite_symmetric, only those diagonal submatrices are hermite_symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is upper_triangular, only those diagonal submatrices are upper_triangular, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is lower_triangular, only those diagonal submatrices are lower_triangular, while the other submatrices are general.
Append the initialized child to the list of submatrices of hmat.
Set the pointer to the parent \(\mathcal{H}\)-matrix node of the current child \(\mathcal{H}\)-matrix node.
Update the current matrix type according to the identity of the block cluster node. When the block cluster belongs to the near field, hmat should be represented as a LAPACKFullMatrixExt. When the block cluster belongs to the far field, hmat should be represented as an RkMatrix. Correspondingly, new matrices, either full matrix or rank-k matrix will be created on the heap and assigned to the current \(\mathcal{H}\)-matrix.
When the top level \(\mathcal{H}\)-matrix node has the general property, all \(\mathcal{H}\)-matrix nodes in the leaf set should be created with allocated memory.
Assign matrix values from M to the current HMatrix.
When the top level \(\mathcal{H}\)-matrix node has the symmetric property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part of the original \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a symmetric full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to symmetric.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is symmetric to the corresponding block in the lower triangular part.
When the top level \(\mathcal{H}\)-matrix node has the hermite_symmetric property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part of the original \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be an Hermite symmetric full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to hermite_symmetric.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is symmetric to the corresponding block in the lower triangular part.
When the top level \(\mathcal{H}\)-matrix node has the lower_triangular property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part in the top level \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a lower triangular full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to lower_triangular.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is zero-valued.
When the top level \(\mathcal{H}\)-matrix node has the upper_triangular property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or upper triangular part in the top level \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a upper triangular full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to upper_triangular.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is zero-valued.
Definition at line 6601 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::block_type, HMatrix< spacedim, Number >::col_index_range, HMatrix< spacedim, Number >::fullmatrix, FullMatrixType, HierarchicalMatrixType, InitAndCreateHMatrixChildren(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::parent, HMatrix< spacedim, Number >::property, HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::row_index_range, HMatrix< spacedim, Number >::state, HMatrix< spacedim, Number >::submatrices, HMatrix< spacedim, Number >::submatrix_index, and HMatrix< spacedim, Number >::type.
InitAndCreateHMatrixChildren() [2/6]
template<int spacedim, typename Number = double> void InitAndCreateHMatrixChildren (HMatrix< spacedim, Number > * hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const LAPACKFullMatrixExt< Number > & M, const std::array< types::global_dof_index, 2 > & M_row_index_range, const std::array< types::global_dof_index, 2 > & M_col_index_range, const HMatrixSupport::Property top_hmat_node_property = HMatrixSupport::Property::general)
Recursively construct the children of an \(\mathcal{H}\)-matrix with respect to a block cluster tree by starting from a tree node which is associated with the current \(\mathcal{H}\)-matrix. There is no rank truncation to the rank-k matrices.
The matrices in the leaf set are initialized with the data in the given full matrix M, which is created on the block cluster index set \(\tau \times \sigma\) associated with the current \(\mathcal{H}\)-matrix. Hence, this full matrix is just a block of the original global full matrix created on the block cluster index set \(I \times J\).
During the recursive calling of this function, the source data matrix M is kept intact, which will not be restricted to small matrix blocks.
Link hmat with bc_node.
Link row and column indices.
Update the matrix dimension of hmat.
When the block cluster node bc_node has children, set the current hmat type as HierarchicalMatrixType. Then we will continue constructing hierarchical submatrices.
Create an empty HMatrix on the heap.
Set the state of the child \(\mathcal{H}\)-matrix, which is the same as its parent.
Set the block type of the child \(\mathcal{H}\)-matrix, which depends on the block type of its parent.
When the current \(\mathcal{H}\)-matrix block is undefined_block, all child \(\mathcal{H}\)-matrices are undefined_block.
When the current \(\mathcal{H}\)-matrix is diagonal_block, the first and fourth child \(\mathcal{H}\)-matrices are diagonal_block, while the second child \(\mathcal{H}\)-matrix is upper_triangular_block and the third child \(\mathcal{H}\)-matrix is lower_triangular_block.
When the current \(\mathcal{H}\)-matrix is upper_triangular_block, all child \(\mathcal{H}\)-matrices are upper_triangular_block.
When the current \(\mathcal{H}\)-matrix is lower_triangular_block, all child \(\mathcal{H}\)-matrices are lower_triangular_block.
Set the property of the child \(\mathcal{H}\)-matrix, which depends on the property of its parent.
When the property of the current \(\mathcal{H}\)-matrix is general, all of its children have the same property general.
When the property of the current \(\mathcal{H}\)-matrix is symmetric, only those diagonal submatrices are symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is hermite_symmetric, only those diagonal submatrices are hermite_symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is upper_triangular, only those diagonal submatrices are upper_triangular, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is lower_triangular, only those diagonal submatrices are lower_triangular, while the other submatrices are general.
Append the initialized child to the list of submatrices of hmat.
Set the pointer to the parent \(\mathcal{H}\)-matrix node of the current child \(\mathcal{H}\)-matrix node.
Update the current matrix type according to the identity of the block cluster node. When the block cluster belongs to the near field, hmat should be represented as a LAPACKFullMatrixExt. When the block cluster belongs to the far field, hmat should be represented as an RkMatrix. Correspondingly, new matrices, either full matrix or rank-k matrix will be created on the heap and assigned to the current \(\mathcal{H}\)-matrix.
When the top level \(\mathcal{H}\)-matrix node has the general property, all \(\mathcal{H}\)-matrix nodes in the leaf set should be created with allocated memory.
Assign matrix values from M to the current HMatrix.
When the top level \(\mathcal{H}\)-matrix node has the symmetric property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part of the original \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a symmetric full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to symmetric.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is symmetric to the corresponding block in the lower triangular part.
When the top level \(\mathcal{H}\)-matrix node has the hermite_symmetric property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part of the original \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be an Hermite symmetric full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to hermite_symmetric.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is symmetric to the corresponding block in the lower triangular part.
When the top level \(\mathcal{H}\)-matrix node has the lower_triangular property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part in the top level \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a lower triangular full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to lower_triangular.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is zero-valued.
When the top level \(\mathcal{H}\)-matrix node has the upper_triangular property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or upper triangular part in the top level \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a upper triangular full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to upper_triangular.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is zero-valued.
Definition at line 8318 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::block_type, HMatrix< spacedim, Number >::col_index_range, HMatrix< spacedim, Number >::fullmatrix, FullMatrixType, HierarchicalMatrixType, InitAndCreateHMatrixChildren(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::parent, HMatrix< spacedim, Number >::property, HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::row_index_range, HMatrix< spacedim, Number >::state, HMatrix< spacedim, Number >::submatrices, HMatrix< spacedim, Number >::submatrix_index, and HMatrix< spacedim, Number >::type.
InitAndCreateHMatrixChildren() [3/6]
template<int spacedim, typename Number = double> void InitAndCreateHMatrixChildren (HMatrix< spacedim, Number > * hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const unsigned int fixed_rank_k, const HMatrixSupport::Property top_hmat_node_property = HMatrixSupport::Property::general)
Recursively construct the children of an \(\mathcal{H}\)-matrix with respect to a block cluster tree by starting from a tree node which is associated with the current \(\mathcal{H}\)-matrix.
The matrices in the leaf set are initialized with zero values. The rank of the near field matrices are predefined fixed values.
Parameters
hmat Pointer to the current \(\mathcal{H}\)-matrix node, which has already been created on the heap but with its internal data left empty.
bc_node Pointer to a TreeNode in a BlockClusterTree, which is to be associated with hmat.
top_hmat_node_property The property of the \(\mathcal{H}\)-matrix node on the top level
Link hmat with bc_node.
Link row and column indices stored in the clusters \(\tau\) and \(\sigma\) respectively.
Update the matrix dimension of hmat.
When the block cluster node bc_node has children, set the current hmat type as HierarchicalMatrixType.
Then we will continue constructing its hierarchical submatrices.
Create an empty \(\mathcal{H}\)-matrix on the heap.
Set the state of the child \(\mathcal{H}\)-matrix, which is the same as its parent.
Set the block type of the child \(\mathcal{H}\)-matrix, which depends on the block type of its parent.
When the current \(\mathcal{H}\)-matrix block is undefined_block, all child \(\mathcal{H}\)-matrices are undefined_block.
When the current \(\mathcal{H}\)-matrix is diagonal_block, the first and fourth child \(\mathcal{H}\)-matrices are diagonal_block, while the second child \(\mathcal{H}\)-matrix is upper_triangular_block and the third child \(\mathcal{H}\)-matrix is lower_triangular_block.
When the current \(\mathcal{H}\)-matrix is upper_triangular_block, all child \(\mathcal{H}\)-matrices are upper_triangular_block.
When the current \(\mathcal{H}\)-matrix is lower_triangular_block, all child \(\mathcal{H}\)-matrices are lower_triangular_block.
Set the property of the child \(\mathcal{H}\)-matrix, which depends on the property of its parent.
When the property of the current \(\mathcal{H}\)-matrix is general, all of its children have the same property general.
When the property of the current \(\mathcal{H}\)-matrix is symmetric, only those diagonal submatrices are symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is hermite_symmetric, only those diagonal submatrices are hermite_symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is upper_triangular, only those diagonal submatrices are upper_triangular, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is lower_triangular, only those diagonal submatrices are lower_triangular, while the other submatrices are general.
Append the initialized child to the list of submatrices of hmat.
Set the pointer to the parent \(\mathcal{H}\)-matrix node of the current child \(\mathcal{H}\)-matrix node.
Update the current matrix type according to the identity of the block cluster node. When the block cluster belongs to the near field, hmat should be represented as a LAPACKFullMatrixExt. When the block cluster belongs to the far field, hmat should be represented as an RkMatrix. Correspondingly, new matrices, either full matrix or rank-k matrix will be created on the heap and assigned to the current \(\mathcal{H}\)-matrix.
When the top level \(\mathcal{H}\)-matrix node has the general property, all \(\mathcal{H}\)-matrix nodes in the leaf set should be created with allocated memory.
When the top level \(\mathcal{H}\)-matrix node has the symmetric property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part of the original \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a symmetric full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to symmetric.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is symmetric to the corresponding block in the lower triangular part.
When the top level \(\mathcal{H}\)-matrix node has the hermite_symmetric property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part of the original \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a Hermite symmetric full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to hermite_symmetric.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is Hermite symmetric to the corresponding block in the lower triangular part.
When the top level \(\mathcal{H}\)-matrix node has the lower_triangular property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part in the top level \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a lower triangular full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to lower_triangular.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is zero-valued.
When the top level \(\mathcal{H}\)-matrix node has the upper_triangular property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or upper triangular part in the top level \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a upper triangular full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to upper_triangular.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is zero-valued.
Definition at line 4976 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::block_type, HMatrix< spacedim, Number >::col_index_range, HMatrix< spacedim, Number >::fullmatrix, FullMatrixType, HierarchicalMatrixType, InitAndCreateHMatrixChildren(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::parent, HMatrix< spacedim, Number >::property, HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::row_index_range, HMatrix< spacedim, Number >::state, HMatrix< spacedim, Number >::submatrices, HMatrix< spacedim, Number >::submatrix_index, and HMatrix< spacedim, Number >::type.
Referenced by InitAndCreateHMatrixChildren(), and HMatrix< spacedim, Number >::reinit().
InitAndCreateHMatrixChildren() [4/6]
template<int spacedim, typename Number = double> void InitAndCreateHMatrixChildren (HMatrix< spacedim, Number > * hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const unsigned int fixed_rank_k, const LAPACKFullMatrixExt< Number > & M, const HMatrixSupport::Property top_hmat_node_property = HMatrixSupport::Property::general)
Recursively construct the children of an \(\mathcal{H}\)-matrix with respect to a block cluster tree by starting from a tree node which is associated with the current \(\mathcal{H}\)-matrix.
The matrices in the leaf set are initialized with the data in the given global full matrix M. M is created on the complete block cluster index set \(I \times J\) and whose elements should be accessed via indices stored in the block cluster. The rank of the far field matrices are predefined fixed values.
During the recursive calling of this function, the source data matrix M is kept intact, which will not be restricted to small matrix blocks.
Note
hmat may not be global, but only a block in the global matrix, and bc_node in this case is not the root node of the block cluster tree.
Parameters
hmat Pointer to the current \(\mathcal{H}\)-matrix node, which has already been created on the heap but with its internal data left empty.
bc_node Pointer to a TreeNode in a BlockClusterTree, which is to be associated with hmat.
M The global full matrix containing all the data required to initialize the \(\mathcal{H}\)-matrix.
Link hmat with bc_node.
Link row and column indices.
Update the matrix dimension of hmat.
When the block cluster node bc_node has children, set the current hmat type as HierarchicalMatrixType. Then we will continue constructing hierarchical submatrices.
Create an empty HMatrix on the heap.
Set the state of the child \(\mathcal{H}\)-matrix, which is the same as its parent.
Set the block type of the child \(\mathcal{H}\)-matrix, which depends on the block type of its parent.
When the current \(\mathcal{H}\)-matrix block is undefined_block, all child \(\mathcal{H}\)-matrices are undefined_block.
When the current \(\mathcal{H}\)-matrix is diagonal_block, the first and fourth child \(\mathcal{H}\)-matrices are diagonal_block, while the second child \(\mathcal{H}\)-matrix is upper_triangular_block and the third child \(\mathcal{H}\)-matrix is lower_triangular_block.
When the current \(\mathcal{H}\)-matrix is upper_triangular_block, all child \(\mathcal{H}\)-matrices are upper_triangular_block.
When the current \(\mathcal{H}\)-matrix is lower_triangular_block, all child \(\mathcal{H}\)-matrices are lower_triangular_block.
Set the property of the child \(\mathcal{H}\)-matrix, which depends on the property of its parent.
When the property of the current \(\mathcal{H}\)-matrix is general, all of its children have the same property general.
When the property of the current \(\mathcal{H}\)-matrix is symmetric, only those diagonal submatrices are symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is hermite_symmetric, only those diagonal submatrices are hermite_symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is upper_triangular, only those diagonal submatrices are upper_triangular, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is lower_triangular, only those diagonal submatrices are lower_triangular, while the other submatrices are general.
Append the initialized child to the list of submatrices of hmat.
Set the pointer to the parent \(\mathcal{H}\)-matrix node of the current child \(\mathcal{H}\)-matrix node.
Update the current matrix type according to the identity of the block cluster node. When the block cluster belongs to the near field, hmat should be represented as a LAPACKFullMatrixExt. When the block cluster belongs to the far field, hmat should be represented as an RkMatrix. Correspondingly, new matrices, either full matrix or rank-k matrix will be created on the heap and assigned to the current \(\mathcal{H}\)-matrix.
When the top level \(\mathcal{H}\)-matrix node has the general property, all \(\mathcal{H}\)-matrix nodes in the leaf set should be created with allocated memory.
Assign matrix values from M to the current \(\mathcal{H}\)-matrix.
When the top level \(\mathcal{H}\)-matrix node has the symmetric property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part of the original \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a symmetric full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to symmetric.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is symmetric to the corresponding block in the lower triangular part.
When the top level \(\mathcal{H}\)-matrix node has the hermite_symmetric property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part of the original \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be an Hermite symmetric full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to hermite_symmetric.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is Hermite symmetric to the corresponding block in the lower triangular part.
When the top level \(\mathcal{H}\)-matrix node has the lower_triangular property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part in the top level \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a lower triangular full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to lower_triangular.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is zero-valued.
When the top level \(\mathcal{H}\)-matrix node has the upper_triangular property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or upper triangular part in the top level \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a upper triangular full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to upper_triangular.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is zero-valued.
Definition at line 5726 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::block_type, HMatrix< spacedim, Number >::col_index_range, HMatrix< spacedim, Number >::fullmatrix, FullMatrixType, HierarchicalMatrixType, InitAndCreateHMatrixChildren(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::parent, HMatrix< spacedim, Number >::property, HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::row_index_range, HMatrix< spacedim, Number >::state, HMatrix< spacedim, Number >::submatrices, HMatrix< spacedim, Number >::submatrix_index, and HMatrix< spacedim, Number >::type.
InitAndCreateHMatrixChildren() [5/6]
template<int spacedim, typename Number = double> void InitAndCreateHMatrixChildren (HMatrix< spacedim, Number > * hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const unsigned int fixed_rank_k, const LAPACKFullMatrixExt< Number > & M, const std::array< types::global_dof_index, 2 > & M_row_index_range, const std::array< types::global_dof_index, 2 > & M_col_index_range, const HMatrixSupport::Property top_hmat_node_property = HMatrixSupport::Property::general)
Recursively construct the children of an \(\mathcal{H}\)-matrix with respect to a block cluster tree by starting from a tree node which is associated with the current \(\mathcal{H}\)-matrix.
The matrices in the leaf set are initialized with the data in the given full matrix M, which is created on the block cluster index set \(\tau \times \sigma\). N.B. This block cluster should be one of the ancestors of the block cluster associated with hmat that has been passed to the initial call of this function (let's call it hmat_first). Only in this way, it is valid to restrict this full matrix M to each leaf node of hmat. Hence, this full matrix is just a block of the original global full matrix (the global full matrix is created on the block cluster index set \(I \times J\)). The rank of the far field matrices are predefined fixed values.
During the recursive calling of this function, the source data matrix M is kept intact, which will not be restricted to small matrix blocks.
Parameters
hmat
bc_node
fixed_rank_k
M
M_tau_index_range
M_sigma_index_range
top_hmat_node_property
Update the matrix dimension of hmat.
When the block cluster node bc_node has children, set the current hmat type as HierarchicalMatrixType. Then we will continue constructing hierarchical submatrices.
Create an empty HMatrix on the heap.
Set the state of the child \(\mathcal{H}\)-matrix, which is the same as its parent.
Set the block type of the child \(\mathcal{H}\)-matrix, which depends on the block type of its parent.
When the current \(\mathcal{H}\)-matrix block is undefined_block, all child \(\mathcal{H}\)-matrices are undefined_block.
When the current \(\mathcal{H}\)-matrix is diagonal_block, the first and fourth child \(\mathcal{H}\)-matrices are diagonal_block, while the second child \(\mathcal{H}\)-matrix is upper_triangular_block and the third child \(\mathcal{H}\)-matrix is lower_triangular_block.
When the current \(\mathcal{H}\)-matrix is upper_triangular_block, all child \(\mathcal{H}\)-matrices are upper_triangular_block.
When the current \(\mathcal{H}\)-matrix is lower_triangular_block, all child \(\mathcal{H}\)-matrices are lower_triangular_block.
Set the property of the child \(\mathcal{H}\)-matrix, which depends on the property of its parent.
When the property of the current \(\mathcal{H}\)-matrix is general, all of its children have the same property general.
When the property of the current \(\mathcal{H}\)-matrix is symmetric, only those diagonal submatrices are symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is hermite_symmetric, only those diagonal submatrices are hermite_symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is upper_triangular, only those diagonal submatrices are upper_triangular, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is lower_triangular, only those diagonal submatrices are lower_triangular, while the other submatrices are general.
Append the initialized child to the list of submatrices of hmat.
Set the pointer to the parent \(\mathcal{H}\)-matrix node of the current child \(\mathcal{H}\)-matrix node.
Update the current matrix type according to the identity of the block cluster node. When the block cluster belongs to the near field, hmat should be represented as a LAPACKFullMatrixExt. When the block cluster belongs to the far field, hmat should be represented as an RkMatrix. Correspondingly, new matrices, either full matrix or rank-k matrix will be created on the heap and assigned to the current \(\mathcal{H}\)-matrix.
When the top level \(\mathcal{H}\)-matrix node has the general property, all \(\mathcal{H}\)-matrix nodes in the leaf set should be created with allocated memory.
Assign matrix values from M to the current HMatrix.
When the top level \(\mathcal{H}\)-matrix node has the symmetric property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part of the original \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a symmetric full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to symmetric.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is symmetric to the corresponding block in the lower triangular part.
When the top level \(\mathcal{H}\)-matrix node has the hermite_symmetric property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part of the original \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be an Hermite symmetric full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to hermite_symmetric.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is symmetric to the corresponding block in the lower triangular part.
When the top level \(\mathcal{H}\)-matrix node has the lower_triangular property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or lower triangular part in the top level \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a lower triangular full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to lower_triangular.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is zero-valued.
When the top level \(\mathcal{H}\)-matrix node has the upper_triangular property, only those \(\mathcal{H}\)-matrix nodes in the leaf set that belong to the diagonal or upper triangular part in the top level \(\mathcal{H}\)-matrix will be created with allocated memory.
When the current \(\mathcal{H}\)-matrix node in the leaf set is a diagonal block in the top level \(\mathcal{H}\)-matrix, it can only be a upper triangular full matrix. Its memory will be allocated and its LAPACKFullMatrix type will be set to upper_triangular.
Here we make an assertion about the fact that a diagonal \(\mathcal{H}\)-matrix block in the leaf set should belong to the near field.
And we further make an assertion about the fact that the diagonal \(\mathcal{H}\)-matrix block should have the same property as the top level \(\mathcal{H}\)-matrix node.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the upper triangular part in the top level \(\mathcal{H}\)-matrix, it can be either a full matrix or a rank-k matrix. Its memory will be allocated because it contains effective data.
Assign matrix values from M to the current HMatrix.
When the current \(\mathcal{H}\)-matrix node in the leaf set belongs to the lower triangular part in the top level \(\mathcal{H}\)-matrix, only set its \(\mathcal{H}\)-matrix type without allocating memory because it is zero-valued.
Definition at line 7459 of file hmatrix.h.
References HMatrix< spacedim, Number >::block_type, HMatrix< spacedim, Number >::col_index_range, HMatrix< spacedim, Number >::fullmatrix, FullMatrixType, HierarchicalMatrixType, InitAndCreateHMatrixChildren(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::parent, HMatrix< spacedim, Number >::property, HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::row_index_range, HMatrix< spacedim, Number >::state, HMatrix< spacedim, Number >::submatrices, HMatrix< spacedim, Number >::submatrix_index, and HMatrix< spacedim, Number >::type.
InitAndCreateHMatrixChildren() [6/6]
template<int spacedim, typename Number = double> void InitAndCreateHMatrixChildren (HMatrix< spacedim, Number > * hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, HMatrix< spacedim, Number > && H)
Recursively construct the children of an \(\mathcal{H}\)-matrix node with respect to a block cluster tree by starting from a tree node which is associated with the current \(\mathcal{H}\)-matrix node.
The matrices in the leaf set take the data migrated from the leaf set of the given \(\mathcal{H}\)-matrix H.
Parameters
hmat The \(\mathcal{H}\)-matrix node to be associated with the block cluster node bc_node.
bc_node The block cluster node to be associated with the \(\mathcal{H}\)-matrix node hmat
H
Link hmat with bc_node and remove the const feature bc_node by using const_cast.
Link row and column indices stored in the clusters \(\tau\) and \(\sigma\) respectively..
Update the matrix dimension of hmat.
When the block cluster node bc_node has children, set the current hmat type as HierarchicalMatrixType.
Then we will continue constructing its hierarchical submatrices.
Create an empty HMatrix on the heap.
Set the state of the child \(\mathcal{H}\)-matrix, which is the same as its parent.
Set the block type of the child \(\mathcal{H}\)-matrix, which depends on the block type of its parent.
When the current \(\mathcal{H}\)-matrix block is undefined_block, all child \(\mathcal{H}\)-matrices are undefined_block.
When the current \(\mathcal{H}\)-matrix is diagonal_block, the first and fourth child \(\mathcal{H}\)-matrices are diagonal_block, while the second child \(\mathcal{H}\)-matrix is upper_triangular_block and the third child \(\mathcal{H}\)-matrix is lower_triangular_block.
When the current \(\mathcal{H}\)-matrix is upper_triangular_block, all child \(\mathcal{H}\)-matrices are upper_triangular_block.
When the current \(\mathcal{H}\)-matrix is lower_triangular_block, all child \(\mathcal{H}\)-matrices are lower_triangular_block.
Set the property of the child \(\mathcal{H}\)-matrix, which depends on the property of its parent.
When the property of the current \(\mathcal{H}\)-matrix is general, all of its children have the same property general.
When the property of the current \(\mathcal{H}\)-matrix is symmetric, only those diagonal submatrices are symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is hermite_symmetric, only those diagonal submatrices are hermite_symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is upper_triangular, only those diagonal submatrices are upper_triangular, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is lower_triangular, only those diagonal submatrices are lower_triangular, while the other submatrices are general.
Append the initialized child to the list of submatrices of hmat.
Set the pointer to the parent \(\mathcal{H}\)-matrix node of the current child \(\mathcal{H}\)-matrix node.
When the current \(\mathcal{H}\)-matrix node is a leaf, migrate the data from the leaf set of H to it.
Shallow copy the found \(\mathcal{H}\)-matrix node in the leaf set to the current \(\mathcal{H}\)-matrix node.
Definition at line 9189 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::block_type, HMatrix< spacedim, Number >::col_index_range, HierarchicalMatrixType, InitAndCreateHMatrixChildren(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::parent, HMatrix< spacedim, Number >::property, HMatrix< spacedim, Number >::row_index_range, HMatrix< spacedim, Number >::state, HMatrix< spacedim, Number >::submatrices, HMatrix< spacedim, Number >::submatrix_index, and HMatrix< spacedim, Number >::type.
InitAndCreateHMatrixChildrenWithoutAlloc()
template<int spacedim, typename Number = double> void InitAndCreateHMatrixChildrenWithoutAlloc (HMatrix< spacedim, Number > * hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node)
Recursively construct the children of an \(\mathcal{H}\)-matrix with respect to a block cluster tree by starting from a tree node which is to be associated with the current \(\mathcal{H}\)-matrix.
Parameters
hmat Pointer to the current \(\mathcal{H}\)-matrix node, which has already been created on the heap but with its internal data left empty.
bc_node Pointer to a TreeNode in a BlockClusterTree, which is to be associated with hmat.
Link hmat with bc_node.
Link row and column indices stored in the clusters \(\tau\) and \(\sigma\) respectively.
Update the matrix dimension of hmat.
When the block cluster node bc_node has children, set the current hmat type as HierarchicalMatrixType.
Then we will continue constructing its hierarchical submatrices.
Create an empty HMatrix on the heap.
Set the state of the child \(\mathcal{H}\)-matrix, which is the same as its parent.
Set the block type of the child \(\mathcal{H}\)-matrix, which depends on the block type of its parent.
When the current \(\mathcal{H}\)-matrix block is undefined_block, all child \(\mathcal{H}\)-matrices are undefined_block.
When the current \(\mathcal{H}\)-matrix is diagonal_block, the first and fourth child \(\mathcal{H}\)-matrices are diagonal_block, while the second child \(\mathcal{H}\)-matrix is upper_triangular_block and the third child \(\mathcal{H}\)-matrix is lower_triangular_block.
When the current \(\mathcal{H}\)-matrix is upper_triangular_block, all child \(\mathcal{H}\)-matrices are upper_triangular_block.
When the current \(\mathcal{H}\)-matrix is lower_triangular_block, all child \(\mathcal{H}\)-matrices are lower_triangular_block.
Set the property of the child \(\mathcal{H}\)-matrix, which depends on the property of its parent.
When the property of the current \(\mathcal{H}\)-matrix is general, all of its children have the same property general.
When the property of the current \(\mathcal{H}\)-matrix is symmetric, only those diagonal submatrices are symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is hermite_symmetric, only those diagonal submatrices are hermite_symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is upper_triangular, only those diagonal submatrices are upper_triangular, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is lower_triangular, only those diagonal submatrices are lower_triangular, while the other submatrices are general.
Append the initialized child to the list of submatrices of hmat.
Set the pointer to the parent \(\mathcal{H}\)-matrix node of the current child \(\mathcal{H}\)-matrix node.
Update the current matrix type according to the identity of the block cluster node. When the block cluster belongs to the near field, hmat should be represented as a LAPACKFullMatrixExt. When the block cluster belongs to the far field, hmat should be represented as an RkMatrix. Correspondingly, new matrices, either full matrix or rank-k matrix will be created on the heap and assigned to the current \(\mathcal{H}\)-matrix.
Set the full matrix's property according to the current \(\mathcal{H}\)-matrix node property only when the current \(\mathcal{H}\)-matrix node is a diagonal block.
Note
The state of the full matrix will be taken care of by itself, i.e. its state will change accordingly when some specific operation is applied to it.
Definition at line 4621 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::block_type, HMatrix< spacedim, Number >::col_index_range, HMatrix< spacedim, Number >::fullmatrix, FullMatrixType, HierarchicalMatrixType, InitAndCreateHMatrixChildrenWithoutAlloc(), HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::parent, HMatrix< spacedim, Number >::property, HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::row_index_range, HMatrix< spacedim, Number >::state, HMatrix< spacedim, Number >::submatrices, HMatrix< spacedim, Number >::submatrix_index, and HMatrix< spacedim, Number >::type.
Referenced by InitAndCreateHMatrixChildrenWithoutAlloc().
InitHMatrixWrtBlockClusterNode() [1/3]
template<int spacedim, typename Number = double> void InitHMatrixWrtBlockClusterNode (HMatrix< spacedim, Number > & hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node)
Initialize an \(\mathcal{H}\)-matrix node with respect to a block cluster node. The list \(\Sigma_b^P\) is set to empty.
Parameters
hmat
bc_node
Sigma_P
Link hmat with bc_node.
Link row and column indices stored in the clusters \(\tau\) and \(\sigma\) respectively.
Update the matrix dimension of hmat.
Definition at line 4455 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::col_index_range, HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::row_index_range, HMatrix< spacedim, Number >::Sigma_F, HMatrix< spacedim, Number >::Sigma_P, and HMatrix< spacedim, Number >::Sigma_R.
Referenced by HMatrix< spacedim, Number >::mmult().
InitHMatrixWrtBlockClusterNode() [2/3]
template<int spacedim, typename Number = double> void InitHMatrixWrtBlockClusterNode (HMatrix< spacedim, Number > & hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const std::pair< HMatrix< spacedim, Number > *, HMatrix< spacedim, Number > * > & hmat_pair)
Initialize an \(\mathcal{H}\)-matrix node with respect to a block cluster node. The given hmat_pair will be appended to the list \(\Sigma_b^P\).
Parameters
hmat
bc_node
hmat_pair
Link hmat with bc_node.
Link row and column indices stored in the clusters \(\tau\) and \(\sigma\) respectively.
Update the matrix dimension of hmat.
Definition at line 4566 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::col_index_range, HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::row_index_range, HMatrix< spacedim, Number >::Sigma_F, HMatrix< spacedim, Number >::Sigma_P, and HMatrix< spacedim, Number >::Sigma_R.
InitHMatrixWrtBlockClusterNode() [3/3]
template<int spacedim, typename Number = double> void InitHMatrixWrtBlockClusterNode (HMatrix< spacedim, Number > & hmat, typename BlockClusterTree< spacedim, typename numbers::NumberTraits< Number >::real_type >::node_const_pointer_type bc_node, const std::vector< std::pair< HMatrix< spacedim, Number > *, HMatrix< spacedim, Number > * > > & Sigma_P)
Initialize an \(\mathcal{H}\)-matrix node with respect to a block cluster node. Its member list \(\Sigma_b^P\) will be merged with the given Sigma_P.
Parameters
hmat
bc_node
Sigma_P
Link hmat with bc_node.
Link row and column indices stored in the clusters \(\tau\) and \(\sigma\) respectively.
Update the matrix dimension of hmat.
Definition at line 4507 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::col_index_range, HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::row_index_range, HMatrix< spacedim, Number >::Sigma_F, HMatrix< spacedim, Number >::Sigma_P, and HMatrix< spacedim, Number >::Sigma_R.
print_h_h_submatrix_mmult_accessor()
template<int spacedim, typename Number = double> void print_h_h_submatrix_mmult_accessor (std::ostream & out, const std::string & name1, const HMatrix< spacedim, Number > & M1, const std::string & name2, const HMatrix< spacedim, Number > & M2)
Definition at line 17562 of file hmatrix.h.
print_h_submatrix_accessor()
template<int spacedim, typename Number = double> void print_h_submatrix_accessor (std::ostream & out, const std::string & name, const HMatrix< spacedim, Number > & M)
Definition at line 17548 of file hmatrix.h.
RefineHMatrixWrtExtendedBlockClusterTree()
template<int spacedim, typename Number > void RefineHMatrixWrtExtendedBlockClusterTree (HMatrix< spacedim, Number > * starting_hmat, HMatrix< spacedim, Number > * current_hmat)
Refine an \(\mathcal{H}\)-matrix node with respect to its associated block cluster tree which has already been extended to be finer than the original tree. The \(\mathcal{H}\)-matrix node should be of either FullMatrixType or RkMatrixType, i.e. it belongs to the leaf set of the block cluster tree before extension.
Parameters
starting_hmat The pointer to the initial \(\mathcal{H}\)-matrix node from which this recursive function is called for the first time, i.e. the \(\mathcal{H}\)-matrix node from which the refinement begins.
current_hmat The pointer to the current \(\mathcal{H}\)-matrix node being handled during the recursion. For the first time of calling this function, current_hmat is the same as starting_hmat.
Work flow
Because the \(\mathcal{H}\)-matrix node from which the refinement begins belongs to the leaf set of the original block cluster tree, its \(\mathcal{H}\)-matrix type can only be FullMatrixType or RkMatrixType. Therefore, we make an assertion here.
Determine the total number of children of the current \(\mathcal{H}\)-matrix node by querying its associated block cluster node. We do it like this is because the block cluster tree has already been extended which contains a set of child node, while the hierarchy of H-matrices has still not been extended yet.
If the associated block cluster node of the current \(\mathcal{H}\)-matrix node has children, we firstly update the \(\mathcal{H}\)-matrix type for the current \(\mathcal{H}\)-matrix node as HierarchicalMatrix and this is only performed when the current \(\mathcal{H}\)-matrix node is not the starting \(\mathcal{H}\)-matrix node, because the original matrix type of the starting \(\mathcal{H}\)-matrix node will be used later during restriction operations to the current block cluster. When the whole recursive call of this function RefineHMatrixWrtExtendedBlockClusterTree is complete, the \(\mathcal{H}\)-matrix type of starting_hmat will be corrected if this \(\mathcal{H}\)-matrix node has literally been refined. And this operation should be performed in the caller function of RefineHMatrixWrtExtendedBlockClusterTree, such as HMatrix<spacedim, Number>::refine_to_supertree.
For each of the children, create an empty \(\mathcal{H}\)-matrix node on the heap and append it to the list of submatrices of the current \(\mathcal{H}\)-matrix.
Set the state of the child \(\mathcal{H}\)-matrix, which is the same as its parent.
Set the block type of the child \(\mathcal{H}\)-matrix, which depends on the block type of its parent.
When the current \(\mathcal{H}\)-matrix block is undefined_block, all child \(\mathcal{H}\)-matrices are undefined_block.
When the current \(\mathcal{H}\)-matrix is diagonal_block, the first and fourth child \(\mathcal{H}\)-matrices are diagonal_block, while the second child \(\mathcal{H}\)-matrix is upper_triangular_block and the third child \(\mathcal{H}\)-matrix is lower_triangular_block.
When the current \(\mathcal{H}\)-matrix is upper_triangular_block, all child \(\mathcal{H}\)-matrices are upper_triangular_block.
When the current \(\mathcal{H}\)-matrix is lower_triangular_block, all child \(\mathcal{H}\)-matrices are lower_triangular_block.
Set the property of the child \(\mathcal{H}\)-matrix, which depends on the property of its parent.
When the property of the current \(\mathcal{H}\)-matrix is general, all of its children have the same property general.
When the property of the current \(\mathcal{H}\)-matrix is symmetric, only those diagonal submatrices are symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is hermite_symmetric, only those diagonal submatrices are hermite_symmetric, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is upper_triangular, only those diagonal submatrices are upper_triangular, while the other submatrices are general.
When the property of the current \(\mathcal{H}\)-matrix is lower_triangular, only those diagonal submatrices are lower_triangular, while the other submatrices are general.
Link the child \(\mathcal{H}\)-matrix node with the corresponding block cluster node.
Link row and column indices of the child \(\mathcal{H}\)-matrix node to those index sets stored in clusters.
Update the matrix dimension of the child \(\mathcal{H}\)-matrix node.
Set the pointer to the parent \(\mathcal{H}\)-matrix node of the current child \(\mathcal{H}\)-matrix node.
Recursively call the function.
When the current \(\mathcal{H}\)-matrix node has no children, i.e. it belongs to the leaf set of the extended block cluster tree.
If the current \(\mathcal{H}\)-matrix node is still the same as the starting \(\mathcal{H}\)-matrix node, there is no actual refinement work to be done.
Update the current \(\mathcal{H}\)-matrix node type according to the identity of the block cluster node: when the block cluster belongs to the near field, current_hmat should be represented as a full matrix LAPACKFullMatrixExt; when the block cluster belongs to the far field, current_hmat should be represented as a rank-k matrix RkMatrix. Correspondingly, new matrices, either full matrix or rank-k matrix will be created on the heap and assigned to the corresponding field of the current \(\mathcal{H}\)-matrix.
Fill the current full matrix with the data extracted from the starting \(\mathcal{H}\)-matrix node. This is actually a restriction of the starting \(\mathcal{H}\)-matrix node to the current \(\mathcal{H}\)-matrix node.
Restrict full matrix to full matrix.
Restrict rank-k matrix to full matrix.
Set the full matrix's property according to the current \(\mathcal{H}\)-matrix node property only when the current \(\mathcal{H}\)-matrix node is a diagonal block.
Note
The state of the full matrix will be taken care of by itself, i.e. its state will change accordingly when some specific operation is applied to it.
Fill the current rank-k matrix with the data extracted from the starting \(\mathcal{H}\)-matrix node.
Restrict full matrix to rank-k matrix.
Restrict rank-k matrix to rank-k matrix.
Definition at line 9483 of file hmatrix.h.
References HMatrix< spacedim, Number >::bc_node, HMatrix< spacedim, Number >::block_type, HMatrix< spacedim, Number >::col_index_range, HMatrix< spacedim, Number >::fullmatrix, FullMatrixType, HierarchicalMatrixType, HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::parent, HMatrix< spacedim, Number >::property, RefineHMatrixWrtExtendedBlockClusterTree(), HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::row_index_range, HMatrix< spacedim, Number >::state, HMatrix< spacedim, Number >::submatrices, HMatrix< spacedim, Number >::submatrix_index, and HMatrix< spacedim, Number >::type.
Referenced by HMatrix< spacedim, Number >::refine_to_supertree(), and RefineHMatrixWrtExtendedBlockClusterTree().
rk_h_mmult() [1/2]
template<int spacedim, typename Number = double> void rk_h_mmult (const Number alpha, const RkMatrix< Number > & M1, HMatrix< spacedim, Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes and the result is scaled by a factor, where the first one M1 has RkMatrixType and the result is also a rank-k matrix.
The arithmetic operation to be performed is
\[ M = \alpha \cdot M_1 \cdot M_2 = \alpha \cdot (A B^T) M_2 = \alpha \cdot A (B^T M_2) = \alpha \cdot A B'^T, \]
where \(B' = M_2^T B\) is calculated as a series of transposed \(\mathcal{H}\)-matrix/vector multiplications. For details,
\[ M_2^T B = M_2^T \begin{bmatrix} b_{\sigma,1} & \cdots & b_{\sigma,r} \end{bmatrix} = \begin{bmatrix} M_2^T b_{\sigma,1} & \cdots & M_2^T b_{\sigma,r} \end{bmatrix} = \begin{bmatrix} b'_{\rho,1} & \cdots & b'_{\rho,r} \end{bmatrix}. \]
It can be seen that the formal rank \(r\) of the result matrix M is the same as that of M1.
Parameters
alpha
M1
M2
M
Create a temporary Vector storing a column \(b_{\sigma,j}\) in the B component of M1 and another Vector \(b'_{\rho,j}\) storing the \(\mathcal{H}\)-matrix/vector product \(M_2^T \cdot b_{\sigma,j}\).
Initialize the result rank-k matrix M with the formal rank of M1_rk. Its A component matrix is the same as that of M1_rk.
Then we calculate the B component matrix of M, which is M2^T*M1_rk.B.
Since the following Tvmult will compute \(y = y + M^T x\), result_vect should be reset to zero beforehand.
Fill the result vector into the B component matrix of M.
Definition at line 11038 of file hmatrix.h.
rk_h_mmult() [2/2]
template<int spacedim, typename Number = double> void rk_h_mmult (const RkMatrix< Number > & M1, HMatrix< spacedim, Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes, where the first one M1 has RkMatrixType and the result is also a rank-k matrix.
The arithmetic operation to be performed is
\[ M = M_1 \cdot M_2 = (A B^T) M_2 = A (B^T M_2) = A B'^T, \]
where \(B' = M_2^T B\) is calculated as a series of transposed \(\mathcal{H}\)-matrix/vector multiplications. For details,
\[ M_2^T B = M_2^T \begin{bmatrix} b_{\sigma,1} & \cdots & b_{\sigma,r} \end{bmatrix} = \begin{bmatrix} M_2^T b_{\sigma,1} & \cdots & M_2^T b_{\sigma,r} \end{bmatrix} = \begin{bmatrix} b'_{\rho,1} & \cdots & b'_{\rho,r} \end{bmatrix}. \]
It can be seen that the formal rank \(r\) of the result matrix M is the same as that of M1.
Parameters
M1
M2
M
Create a temporary Vector storing a column \(b_{\sigma,j}\) in the B component of M1 and another Vector \(b'_{\rho,j}\) storing the \(\mathcal{H}\)-matrix/vector product \(M_2^T \cdot b_{\sigma,j}\).
Initialize the result rank-k matrix M with the formal rank of M1_rk. Its A component matrix is the same as that of M1_rk.
Then we calculate the B component matrix of M, which is M2^T*M1_rk.B.
Fill the result vector into the B component matrix of M.
Definition at line 10959 of file hmatrix.h.
References RkMatrix< Number >::formal_rank, HMatrix< spacedim, Number >::get_property(), HMatrix< spacedim, Number >::m, RkMatrix< Number >::m, HMatrix< spacedim, Number >::n, RkMatrix< Number >::n, RkMatrix< Number >::rank, RkMatrix< Number >::reinit(), and HMatrix< spacedim, Number >::Tvmult().
Referenced by f_h_mmult(), h_h_mmult_level_conserving(), and rk_h_mmult_for_h_h_mmult().
rk_h_mmult_for_h_h_mmult()
template<int spacedim, typename Number = double> void rk_h_mmult_for_h_h_mmult (const HMatrix< spacedim, Number > * M1, HMatrix< spacedim, Number > * M2, HMatrix< spacedim, Number > * M, bool is_M1M2_last_in_M_Sigma_P = true)
Calculate the product of two \(\mathcal{H}\)-matrix nodes, where the first one M1 has RkMatrixType and the result will also be a rank-k matrix. This function is to be called by the matrix-matrix multiplication function.
Parameters
M1
M2
M
Definition at line 11411 of file hmatrix.h.
References HMatrix< spacedim, Number >::m, HMatrix< spacedim, Number >::n, HMatrix< spacedim, Number >::remove_hmat_pair_from_mm_product_list(), rk_h_mmult(), HMatrix< spacedim, Number >::rkmatrix, RkMatrixType, HMatrix< spacedim, Number >::Sigma_F, HMatrix< spacedim, Number >::Sigma_P, HMatrix< spacedim, Number >::Sigma_R, and HMatrix< spacedim, Number >::type.
Referenced by HMatrix< spacedim, Number >::h_h_mmult_reduction().
rk_h_mTmult() [1/2]
template<int spacedim, typename Number = double> void rk_h_mTmult (const Number alpha, const RkMatrix< Number > & M1, HMatrix< spacedim, Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the second operand being transposed, where the first operand M1 has RkMatrixType and the result is also a rank-k matrix. The result will be scaled by a factor.
The arithmetic operation to be performed is
\[ M = \alpha \cdot M_1 \cdot M_2^T = \alpha \cdot (A B^T) M_2^T = \alpha \cdot A (B^T M_2^T) = \alpha \cdot A B'^T, \]
where \(B' = M_2 B\) is calculated as a series of \(\mathcal{H}\)-matrix/vector multiplications. For details,
\[ M_2 B = M_2 \begin{bmatrix} b_{\sigma,1} & \cdots & b_{\sigma,r} \end{bmatrix} = \begin{bmatrix} M_2 b_{\sigma,1} & \cdots & M_2 b_{\sigma,r} \end{bmatrix} = \begin{bmatrix} b'_{\rho,1} & \cdots & b'_{\rho,r} \end{bmatrix}. \]
It can be seen that the formal rank \(r\) of the result matrix M is the same as that of M1.
Parameters
alpha
M1
M2
M
Create a temporary Vector storing a column \(b_{\sigma,j}\) in the B component of M1 and another Vector \(b'_{\rho,j}\) storing the \(\mathcal{H}\)-matrix/vector product \(M_2 \cdot b_{\sigma,j}\).
Initialize the result rank-k matrix M with the formal rank of M1_rk. Its A component matrix is the same as that of M1_rk.
Then we calculate the B component matrix of M, which is M2*M1_rk.B.
Fill the result vector into the B component matrix of M.
Definition at line 11194 of file hmatrix.h.
rk_h_mTmult() [2/2]
template<int spacedim, typename Number = double> void rk_h_mTmult (const RkMatrix< Number > & M1, HMatrix< spacedim, Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the second operand being transposed, where the first operand M1 has RkMatrixType and the result is also a rank-k matrix.
The arithmetic operation to be performed is
\[ M = M_1 \cdot M_2^T = (A B^T) M_2^T = A (B^T M_2^T) = A B'^T, \]
where \(B' = M_2 B\) is calculated as a series of \(\mathcal{H}\)-matrix/vector multiplications. For details,
\[ M_2 B = M_2 \begin{bmatrix} b_{\sigma,1} & \cdots & b_{\sigma,r} \end{bmatrix} = \begin{bmatrix} M_2 b_{\sigma,1} & \cdots & M_2 b_{\sigma,r} \end{bmatrix} = \begin{bmatrix} b'_{\rho,1} & \cdots & b'_{\rho,r} \end{bmatrix}. \]
It can be seen that the formal rank \(r\) of the result matrix M is the same as that of M1.
Parameters
M1
M2
M
Create a temporary Vector storing a column \(b_{\sigma,j}\) in the B component of M1 and another Vector \(b'_{\rho,j}\) storing the \(\mathcal{H}\)-matrix/vector product \(M_2 \cdot b_{\sigma,j}\).
Initialize the result rank-k matrix M with the formal rank of M1_rk. Its A component matrix is the same as that of M1_rk.
Then we calculate the B component matrix of M, which is M2*M1_rk.B.
Fill the result vector into the B component matrix of M.
Definition at line 11119 of file hmatrix.h.
References RkMatrix< Number >::formal_rank, HMatrix< spacedim, Number >::get_property(), HMatrix< spacedim, Number >::m, RkMatrix< Number >::m, HMatrix< spacedim, Number >::n, RkMatrix< Number >::n, RkMatrix< Number >::rank, RkMatrix< Number >::reinit(), and HMatrix< spacedim, Number >::vmult().
Referenced by f_h_mTmult(), and h_h_mTmult_level_conserving().
rk_h_Tmmult() [1/2]
template<int spacedim, typename Number = double> void rk_h_Tmmult (const Number alpha, const RkMatrix< Number > & M1, HMatrix< spacedim, Number > & M2, RkMatrix< Number > & M)
Calculate the scaled product of two \(\mathcal{H}\)-matrix nodes with the first operand being transposed, where the first one M1 has RkMatrixType and the result is also a rank-k matrix.
The arithmetic operation to be performed is
\[ M = \alpha M_1^T \cdot M_2 = \alpha (A B^T)^T M_2 = \alpha B (A^T M_2) = \alpha B A'^T, \]
where \(A' = M_2^T A\) is calculated as a series of transposed \(\mathcal{H}\)-matrix/vector multiplications. For details,
\[ M_2^T A = M_2^T \begin{bmatrix} a_{\sigma,1} & \cdots & a_{\sigma,r} \end{bmatrix} = \begin{bmatrix} M_2^T a_{\sigma,1} & \cdots & M_2^T a_{\sigma,r} \end{bmatrix} = \begin{bmatrix} a'_{\rho,1} & \cdots & a'_{\rho,r} \end{bmatrix}. \]
It can be seen that the formal rank \(r\) of the result matrix M is the same as that of M1.
Parameters
alpha
M1
M2
M
Create a temporary Vector storing a column \(a_{\sigma,j}\) in the A component of M1 and another Vector \(a'_{\rho,j}\) storing the transposed \(\mathcal{H}\)-matrix/vector product \(M_2^T \cdot a_{\sigma,j}\).
Initialize the result rank-k matrix M with the formal rank of M1_rk. Its A component matrix is the same as the B component of M1_rk.
Then we calculate the B component matrix of M, which is M2^T*M1_rk.A.
Fill the result vector into the B component matrix of M.
Definition at line 11354 of file hmatrix.h.
rk_h_Tmmult() [2/2]
template<int spacedim, typename Number = double> void rk_h_Tmmult (const RkMatrix< Number > & M1, HMatrix< spacedim, Number > & M2, RkMatrix< Number > & M)
Calculate the product of two \(\mathcal{H}\)-matrix nodes with the first operand being transposed, where the first one M1 has RkMatrixType and the result is also a rank-k matrix.
The arithmetic operation to be performed is
\[ M = M_1^T \cdot M_2 = (A B^T)^T M_2 = B (A^T M_2) = B A'^T, \]
where \(A' = M_2^T A\) is calculated as a series of transposed \(\mathcal{H}\)-matrix/vector multiplications. For details,
\[ M_2^T A = M_2^T \begin{bmatrix} a_{\sigma,1} & \cdots & a_{\sigma,r} \end{bmatrix} = \begin{bmatrix} M_2^T a_{\sigma,1} & \cdots & M_2^T a_{\sigma,r} \end{bmatrix} = \begin{bmatrix} a'_{\rho,1} & \cdots & a'_{\rho,r} \end{bmatrix}. \]
It can be seen that the formal rank \(r\) of the result matrix M is the same as that of M1.
Parameters
M1
M2
M
Create a temporary Vector storing a column \(a_{\sigma,j}\) in the A component of M1 and another Vector \(a'_{\rho,j}\) storing the transposed \(\mathcal{H}\)-matrix/vector product \(M_2^T \cdot a_{\sigma,j}\).
Initialize the result rank-k matrix M with the formal rank of M1_rk. Its A component matrix is the same as the B component of M1_rk.
Then we calculate the B component matrix of M, which is M2^T*M1_rk.A.
Fill the result vector into the B component matrix of M.
Definition at line 11273 of file hmatrix.h.
References RkMatrix< Number >::formal_rank, HMatrix< spacedim, Number >::get_property(), HMatrix< spacedim, Number >::m, RkMatrix< Number >::m, HMatrix< spacedim, Number >::n, RkMatrix< Number >::n, RkMatrix< Number >::rank, RkMatrix< Number >::reinit(), and HMatrix< spacedim, Number >::Tvmult().
Referenced by f_h_Tmmult(), and h_h_Tmmult_level_conserving().