HierBEM: include/linear_algebra/lapack_helpers.h File Reference
lapack_helpers.h File Reference
Linear algebra
Exposes LAPACK helper functions defined in lapack_full_matrix.cc and define new ones by following them as examples.
#include <deal.II/base/numbers.h>
#include <deal.II/lac/blas_extension_templates.h>
#include <deal.II/lac/block_vector.h>
#include <deal.II/lac/full_matrix.h>
#include <deal.II/lac/lapack_full_matrix.h>
#include <deal.II/lac/lapack_support.h>
#include <deal.II/lac/lapack_templates.h>
#include <deal.II/lac/sparse_matrix.h>
#include <deal.II/lac/utilities.h>
#include <deal.II/lac/vector.h>
#include <complex>
#include <type_traits>
#include "config.h"
#include "lapack_templates_ext.h"
Functions
template<typename T >
void LAPACKHelpers::gemv_helper (const char trans, const T alpha, const types::blas_int n_rows, const types::blas_int n_cols, const AlignedVector< T > &matrix, const T *x_pointer, const T beta, T *y_pointer, const types::blas_int incx=1, const types::blas_int incy=1)
Multiplication of a general matrix and a vector, which computes y = alpha*A*x + beta*y.
template<typename T >
void LAPACKHelpers::symv_helper (const char uplo, const T alpha, const types::blas_int n_rows, const AlignedVector< T > &matrix, const T *x_pointer, const T beta, T *y_pointer, const types::blas_int incx=1, const types::blas_int incy=1)
template<typename T >
void LAPACKHelpers::hemv_helper (const char uplo, const T alpha, const types::blas_int n_rows, const AlignedVector< T > &matrix, const T *x_pointer, const T beta, T *y_pointer, const types::blas_int incx=1, const types::blas_int incy=1)
template<typename T >
void LAPACKHelpers::trmv_helper (const char uplo, const char trans, const char diag, const types::blas_int n_rows, const AlignedVector< T > &matrix, T *x_pointer, const types::blas_int incx=1)
template<typename T >
void LAPACKHelpers::geev_helper (const char vl, const char vr, AlignedVector< T > &matrix, const types::blas_int n_rows, std::vector< T > &real_part_eigenvalues, std::vector< T > &imag_part_eigenvalues, std::vector< T > &left_eigenvectors, std::vector< T > &right_eigenvectors, std::vector< T > &real_work, std::vector< T > &, const types::blas_int work_flag, types::blas_int &info)
template<typename T >
void LAPACKHelpers::geev_helper (const char vl, const char vr, AlignedVector< std::complex< T > > &matrix, const types::blas_int n_rows, std::vector< T > &, std::vector< std::complex< T > > &eigenvalues, std::vector< std::complex< T > > &left_eigenvectors, std::vector< std::complex< T > > &right_eigenvectors, std::vector< std::complex< T > > &complex_work, std::vector< T > &real_work, const types::blas_int work_flag, types::blas_int &info)
template<typename T >
void LAPACKHelpers::gesdd_helper (const char job, const types::blas_int n_rows, const types::blas_int n_cols, AlignedVector< T > &matrix, std::vector< T > &singular_values, AlignedVector< T > &left_vectors, AlignedVector< T > &right_vectors, std::vector< T > &real_work, std::vector< T > &, std::vector< types::blas_int > &integer_work, const types::blas_int work_flag, types::blas_int &info)
template<typename T >
void LAPACKHelpers::gesdd_helper (const char job, const types::blas_int n_rows, const types::blas_int n_cols, AlignedVector< std::complex< T > > &matrix, std::vector< T > &singular_values, AlignedVector< std::complex< T > > &left_vectors, AlignedVector< std::complex< T > > &right_vectors, std::vector< std::complex< T > > &work, std::vector< T > &real_work, std::vector< types::blas_int > &integer_work, const types::blas_int &work_flag, types::blas_int &info)
template<typename T >
void LAPACKHelpers::geqrf_helper (const types::blas_int n_rows, const types::blas_int n_cols, AlignedVector< T > &matrix, std::vector< T > &tau, std::vector< T > &work, const types::blas_int work_flag, types::blas_int &info)
template<typename T >
void LAPACKHelpers::trsv_helper (const char uplo, const bool is_transposed, const bool is_hermite_transposed, const bool is_unit_diagonal, const types::blas_int n_rows, const AlignedVector< T > &matrix, T *right_vector_pointer, const types::blas_int incx=1)
template<typename T >
void LAPACKHelpers::trsv_helper (const char uplo, const bool is_transposed, const bool is_hermite_transposed, const bool is_unit_diagonal, const types::blas_int n_rows, const AlignedVector< std::complex< T > > &matrix, std::complex< T > *right_vector_pointer, const types::blas_int incx=1)
Detailed Description
Exposes LAPACK helper functions defined in lapack_full_matrix.cc and define new ones by following them as examples.
Note
Because helper functions in lapack_full_matrix.cc are template functions and they are not defined in a header file, their instantiation is limited within the translation unit lapack_full_matrix.cc. Therefore, the helper functions are not available in the deal.ii dynamic library compiled in Release mode. But why they are available in the Debug mode library is still a mystery. Comment on 2022-03-23 by Jihuan Tian.
Date
2021-06-09
Author
Jihuan Tian
Definition in file lapack_helpers.h.
Function Documentation
geev_helper() [1/2]
template<typename T > void LAPACKHelpers::geev_helper (const char vl, const char vr, AlignedVector< std::complex< T > > & matrix, const types::blas_int n_rows, std::vector< T > & , std::vector< std::complex< T > > & eigenvalues, std::vector< std::complex< T > > & left_eigenvectors, std::vector< std::complex< T > > & right_eigenvectors, std::vector< std::complex< T > > & complex_work, std::vector< T > & real_work, const types::blas_int work_flag, types::blas_int & info)
Definition at line 304 of file lapack_helpers.h.
geev_helper() [2/2]
template<typename T > void LAPACKHelpers::geev_helper (const char vl, const char vr, AlignedVector< T > & matrix, const types::blas_int n_rows, std::vector< T > & real_part_eigenvalues, std::vector< T > & imag_part_eigenvalues, std::vector< T > & left_eigenvectors, std::vector< T > & right_eigenvectors, std::vector< T > & real_work, std::vector< T > & , const types::blas_int work_flag, types::blas_int & info)
Definition at line 251 of file lapack_helpers.h.
gemv_helper()
template<typename T > void LAPACKHelpers::gemv_helper (const char trans, const T alpha, const types::blas_int n_rows, const types::blas_int n_cols, const AlignedVector< T > & matrix, const T * x_pointer, const T beta, T * y_pointer, const types::blas_int incx = 1, const types::blas_int incy = 1)
Multiplication of a general matrix and a vector, which computes y = alpha*A*x + beta*y.
Template Parameters
T
Parameters
trans
alpha
n_rows
n_cols
matrix
x
beta
y
incx
incy
Definition at line 73 of file lapack_helpers.h.
References LAPACKHelpers::gemv_helper().
Referenced by LAPACKHelpers::gemv_helper().
geqrf_helper()
template<typename T > void LAPACKHelpers::geqrf_helper (const types::blas_int n_rows, const types::blas_int n_cols, AlignedVector< T > & matrix, std::vector< T > & tau, std::vector< T > & work, const types::blas_int work_flag, types::blas_int & info)
Helper function for QR decomposition.
Definition at line 486 of file lapack_helpers.h.
References LAPACKHelpers::geqrf_helper().
Referenced by LAPACKHelpers::geqrf_helper().
gesdd_helper() [1/2]
template<typename T > void LAPACKHelpers::gesdd_helper (const char job, const types::blas_int n_rows, const types::blas_int n_cols, AlignedVector< std::complex< T > > & matrix, std::vector< T > & singular_values, AlignedVector< std::complex< T > > & left_vectors, AlignedVector< std::complex< T > > & right_vectors, std::vector< std::complex< T > > & work, std::vector< T > & real_work, std::vector< types::blas_int > & integer_work, const types::blas_int & work_flag, types::blas_int & info)
Helper function for complex valued SVD.
Its implementation has already existed in the deal.ii library.
Parameters
job
n_rows
n_cols
matrix
singular_values
left_vectors
right_vectors
work
real_work
integer_work
work_flag
info
Definition at line 435 of file lapack_helpers.h.
References LAPACKHelpers::gesdd_helper().
gesdd_helper() [2/2]
template<typename T > void LAPACKHelpers::gesdd_helper (const char job, const types::blas_int n_rows, const types::blas_int n_cols, AlignedVector< T > & matrix, std::vector< T > & singular_values, AlignedVector< T > & left_vectors, AlignedVector< T > & right_vectors, std::vector< T > & real_work, std::vector< T > & , std::vector< types::blas_int > & integer_work, const types::blas_int work_flag, types::blas_int & info)
Helper function for real valued SVD.
Its implementation has already existed in the deal.ii library.
Parameters
job
n_rows
n_cols
matrix
singular_values
left_vectors
right_vectors
real_work
param integer_work
Parameters
work_flag
info
Definition at line 372 of file lapack_helpers.h.
References LAPACKHelpers::gesdd_helper().
Referenced by LAPACKHelpers::gesdd_helper().
hemv_helper()
template<typename T > void LAPACKHelpers::hemv_helper (const char uplo, const T alpha, const types::blas_int n_rows, const AlignedVector< T > & matrix, const T * x_pointer, const T beta, T * y_pointer, const types::blas_int incx = 1, const types::blas_int incy = 1)
Multiplication of an Hermite symmetric matrix and a vector. Only the triangular part of the symmetric matrix is stored.
Parameters
uplo
alpha
n_rows
matrix
x_pointer
beta
y_pointer
incx
incy
Definition at line 172 of file lapack_helpers.h.
References LAPACKHelpers::hemv_helper().
Referenced by LAPACKHelpers::hemv_helper().
symv_helper()
template<typename T > void LAPACKHelpers::symv_helper (const char uplo, const T alpha, const types::blas_int n_rows, const AlignedVector< T > & matrix, const T * x_pointer, const T beta, T * y_pointer, const types::blas_int incx = 1, const types::blas_int incy = 1)
Multiplication of a symmetric matrix and a vector. Only the triangular part of the symmetric matrix is stored.
Parameters
uplo
alpha
n_rows
matrix
x_pointer
beta
y_pointer
incx
incy
Definition at line 122 of file lapack_helpers.h.
References LAPACKHelpers::symv_helper().
Referenced by LAPACKHelpers::symv_helper().
trmv_helper()
template<typename T > void LAPACKHelpers::trmv_helper (const char uplo, const char trans, const char diag, const types::blas_int n_rows, const AlignedVector< T > & matrix, T * x_pointer, const types::blas_int incx = 1)
Multiplication of a triangular matrix with a vector.
Parameters
uplo
trans
diag
n_rows
matrix
x_pointer
incx
Definition at line 218 of file lapack_helpers.h.
References LAPACKHelpers::trmv_helper().
Referenced by LAPACKHelpers::trmv_helper().
trsv_helper() [1/2]
template<typename T > void LAPACKHelpers::trsv_helper (const char uplo, const bool is_transposed, const bool is_hermite_transposed, const bool is_unit_diagonal, const types::blas_int n_rows, const AlignedVector< std::complex< T > > & matrix, std::complex< T > * right_vector_pointer, const types::blas_int incx = 1)
Complex valued version of the helper function for trsv.
Since the values member variable of type AlignedVector stored in the right hand side vector is private, which cannot be directly accessed from LAPACKFullMatrixExt, the data pointer to the right hand side vector is passed as argument, which can be obtained via the member function data of Vector.
Parameters
uplo
is_transposed
is_hermite_transposed
is_unit_diagonal
n_rows
matrix
right_vector
incx
Definition at line 589 of file lapack_helpers.h.
References LAPACKHelpers::trsv_helper().
trsv_helper() [2/2]
template<typename T > void LAPACKHelpers::trsv_helper (const char uplo, const bool is_transposed, const bool is_hermite_transposed, const bool is_unit_diagonal, const types::blas_int n_rows, const AlignedVector< T > & matrix, T * right_vector_pointer, const types::blas_int incx = 1)
Real valued version of the helper function for trsv, which solves a unit or non-unit, upper or lower triangular matrix.
Note
1. Access the matrix data: the internal data contained within a LAPACKFullMatrixExt has the type AlignedVector, which is a protected member variable in the parent class TableBase of LAPACKFullMatrixExt. Therefore, this variable can be directly visited from LAPACKFullMatrixExt and passed into this function.
Access the RHS vector data: being different from LAPACKFullMatrixExt, the values member variable of type AlignedVector contained in the RHS vector is private, which cannot be accessed from LAPACKFullMatrixExt. Therefore, the pointer to the internal data within the RHS vector can be obtained by calling the member function Vector::data(). Then it is passed to this function.
Parameters
uplo
is_transposed
is_hermite_transposed
is_unit_diagonal
n_rows
matrix
right_vector
incx
Definition at line 540 of file lapack_helpers.h.
References LAPACKHelpers::trsv_helper().
Referenced by LAPACKHelpers::trsv_helper().