HierBEM: include/linear_algebra/linalg.h File Reference
linalg.h File Reference
#include <deal.II/base/exceptions.h>
#include <deal.II/base/numbers.h>
#include <deal.II/base/parallel.h>
#include <deal.II/base/types.h>
#include <deal.II/base/vectorization.h>
#include <deal.II/lac/full_matrix.h>
#include <deal.II/lac/lapack_support.h>
#include <deal.II/lac/vector.h>
#include <deal.II/lac/vector_operations_internal.h>
#include <tbb/partitioner.h>
#include <complex>
#include <limits>
#include <type_traits>
#include "blas_helpers.h"
#include "config.h"
#include "lapack_full_matrix_ext.h"
#include "utilities/number_traits.h"
Classes
struct LinAlg::InnerProductOperation< Number1, Number2 >
struct LinAlg::LinearCombinationOperation< Number1, Number2 >
struct LinAlg::Vector_conjugate< Number >
struct LinAlg::Vector_real_part< Number1, Number2 >
struct LinAlg::Vector_imag_part< Number1, Number2 >
struct LinAlg::Vector_amplitude< Number1, Number2 >
struct LinAlg::Vector_angle< Number1, Number2 >
Typedefs
using LinAlg::size_type = std::make_unsigned< types::blas_int >::type
Functions
template<typename number >
number LinAlg::determinant4x4 (const FullMatrix< number > &matrix)
template<typename number >
number LinAlg::determinant4x4 (const LAPACKFullMatrixExt< number > &matrix)
template<typename number >
bool LinAlg::is_all_zero (const Vector< number > &vec)
template<typename number >
void LinAlg::copy_vector (Vector< number > &dst_vec, const typename Vector< number >::size_type dst_start_index, const Vector< number > &src_vec, const typename Vector< number >::size_type src_start_index, const typename Vector< number >::size_type number_of_data)
template<typename VectorType1 , typename VectorType2 >
VectorType1::value_type LinAlg::inner_product (const VectorType1 &vec1, const VectorType2 &vec2)
template<typename VectorType1 , typename VectorType2 >
VectorType1::value_type LinAlg::linear_combination (const VectorType1 &vec1, const VectorType2 &vec2)
template<typename VectorType1 , typename VectorType2 >
VectorType1::value_type LinAlg::inner_product_tbb (const VectorType1 &vec1, const VectorType2 &vec2)
template<typename VectorType1 , typename VectorType2 >
VectorType1::value_type LinAlg::linear_combination_tbb (const VectorType1 &vec1, const VectorType2 &vec2)
template<typename VectorType >
void LinAlg::conjugate_vector (VectorType &v)
template<typename VectorType1 , typename VectorType2 >
void LinAlg::get_vector_real_part (VectorType1 &vec1, const VectorType2 &vec2)
template<typename VectorType1 , typename VectorType2 >
void LinAlg::get_vector_imag_part (VectorType1 &vec1, const VectorType2 &vec2)
template<typename VectorType1 , typename VectorType2 >
void LinAlg::get_vector_amplitude (VectorType1 &vec1, const VectorType2 &vec2)
template<typename VectorType1 , typename VectorType2 >
void LinAlg::get_vector_angle (VectorType1 &vec1, const VectorType2 &vec2)
template<typename VectorType , typename MatrixType >
void LinAlg::apply_givens_2x2 (VectorType &v, const MatrixType &givens, const size_type i)
Apply a 2x2 Givens rotation matrix to the input vector at the specified index.
Detailed Description
Date
2020-11-30
Author
Jihuan Tian
Definition in file linalg.h.
Typedef Documentation
size_type
using LinAlg::size_type = typedef std::make_unsigned<types::blas_int>::type
Definition at line 48 of file linalg.h.
Function Documentation
apply_givens_2x2()
template<typename VectorType , typename MatrixType > void LinAlg::apply_givens_2x2 (VectorType & v, const MatrixType & givens, const size_type i)
Apply a 2x2 Givens rotation matrix to the input vector at the specified index.
Template Parameters
VectorType
MatrixType
Parameters
v
givens
i
Definition at line 595 of file linalg.h.
References LinAlg::apply_givens_2x2().
Referenced by LinAlg::apply_givens_2x2().
conjugate_vector()
template<typename VectorType > void LinAlg::conjugate_vector (VectorType & v)
Definition at line 396 of file linalg.h.
copy_vector()
template<typename number > void LinAlg::copy_vector (Vector< number > & dst_vec, const typename Vector< number >::size_type dst_start_index, const Vector< number > & src_vec, const typename Vector< number >::size_type src_start_index, const typename Vector< number >::size_type number_of_data)
Copy a segment of a vector into another vector at the specified location.
Parameters
dst_vec
dst_start_index
src_vec
start_index
number_of_data
Definition at line 159 of file linalg.h.
determinant4x4() [1/2]
template<typename number > number LinAlg::determinant4x4 (const FullMatrix< number > & matrix)
Calculate the determinant of a $4 \times 4$ matrix.
Definition at line 55 of file linalg.h.
determinant4x4() [2/2]
template<typename number > number LinAlg::determinant4x4 (const LAPACKFullMatrixExt< number > & matrix)
Definition at line 93 of file linalg.h.
get_vector_amplitude()
template<typename VectorType1 , typename VectorType2 > void LinAlg::get_vector_amplitude (VectorType1 & vec1, const VectorType2 & vec2)
Definition at line 555 of file linalg.h.
get_vector_angle()
template<typename VectorType1 , typename VectorType2 > void LinAlg::get_vector_angle (VectorType1 & vec1, const VectorType2 & vec2)
Definition at line 570 of file linalg.h.
get_vector_imag_part()
template<typename VectorType1 , typename VectorType2 > void LinAlg::get_vector_imag_part (VectorType1 & vec1, const VectorType2 & vec2)
Definition at line 540 of file linalg.h.
get_vector_real_part()
template<typename VectorType1 , typename VectorType2 > void LinAlg::get_vector_real_part (VectorType1 & vec1, const VectorType2 & vec2)
Definition at line 525 of file linalg.h.
inner_product()
template<typename VectorType1 , typename VectorType2 > VectorType1::value_type LinAlg::inner_product (const VectorType1 & vec1, const VectorType2 & vec2)
Compute the inner product of two vectors. When in the complex valued case, complex conjugation is applied to the second operand.
Definition at line 177 of file linalg.h.
inner_product_tbb()
template<typename VectorType1 , typename VectorType2 > VectorType1::value_type LinAlg::inner_product_tbb (const VectorType1 & vec1, const VectorType2 & vec2)
Compute the inner product of two vectors using TBB parallel_reduce . When in the complex valued case, complex conjugation is applied to the second operand.
Definition at line 328 of file linalg.h.
References LinAlg::inner_product_tbb().
Referenced by LinAlg::inner_product_tbb().
is_all_zero()
template<typename number > bool LinAlg::is_all_zero (const Vector< number > & vec)
Check if the vector is zero-valued by calculating its L1 norm.
Parameters
vec
Returns
Definition at line 137 of file linalg.h.
References LinAlg::is_all_zero().
Referenced by LinAlg::is_all_zero().
linear_combination()
template<typename VectorType1 , typename VectorType2 > VectorType1::value_type LinAlg::linear_combination (const VectorType1 & vec1, const VectorType2 & vec2)
Compute the linear combination of two vectors, which is different from the inner product operation in that the second operand is not conjugated when the number is complex valued.
Definition at line 207 of file linalg.h.
linear_combination_tbb()
template<typename VectorType1 , typename VectorType2 > VectorType1::value_type LinAlg::linear_combination_tbb (const VectorType1 & vec1, const VectorType2 & vec2)
Compute the linear combination of two vectors using TBB parallel_reduce .
Definition at line 352 of file linalg.h.
References LinAlg::linear_combination_tbb().
Referenced by LinAlg::linear_combination_tbb().