HierBEM: include/cluster_tree/tree.h File Reference
tree.h File Reference
Hierarchical matrices
Implementation of the classes for binary tree node, general tree node and functions for manipulating the trees constructed from these nodes.
#include <deal.II/base/exceptions.h>
#include <deal.II/base/memory_consumption.h>
#include <algorithm>
#include <array>
#include <exception>
#include <functional>
#include <iostream>
#include <new>
#include <vector>
#include "config.h"
Classes
class BinaryTreeNode< T >
Class for binary tree node.
class TreeNode< T, N >
Class for general tree node.
enum TreeNodeSplitMode { HorizontalSplitMode , VerticalSplitMode , CrossSplitMode , UnsplitMode }
template<typename T >
BinaryTreeNode< T > * CreateTreeNode (const T &data, unsigned int level=0, BinaryTreeNode< T > *left=nullptr, BinaryTreeNode< T > *right=nullptr, BinaryTreeNode< T > *parent=nullptr)
template<typename T , std::size_t N>
TreeNode< T, N > * CreateTreeNode (const T &data, unsigned int level, const std::array< TreeNode< T, N > *, N > &children, TreeNode< T, N > *parent=nullptr, TreeNodeSplitMode split_mode=UnsplitMode)
template<typename T >
void DeleteTreeNode (const BinaryTreeNode< T > *p)
template<typename T , std::size_t N>
void DeleteTreeNode (const TreeNode< T, N > *p)
template<typename T >
void PrintTreeNode (std::ostream &out, const BinaryTreeNode< T > *p)
template<typename T , std::size_t N>
void PrintTreeNode (std::ostream &out, const TreeNode< T, N > *p)
template<typename T >
unsigned int calc_depth (const BinaryTreeNode< T > *p)
template<typename T , std::size_t N>
unsigned int calc_depth (TreeNode< T, N > *p)
template<typename T >
void Preorder (BinaryTreeNode< T > *p, std::function< void(BinaryTreeNode< T > *)> operate)
template<typename T >
void Preorder (const BinaryTreeNode< T > *p, std::function< void(const BinaryTreeNode< T > *)> operate)
template<typename T , typename Number >
void Preorder_for_memory_consumption (const BinaryTreeNode< T > *p, Number &accumulated_results)
template<typename T , std::size_t N>
void Preorder (TreeNode< T, N > *p, std::function< void(TreeNode< T, N > *)> operate)
template<typename T , std::size_t N>
void Preorder (const TreeNode< T, N > *p, std::function< void(const TreeNode< T, N > *)> operate)
template<typename T , std::size_t N, typename Number >
void Preorder_for_memory_consumption (TreeNode< T, N > *p, Number &accumulated_results)
template<typename T >
void Inorder (BinaryTreeNode< T > *p, std::function< void(BinaryTreeNode< T > *)> operate)
template<typename T >
void Inorder (const BinaryTreeNode< T > *p, std::function< void(const BinaryTreeNode< T > *)> operate)
template<typename T >
void Postorder (BinaryTreeNode< T > *p, std::function< void(BinaryTreeNode< T > *)> operate)
template<typename T >
void Postorder (const BinaryTreeNode< T > *p, std::function< void(const BinaryTreeNode< T > *)> operate)
template<typename T , std::size_t N>
void Postorder (TreeNode< T, N > *p, std::function< void(TreeNode< T, N > *)> operate)
template<typename T , std::size_t N>
void Postorder (const TreeNode< T, N > *p, std::function< void(const TreeNode< T, N > *)> operate)
template<typename T >
BinaryTreeNode< T > * CopyTree (const BinaryTreeNode< T > *p)
template<typename T , std::size_t N>
TreeNode< T, N > * CopyTree (const TreeNode< T, N > *p)
template<typename T >
void GetTreeLeaves (const BinaryTreeNode< T > *p, std::vector< BinaryTreeNode< T > * > &leaf_set)
template<typename T , std::size_t N>
void GetTreeLeaves (const TreeNode< T, N > *p, std::vector< TreeNode< T, N > * > &leaf_set)
template<typename T >
void GetTreeNodesAtLevel (const BinaryTreeNode< T > *p, const unsigned int level, std::vector< BinaryTreeNode< T > * > &node_set)
template<typename T , std::size_t N>
void GetTreeNodesAtLevel (const TreeNode< T, N > *p, const unsigned int level, std::vector< TreeNode< T, N > * > &node_set)
template<typename T >
void PrintTree (std::ostream &out, const BinaryTreeNode< T > *p)
template<typename T , std::size_t N>
void PrintTree (std::ostream &out, const TreeNode< T, N > *p)
template<typename T >
unsigned int CountTreeNodes (const BinaryTreeNode< T > *p)
template<typename T , std::size_t N>
unsigned int CountTreeNodes (const TreeNode< T, N > *p)
template<typename T >
void DeleteTree (const BinaryTreeNode< T > *p)
template<typename T , std::size_t N>
void DeleteTree (const TreeNode< T, N > *p)
Detailed Description
Implementation of the classes for binary tree node, general tree node and functions for manipulating the trees constructed from these nodes.
Date
2021-04-18
Author
Jihuan Tian
Definition in file tree.h.
Enumeration Type Documentation
TreeNodeSplitMode
enum TreeNodeSplitMode
The splitting mode for a tree node, which can be cross split (CrossSplitMode), horizontal split (HorizontalSplitMode), vertical split (VerticalSplitMode) and unsplit (UnsplitMode).
Note
When a tree node has four children, which are constructed via a tensor product of the children of the \(\tau\) cluster and the children of the \(\sigma\) cluster, it must be cross split.
When a tree node has two children, which are constructed via a tensor product of the children of the \(\tau\) cluster and the \(\sigma\) cluster, i.e. only the rows of the associated \(\mathcal{H}\)-matrix node will be split, then it should be horizontal split.
When a tree node has two children, which are constructed via a tensor product of the \(\tau\) cluster and the children of the \(\sigma\) cluster, i.e. only the columns of the associated \(\mathcal{H}\)-matrix node will be split, then it should be vertical split.
Definition at line 531 of file tree.h.
Function Documentation
calc_depth() [1/2]
template<typename T > unsigned int calc_depth (const BinaryTreeNode< T > * p)
Calculate the depth of a BinaryTree using recursion.
Definition at line 1108 of file tree.h.
References calc_depth(), BinaryTreeNode< T >::Left(), and BinaryTreeNode< T >::Right().
Referenced by calc_depth(), BlockClusterTree< spacedim, Number >::calc_depth_and_max_level(), and ClusterTree< spacedim, Number >::partition().
calc_depth() [2/2]
template<typename T , std::size_t N> unsigned int calc_depth (TreeNode< T, N > * p)
Calculate the depth of a TreeNode using recursion.
Definition at line 1125 of file tree.h.
References calc_depth(), and TreeNode< T, N >::get_child_pointer().
CopyTree() [1/2]
template<typename T > BinaryTreeNode< T > * CopyTree (const BinaryTreeNode< T > * p)
Copy the current node to a new node without setting children, parent and child_num at the moment.
Associate the newly created left child node with the current node.
Associate the newly created right child node with the current node.
Definition at line 1375 of file tree.h.
References CopyTree(), CreateTreeNode(), BinaryTreeNode< T >::get_data_reference(), BinaryTreeNode< T >::get_level(), BinaryTreeNode< T >::increase_child_num(), BinaryTreeNode< T >::Left(), BinaryTreeNode< T >::Parent(), and BinaryTreeNode< T >::Right().
Referenced by BlockClusterTree< spacedim, Number >::BlockClusterTree(), ClusterTree< spacedim, Number >::ClusterTree(), CopyTree(), BlockClusterTree< spacedim, Number >::operator=(), and ClusterTree< spacedim, Number >::operator=().
CopyTree() [2/2]
template<typename T , std::size_t N> TreeNode< T, N > * CopyTree (const TreeNode< T, N > * p)
Perform deep copy of a tree.
Parameters
p
Returns
Create and copy the current node.
Definition at line 1430 of file tree.h.
References CopyTree(), CreateTreeNode(), TreeNode< T, N >::get_child_num(), TreeNode< T, N >::get_child_pointer(), TreeNode< T, N >::get_data_reference(), TreeNode< T, N >::get_level(), TreeNode< T, N >::get_split_mode(), TreeNode< T, N >::increase_child_num(), TreeNode< T, N >::Parent(), and TreeNode< T, N >::set_child_pointer().
CountTreeNodes() [1/2]
template<typename T > unsigned int CountTreeNodes (const BinaryTreeNode< T > * p)
Count the total number of the binary tree nodes by recursion.
Definition at line 1699 of file tree.h.
References CountTreeNodes(), BinaryTreeNode< T >::Left(), and BinaryTreeNode< T >::Right().
Referenced by BlockClusterTree< spacedim, Number >::BlockClusterTree(), CountTreeNodes(), and BlockClusterTree< spacedim, Number >::prune_descendants_from_node().
CountTreeNodes() [2/2]
template<typename T , std::size_t N> unsigned int CountTreeNodes (const TreeNode< T, N > * p)
Count the total number of the tree nodes by recursion.
Definition at line 1723 of file tree.h.
References CountTreeNodes(), and TreeNode< T, N >::get_child_pointer().
CreateTreeNode() [1/2]
template<typename T , std::size_t N> TreeNode< T, N > * CreateTreeNode (const T & data, unsigned int level, const std::array< TreeNode< T, N > *, N > & children, TreeNode< T, N > * parent = nullptr, TreeNodeSplitMode split_mode = UnsplitMode)
Create a new tree node from the provided data.
Definition at line 1009 of file tree.h.
CreateTreeNode() [2/2]
template<typename T > BinaryTreeNode< T > * CreateTreeNode (const T & data, unsigned int level = 0, BinaryTreeNode< T > * left = nullptr, BinaryTreeNode< T > * right = nullptr, BinaryTreeNode< T > * parent = nullptr)
Create a new binary tree node from the provided data.
Definition at line 985 of file tree.h.
Referenced by BlockClusterTree< spacedim, Number >::BlockClusterTree(), and CopyTree().
DeleteTree() [1/2]
template<typename T > void DeleteTree (const BinaryTreeNode< T > * p)
Use the Delete a whole binary tree using post-order traversal.
Definition at line 1749 of file tree.h.
Referenced by BlockClusterTree< spacedim, Number >::prune_descendants_from_node(), BlockClusterTree< spacedim, Number >::release(), and ClusterTree< spacedim, Number >::release().
DeleteTree() [2/2]
template<typename T , std::size_t N> void DeleteTree (const TreeNode< T, N > * p)
Use the Delete a whole tree using post-order traversal.
Definition at line 1759 of file tree.h.
DeleteTreeNode() [1/2]
template<typename T > void DeleteTreeNode (const BinaryTreeNode< T > * p)
Destroy a binary tree node.
Definition at line 1033 of file tree.h.
DeleteTreeNode() [2/2]
template<typename T , std::size_t N> void DeleteTreeNode (const TreeNode< T, N > * p)
Destroy a tree node.
Definition at line 1046 of file tree.h.
GetTreeLeaves() [1/2]
template<typename T > void GetTreeLeaves (const BinaryTreeNode< T > * p, std::vector< BinaryTreeNode< T > * > & leaf_set)
Construct the leaf set of a binary tree.
Note
The leaf set should be cleared before calling this function.
Parameters
p
leaf_set
If the current node has no children, append it to the leaf set.
If the current node has children, recursively collect leaves from its left and right children.
Definition at line 1488 of file tree.h.
References BinaryTreeNode< T >::get_child_num(), GetTreeLeaves(), BinaryTreeNode< T >::Left(), and BinaryTreeNode< T >::Right().
Referenced by BlockClusterTree< spacedim, Number >::build_leaf_set(), ClusterTree< spacedim, Number >::build_leaf_set(), and GetTreeLeaves().
GetTreeLeaves() [2/2]
template<typename T , std::size_t N> void GetTreeLeaves (const TreeNode< T, N > * p, std::vector< TreeNode< T, N > * > & leaf_set)
Construct the leaf set of a general tree.
Note
The leaf set should be cleared before calling this function.
Parameters
p
leaf_set
If the current node has no children, append it to the leaf set.
If the current node has children, recursively collect leaves from each of its children.
Definition at line 1537 of file tree.h.
References TreeNode< T, N >::get_child_num(), TreeNode< T, N >::get_child_pointer(), and GetTreeLeaves().
GetTreeNodesAtLevel() [1/2]
template<typename T > void GetTreeNodesAtLevel (const BinaryTreeNode< T > * p, const unsigned int level, std::vector< BinaryTreeNode< T > * > & node_set)
Construct the set of nodes at the specified level of a binary tree.
@level starts from zero.
Template Parameters
T
Parameters
p
level
node_set
If the current node has children, recursively collect nodes at the specified level from its left and right children.
Definition at line 1582 of file tree.h.
References BinaryTreeNode< T >::get_level(), GetTreeNodesAtLevel(), BinaryTreeNode< T >::Left(), and BinaryTreeNode< T >::Right().
Referenced by ClusterTree< spacedim, Number >::build_cluster_set_at_level(), and GetTreeNodesAtLevel().
GetTreeNodesAtLevel() [2/2]
template<typename T , std::size_t N> void GetTreeNodesAtLevel (const TreeNode< T, N > * p, const unsigned int level, std::vector< TreeNode< T, N > * > & node_set)
Construct the set of nodes at the specified level of a general tree.
@level starts from zero.
Template Parameters
T
N
Parameters
p
level
node_set
If the current node has children, recursively collect nodes at the specified level from each of its children.
Definition at line 1631 of file tree.h.
References TreeNode< T, N >::get_child_pointer(), TreeNode< T, N >::get_level(), and GetTreeNodesAtLevel().
Inorder() [1/2]
template<typename T > void Inorder (BinaryTreeNode< T > * p, std::function< void(BinaryTreeNode< T > *)> operate)
In-order traverse of a binary tree.
Definition at line 1271 of file tree.h.
References Inorder(), BinaryTreeNode< T >::Left(), and BinaryTreeNode< T >::Right().
Referenced by Inorder().
Inorder() [2/2]
template<typename T > void Inorder (const BinaryTreeNode< T > * p, std::function< void(const BinaryTreeNode< T > *)> operate)
In-order traverse of a binary tree (const version).
Definition at line 1286 of file tree.h.
References Inorder(), BinaryTreeNode< T >::Left(), and BinaryTreeNode< T >::Right().
Postorder() [1/4]
template<typename T > void Postorder (BinaryTreeNode< T > * p, std::function< void(BinaryTreeNode< T > *)> operate)
Post-order traverse of a binary tree.
Definition at line 1302 of file tree.h.
References BinaryTreeNode< T >::Left(), Postorder(), and BinaryTreeNode< T >::Right().
Referenced by Postorder().
Postorder() [2/4]
template<typename T > void Postorder (const BinaryTreeNode< T > * p, std::function< void(const BinaryTreeNode< T > *)> operate)
Post-order traverse of a binary tree (const version).
Definition at line 1318 of file tree.h.
References BinaryTreeNode< T >::Left(), Postorder(), and BinaryTreeNode< T >::Right().
Postorder() [3/4]
template<typename T , std::size_t N> void Postorder (const TreeNode< T, N > * p, std::function< void(const TreeNode< T, N > *)> operate)
Post-order traverse of a tree (const version).
Recursively call the operate function on each child.
Definition at line 1355 of file tree.h.
References TreeNode< T, N >::get_child_pointer(), and Postorder().
Postorder() [4/4]
template<typename T , std::size_t N> void Postorder (TreeNode< T, N > * p, std::function< void(TreeNode< T, N > *)> operate)
Post-order traverse of a tree.
Recursively call the operate function on each child.
Definition at line 1334 of file tree.h.
References TreeNode< T, N >::get_child_pointer(), and Postorder().
Preorder() [1/4]
template<typename T > void Preorder (BinaryTreeNode< T > * p, std::function< void(BinaryTreeNode< T > *)> operate)
Pre-order traverse of a binary tree.
Definition at line 1153 of file tree.h.
References BinaryTreeNode< T >::Left(), Preorder(), and BinaryTreeNode< T >::Right().
Referenced by Preorder().
Preorder() [2/4]
template<typename T > void Preorder (const BinaryTreeNode< T > * p, std::function< void(const BinaryTreeNode< T > *)> operate)
Pre-order traverse of a binary tree (const version).
Definition at line 1168 of file tree.h.
References BinaryTreeNode< T >::Left(), Preorder(), and BinaryTreeNode< T >::Right().
Preorder() [3/4]
template<typename T , std::size_t N> void Preorder (const TreeNode< T, N > * p, std::function< void(const TreeNode< T, N > *)> operate)
Pre-order traverse of a tree (const version).
Recursively call the operate function on each child.
Definition at line 1224 of file tree.h.
References TreeNode< T, N >::get_child_pointer(), and Preorder().
Preorder() [4/4]
template<typename T , std::size_t N> void Preorder (TreeNode< T, N > * p, std::function< void(TreeNode< T, N > *)> operate)
Pre-order traverse of a tree.
Recursively call the function itself on each child.
Definition at line 1203 of file tree.h.
References TreeNode< T, N >::get_child_pointer(), and Preorder().
Preorder_for_memory_consumption() [1/2]
template<typename T , typename Number > void Preorder_for_memory_consumption (const BinaryTreeNode< T > * p, Number & accumulated_results)
Pre-order traverse of a binary tree and accumulate the memory consumption from each node.
Definition at line 1186 of file tree.h.
References BinaryTreeNode< T >::Left(), BinaryTreeNode< T >::memory_consumption(), Preorder_for_memory_consumption(), and BinaryTreeNode< T >::Right().
Referenced by BlockClusterTree< spacedim, Number >::memory_consumption_of_all_block_clusters(), ClusterTree< spacedim, Number >::memory_consumption_of_all_clusters(), and Preorder_for_memory_consumption().
Preorder_for_memory_consumption() [2/2]
template<typename T , std::size_t N, typename Number > void Preorder_for_memory_consumption (TreeNode< T, N > * p, Number & accumulated_results)
Pre-order traverse of a tree and accumulate the memory consumption from each node.
Recursively call the function itself on each child.
Definition at line 1248 of file tree.h.
References TreeNode< T, N >::get_child_pointer(), TreeNode< T, N >::memory_consumption(), and Preorder_for_memory_consumption().
PrintTree() [1/2]
template<typename T > void PrintTree (std::ostream & out, const BinaryTreeNode< T > * p)
Print a binary tree recursively by starting from a node.
Definition at line 1668 of file tree.h.
PrintTree() [2/2]
template<typename T , std::size_t N> void PrintTree (std::ostream & out, const TreeNode< T, N > * p)
Print a tree recursively by starting from a node.
Definition at line 1682 of file tree.h.
PrintTreeNode() [1/2]
template<typename T > void PrintTreeNode (std::ostream & out, const BinaryTreeNode< T > * p)
Print the data contained in a binary tree node.
Definition at line 1059 of file tree.h.
References BinaryTreeNode< T >::get_child_num(), BinaryTreeNode< T >::get_data_reference(), BinaryTreeNode< T >::get_level(), and BinaryTreeNode< T >::Parent().
PrintTreeNode() [2/2]
template<typename T , std::size_t N> void PrintTreeNode (std::ostream & out, const TreeNode< T, N > * p)
Print the data contained in a tree node.
Definition at line 1083 of file tree.h.
References TreeNode< T, N >::get_child_num(), TreeNode< T, N >::get_data_reference(), TreeNode< T, N >::get_level(), TreeNode< T, N >::get_split_mode(), and TreeNode< T, N >::Parent().